dotnet/winforms

src/System.Windows.Forms/src/System/Resources/ResXResourceWriter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/ButtonStandardAdapter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/GroupBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/Layout/FlowLayout.cs, src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs, src/System.Windows.Forms/src/System/Windows/Forms/TabRenderer.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
=> remove the word hack

Documentation/contributing.md, Documentation/developer-guide.md, Documentation/issue-guide.md
Winforms->WinForms
git->Git
added a note that API changes will require docs updates
=> minor edits to docs

src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
Fixes unicode issues introduced by #144
=> Fix unicode issues in comments

eng/ci.yml
=> added helix token env vars for later use

eng/ci.yml
This reverts commit 9e892c8d1ad423233870d24711da13efa3f97856.
=> Revert "added helix token env vars for later use (#132)"

pkg/Microsoft.Private.Winforms.csproj
...until we decide to use them in the WindowsDesktop package
=> comment out including resource dlls in pkg

eng/ci.yml
This reverts commit cf9f5f7a0d4bed538deb68a7b84a144bc44e44a3.
=> Revert "disable test signing for now (#206)"

eng/Versions.props, global.json, src/System.Windows.Forms/src/System.Windows.Forms.csproj
rev tools dotnet and sdk ver to preview-009820, rev pkgs to 4.6-previ…ew-18606.1, remove unnecessary system drawing primitives package
=> rev tools dotnet and sdk ver; and pkgs, remove unnecessary

.editorconfig
Some commits coming in were adding unicode not readable chars
This change should prevent that in new files / additions.
=> charset utf-8

src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.cs, src/System.Windows.Forms/tests/UnitTests/DomainUpDown.cs
- Fixed DomainUpDown navigation by up/down buttons
- Added some tests for the class
Fixes #195
=> Fixed DomainUpDown UpButton and DownButton behaviour

Documentation/winforms-designer.md
Some unicode characters in this file were not readable, also we shoudl avoid html in the markdown if there is a way to perform the same operations without it 
Changing some characters to diacritic, some to em-dash, some to apostrophe (grave accent)
=> fix unreadable unicode chars in winforms-designer.md and add images the markdown way

eng/Versions.props, src/System.Windows.Forms/src/System.Windows.Forms.csproj
=> Remove PackageReference of System.Drawing.Primitives

src/System.Windows.Forms/src/Properties/InternalsVisibleTo.cs, src/System.Windows.Forms/tests/UnitTests/DataStreamFromComStreamTests.cs
Related to discussions in https://github.com/dotnet/winforms/pull/148.
cc: @raffaeler
=> Add internals visible to Castle/Moq and create example tests.

src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.cs
Fixes #283, #284, #290 and #291
Extracted from https://github.com/dotnet/winforms/pull/285 by request
/cc @zsd4yr @sharwell
=> Fix DockPaddingEdges bugs

src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewAdvancedBorderStyle.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellStyle.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewHitTestInfo.cs, src/System.Windows.Forms/src/System/Windows/Forms/FxCopSuppression.cs, src/System.Windows.Forms/src/System/Windows/Forms/Padding.cs, src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutPanelCellPosition.cs, src/System.Windows.Forms/src/System/Windows/Forms/WinFormsUtils.cs
Fixes https://github.com/dotnet/winforms/issues/295
=> Use HashCode.Combine instead of rolling out our own hashing

eng/ci.yml
- Internal build has a banner that mentions this task is going to be required in the near future
- Info about the task is at https://docs.opensource.microsoft.com/tools/cg.html
=> Component governance detection

src/System.Windows.Forms/src/System/Windows/Forms/WinFormsUtils.cs
Extracted from https://github.com/dotnet/winforms/pull/298
=> Remove dead debug helper

src/System.Windows.Forms.Design.Editors/src/Properties/InternalsVisibleTo.cs, src/System.Windows.Forms.Design/src/Properties/InternalsVisibleTo.cs
=> internals visible set for System.Windows.Forms.Design and .Editors

src/System.Windows.Forms/ref/System.Windows.Forms.cs, src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs, src/System.Windows.Forms/tests/UnitTests/TextBox.cs
Recreating https://github.com/dotnet/winforms/pull/96
=> Added PlaceholderText functionality 

src/Common/tests/CommonTestHelper.cs, src/System.Windows.Forms/tests/UnitTests/Control.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellErrorTextNeededEventArgsTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellStyleTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewElementTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowErrorTextNeededEventArgsTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowHeightInfoNeededEventArgsTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowTests.cs, src/System.Windows.Forms/tests/UnitTests/TestHelper.cs
Depends on #308 
By no means fully comprehensive - I will submit more - but I'm busy for the next couple of days (watch as I renegade on saying that and do more work!)
=> Add DataGridViewRow/Cell tests

src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserDocumentCompletedEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserNavigatedEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserNavigatingEventArgs.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/WebBrowserDocumentCompletedEventArgsTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/WebBrowserNavigatedEventArgsTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/WebBrowserNavigatingEventArgsTests.cs
Contributes to https://github.com/dotnet/winforms/issues/40
=> Remove usages of WebPermission

Directory.Build.targets, eng/Version.Details.xml, eng/Versions.props
=> fix downgrade netcore platforms

src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs, src/System.Windows.Forms/src/System/Windows/Forms/InputLanguageChangedEventArgs.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/InputLanguageChangedEventArgsTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/InputLanguageChangingEventArgsTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/InputLanguageTests.cs
Fixes https://github.com/dotnet/winforms/issues/379
Fixes https://github.com/dotnet/winforms/issues/378
Also some code cleanup
=> Fix InputLanguage null refs and add tests

src/System.Windows.Forms/src/System/Windows/Forms/Layout/LayoutEngine.cs, src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutPanel.cs, src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutPanelCellPosition.cs, src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutSettings.cs, src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutStyleCollection.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Layout/LayoutEngineTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Layout/TableLayoutSettingsTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Layout/TableLayoutSettingsTypeConverterTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PaddingConverterTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TableLayoutControlCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TableLayoutPanelCellPositionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TableLayoutPanelTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TableLayoutStyleCollectionTests.cs
Fixes #382 
Fixes #383 
Fixes #384
Fixes #385
=> Improve validation of Table arguments

src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeCollection.cs, src/System.Windows.Forms/tests/UnitTests/TreeView.cs
Closes #358 
@manuelvalenzuela the closing comment has to go in this first message, not the PR header
=> Added CheckParentingCycle, that check for any circular reference in the ancestors chain.

Directory.Build.targets, eng/Version.Details.xml, eng/Versions.props
duel checking of #479 for release/3.0
=> fix downgrade netcore platform

src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitButton.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBindingHelperTests.cs
Depends on https://github.com/dotnet/winforms/pull/394
=> Add ListBindingHelper tests

eng/FacadeAssemblies.props, eng/Version.Details.xml, eng/Versions.props, global.json, src/Common/tests/InternalUtilitiesForTests/InternalUtilitiesForTests.csproj
=> Remove condition from Name of FacadeAssemblies.props; Also take Arcade updates for Microsoft.DotNet.GenFacades and Microsoft.DotNet.XUnitExtensions

src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
I removed double spaces and double semi-colon in the ContolPaint.cs.
=> Fix formatting issues in file.

src/System.Windows.Forms/src/System/Resources/ResXResourceWriter.cs, src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXFileRef.ConverterTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXFileRefTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceWriterTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Resources/ResxDataNodeTests.cs
=> Remove comment header from ResXResourceWriter output

src/System.Windows.Forms/src/System/Windows/Forms/AnchorStyles.cs, src/System.Windows.Forms/src/System/Windows/Forms/Appearance.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.cs, src/System.Windows.Forms/src/System/Windows/Forms/ArrangeDirection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ArrangeStartingPosition.cs, src/System.Windows.Forms/src/System/Windows/Forms/ArrowDirection.cs, src/System.Windows.Forms/src/System/Windows/Forms/AutoCompleteMode.cs, src/System.Windows.Forms/src/System/Windows/Forms/AutoCompleteSource.cs, src/System.Windows.Forms/src/System/Windows/Forms/AutoScaleMode.cs, src/System.Windows.Forms/src/System/Windows/Forms/AutoSizeMode.cs, src/System.Windows.Forms/src/System/Windows/Forms/AutoValidate.cs, src/System.Windows.Forms/src/System/Windows/Forms/Automation/AutomationLiveSetting.cs, src/System.Windows.Forms/src/System/Windows/Forms/Automation/AutomationNotificationKind.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/HighDpiMode.cs
=> Cleanup enums [A]

src/System.Windows.Forms/src/System/Windows/Forms/Binding.cs, src/System.Windows.Forms/src/System/Windows/Forms/BindingsCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ControlBindingsCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListManagerBindingsCollection.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BindingManagerBaseTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BindingsCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlBindingsCollectionTests.cs
Fixes #553
Fixes #544
Fixes #543
=> Add BindingCollection tests and fix resultant bugs

src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DockPaddingEdgesTests.cs
=>  Cleanup DockPaddingEdges and add some Reset* tests

src/System.Windows.Forms/src/System/Windows/Forms/BindingSource.cs
Best reviewed commit-by-commit :)
=> Cleanup BindingSource

.github/ISSUE_TEMPLATE/localization_request.md, Documentation/contributing.md
=> new issue template for localization, small edit to contribution guidelines

eng/ci.yml
For now, run all tests on build machines
unblocks #593
=> unblock issue with helix

eng/Version.Details.xml, eng/Versions.props, global.json
=> Revert "[master] Update dependencies from dotnet/coreclr"

Directory.Build.props, eng/Version.Details.xml, eng/Versions.props, eng/common/PublishToPackageFeed.proj, eng/common/init-tools-native.ps1, eng/common/templates/job/publish-build-assets.yml, eng/common/templates/steps/send-to-helix.yml, global.json, pkg/Microsoft.Private.Winforms.csproj
=> Revert "[master] Update dependencies from dotnet/arcade"

src/System.Windows.Forms/src/System/Windows/Forms/BatteryChargeStatus.cs, src/System.Windows.Forms/src/System/Windows/Forms/BootMode.cs, src/System.Windows.Forms/src/System/Windows/Forms/Border3DSide.cs, src/System.Windows.Forms/src/System/Windows/Forms/Border3DStyle.cs, src/System.Windows.Forms/src/System/Windows/Forms/BorderStyle.cs, src/System.Windows.Forms/src/System/Windows/Forms/BoundsSpecified.cs, src/System.Windows.Forms/src/System/Windows/Forms/ButtonBorderStyle.cs, src/System.Windows.Forms/src/System/Windows/Forms/ButtonState.cs, src/System.Windows.Forms/src/System/Windows/Forms/CaptionButton.cs, src/System.Windows.Forms/src/System/Windows/Forms/CharacterCasing.cs, src/System.Windows.Forms/src/System/Windows/Forms/CloseReason.cs, src/System.Windows.Forms/src/System/Windows/Forms/ColumnHeaderAutoResizeStyle.cs, src/System.Windows.Forms/src/System/Windows/Forms/ColumnHeaderStyle.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBoxStyle.cs, src/System.Windows.Forms/src/System/Windows/Forms/ControlStyles.cs, src/System.Windows.Forms/src/System/Windows/Forms/ControlUpdateMode.cs, src/System.Windows.Forms/src/System/Windows/Forms/PowerLineStatus.cs, src/System.Windows.Forms/src/System/Windows/Forms/PowerState.cs, src/System.Windows.Forms/src/System/Windows/Forms/PowerStatus.cs
=> Cleanup enums [B-C]

src/System.Windows.Forms/src/System/Windows/Forms/ErrorBlinkStyle.cs, src/System.Windows.Forms/src/System/Windows/Forms/ErrorIconAlignment.cs, src/System.Windows.Forms/src/System/Windows/Forms/FixedPanel.cs, src/System.Windows.Forms/src/System/Windows/Forms/FlatStyle.cs, src/System.Windows.Forms/src/System/Windows/Forms/FlowDirection.cs, src/System.Windows.Forms/src/System/Windows/Forms/FormBorderStyle.cs, src/System.Windows.Forms/src/System/Windows/Forms/FormStartPosition.cs, src/System.Windows.Forms/src/System/Windows/Forms/FormWindowState.cs, src/System.Windows.Forms/src/System/Windows/Forms/FrameStyle.cs, src/System.Windows.Forms/src/System/Windows/Forms/GDI/TextFormatFlags.cs, src/System.Windows.Forms/src/System/Windows/Forms/GetChildAtPointSkip.cs, src/System.Windows.Forms/src/System/Windows/Forms/GridItemType.cs, src/System.Windows.Forms/src/System/Windows/Forms/HelpNavigator.cs, src/System.Windows.Forms/src/System/Windows/Forms/HorizontalAlignment.cs, src/System.Windows.Forms/src/System/Windows/Forms/HtmlElement.cs, src/System.Windows.Forms/src/System/Windows/Forms/HtmlElementInsertionOrientation.cs, src/System.Windows.Forms/src/System/Windows/Forms/IMEMode.cs, src/System.Windows.Forms/src/System/Windows/Forms/ImageLayout.cs, src/System.Windows.Forms/src/System/Windows/Forms/InsertKeyMode.cs, src/System.Windows.Forms/src/System/Windows/Forms/ItemActivation.cs, src/System.Windows.Forms/src/System/Windows/Forms/ItemBoundsPortion.cs, src/System.Windows.Forms/src/System/Windows/Forms/Keys.cs
=> Cleanup enums [E-I]

src/System.Windows.Forms/src/System/Windows/Forms/LeftRightAlignment.cs, src/System.Windows.Forms/src/System/Windows/Forms/LinkBehavior.cs, src/System.Windows.Forms/src/System/Windows/Forms/LinkState.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewAlignment.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewHitTestLocation.cs, src/System.Windows.Forms/src/System/Windows/Forms/MDILayout.cs, src/System.Windows.Forms/src/System/Windows/Forms/MaskFormat.cs, src/System.Windows.Forms/src/System/Windows/Forms/MenuGlyph.cs, src/System.Windows.Forms/src/System/Windows/Forms/MenuMerge.cs, src/System.Windows.Forms/src/System/Windows/Forms/MergeAction.cs, src/System.Windows.Forms/src/System/Windows/Forms/MessageBoxButtons.cs, src/System.Windows.Forms/src/System/Windows/Forms/MessageBoxDefaultButton.cs, src/System.Windows.Forms/src/System/Windows/Forms/MessageBoxIcon.cs, src/System.Windows.Forms/src/System/Windows/Forms/MessageBoxOptions.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs, src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs, src/System.Windows.Forms/src/System/Windows/Forms/Orientation.cs, src/System.Windows.Forms/src/System/Windows/Forms/PictureBoxSizeMode.cs, src/System.Windows.Forms/src/System/Windows/Forms/PreProcessControlState.cs, src/System.Windows.Forms/src/System/Windows/Forms/ProgressBarStyle.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertySort.cs, src/System.Windows.Forms/src/System/Windows/Forms/UnhandledExceptionMode.cs
=> Cleanup enums [L-P]

src/System.Windows.Forms/src/System/Windows/Forms/RichTextBoxFinds.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBoxLanguageOptions.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBoxScrollBars.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBoxSelectionAttribute.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBoxSelectionTypes.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBoxStreamType.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBoxWordPunctuations.cs, src/System.Windows.Forms/src/System/Windows/Forms/ScreenOrientation.cs, src/System.Windows.Forms/src/System/Windows/Forms/ScrollBars.cs, src/System.Windows.Forms/src/System/Windows/Forms/ScrollButton.cs, src/System.Windows.Forms/src/System/Windows/Forms/SearchDirectionHint.cs, src/System.Windows.Forms/src/System/Windows/Forms/SecurityIDType.cs, src/System.Windows.Forms/src/System/Windows/Forms/SelectionMode.cs, src/System.Windows.Forms/src/System/Windows/Forms/Shortcut.cs, src/System.Windows.Forms/src/System/Windows/Forms/SizeGripStyle.cs, src/System.Windows.Forms/src/System/Windows/Forms/SizeType.cs, src/System.Windows.Forms/src/System/Windows/Forms/SortOrder.cs, src/System.Windows.Forms/src/System/Windows/Forms/StatusBarPanelAutoSize.cs, src/System.Windows.Forms/src/System/Windows/Forms/StatusBarPanelBorderStyle.cs, src/System.Windows.Forms/src/System/Windows/Forms/StatusBarPanelStyle.cs, src/System.Windows.Forms/src/System/Windows/Forms/SystemParameter.cs, src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutSettings.cs
=> Cleanup enums [R-S]

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionItemCollection.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionListCollection.cs, src/System.Windows.Forms.Design/tests/UnitTests/DesignerActionItemCollectionTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/DesignerActionListCollectionTests.cs
Fixes #609 
Components copied from framework.
=> Port DesignerAction*Collection components

src/System.Windows.Forms/src/System/Windows/Forms/PropertyManager.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyManagerTests.cs
=>  Add PropertyManager tests

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/Microsoft.Dotnet.Winforms.ProjectTemplates.csproj, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/.template.config/dotnetcli.host.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/Company.WinFormsApplication1.vbproj, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/Form1.Designer.vb, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/Form1.resx, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/Form1.vb, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/xlf/Form1.cs.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/xlf/Form1.de.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/xlf/Form1.es.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/xlf/Form1.fr.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/xlf/Form1.it.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/xlf/Form1.ja.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/xlf/Form1.ko.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/xlf/Form1.pl.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/xlf/Form1.pt-BR.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/xlf/Form1.ru.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/xlf/Form1.tr.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/xlf/Form1.zh-Hans.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/xlf/Form1.zh-Hant.xlf
fixes #689
The `Form1.resx` file and `xlf` folder are copied from C# template.
=> Add Visual Basic template

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/Form1.Designer.cs, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/Form1.cs
fixes #679
/cc @vatsan-madhavan and @chabiss
=> Make C# Project template for WinForms identical to the .NET Framework version of the corresponding template

src/System.Windows.Forms/src/System/Windows/Forms/BindingContext.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BindingContextTests.cs
=> Add BindingContext tests

src/System.Windows.Forms/src/System/Windows/Forms/FeatureSupport.cs, src/System.Windows.Forms/src/System/Windows/Forms/OSFeature.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FeatureSupportTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/OSFeatureTests.cs
=> Add FeatureSupport/OSFeature tests and fix bug

src/System.Windows.Forms/src/System/Windows/Forms/Menu.cs, src/System.Windows.Forms/src/System/Windows/Forms/MenuItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/tests/UnitTests/MenuItemTests.cs
=> Cleanup MenuItem and add param names

Directory.Build.props, Directory.Build.targets
This should be the last bit of the cycle to close
=> Set TargetingPackVersion intentionally

src/System.Windows.Forms/src/System/Windows/Forms/BindToObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/Binding.cs
I'm going to do a bit of refactoring to cleanup things up, but here are the formatting changes first :)
(already tested)
=>  Cleanup Binding/BindToObject

src/System.Windows.Forms.Design/src/Resources/SR.resx, src/System.Windows.Forms.Design/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializationProvider.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializer.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerBase.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CollectionCodeDomSerializer.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ComponentCodeDomSerializer.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ComponentTypeCodeDomSerializer.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ContainerCodeDomSerializer.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/EnumCodeDomSerializer.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/EventMemberCodeDomSerializer.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/PrimitiveCodeDomSerializer.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/PropertyMemberCodeDomSerializer.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourceCodeDomSerializer.cs, src/System.Windows.Forms.Design/tests/UnitTests/Serialization/CollectionCodeDomSerializerTests.cs
fixes #827 
/cc @DustinCampbell
=> Port Coded Dom Serializer Provider and related types

src/System.Windows.Forms.Design.Editors/src/System/Drawing/Design/ImageEditor.cs
Extracted from (and tested in) #810
=> Cleanup ImageEditor

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
Added unit test to check ComboBox item accessible object doesn't throw an exception
=> Added unit test for ComboBox

src/Common/tests/CommonTestHelper.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/System/Windows/Forms/Design/FolderNameEditorTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/UndoUnitTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/Drawing/Design/ToolboxItemTests.cs, src/System.Windows.Forms/src/System/Windows/Forms/Binding.cs, src/System.Windows.Forms/tests/UnitTests/MenuItemCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/MenuItemTests.cs, src/System.Windows.Forms/tests/UnitTests/MenuTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BindingTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ColumnHeaderCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ColumnHeaderTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellStyleTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/GridItemTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HelpProviderTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/LinkTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItemTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewSubItemCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewSubItemTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TimerTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemTests.cs
Fixes #864 
Fixes #862 
Fixes #863 
Fixes #861
=> Add tests for Binding without a control

src/System.Windows.Forms/src/System/Windows/Forms/DataGrid.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridColumnStyle.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/DataGridColumnHeaderAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridColumnStyleTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridTableStyleTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/GridColumnStylesCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/GridTableStylesCollectionTests.cs
=> Add DataGridColumnStyle tests

src/System.Windows.Forms/src/System/Windows/Forms/Design/EventsTab.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/EventsTabTests.cs
Fixes #960
Fixes #899
contributes to #817
=> Add EventsTab tests, cleanup and fix bugs

eng/ci.yml
Relates to: https://github.com/dotnet/core-eng/issues/6291
=> ci.yml params should be External / Public settings

Documentation/porting-guidelines.md
@OliaG we should probably also add current understood guidance on what to do about multiple app domains, what to do about assembly loader and metadata load context, etc...
=> Add link to apis of .net link to porting guidelines

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerHost.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignSurfaceTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignerHostTests.cs
Fixes #964
Fixes #963
Fixes #962
Fixes #946
=> Add DesignerHost/DesignSurface tests and fix bugs

src/System.Windows.Forms.Design.Editors/src/Misc/NativeMethods.cs, src/System.Windows.Forms.Design.Editors/src/Resources/SR.resx, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms.Design.Editors/src/System.Windows.Forms.Design.Editors.csproj, src/System.Windows.Forms.Design.Editors/src/System/ComponentModel/Design/MultilineStringEditor.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/MultilineStringEditorTests.cs
=> port multiline string editor

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/DesignerSerializationManager.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/Serialization/DesignerSerializationManagerTests.cs
=> Add DesignerSerializationManager tests and fix bug

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/DesignerSerializationManager.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/Serialization/DesignerSerializationManagerTests.cs
=> Fix infinite looping in DesignerSerializationManager.GetType

src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupCollection.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupCollectionTests.cs
=>  Fix missing validation in ListViewGroupCollection.Insert

src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/Resources/System/Windows/Forms/xlf/PrintPreviewDialog.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
=> LOC CHECKIN | dotnet/winforms master | 20190522

src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItemTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewSubItemCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewSubItemTests.cs
=>  Reset the owner of ListViewSubItem when removing from ListViewSubItemCollection

src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupCollection.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupCollectionTests.cs
=> Fix assignment and validation of ListViewGroupCollection.Item setter

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/VisualStyles/VisualStyleInformationTests.cs
Extracted from https://github.com/dotnet/winforms/pull/1012
=> Add VisualStyleInformation tests

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerHost.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ExtenderProviderService.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/HostDesigntimeLicenseContext.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/SiteNestedContainer.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignSurfaceTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignerHostTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ExtenderProviderServiceTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/SiteNestedContainerTests.cs
=> Add more DesignerHost related tests, remove Debug.Asserts and fix a NRE bug

Directory.Build.props, src/Common/tests/InternalUtilitiesForTests/InternalUtilitiesForTests.csproj, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms.Design/tests/UnitTests/System.Windows.Forms.Design.Tests.csproj, src/System.Windows.Forms/src/System.Windows.Forms.csproj, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/WinformsControlsTest.csproj, src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj
=> Update LangVersion to preview

src/System.Design/src/ApiCompatBaseline.netcoreapp.txt, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionHeaderItem.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionTextItem.cs
This is public in System.Design.dll
=> Make DesignerActionHeaderItem public

src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
I understand that this is not enabled in winforms and actually isn't supported in .NET Core
=> Remove Click Once code

src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewMethods.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/DataGridViewAccessibleObjectTests.cs
=> Accessibility: Fixing ItemStatus property in programmatically sorted DataGridView

src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/CheckedListBoxAccessibleObjectTests.cs
=> Accessibility: Fixing BoundingRectangle value for CheckedListBox entries

src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
=> Remove Contract.Requires()

.github/PULL_REQUEST_TEMPLATE.md
That's how it will look when a PR is opened:
=> Add a GitHub pull request template

Directory.Build.props, src/System.Windows.Forms/tests/UnitTests/ButtonTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
Closes #254
- configure `ProductName` property
- manual
- unit tests
=> fix: Incorrect ProductName property

src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
=> Fixing mouse-move selection of ComboBox current item text

.github/PULL_REQUEST_TEMPLATE.md
Added the following content:
Microsoft prioritizes making our products accessible. WinForms has a key role in allowing developers to create accessible apps. When submitting a change which impacts UI in any way, including adding new UI or modifying existing controls the developer needs to run the [Accessibility Insights](https://accessibilityinsights.io/) tool and verify that there are no changes or regressions. The developer should run the [Fast Pass](https://accessibilityinsights.io/docs/en/web/getstarted/fastpass) over the impacted control(s) and provide a snapshot of the passing results along with before/after snapshots of the UI.
=> Add Accessibility Insights info into PR Template

src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
=> Add TreeNode tests and fix some NREs

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ComponentDesignerTests.cs
Closes #989
- Copy the behaviour as provided by NET Fx.
- Cleanup remove duplicated code and invert `if`s to reduce nesting
=> Fix 989 implement PreFilterAttributes and PreFilterEvents events

src/Common/tests/TraceListenerlessContext.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/EventHandlerService.cs, src/System.Windows.Forms.Design/tests/UnitTests/System.Windows.Forms.Design.Tests.csproj, src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/EventHandlerServiceTests.cs
Fixes #988
- Port `EventHandlerService` from NET Fx
- Cleanup the code to adhere to the current set of guidelines and language constructs 
- Add tests
- unit tests
=> Fix 988 Port EventHandlerService

src/Common/tests/CommonTestHelper.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/System/ComponentModel/Design/ArrayEditorTests.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/System/ComponentModel/Design/CollectionEditorTests.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/System/Drawing/Design/BitmapEditorTests.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/System/Drawing/Design/FontEditorTests.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/System/Drawing/Design/FontNameEditorTests.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/System/Drawing/Design/ImageEditorTests.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/System/Drawing/Design/MetafileEditorTests.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/System/Windows/Forms/Design/FileNameEditorTests.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/System/Windows/Forms/Design/FolderNameEditorTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Drawing/Design/UITypeEditorTests.cs
=> Improve editor tests

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ComponentDesignerTests.cs
Fixes #1259
Fixes #1260
Fixes #1261
Fixes #1262
Fixes #1263
=> Add more ComponentDesigner tests and fix some bugs

src/System.Windows.Forms.Design.Editors/src/System/ComponentModel/Design/MultilineStringEditor.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/System/ComponentModel/Design/MultilineStringEditorTests.cs
=> Add MultilineStringEditor tests and fix some bugs

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignSurface.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerHost.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignSurfaceTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignerActionListCollectionTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignerHostTests.cs
=> Add more DesignHost/Surface tests, remove dead code and fix NRE bug

src/System.Windows.Forms.Design.Editors/src/System/Drawing/Design/CursorEditor.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/System/Drawing/Design/CursorEditorTests.cs
=> Add CursorEditor tests and fix bugs

src/System.Windows.Forms.Design.Editors/src/System/ComponentModel/Design/ObjectSelectorEditor.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/System/ComponentModel/Design/ObjectSelectorEditorTests.cs
=> Add ObjectSelectorEditor tests and fix a bug

src/System.Windows.Forms.Design.Editors/src/System/Drawing/Design/ColorEditor.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/System/Drawing/Design/ColorEditorTests.cs
=> Add ColorEditor tests and fix some bugs

src/System.Windows.Forms.Design.Editors/src/System/Windows/Forms/Design/ShortcutKeysEditor.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/System/Windows/Forms/Design/ShortcutKeysEditorTests.cs
=> Add ShortcutKeysEditor tests and fix some bugs

src/System.Windows.Forms.Design.Editors/src/System/Windows/Forms/Design/BorderSidesEditor.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/System/Windows/Forms/Design/BorderSidesEditorTests.cs
=> Add BorderSidesEditor tests and fix some bugs

src/System.Windows.Forms.Design.Editors/src/System/Windows/Forms/Design/AnchorEditor.cs, src/System.Windows.Forms.Design.Editors/src/System/Windows/Forms/Design/DockEditor.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/System/Windows/Forms/Design/AnchorEditorTests.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/System/Windows/Forms/Design/DockEditorTests.cs
=> More editor tests

src/System.Windows.Forms/src/System/Windows/Forms/HScrollProperties.cs, src/System.Windows.Forms/src/System/Windows/Forms/ScrollProperties.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollPropertiesTests.cs
=> Fix ScrollProperties NREs without parent

src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
=> Add Control.Site tests and fix an InvalidCastException

src/System.Windows.Forms.Design.Editors/src/System/Drawing/Design/FontNameEditor.cs
Fixes #1176 and fixes #1177
cc @RussKie
=> Remove obsolete attributes

src/System.Windows.Forms/src/Resources/System/Windows/Forms/xlf/PrintPreviewDialog.cs.xlf, src/System.Windows.Forms/src/Resources/System/Windows/Forms/xlf/PrintPreviewDialog.de.xlf, src/System.Windows.Forms/src/Resources/System/Windows/Forms/xlf/PrintPreviewDialog.es.xlf, src/System.Windows.Forms/src/Resources/System/Windows/Forms/xlf/PrintPreviewDialog.fr.xlf, src/System.Windows.Forms/src/Resources/System/Windows/Forms/xlf/PrintPreviewDialog.it.xlf, src/System.Windows.Forms/src/Resources/System/Windows/Forms/xlf/PrintPreviewDialog.ja.xlf, src/System.Windows.Forms/src/Resources/System/Windows/Forms/xlf/PrintPreviewDialog.ko.xlf, src/System.Windows.Forms/src/Resources/System/Windows/Forms/xlf/PrintPreviewDialog.pl.xlf, src/System.Windows.Forms/src/Resources/System/Windows/Forms/xlf/PrintPreviewDialog.pt-BR.xlf, src/System.Windows.Forms/src/Resources/System/Windows/Forms/xlf/PrintPreviewDialog.ru.xlf, src/System.Windows.Forms/src/Resources/System/Windows/Forms/xlf/PrintPreviewDialog.tr.xlf, src/System.Windows.Forms/src/Resources/System/Windows/Forms/xlf/PrintPreviewDialog.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/System/Windows/Forms/xlf/PrintPreviewDialog.zh-Hant.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
Fixes #
Localization update
- 
- 
- 
- 
- 
- 
-
=> LOC CHECKIN | dotnet/winforms master | 20190717

src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorPage.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/ComponentEditorPageTests.cs
=> Add ComponentEditorPage tests and fix some bugs

src/Common/tests/CommonTestHelper.cs, src/System.Windows.Forms/src/System/Windows/Forms/Panel.cs, src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PanelTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollableControlTests.cs
=> Add more Panel/ScrollableControl tests and fix a bug

src/Common/src/ClientUtils.cs, src/System.Windows.Forms.Design/src/System/Drawing/Design/ToolboxItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/BindingContext.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2TypeInfoProcessor.cs, src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGrid.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnDesignTimeVisibleAttribute.cs, src/System.Windows.Forms/src/System/Windows/Forms/HtmlDocument.cs, src/System.Windows.Forms/src/System/Windows/Forms/HtmlElement.cs, src/System.Windows.Forms/src/System/Windows/Forms/HtmlWindow.cs, src/System.Windows.Forms/src/System/Windows/Forms/KeyboardToolTipStateMachine.cs, src/System.Windows.Forms/src/System/Windows/Forms/Layout/ArrangedElementCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.cs, src/System.Windows.Forms/src/System/Windows/Forms/LinkArea.cs, src/System.Windows.Forms/src/System/Windows/Forms/Padding.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/Screen.cs, src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutPanelCellPosition.cs, src/System.Windows.Forms/src/misc/GDI/DeviceContext.cs, src/System.Windows.Forms/src/misc/GDI/WindowsFont.cs, src/System.Windows.Forms/src/misc/WeakHashtable.cs
- Prefer HashCode.Combine
- Use expression body members where possible
- Cleanup associated code
=> Simplify hashcodes across winforms

src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewBand.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumn.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
Just use the `IsRow` setter and simplify the check
Follow-up to #1390
=> Remove DataGridViewBand._bandIsRow

src/System.Windows.Forms/src/System/Windows/Forms/DataGrid.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridTable.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridTableStyle.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridColumnStyleTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridTableStyleTests.cs
Fixes #1372 
Fixes #1378
Fixes #1379
Fixes #1380
=> Add DataGridTableStyle tests and fix some bugs

src/Common/tests/CommonTestHelper.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ContainerControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HScrollBarTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/InputLanguageChangedEventArgsTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/InputLanguageChangingEventArgsTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PanelTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollBarTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollableControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/VScrollBarTests.cs
=> Add more ContainerControl tests, cleanup ContainerControl and fix an NRE

Documentation/testing-in-vs.md, Documentation/testing.md
=> adding docs for common problems running tests through visual studio

eng/FacadeAssemblies.props, eng/Version.Details.xml, eng/Versions.props, eng/common/init-tools-native.ps1, eng/common/init-tools-native.sh, eng/common/pipeline-logging-functions.sh, eng/common/tools.ps1, eng/common/tools.sh, global.json
Update Arcade to Build: 20190722.10
Replaces https://github.com/dotnet/winforms/pull/1422
=> [master] Manually update dependencies from dotnet/arcade

eng/configure-toolset.ps1
See:
* https://github.com/dotnet/arcade/pull/3315
* https://github.com/dotnet/wpf/pull/1339
Resolves #1389
=> Suppress warnings generated by native-tools installation

src/Common/src/FileDialog_Vista_Interop.cs, src/Common/src/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Label.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
=> Remove remaining FXCop references

src/System.Windows.Forms/src/System/Windows/Forms/HelpProvider.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HelpProviderTests.cs
=> Fix HelpProvider argument validation parameter names

src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/tests/UnitTests/InteropTests/SysInfoTests.cs
=> fixing CLI build (#pragma warning restore)

src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolTipTests.cs
=> Fix ToolTip.ToString typo

src/Common/src/CommonUnsafeNativeMethods.cs, src/Common/src/Interop/Interop.Errors.cs, src/Common/src/Interop/Interop.Libraries.cs, src/Common/src/Interop/Kernel32/Interop.FreeLibrary.cs, src/Common/src/Interop/Kernel32/Interop.GetModuleHandle.cs, src/Common/src/Interop/Kernel32/Interop.GetProcAddress.cs, src/Common/src/Interop/Kernel32/Interop.LoadLibrary.cs, src/Common/src/Interop/Kernel32/Interop.MAX_PATH.cs, src/Common/src/Interop/Shell32/Interop.SHBrowseForFolder.cs, src/Common/src/Interop/Shell32/Interop.SHGetSpecialFolderLocation.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design.Editors/src/Misc/CommonUnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CodeMarkers.cs, src/System.Windows.Forms/src/System.Windows.Forms.csproj, src/System.Windows.Forms/src/System/Windows/Forms/Application.cs, src/System.Windows.Forms/src/System/Windows/Forms/ColorDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/FontDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/MessageBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBoxConstants.cs, src/System.Windows.Forms/src/System/Windows/Forms/SendKeys.cs
=> Consolidate and cleanup pinvokes for loading libraries/dlls

src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
Fixes #
- Localization update
- 
- 
- 
- 
- 
-
=> LOC CHECKIN | dotnet/winforms master | 20190726

src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignerHostTests.cs
- Skip unstable tests
Closes #1460
Relates to #1151
=> Skip unstable tests

eng/Versions.props
Rebrand master to `preview9 `as part of Preview8 completion
=> Rebrand master to preview9

src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests/WinformsControlsTest.cs
Fixes #540
Passes on my machine
=> Enable WinformsControlsTest_TreeViewAndImageListTest

src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignerHostTests.cs
=> Skip more flakey tests

src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/MenuItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/SplitContainer.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs, src/System.Windows.Forms/src/System/Windows/Forms/ThreadExceptionDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
Rename events and properties in Control to match coding guidelines
No
None
N/A
=> Cleanup Control event and property naming

src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
Fixes #1615 
- Disabling visual styles for ToolTip control in High Contrast mode as Visual Styles prevent setting colors for ToolTip background and text in TTM_SETTIPBKCOLOR and TTM_SETTIPTEXTCOLOR (please see https://docs.microsoft.com/en-us/windows/win32/controls/ttm-settipbkcolor and https://docs.microsoft.com/en-us/windows/win32/controls/ttm-settiptextcolor
- Visual styles are disabled only for ToolTips and only in HC mode.
- Disabling visual styles for a control is usually performed in OnHandleCreated handler. I've put it just after _window.CreateHandle(cp); call.
- With the fix available customers with visual impairments may observe more contrasted tooltips in WinForms apps.
- No
- Minimal
- Awaiting QA sign-off.
- Color contrast analyzer tools show enough contrast …
=> Fix 1615: Disabling ToolTip visual styles to make it enough contrasted in HC mode.

eng/ci.yml
Going to merge this in without review since we need to unblock the build.
=> disable sdl validation until the arcade team fixes it, since it's blocking the build

azure-pipelines.yml, eng/ci.yml
=> change agent pools to deal with recent build delays

eng/ci.yml
Does not affect shipping bits, very low risk. Going to merge it in without build since the step being changed is internal-build-only.
=> re-enable sdl runs and fix some params

azure-pipelines.yml
Does not affect customers or shipping bits. Very low risk.
Merging without build since this change only runs on internal builds.
=> change internal agent pool

src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/ShortcutKeysEditor.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
Fixes #
- Localization update
- 
- 
- 
- 
- Yes / No
-
- 
- 
- 
-
=> LOC CHECKIN | dotnet/winforms master | 20190902

src/Common/src/Interop/User32/Interop.BeginPaint.cs, src/Common/src/Interop/User32/Interop.EndPaint.cs, src/Common/src/Interop/User32/Interop.InvalidateRect.cs, src/Common/src/Interop/User32/Interop.PAINTSTRUCT.cs, src/Common/src/Interop/User32/Interop.RedrawWindow.cs, src/Common/src/NativeMethods.cs, src/Common/src/SafeNativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design.Editors/src/Misc/NativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerFrame.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormDocumentDesigner.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.cs, src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs, src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ItemAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
=> Cleanup RedrawWindow/InvalidateRect interop

src/Common/src/Interop/Ole32/Interop.IEnumVariant.cs, src/Common/src/Interop/OleAut32/Interop.IEnumVariant.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design.Editors/src/Misc/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
-  Cleanup IEnumVariant interface
- Fix crashes if parameters are null
- More solid, more performant
- No
- Minimal
- Existing tests
=> Cleanup IEnumVariant

eng/Versions.props
=> Update Release/3.0 branding for release candidate 2

src/System.Windows.Forms/tests/UnitTests/MenuItemTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ContainerControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/ComponentEditorPageTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FlowLayoutPanelTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HScrollBarTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PanelTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PictureBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollBarTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollableControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/VScrollBarTests.cs
- Add more Control/AxHost tests
- Focused around the open PRs right now to get a little more coverage
=> Add more Control/AxHost tests

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/Microsoft.Dotnet.Winforms.ProjectTemplates.csproj, pkg/Microsoft.Private.Winforms/Microsoft.Private.Winforms.csproj
=> [release/3.0] Mark transport packages as non-shipping

src/System.Windows.Forms/tests/IntegrationTests/WinFormsControlsClassicTests/WinFormsControlsClassicTests.csproj, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/FormBorderStyles.Designer.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/FormBorderStyles.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/FormBorderStyles.resx, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.Designer.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/FormBorderStyles.cs.xlf, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/FormBorderStyles.de.xlf, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/FormBorderStyles.es.xlf, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/FormBorderStyles.fr.xlf, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/FormBorderStyles.it.xlf, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/FormBorderStyles.ja.xlf, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/FormBorderStyles.ko.xlf, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/FormBorderStyles.pl.xlf, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/FormBorderStyles.pt-BR.xlf, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/FormBorderStyles.ru.xlf, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/FormBorderStyles.tr.xlf, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/FormBorderStyles.zh-Hans.xlf, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/FormBorderStyles.zh-Hant.xlf
- Add tests for manual verification of `Form.FormBorderStyle` functionality which were created as part of #1338 verification.
- None
- No
- None
=> Tests `FormBorderStyles`

src/Common/src/Interop/User32/Interop.HELPINFO.cs, src/Common/src/Interop/User32/Interop.HELPINFOENUM.cs, src/Common/src/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- Match interop guidelines
- Convert to struct
=> Structify HELPINFO

src/Common/src/Interop/Gdi32/Interop.GetTextMetricsW.cs, src/Common/src/Interop/Gdi32/Interop.TEXTMETRICW.cs, src/Common/src/Interop/Gdi32/Interop.TMPF.cs, src/Common/src/NativeMethods.cs, src/Common/src/SafeNativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerUtils.cs, src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/TextMetricsPitchAndFamilyValues.cs, src/System.Windows.Forms/src/misc/GDI/NativeMethods.cs, src/System.Windows.Forms/src/misc/GDI/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/misc/GDI/WindowsFont.cs, src/System.Windows.Forms/src/misc/GDI/WindowsGraphics2.cs
- Consolidate common code
- Follow Interop guidelines
=> Cleanup TEXTMETRICW interop

src/Common/src/Interop/User32/Interop.MINMAXINFO.cs, src/Common/src/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
- Turn MINMAXINFO into a struct
- Follow interop guidelines
=> Structify MINMAXINFO

src/System.Windows.Forms/src/System/Resources/ResXFileRef.cs
Related to #889 
removed attribute and methods that I missed in PR #1251 
Thank you to @RussKie for the feedback!
code clean up
- Yes / **No**
Low, private methods that are never called
- 
- 
- 
-
=> Cleaned up ResxFileRef

src/Common/src/Interop/Ole32/Interop.IOleInPlaceObject.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserSiteBase.cs
- Cleanup IOleInPlaceObject
- Use PreserveSig in more places
=> Cleanup IOleInPlaceObject

.gitattributes
dev experience enhancement
set git attributes to collapse .xlf files when viewing PRs
=> Collapse XLF files in PRs by default

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ContainerControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridTableStyleTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/ComponentEditorPageTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FlowLayoutPanelTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HScrollBarTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PanelTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PictureBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollBarTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollableControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/VScrollBarTests.cs
- Add more Control tests
- Add ListView construction tests
=> Add some ListView tests and more Control tests

src/Common/src/Interop/Comdlg32/Interop.PSD.cs, src/Common/src/Interop/Comdlg32/Interop.PageSetupDlgW.cs, src/Common/src/Interop/Interop.Libraries.cs, src/Common/src/Interop/User32/Interop.WNDPROC.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Printing/PageSetupDialog.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PageSetupDialogTests.cs
- Cleanup PageSetupDialog: interop, code style, auto properties
- Add PageSetupDialog tests
=> Cleanup PageSetupDialog and add tests

src/Common/src/Interop/Ole32/Interop.IGetOleObject.cs, src/Common/src/Interop/OleAut32/Interop.IExtender.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
- Cleanup IExtender
- Cleanup IGetOleObject
=> Cleanup IExtender/IGetOleObject

README.md
* Add badges for build pipeline for release/3.1
* remove badges for test and all code code coverage
* add section for code coverage in release/3.1
=> Add badges for 3.1 release build pipeline and also the code cov of 3.1

src/Common/src/Interop/Ole32/Interop.IFont.cs, src/Common/src/Interop/Ole32/Interop.IFontDisp.cs, src/Common/src/Interop/Ole32/Interop.IPicture.cs, src/Common/src/Interop/OleAut32/Interop.FONTDESC.cs, src/Common/src/Interop/OleAut32/Interop.OleCreateFontIndirect.cs, src/Common/src/NativeMethods.cs, src/Common/src/SafeNativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2FontConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXFontMarshaler.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserHelper.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs
- Cleanup IFont related interop code
- Add IFont/IPicture tests
=> Cleanup IFont related interop

src/Common/src/Interop/SHDocVw/Interop.CSC.cs, src/Common/src/Interop/SHDocVw/Interop.DWebBrowserEvents2.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PictureBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/WebBrowserTests.cs
- Cleanup DWebBrowserEvents2
- Add some WebBrowser tests
=> Cleanup DWebBrowserEvents2 and add some WebBrowser tests

eng/Versions.props
=> Prep'ing for 3.0.1 set the next patch release to 3.0.1

src/Common/tests/CommonTestHelper.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridTableStyleTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PanelTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
=> Add more Control/ListView related tests

src/Common/src/Interop/ComCtl32/Interop.LVFI.cs, src/Common/src/Interop/ComCtl32/Interop.LVFINDINFOW.cs, src/Common/src/Interop/ComCtl32/Interop.NMLVFINDITEMW.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
- Turn into structs
- Follow interop guidelines
=> Structify and cleanup LVFINDINFOW/NMLVFINDITEMW

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs
The issues are tracked in
* https://github.com/dotnet/winforms/issues/2002
* https://github.com/dotnet/winforms/issues/2003
* https://github.com/dotnet/winforms/issues/2004
* https://github.com/dotnet/winforms/issues/2005
=> Disable the flaky tests

src/Common/src/Interop/User32/Interop.GetCaretBlinkTime.cs, src/Common/src/Interop/User32/Interop.HideCaret.cs, src/Common/src/Interop/User32/Interop.ShowCaret.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/SystemInformation.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs
- Cleanup `ShowCaret`
- Cleanup `HideCaret`
- Cleanup `GetCaretBlinkTime`
=> Cleanup Caret interop

src/Common/src/Interop/Ole32/Interop.DISPPARAMS.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2AboutBoxPropertyDescriptor.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/ComNativeDescriptor.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/HtmlDocument.cs, src/System.Windows.Forms/src/System/Windows/Forms/HtmlElement.cs
- Structify `DISPPARAMS`
- Cleanup `IDispatch.GetTypeInfoCount` and `IDispatch.Invoke` interop
=> Structify DISPPARAMS

src/System.Windows.Forms.Design.Editors/src/Resources/xlf/ShortcutKeysEditor.zh-Hant.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
Fixes #
- Loc update
- 
- 
- 
- 
- Yes / No
-
- 
- 
- 
-
=> LOC CHECKIN | dotnet/winforms release/3.1 | 20191004

src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/StatusBar.cs
Fixes #1504 (Dual monitor dialog resize issue). See the issue thread for details.
=> Fix: Dual monitor dialog resize issue (#1504)

src/Common/src/Interop/Ole32/Interop.CAUUID.cs, src/Common/src/Interop/Ole32/Interop.ISpecifyPropertyPages.cs, src/Common/src/NativeMethods.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2ComponentEditor.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyPageUITypeConverter.cs
- Structify CAUUID
- Cleanup ISpecifyPropertyPages: add PreserveSig and harden against invalid pointers
=> Structify CAUUID

src/System.Windows.Forms/tests/UnitTests/CheckedListBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/MonthCalendarTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PictureBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
- Add more Control tests related to methods/properties by `MonthCalendar`
- Add `MonthCalendar` tests
=> Add MonthCalendar tests

src/Common/src/Interop/ComCtl32/Interop.LVIS.cs, src/Common/src/NativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
- Extract LVIS_ constants to Interop.ComCtl32
=> Extract LVIS_ constants

src/Common/src/Interop/Gdi32/Interop.GetNearestColor.cs, src/System.Windows.Forms/src/misc/GDI/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/misc/GDI/WindowsGraphics2.cs
=> Cleanup GetNearestColor

Directory.Build.props, eng/ci.yml
=> set EmbedUntrackedSources to embed SR files into the PDB in order to satisfy SourceLink check

src/Common/src/Interop/User32/Interop.PostQuitMessage.cs, src/Common/src/Interop/User32/Interop.WaitMessage.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.ComponentManager.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs
- Cleanup WaitMessage
- Cleanup PostQuitMessage
=> Cleanup WaitMessage/PostQuitMessage

src/Common/src/Interop/User32/Interop.MWMO.cs, src/Common/src/Interop/User32/Interop.MsgWaitForMultipleObjectsEx.cs, src/Common/src/Interop/User32/Interop.QS.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.ComponentManager.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
- Cleanup MsgWaitForMultipleObjectsEx
- Cleanup QS_ constants
- Cleanup MWM_ constants
=> Cleanup MsgWaitForMultipleObjectsEx

src/Common/src/Interop/User32/Interop.DEVMODEW.cs, src/Common/src/Interop/User32/Interop.DM.cs, src/Common/src/Interop/User32/Interop.ENUM.cs, src/Common/src/Interop/User32/Interop.EnumDisplaySettingsW.cs, src/Common/src/NativeMethods.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/SystemInformation.cs
- Change to unicode
- Cleanup definition (use enums etc)
=> Cleanup DEVMODE interop

src/Common/src/Interop/Interop.ERROR.cs, src/Common/src/Interop/Kernel32/Interop.LoadLibrary.cs, src/Common/src/Interop/User32/Interop.CloseDesktop.cs, src/Common/src/Interop/User32/Interop.DESKTOP.cs, src/Common/src/Interop/User32/Interop.DF.cs, src/Common/src/Interop/User32/Interop.OpenInputDesktop.cs, src/Common/src/NativeMethods.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/SystemInformation.cs
- Cleanup User32.OpenInputDesktop
- Cleanup User32.CloseDesktop
=> Cleanup OpenInputDesktop/CloseDesktop

Documentation/designer-releases/0.1/knownissues.md
Non-Code change. Just updating the instructions to link to the script that turns PLM on/off and resets settings for the first release. We'll update again as soon as we've got the public release with UI that enables/disables instead of feature flags
=> Fix link to PLM zip

src/Common/src/Interop/ComCtl32/Interop.NMLISTVIEW.cs, src/Common/src/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
=> Cleanup NMLISTVIEW

src/Common/src/Interop/OleAut32/Interop.OleCreatePropertyFrame.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2ComponentEditor.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyPageUITypeConverter.cs
- Consolidate overloads
- Cleanup interop to avoid array allocation
=> Cleanup OleCreatePropertyFrame

src/Common/src/Interop/Comdlg32/Interop.CC.cs, src/Common/src/Interop/Comdlg32/Interop.ChooseColorW.cs, src/Common/src/NativeMethods.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms.Design.Editors/src/Misc/NativeMethods.cs, src/System.Windows.Forms.Design.Editors/src/System.Windows.Forms.Design.Editors.csproj, src/System.Windows.Forms.Design.Editors/src/System/Drawing/Design/ColorEditor.cs, src/System.Windows.Forms/src/System/Windows/Forms/ColorDialog.cs
- Cleanup and structify ChooseColor
=> Cleanup ChooseColor

src/Common/src/Interop/Richedit/Interop.REQRESIZE.cs, src/Common/src/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
- Structify REQRESIZE
- Move to Richedit namespace
=> Structify REQRESIZE

src/Common/src/Interop/ComCtl32/Interop.HICF.cs, src/Common/src/Interop/ComCtl32/Interop.NMTBHOTITEM.cs, src/Common/src/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolBar.cs
- Move NMTBHOTITEM to Interop
- Cleanup enums
=> Cleanup NMTBHOTITEM

src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
Fixes #
- Loc update
- 
- 
- 
- 
- Yes / No
-
- 
- 
- 
-
=> LOC CHECKIN | dotnet/winforms release/3.1 | 20191015

src/System.Windows.Forms.Design.Editors/tests/UnitTests/EnsureEditorsTests.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/System.Windows.Forms.Design.Editors.Tests.csproj, src/System.Windows.Forms/src/System/Drawing/Design/UITypeEditor.cs
=> Add associations to previous ported editors and add meta test for editors

src/System.Windows.Forms.Design.Editors/tests/UnitTests/EnsureEditorsTests.cs
=> better editors tests

src/Common/src/NativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2TypeInfoProcessor.cs
- Consolidate tagVT into VARENUM
=> Cleanup tagVT enum

src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
Fixes #1976 
Original bug:
- [Bug 820332:](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/820332) Accessibility: [MAS42A] [HC 1/Black]: The no row-data area’s background is black in DGV on HC 1/Black theme
- Change DefaultBackgroundBrush to `SystemBrushes.ControlDark` instead `SystemBrushes.AppWorkspace`
**High contrast is observed in all themes. 
DataGridView has one color in all HC themes when the background is black (HC1, HC2, HC Black)**
- Changed UI colors. DataGridView background color is dark gray now in HC1, HC2 and HC Black themes 
- Changed HC2 DataGridView empty area background color
- No
- .NET Core Version: 3.1.0-preview1.19458.7
- Microsoft Windows [Version 10.0.18362.356]
=> [Accessibility][HC]: Fixing DataGridView background color in HC themes

src/Common/src/Interop/Ole32/Interop.OLEMENUGROUPWIDTHS.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserContainer.cs
- Structify OLEMENUGROUPWIDTHS
- Cleanup use in interfaces
=> Cleanup OLEMENUGROUPWIDTHS

src/Common/src/Interop/Gdi32/Interop.ETO.cs, src/Common/src/Interop/Gdi32/Interop.ExtTextOutW.cs, src/Common/src/Interop/Gdi32/Interop.LineTo.cs, src/Common/src/Interop/Gdi32/Interop.MoveToEx.cs, src/Common/src/Interop/Gdi32/Interop.Rectangle.cs, src/Common/src/Interop/Gdi32/Interop.RoundRect.cs, src/Common/src/NativeMethods.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerUtils.cs, src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs, src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.cs, src/System.Windows.Forms/src/misc/GDI/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/misc/GDI/WindowsGraphics2.cs
- Cleanup ExtTextOutW interop
- Cleanup LineTo Interop
- Cleanup MoveToEx
- Cleanup Rectangle
=> Cleanup Gdi32 drawing apis

.gitattributes, src/System.Windows.Forms.Design.Editors/src/Misc/DpiHelper.cs, src/System.Windows.Forms.Design.Editors/src/Resources/SR.resx, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms.Design.Editors/src/System/Drawing/Design/ContentAlignmentEditor.ContentUI.cs, src/System.Windows.Forms.Design.Editors/src/System/Drawing/Design/ContentAlignmentEditor.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/EnsureEditorsTests.cs, src/System.Windows.Forms/src/System/Drawing/Design/UITypeEditor.cs
=> Port ContentAlignmentEditor; add test for it

src/Common/src/Interop/ComCtl32/Interop.MCMV.cs, src/Common/src/Interop/ComCtl32/Interop.NMVIEWCHANGE.cs, src/Common/src/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
- Structify NMVIEWCHANGE
- Cleanup NMVIEWCHANGE interop
=> Structify NMVIEWCHANGE

src/Common/src/Interop/Ole32/Interop.IOleInPlaceActiveObject.cs, src/Common/src/Interop/Ole32/Interop.IOleInPlaceUIWindow.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserContainer.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserSiteBase.cs
- Cleanup IOleInPlaceActiveObject
- Cleanup IOleInPlaceUIWindow
=> Cleanup IOleInPlaceActiveObject and IOleInPlaceUIWindow interop

src/Common/src/Interop/Gdi32/Interop.GetViewportExtEx.cs, src/Common/src/Interop/Gdi32/Interop.GetViewportOrgEx.cs, src/Common/src/Interop/Gdi32/Interop.SetViewportExtEx.cs, src/Common/src/Interop/Gdi32/Interop.SetViewportOrgEx.cs, src/Common/src/Interop/Gdi32/Interop.SetWindowExtEx.cs, src/Common/src/Interop/Gdi32/Interop.SetWindowOrgEx.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/WinFormsUtils.cs, src/System.Windows.Forms/src/misc/GDI/DeviceContext2.cs, src/System.Windows.Forms/src/misc/GDI/UnsafeNativeMethods.cs
- Cleanup SetWindowExtEx/SetWindowOrgEx
- Cleanup GetViewportOrgEx/SetViewportOrgEx
- Cleanup GetViewportExtEx/SetViewportExtEx
=> Cleanup Gdi32 Ext/Org interop

src/Common/src/Interop/ComCtl32/Interop.GDT.cs, src/Common/src/Interop/ComCtl32/Interop.NMDATETIMECHANGE.cs, src/Common/src/Interop/ComCtl32/Interop.NMDAYSTATE.cs, src/Common/src/Interop/ComCtl32/Interop.NMSELCHANGE.cs, src/Common/src/Interop/Kernel32/Interop.SYSTEMTIME.cs, src/Common/src/Interop/User32/Interop.MCM.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
- Cleanup SYSTEMTIME
- Cleanup NMDATETIMECHANGE
- Cleanup NMDAYSTATE
- Cleanup NMSELCHANGE
=> Cleanup SYSTEMTIME and dependencies

src/Common/src/Interop/Ole32/Interop.CALLCONV.cs, src/Common/src/Interop/Ole32/Interop.DESCKIND.cs, src/Common/src/Interop/Ole32/Interop.FUNCFLAGS.cs, src/Common/src/Interop/Ole32/Interop.FUNCKIND.cs, src/Common/src/Interop/Ole32/Interop.IDLFLAG.cs, src/Common/src/Interop/Ole32/Interop.IMPLTYPEFLAG.cs, src/Common/src/Interop/Ole32/Interop.INVOKEKIND.cs, src/Common/src/Interop/Ole32/Interop.PARAMFLAG.cs, src/Common/src/Interop/Ole32/Interop.TYPEKIND.cs, src/Common/src/Interop/Ole32/Interop.VARFLAGS.cs, src/Common/src/Interop/Ole32/Interop.VARKIND.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2TypeInfoProcessor.cs
- Cleanup Ole32 enums (extracted from #1961)
=> Cleanup Ole32 enums

src/Common/tests/CommonTestHelper.cs, src/System.Windows.Forms/tests/UnitTests/MonthCalendarTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridTableStyleTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItemTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewSubItemTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
- Add more TabControl tests
- Add more Control tests
=> Add TabControl tests

src/Common/src/Interop/Richedit/Interop.TEXTRANGE.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
=> Structify TEXTRANGE

eng/ci.yml
Fixes #2149 
- Fix the TSA bug area path
- None
- No
- None
- Arcade has tested this
=> fix tsa bug area path

src/System.Windows.Forms/tests/UnitTests/ContextMenuTests.cs, src/System.Windows.Forms/tests/UnitTests/MainMenuTests.cs, src/System.Windows.Forms/tests/UnitTests/MenuTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
- Add more Control tests
- Add more related ContextMenu/MainMenu/Menu tests
=> Add Control dialog/input/key/menu tests

src/Common/src/Interop/Gdi32/Interop.BitBlt.cs, src/Common/src/Interop/Gdi32/Interop.CreateCompatibleBitmap.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerUtils.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
- Cleanup CreateCompatibleBitmap
- Cleanup BitBlt
=> Cleanup CreateCompatibleBitmap/BitBlt

eng/ci.yml
Ports https://github.com/dotnet/winforms/pull/2150 to release/3.1 to unblock the preview2 builds.
CC @AdamYoblick @RussKie
=> Fix SDL validation in rel/3.1

eng/ci.yml
- Move SDL validation parameters to azdo variable group to allow us to change them without the need for a PR
- None
- No
- None
=> move sdl validation parameters to azdo variable group

src/Common/src/Interop/User32/Interop.SetParent.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerFrame.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.ParkingWindow.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
=> Cleanup SetParent interop

src/Common/src/NativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs
- Remove ClassStyle enum and replace usages with CS enum values.
=> Remove ClassStyle enum

src/Common/src/Interop/User32/Interop.ARW.cs, src/Common/src/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ArrangeDirection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ArrangeStartingPosition.cs
- Add ARW enum.
- Remove ARW constants and replace their usages with the above enum.
=> Add ARW enum and remove ARW constants

src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlPaintTests.cs
=> Add ControlPaint tests

src/Common/src/Interop/User32/Interop.DrawTextEx.cs, src/System.Windows.Forms/src/misc/GDI/DeviceContext.cs, src/System.Windows.Forms/src/misc/GDI/WindowsGraphics.cs, src/System.Windows.Forms/src/misc/GDI/WindowsGraphics2.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextRendererTests.cs
=> Add TextRenderer tests

src/Common/src/Interop/Imm32/Interop.GCS.cs, src/Common/src/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.cs
- Add GCS enum.
- Replace GCS constants with the values from the above enum.
=> Add GCS enum and remove GCS constants

src/System.Windows.Forms/src/System/Windows/Forms/ProgressBar.cs
- Rename `ProgressBar` fields
- Follow coding guidelines in `ProgressBar`
Tested by #2141
=> Cleanup ProgressBar code

src/System.Windows.Forms/src/System/Windows/Forms/CheckBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/Command.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGrid.cs, src/System.Windows.Forms/src/System/Windows/Forms/MenuStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitButton.cs
They should be on their own lines
=> Cleanup formatting of EventHandler invokes

src/Common/src/Interop/Gdi32/Interop.AdjustWindowRectEx.cs, src/Common/src/Interop/Gdi32/Interop.AdjustWindowRectExForDpi.cs, src/Common/src/Interop/Gdi32/Interop.LPtoDP.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- Cleanup AdjustWindowRectEx/AdjustWindowRectExForDpi
- Cleanup LPToDp
=> Cleanup AdjustWindowRectEx and friends

src/Common/src/Interop/User32/Interop.GetClientRect.cs, src/Common/src/SafeNativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/GroupBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/StatusStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.cs
- Cleanup GetClientRect interop
=> Cleanup GetClientRect interop

src/Common/src/Interop/Gdi32/Interop.LOGPALETTE.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
=> Structify LOGPALETTE

src/Common/src/Interop/User32/Interop.IsChild.cs, src/Common/src/SafeNativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs, src/System.Windows.Forms/src/System/Windows/Forms/UserControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.cs
=> Cleanup IsChild interop

src/Common/src/Interop/ComCtl32/Interop.LVGIT.cs, src/Common/src/Interop/ComCtl32/Interop.NMLVCACHEHINT.cs, src/Common/src/Interop/ComCtl32/Interop.NMLVGETINFOTIPW.cs, src/Common/src/Interop/ComCtl32/Interop.NMLVKEYDOWN.cs, src/Common/src/Interop/ComCtl32/Interop.NMLVODSTATECHANGE.cs, src/Common/src/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
- Structify NMLVKEYDOWN
- Structify NMLVCACHEHINT
- Cleanup NMLVODSTATECHANGE
- Structify NMLVGETINFOTIPW
=> Structify more ListView messages

src/Common/src/Interop/Ole32/Interop.IOleInPlaceSite.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.OleInterfaces.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserSiteBase.cs
=> Cleanup IOleInPlaceSite

src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
=> Remove dead code from Control.PerformLayout

src/Common/src/Interop/User32/Interop.GetParent.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.ParkingWindow.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserSiteBase.cs
=> Cleanup GetParent interop

src/Common/src/Interop/User32/Interop.GetParent.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.ControlCollection.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Handlers.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Properties.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
- Add `ControlCollection` tests
=> Add ControlCollection tests

src/Common/src/Interop/Ole32/Interop.CONTROLINFO.cs, src/Common/src/Interop/Ole32/Interop.CTRLINFO.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
- Structify CONTROLINFO
- Make CTRLINFO_ constants into enum
- Cleanup IOleControl interface
=> Structify CONTROLINFO

src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
=> Consolidate IsWindowUnicode interop

src/Common/src/Interop/User32/Interop.MapWindowPoints.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ComponentTray.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripAdornerWindowService.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripDesigner.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs, src/System.Windows.Forms/src/System/Windows/Forms/StatusStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolBar.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs, src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs, src/System.Windows.Forms/src/System/Windows/Forms/WinFormsUtils.cs
=> Cleanup MapWindowPoints interop

src/Common/src/Interop/ComCtl32/Interop.LVIF.cs, src/Common/src/Interop/ComCtl32/Interop.NMLISTVIEW.cs, src/Common/src/NativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
- Cleanup LVIF_ constants
- Remove LVITEM.Reset
=> Cleanup LVIF constants

src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
=> Rename TabPage fields

src/Common/src/Interop/Ole32/Interop.IOleControl.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
- Move IOleControl interface to Ole32
=> Cleanup IOleControl interface

src/Common/src/Interop/Ole32/Interop.EXCEPINFO.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.PropertyBagStream.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2AboutBoxPropertyDescriptor.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/ComNativeDescriptor.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/HtmlDocument.cs, src/System.Windows.Forms/src/System/Windows/Forms/HtmlElement.cs
=> Structify EXCEPINFO

src/Common/src/Interop/User32/Interop.EnableWindow.cs, src/Common/src/Interop/User32/Interop.IsWindowEnabled.cs, src/Common/src/Interop/User32/Interop.IsWindowVisible.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms.Design.Editors/src/Misc/NativeMethods.cs, src/System.Windows.Forms.Design.Editors/src/System.Windows.Forms.Design.Editors.csproj, src/System.Windows.Forms.Design.Editors/src/System/Drawing/Design/ColorEditor.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadWindows.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs
- Cleanup `IsWindowEnabled`
- Cleanup `IsWindowVisible`
- Cleanup `EnableWindow`
=> Cleanup IsWindowEnabled/IsWindowVisible/EnableWindow

src/Common/src/Interop/Ole32/Interop.DVTARGETDEVICE.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
=> Structify DVTARGETDEVICE

src/Common/src/Interop/Ole32/Interop.QACONTAINER.cs, src/Common/src/Interop/Ole32/Interop.QACONTAINERFLAGS.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- Cleanup QACONTAINER
- Cleanup QACONTAINER_ flags
=> Cleanup QACONTAINER

src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignerHostTests.cs
related to #2325 
Changed test name to match the new expected result, this is a follow up change to #2326
=> renamed test to match the expected result

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
- Delete unnecessary new test that is failing randomly: we don't need this really as it tests the layout of a TreeView to a slightly specific and clearly variable level
=> Fix flakey tests

src/Common/src/Interop/ComCtl32/Interop.TVS.cs, src/Common/src/Interop/ComCtl32/Interop.TVS_EX.cs, src/Common/src/NativeMethods.cs, src/System.Windows.Forms.Design.Editors/src/Misc/NativeMethods.cs, src/System.Windows.Forms.Design.Editors/src/System.Windows.Forms.Design.Editors.csproj, src/System.Windows.Forms.Design.Editors/src/System/ComponentModel/Design/ObjectSelectorEditor.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerUtils.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
=> Cleanup TVS_ constants

src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Handlers.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Properties.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
=> Add more Control tests

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
=> Add more ListView tests

src/Common/src/NativeMethods.cs, src/Common/src/SafeNativeMethods.cs
=> Cleanup TrackPopupMenuEx interop

src/Common/src/Interop/ComCtl32/Interop.TCIF.cs, src/Common/src/Interop/ComCtl32/Interop.TCIS.cs, src/Common/src/Interop/ComCtl32/Interop.TCITEMW.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/TabControl.ControlCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.ControlCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.TabPageCollectionTests.cs
=> Structify TCITEM

src/Common/src/Interop/Ole32/Interop.POINTERINACTIVE.cs, src/Common/src/Interop/Ole32/Interop.QACONTROL.cs, src/Common/src/Interop/Ole32/Interop.VIEWSTATUS.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
=> Structify QACONTROL

src/Common/src/ExternDll.cs, src/Common/src/Interop/Imm32/Interop.CPS.cs, src/Common/src/Interop/Imm32/Interop.IME_CMODE.cs, src/Common/src/Interop/Imm32/Interop.IME_SMODE.cs, src/Common/src/Interop/Imm32/Interop.ImmAssociateContext.cs, src/Common/src/Interop/Imm32/Interop.ImmCreateContext.cs, src/Common/src/Interop/Imm32/Interop.ImmGetContext.cs, src/Common/src/Interop/Imm32/Interop.ImmGetConversionStatus.cs, src/Common/src/Interop/Imm32/Interop.ImmGetOpenStatus.cs, src/Common/src/Interop/Imm32/Interop.ImmNotifyIME.cs, src/Common/src/Interop/Imm32/Interop.ImmReleaseContext.cs, src/Common/src/Interop/Imm32/Interop.ImmSetConversionStatus.cs, src/Common/src/Interop/Imm32/Interop.ImmSetOpenStatus.cs, src/Common/src/Interop/Imm32/Interop.NI.cs, src/Common/src/Interop/Interop.Libraries.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design.Editors/src/Misc/ExternDll.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs, src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.cs
=> Cleanup Imm32 interop

azure-pipelines.yml
=> Subscribe to MSRC on internal CI

azure-pipelines.yml, eng/Versions.props
=> Switch to non-stable

src/Common/src/Interop/Ole32/Interop.IConnectionPoint.cs, src/Common/src/Interop/Ole32/Interop.IConnectionPointContainer.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.ConnectionPointCookie.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHost.ConnectionPointCookieTests.cs
- Cleanup IConnectionPoint interface
=> Cleanup IConnectionPoint interface

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ProfessionalColorTableTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ProfessionalColorsTests.cs
- Add ProfessionalColors tests
=> Add ProfessionalColors tests

src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Handlers.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Properties.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PictureBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.TabPageControlCollection.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs
- Add TabPage tests
- Add and improve other Control tests
=> Add more tests

src/Common/src/Interop/Comdlg32/Interop.OFNOTIFYW.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
=> Structify OFNOTIFYW

src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
=> Remove SYSTEMTIMEARRAY

src/Common/src/Interop/User32/Interop.ActivateKeyboardLayout.cs, src/Common/src/Interop/User32/Interop.GetKeyboardLayout.cs, src/Common/src/Interop/User32/Interop.GetKeyboardLayoutList.cs, src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/InputLanguageTests.cs
- Cleanup InputLanguage interop
=> Cleanup InputLanguage interop

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PanelTests.cs
=> Add more Panel tests

src/Common/src/Interop/Ole32/Interop.IQuickActivate.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- Move IQuickActivate to Ole32
=> Move IQuickActivate to Ole32

NuGet.config
=> Update feeds for tooling and .net 3

NuGet.config
=> Fix dotnet-eng feed to actually point to dotnet-eng.

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/Microsoft.Dotnet.Winforms.ProjectTemplates.csproj, pkg/Microsoft.Private.Winforms/Microsoft.Private.Winforms.csproj
=> suppress nuget package generation warnings NU5131 and NU5128 (#2373)

src/Common/src/Interop/ComCtl32/Interop.LVBKIF.cs, src/Common/src/Interop/ComCtl32/Interop.LVBKIMAGEW.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
=> Cleanup LVBKIMAGEW

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FontDialogTests.cs
=> Add FontDialog tests

src/Common/src/Interop/User32/Interop.UIS.cs, src/Common/src/Interop/User32/Interop.UISF.cs, src/Common/src/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/tests/UnitTests/MonthCalendarTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ContainerControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Properties.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/ComponentEditorPageTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FlowLayoutPanelTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HScrollBarTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PanelTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PictureBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ProgressBarTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollBarTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollableControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripPanelTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/VScrollBarTests.cs
- Cleanup UIS and UISF cues
- Add ShowFocusCues/ShowKeyboardCues tests
=> Cleanup UIS and UISF cues and add ShowFocusCues/ShowKeyboardCues tests 

src/System.Windows.Forms/tests/UnitTests/ButtonTests.cs, src/System.Windows.Forms/tests/UnitTests/CheckBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/DateTimePickerTests.cs, src/System.Windows.Forms/tests/UnitTests/LabelTests.cs, src/System.Windows.Forms/tests/UnitTests/RadioButtonTests.cs, src/System.Windows.Forms/tests/UnitTests/RichTextBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ButtonBaseTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ContainerControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/ComponentEditorPageTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FlowLayoutPanelTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HScrollBarTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PictureBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ProgressBarTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollBarTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollableControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripPanelTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolTipTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/VScrollBarTests.cs, src/System.Windows.Forms/tests/UnitTests/TextBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/TrackBarTests.cs
- Add ComCtl32 control tests
- Fix a debug assert failure
=> Add ComCtl32 control tests and fix a debug assert failure

src/Common/src/Interop/Gdi32/Interop.PatBlt.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.cs, src/System.Windows.Forms/src/System/Windows/Forms/SplitContainer.cs, src/System.Windows.Forms/src/System/Windows/Forms/Splitter.cs
=> Cleanup PatBlt interop

src/Common/src/Interop/User32/Interop.GetMonitorInfoW.cs, src/Common/src/Interop/User32/Interop.MONITORINFOEXW.cs, src/Common/src/Interop/User32/Interop.MONITORINFOF.cs, src/Common/src/NativeMethods.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Screen.cs
=> Cleanup MONITORINFOEX

src/Common/src/Interop/Comdlg32/Interop.CF.cs, src/Common/src/NativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/FontDialog.cs
=> Cleanup CF_ constants

src/Common/src/Interop/Gdi32/Interop.CreateDIBSection.cs, src/Common/src/Interop/Gdi32/Interop.CreateHalftonePalette.cs, src/Common/src/Interop/Gdi32/Interop.DIB.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
- Cleanup CreateHalftonePalette
- Cleanup CreateDIBSection
=> Cleanup ControlPaint interop

azure-pipelines.yml, eng/Versions.props
Remove stabilize package version block. winforms never stabilizes
=> [release/3.0] Add internal/release/* ci triggers

eng/ci.yml
Bring ci.yml's SDL config in line with 3.1
=> Update area paths to be like 3.1

src/System.Windows.Forms/tests/UnitTests/CheckBoxTests.cs
=> Add tests to verify joint behaviours pertaining to `ThreeState`, `CheckState` and `Checked`

src/Common/src/Interop/User32/Interop.ValidateRect.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs, src/System.Windows.Forms.Design/tests/UnitTests/ControlDesignerTests.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
- Cleanup ValidateRect
- Add tests to cover affected components
=> Cleanup ValidateRect and add tests for affected components

src/Common/src/Interop/User32/Interop.WA.cs, src/Common/src/NativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionUI.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs
- Add WA enum to User32
- Remove the corresponding constants and replace their usages with the above enum.
=> Add WA enum to User32

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ColorDialogTests.cs
=> Add ColorDialog tests

src/System.Windows.Forms/src/System/Windows/Forms/PaintEventArgs.cs, src/System.Windows.Forms/src/misc/GDI/WindowsGraphics.cs, src/System.Windows.Forms/tests/UnitTests/GroupBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Handlers.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
- Add GroupBox tests and related Control methods
=> Add GroupBox tests and related Control methods

src/Common/src/Interop/User32/Interop.WindowFromPoint.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CommandSet.cs, src/System.Windows.Forms/src/System/Windows/Forms/Button.cs, src/System.Windows.Forms/src/System/Windows/Forms/CheckBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/RadioButton.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs, src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs
- Cleanup WindowFromPoint interop
=> Cleanup WindowFromPoint interop

src/Common/src/Interop/User32/Interop.UpdateWindow.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.cs
- Cleanup UpdateWindow interop
=> Cleanup UpdateWindow interop

src/Common/src/Interop/Ole32/Interop.USERCLASSTYPE.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- Cleanup `IOleObject` interface
=> Cleanup IOleObject interface

src/Common/src/Interop/Ole32/Interop.IEnumOLEVERB.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXVerbEnum.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- Move `IEnumOLEVERB` to interop
=> Move IEnumOLEVERB to interop

global.json
=> [release/3.1] Move to RTM sdk

src/Common/src/Interop/User32/Interop.GetDpiForWindow.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs
- Cleanup GetDpiForWindow and add tests
=> Cleanup GetDpiForWindow and add tests

src/Common/src/Interop/Ole32/Interop.RegisterDragDrop.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropTargetManager.cs
=> Make RegisterDragDrop IHandle

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollableControlTests.cs
- Add more ScrollableControl tests
=> Add more ScrollableControl tests

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/NativeWindowTests.cs
=> Add NativeWindow tests

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Properties.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.ControlCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.TabPageCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs
Extracted from https://github.com/dotnet/winforms/pull/2465
=> Add misc TabControl related tests

src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.ControlCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.TabPageCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs
- This was never set in #2258 
Contributes to https://github.com/dotnet/winforms/issues/2462
=> Fix Tab Control Text and add more TabControl tests

Directory.Build.props, Directory.Build.targets, codecov.yml, eng/CodeCoverage.proj, eng/Versions.props, eng/ci.yml
=> Update code coverage integration

src/Common/src/Interop/User32/Interop.GetWindowRect.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/CommonDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.cs, src/System.Windows.Forms/src/System/Windows/Forms/SplitContainer.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
- Cleanup GetWindowRect interop
=> Cleanup GetWindowRect interop

Documentation/designer-releases/readme.md
=> Updated the link to the latest blogpost

src/Common/src/Interop/Gdi32/Interop.BI.cs, src/Common/src/Interop/Gdi32/Interop.BITMAPINFO.cs, src/Common/src/Interop/Gdi32/Interop.BITMAPINFOHEADER.cs, src/Common/src/Interop/Gdi32/Interop.GetDIBits.cs, src/Common/src/Interop/Gdi32/Interop.StretchDIBits.cs, src/Common/src/NativeMethods.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.MetafileDCWrapper.cs, src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
- Cleanup BITMAPINFOHEADER interop
- Cleanup BITMAPINFO interop
- Cleanup GetDIBits
- Cleanup CreateDIBSection
- Cleanup StretchDIBits
=> Cleanup DIB related interop

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Properties.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemTests.cs
- Add ToolStripItem tests and tests for related components
=> Add ToolStripItem tests and tests for related components

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
- Remove always undefined SELECTEDCHANGED
=> Remove always undefined SELECTEDCHANGED

src/Common/src/Interop/VSSDK/Interop.IVSMDPerPropertyBrowsing.cs, src/Common/src/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IManagedPerPropertyBrowsingHandler.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2Properties.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/ComNativeDescriptor.cs
- Cleanup IVSMDPerPropertyBrowsing interface
See https://docs.microsoft.com/en-us/dotnet/api/microsoft.visualstudio.designer.interfaces.ivsmdperpropertybrowsing?view=visualstudiosdk-2017
=> Cleanup IVSMDPerPropertyBrowsing interface

src/Common/src/Interop/ComCtl32/Interop.MCM.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Handlers.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
- Don't create Handle in MonthCalendar.OnHandleCreate (#2235)
=> Don't create Handle in MonthCalendar.OnHandleCreated

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CommonDialogTests.cs
- Fix some coverage gaps in CommonDialog
=> Fix some coverage gaps in CommonDialog

src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/VisualStyles/VisualStyleRendererTests.cs
- Should be `IsHandleCreated`
Fixes #2219
=> Correct handle check in VisualStyleRenderer.DrawParentBackground

src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Properties.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
- Add ToolStrip tests and related tests
=> Add ToolStrip tests and related tests

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/SplitterPanelTests.cs
=> Add SplitterPanel tests

src/Common/src/Interop/ComCtl32/Interop.ImageList.Draw.cs, src/Common/src/Interop/ComCtl32/Interop.ImageList.Remove.cs, src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageList.ImageCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageListTests.cs
=> Fix ImageList stack overflows

src/Common/src/NativeMethods.cs
=> Remove IMAGELISTDRAWPARAMS

src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutControlCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutPanel.cs
- Extract TableLayoutControlCollection from TableLayoutPanel.cs
=> Extract TableLayoutControlCollection from TableLayoutPanel.cs

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BaseCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewSelectedCellCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewSelectedColumnCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewSelectedRowCollectionTests.cs
- Add DataGridView selected collection tests
=> Add DataGridView selected collection tests

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSeparator.ToolStripSeparatorAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSeparator.cs
=> Cleanup ToolStripSeparator

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSeparator.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripSeparatorTests.cs
- Add ToolStripSeparator tests
=> Add ToolStripSeparator tests

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripButtonTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemTests.cs
=> Add ToolStripButton tests

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ColumnStyleTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RowStyleTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TableLayoutStyleTests.cs
- Improve ColumnStyle/Row/TableLayout style tests
=> Improve ColumnStyle/Row/TableLayout style tests

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Handlers.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripControlHostTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemTests.cs
- Add ToolStripControlHost tests
=> Add ToolStripControlHost tests

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/ComponentEditorPageTests.cs
- Cleanup and improve ComponentEditorPage testing
=> Cleanup and improve ComponentEditorPage testing

src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
- Remove dead SetSelectionInCreateHandle flag
=> Remove dead SetSelectionInCreateHandle flag

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FlowLayoutPanelTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FlowLayoutSettingsTests.cs
- Improve tests for FlowLayoutPanel/FlowLayoutSettings
=> Improve tests for FlowLayoutPanel/FlowLayoutSettings

src/Common/src/Interop/UxTheme/Interop.TMT.cs, src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/BooleanProperty.cs, src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/ColorProperty.cs, src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/EnumProperty.cs, src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/FilenameProperty.cs, src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/FontProperty.cs, src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/IntegerProperty.cs, src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/MarginProperty.cs, src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/PointProperty.cs, src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/StringProperty.cs
- Add more TMT enum values.
- Use them in the VisualStyles enums.
=> Add more TMT enum values

src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripButton.ToolStripButtonAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripButton.cs
=> Cleanup ToolStripButton

src/System.Windows.Forms/src/System/Windows/Forms/ButtonRenderer.cs, src/System.Windows.Forms/src/System/Windows/Forms/CheckBoxRenderer.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBoxRenderer.cs, src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs, src/System.Windows.Forms/src/System/Windows/Forms/GDI/TextRenderer.cs, src/System.Windows.Forms/src/System/Windows/Forms/GroupBoxRenderer.cs, src/System.Windows.Forms/src/System/Windows/Forms/Help.cs, src/System.Windows.Forms/src/System/Windows/Forms/ProfessionalColors.cs, src/System.Windows.Forms/src/System/Windows/Forms/ProgressBarRenderer.cs, src/System.Windows.Forms/src/System/Windows/Forms/RadioButtonRenderer.cs, src/System.Windows.Forms/src/System/Windows/Forms/ScrollBarRenderer.cs, src/System.Windows.Forms/src/System/Windows/Forms/TabRenderer.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextBoxRenderer.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs, src/System.Windows.Forms/src/System/Windows/Forms/TrackBarRenderer.cs
- Make sealed classes with private constructors static
=> Make sealed classes with private constructors static

src/System.Windows.Forms/src/System/Windows/Forms/SplitterPanel.cs
=> Cleanup SplitterPanel

src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ControlAccessibleObjectTests.cs
- Add ControlAccessibleObject tests
=> Add ControlAccessibleObject tests

src/Common/src/Interop/User32/Interop.ID.cs, src/Common/src/Interop/User32/Interop.MB.cs, src/Common/src/Interop/User32/Interop.MessageBoxW.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms.Design.Editors/src/Misc/NativeMethods.cs, src/System.Windows.Forms.Design.Editors/src/System.Windows.Forms.Design.Editors.csproj, src/System.Windows.Forms.Design.Editors/src/System/Drawing/Design/ColorEditor.cs, src/System.Windows.Forms/src/System/Windows/Forms/MessageBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/MessageBoxButtons.cs, src/System.Windows.Forms/src/System/Windows/Forms/MessageBoxDefaultButton.cs, src/System.Windows.Forms/src/System/Windows/Forms/MessageBoxIcon.cs, src/System.Windows.Forms/src/System/Windows/Forms/MessageBoxOptions.cs
- Cleanup MessageBox interop
- Cleanup `MB_` constants
- Cleanup `ID` constants
=> Cleanup MessageBox interop

src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.cs, src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/SplitContainer.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
=> Cleanup Control.SendMessage

src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.IPersist.cs, src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.IPersistPropertyBag.cs, src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.IPersistStream.cs, src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.IPersistStreamInit.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- Cleanup IPersist interface and related interfaces
=> Cleanup IPersist interface and related interfaces

src/System.Windows.Forms.Primitives/src/Interop/Interop.ERROR.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
=> Cleanup ERROR_ constants

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
=> Cleanup some Menu interop

src/System.Windows.Forms.Design.Editors/src/System/ComponentModel/Design/ObjectSelectorEditor.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.NM.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/StatusBar.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
=> Cleanup NM_ constants

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripRendererTests.cs
=> Add ToolStripRenderer tests

src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TCN.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
=> Cleanup TCN constants

src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TBM.cs, src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.cs, src/System.Windows.Forms/tests/UnitTests/CheckedListBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ContainerControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Handlers.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Properties.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PanelTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PictureBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ProgressBarTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollBarTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs, src/System.Windows.Forms/tests/UnitTests/TrackBarTests.cs
- Add TrackBar tests and update tests to match styles for other ComCtl32 controls
Also include the `TBM` file because I'm using it in the test project
=> Add TrackBar tests and update tests to match styles for other ComCtl32 controls

eng/Version.Details.xml, eng/Versions.props, global.json
https://github.com/dotnet/winforms/pull/2638 plus a breaking change fix (https://github.com/dotnet/runtime/issues/1338). Filing as a separate PR to get CI running ASAP. (I also don't have permissions to update the existing PR.)
> This pull request updates the following dependencies
> 
> ## From https://github.com/dotnet/runtime
> * **Build**: 20200105.4
> * **Date Produced**: 1/6/2020 6:59 AM
> * **Commit**: 5b968685ce89f9dddf49e9aa3aa0608820a585aa
> * **Branch**: refs/heads/master
> * **Updates**:
>   * **Microsoft.NETCore.App** -> 5.0.0-alpha.1.20055.4
> 
> ## Coherency Updates
> The following updates ensure that dependencies with a _CoherentParentDependency_
> attribute were produced in a build used as input to the parent dependency's build.
> See [Dependency Description …
=> [master] [patched] Update dependencies from dotnet/runtime

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.MOUSEHOOKSTRUCT.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
=> Cleanup MOUSEHOOKSTRUCT

src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.LVA.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.LVIR.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.LVNI.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.LVSCW.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.LVSIL.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ItemBoundsPortion.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewAlignment.cs
- Cleanup LVSCW_ constants
- Cleanup LVSIL_ constants
- Cleanup LVNI_ constants
- Cleanup LVIR_ constants
- Cleanup LVA_ constants
=> Cleanup a bunch of ListView constants

src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.NMHEADERW.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
=> Cleanup NMHEADERW interop

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.LBS.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs
=> Cleanup LBS_ styles

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.MA.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
- Add MA enum in Interop User32.
- Remove MA constants and replace their usages with the above enum.
=> Add MA enum in Interop User32

src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs, src/System.Windows.Forms/tests/UnitTests/TextBoxBaseTests.cs, src/System.Windows.Forms/tests/UnitTests/TextBoxTests.cs
=> Add TextBoxBase tests

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.BM.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.BN.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Button.cs, src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs, src/System.Windows.Forms/src/System/Windows/Forms/CheckBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/RadioButton.cs
=> Cleanup Button interop

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.WindowMessage.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
=> Remove unused window messages

.editorconfig
Fixes #
comments added by #2715 and confusing comment in the file
Delete confusing comments and redundant lines
Avoids customers confusing based by comment saying to uncomment code to do something when a copy of the code was already uncommented.
- No
None, just deleted comments
No code changes only removal of comments
=> .editorConfig delete comments that don't make sense, no code changes

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.RegisteredMessage.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.WindowMessage.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlNativeWindow.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- Cleanup WindowMessage RegisteredMessages
=> Cleanup WindowMessage RegisteredMessages

src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.DTM.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.WindowMessage.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs
=> Cleanup DTM window messages

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetMenuItemInfoW.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.MENUITEMINFOW.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.MFS.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.MFT.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.MIIM.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownMenu.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.cs
=> Cleanup MENUITEM structs

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Properties.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Layout/TableLayoutSettingsTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TableLayoutControlCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TableLayoutPanelTests.cs
- Add TableLayoutPanel tests
Depends on https://github.com/dotnet/winforms/pull/2563
=> Add TableLayoutPanel tests

src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.CCS.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.SBARS.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/StatusBar.cs
=> Cleanup StatusBar interop

src/System.Windows.Forms.Primitives/src/Interop/Comdlg32/Interop.ChooseFontW.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/FontDialog.cs
=> Cleanup CHOOSEFONT

src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.NMTTDISPINFOW.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TTF.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TTOOLINFOW.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolTipBuffer.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MultipleControls.Designer.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolTipBufferTests.cs
- Cleanup NMTTDISPINFOW interop
=> Cleanup NMTTDISPINFOW interop

src/System.Windows.Forms.Design.Editors/src/System/Windows/Forms/Design/ImageIndexEditor.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ReferenceService.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerBase.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/LockedBorderGlyph.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/MiniLockedBorderGlyph.cs, src/System.Windows.Forms/src/System/Windows/Forms/Binding.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/Label.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewVirtualItemsSelectionRangeChangedEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
=> Contributing: fixed some typos

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.DrawMenuBar.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
- Move DrawMenuBar to Interop User32.
=> Move DrawMenuBar to Interop User32

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollBarTests.cs, src/System.Windows.Forms/tests/UnitTests/TrackBarTests.cs
=> Add more ScrollBar tests

src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.BFFM.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.SendMessageW.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
=> Cleanup BFFM constants

src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.MAX_TAB_STOPS.cs, src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.PARAFORMAT.cs, src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.PFA.cs, src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.PFM.cs, src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.PFN.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBoxConstants.cs
=> Structify PARAFORMAT

src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.GETTEXTLENGTHEX.cs, src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.GTL.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBoxConstants.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/TextBoxBaseTests.cs
=> Cleanup GETTEXTLENGTHEX

src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TVE.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TVGN.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TVI.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TVN.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TVSIL.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
- Cleanup remaining TreeView constants
=> Cleanup remaining TreeView constants

src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.ENDROPFILES.cs, src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
- Cleanup ENDROPFILES and DragQueryFileW
=> Cleanup ENDROPFILES

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerUtils.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.PRF.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
=> Cleanup PRF_ constants

eng/Versions.props
=> Update to preview branding

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ColumnHeader.cs, src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/StatusBarPanel.cs, src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
=> More SendMessage cleanup

src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.GetStartupInfoW.cs, src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.STARTF.cs, src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.STARTUPINFOW.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
=> Cleanup GetStartupInfo code

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.COPYDATASTRUCT.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
=> Cleanup COPYDATASTRUCT

src/System.Windows.Forms.Primitives/src/Interop/Comdlg32/Interop.FR.cs, src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.FINDTEXTW.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBoxConstants.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
=> Cleanup FINDTEXTW

src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.cs
=> Cleanup TrackBar code

src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs, src/System.Windows.Forms/tests/UnitTests/TextBoxBaseTests.cs
=> Fix TextBoxBase NREs

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
- Replace SendCallbackMessage with SendMessageW.
=> Replace SendCallbackMessage with SendMessageW

src/System.Windows.Forms/src/System/Windows/Forms/HitArea.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.HitTestInfo.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
=> Cleanup MonthCalendar code

src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs
=> Fix TabControl NREs

Directory.Build.targets
=> Run tests in x86 and x64

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MdiClientTests.cs
=> Add MdiClient tests

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ContainerControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Handlers.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/GroupBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PanelTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PictureBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/SplitterPanelTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripContentPanelTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/UserControlTests.cs
- Add UserControl and related tests
=> Add UserControl and related tests

src/System.Windows.Forms/tests/UnitTests/WebBrowserBaseTests.cs, src/System.Windows.Forms/tests/UnitTests/WebBrowserTests.cs
=> Add WebBrowser tests

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewElementTests.cs
- Improve DataGridViewElement testing
=> Improve DataGridViewElement testing

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Layout/FlowLayoutTests.cs
Lays groundwork for testing fix for #522
=> Add FlowLayout tests

src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs
=> Add more AxHost tests

src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumn.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewColumnTests.cs
- Add DataGridViewColumn tests
=> Add DataGridViewColumn tests

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/FileDialog_Vista.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FileDialogTests.cs
=> Add FileDialog.ClientGuid

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/WebBrowserTests.cs
See https://github.com/dotnet/winforms/pull/2962#discussion_r394735398 - guessing this depends on the version of IE installed on the computer.
Doesn't yet fix https://github.com/dotnet/winforms/pull/2962#discussion_r394748792 - waiting for comments /cc @russkie @weltkante
=> Fix WebBrowser tests on internal CI

src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Interaction.vb, src/Microsoft.VisualBasic.Forms/src/PublicAPI.Shipped.txt
Resolves #2997
- fix incorrect access modifiers
=> fix incorrect access modifiers

.github/ISSUE_TEMPLATE/feature_request.md, Documentation/developer-guide.md, Documentation/issue-guide.md
=> Update docs pertaining to feature requests

src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
=> LOC CHECKIN | dotnet/winforms master | 20200409

eng/Versions.props
Relates to https://github.com/dotnet/winforms/issues/2926
=> Update Microsoft.NET.Test.Sdk to v16.5.0

src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/PropertyGridViewRowsAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripDropDownTests.cs
=> Disable tests suspected to cause deadlocks

eng/common/templates/post-build/post-build.yml
=> Manually add publishing for p4 and p5 channels while arcade is not flowing

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Application.ParkingWindowTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CommonDialogTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/GroupBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewInsertionMarkTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
See: https://github.com/dotnet/arcade/issues/5325
=> Disable tests that rely on RemoteExecutor

eng/ci.yml
=> Move to NetCorePublic-Pool

eng/common/templates/post-build/post-build.yml
The change got merged in master, it needed to be in preview4 
so just cherry-picking the change
=> Manually add publishing for p4 and p5 channels in preview4

NuGet.config
=> add dotnet tools feed

src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
.NET Core Encoding.Default gets UTF-8, not the default code page. Change our code to get the code page as we're sending
data to the control as ASCII.
Ultimately we should remove all non-Unicode codePaths in RichTextBox. This should be possible as we're force loading the latest RichEdit.
Fixes #3032
=> Fix RichTextBox Rtf encoding

src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
Localization update
- 
- 
- 
- 
- 
- Yes / No
-
- 
- 
- 
-
=> LOC CHECKIN | dotnet/winforms master | 20200424

src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewColumnCollectionTests.cs
- Add some initial DataGridViewColumnCollection tests
=> Add some initial DataGridViewColumnCollection tests

src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.NOTIFYICONDATAW.cs, src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.Shell_NotifyIconW.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/NotifyIcon.cs
=> Cleanup NOTIFYICONDATA

eng/configure-toolset.sh
Fixes https://github.com/dotnet/winforms/issues/3018
Inspired by https://github.com/dotnet/runtime/blob/master/eng/configure-toolset.sh
/cc @kant2002
=> Fix errors building on Unix

src/Microsoft.VisualBasic.Forms/src/Microsoft.VisualBasic.Forms.vbproj, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
which broke build on Linux
Related #3018
=> Correct casing of filenames

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ApplicationTests.cs
Fixes #2192
This should make the test resilient in the future
/cc @weltkante
=> Move Application_VisualStyleState_Set_ReturnsExpected to RemoteExecutor

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewBand.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewElement.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyStore.cs
- Nullable annotate DataGridViewBand
=> Nullable annotate DataGridViewBand

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ApplicationContext.cs
- Nullable annotate ApplicationContext
=> Nullable annotate ApplicationContext

src/System.Windows.Forms.Design/src/System/Drawing/Design/ColorEditor.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.EnumDisplayMonitors.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetDlgItemInt.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetPhysicalCursorPos.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.MONITORENUMPROC.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.MessageBeep.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/SafeNativeMethods.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.MonthCalendarAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/NumericUpDown.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/Screen.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs, src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiListViewTests/MauiListViewTests.cs
=> Cleanup more User32 interop

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ProfessionalColorTableTests.cs
=> Disable deadlocking test

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.TabPageCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs
- Add some more TabPage related tests for Visual Styles coverage
=> Add some more TabPage related tests for Visual Styles coverage

src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.cs
- Strip out IsIE support
/cc @Tanya-Solyanik 
Fixes #3178
=> Strip out IsIE support

src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
Fixes #3251
- Porting .NET Framework fix for DataGridViewComboBox cell issue related to the control handle recreating when restructuring accessibility hierarchy tree.
- Costumers will not experience application error when working with the DataGridView containing ComboBox cell. 
- Yes
- Minimal
Application error (crash) when working with DataGridView with ComboBox cell (reproduces rarely).
No issues.
- Unit testing.
- Automation tests.
Version:   5.0.100-preview.5.20260.4
Commit:    0950d416f9
Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.5.20260.4\
Version: 5.0.0-preview.5.20260.5 …
=> Fixing DataGridViewComboBoxCell: ComboBox causes application crash on handle recreating related to accessibility hierarchy tree restructuring

src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Interaction.vb
Fixes #3252
- Pass the missing parameter
=> Correct exception

src/System.Windows.Forms/src/System/Windows/Forms/Button.cs, src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ButtonBaseTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ButtonTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs
=> Add ButtonBase tests

roadmap.md
Addressed comments from https://github.com/dotnet/winforms/pull/3054
=> Updated roadmap.md

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/Microsoft.Dotnet.Winforms.ProjectTemplates.csproj, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/Company.WinFormsApplication1.csproj, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/Company.WinFormsApplication1.vbproj, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/Company.ClassLibrary1.csproj, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-VisualBasic/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-VisualBasic/Company.ClassLibrary1.vbproj
SDK related issue dotnet/sdk#11706
=> Update templates to net5.0

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs
Fixes #3272 
Fix menu navigation
- No
-
Manual testing with MenuStripAndCheckedListBox 
Version:   5.0.100-preview.5.20262.6
Commit:    9ad967d49e
Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.5.20262.6\
Version: 5.0.0-preview.6.20262.3
Commit:  210a82a2e7
3.1.201 [C:\Program Files\dotnet\sdk]
3.1.202 [C:\Program Files\dotnet\sdk]
5.0.100-preview.5.20262.6 [C:\Program Files\dotnet\sdk]
.NET runtimes installed:
Microsoft.AspNetCore.App 3.1.3 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App]
Microsoft.AspNetCore.App 3.1.4 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.App] …
=> Fix menu arrow key navigation

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/Microsoft.Dotnet.Winforms.ProjectTemplates.csproj, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/Company.WinFormsApplication1.csproj, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/Company.WinFormsApplication1.vbproj, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/Company.ClassLibrary1.csproj, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-VisualBasic/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-VisualBasic/Company.ClassLibrary1.vbproj
Cherry-pick of https://github.com/dotnet/winforms/commit/f881902a3860bc6d0c348aacdbea51ea63bbd9b8
cc @RussKie @mmitche
=> Update templates to net5.0 (#3344)

src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.GetThemeBackgroundContentRect.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.GetThemeBackgroundExtent.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.GetThemeBackgroundRegion.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.GetThemeFilename.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.GetThemeMargins.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.GetThemePartSize.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.GetThemePosition.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.GetThemeString.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.GetThemeTextExtent.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.GetThemeTextMetrics.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.HitTestThemeBackground.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
- Cleanup remaining UxTheme interop
=> Cleanup remaining UxTheme interop

src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/SingleInstanceHelpers.vb, src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb, src/Microsoft.VisualBasic.Forms/src/PublicAPI.Unshipped.txt, src/Microsoft.VisualBasic.Forms/src/Resources/SR.resx, src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.cs.xlf, src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.de.xlf, src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.es.xlf, src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.fr.xlf, src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.it.xlf, src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.ja.xlf, src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.ko.xlf, src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.pl.xlf, src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.ru.xlf, src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.tr.xlf, src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/Microsoft.VisualBasic/tests/IntegrationTests/Microsoft.VisualBasic.IntegrationTests/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBaseTests.cs, src/Microsoft.VisualBasic/tests/IntegrationTests/VisualBasicRuntimeTest/Program.cs, src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/ApplicationServices/SingleInstanceTests.cs
Fixes https://github.com/dotnet/winforms/issues/2056
Implement support for `WindowsFormsApplicationBase` single-instance behavior. 
Allows applications using the VisualBasic application model to opt-in to single-instance behavior.
Not implemented when porting Microsoft.VisualBasic to .NET Core previously.
Medium risk when opted-in; low risk otherwise.
Unit tests.
=> Implement WindowsFormsApplicationBase.IsSingleInstance

eng/NonShipping.ruleset
=> Relax CA1825 for tests

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RadioButtonTests.cs
=> Add RadioButton tests

eng/NonShipping.ruleset, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.SelectedIndexCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.SelectedObjectCollection.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewColumnCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewSelectedCellCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewSelectedColumnCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewSelectedRowCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageList.ImageCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBox.IntegerCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBox.ObjectCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBox.SelectedIndexCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBox.SelectedObjectCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs
- Add ListBox SelectedItems tests
=> Add ListBox SelectedItems tests

src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewHeaderCell.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewHeaderCellTests.cs
- Add DataGridViewHeaderCell tests
- Add parameter names to ArgumentExceptions
=> Add DataGridViewHeaderCell tests

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/HScrollBar.cs, src/System.Windows.Forms/src/System/Windows/Forms/HScrollProperties.cs, src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.cs, src/System.Windows.Forms/src/System/Windows/Forms/ScrollProperties.cs, src/System.Windows.Forms/src/System/Windows/Forms/VScrollBar.cs, src/System.Windows.Forms/src/System/Windows/Forms/VScrollProperties.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollableControlTests.cs
- Enable nullability for ScrollBar/ScrollProperties
=> Enable nullability for ScrollBar/ScrollProperties

src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.cs.xlf, src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.de.xlf, src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.es.xlf, src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.fr.xlf, src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.it.xlf, src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.ja.xlf, src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.ko.xlf, src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.pl.xlf, src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.ru.xlf, src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.tr.xlf, src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/Microsoft.VisualBasic.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
Fixes #
Localization update only
- 
- 
- 
- 
- 
- Yes / No
-
- 
- 
- 
-
=> LOC CHECKIN | dotnet/winforms master | 20200605

src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.CA.cs, src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.IPerPropertyBrowsing.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxPropertyDescriptor.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/BaseCAMarshaler.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IPerPropertyBrowsingHandler.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/Int32CAMarshaler.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/OleStrCAMarshaler.cs
Extracted from #3197
- Move to Ole32
- Rename to `CA`
- Make void pointer
=> Cleanup CA code

src/System.Windows.Forms.Primitives/src/Interop/Mshtml/Interop.IHTMLDocument4.cs, src/System.Windows.Forms/src/System/Windows/Forms/HtmlDocument.cs, src/System.Windows.Forms/src/System/Windows/Forms/HtmlElement.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HtmlDocumentTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HtmlElementTests.cs
Extracted from https://github.com/dotnet/winforms/pull/3326
=> Add tests for HtmlElement/HtmlDocument

eng/NonShipping.ruleset, src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/ApplicationServices/SingleInstanceTests.cs, src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBaseTests.cs
- Test for `WindowsFormsApplicationBase.GetApplicationInstanceID()`.
- None. Added test only. 
- No
- Low risk. Added test only.
- Unit test.
=> Test WindowsFormsApplicationBase.GetApplicationInstanceID

src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
Fixes #
Localization update only
- 
- 
- 
- 
- 
- Yes / No
-
- 
- 
- 
-
=> LOC CHECKIN | dotnet/winforms master | 20200617

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs, src/System.Windows.Forms/src/System/Windows/Forms/InputLanguageChangedEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/InputLanguageChangedEventHandler.cs, src/System.Windows.Forms/src/System/Windows/Forms/InputLanguageChangingEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/InputLanguageChangingEventHandler.cs, src/System.Windows.Forms/src/System/Windows/Forms/InputLanguageCollection.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/InputLanguageChangedEventArgsTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/InputLanguageChangingEventArgsTests.cs
- Nullable annotate InputLanguage
=> Nullable annotate InputLanguage

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnHeaderCell.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowHeaderCell.cs
- Looks like some StringWriter instances should be disposed.
=> Dispose StringWriter instances

src/System.Windows.Forms/src/System/Windows/Forms/GroupBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/Label.cs, src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextRenderer.cs
- WindowsFont was not disposed in some cases.
- Made using statement usage consistent.
=> Dispose GetWindowsFont return value

start-vs.cmd
Don't want to lock the current command prompt.
=> Another incremental improvement

src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeCollection.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.ControlCollection.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeCollectionTests.cs
- Add tests for TreeNodeCollection Find method.
=> Add tests for TreeNodeCollection Find method

src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
Fixes #
- 
- 
- 
- 
- 
- Yes / No
-
- 
- 
- 
-
=> localization HB

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/CheckBox.CheckBoxAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/CheckBox.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/CheckBox.CheckBoxAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CheckBoxTests.cs
Fixes #3227
- Adding UIA providers support for CheckBox control.
- Moving CheckBox control accessible object to a separate file.
- Improving development experience for Button control accessibility.
- Prerequisite for #2164
- No
- Minimal
- Unit tests.
- UI automation tests.
- Inspect tool (need to ensure that Inspect properties are similar to what we had before switching to UIA as well as accessibility actions should work properly: Default action, Toggle action and so on)
- Narrator
.NET Core 5.0
Version: 5.0.100-alpha.1.20073.10
Commit: 29f4d693a9
OS Version: 10.0.18363
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\5.0.100-alpha1-05536
Version: …
=> Adding CheckBox control UIA accessibility

src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
Fixes #
- 
- 
- 
- 
- 
- Yes / No
-
- 
- 
- 
-
=> LOC CHECKIN | dotnet/winforms master | 20200702

src/System.Windows.Forms/tests/AccessibilityTests/DialogsTesting.Designer.cs, src/System.Windows.Forms/tests/AccessibilityTests/DialogsTesting.cs
=> Add TaskDialog accessibility sample

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/SystemDrawingExtensions.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextRenderer.cs, src/System.Windows.Forms/src/misc/GDI/WindowsFont.cs, src/System.Windows.Forms/src/misc/GDI/WindowsGraphics2.cs, src/System.Windows.Forms/tests/UnitTests/Text/FontMetrics.cs
Move font quality method to extensions.
Add basic text measurement related tests.
Put the tests in a general file as the intent is to refactor these methods (e.g. they won't stay where they are).
=> Add tests for font measurement

eng/CIBuild.cmd, eng/custom-cibuild.ps1
=> Test screenshots

src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlTabOrderHolder.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- Use generic lists in Control.
=> Use generic lists in Control

eng/Shipping.ruleset, src/System.Windows.Forms.Design/src/System/Drawing/Design/FontNameEditor.cs, src/System.Windows.Forms.Primitives/src/Interop/IHandle.cs, src/System.Windows.Forms/src/System/Windows/Forms/CurrencyManager.cs
- Enable and fix CA1200 warnings.
=> Enable and fix CA1200 warnings

eng/Shipping.ruleset, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.LayoutData.cs
- Enable and fix CA1830 warnings.
=> Enable and fix CA1830 warnings

eng/Shipping.ruleset, src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/SingleInstanceHelpers.vb
- Enable and fix CA1835 warnings.
=> Enable and fix CA1835 warnings

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ItemArray.Entry.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ItemArray.EntryEnumerator.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ItemArray.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ObjectCollection.cs
- Automated changes, nothing functional
=> ListBox nested classes cleanup

src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListView.ListViewItemCollectionTests.cs
- Add tests for ListViewItemCollection Find method.
=> Add tests for ListViewItemCollection Find method

eng/NonShipping.ruleset, eng/Shipping.ruleset, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerUtils.cs, src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/SendKeys.cs
- Enable and fix CA1810 warnings.
=> Enable and fix CA1810 warnings

azure-pipelines.yml
=> [release/5.0-preview8] Enable builds of internal branches

src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/Person.cs, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/TestDataSources.cs, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests/System.Windows.Forms.IntegrationTests.csproj, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxes.Designer.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxes.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/WinformsControlsTest.csproj, src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
Fixes #3549 
use method that accesses DisplayMember property instead of ToString
see the issue
manual
=> Fixes #3549

azure-pipelines.yml
=> [master] Enable builds of internal branches

azure-pipelines.yml, eng/ci.yml
Also do a bit of cleanup on the YAML
=> Enable internal build consumption

src/System.Windows.Forms/src/System/Windows/Forms/MenuStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/MenuStrip.MenuStripAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/StatusStrip.StatusStripAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/ToolStripAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/ToolStripItemAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/ToolStripTextBox.ToolStripTextBoxAccessibleObjectTests.cs
Fixes #3560
Added supporting of "LegacyIAccessible" pattern. Added missing logic for Name property.
- No
- No
- Minimal
- Unit-tests 
- .NET Core 5.0 Version: 5.0.100-rc.1.20367.2
=> Fixing issue with getting of Accessible Name, Role, Description

src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
Fixes #
- 
- 
- 
- 
- 
- Yes / No
-
- 
- 
- 
-
=> LOC CHECKIN

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ButtonTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextRendererTests.cs
=> Disable flaky tests

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-CSharp/.template.config/dotnetcli.host.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-CSharp/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-CSharp/Company.ControlLibrary1.csproj, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-CSharp/Company.ControlLibrary1.csproj.user, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-CSharp/UserControl1.Designer.cs, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-CSharp/UserControl1.cs, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-VisualBasic/.template.config/dotnetcli.host.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-VisualBasic/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-VisualBasic/Company.ControlLibrary1.vbproj, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-VisualBasic/Company.ControlLibrary1.vbproj.user, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-VisualBasic/UserControl1.Designer.vb, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-VisualBasic/UserControl1.vb, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/readme.md
Resolves #3608
- local / manually
=> Add template for WinForms Control Library

src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.GetLocaleInfoEx.cs, src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.LCID.cs, src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.LCTYPE.cs, src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.SORT.cs, src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.SetThreadLocale.cs, src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.QACONTAINER.cs, src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.TYPEATTR.cs, src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.IDispatch.cs, src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.OCPFIPARAMS.cs, src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.OleCreatePropertyFrame.cs, src/System.Windows.Forms.Primitives/src/Interop/VSSDK/Interop.ICategorizeProperties.cs, src/System.Windows.Forms.Primitives/src/Interop/VSSDK/Interop.IVsPerPropertyBrowsing.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2ComponentEditor.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2ICategorizePropertiesHandler.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IVsPerPropertyBrowsingHandler.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs, src/System.Windows.Forms/src/System/Windows/Forms/Printing/PageSetupDialog.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ApplicationTests.cs
=> Cleanup LCID code

src/System.Windows.Forms/tests/AccessibilityTests/AccessibilityTests.csproj, src/System.Windows.Forms/tests/AccessibilityTests/PrintingTesting.Designer.cs
=> removed a duplicate property from the project file

src/System.Windows.Forms/tests/AccessibilityTests/StripControls.Designer.cs
=> Fixed PR comment: accessible name should not refer to control type

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/AmbientProperties.cs
- Enable nullability in AmbientProperties.
=> Enable nullability in AmbientProperties

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/Company.WinFormsApplication3x1.csproj, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/Company.WinFormsApplication3x1.vbproj, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/Company.ClassLibrary3x1.csproj, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-VisualBasic/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-VisualBasic/Company.ClassLibrary3x1.vbproj
Port change to preview 8 https://github.com/dotnet/winforms/pull/3690
=> Update to net5.0 template with backcompact

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleInformation.cs
- Enable nullability in VisualStyleInformation.
=> Enable nullability in VisualStyleInformation

eng/Shipping.ruleset, src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutSettings.cs
- Enable and fix CA2229 warning.
=> Enable and fix CA2229 warning

src/System.Windows.Forms/src/AssemblyRef.cs, src/System.Windows.Forms/src/SRCategoryAttribute.cs, src/System.Windows.Forms/src/SRDescriptionAttribute.cs
- Enable nullability in AssemblyRef, SRCategoryAttribute and SRDescriptionAttribute.
=> Enable nullability in AssemblyRef, SRCategoryAttribute and SRDescriptionAttribute

Documentation/getting-started.md, eng/Versions.props, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-CSharp/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-VisualBasic/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-VisualBasic/.template.config/template.json
=> .NET 6.0 branding

eng/Shipping.ruleset, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/SpanHelpers.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/NoAssertContext.cs, src/System.Windows.Forms/src/System/Windows/Forms/FontDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.cs
- Enable and fix CA1836 warnings.
=> Enable and fix CA1836 warnings

src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
Fixes #
-  New string translations.
- 
- 
- 
- 
- Yes / No
-
- 
- 
- 
-
=> LOC CHECKIN 2020-08-25

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ComponentTray.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.cs, src/System.Windows.Forms/src/System/Windows/Forms/BindingSource.cs, src/System.Windows.Forms/src/System/Windows/Forms/Command.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBindingHelper.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.cs, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/TestHelpers.cs
=> Use 'is null' instead of 'null =='

src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
Fix a regression introduced 60acd0e81b25067b6cbf5d6a987e540f1106e71c.
Resolves #3579
Resolves #3573
=> Correct attribute decorations

src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
Fixes #
Latest localized strings.
- 
- 
- 
- 
- 
- Yes / No
-
- 
- 
- 
-
=> loc checking 20200904

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
DeviceDPI can change *once* after setting the DPI awareness context. When we explicitly do so, reset the backing property.
Add more clarifying comments.
Fixes #3832
- Reset the device DPI after calling `Application.SetHighDpiMode`
- Without this you will not get proper DeviceDpi without a manifest.
- Yes
- Very low, constrained to `DpiHelper` code.
- Ran multiple low level API tests to validate Windows behavior with logical pixels
- Ran manual tests with WinForms app to see that the DPI is now correct
cc: @dreddy-work
=> Reset the DeviceDPI after setting DPI awareness

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
DeviceDPI can change *once* after setting the DPI awareness context. When we explicitly do so, reset the backing property.
Add more clarifying comments.
Fixes #3832
- Reset the device DPI after calling `Application.SetHighDpiMode`
- Without this you will not get proper DeviceDpi without a manifest.
- Yes
- Very low, constrained to `DpiHelper` code.
- Ran multiple low level API tests to validate Windows behavior with logical pixels
- Ran manual tests with WinForms app to see that the DPI is now correct
cc: @Pilchie for RC2
=> Reset the DeviceDPI after setting DPI awareness (#3855)

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.cs
See https://docs.microsoft.com/en-us/visualstudio/code-quality/ca1820?view=vs-2019
=> Empty string check optimization

src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
New translations.
- 
- 
- 
- 
- 
- Yes / No
-
- 
- 
- 
-
=> locheckin 20200914

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.CDDesignerCommandSet.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.ShadowPropertyCollection.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/Behavior.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorDragDropEventArgs.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorDragDropEventHandler.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.AdornerWindow.MouseHook.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.AdornerWindow.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.MenuCommandHandler.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.CanResetSizePropertyDescriptor.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.ChildSubClass.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.ChildWindowTarget.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.ControlDesignerAccessibleObject.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.DesignerControlCollection.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.DesignerControlCollectionCodeDomSerializer.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.TransparentBehavior.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
Using tools to:
- Implement autoproperties
- Invert and combine if blocks to reduce nesting
- Use expression bodies
- Convert to conditional expressions
And some manual spacing and comment cleanup
=> More non-functional behavior service related cleanup

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.ShadowPropertyCollection.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/Behavior.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorDragDropEventArgs.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.AdornerWindow.MouseHook.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.AdornerWindow.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.ChildSubClass.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.ControlDesignerAccessibleObject.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.DockingActionList.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
- Use null coalescing operators
- Use conditional operators
- Few more if block simplifications
- Minor comment and spacing cleanup
- Simplify usings
Not exhaustive, just grabbing low-hanging fruit
=> More BehaviorService related code cleanup

eng/Publishing.props, eng/ci.yml
Test build: https://dev.azure.com/dnceng/internal/_build/results?buildId=825309&view=results
=> Onboard to v3 publishing

eng/packageContent.targets, global.json
Cherry pick https://github.com/dotnet/winforms/commit/4bdf29eef947200c946ca7f295b47fe829bed41f from master
=> use new intellisense blob, change package composition logic (#3999)

src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.HRGN.cs, src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.RGNDATAHEADER.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/RecordTypes/EMREXTSELECTCLIPRGN.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.Rendering.cs
Two commits, the first is just a style cleanup for a section of DataGridView around the consuming code for this change.
The second unifies RGNDATAHEADER helper code in the primitives assembly and makes a minor tweak for a test where I first implemented the newer, better perf helper.
=> Refactor getting region clipping rectangles

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
Reinstate `RichTextBox_Text_GetWithHandle_ReturnsExpected`
Relates to #3778
Resolves #3867
=> Reinstate `RichTextBox_Text_GetWithHandle_ReturnsExpected`

src/System.Windows.Forms.Primitives/src/PublicAPI.Shipped.txt, src/System.Windows.Forms.Primitives/src/PublicAPI.Unshipped.txt, src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
=> Mark .NET 5.0 API as shipped

eng/packageContent.targets, global.json
Update intellisense artifacts from https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=164260&view=artifacts&type=publishedArtifacts
=> update intellisense artifacts

src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.Designer.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.cs
Set title of the list view test form and fixed message displayed on click
=> minor cleanup in the interactive test

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
- Remove extra StackOverflow comments in unit tests
- No
- No
- Minimal
=> Removed an extra comment in tests

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/EventBindingService.EventPropertyDescriptor.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.StateConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ColumnHeaderConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2EnumConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2ExtendedTypeConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IDispatchConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/CursorConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellStyleConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ImageIndexConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ImageKeyConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/LinkArea.cs, src/System.Windows.Forms/src/System/Windows/Forms/LinkConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBindingConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListItemConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/OpacityConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/SelectionRangeConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeViewImageIndexConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeViewImageKeyConverter.cs
=> Fix typo in comments: desitnation -> destination

eng/packageContent.targets, global.json
Fixes #4095
New package came from https://apidrop.visualstudio.com/Content%20CI/_build/results?buildId=167131&view=results
=> bump intellisense version

src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.LinkAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.LinkLabelAccessibleObject.cs
- Enabled NRT for Combobox and LinkLabel AccessibleObjects
- No
- No
- Minimal
=> Enabled NRT for Combobox and LinkLabel AccessibleObjects

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.AccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.DataGridViewEditingPanelAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.SelectedCellsAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.TopRowAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.AccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
- Enabled NRT for DataGridView AccessibleObjects
- No
- No
- Minimal
=> Enable NRT for DataGridView AccessibleObjects

src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.AccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/MenuStrip.MenuStripAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarBodyAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarButtonAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarCellAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarChildAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarGridChildAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarHeaderAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarNextButtonAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarPreviousButtonAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarRowAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarTodayLinkAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.MonthCalendarAccessibleObject.cs
- Enabled NRT for MonthCalendar AccessibleObjects
- No
- No
- Minimal
=> Enable NRT for MonthCalendar accessible objects

eng/ci.yml
Remove unused agent pool variables so we only have to change them in one place
=> remove unused agent pool variables

CONTRIBUTING.md
Changed "pease note" to "please note".
=> Fixed spelling mistake in CONTRIBUTING.MD

src/System.Windows.Forms/src/System/Windows/Forms/TaskDialogButton.cs, src/System.Windows.Forms/src/System/Windows/Forms/TaskDialogCommandLinkButton.cs
=> add missing params to triple slash comments

src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/Kernel32/FILETIMETests.cs, src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/Oleaut32/VARIANTTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs
=> Fix locale dependent tests

eng/Versions.props
=> Update branding to 5.0.1

src/System.Windows.Forms.SourceGenerators/src/System/Windows/Forms/SourceGenerators/EnumValidationGenerator.cs
Hopefully this is a mitigation for AB#1241130 before the real work is done in the compiler.
=> Cache semantic models per syntax tree

src/System.Windows.Forms/tests/TestUtilities/ThreadExceptionFixture.cs, src/System.Windows.Forms/tests/UnitTests/NumericUpDownTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ButtonRenderingTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Handlers.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewHeaderCellTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DomainUpDownTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/GroupBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageList.ImageCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollableControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextBoxBase.TextBoxBaseUiaTextProviderTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/UpDownBaseTests.cs
- Enable visual styles when running tests to ensure we test the main user scenarios
=> Enable visual styles

src/System.Windows.Forms/tests/TestUtilities/ThreadExceptionFixture.cs, src/System.Windows.Forms/tests/UnitTests/NumericUpDownTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ButtonRenderingTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Handlers.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewHeaderCellTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DomainUpDownTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/GroupBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageList.ImageCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollableControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextBoxBase.TextBoxBaseUiaTextProviderTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/UpDownBaseTests.cs
=> Enable visual styles (#4197)

eng/Version.Details.xml
These got updated to a newer build before branding was updated.
=> [release/5.0] Fixup 5.0.0 shas to be RTM

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/My Project/Application.Designer.HighDpi.vb
Fixes #4178
Change
```
Dim eventArgs = New ApplyHighDpiModeEventArgs(
```
to
```
Dim eventArgs As New ApplyHighDpiModeEventArgs(
```
Customers who use Option Explicit On will fail using "=" but with "As" it will work no matter what setting are used.
- Yes this file does not exist before Core 5.0
none, this is a valid alternative syntax
This code is already tested but Option Explicit On is not set in tests.
- 
```
Version:   5.0.100
Commit:    5044b93829
OS Version:  10.0.19042
Base Path:   C:\Program Files\dotnet\sdk\5.0.100\
Version: 5.0.0
Commit:  cf258a14b7
1.1.13 [C:\Program Files\dotnet\sdk]
2.2.402 [C:\Program …
```
=> Fix OnInitialize fails to compile if VB Compile Options changes

src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.LinkAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/WinFormsUtils.cs
- Enable nullability in WinFormsUtils.
=> Enable nullability in WinFormsUtils

src/System.Windows.Forms/src/System/Windows/Forms/Layout/LayoutUtils.cs
- Enable nullability in LayoutUtils.
=> Enable nullability in LayoutUtils

src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildListUiaProvider.cs
- Fixed comment 
- No 
- Yes
- Minimal
=> Fix PoliCheck issue

src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
New translations.
- 
- 
- 
- 
- 
- Yes / No
-
- 
- 
- 
-
=> [loc] Latest translations

eng/Version.Details.xml, eng/Versions.props
=> Remove unused Microsoft.NETCore.App.Internal dependency

src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/User32/SystemParametersInfoWTests.cs
=> Check font returned via `SystemParametersInfoW` interop

src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/MainFormControlsTabOrder.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxesWithScrollBars.Designer.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxesWithScrollBars.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxesWithScrollBars.resx, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
Fixes #4335
Fixes #4323
- Implement `ScrollIntoView` method of `ScrollItemPattern`
- Fix getting of `Bounds`
- Accessibility tools or users can scroll a combo box drop-down list to some item
- A user can see a correct item Bounds position when combobox scrolling
- Yes (from .NET Framework 4.7.2)
- Minimal
- ComboBox items don't support `ScrollItemPattern` - do nothing when `ScrollIntoView` calling
- ComboBox items support `ScrollItemPattern` - scroll to some item when `ScrollIntoView` calling. 
For example, in the gif below I call `ScroolIntoView` for the **9th** item, and the `ComboBox` scrolls to the **9th** item on top or bottom.
- Unit tests
- CTI
- Using Inspect
- Microsoft Windows [Version 10.0.19042.685]
- .NET v. 6.0.100-alpha.1.20554.10
=> Implemented ScrollItemPattern for ComboBoxItemAccessibleObject

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MdiControlStripTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripMenuItemTests.cs
=> Add tests for #4388

src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/MainFormControlsTabOrder.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/TaskDialogSamples.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/TaskDialogSamples.resx
Copied from https://github.com/dotnet/samples/tree/master/windowsforms/TaskDialogDemo/cs
=> Add Task Dialog sample

Directory.Build.props, Directory.Build.targets, docs/building.md, docs/debugging.md, docs/testing.md, docs/winforms-designer.md, eng/Shipping.ruleset, global.json, src/System.Windows.Forms/tests/AccessibilityTests/AccessibilityTests.csproj, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/TestHelpers.cs, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/readme.md, src/System.Windows.Forms/tests/IntegrationTests/VisualBasicTemplate/VbWinForms.vbproj
=> Replace 'netcoareapp5' with 'net5' to reflect current TFM

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/BindingManagerDataErrorEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/DrawItemEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/HtmlElementErrorEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/LabelEditEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/LinkClickedEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/MeasureItemEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/PaintEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/QueryAccessibilityHelpEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/SearchForVirtualItemEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserDocumentCompletedEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserNavigatedEventArgs.cs
- Enable nullability in some Event Args.
=> Enable nullability in some Event Args

src/System.Windows.Forms/src/misc/MultitargetUtil.cs
- Enable nullability in MultitargetUtil.
=> Enable nullability in MultitargetUtil

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/GridItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/GridItemCollection.cs
- Enable nullability in GridItem and GridItemCollection.
=> Enable nullability in GridItem and GridItemCollection

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItemCollection.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemCollectionTests.cs
Fixes #4454 
- Fix the ToolStripItemCollection.AddRange ArgumentOutOfRangeException.
- Add a test to validate the fix.
As @weltkante [mentioned here](https://github.com/dotnet/winforms/issues/4454#issuecomment-759381740), the only non-breaking option is to implement `AddRange` in a way that moves all of the items without throwing an exception. There are several ways to solve this problem and I would appreciate any feedback.
The approach that I've taken here is to decrement the index to always `Add` from index 0 which preserves the original order, does not require reversing the collection, and avoids the ArgumentOutOfRangeException.
- Fixes the ArgumentOutOfRangeException and adds the elements to the end of the ToolStripItemCollection inner ArrayList.
- No.
- Could break people who expect …
=> Fix ToolStripItemCollection.AddRange ArgumentOutOfRangeException

src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnHeaderCell.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxEditingControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewNativeItemCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/MdiWindowListStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs, src/System.Windows.Forms/src/System/Windows/Forms/SplitContainer.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitStackLayout.cs
Fixes #1991
- Add parenthesizes around logical And operators that are in logical Or operators.  
- None
- No
- None
- manual testing
- existing unit tests
=> fixes #1991 => remove disable warning SA1408

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.Vista.cs
- Enabled NRT for FileDialog.Vista
- No 
- No
- Minimal
- .NET Core SDK 6.0.0-alpha.1.21073.5
=> Enable NRT for FileDialog.Vista

src/System.Windows.Forms/src/System/Windows/Forms/Keys.cs, src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutPanelGrowStyle.cs
- Enable nullability in Keys and TableLayoutPanelGrowStyle.
=> Enable nullability in Keys and TableLayoutPanelGrowStyle

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/DrawListViewColumnHeaderEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/DrawListViewItemEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/DrawListViewSubItemEventArgs.cs
- Enable nullability in DrawListView EventArgs.
=> Enable nullability in DrawListView EventArgs

src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxUiaTextProvider.cs
- Fixed build
- No 
- No
- Minimal
- .NET Core SDK 6.0.100-preview.2.21155.3
=> Fix build issue (ComboBoxUiaTextProvider)

src/System.Windows.Forms.Design/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
=> Loc updates

eng/Versions.props
Updating branding for 5.0 servicing branch to 5.0.6.
=> Update branding to 5.0.6 on servicing branch.

NuGet.config, eng/Version.Details.xml, eng/Versions.props, global.json
=> Merge in 'release/5.0.5' tags changes

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
=> Shipped APIs for Preview 4

eng/Versions.props
=> Branding change for Winforms 6.0 preview 5

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/DeviceContextHdcScope.cs, src/System.Windows.Forms/src/System/Windows/Forms/Internal/DrawingEventArgs.cs
Port pull request #4814
Use new GetContext overloads
=> Use new GetContext overloads

eng/Versions.props
=> Branding change in 5.0 servicing branch.

src/System.Windows.Forms/src/System/Windows/Forms/Internal/WinFormsMetadataUpdateHandler.cs
Contributes to https://github.com/dotnet/runtime/issues/51545
=> React to MetadataUpdateHandler renames

eng/Signing.props
Enables an automatic swap from Microsoft400 to MicrosoftDotNet500
=> Use .NET certificate

NuGet.config, eng/Version.Details.xml, eng/Versions.props, global.json
=> [release/5.0] Merge in 5.0.6 changes

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HtmlDocumentTests.cs
=> Disabled flaky tests to enable release build

eng/Versions.props
Branding to next milestone in main branch
=> Branding to P6

src/System.Windows.Forms.Design/src/Resources/SR.resx, src/System.Windows.Forms.Design/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hant.xlf
Resolves #4944 
/cc: @crsuzukimsft
=> Fix incorect resource string

src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignSurfaceTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignerActionServiceTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationServiceTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/Drawing/Design/FontNameEditorTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/MenuCommandsTests.cs
- 
- 
- 
- None
- No
- Minimal
- 
- 
- 
- 
##
=> Spelling src system.windows.forms.design tests unit tests

src/System.Windows.Forms/tests/TestUtilities/BinarySerialization.cs, src/System.Windows.Forms/tests/TestUtilities/Properties/InternalsVisibleTo.cs
- 
- 
- 
- None
- No
- Minimal
- 
- 
- 
- 
##
=> Spelling src system.windows.forms tests test utilities

src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Calendar.Designer.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Calendar.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
- 
- 
- 
- None
- No
- Some (the object name could matter)
- 
- 
- 
- 
##
=> Spelling src system.windows.forms tests integration tests winforms controls test

src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiTestsHelper/MouseHelper.cs
- 
- 
- 
- None
- No
- Minimal
- 
- 
- 
- 
##
=> Spelling src system.windows.forms tests integration tests maui tests maui tests helper

src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/Oleaut32/VARIANTTests.cs, src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/Automation/UiaTextRangeTests.cs
Fixes #
- 
- 
- 
- 
- 
- Yes / No
-
- 
- 
- 
-
=> Spelling src system.windows.forms.primitives tests unit tests

src/System.Windows.Forms/tests/AccessibilityTests/CommonControls2.Designer.cs, src/System.Windows.Forms/tests/AccessibilityTests/CustomAccessiblePropertiesForm.Designer.cs, src/System.Windows.Forms/tests/AccessibilityTests/DataBindingExample.cs
- 
- 
- 
- None
- No
- Minimal -- https://github.com/dotnet/winforms/pull/4998#discussion_r641564702
- 
- 
- 
- 
##
=> Spelling src system.windows.forms tests accessibility tests

src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DesignSurfaceExt/IDesignSurfaceExt.cs, src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DesignSurfaceExt/TabOrderHooker.cs
- 
- 
- 
- None
- No
- Minimal
- 
- 
- 
- 
##
=> Spelling src system.windows.forms tests integration tests design surface design surface ext

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/Microsoft.Dotnet.Winforms.ProjectTemplates.csproj
- 
- 
- 
- None
- No
- Minimal
- 
- 
- 
- 
##
=> spelling: suppress

pkg/Microsoft.Private.Winforms/ProcessFrameworkListFiles.ps1
- 
- 
- 
- None
- No
- Minimal
- 
- 
- 
- 
##
=> spelling: explicitly

src/System.Windows.Forms/tests/InteropTests/AccessibleObjectTests.cs
- 
- 
- 
- None
- No
- Minor (a "public" class in a test namespace is being renamed)
- 
- 
- 
- 
##
=> spelling: accessible

src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.cs
- 
- 
- 
- None
- No
- Minimal
- 
- 
- 
- 
##
=> Spelling src system.windows.forms tests integration tests design surface demo console
