CONTRIBUTING.md, Directory.Build.props, README.md, docs/accessibility/monthcalendar-expected-behavior.md, docs/designer-releases/0.1/releasenotes.md, docs/roadmap.md, docs/testing.md
- 
- 
- 
- Minimal, unless they read the docs
- No
- Minimal
- 
- 
- 
- 
##
=> Spelling docs

src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.MCGIF.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.MCS.cs, src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.SelectPaletteScope.cs, src/System.Windows.Forms.Primitives/src/Interop/Mso/Interop.IMsoComponent.cs, src/System.Windows.Forms.Primitives/src/Interop/Mso/Interop.msocstate.cs, src/System.Windows.Forms.Primitives/src/Interop/Mso/Interop.msoloop.cs, src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.IStream.cs, src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.STATSTG.cs, src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DragQueryFileW.cs, src/System.Windows.Forms.Primitives/src/Interop/UiaCore/Interop.IAccessibleEx.cs, src/System.Windows.Forms.Primitives/src/Interop/UiaCore/Interop.IInvokeProvider.cs, src/System.Windows.Forms.Primitives/src/Interop/UiaCore/Interop.IRawElementProviderFragment.cs, src/System.Windows.Forms.Primitives/src/Interop/UiaCore/Interop.ISelectionProvider.cs, src/System.Windows.Forms.Primitives/src/Interop/VSSDK/Interop.IVsPerPropertyBrowsing.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/DeviceContextExtensions.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/DeviceContextHdcScope.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/WeakRefCollection.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/SystemDrawingExtensions.cs
- 
- 
- 
- None
- No
- Minimal -- https://github.com/dotnet/winforms/pull/4998#discussion_r641542442
- 
- 
- 
- 
##
=> Spelling src system.windows.forms.primitives src

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config/dotnetcli.host.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/Company.WinFormsApplication1.csproj, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-CSharp/.template.config/dotnetcli.host.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-CSharp/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-CSharp/Company.ControlLibrary1.csproj, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/.template.config/dotnetcli.host.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/Company.ClassLibrary1.csproj
resolves https://github.com/dotnet/templates/issues/485
=> enable nullable for new projects

src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/WinformsMauiButtonTests.cs, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/WinformsMauiComboBoxTests.cs, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/WinformsMauiImageListTests.cs, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/WinformsMauiLabelTests.cs, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/WinformsMauiListViewTests.cs, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/WinformsMauiMonthCalendarTests.cs, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/WinformsMauiPrintPreviewDialogTests.cs, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/WinformsMauiPropertyGridViewTests.cs, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/WinformsMauiTabControlTests.cs, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/WinformsMauiToolStripTests.cs
- 
- 
- 
- None
- No
- Minimal
- 
- 
- 
- 
##
=> Spelling src system.windows.forms tests integration tests system.windows.forms.maui.integration tests

src/System.Windows.Forms.Primitives/tests/TestUtilities/ITestAccessor.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/RecordTypes/ENHMETAHEADER.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Properties/InternalsVisibleTo.cs
- 
- 
- 
- None
- No
- Minimal
- 
- 
- 
- 
##
=> Spelling src system.windows.forms.primitives tests test utilities

src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb, src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Helpers/NativeMethods.vb, src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Helpers/UnsafeNativeMethods.vb
- 
- 
- 
- None
- No
- Minimal
- 
- 
- 
- 
##
=> Spelling src microsoft.visual basic.forms src microsoft visual basic

eng/Versions.props
=> Update branding to 5.0.8

Winforms.sln
That allow progress a bit in compiling source code on Linux
Only problem right now is missing eng/common/native/install-dotnet-api-docs_net5.0.sh
This is just attempt compiling of existing code, not run it under Linux.
=> Fix path to project in solution

src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
Fixes #
correct defaultValue of ListView.HideSelection
- 
- 
- 
- Designer for ListView.HideSelection serialize correct
- 
- No
- 0
- 
- 
-
=> correct defaultValue of ListView.HideSelection

NuGet.config, eng/Version.Details.xml, eng/Versions.props, global.json
=> Merging internal commits for release/5.0

docs/accessibility/monthcalendar-expected-behavior.md
This was split from #4998
Per https://github.com/dotnet/winforms/pull/5065#discussion_r648277462
- spelling
- 
- 
- Some debugging output may no longer have typos
- 
- No
- Minor
- 
- 
- 
-
=> spelling: calendar

src/System.Windows.Forms/src/System/Windows/Forms/MessageBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/WinFormsUtils.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MessageBoxTests.cs
Fixes #4639
- Replaces WindowsFormsUtils.EnumValidator.IsEnumWithinShiftedRange only usage inside of MessageBox.cs with the source generated validation.
- None
- No
- None
TODO: Testing is needed.
- 
```
Version:   6.0.100-preview.2.21155.3
Commit:    1a9103db2d
OS Version:  10.0.21343
Base Path:   C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\
Version: 6.0.0-preview.2.21154.6
Commit:  3eaf1f316b
5.0.200-preview.21077.7 [C:\Program Files\dotnet\sdk]
6.0.100-preview.2.21155.3 [C:\Program Files\dotnet\sdk]
.NET runtimes installed:
Microsoft.AspNetCore.All 2.1.23 [C:\Program …
```
=> Replace WindowsFormsUtils.EnumValidator.IsEnumWithinShiftedRange with SourceGenerated.EnumValidator.Validate.

eng/Versions.props
=> Branding to preview 7

src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb
=> Fix StartupNextInstance when the main Form is nothing.

eng/Version.Details.xml, eng/Versions.props, src/System.Windows.Forms.Primitives/src/System.Windows.Forms.Primitives.csproj, src/System.Windows.Forms.Primitives/tests/TestUtilities/System.Windows.Forms.Primitives.TestUtilities.csproj, src/System.Windows.Forms/src/System.Windows.Forms.csproj, src/System.Windows.Forms/tests/TestUtilities/System.Windows.Forms.TestUtilities.csproj
=> Removing unused package references that were moved to netcore.

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.MCM.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/MonthCalendar.CalendarAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/MonthCalendar.CalendarCellAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/MonthCalendar.CalendarNextButtonAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/MonthCalendar.CalendarPreviousButtonAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/MonthCalendar.CalendarTodayLinkAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/MonthCalendar.MonthCalendarAccessibleObjectTests.cs
Fixes #
- Add unit tests for MonthCalendarAccessibleObject class and its children
- No
- No
- No
=> Adding month calendar unit tests

eng/Version.Details.xml, eng/Versions.props, global.json
Windows Desktop repo was backed up complaining about downgrades.
=> Remove stale and obsolete dependencies. Add CMake SDK.

src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Buttons.Designer.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Buttons.cs
=> Added tooltip to the interactive control test

azure-pipelines.yml, eng/pipelines/build.yml, eng/pipelines/post-build.yml
- Fixup the internal runtime download arguments
- Remove a bunch of unused and dead variables
=> Clean up YAML and fixup internal runtime download

eng/Versions.props
Updating servicing branding tp 5.0.9
=> Update servicng branding to 5.0.9

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObjectTests.cs
Fixes #5200 
- Rework ListViewSubItemAccessibleObject_ProcessId unit test
- No
- No
- No
- .Net SDK
Version: 6.0.0-preview.7.21358.2
=> Rework ListViewSubItemAccessibleObject_ProcessId unit test

eng/Version.Details.xml, global.json
=> Downgrade dotnet/runtime to allow flow of WPF (see https://github.com/dotnet/wpf/pull/4823)

src/System.Windows.Forms.Primitives/src/PublicAPI.Shipped.txt, src/System.Windows.Forms.Primitives/src/PublicAPI.Unshipped.txt, src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
Publishing Unshipped APIs for the upcoming preview.
=> Publishing APIs for current preview.

Winforms.sln, src/System.Windows.Forms/src/PublicAPI.Unshipped.txt, src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/MDIClient.cs, src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiMDITests/MauiMDITests.cs, src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiMDITests/MauiMDITests.csproj, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/System.Windows.Forms.Maui.IntegrationTests.csproj, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/WinformsMauiMDITests.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MdiChild.Designer.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MdiChild.cs
Fix https://github.com/dotnet/winforms/issues/4720.
- Add public bool property `MdiChildrenMinimizedAnchorBottom` to `Form` class.
WinForms override standard MDI behavior without option to use original one. It's lead to all child windows layout (with minimized windows) are mess up after main window resize. This can happened after simple resize, or after resolution changed (for example if your connect by rdp from other device), etc... Customer can use `MdiChildrenMinimizedAnchorBottom` to revert for Windows default behavior.
No
Minimal.
https://user-images.githubusercontent.com/17767561/125053862-3e5ac700-e0ae-11eb-8ff1-3b5f72500f9d.mp4
P.s. Video above with old name of the property.
Manual.
Maui automated test.
Unfortunately, I do not know anything on this topic. Therefore, if this is …
=> Possibility to align minimized MDI child to default location (TOP LEFT)

src/System.Windows.Forms/src/System/Windows/Forms/GridItemCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.SnappableControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/ArrayElementGridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/CategoryGridEntry.CategoryGridEntryAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/CategoryGridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/DocComment.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.DisplayNameSortComparer.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.Flags.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.GridEntryAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.Notify.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.PaintValueFlags.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/ImmutablePropertyDescriptorGridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiPropertyDescriptorGridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiSelectRootGridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridPositionData.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/SingleSelectRootGridEntry.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridTests.cs
Primarily focusing on local variable names for this iteration.
=> Clean up PropertyGrid entries

pkg/Microsoft.Private.Winforms/sdk/dotnet-wpf/Microsoft.NET.SDk.WindowsDesktop.WindowsForms.props, pkg/Microsoft.Private.Winforms/sdk/dotnet-wpf/Microsoft.NET.SDk.WindowsDesktop.WindowsForms.targets
Rename Windows Forms props/targets referenced through Windows Desktop as per agreed convention with @ryalanms 
Unblocks https://github.com/dotnet/wpf/pull/4779
=> Rename Windows Forms props/targets

eng/common/templates/job/onelocbuild.yml
Disable auto triggering loc PRs
=> disable loc PR.

src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationGeneratorTests.cs, src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.GenerateInitialize_DefaultFont=Tahoma.verified.txt, src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.GenerateInitialize_DefaultFont=default.verified.txt, src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.GenerateInitialize_DefaultFont=null.verified.txt, src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.GenerateInitialize_EnableVisualStyles=false.verified.txt, src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.GenerateInitialize_EnableVisualStyles=true.verified.txt, src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.GenerateInitialize_UseCompTextRendering=false.verified.txt, src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.GenerateInitialize_UseCompTextRendering=true.verified.txt, src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/MockData/ApplicationConfigurationGeneratorTests.GenerateInitialize_default_boilerplate.cs, src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/MockData/ApplicationConfigurationGeneratorTests.GenerateInitialize_default_top_level.cs, src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/MockData/ApplicationConfigurationGeneratorTests.GenerateInitialize_user_settings_boilerplate.cs, src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/MockData/ApplicationConfigurationGeneratorTests.GenerateInitialize_user_top_level.cs, src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/MockData/ApplicationConfigurationInitializeBuilderTests.default_boilerplate.cs, src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/MockData/ApplicationConfigurationInitializeBuilderTests.default_top_level.cs, src/System.Windows.Forms.Analyzers/src/System/Windows/Forms/ApplicationConfig.cs
=> Default to SA instead of PMv2 for ApplicationConfiguration.Initialize()

src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.ToolTipNativeWindow.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
=> Mechanical cleanup - renamed some variables

Directory.Build.props, global.json, src/System.Windows.Forms.Analyzers.CSharp/src/System/Windows/Forms/Generators/ApplicationConfigurationGenerator.cs, src/System.Windows.Forms.PrivateSourceGenerators/src/System/Windows/Forms/SourceGenerators/EnumValidationGenerator.cs, src/System.Windows.Forms.PrivateSourceGenerators/src/System/Windows/Forms/SourceGenerators/EnumValidationInfo.cs, src/System.Windows.Forms.PrivateSourceGenerators/src/System/Windows/Forms/SourceGenerators/SyntaxReceiver.cs
Relates to https://github.com/dotnet/sdk/issues/19521
Relates to https://github.com/dotnet/sdk/pull/19599
=> Update SDK and opt-in implicit usings

pkg/Microsoft.Private.Winforms/sdk/dotnet-wpf/Microsoft.NET.Sdk.WindowsDesktop.WindowsForms.props, pkg/Microsoft.Private.Winforms/sdk/dotnet-wpf/Microsoft.NET.Sdk.WindowsDesktop.WindowsForms.targets
Relates to https://github.com/dotnet/sdk/issues/19521
Relates to https://github.com/dotnet/sdk/pull/19599
=> Update import of implicit usings

azure-pipelines.yml
=> Add vnext branch to CI builds

src/Microsoft.VisualBasic.Forms/src/PublicAPI.Shipped.txt, src/Microsoft.VisualBasic.Forms/src/PublicAPI.Unshipped.txt, src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
=> Merging public APIs

src/Microsoft.VisualBasic.Forms/src/PublicAPI.Shipped.txt, src/Microsoft.VisualBasic.Forms/src/PublicAPI.Unshipped.txt, src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
Publishing public APIs for the release 6.0.
=> Publishing public APIs

eng/Versions.props
=> Branding for 7.0

eng/Versions.props
=> Branding release/6.0 to RC2

src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewItemCollection.IInnerList.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewItemCollection.cs
- IInnerList interface was extracted to its own file
- No
- No
- Minimal
- Microsoft Windows [Version 10.0.19043.1165]
- .NET SDK 6.0.100-rc.1.21416.15
=> IInnerList interface was extracted to its own file

azure-pipelines.yml, src/System.Windows.Forms/src/System/Windows/Forms/Design/EventsTab.cs, src/System.Windows.Forms/src/System/Windows/Forms/Design/PropertyTab.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.FreezePaintScope.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiSelectRootGridEntry.PropertyMerger.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridTests.cs
=> Pull vnext into main.

eng/Version.Details.xml
=> [release/6.0-rc1] Add Microsoft.Internal.Runtime.WindowsDesktop.Transport dependency for CPD

Directory.Build.targets
=> [release/6.0] Properly set the ref and runtime pack versions

azure-pipelines.yml
porting change on disabling loc into release branches.
=> Disable loc builds from release branch for 6.0 (#5653)

src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.CheckedListBoxAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.CheckedListBoxItemAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.AccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ItemAccessibleObject.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.Designer.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MultipleControls.Designer.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/CheckedListBoxAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/CheckedListBoxItemAccessibleObjectTests.cs
Port from PR #5276
Cherry-pick commit  4ce6b02a85b2315cf706ea606baf9e9563e92ab9 from main
=> Add support UIA provider for CheckedListBox control (#5276 port 6.0)

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/GridItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/IRootGridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/ImmutablePropertyDescriptorGridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiPropertyDescriptorGridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiSelectRootGridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/SingleSelectRootGridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleElement.cs, src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridTests.cs
- Clarify and add documentation
- Validate virtuals and visibility
- Seal some types/methods
Also update VisualStyleElement to code standards. (Still needs broken out into code files.)
=> GridEntry cleanup

src/System.Windows.Forms/src/PublicAPI.Unshipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/Panel.PanelAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/Panel.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Panel.PanelAccessibleObjectTests.cs
- Added and implemented Panel accessible object
**Before update:**
ProviderDescription: "[pid:28324,providerId:0x4909EE Main:Nested [pid:25160,providerId:0x4909EE Main(parent link):Microsoft: MSAA Proxy (unmanaged:uiautomationcore.dll)]; Hwnd(parent link):Microsoft: HWND Proxy (unmanaged:uiautomationcore.dll)]"
**After update:**
ProviderDescription: "[pid:20624,providerId:0xB0CEE Main:Nested [pid:14560,providerId:0xB0CEE Main(parent link):Unidentified Provider (unmanaged:coreclr.dll)]; Hwnd(parent link):Microsoft: HWND Proxy (unmanaged:uiautomationcore.dll)]"
- No
- Minimal
- Unit tests
- CTI team
- Narrator
- Inspect
=> Adding UIA support for Panel

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/CategoryGridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.Notify.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.PaintValueFlags.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/ImmutablePropertyDescriptorGridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiPropertyDescriptorGridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
Removes a number of other virtuals that weren't needed and dials in visibility.
Clarify terminology around notification and value ownership.
=> More changes to GridEntry.

src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
Fixes #4356
-  Added special logic using `CompatibleDC` for lazy `Glyph` rendering. We draw the background (using the  `PropertyGrid.LineColor` property) and the `Glyph` on a temporary `HBitmap`. After that, we process the `Bitmap` by doing a color inverse for the pixels of the `Glyph`. Then we draw the resulting `Bitmap` instead of the `Glyph`.
**After fix:**
**High contrast Black**
**High contrast White**
- No
- Minimal
- Manually 
- .NET Core SDK: 6.0.100-rc.1.21379.2
=> Fix Color contrast ratio of Collapsed icon

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/net5.0/Program.cs
Fixes #5706
- The file was lost in #5609.
- .NET 5.0 app templates will work as expected
- Yes 
- Minimal
=> Restore missing Program.cs

src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildDropDownButtonUiaProvider.cs, src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.ScrollBarChildAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.TrackBarAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.TrackBarChildAccessibleObject.cs
- A minor refactoring: declaration and initialization of some variables were simplified.
- No
- No
- Minimal
=> Small refactoring: variables initialization was simplified

src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.DateTimePickerAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePicker.DateTimePickerAccessibleObjectTests.cs
Port commit dc90a52b6eec69ff6a38cabd60fc83394519c7d2 from `main` to `6.0` (pr #5245)
=> Fix date time picker control must support expand collapse pattern (port 6.0)

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CategoryGridEntryAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ColumnHeader.ListViewColumnHeaderAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ChildAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewButtonCellAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCheckBoxCellAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewColumnHeaderCellAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewImageCellAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewLinkCellAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowHeaderCellAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewSelectedCellsAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewSelectedRowCellsAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTopLeftHeaderCellAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DomainUpDown.DomainItemAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DomainUpDown.DomainItemListAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProvider.ControlItem.ControlItemAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProvider.ErrorWindow.ErrorWindowAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemDetailsAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemListAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemTileAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridView.GridViewListBoxItemAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollBar.ScrollBarChildAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStrip.ToolStripAccessibleObjectWrapperForItemsOnOverflowTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripControlHost.ToolStripControlHostAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripDropDownItemAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripSplitButton.ToolStripSplitButtonExAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripSplitButton.ToolStripSplitButtonUiaProviderTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TrackBar.TrackBarChildAccessibleObjectTests.cs
- Created test files for missing AO classes
- Added test for `ctor` in each test file
- No
- No
- Minimal
=> Created test files for missing ao classes

src/System.Windows.Forms.Analyzers.CSharp/src/AnalyzerReleases.Shipped.md, src/System.Windows.Forms.Analyzers.CSharp/src/AnalyzerReleases.Unshipped.md, src/System.Windows.Forms.Analyzers.CSharp/src/System.Windows.Forms.Analyzers.CSharp.csproj, src/System.Windows.Forms.Analyzers/src/AnalyzerReleases.Shipped.md, src/System.Windows.Forms.Analyzers/src/AnalyzerReleases.Unshipped.md, src/System.Windows.Forms.Analyzers/src/System.Windows.Forms.Analyzers.csproj, src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
=> Publish unshipped APIs

src/System.Windows.Forms.Analyzers.CSharp/src/AnalyzerReleases.Shipped.md, src/System.Windows.Forms.Analyzers.CSharp/src/AnalyzerReleases.Unshipped.md, src/System.Windows.Forms.Analyzers.CSharp/src/System.Windows.Forms.Analyzers.CSharp.csproj, src/System.Windows.Forms.Analyzers/src/AnalyzerReleases.Shipped.md, src/System.Windows.Forms.Analyzers/src/AnalyzerReleases.Unshipped.md, src/System.Windows.Forms.Analyzers/src/System.Windows.Forms.Analyzers.csproj, src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
=> Port Shipped APIs and Analyzer rules

src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/KeyboardToolTipStateMachine.SmEvent.cs, src/System.Windows.Forms/src/System/Windows/Forms/KeyboardToolTipStateMachine.SmState.cs, src/System.Windows.Forms/src/System/Windows/Forms/KeyboardToolTipStateMachine.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolTipTests.Designer.cs, src/System.Windows.Forms/tests/TestUtilities/CommonTestHelperEx.cs, src/System.Windows.Forms/tests/UnitTests/KeyboardTooltipStateMachineTests.cs, src/System.Windows.Forms/tests/UnitTests/OsVersionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ButtonBaseTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/SplitterTests.cs
cherry-pick and merge from 99c9e6c1203bae1a3a108ef590a2d3d63cfea7fe
@Tanya-Solyanik , i went ahead and created this PR. once signed off, will snap.
=> Port : Merge pull request #5424 from Tanya-Solyanik/tooltip-keyboard

eng/Versions.props
=> Branding to 6.0 RTM

src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainItemListAccessibleObject.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DomainUpDown.DomainItemAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DomainUpDown.DomainItemListAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemListAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemTileAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollBar.ScrollBarChildAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TrackBar.TrackBarChildAccessibleObjectTests.cs
- `ListViewItemListAccessibleObject`
- `ListViewItemTileAccessibleObject`
- `DomainItemListAccessibleObject`
- `DomainItemAccessibleObject`
- `ScrollBarChildAccessibleObject`
- `TrackBarChildAccessibleObject`
- No
- No
- Minimal
=> Filling empty test files

azure-pipelines.yml
Enable Loc on RC2 for final localization.
=> Enable Loc on RC2 branch. Will be disabled again.

azure-pipelines.yml
=> Disable loc on main

eng/common/templates/job/onelocbuild.yml
Update branch name for loc build
=> update branch name for loc.

azure-pipelines.yml
=> fix loc pipeline

azure-pipelines.yml
=> Disable Loc on RC2

WinForms.vsconfig, docs/developer-guide.md, src/System.Windows.Forms/tests/IntegrationTests/NativeHost/NativeHost.vcxproj
- Updated NativeHost.PlatformToolset version
-  No
- No
- Minimal
- .NET Core SDK 6.0.100-rc.1.21430.12
=> Updating NativeHost.PlatformToolset version

azure-pipelines.yml
=> Enable Loc on main

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-CSharp/.template.config/template.json
Porting from #5848.
Removed unnecessary exclude form WinformLibrary template.
=> Merge from 6.0 rc2 :Update template to include *.user file while creating new applications

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripSettingsManagerTests.cs
=> Cleaning up user.config files after test run.

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripSettingsManagerTests.cs
Cleaning up user.config files after test run.
Merge pull request #5859 into release branch
=> [RC2] Clean Configuration Settings file in test

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripSettingsManagerTests.cs
Cleaning up user.config files after test run.
Merge pull request #5859 into release branch
=> [release\6.0] :Cleaning up user.config files after test run.

src/System.Windows.Forms/tests/TestUtilities/ThreadExceptionFixture.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripSettingsManagerTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/UserConfigDisposableFixture.cs
=> Addendum to #5859

src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.DataGridViewCheckBoxCellAccessibleObject.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCheckBoxCellAccessibleObjectTests.cs
Fixes #5886
Port the commit 5ba35d20eaf5d078dcce701f3fb266d9443b731e in PR #5887 to 6.0
=> Fix toggle state of data grid view check box cell ao class - port 6.0

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserNavigatingEventArgs.cs
- Enable nullability in WebBrowserNavigatingEventArgs
=> Enable nullability in WebBrowserNavigatingEventArgs

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/NodeLabelEditEventArgs.cs
- Enable nullability in NodeLabelEditEventArgs
=> Enable nullability in NodeLabelEditEventArgs

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.InvalidActiveXStateException.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.State.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.StateConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.TypeLibraryTimeStampAttribute.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.VBFormat.cs
- Enable nullability in some AxHost classes
=> Enable nullability in some AxHost classes

src/System.Windows.Forms/src/System/Windows/Forms/CachedItemHdcInfo.cs
- Enable nullability in CachedItemHdcInfo
=> Enable nullability in CachedItemHdcInfo

eng/Versions.props
=> Update branding for 5.0.12

src/System.Windows.Forms/src/System/Windows/Forms/ImageList.ImageCollection.cs
- Use generic list in ImageCollection
=> Use generic list in ImageCollection

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/CreateParams.cs
- Enable nullability in CreateParams
=> Enable nullability in CreateParams

eng/Versions.props
=> Servicing branding.

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ColumnHeader.ColumnHeaderImageListIndexer.cs, src/System.Windows.Forms/src/System/Windows/Forms/ColumnHeader.cs
- Enable nullability in ColumnHeader
=> Enable nullability in ColumnHeader

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/BasicDesignerLoader.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.ModifierConverter.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.ModifiersExtenderProvider.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.ModifiersInheritedExtenderProvider.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomLocalizationProvider.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializationProvider.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializer.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerBase.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeMethodMap.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CollectionCodeDomSerializer.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ComponentCache.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ComponentCodeDomSerializer.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ContainerCodeDomSerializer.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/DesignerSerializationManager.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/EnumCodeDomSerializer.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/EventMemberCodeDomSerializer.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ExpressionTable.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/LocalizationCodeDomSerializer.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/PropertyMemberCodeDomSerializer.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourceCodeDomSerializer.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourcePropertyMemberCodeDomSerializer.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/StatementContext.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/TypeCodeDomSerializer.cs
- Contributes to https://github.com/dotnet/winforms/issues/3459
=> Use 'is not null' in some System.Windows.Forms.Design files

eng/Versions.props
=> Update branding for 5.0.13

src/System.Windows.Forms/src/System/Windows/Forms/AutomationMessages.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.Annotated.cs, src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.PageSelector.cs, src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.cs, src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorPage.cs, src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.cs, src/System.Windows.Forms/src/System/Windows/Forms/DrawListViewItemEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/DropTarget.cs, src/System.Windows.Forms/src/System/Windows/Forms/KeyboardToolTipStateMachine.cs, src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/Layout/CommonProperties.cs, src/System.Windows.Forms/src/System/Windows/Forms/Layout/DockAndAnchorLayout.cs, src/System.Windows.Forms/src/System/Windows/Forms/Layout/FlowLayout.cs, src/System.Windows.Forms/src/System/Windows/Forms/Layout/LayoutTransaction.cs, src/System.Windows.Forms/src/System/Windows/Forms/Layout/LayoutUtils.cs, src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.ContainerInfo.cs, src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.cs, src/System.Windows.Forms/src/System/Windows/Forms/MessageBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/Printing/PageSetupDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintControllerWithStatusDialog.BackgroundThread.cs, src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintControllerWithStatusDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs, src/System.Windows.Forms/src/misc/MultitargetUtil.cs, src/System.Windows.Forms/src/misc/WeakHashtable.cs
- Contributes to https://github.com/dotnet/winforms/issues/3459
=> Use 'is not null' in some System.Windows.Forms files

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/net6.0/Program.cs
- Add a comment with a link to docs for the new source-generated API to help developers discover docs and the usage of the API.
- Increased awareness. No code changes.
- None.
=> Add a comment with a link to docs

src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/CheckBoxBaseAdapter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/CheckBoxFlatAdapter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/CheckBoxPopupAdapter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/CheckBoxStandardAdapter.cs
- Enable nullability in CheckBox adapters
=> Enable nullability in CheckBox adapters

src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/ButtonBaseAdapter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/ButtonPopupAdapter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/ButtonStandardAdapter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
Fixes #6021
- The problem is reproduced because the default colors are too low contrast.
- As a fix for the `Popup` button, added logic to darken the current color.
- As a fix for the `Standard` button, added logic for drawing the border with the necessary contrast.
**Notes:**
`Flat` buttons do not need to be fixed as they already have the necessary contrast ratio:
The fix does not affect the `System` button, since the Windows team is responsible for it rendering
<details>
<summary>"Popup" button</summary>
**After fix:**
</details>
<details>
<summary>"Popup" button in the "Hovered" state</summary>
**After fix:**
</details>
<details>
<summary>"Standard" button</summary>
**After fix:**
</details>
- No
- Minimal
- CTI team
- Accessibility …
=> Fixing of the contrast of the borders "Popup" and "Standard" buttons

azure-pipelines.yml
Enable Loc on servicing branch to get it upto date.
=> Enable loc on servicing branch.

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-CSharp/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/.template.config/template.json
* Update template to include *.user file while creating new applications. Helps in recognizing the winforms designer files and be able to open them in designer view.
Fixes https://github.com/dotnet/winforms-designer/issues/3724
=> [6.0][Servicing]Update template to include *.user file while creating new applications

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ScrollBarRenderer.cs
- Enable nullability in ScrollBarRenderer.
=> Enable nullability in ScrollBarRenderer

src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
Fixes two code comments.
None. 
No
Low
=> Fix some comments

src/System.Windows.Forms/src/System/Windows/Forms/Label.LabelImageIndexer.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemImageIndexer.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeImageIndexer.cs
- Enable nullability in some Indexer classes
=> Enable nullability in some Indexer classes

src/System.Windows.Forms/src/System/Windows/Forms/IWin32WindowAdapter.cs
- Enable nullability in IWin32WindowAdapter
=> Enable nullability in IWin32WindowAdapter

src/System.Windows.Forms/src/System/Windows/Forms/Triangle.cs
- Enable nullability in Triangle
=> Enable nullability in Triangle

src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/RadioButtonBaseAdapter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/RadioButtonFlatAdapter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/RadioButtonPopupAdapter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/RadioButtonStandardAdapter.cs
- Enable nullability in RadioButton adapters.
=> Enable nullability in RadioButton adapters

src/System.Windows.Forms/src/misc/CoreSwitches.cs
- Enable nullability on CoreSwitches
=> Enable nullability on CoreSwitches

src/System.Windows.Forms/src/misc/ImageListUtils.cs
- Enable nullability in ImageListUtils
=> Enable nullability in ImageListUtils

src/System.Windows.Forms/src/misc/InvariantComparer.cs
- Enable nullability in InvariantComparer
=> Enable nullability in InvariantComparer

src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXVerbEnum.cs
- Enable nullability in ActiveXVerbEnum.
=> Enable nullability in ActiveXVerbEnum

src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewButtonCell.DataGridViewButtonCellRenderer.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.DataGridViewCheckBoxCellRenderer.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnHeaderCell.DataGridViewColumnHeaderCellRenderer.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.DataGridViewComboBoxCellRenderer.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewHeaderCell.DataGridViewHeaderCellRenderer.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowHeaderCell.DataGridViewRowHeaderCellRenderer.cs
- Enable nullability in various Cell renderers
=> Enable nullability in various Cell renderers

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ComboBoxRenderer.cs
- Enable nullability in ComboBoxRenderer.
=> Enable nullability in ComboBoxRenderer

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.HLSColor.cs, src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlPaintTests.cs
- Enable nullability in ControlPaint
=> Enable nullability in ControlPaint

src/System.Windows.Forms/src/System/Windows/Forms/Command.cs
- Enable nullability in Command
=> Enable nullability in Command

src/System.Windows.Forms/src/System/Windows/Forms/DCMapping.cs
- Enable nullability in DCMapping.
=> Enable nullability in DCMapping

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/TrackBarRenderer.cs
- Enable nullability in TrackBarRenderer
=> Enable nullability in TrackBarRenderer

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ProgressBarRenderer.cs
- Enable nullability in ProgressBarRenderer.
=> Enable nullability in ProgressBarRenderer

src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.FlatComboAdapter.cs
- Enable nullability in FlatComboAdapter.
=> Enable nullability in FlatComboAdapter

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapter.cs
- Enable nullability in ToolStripComboBoxFlatComboAdapter
=> Enable nullability in ToolStripComboBoxFlatComboAdapter

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/DropDownButton.DropDownButtonAdapter.cs
- Enable nullability in DropDownButtonAdapter
=> Enable nullability in DropDownButtonAdapter

src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXFontMarshaler.cs
- Enable nullability in ActiveXFontMarshaler.
=> Enable nullability in ActiveXFontMarshaler

eng/Versions.props
=> Update branding to 6.0.2

eng/Versions.props
=> Update branding to 5.0.14

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.EnumDisplaySettingsW.cs, src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/SystemInformation.cs
- Enable nullability in SystemInformation
=> Enable nullability in SystemInformation

src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2Enum.cs
- Enable nullability in Com2Enum
=> Enable nullability in Com2Enum

src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserUriTypeConverter.cs
- Enable nullability in WebBrowserUriTypeConverter.
=> Enable nullability in WebBrowserUriTypeConverter

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/Timer.cs
- Enable nullability in Timer.
=> Enable nullability in Timer

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ChildAccessibleObject.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ChildAccessibleObjectTests.cs
- Enable nullability in ChildAccessibleObject
=> Enable nullability in ChildAccessibleObject

src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.OleGetClipboard.cs, src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.OleSetClipboard.cs, src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/Clipboard.cs
- Enable nullability in Clipboard.
=> Enable nullability in Clipboard

azure-pipelines.yml
=> Disable loc on release

azure-pipelines.yml
=> Enable loc on main.

NuGet.config, eng/Version.Details.xml, eng/Versions.props, global.json
=> Merging internal commits for release/6.0

src/System.Windows.Forms/src/System/Windows/Forms/ArrangedElement.cs, src/System.Windows.Forms/src/System/Windows/Forms/Layout/IArrangedElement.cs
- Enable nullability in ArrangedElement and IArrangedElement
=> Enable nullability in ArrangedElement and IArrangedElement

src/System.Windows.Forms/src/System/Windows/Forms/Control.AxSourcingSite.cs
- Enable nullability in AxSourcingSite
=> Enable nullability in AxSourcingSite

src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MdiChild.Designer.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MdiChild.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MdiParent.cs
Added test cases from the PR #6239 as discussed in this comment https://github.com/dotnet/winforms/pull/6239#pullrequestreview-822243910.
=> Adding MDI test cases to internal test app

src/System.Windows.Forms/src/System/Windows/Forms/LinkLabelLinkClickedEventHandler.cs
- Enable nullability in LinkLabelLinkClickedEventHandler
=> Enable nullability in LinkLabelLinkClickedEventHandler

src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutSettings.ControlInformation.cs
- Enable nullability in ControlInformation.
=> Enable nullability in ControlInformation

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/TabPage.TabPageControlCollection.cs
- Enable nullability in ControlCollection.
=> Enable nullability in ControlCollection

src/System.Windows.Forms/src/System/Windows/Forms/HelpInfo.cs
- Enable nullability in HelpInfo.
=> Enable nullability in HelpInfo

src/System.Windows.Forms/src/System/Windows/Forms/ArraySubsetEnumerator.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeCollection.cs
- Enable nullability in ArraySubsetEnumerator.
=> Enable nullability in ArraySubsetEnumerator

src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserHelper.cs
- Enable nullability in WebBrowserHelper
=> Enable nullability in WebBrowserHelper

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/OpacityConverter.cs
- Enable nullability in OpacityConverter.
=> Enable nullability in OpacityConverter

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeConverter.cs
- Enable nullability in TreeNodeConverter.
=> Enable nullability in TreeNodeConverter

src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupConverter.cs
- Enable nullability in ListViewGroupConverter
=> Enable nullability in ListViewGroupConverter

src/System.Windows.Forms/src/System/Windows/Forms/SpecialFolderEnumConverter.cs
- Enable nullability in SpecialFolderEnumConverter.
=> Enable nullability in SpecialFolderEnumConverter

src/System.Windows.Forms/src/System/Windows/Forms/AutomationMessages.cs
- Enable nullability in AutomationMessages.
=> Enable nullability in AutomationMessages

src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutSettings.StyleConverter.cs
- Enable nullability in StyleConverter.
=> Enable nullability in StyleConverter

src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowConverter.cs
- Enable nullability in DataGridViewRowConverter.
=> Enable nullability in DataGridViewRowConverter

src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.IconRegion.cs
- Enable nullability in IconRegion.
=> Enable nullability in IconRegion

src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.DataGridViewMouseEvent.cs
- Enable nullability in DataGridViewMouseEvent.
=> Enable nullability in DataGridViewMouseEvent

src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.MouseClickInfo.cs
- Enable nullability in MouseClickInfo.
=> Enable nullability in MouseClickInfo

src/System.Windows.Forms/src/System/Windows/Forms/LinkUtilities.cs
- Enable nullability in LinkUtilities.
=> Enable nullability in LinkUtilities

src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewNativeItemCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
- Use generic list in ListView.
=> Use generic list in ListView

src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.EnumChildren.cs
- Enable nullability in EnumChildren.
=> Enable nullability in EnumChildren

src/System.Windows.Forms/src/System/Windows/Forms/ImageListConverter.cs
- Enable nullability in ImageListConverter.
=> Enable nullability in ImageListConverter

src/System.Windows.Forms/src/System/Windows/Forms/IKeyboardToolTip.cs
- Enable nullability in IKeyboardToolTip.
=> Enable nullability in IKeyboardToolTip

src/System.Windows.Forms/src/System/Windows/Forms/ListBox.SelectedIndexCollection.SelectedIndexEnumerator.cs
- Enable nullability in SelectedIndexEnumerator.
=> Enable nullability in SelectedIndexEnumerator

src/System.Windows.Forms/src/System/Windows/Forms/DataObject.FormatEnumerator.cs
- Enable nullability in FormatEnumerator.
=> Enable nullability in FormatEnumerator

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CheckBoxTests.cs
- Looks like the corresponding issue has been resolved.
=> Uncomment IsHandleCreated asserts

src/System.Windows.Forms/src/System/Windows/Forms/DisplayInformation.cs
- Enable nullability in DisplayInformation.
=> Enable nullability in DisplayInformation

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/Microsoft.Dotnet.Winforms.ProjectTemplates.csproj
Until the issue discussed here  https://github.com/dotnet/winforms/pull/6319#discussion_r773423442 resolved.
related to #6319
=> Disable template localizer tool

src/System.Windows.Forms/src/System/Windows/Forms/Datagridview.DisplayedBandsData.cs
- Enable nullability in DisplayedBandsData.
=> Enable nullability in DisplayedBandsData

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/DockingAttribute.cs
- Enable nullability in DockingAttribute.
=> Enable nullability in DockingAttribute

src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.GetModuleHandle.cs, src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/SendKeys.cs
- Enable nullability in SendKeys.
=> Enable nullability in SendKeys

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/LinkConverter.cs
- Enable nullability in LinkConverter.
=> Enable nullability in LinkConverter

src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- Use generic queue in Control.
=> Use generic queue in Control

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Drawing/Design/UITypeEditor.cs
- Enable nullability in UITypeEditor.
=> Enable nullability in UITypeEditor

src/System.Windows.Forms/src/System/Windows/Forms/ImageList.ImageCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs
- Use generic list in ImageList.
=> Use generic list in ImageList

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/FeatureSupport.cs, src/System.Windows.Forms/src/System/Windows/Forms/IFeatureSupport.cs
- Enable nullability in FeatureSupport and IFeatureSupport.
=> Enable nullability in FeatureSupport and IFeatureSupport

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/FeatureSupport.cs, src/System.Windows.Forms/src/System/Windows/Forms/OSFeature.cs
- Enable nullability in OSFeature.
- Addresses post-merge feedback in https://github.com/dotnet/winforms/pull/6465.
=> Enable nullability in OSFeature

src/System.Windows.Forms/src/System/Windows/Forms/WinCategoryAttribute.cs
- Enable nullability in WinCategoryAttribute.
=> Enable nullability in WinCategoryAttribute

src/System.Windows.Forms/src/System/Windows/Forms/MouseHoverTimer.cs
- Enable nullability in MouseHoverTimer.
=> Enable nullability in MouseHoverTimer

src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PrintPreviewDialogTests.cs
Froze #6501
- Problematic test  in _main_ `System.Windows.Forms.UITests.PrintPreviewDialogTests`
is ignored for now.
=> Marked problematic test with "Skip" attribute

eng/Versions.props
=> Branding for 7.0 Preview 1

eng/Versions.props
=> Branding main branch to Preview2

src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PrintPreviewDialogTests.cs
Froze #6501
- Problematic test  in _main_ `System.Windows.Forms.UITests.PrintPreviewDialogTests`
is ignored for now.
=> Marked problematic PrintPreviewDialog tests with "Skip" attribute

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/Button.cs, src/System.Windows.Forms/src/System/Windows/Forms/IButtonControl.cs
- Enable nullability in Button and IButtonControl.
=> Enable nullability in Button and IButtonControl

azure-pipelines.yml
=> Replaces deprecated build image

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/Layout/LayoutEngine.cs
- Enable nullability in LayoutEngine.
=> Enable nullability in LayoutEngine

src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.ContainerInfo.cs
- Enable nullability in ContainerInfo.
=> Enable nullability in ContainerInfo

docs/debugging.md
Repository target `net7.0` now, so I change paths, so for newcomers would be easier to just copy-paste
=> Update dev instruction to .NET 7

src/System.Windows.Forms/src/System/Windows/Forms/AxHost.EnumUnknown.cs
- Enable nullability in EnumUnknown.
=> Enable nullability in EnumUnknown

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSystemRenderer.cs
- Enable nullability in ToolStripSystemRenderer.
=> Enable nullability in ToolStripSystemRenderer

src/System.Windows.Forms/src/System/Windows/Forms/DataStreamFromComStream.cs
- Enable nullability in DataStreamFromComStream.
=> Enable nullability in DataStreamFromComStream

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ItemArray.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListControl.cs
- Enable nullability in ListControl.
=> Enable nullability in ListControl

eng/Versions.props
=> Update branding to 6.0.3

eng/Versions.props
=> Update branding to 5.0.15

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/DetailsButton.DetailsButtonAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/DetailsButton.cs
- Enable nullability in DetailsButton.
=> Enable nullability in DetailsButton

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintDialog.cs
- Enable nullability in PrintDialog.
=> Enable nullability in PrintDialog

src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.IOleInPlaceFrame.cs, src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.IOleInPlaceUIWindow.cs, src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.IPropertyBag.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.PropertyBagStream.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
- Enable nullability in ActiveXImpl.
=> Enable nullability in ActiveXImpl

src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildDropDownButtonUiaProvider.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildEditUiaProvider.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildTextUiaProvider.cs
- Enable nullability in ComboBox Uia providers.
=> Enable nullability in ComboBox Uia providers

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ProgressBar.cs
- Enable nullability in ProgressBar.
=> Enable nullability in ProgressBar

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/DisplayInformation.cs, src/System.Windows.Forms/src/System/Windows/Forms/Screen.cs, src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/TabControlTests.cs
- Enable nullability in Screen.
=> Enable nullability in Screen

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ListBindingConverter.cs
- Enable nullability in ListBindingConverter.
=> Enable nullability in ListBindingConverter

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ImageKeyConverter.cs
- Enable nullability in ImageKeyConverter.
=> Enable nullability in ImageKeyConverter

src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DataGridViewTest.Designer.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DataGridViewTest.cs
This is a follow up on https://github.com/dotnet/winforms/pull/6498
=> added hidden column and row to a DGV in the integration test

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.DockPaddingEdges.cs, src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.DockPaddingEdgesConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.cs
- Enable nullability on ScrollableControl.
=> Enable nullability on ScrollableControl

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.SelectedIndexCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.SelectedObjectCollection.cs
- Enable nullability in SelectedIndexCollection and SelectedObjectCollection.
=> Enable nullability in SelectedIndexCollection and SelectedObjectCollection

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs, src/System.Windows.Forms/src/System/Windows/Forms/ImageList.Indexer.cs, src/System.Windows.Forms/src/System/Windows/Forms/Label.LabelImageIndexer.cs
- Enable nullability in ButtonBase.
=> Enable nullability in ButtonBase

src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
Addresses PR feedback at https://github.com/dotnet/winforms/pull/6643#pullrequestreview-876645648
=> Delete unnecessary Regex.IsMatch usage

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/Panel.cs
- Enable nullability in Panel.
=> Enable nullability in Panel

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/DataObject.BitmapBinder.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataObject.DataStore.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataObject.FormatEnumerator.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataObject.OleConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataObject.RestrictedTypeDeserializationException.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/IDataObject.cs, src/System.Windows.Forms/src/misc/CompatibleIComparer.cs
- Enable nullability in DataObject.
=> Enable nullability in DataObject

src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
=> Removed redundant condition

.github/workflows/backport.yml, eng/actions/backport/action.yml, eng/actions/backport/index.js
Enabling a github action on this repo to make it easy to port PR between main and release branches.  Once PR is up on any branch , following comment on the PR will create a backporting PR in the right branch.
Ex: 
PR on main branhc created and need to be ported back to release, need to tell bot with following command 
`/backport to <branch>`
i.e.  /backport to release/6.0
=> Adding github action to backport PRs from main -> Release or release -> main

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/Label.cs
- Enable nullability in Label.
=> Enable nullability in Label

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/GroupBox.cs
- Enable nullability in GroupBox.
=> Enable nullability in GroupBox

src/System.Windows.Forms/src/System/Windows/Forms/Form.AccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.AccessibleObject.cs
- Enable nullability in FormAccessibleObject.
=> Enable nullability in FormAccessibleObject

src/System.Windows.Forms/src/System/Windows/Forms/StatusStrip.StatusStripAccessibleObject.cs
- Enable nullability in StatusStripAccessibleObject.
=> Enable nullability in StatusStripAccessibleObject

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridToolStrip.PropertyGridToolStripAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.ToolStripAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.ToolStripAccessibleObjectWrapperForItemsOnOverflow.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxControlAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.ToolStripDropDownAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownButton.ToolStripDropDownButtonAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItemAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripGrip.ToolStripGripAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.ToolStripMenuItemAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripNumericUpDown.ToolStripNumericUpDownControl.ToolStripNumericUpDownAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripProgressBar.ToolStripProgressBarControlAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitButton .ToolStripSplitButtonUiaProvider.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitButton.ToolStripSplitButtonExAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripStatusLabel.ToolStripStatusLabelAccessibleObject.cs
- Enable nullability in various ToolStrip accessible objects.
=> Enable nullability in various ToolStrip accessible objects

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.Vista.cs, src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
- Enable nullability in FileDialog
=> Enable nullability in FileDialog

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
=> 7.0 preview 2 publishing APIs

eng/Versions.props
=> branding for 7.0 preview 3

src/System.Windows.Forms/src/System/Windows/Forms/SendKeys.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/SendKeysTests.cs
Regression introduced in 90f7c1dd955c51c904efd496731a2394cacf578f.
Fixes #6666
=> Pass SendKeys state by ref

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/Cursor.cs, src/System.Windows.Forms/src/System/Windows/Forms/CursorConverter.cs
- Enable nullability in CursorConverter.
=> Enable nullability in CursorConverter

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/FlowLayoutSettings.cs, src/System.Windows.Forms/src/System/Windows/Forms/LayoutSettings.cs, src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutSettings.cs
- Enable nullability in LayoutSettings, FlowLayoutSettings and TableLayoutSettings.
=> Enable nullability in LayoutSettings, FlowLayoutSettings and TableLayoutSettings

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/DropDownButton.DropDownButtonAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/DropDownButton.cs
- Enable nullability in DropDownButton.
=> Enable nullability in DropDownButton

src/System.Windows.Forms/tests/UnitTests/CheckedListBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
- Added missing unit tests for deleting items from list controls
- No 
- No
- Minimal
- .NET Core SDK: 7.0.0-preview.2.22113.2
=> Added missing unit tests for deleting items from list controls

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ColumnHeader.cs, src/System.Windows.Forms/src/System/Windows/Forms/ItemCheckedEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.ColumnHeaderCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewNativeItemCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.SelectedIndexCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.SelectedListViewItemCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ItemCheckedEventArgsTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
- Enable nullability in ListView.
=> Enable nullability in ListView

azure-pipelines.yml
disable loc on release branch.
=> Disable loc on release to avoid triggering locs

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainItemListAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainUpDownItemCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainUpDownItemCompare.cs, src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.cs
- Enable nullability in DomainUpDown.
=> Enable nullability in DomainUpDown

eng/pipelines/build.yml
Relates to https://github.com/dotnet/arcade/issues/8477
=> Generate SBOM manifest

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/FormCollection.cs
- Enable nullability in FormCollection.
=> Enable nullability in FormCollection

src/System.Windows.Forms/src/System/Windows/Forms/FlatButtonAppearance.cs
- Enable nullability in FlatButtonAppearance.
=> Enable nullability in FlatButtonAppearance

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
- Enable nullability in KeysConverter.
=> Enable nullability in KeysConverter

eng/Versions.props
=> Update branding to 6.0.4

eng/Versions.props
=> Update branding to 5.0.16

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ImageList.ImageCollection.ImageInfo.cs, src/System.Windows.Forms/src/System/Windows/Forms/ImageList.ImageCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ImageList.Original.cs, src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs
- Enable nullability in ImageList.
=> Enable nullability in ImageList

src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHCreateItemFromParsingName.cs, src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHCreateShellItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
=> Do not retreive shell items via built-in COM

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.cs
- Enable nullability in TrackBar.
=> Enable nullability in TrackBar

src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.cs
- Enable nullability in UpDownButtons.
=> Enable nullability in UpDownButtons

src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.AutoCompleteDropDownFinder.cs
- Enable nullability in AutoCompleteDropDownFinder
=> Enable nullability in AutoCompleteDropDownFinder

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/Form.ControlCollection.cs
- Enable nullability in Form.ControlCollection.
=> Enable nullability in Form.ControlCollection

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/PublicAPI.Unshipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs
- Enable nullability in PrintPreviewControl.
=> Enable nullability in PrintPreviewControl

src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxEnumConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2EnumConverter.cs
- Enable nullability in Com2EnumConverter and AxEnumConverter.
=> Enable nullability in Com2EnumConverter and AxEnumConverter

src/System.Windows.Forms.Primitives/src/Interop/VSSDK/Interop.IVsPerPropertyBrowsing.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2ExtendedBrowsingHandler.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2ICategorizePropertiesHandler.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IManagedPerPropertyBrowsingHandler.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IPerPropertyBrowsingHandler.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IProvidePropertyBuilderHandler.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IVsPerPropertyBrowsingHandler.cs
- Enable nullability in some COM2 handlers.
=> Enable nullability in some COM2 handlers

src/System.Windows.Forms/tests/IntegrationTests/NativeHost/NativeHost.vcxproj, src/System.Windows.Forms/tests/InteropTests/NativeTests/CMakeLists.txt
=> Enable additional C/C++ compiler warnings

src/System.Windows.Forms/src/System/Windows/Forms/Layout/PropertyNames.cs
- Enable nullability in PropertyNames.
=> Enable nullability in PropertyNames

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewDialog.cs
- Enable nullability in PrintPreviewDialog.
=> Enable nullability in PrintPreviewDialog

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/Form.ControlCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
=> Enable nullability in Form

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.SendMessageW.cs, src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ObjectCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.SelectedObjectCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListControl.cs
- Enable nullability in ListBox.
=> Enable nullability in ListBox

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/CheckBox.cs
- Enable nullability in CheckBox.
=> Enable nullability in CheckBox

src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.VARIANT.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.Vista.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
- Use ThrowIfFailed extension method where possible.
=> Use ThrowIfFailed extension method where possible

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/Design/PropertyTab.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertiesTab.cs
- Enable nullability in PropertiesTab.
=> Enable nullability in PropertiesTab

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItemCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewSubItemConverter.cs, src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs
- Enable nullability in ListViewSubItem.
=> Enable nullability in ListViewSubItem

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
=> Publish apis for the milestone

eng/Versions.props
=> update branding for milestone

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.cs, src/System.Windows.Forms/tests/UnitTests/CheckedListBoxTests.cs
- Enable nullability in CheckedListBox.
=> Enable nullability in CheckedListBox

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs
- Enable nullability in TextBox.
=> Enable nullability in TextBox

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/FontDialog.cs
- Enable nullability in FontDialog.
=> Enable nullability in FontDialog

src/System.Windows.Forms.Primitives/src/Interop/UiaCore/Interop.UiaRaiseAutomationPropertyChangedEvent.cs, src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs
- Enable nullability in DateTimePicker.
=> Enable nullability in DateTimePicker

docs/release-activity.md
Adding release activities doc to the repo.
=> Add release activities doc

src/System.Windows.Forms/src/System/Windows/Forms/ListViewInsertionMark.cs
- Enable nullability in ListViewInsertionMark.
=> Enable nullability in ListViewInsertionMark

src/System.Windows.Forms/src/System/Windows/Forms/SpecialFolderEnumConverter.SpecialFolderEnumComparer.cs, src/System.Windows.Forms/src/System/Windows/Forms/SpecialFolderEnumConverter.cs
- Move SpecialFolderEnumConverter to a separate file.
=> Move SpecialFolderEnumConverter to a separate file

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.cs
- Enable nullability in MaskedTextBox.
=> Enable nullability in MaskedTextBox

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/GroupBoxRenderer.cs
- Enable nullability in GroupBoxRenderer.
=> Enable nullability in GroupBoxRenderer

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/NumericUpDown.cs
- Enable nullability in NumericUpDown.
=> Enable nullability in NumericUpDown

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/RadioButton.cs
- Enable nullability in RadioButton.
=> Enable nullability in RadioButton

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxComponentEditor.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2ComponentEditor.cs, src/System.Windows.Forms/src/System/Windows/Forms/Design/WindowsFormsComponentEditor.cs
- Enable nullability in some component editors.
=> Enable nullability in some component editors

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/FlowLayoutPanel.cs
- Enable nullability in FlowLayoutPanel.
=> Enable nullability in FlowLayoutPanel

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/Splitter.cs
- Enable nullability in Splitter.
=> Enable nullability in Splitter

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
- Enable nullability in TextBoxBase.
=> Enable nullability in TextBoxBase

src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxContainer.cs
More strict about types used in the app.
=> Replace Hashtable with Dictionary<> in AxContainer

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ThreadExceptionDialog.cs
- Enable nullability in ThreadExceptionDialog.
=> Enable nullability in ThreadExceptionDialog

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.CheckedIndexCollection.cs
- Enable nullability in CheckedIndexCollection.
=> Enable nullability in CheckedIndexCollection

eng/Versions.props
=> Update branding to 6.0.5

eng/Versions.props
=> Update branding to 5.0.17

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.CheckedItemCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ItemArray.cs
- Enable nullability in CheckedItemCollection.
=> Enable nullability in CheckedItemCollection

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.ObjectCollection.cs
- Enable nullability in ObjectCollection.
=> Enable nullability in ObjectCollection

src/System.Windows.Forms/src/System/Windows/Forms/KeyboardToolTipStateMachine.ToolToTipDictionary.cs, src/System.Windows.Forms/src/System/Windows/Forms/KeyboardToolTipStateMachine.cs
- Enable nullability in KeyboardToolTipStateMachine.
=> Enable nullability in KeyboardToolTipStateMachine

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ListView.SelectedIndexCollection.cs
- Enable nullability in SelectedIndexCollection.
=> Enable nullability in SelectedIndexCollection

src/System.Windows.Forms/src/System/Windows/Forms/MDIWindowDialog.ListItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/MDIWindowDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewDialog.cs
- Enable nullability in MdiWindowDialog.
=> Enable nullability in MdiWindowDialog

eng/Versions.props, eng/packageContent.targets
* Update the intellisense version
* Avoid additional copy step
* Avoid race conditions
Closes #6928
Manually verified the content against a previously published microsoft.private.winforms NuGet package.
=> Update the intellisense version

src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlCollection.ControlCollectionEnumerator.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlCollection.cs
- Move ControlCollectionEnumerator to a separate file.
=> Move ControlCollectionEnumerator to a separate file

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/MDIClient.ControlCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/MDIClient.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MdiClientTests.cs
- Enable nullability in MdiClient.
=> Enable nullability in MdiClient

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/SplitterPanel.cs
- Enable nullability in SplitterPanel.
=> Enable nullability in SplitterPanel

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ListView.ColumnHeaderCollection.cs
- Enable nullability in ColumnHeaderCollection.
=> Enable nullability in ColumnHeaderCollection

src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ACNativeWindow.cs
- Use generic dictionary and list in ACNativeWindow.
=> Use generic dictionary and list in ACNativeWindow

src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.DoDragDrop.cs, src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.RegisterDragDrop.cs, src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs, src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DragDropTests.cs, src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs, src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/System.Windows.Forms.UI.IntegrationTests.csproj
=> Pass proper COM interfaces to the drag functions

src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs
- Replace hashtables with generic dictionaries in ErrorProvider.
=> Replace hashtables with generic dictionaries in ErrorProvider

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/SplitContainer.cs, src/System.Windows.Forms/src/System/Windows/Forms/SplitterPanel.cs
- Enable nullability in SplitContainer.
=> Enable nullability in SplitContainer

src/System.Windows.Forms/src/PublicAPI.Shipped.txt
Publishing APIs. Nothing new but keeping them in order generated by tool.
=> Publishing APIs - no new but reordered by running the tool.

src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellLinkedListEnumerator.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewIntLinkedListEnumerator.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowCollection.UnsharingRowEnumerator.cs
- Enable nullability in DataGridView enumerator classes.
=> Enable nullability in DataGridView enumerator classes

eng/CodeAnalysis.src.globalconfig, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SelectionUIService.cs, src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.HDC.cs, src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.HGDIOBJ.cs, src/System.Windows.Forms.Primitives/src/Interop/Interop.COLORREF.cs, src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.LCID.cs, src/System.Windows.Forms.Primitives/src/PublicAPI.Unshipped.txt, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Message.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Padding.cs, src/System.Windows.Forms/src/PublicAPI.Unshipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/BindingMemberInfo.cs, src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.HLSColor.cs, src/System.Windows.Forms/src/System/Windows/Forms/LinkArea.cs, src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutPanelCellPosition.cs
Fixes #7061
- Enable and fix CA1066 warnings in src files.
=> Enable and fix CA1066 warnings in src files

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ListViewHitTestInfo.cs
- Enable nullability in ListViewHitTestInfo.
=> Enable nullability in ListViewHitTestInfo

src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.IGetVBAObject.cs, src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.IOleInPlaceSite.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.OleInterfaces.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
- Enable nullability in OleInterfaces.
=> Enable nullability in OleInterfaces

.github/fabricbot.json
@gpetrou I got tired of applying the label, so this is for you :)
=> Auto-add "area: NRT" label

eng/CodeAnalysis.src.globalconfig, src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Helpers/FileSystemUtils.vb, src/System.Windows.Forms.Primitives/src/Interop/Imm32/Interop.CPS.cs, src/System.Windows.Forms.Primitives/src/Interop/NtDll/Interop.RtlNtStatusToDosError.cs, src/System.Windows.Forms.Primitives/src/Interop/Powrprof/Interop.SetSuspendState.cs, src/System.Windows.Forms.Primitives/src/Interop/SHDocVw/Interop.CSC.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/ThemingScope.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptorRefresh.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2TypeInfoProcessor.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewButtonCell.DataGridViewButtonCellRenderer.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.DataGridViewCheckBoxCellRenderer.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnHeaderCell.DataGridViewColumnHeaderCellRenderer.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.DataGridViewComboBoxCellRenderer.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewHeaderCell.DataGridViewHeaderCellRenderer.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowHeaderCell.DataGridViewRowHeaderCellRenderer.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTopLeftHeaderCell.DataGridViewTopLeftHeaderCellRenderer.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewUtilities.cs, src/System.Windows.Forms/src/System/Windows/Forms/DisplayInformation.cs, src/System.Windows.Forms/src/System/Windows/Forms/Formatter.cs, src/System.Windows.Forms/src/System/Windows/Forms/Layout/CommonProperties.DockAnchorMode.cs, src/System.Windows.Forms/src/System/Windows/Forms/Layout/LayoutUtils.MeasureTextCache.cs, src/System.Windows.Forms/src/System/Windows/Forms/Layout/PropertyNames.cs, src/System.Windows.Forms/src/System/Windows/Forms/LinkUtilities.cs
- Enable and fix CA1052 warnings in src files.
=> Enable and fix CA1052 warnings in src files

src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.LayoutData.cs
- Enable nullability in LayoutData.
=> Enable nullability in LayoutData

src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownEdit.cs
- Enable nullability in UpDownEdit.
=> Enable nullability in UpDownEdit

src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.IOleObject.cs, src/System.Windows.Forms.Primitives/src/Interop/UiaCore/Interop.UiaReturnRawElementProvider.cs, src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- Partially enable nullability in Control.
=> Partially enable nullability in Control

src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/RadioButtonBaseAdapter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/RadioButtonPopupAdapter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/ComNativeDescriptor.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/Layout/DockAndAnchorLayout.cs, src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.cs, src/System.Windows.Forms/src/System/Windows/Forms/StatusStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropTargetManager.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitStackLayout.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
- Remove some unused parameters.
=> Remove some unused parameters

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ColumnHeaderConverter.cs
- Enable nullability in ColumnHeaderConverter.
=> Enable nullability in ColumnHeaderConverter

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ContextMenuStrip.cs
- Enable nullability in ContextMenuStrip.
=> Enable nullability in ContextMenuStrip

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs
- Enable nullability in UpDownBase.
=> Enable nullability in UpDownBase

src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewUtilities.cs
- Enable nullability in DataGridViewUtilities.
=> Enable nullability in DataGridViewUtilities

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/UserControl.cs
- Enable nullability in UserControl.
=> Enable nullability in UserControl

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellStyleConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnConverter.cs
- Enable nullability in some DataGridView converters.
=> Enable nullability in some DataGridView converters

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
- Enable nullability in TabPage.
=> Enable nullability in TabPage

eng/Versions.props
=> Bump Intellisense

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/TreeViewImageKeyConverter.cs
- Enable nullability in TreeViewImageKeyConverter.
=> Enable nullability in TreeViewImageKeyConverter

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/NotifyIcon.cs
- Enable nullability in NotifyIcon.
=> Enable nullability in NotifyIcon

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ToolstripProfessionalRenderer.cs
- Enable nullability in ToolStripProfessionalRenderer.
=> Enable nullability in ToolStripProfessionalRenderer

eng/Versions.props
=> Update branding to 6.0.6

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/CheckBox.CheckBoxAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewTextBox.GridViewTextBoxAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs, src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.TrackBarAccessibleObject.cs
- Enable nullability in some Control members.
=> Enable nullability in some Control members

src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.ReservationGrid.cs
- Enable nullability in ReservationGrid.
=> Enable nullability in ReservationGrid

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripProfessionalLowResolutionRenderer.cs
- Enable nullability in ToolStripProfessionalLowResolutionRenderer.
=> Enable nullability in ToolStripProfessionalLowResolutionRenderer

src/System.Windows.Forms/src/System/Windows/Forms/Layout/CommonProperties.cs, src/System.Windows.Forms/src/System/Windows/Forms/Layout/LayoutTransaction.cs
- Enable nullability in CommonProperties.
=> Enable nullability in CommonProperties

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
- Enable nullability in TabPageCollection.
=> Enable nullability in TabPageCollection

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewTextBox.cs
- Enable nullability in GridViewTextBox.
=> Enable nullability in GridViewTextBox

src/System.Windows.Forms/src/System/Windows/Forms/Label.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/HelpPane.cs
- Enable nullability in HelpPane.
=> Enable nullability in HelpPane

src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.EnumFORMATETCWrapper.cs, src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.IDataObjectVtbl.cs, src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.IEnumFORMATETCVtbl.cs, src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
This is extract of https://github.com/dotnet/winforms/pull/7087 which should help fix https://github.com/dotnet/winforms/pull/6976#discussion_r867278650 and unblock https://github.com/dotnet/winforms/pull/6576
I expect #7087 would take a bit of time if Win 7 support would be required, so I think if fast-track only this part it would bring main in more healthy state.
=> Add IEnumFormatEtc ComWrapper

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ListView.CheckedListViewItemCollection.cs
- Enable nullability in CheckedListViewItemCollection.
=> Enable nullability in CheckedListViewItemCollection

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/LinkArea.LinkAreaConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/LinkArea.cs, src/System.Windows.Forms/src/System/Windows/Forms/LinkConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutPanelCellPosition.cs
- Enable nullability in LinkArea and LinkAreaConverter.
=> Enable nullability in LinkArea and LinkAreaConverter

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ListView.CheckedListViewItemCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.SelectedListViewItemCollection.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListView.CheckedListViewItemCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListView.SelectedListViewItemCollectionTests.cs
- Enable nullability in SelectedListViewItemCollection.
=> Enable nullability in SelectedListViewItemCollection

src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.DataGridViewEditingPanel.cs
- Enable nullability in DataGridViewEditingPanel.
=> Enable nullability in DataGridViewEditingPanel

src/System.Windows.Forms.Primitives/src/PublicAPI.Shipped.txt, src/System.Windows.Forms.Primitives/src/PublicAPI.Unshipped.txt, src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
=> Publishing APIs

azure-pipelines.yml
disable loc in release pipeline for preview 5
=> disable loc on release pipeline.

eng/Versions.props
=> Branding to Preview5

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.cs, src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutPanel.cs, src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutSettings.cs
- Enable nullability in TableLayoutPanel.
=> Enable nullability in TableLayoutPanel

docs/debugging.md
This is required to run sample from https://github.com/kant2002/winforms-modernui using locally built WinForms
=> Document additional assembly which is needed for designer

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/.template.config/template.json
Updating template version to 3.1
fixes: https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1547593
=> Update version to 3.1 in templates

src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.ExtTextOutW.cs, src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.ComponentEditorPageSite.cs, src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.PageSelector.cs, src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.cs
- Enable nullability in ComponentEditorForm.
=> Enable nullability in ComponentEditorForm

eng/Versions.props
=> Update branding to 6.0.7

eng/Versions.props
=> Bump intellisense.

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/.template.config/template.json
=> Fix typo in 3.1 template.

src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
Also tweak the constructors in ControlAccessibleObject to chain them together and roll InitHandle into the constructor.
=> Add some clarifying comments to AccessibleObject

src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.CloseThemeData.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.DrawThemeBackground.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.DrawThemeEdge.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.DrawThemeParentBackground.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.DrawThemeText.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.GetCurrentThemeName.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.GetThemeAppProperties.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.GetThemeBackgroundContentRect.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.GetThemeBackgroundExtent.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.GetThemeBackgroundRegion.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.GetThemeBool.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.GetThemeColor.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.GetThemeDocumentationProperty.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.GetThemeEnumValue.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.GetThemeFilename.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.GetThemeFont.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.GetThemeInt.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.GetThemeMargins.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.GetThemeString.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.GetThemeSysBool.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.GetThemeSysInt.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.GetThemeTextExtent.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.IsAppThemed.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.IsThemeBackgroundPartiallyTransparent.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.IsThemePartDefined.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.OpenThemeData.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.SetThemeAppProperties.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.SetWindowTheme.cs
- Use LibraryImport in some Interop UxTheme.
=> Use LibraryImport in some Interop UxTheme

src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewNativeItemCollection.cs
- Enable nullability in ListViewNativeItemCollection.
=> Enable nullability in ListViewNativeItemCollection

src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.GetErrorInfo.cs, src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.OleCreatePropertyFrame.cs, src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.OleCreatePropertyFrameIndirect.cs, src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.SafeArrayGetVartype.cs, src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.SafeArrayLock.cs, src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.SafeArrayUnlock.cs, src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.SysFreeString.cs, src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.VarFormat.cs
- Use LibraryImport in some Interop Oleaut32.
=> Use LibraryImport in some Interop Oleaut32

src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
This reverts commit 5a3ad18d1a3f25ae2bed8c9c74c24e66a95944e8.
related #6381.  fixes #7201
=> Revert "Fix nested/User control scaling. (#6971)"

src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.CoRegisterMessageFilter.cs, src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.CoRevokeMallocSpy.cs, src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.CreateILockBytesOnHGlobal.cs, src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.DoDragDrop.cs, src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.OleCreatePictureIndirect.cs, src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.OleFlushClipboard.cs, src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.OleInitialize.cs, src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.OleUninitialize.cs, src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.PropVariantClear.cs, src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.RevokeDragDrop.cs
- Use LibraryImport in some Interop Ole32.
=> Use LibraryImport in some Interop Ole32

src/System.Windows.Forms/src/System/Windows/Forms/Application.MarshallingControl.cs
- Enable nullability in MarshalingControl.
=> Enable nullability in MarshalingControl

eng/init-vs-env.cmd, eng/pipelines/build.yml, src/System.Windows.Forms/tests/InteropTests/NativeTests/NativeTests.proj
=> Build with VS 2022 / C++ toolset v143

azure-pipelines-richnav.yml
=> Fix richnav

src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
=> Fixed a typo

eng/Versions.props
=> Update branding to 6.0.8

azure-pipelines.yml
=> Add Win32 feature branch to CI build

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
standard branding step, this was produced by end/APIConpatibility/mark-shipped.cmd
=> Publish APIs for .NET 7.0 preview 7

eng/Versions.props
=> update version to .NET 7 RC1

.github/fabricbot.json
=> Create an RC1 milestone

azure-pipelines.yml
=> Disable localization in the servicing branch for .NET7 preview7

src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutStyle.cs
- Enable nullability in TableLayoutStyle.
=> Enable nullability in TableLayoutStyle

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripContainer.cs
- Enable nullability in ToolStripContainer.
=> Enable nullability in ToolStripContainer

src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxPropertyTypeEditor.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyPageUITypeConverter.cs
- Enable nullability in AxPropertyTypeEditor.
=> Enable nullability in AxPropertyTypeEditor

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ImageIndexEditor.cs, src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/RelatedImageListAttribute.cs, src/System.Windows.Forms/src/misc/ImageListUtils.cs
- Enable nullability in RelatedImageListAttribute.
=> Enable nullability in RelatedImageListAttribute

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/IBindableComponent.cs
- Enable nullability in IBindableComponent.
=> Enable nullability in IBindableComponent

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.ExceptionEditor.cs
- Enable nullability in ExceptionEditor.
=> Enable nullability in ExceptionEditor

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripGrip.cs
- Enable nullability in ToolStripGrip.
=> Enable nullability in ToolStripGrip

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.cs
- Enable nullability in ToolStripPanel.
=> Enable nullability in ToolStripPanel

eng/Versions.props, src/System.Windows.Forms.Primitives/src/System.Windows.Forms.Primitives.csproj
#7445
Changes based on @AArnott's code in https://github.com/dotnet/winforms/compare/main...AArnott:cswin32
=> CsWin32-UseVersionProps

.github/ISSUE_TEMPLATE/internal-tracking-issue.md
=> Add internal tracking issue template

eng/Versions.props
=> Bump intelli

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/IContainerControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.cs
- Enable nullability in ContainerControl.
=> Enable nullability in ContainerControl

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ISupportOleDropSource.cs, src/System.Windows.Forms/src/System/Windows/Forms/ISupportOleDropTarget.cs
- Enable nullability in IDropTarget and ISupportOleDropSource.
=> Enable nullability in IDropTarget and ISupportOleDropSource

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorPage.cs
- Enable nullability in ComponentEditorPage.
=> Enable nullability in ComponentEditorPage

eng/Versions.props
=> Update branding to 6.0.9

eng/Versions.props
Expected to fix: https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-windowsdesktop/alert/7076334?typeId=6457534
=> Update newtonsoft.json package version for complaince

src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.IDropTargetVtbl.cs
Fixes #7518
Eventually I should improve #7519 but until then, this is safer approach IMO.
cc @Olina-Zhang  @dreddy-work @RussKie
=> Fix drag and drop

.github/fabricbot.json, CONTRIBUTING.md, docs/developer-guide.md, docs/issue-guide.md, docs/roadmap.md
=> Replace "up for grabs" with "help wanted"

azure-pipelines-richnav.yml, azure-pipelines.yml, eng/pipelines/build.yml
Fixes #
- 
- 
- 
- 
- 
- Yes / No
-
- 
- 
- 
-
=> Move to -Svc pool provider in release branch (7.0-rc1)

eng/Version.Details.xml
=> Upgrade VS redist version.

eng/Version.Details.xml, eng/Versions.props
=> Revert "UPgrade VS redist version."

eng/Localize/LocProject.json
Fix Loc build failure in the [pipeline](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdev.azure.com%2Fdnceng%2Finternal%2F_build%2Fresults%3FbuildId%3D1969362%26view%3Dlogs%26j%3Dc2111129-d6a3-58de-e667-00e5a0966c99%26t%3D04624205-1088-500d-206a-392ceb108efa&data=05%7C01%7Cdreddy%40microsoft.com%7Cbf0da489396e43bcdd1508da8ad5db37%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637974948372288605%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C3000%7C%7C%7C&sdata=NgG5EL%2BiI5Ct81cXX6xd1pmKJO9JhK2AeUJ9W%2FW6jdA%3D&reserved=0) that was introduced [here](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fwinforms%2Fpull%2F7604&data=05%7C01%7Cdreddy%40microsoft.com%7Cbf0da489396e43bcdd1508da8ad5db …
=> Fix LocProject to fix Loc build failure in the internal pipeline.

azure-pipelines-richnav.yml, azure-pipelines.yml, eng/pipelines/build.yml
Per the offline email directions
Tested successfully:
* https://dev.azure.com/dnceng/public/_build/results?buildId=1975549&view=results
* https://dev.azure.com/dnceng/internal/_build/results?buildId=1975548&view=results
=> Update build images

azure-pipelines-richnav.yml, azure-pipelines.yml, eng/pipelines/build.yml
Per the offline email directions
Tested successfully:
* https://dev.azure.com/dnceng/public/_build/results?buildId=1975549&view=results
* https://dev.azure.com/dnceng/internal/_build/results?buildId=1975548&view=results
=> Update build images (release/7.0)

azure-pipelines-richnav.yml, eng/common/templates/job/source-build.yml, eng/common/templates/job/source-index-stage1.yml, eng/pipelines/build.yml
This change is required for builds to continue working in the new org, dev.azure.com/dnceng-public.
=> Update public pool names

eng/Versions.props
=> Update branding to 6.0.10

eng/Versions.props
=> Branding to RTM

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-CSharp/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-VisualBasic/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-VisualBasic/.template.config/template.json
Update template point to .NET8.0
=> Update template branding

Directory.Build.props, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/WinformsControlsTest.csproj
... for easy experiments with DPI awareness.
=> Explicitly declare HighDpiMode in the project file for integration test

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DockEditor.DockUI.cs
Fixes #5307
- Changed base type of `DockEditorCheckBox` to `RadioButton`.
- Used solution from `ContentAlignmentEditor.ContentUI` in `DockEditor.DockUI` to work with radio buttons.
- Fixed unit tests.
- A user can see the right type of dock panel's buttons via accessibility tools.
- No
- Minimal
- Manually.
- Unit tests. 
- Inspect
- 8.0.100-alpha.1.22423.9
=> Changing base type of DockEditorCheckBox to RadioButton

Restore.cmd, build.cmd, global.json
=> Use native tools present on the machine rather than bootstraped tools in CI build

azure-pipelines.yml, global.json
=> Update build image

azure-pipelines.yml
=> [release/7.0] Update build image

eng/Localize/LocProject.json
Fix build for https://dev.azure.com/dnceng/internal/_build/results?buildId=2004500&view=results
=> Update loc definitions

docs/testing.md
Relates to https://github.com/dotnet/winforms/pull/7833.
=> Add section on how to run/debug test runner crashes

src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.DoDragDrop.cs
=> Restore back ComWrappers for DoDragDrop

eng/Versions.props
=> Update branding to 6.0.11

eng/CodeAnalysis.src.globalconfig, src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Logging/Log.vb, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerBase.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/TypeCodeDomSerializer.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs, src/System.Windows.Forms/src/System/Windows/Forms/HtmlShim.cs, src/System.Windows.Forms/src/System/Windows/Forms/HtmlShimManager.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemDetailsAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSettingsManager.cs
Related: #7887
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca1854
=> CA1854 Prefer the 'IDictionary.TryGetValue(TKey, out TValue)' method

eng/CodeAnalysis.src.globalconfig, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ComponentCodeDomSerializer.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/AdornerCollection.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CommandSet.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CustomMenuItemCollection.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignBindingValueUIHandler.LocalUIItem.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignBindingValueUIHandler.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/MaskDescriptor.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.ComponentDataObject.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Automation/UiaTextRange.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewBand.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/MdiWindowListStrip.cs
Enables analyzers and refactor.
Related: #7887
=> Enable IDE0020/IDE0029/IDE0054 analyzers

eng/CodeAnalysis.src.globalconfig, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/EventBindingService.EventPropertyDescriptor.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomLocalizationProvider.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializer.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourceCodeDomSerializer.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelCell.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.ToolStripPanelRowControlCollection.cs, src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/CustomControls/CustomButtonDesignerActionList.cs, src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DesignBehaviorsTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObjectTests.cs
Enables IDE0082 'typeof' can be converted  to 'nameof'
Related: #7887
=> Enable IDE0082 'typeof' can be converted  to 'nameof'

eng/CodeAnalysis.src.globalconfig, src/System.Windows.Forms.Analyzers.CSharp/src/System/Windows/Forms/Generators/ApplicationConfigurationGenerator.cs, src/System.Windows.Forms.PrivateSourceGenerators/src/System/Windows/Forms/SourceGenerators/SyntaxReceiver.cs
Enables IDE0170 analyzer and fix occurrences
Related: #7887
=> Enable IDE0170 (simplify property pattern) analyzer and fix occurrences

eng/Versions.props
=> Upgrade Cswin32 Version to 0.2.84-beta

eng/CodeAnalysis.src.globalconfig, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/SiteNestedContainerTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/Behavior/SnapLineTests.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxUiaTextProvider.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewLabelEditUiaTextProvider.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseUiaTextProvider.cs, src/System.Windows.Forms/tests/UnitTests/SerializableTypesTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CursorsTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MessageTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PowerStatusTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ProfessionalColorTableTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ProfessionalColorsTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/VisualStyles/VisualStyleElementTests.cs
Enables IDE0062 Make local function 'static'
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/style-rules/IDE0062
Related: #7887
=> Enable IDE0062 Make local function 'static'

Restore.cmd, azure-pipelines-richnav.yml, azure-pipelines.yml, build.cmd, eng/pipelines/build.yml, global.json
Per the offline email directions. Similar to https://github.com/dotnet/winforms/pull/7694.
=> [release/6.0] Update build images

eng/CodeAnalysis.src.globalconfig, src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownEdit.UpDownEditAccessibleObject.cs
Enable IDE0110 Remove unnecessary discard
Related: #7887
=> Enable IDE0110 (Remove unnecessary discard)

Directory.Build.props, Directory.Build.targets, global.json
Updating build target for Winforms binaries to .NET 8.0.
=> Update TFM for build targets

src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs, src/System.Windows.Forms.Primitives/src/System.Windows.Forms.Primitives.csproj, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/FileDialogCustomPlacesCollection.cs, src/System.Windows.Forms.Primitives/src/Windows/Win32/Foundation/ComScope.cs, src/System.Windows.Forms.Primitives/src/Windows/Win32/System/Com/IUnknown.cs, src/System.Windows.Forms.Primitives/src/Windows/Win32/UI/Shell/IFileDialogCustomize.cs, src/System.Windows.Forms.Primitives/src/Windows/Win32/UI/Shell/IFileDialogEvents.cs, src/System.Windows.Forms.Primitives/src/Windows/Win32/UI/Shell/IFileOpenDialog.cs, src/System.Windows.Forms.Primitives/src/Windows/Win32/UI/Shell/INativeGuid.cs, src/System.Windows.Forms.Primitives/src/Windows/Win32/UI/Shell/IShellItem.cs, src/System.Windows.Forms.Primitives/src/Windows/Win32/UI/Shell/IShellItemArray.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2TypeInfoProcessor.cs, src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/SaveFileDialog.cs
I'll continue to fiddle with the struct to see if I can make these cleaner, but this gets something in place to ensure we Release in all cases.
=> Add ref struct for scoping COM objects

eng/Versions.props, src/System.Windows.Forms.Primitives/src/Windows/Win32/Foundation/BSTR.cs
=> Update to latest CsWin32 drop

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.LinkLabelAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.cs, src/System.Windows.Forms/src/System/Windows/Forms/LinkUtilities.cs
- Enable nullability in LinkLabel.
=> Enable nullability in LinkLabel

eng/Versions.props
=> Update to latest CsWin32

src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/Oleaut32/VARIANTTests.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.AdviseHelper.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.PropertyBagStream.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
Also do some code cleanup in the main class.
Added a couple sanity tests on VARIANT behavior with the .NET runtime.
=> Break out nested classes in Control.ActiveXImpl.

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripLabel.cs
- Enable nullability in ToolStripLabel.
=> Enable nullability in ToolStripLabel

src/System.Windows.Forms/src/System/Windows/Forms/Application.ComponentManager.cs
- Enable nullability in ComponentManager.
=> Enable nullability in ComponentManager

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripProgressBar.cs
- Enable nullability in ToolStripProgressBar.
=> Enable nullability in ToolStripProgressBar

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/MenuStrip.cs
- Enable nullability in MenuStrip.
=> Enable nullability in MenuStrip

src/System.Windows.Forms/src/System/Windows/Forms/MdiControlStrip.ControlBoxMenuItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/MdiControlStrip.SystemMenuItem.cs
- Enable nullability in ControlBoxMenuItem and SystemMenuItem.
=> Enable nullability in ControlBoxMenuItem and SystemMenuItem

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripScrollButton.cs
- Enable nullability in ToolStripScrollButton.
=> Enable nullability in ToolStripScrollButton

src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2AboutBoxPropertyDescriptor.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2ColorConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2ComponentEditor.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2DataTypeToManagedDataTypeConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2Enum.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2EnumConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2ExtendedBrowsingHandler.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2ExtendedTypeConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2ExtendedUITypeEditor.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2FontConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2ICategorizePropertiesHandler.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IDispatchConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IManagedPerPropertyBrowsingHandler.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IPerPropertyBrowsingHandler.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IProvidePropertyBuilderHandler.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IVsPerPropertyBrowsingHandler.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PictureConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2Properties.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyBuilderUITypeEditor.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyPageUITypeConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2TypeInfoProcessor.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/Com2IPerPropertyBrowsingHandler.Com2IPerPropertyBrowsingEnum.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/Com2IPerPropertyBrowsingHandler.Com2IPerPropertyEnumConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/ComNativeDescriptor.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.PropertyBagStream.cs
Basic cleanup. Also a lot of removing redundant comments.
=> Do some code cleanup of COM2 interop classes

src/System.Windows.Forms/src/System/Windows/Forms/MenuTimer.cs
- Enable nullability in MenuTimer.
=> Enable nullability in MenuTimer

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.ToolStripPanelControlCollection.cs
- Enable nullability in ToolStripPanelControlCollection.
=> Enable nullability in ToolStripPanelControlCollection

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripComboBox.cs
- Enable nullability in ToolStripComboBox.
=> Enable nullability in ToolStripComboBox

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripOverflow.cs
- Enable nullability in ToolStripOverflow.
=> Enable nullability in ToolStripOverflow

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.ModalMenuFilter.cs
- Enable nullability in ModalMenuFilter.
=> Enable nullability in ModalMenuFilter

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.Link.LinkAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.Link.cs, src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/CommandsPane.cs
- Enable nullability in Link class.
=> Enable nullability in Link class

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripProgressBar.ToolStripProgressBarControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripProgressBar.ToolStripProgressBarControlAccessibleObject.cs
- Enable nullability in ToolStripProgressBarControl.
=> Enable nullability in ToolStripProgressBarControl

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.FeedbackRectangle.FeedbackDropDown.cs
- Enable nullability in FeedbackDropDown.
=> Enable nullability in FeedbackDropDown

eng/Versions.props
=> Update branding to 7.0.1

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxControlAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxControl.cs
- Enable nullability in ToolStripComboBoxControl.
=> Enable nullability in ToolStripComboBoxControl

eng/common/native/CommonLibrary.psm1, eng/pipelines/azure-pipelines-codeql.yml, eng/pipelines/tsaoptions.json
- Enabling CodeQL for WinForms repo by adding new YML
- CodeQL is increasing the build time hence, scheduled to run weekly and comply with the policy.
- Will be adding new pipeline, new pipeline is going to run on this new YML, scheduled weekly, and separate from regular pipeline.
=> Enable CodeQL in WinForms repo

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/StatusStrip.cs
- Enable nullability in StatusStrip.
=> Enable nullability in StatusStrip

src/System.Windows.Forms/src/System/Windows/Forms/MDIWindowDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/MdiWindowListStrip.cs
- Enable nullability in MdiWindowListStrip.
=> Enable nullability in MdiWindowListStrip

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridToolTip.cs
- Enable nullability in GridToolTip.
=> Enable nullability in GridToolTip

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
- Enable nullability in MonthCalendar.
=> Enable nullability in MonthCalendar

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
- Enable nullability in some ToolStripItem members.
=> Enable nullability in some ToolStripItem members

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.HorizontalRowManager.cs
- Enable nullability in HorizontalRowManager.
=> Enable nullability in HorizontalRowManager

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.LinkCollection.cs
- Enable nullability in LinkCollection.
=> Enable nullability in LinkCollection

src/System.Windows.Forms.Primitives/src/Interop/Hhctrl/Interop.HtmlHelpW.cs, src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/Help.cs
=> Enable nullability in Help

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.VerticalRowManager.cs
- Enable nullability in VerticalRowManager.
=> Enable nullability in VerticalRowManager

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/MdiWindowListStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/MenuStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/MenuTimer.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.RestoreFocusMessageFilter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.ModalMenuFilter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitStackDragDropHandler.cs
- Enable nullability in some ToolStrip members.
=> Enable nullability in some ToolStrip members

src/Common/src/Obsoletions.cs, src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
* Suppressed warnings about obsolete types
* Minor cleanup in AccessibleObject
=> Suppressed WFDEV warnings in source

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSeparator.cs
- Enable nullability in ToolStripSeparator.
=> Enable nullability in ToolStripSeparator

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/MdiWindowListStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/MenuTimer.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.ToolStripMenuItemInternalLayout.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.cs
- Enable nullability in ToolStripMenuItem.
=> Enable nullability in ToolStripMenuItem

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.cs
- Enable nullability in DropDownHolder.
=> Enable nullability in DropDownHolder

src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.cs
Missed one use case when fixing https://github.com/dotnet/winforms/pull/8092
=> Disable WFDEV002 warning in source

eng/Versions.props
=> Change PreReleaseVersionLabel to servicing

eng/Versions.props, global.json
=> Update branding to 6.0.12

src/System.Windows.Forms/src/System/Resources/ResXResourceReader.ReaderAliasResolver.cs
- Enable nullability in ReaderAliasResolver.
=> Enable nullability in ReaderAliasResolver

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSettingsManager.cs
- Replace ArrayList with generic list in ToolStripSettingsManager.
=> Replace ArrayList with generic list in ToolStripSettingsManager

src/Common/src/TraceSwitchExtensions.cs
- Add conditional attribute in TraceVerbose.
- Addresses https://github.com/dotnet/winforms/pull/8119#discussion_r1017078952.
=> Add conditional attribute in TraceVerbose

NuGet.config, eng/Version.Details.xml, eng/Versions.props
=> Merging internal commits for release/7.0

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/CategoryGridEntry.cs
- Enable nullability in CategoryGridEntry.
=> Enable nullability in CategoryGridEntry

src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb, src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Network.vb
=> Convert VB ArrayList usage to List<T>

src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxPropertyDescriptor.cs
=> Small refactoring in AxHost.AxPropertyDescriptor.cs

src/System.Windows.Forms.Primitives/src/Interop/UiaCore/Interop.UiaRaiseNotificationEvent.cs, src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs
- Enable nullability in ErrorProvider.
=> Enable nullability in ErrorProvider

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/IComponentEditorPageSite.cs
- Enable nullability in IComponentEditorPageSite.
=> Enable nullability in IComponentEditorPageSite

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/BindingMemberInfo.cs
- Enable nullability in BindingMemberInfo.
=> Enable nullability in BindingMemberInfo

src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
=> Refactor `VisualStyleRenderer` to use `Dictionary` instead of `Hashtable`

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/PbrsForward.BufferedKey.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/PbrsForward.cs
As well as other refactors.
Related: #8140
=> Refactor PbrsForward to use List<T> instead of ArrayList

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ExtenderProviderService.cs
=> Refactor ExtenderProviderService to use List<IExtenderProvider> instead of ArrayList

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerEventService.cs
=> Refactor DesignerEventService to use List<IDesignerHost> instead of ArrayList

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ReferenceService.cs
=> Refactor ReferenceService to use List<T> instead of ArrayList

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs
=> Refactor BehaviorService to use List<T> instead of ArrayList

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/ResizeBehavior.cs
=> Refactor ResizeBehavior to replace ArrayList

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DragAssistanceManager.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DropSourceBehavior.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/ResizeBehavior.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CommandSet.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ComponentTray.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlCommandSet.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.CfCodeToolboxItem.cs
=> Refactor CommandSet and associated classes to use List<T> and Dictionary<TKey, TValue>

NuGet.config, eng/CodeAnalysis.src.globalconfig, eng/CodeStyle.targets, eng/Versions.props
=> Add CSharpIsNull Analyzer

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignSurface.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerHost.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/BasicDesignerLoader.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/HtmlHistory.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.cs, src/System.Windows.Forms/src/System/Windows/Forms/WindowSubclassHandler.cs
=> Use ObjectDisposedException.ThrowIf in more places

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionService.cs
=> Refactor DesignerActionService to replace Hashtable and ArrayList

src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
=> Refactor ToolTip to replace HashTable

src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/Cursor.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
=> Convert more `ObjectDisposedExceptions` to use `ThrowIf`

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/IKeyboardToolTip.cs, src/System.Windows.Forms/src/System/Windows/Forms/KeyboardToolTipStateMachine.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripControlHost.ToolStripControlHostAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
- Enable nullability in remaining ToolStripItem members.
=> Enable nullability in remaining ToolStripItem members

src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
=> Refactor DataGridView to replace HashTable

src/System.Windows.Forms/src/System/Windows/Forms/Application.ModalApplicationContext.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.ParkingWindow.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadWindows.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs
- Enable nullability in some Application classes.
=> Enable nullability in some Application classes

src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutStyleCollection.cs
=> Refactor TableLayoutStyleCollection to use List<TableLayoutStyle> instead of ArrayList

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlCodeDomSerializer.cs
=> Refactor `ControlCodeDomSerializer` to remove `ArrayList`

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGrid.PropertyGridAccessibleObjectTests.cs
Part of #6094
- Add missing unit tests to check the method behavior in PropertyGridAccessibleObject class
- .NET 7.0.0-rc.2.22472.3
- Windows 11
=> Added unit tests for "AccessibleObject.FragmentNavigate" method in PropertyGridAccessibleObject class

eng/CodeAnalysis.src.globalconfig, eng/CodeAnalysis.test.globalconfig, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HtmlDocumentTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HtmlElementTests.cs
Fixes #3459
Should be checked after #8242 and #8243 have been merged.
=> Change CSIsNull to a warning

src/System.Windows.Forms.Design/src/System/Drawing/Design/ToolboxItem.cs
=> Refactor `ToolboxItem` to remove `ArrayList`

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/UndoEngine.cs
=> Refactor `UndoEngine` to remove `ArrayList`/`HashTable`

src/System.Windows.Forms/src/System/Windows/Forms/BindingSource.cs
=> Refactor `BindingSource` to remove `ArrayList`

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlCommandSet.cs
=> Refactor `ControlCommandSet` to remove `ArrayList`/`HashTable`

eng/Versions.props
=> Update branding to 7.0.2

eng/Versions.props
=> Update branding to 6.0.13

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerHost.cs
=> Refactor DesignerHost to use Dictionary<IComponent, IDesigner> instead of Hashtable

src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
=> Refactor `KeysConverter` to remove `ArrayList`

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ExpressionTable.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.ColumnHeaderCollection.cs
=> Refactoring to replace usages of HashTable

src/System.Windows.Forms/src/System/Windows/Forms/AutoCompleteStringCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.ObjectCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewSelectedCellCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewSelectedColumnCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewSelectedRowCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ImageList.ImageCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutStyleCollection.cs
as requested by @JeremyKuhne [here](https://github.com/dotnet/winforms/pull/8207#discussion_r1035150381).
Related to #8140 and #8143
=> Cast InnerList to `IList`

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripControlHost.StubSite.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripControlHostTests.cs
=> Convert `StubSite` to use Dictionary instead of HashTable and Enable Nullability

src/Common/tests/TestUtilities/CommonMemberDataAttribute.cs, src/Common/tests/TestUtilities/CommonTestHelper.cs, src/Common/tests/TestUtilities/CustomConverter.cs, src/Common/tests/TestUtilities/ITestAccessor.cs, src/Common/tests/TestUtilities/ReflectionHelper.cs, src/Common/tests/TestUtilities/System.Windows.Forms.Common.TestUtilities.csproj, src/Common/tests/TestUtilities/TempFile.cs, src/Common/tests/TestUtilities/TestAccessor.cs, src/Common/tests/TestUtilities/TestAccessors.cs, src/Common/tests/TestUtilities/XUnit/UseCultureAttribute.cs
Follow up to https://github.com/dotnet/winforms/pull/8251#discussion_r1030797441
=> Enable nullability for TestUtilities Project

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SelectionUIService.ContainerSelectionUIItem.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SelectionUIService.HitTestInfo.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SelectionUIService.SelectionUIItem.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SelectionUIService.cs
- Refactor `SelectionUIService` to replace usages of `HashTable`
- Refactor classes based on feedback in #8321
Related: #8143
=> Refactor `SelectionUIService` to replace `HashTable` usages

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
- Enable nullability in Application.
=> Enable nullability in Application

src/Common/src/RTLAwareMessageBox.cs
- Enable nullability in RTLAwareMessageBox.
=> Enable nullability in RTLAwareMessageBox

src/System.Windows.Forms/src/System/Windows/Forms/ArrangedElement.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelCell.cs
- Enable nullability in ToolStripPanelCell.
=> Enable nullability in ToolStripPanelCell

src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/SnapLine.cs
- Enable nullability in SnapLine.
=> Enable nullability in SnapLine

src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IManagedPerPropertyBrowsingHandler.cs
=> Refactor Com2IManagedPerPropertyBrowsingHandler to replace ArrayList with List<Atrribute>

src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.IGetOleObject.cs, src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.IExtender.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxContainer.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.OleInterfaces.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripOverflow.ToolStripOverflowAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripScrollButton.ToolStripScrollButtonAccessibleObjectTests.cs
Null annotate AxContainer and clean up some related AxHost/Control bits.
=> Null annotate AxContainer

src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt, src/System.Windows.Forms.Design/src/System/Resources/Tools/ITargetAwareCodeDomProvider.cs, src/System.Windows.Forms.Design/src/System/Runtime/InteropServices/UCOMITypeLib.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Automation/IAutomationLiveRegion.cs
Enable Nullability on a couple of Interfaces
Related: #8342
=> Enable Nullability on a couple of Interfaces

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/BindingNavigator.cs
- Enable nullability in BindingNavigator.
=> Enable nullability in BindingNavigator

src/System.Windows.Forms/src/System/Windows/Forms/MergeHistory.cs
- Enable nullability in MergeHistory.
=> Enable nullability in MergeHistory

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/HelpProvider.cs
- Enable nullability in HelpProvider.
=> Enable nullability in HelpProvider

eng/Versions.props
=> Update branding to 7.0.3

eng/Versions.props
=> Update branding to 6.0.14

src/System.Windows.Forms.Design/src/Resources/SR.resx, src/System.Windows.Forms.Design/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ExceptionCollection.cs
=> Follow up to change ArgumentException to use string.Format

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/SingleSelectRootGridEntry.cs
- Enable nullability in SingleSelectRootGridEntry.
=> Enable nullability in SingleSelectRootGridEntry

src/System.Windows.Forms/src/System/Windows/Forms/Formatter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.cs
- Enable nullability in Formatter.
=> Enable nullability in Formatter

src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.ControlItem.ControlItemAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.ControlItem.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProvider.ControlItem.ControlItemAccessibleObjectTests.cs
- Enable nullability in ControlItem.
=> Enable nullability in ControlItem

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutStyleCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItemCollection.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TableLayoutStyleCollectionTests.cs
Use List<T>.Remove return value to confirm ownership and then return if false to avoid any clean-up that should not take place.
Fixes #2750
=> Refactor collection remove methods to fix ownership issues

src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowHeaderCell.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlPaintTests.cs
Fixes #7722
- Added a `ControlPaint.CreateBitmapWithInvertedForeColor` method for inverting colors of the bitmap if the image's primary color has low contrast with a background.
- Used the `ControlPaint.CreateBitmapWithInvertedForeColor` method for `DataGridViewRowHeaderCell` images if HC mode is on.
- Covered the `ControlPaint.CreateBitmapWithInvertedForeColor` method with unit tests.
- Images in `DataGridViewRowHeaderCell` become more clear.
- No
- Minimal
- Manually
- AI
- Unit testing
- AI
- .NET SDK:
=> Making `DataGridView` icons more clear

azure-pipelines.yml
Updating Loc flag by reading branch name.
=> Update LOC flag dynamically.

azure-pipelines.yml
=> Fix LOC dynamically.

eng/Versions.props
=> Branding to Preview 1 in Release branch

eng/Versions.props
=> Branding to Preview 2 on main

azure-pipelines.yml
=> Enable in-build signing based on branch

azure-pipelines.yml
=> [release/8.0-preview1] Enable in-build signing based on branch

src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
=> Fix `KeyUp` event on `Listview` control

.github/fabricbot.json
=> Removing invalid labels from closed/merged PRs

eng/Versions.props
=> Update branding to 7.0.4

eng/Versions.props
=> Update branding to 6.0.15

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComponentModel/Com2Interop/COM2FontConverterTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComponentModel/Com2Interop/COM2PictureConverterTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ActiveXFontMarshallerTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MenuStripTests.cs, src/System.Windows.Forms/tests/UnitTests/Text/FontMetrics.cs
Related to https://github.com/dotnet/winforms/issues/8607
=> Skip some more flaky tests that are being investigated

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.FeedbackRectangle.cs
- Enable nullability in FeedbackRectangle
=> Enable nullability in FeedbackRectangle

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.PropertyTabCollection.cs
- Enable nullability in PropertyTabCollection
=> Enable nullability in PropertyTabCollection

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/KeyboardToolTipStateMachine.cs, src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
- Enable nullability in some ToolTip members.
=> Enable nullability in some ToolTip members

src/System.Windows.Forms/src/misc/WeakHashtable.cs
=> Refactor `WeakHashtable` to replace `ArrayList`

src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewBand.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellStyle.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/Label.cs, src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
- Use ContainsObjectThatIsNotNull in more places.
=> Use ContainsObjectThatIsNotNull in more places

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.cs
=> Replace `Hashtable` with `Dictonary` in `OleDragDropHandler`

src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
=> Refactor `ListView` to replace `ArrayList`

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Drawing/Design/IPropertyValueUIService.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellLinkedListElement.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewSelectedColumnCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewSelectedRowCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxColumn.cs, src/System.Windows.Forms/src/System/Windows/Forms/Design/IUIService.cs, src/System.Windows.Forms/src/System/Windows/Forms/HtmlWindow.HTMLWindowEvents2.cs, src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.LayoutInfo.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListManagerBindingsCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/MDIClient.ControlCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/ImmutablePropertyDescriptorGridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MergePropertyDescriptor.MultiMergeCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/TabControl.ControlCollection.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.ControlCollectionTests.cs
=> Enable nullability in more small line count files

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/ContainerSelectorBehavior.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DropSourceBehavior.BehaviorDataObject.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DropSourceBehavior.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/SelectionManager.cs
=> Refactor `DropSourceBehaviour` and related code to replace `ArrayList` with `List<T>`

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.CfCodeToolboxItem.cs
=> Enable nullability and refactor `CfCodeToolboxItem` to replace `Hashtable` with `Dictionary`

src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
As the issue mentions that the PR sizes should be manageable, I chose to start with one file that sums up all the cases I encountered. I have plenty more changes ready to submit.
static code analysis
8.0.100-preview.1.23115.2, but I failed to run the tests locally...
=> Use interpolated strings in Control.cs

eng/Versions.props
=> Branding for Preview 3
