- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
- src/System.Windows.Forms/src/System/Windows/Forms/MDIClient.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.ToolStripTextBoxControl.cs
Making sure we call `AdjustWindowRectExForDpi` only on supported OS. This API is available in Windows 10 and above versions.
Fixes : https://developercommunity.visualstudio.com/t/unable-to-find-an-entry-point-named-Adj/1476945?entry=problem&space=61&q=AdjustWindowRectEx&viewtype=all
related #4797 
fixes #5278
> Fixing Entry not found exception for AdjustWindowRectExForDpi().

- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
- src/System.Windows.Forms/src/System/Windows/Forms/MDIClient.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.ToolStripTextBoxControl.cs
**Proposed changes**
- We recently fixed an issue to support a high DPI scenario that was using the latest Windows API. however, this API was introduced in Windows 10 (version >1607) and was not serviced/down ported back to Windows7. As a result, running Winforms applications targeting .NET 6.0 on Windows 7 are throwing Entry not found exception for API AdjustWindowRectExForDpi(). This change is checking for the OS at runtime before calling this API.
**Customer Impact**
- Customers running .NET 6.0 Winforms applications on Windows 7 with latest .NET 6.0 preview installed.
**Regression?**
- From recent .NET 6.0 preview (6).
**Risk**
- Minimal
> Fixing Entry not found exception for AdjustWindowRectExForDpi(). (#5260)

- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/ClientUtils.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Layout/CommonProperties.cs
Only changes is `Enum.GetValues()` to `Enum.GetValue<TEnum>()`.
Other changes is just to make compiler happy.
This change affects even when compile in reflection mode, I see other opportinities where reflection can be trimmed.
> Fix which unblock usage of debug builds in NativeAOT

- src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObject.cs
Fixes #5033
- The issue is reproduced because each time we get the Accessibility object, we calculate the current index of the ListViewItemAccessibleObject and the index to get the next / previous ListViewItem. Both operations use a loop that checks all the ListViewItem in order to find the one we want. Unfortunately, when we have 1 million ListViewItem, this approach becomes too laborious.
- Fixed the logic for getting indices, now we use the element's index instead of calculating it every time 
**After fix:**
- Yes
- Minimal
- Manually 
- CTI team
- Narrator
- Inspect
- .NET Core SDK: 6.0.0-preview.7.21352.2
> Fixing freezing ListView in virtual mode when Accessibility Tool is active

- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ObjectCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Combobox.ObjectCollectionTests.cs
- Added "IsAccessibilityObjectCreated" property
- The "IsAccessibilityObjectCreated" property is needed to get data about whether an accessibility object has been created. Currently, we only have access to the accessibility object through the "AccessibilityObject" property, which forces the accessibility object to be created when we try to access it. The "IsAccessibilityObjectCreated" property will help avoid using memory by unnecessary accessibility objects and prevent execution of unnecessary code when external accessibility tools are not active
- No
- No
- Minimal
- .NET Core SDK: 6.0.0-preview.7.21352.2
> Adding "IsAccessibilityObjectCreated" property

- src/System.Windows.Forms.Design/src/Resources/SR.resx
- src/System.Windows.Forms.Design/src/Resources/xlf/SR.cs.xlf
- src/System.Windows.Forms.Design/src/Resources/xlf/SR.de.xlf
- src/System.Windows.Forms.Design/src/Resources/xlf/SR.es.xlf
- src/System.Windows.Forms.Design/src/Resources/xlf/SR.fr.xlf
- src/System.Windows.Forms.Design/src/Resources/xlf/SR.it.xlf
- src/System.Windows.Forms.Design/src/Resources/xlf/SR.ja.xlf
- src/System.Windows.Forms.Design/src/Resources/xlf/SR.ko.xlf
- src/System.Windows.Forms.Design/src/Resources/xlf/SR.pl.xlf
- src/System.Windows.Forms.Design/src/Resources/xlf/SR.pt-BR.xlf
- src/System.Windows.Forms.Design/src/Resources/xlf/SR.ru.xlf
- src/System.Windows.Forms.Design/src/Resources/xlf/SR.tr.xlf
- src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hans.xlf
- src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hant.xlf
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/AnchorEditor.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/AnchorEditorTests.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ContentAlignmentEditorTests.cs
Fixes #4102
- Rework LocalizedControlType of Anchor properties
- No
- No
- Minimal
The `LocalizedControlType` of following property is inconsistent in Inspect:
- For ImageAlign & TextAlign property, it's radio button.
- For Anchor property, it's panel.
- For Dock property, it's check box.
Nothing changes, because they work like a RadioButton and it's already radio button. 
The `LocalizedControlType` of Anchor is check box now. The `DefaultAction` is `Check` or `Uncheck`, and `IsInvokePatternAvailable` is `true`.
Anchor control is pronounced correctly by Narrator (like `Top check box checked` or `unchecked`).
Not resolved for DockEditor due difficulties fixing mistakes appear in narrator announcement for this control. Created new issue #5307 to fix LocalizedControlType …
> Resolving "The LocalizedControlType of ImageAlign/TextAlign/Anchor/Dock property is inconsistent in Inspect" for Anchor property

- src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
Fixes #3059
- During investigation, we found that the orange color from the issue is obtained by inverting the blue (highlighted) color. Unfortunately, orange does not contrast well with most colors. Therefore, during the discussions, it was decided to change the orange color to white. Thus, we get a black and white dotted border that has the necessary contrast with the blue (highlighted) color and the colors that the user can set.
- Added "DrawBlackWhiteFocusRectangle" method. 
- Updated parameters for "DrawFocusRectangle" method.
- Added additional logic to the "GetFocusPen" method to get the required border colors.
**After fix:**
- No
- Minimal
- Manually 
- .NET Core SDK: 6.0.0-preview.7.21363.9
> Fixing color contrast for CheckedListBox

- src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/TestHelpers.cs
- src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests/WinformsControlsTest.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Dialogs.Designer.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Dialogs.cs
In order to make writing tests morepleasant I add shortcuts for operations inside form
That allow me express tests better then just counting tabs and pressing enter.
This currently catches one of issues in #5319
> Add test for opening folder browser dialog

- pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/Company.WinFormsApplication1.vbproj
- pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/Form1.Designer.vb
- pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-VisualBasic/Company.ControlLibrary1.vbproj
- pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-VisualBasic/UserControl1.Designer.vb
When the User tries to create a new Visual Basic .NET 6 WinForms project, a new Project gets created all right, but the resulting project is targeted against .NET 5.
> Fix bug where requested new .NET 6 Visual Basic Project ends up as a .NET 5 project.

- src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObject.cs
Fixes #5033
- The issue is reproduced because each time we get the Accessibility object, we calculate the current index of the ListViewItemAccessibleObject and the index to get the next / previous ListViewItem. Both operations use a loop that checks all the ListViewItem in order to find the one we want. Unfortunately, when we have 1 million ListViewItem, this approach becomes too laborious.
- Fixed the logic for getting indices, now we use the element's index instead of calculating it every time (ported from #5289)
**After fix:**
- Yes
- Minimal
- Manually 
- CTI team
- Narrator
- Inspect
- .NET Core SDK: 6.0.0-preview.7.21352.2
> Fixing freezing ListView in virtual mode when Accessibility Tool is active (port to 5.0)

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnDividerDoubleClickEventArgs.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnEventArgs.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnStateChangedEventArgs.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewColumnStateChangedEventArgsTests.cs
- Enable nullability in DataGridViewColumn EventArgs.
> Enable nullability in DataGridViewColumn EventArgs

- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Fixes #4146.
[Update]: This is now implemented as originally planned.
Wrote a small Test app for this, which should also serve as a guidance for best practice.
It is currently here: https://github.com/KlausLoeffelmann/IsAncestorSiteInDesignMode/blob/main/README.md
Shows where and how to use correctly `DesignMode` and `IsAncestorSiteInDesignMode` for (derived) Forms, UserControls hosted in Forms and Controls:
> Implement IsAncestorSiteInDesignMode.

- src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ItemAccessibleObject.cs
Fixes #5397
- The problem is reproduced because we are caching and then using an obsolete `SystemIAccessibleInternal`. As a result, it can only return data about itself, but not about its descendants. 
- Changed the logic for getting a `SystemIAccessibleInternal`. Now we always get it from the `ListBoxAccessibleObject`, and not store it cached.
**Notes:**
Issue also is reproduced for the .NET Core 5.0
This issue does not lead to exceptions in my custom application (although i see an exception in the test `WinformsControlsTest` application), but blocks the receipt of the following properties:
- DefaultAction
- Help
- Role
- State (if option is not selected)
**After fix:**
- Yes ( .NET Core 5.0)
- Minimal
- CTI team 
- Narrator
- …
> Fixing the issue with getting a ListBox.ItemAccessibleObject.Role

- src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests/WinformsControlsTest.cs
This number reduce count of times the test succeed when it should fail.
I assume this is because of WER doing it's job and process do not exit in time.
When I set 1 sec, each second time test succeed
When I set 1,5 sec, each forth time test succeed
When I set 2 sec seems to be enough.
I suspect that I should add this kind of delay to other similar places.
Related #5319
> Reduce flackiness of the integration tests

- Directory.Build.targets
- src/System.Windows.Forms.Design/src/System/Drawing/Design/ToolboxItem.cs
- src/System.Windows.Forms/src/System/Resources/AssemblyNamesTypeResolutionService.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlVersionInfo.cs
Should fully fix https://github.com/dotnet/runtime/issues/44488
This change turns on the single-file analyzer in the winforms repo, fixes the few real problems that were encountered, and suppresses warnings when issues are addressed.
Full support for single-file publishing in WinForms, with some confidence that all issues are addressed.
- No
Very low.
> Turn on single-file analyzer and fix problems

- eng/Localize/LocProject.json
It looks like #5429 broke an internal localization build step.
The output complains:
> Existing LocProject.json differs from generated LocProject.json. Download LocProject-generated.json and compare them.
This updates the checked in LocProject.json to match what was generated.
> Add templatestrings.json files to LocProject.json

- src/System.Windows.Forms/src/System/Windows/Forms/Design/EventsTab.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Design/PropertyTab.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.FreezePaintScope.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiSelectRootGridEntry.PropertyMerger.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridTests.cs
- Reduce nesting by introducing FreezePaintScope
- Further Reduce nesting in SelectedObjects setter and tweak naming and comments.
- Clean up obtuse EventsTab.GetProperties
> More PropertyGrid related cleanup

- src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ItemAccessibleObject.cs
Fixes #5397
- The problem is reproduced because we are caching and then using an obsolete `SystemIAccessibleInternal`. As a result, it can only return data about itself, but not about its descendants. 
- Changed the logic for getting a `SystemIAccessibleInternal`. Now we always get it from the `ListBoxAccessibleObject`, and not store it cached.
- Ported from #5416
This issue does not lead to exceptions in my custom application (although i see an exception in the test `WinformsControlsTest` application), but blocks the receipt of the following properties:
- DefaultAction
- Help
- Role
- State (if option is not selected)
**After fix:**
- Yes ( .NET Core 5.0)
- Minimal
- CTI team 
- Narrator
- .NET Core SDK: 6.0.100-rc.1.21379.2
> Fixing the issue with getting a ListBox.ItemAccessibleObject.Role (port to .NET Core 5.0)

- global.json
- src/System.Windows.Forms/tests/InteropTests/NativeTests/CMakeLists.txt
Update CMake version that support VS2022 generators.
VS 2022 Preview 3 or above needed ( VS toolset version 143 and above required)
> Update CMake that supports VS 2022

- src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ExtendedStates.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PreProcessControlState.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewListBoxAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewTextBox.GridViewTextBoxAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewTextBox.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewEdit.GridViewEditAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewTextBox.GridViewTextBoxAccessibleObjectTests.cs
PropertyGridView had been gaining virtuals for testing and this wasn't necessary. Sealing the class for perf and maintainability.
Rename GridViewEdit to GridViewTextBox to match typical naming. Also change "Edit" to "EditTextBox" to follow.
Other related code cleanup, including better documentation for Control message preprocessing.
> Seal PropertyGridView

- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/NonNullCollection.cs
- src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/NonNullCollectionTests.cs
- src/System.Windows.Forms/src/System/Windows/Forms/GridItemCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/CategoryGridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntryCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.PropertyGridViewAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
- src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiPropertyGridViewTests/PropertyGridViewRowsAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/PropertyGridView.PropertyGridViewAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/DropDownButton.DropDownButtonAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridTests.cs
Copying NonNullCollection from the designer and use as the base for GridEntryCollection to type the collection and add null safety.
> Add NonNullCollection to Primitives

- src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.DateTimePickerAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePicker.DateTimePickerAccessibleObjectTests.cs
Implemented expand-collapse pattern in DateTimePickerAccessibleObject class
Fixes #4099
- Implemented expand-collapse pattern in `DateTimePickerAccessibleObject` class
- Improve user experience
- Follow accessibility standards
- No
- Minimal
- In the Accessibility Insight tool, an error 'An element of the given ControlType must support the ExpandCollapse pattern' appeared.
- In the inspect tool, the `IsExpandCollapsePattermAvaliable` property value is false.
- In the Accessibility Insight tool, no error 'An element of the given ControlType must support the ExpandCollapse pattern' appeared.
- In the inspect tool, the `IsExpandCollapsePattermAvaliable` property value is true and the `ExpandCollapseExpandCollapseState` property appear.
- Updated notification in narrator.
- …
> Adding support expand-collapse pattern for DateTimePicker

- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabControlAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TabPage.TabAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TabPage.TabPageAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.TabControlAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPage.TabAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPage.TabPageAccessibleObjectTests.cs
Fixes #3058
Related issue: #3421 
- The issue is reproduced because the old logic sometimes returned incorrect results for "NextSibling" and "PreviousSibling", which led to incorrect shortcuts behavior. To fix the issue, UIA support was added in which we return the correct results 
- Added and implemented accessible objects for the TabControl and TabPage
- Fixed issue with Narrator
Shortcuts in some cases did not work for TabControl
**After fix:**
- No
- Minimal
- CTI team
- Unit tests
- Narrator
- Inspect
- .NET Core SDK: 6.0.100-preview.3.21202.5
> Fix UIA navigation for TabControl

- eng/common/templates/job/onelocbuild.yml
Disable loc for main in order to get release branch get updated loc strings.
> disable loc in main in order to get PRs for release branch.

- eng/pipelines/build.yml
I inverted the conditional for tests. Should have been "if in public project, or PR"
> [release/6.0] Fixup test execution conditional

- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Calendar.Designer.cs
Initially this ws based on @JeremyKuhne suggestion made in https://github.com/dotnet/winforms/pull/5201#issuecomment-885210059
> I wouldn't mess with the collections without a clear, measured win. This class originally was using `ArrayList`. `List<DateTime>` is significantly more performant, so we're already way better. Generally speaking the class is way more performant than it used to be as the interop has been cleaned up. The comment in the code should probably be removed.
> 
> There are other things that could be done here if you want to make an improvement:
> 
> * Setting `BoldedDates` should use `AddRange`.
> * WmDateBold could be significantly faster.
>   
>   * There is no need to create a wrapper DateBoldEventArgs class.
>   * BoldDates could also write directly into the buffer …
> cleanup in MonthCalendar

- azure-pipelines.yml
Change in templates, to disable Loc PRs, is being overridden by Arcade. This is the right place to disable Loc build/ PRs on a branch.
Based my conversation with loc team, Loc tools can target only one branch at a time and branch owners need to notify loc team if there is a change in the branch for which loc need to be run. Ideally, we would always be running loc on `main `branches and snapping from there. In some specific cases, like templates, we would need to run localization for the changes/fixes we serviced to `release `branch.
For this to work, and because of limitations in loc tools, Only one branch need to be actively triggering loc build at any point in time. Changing branch needs work from loc team and has an SLA of 1-2 weeks. In our case, the best course of action is to wait …
> Disable loc builds from release branch for 6.0

- src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.CheckedListBoxAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.CheckedListBoxItemAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListBox.AccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ItemAccessibleObject.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.Designer.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MultipleControls.Designer.cs
- src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/CheckedListBoxAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/CheckedListBoxItemAccessibleObjectTests.cs
Related Issue: #3421
- Switched on the `SupportsUiaProviders` property of `CheckedListBox` class.
- Updated uia properties.
- Improving development experience for CheckedListBox control accessibility.
- No
- Minimal
- Manually.
- Unit tests.
- Automation tests.
- Inspect
- Narrator
- .Net SDK version:  6.0.100-rc.1.21377.33
> Add support UIA provider for CheckedListBox control

- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/KeyboardToolTipStateMachine.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ContainerControlTests.cs
Fixes #5128 
- Hide tooltip on container control move and resize
- Keyboard tooltip of Winforms control behavior will be as an expected behavior.
- No
- Minimal
Added hiding on form move and resize
- Manually
- .Net SDK version 6.0.100-rc.1.21408.2
> Hide keyboard tooltip on form move or resize

- src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPage.TabAccessibleObjectTests.cs
Fixes #5571
- The issue is reproduced because the `TabControl` generates an event that switches the focus of the accessibility tool to the `TabControl` after switching between `TabPages`.
- Added `BeginInvoke` method, which allows to send the event about the focusing to the `TabPage` after the focus has switched to `TabControl`.
**After fix:**
- Yes (from #3058 )
- Minimal
- CTI team 
- Narrator
- Inspector
- NET Core SDK 6.0.100-rc.1.21416.15
> Fix the behavior of the Narrator rectangle for TabControl

- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/OsVersion.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
- src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/MainFormControlsTabOrder.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Buttons.Designer.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.Designer.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolTipTests.Designer.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolTipTests.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolTipTests.resx
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolTipTests.cs
If the application does not define dismissal delay, then default behavior on win11 is as follows:
1.  common control tooltip is not dismissed automatically, only by user actions.
2. tooltip can be dismissed by CONTROL key
3. tooltip stays open when mouse hovers over it.
> Support Windows11-style default tooltip behavior.

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSystemRenderer.cs
Fixes #5503
- The issue is reproduced because the `vsRenderer.DrawBackground` method draws the background with the wrong contrast. In addition to this method, logic has been added to draw a solid border with acceptable contrast when the button is focused, pressed or checked
**Before fix:** 
**After fix:**
- No
- Minimal
- CTI team
- .NET Core SDK 6.0.100-rc.1.21416.15
> Fixing ToolStripButton high contrast issue

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSystemRenderer.cs
Fixes #5673
- The issue is reproduced because the `vsRenderer.DrawBackground` method draws the background with the wrong contrast. In addition to this method, logic has been added to draw a solid border with acceptable contrast when the button is focused, pressed or checked
**Before fix:** 
**After fix:**
- Yes / No
- Minimal
- CTI team
- .NET Core SDK 6.0.100-rc.1.21416.15
> Fixing ToolStripButton high contrast issue (port to 6.0)

- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabControlAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TabPage.TabAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TabPage.TabPageAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.TabControlAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPage.TabAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPage.TabPageAccessibleObjectTests.cs
Fixes #5687
Port from: #3058, #5571
Related issue: #3421 
- The issue is reproduced because the old logic sometimes returned incorrect results for "NextSibling" and "PreviousSibling", which led to incorrect shortcuts behavior. To fix the issue, UIA support was added in which we return the correct results 
- Added and implemented accessible objects for the TabControl and TabPage
- Fixed issue with Narrator
- Port from #5380, #5574
Shortcuts in some cases did not work for TabControl
**After fix:**
- No
- Minimal
- CTI team
- Unit tests
- Narrator
- Inspect
- .NET Core SDK: 6.0.100-preview.3.21202.5
> Fix UIA navigation for TabControl (port to 6.0)

- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/OsVersion.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
- src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/MainFormControlsTabOrder.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Buttons.Designer.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.Designer.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolTipTests.Designer.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolTipTests.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolTipTests.resx
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolTipTests.cs
If AutoPopDelay is never set to a non-default, then this tooltip follows the comctl-defined default behavior on win11. (#5422)
* common control tooltip is not dismissed automatically, only by user actions.
* tooltip can be dismissed by CONTROL or ESCAPE keys
* tooltip stays open when mouse hovers over it.
cherry-pick  commit from main - https://github.com/dotnet/winforms/pull/5422/commits/11c9ba1f7b63e34607dd7267a550fd504228853b
On Win11 it will be possible to create tooltips that comply with WCAG2.1
- No
- an expected breaking change in the default behavior, but this change is consistent with the comclt tooltips
manual testing of tooltips with different sets of delays, and manual testing of designer generating code-behind.
> Support Windows11-style default tooltip behavior (port to 6.0)

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripHighContrastRenderer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSystemRenderer.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolStripTests.Designer.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolStripTests.cs
Fixes #5502
- `false` flag is being passed while creating `ToolStripHighContrastRenderer` instance at `ToolStripSystemRenderer`, so after this flag is inverted at `ToolStripHighContrastRenderer`'s constructor, the `FillWhenSelected` flag will be `true` (`ToolStripProfessionalRenderer` already has the same logic) 
- If there's a special overridden renderer for High Contrast theme, then base class should call that renderer's method for rendering backgrounds of `ToolStripButton`, `ToolStripDropDownButton`, `ToolStripSplitButton` (`ToolStripProfessionalRenderer` already has the same logic)  
**Before fix**
**After fix**
- No
- Minimal
- Manually
- Unit tests
- CTI team
- Inspect
> Fixing `ToolStrip` button background rendering in HC theme

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripHighContrastRenderer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSystemRenderer.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolStripTests.Designer.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolStripTests.cs
Fixes #5502
- `false` flag is being passed while creating `ToolStripHighContrastRenderer` instance at `ToolStripSystemRenderer`, so after this flag is inverted at `ToolStripHighContrastRenderer`'s constructor, the `FillWhenSelected` flag will be `true` (`ToolStripProfessionalRenderer` already has the same logic) 
- If there's a special overridden renderer for High Contrast theme, then base class should call that renderer's method for rendering backgrounds of `ToolStripButton`, `ToolStripDropDownButton`, `ToolStripSplitButton` (`ToolStripProfessionalRenderer` already has the same logic)  
- Ported from PR #5614
**Before fix**
**After fix**
- No
- Minimal
- Manually
- Unit tests
- CTI team
- Inspect
.NET SDK …
> Fixing `ToolStrip` button background rendering in HC theme (port to 6.0)

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripButtonTests.Rendering.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripButtonTests.cs
Fixes #5670
- Added rendering tests for ToolStrip buttons
- No
- No
- Minimal
> Issue 5670 tool strip buttons rendering tests

- src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.Link.LinkAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.LinkLabelAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabControlAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ControlAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridTests.cs
Fixes #5702 
- The logic for getting the `AccessKey` property has been moved to the base `ControlAccessibleObject` class.
- Removed the logic to set the `ControlStyles.UseTextForAccessibility` flag to `False` for a `PropertyGrid`, as this changes the behavior of the `AccessKey` property in the `PropertyGrid`, making it different from .NET Framework 4.7.2.
- Added unit test.
**After fix:**
- Yes (regression after tasks listed in the #3421 )
- Minimal
- Manually 
- Unit tests
- Inspect
- .NET Core 6.0.100-rc.1.21430.12
> Fix getting value for "ControlAccessibleObject.AccessKey" property

- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Design/EventsTab.cs
- src/System.Windows.Forms/src/System/Windows/Forms/GridItem.cs
- src/System.Windows.Forms/src/System/Windows/Forms/GridItemType.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/CategoryGridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.Flags.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.GridEntryAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/ImmutablePropertyDescriptorGridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiPropertyDescriptorGridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiSelectRootGridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.ExceptionConverter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/SingleSelectRootGridEntry.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
Change names to "owner" for consistency (instead of "host", "current", etc.).
Other miscellaneous cleanup.
> Normalize more property grid names

- src/System.Windows.Forms/src/Resources/SR.resx
- src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupCollection.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MultipleControls.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListVIew.ListViewAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupCollectionTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Fixes #4044
- Added check in `ListViewGroupCollection` class for `Add`, `AddRange` and `Insert` methods, which prohibits adding a `ListViewGroup` when the `ListView` is in virtual mode.
- Fixed MAUI and unit tests. Added new unit tests. 
Previously, we only threw an error when the `Handle` was created. This happened because when the `Handle` was created we called the `MoveGroupItems` method, in which we called the property enumerator of the `ListViewGroups.Items`, which threw an exception about Virtual Mode.
**After fix:**
Now, when trying to call `Add`, `AddRange` and `Insert` methods for a sheet in virtual mode, we will always check the virtual mode, regardless of whether the `Handle` is created or not.
- No
- Minimal
- CTI team 
- Unit tests
- Microsoft Windows [Version …
> Adding exception when user tries to add group to ListView in virtual mode

- src/System.Windows.Forms/src/Resources/SR.resx
- src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupCollection.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MultipleControls.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListVIew.ListViewAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupCollectionTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Fixes #4044
- Added check in `ListViewGroupCollection` class for `Add`, `AddRange` and `Insert` methods, which prohibits adding a `ListViewGroup` when the `ListView` is in virtual mode.
- Fixed MAUI and unit tests. Added new unit tests. 
- Ported from #5691
Previously, we only threw an error when the `Handle` was created. This happened because when the `Handle` was created we called the `MoveGroupItems` method, in which we called the property enumerator of the `ListViewGroups.Items`, which threw an exception about Virtual Mode.
**After fix:**
Now, when trying to call `Add`, `AddRange` and `Insert` methods for a sheet in virtual mode, we will always check the virtual mode, regardless of whether the `Handle` is created or not.
- No
- Minimal
- CTI team 
- Unit tests
- …
> Adding exception when user tries to add group to ListView in virtual mode (port to 6.0)

- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewTextBox.GridViewTextBoxAccessibleObjectTests.cs
Fixes #5656
The bug repro-steps:
- Create a `PropertyGrid` with `Form` as `SelectedObject`
- Run the app - don't click on the `PropertyGridView`
- Check the Text entry using Inspect - there will be an edit accessible object as a child (incorrect)
- Click any entry (thereby create the edit control) - after that everything is good, the edit acc obj has correct position in the tree and correct properties values.
The fix doesn't allow to create and put EditAccessibleObject to the accessibility tree, if the TextBox control is not created,
because otherwise EditAccessibleObject doesn't get correct native properties, and a user see some AO of not created control.
PropertyGridView EditTextBox creates on the first click on the GridView and if there is a selected GridEntry.
I tried just to …
> Fixing EditTextBox AO position in the PropertyGrid tree

- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewEdit.GridViewEditAccessibleObjectTests.cs
Fixes #5656 
(cherry picked from commit 28e4b7d4ea6a4fb21bc777b83b36e7765e44bd49 and then additional changes were added)
This is a port from #5724. Please see its description for details.
> Fixing EditTextBox AO position in the PropertyGrid tree (port 6.0)

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripButtonTests.Rendering.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripButtonTests.cs
Fixes #5670
- Added rendering tests for ToolStrip buttons
- Ported from PR #5700
- No
- No
- Minimal
> Issue 5670 tool strip buttons rendering tests (port to 6.0)

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
Fixes #3835
- Making sure both Shift and Tab are pressed simultaneously to move focus counter-clockwise (backward).
Pressing `Shift` + `Tab` on `ToolStrip` with `TabStop`=`false`...
- ...before the fix:
- ...after the fix:
- No
- Minimal
- Manual testing 
- Unit tests
.NET SDK 6.0.100-preview.7.21379.14
> Fixing ToolStrip Shift+Tab: now focus turns counter-clockwise

- src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
Fixes #5717
- remove custom temp file name generation. It was using a newly allocated image handle to seed a random number generator, which is both unnecessary overhead and was leaking the image handle.
- no more image handle leaks when assigning background images to list view
- No
- probably none, unless someone relied on the temp file name patterns
- leaking ~3 GDI handles every time the background images was assigned
- no image handle leak
- manual testing and observing GDI object count in task manager
> simplify temp file generation

- src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
Fixes #5717
Port from #5744
- remove custom temp file name generation. It was using a newly allocated image handle to seed a random number generator, which is both unnecessary overhead and was leaking the image handle.
- no more image handle leaks when assigning background images to list view
- No
- probably none, unless someone relied on the temp file name patterns
- leaking ~3 GDI handles every time the background images was assigned
- no image handle leak
- manual testing and observing GDI object count in task manager
> simplify temp file generation (port 6.0)

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
Fixes #3835
- Making sure both Shift and Tab are pressed simultaneously to move focus counter-clockwise (backward).
- Ported from #5726
Pressing `Shift` + `Tab` on `ToolStrip` with `TabStop`=`false`...
- ...before the fix:
- ...after the fix:
- No
- Minimal
- Manual testing 
- Unit tests
.NET SDK 6.0.100-preview.7.21379.14
> Fixing ToolStrip Shift+Tab: now focus turns counter-clockwise (merge to 7.0)

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CheckedListBoxAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DirectionButtonAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DomainUpDownAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/GroupBoxAccessibleObjectTests.cs
Fixes #5746
- Moving unit tests from `AccessibleObjects` folder to make them consistent with other unit tests.
- No
- No
- Minimal
- Unit tests
.NET SDK 7.0.0-alpha.1.21461.7
> Moving units tests from AccessibleObjects folder

- src/System.Windows.Forms/src/System/Drawing/Design/UITypeEditor.cs
- src/System.Windows.Forms/src/System/Windows/Forms/KeyPressEventArgs.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.MeasureTextHelper.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/ArrayElementGridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/CategoryGridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.Flags.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiPropertyDescriptorGridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiSelectRootGridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewTextBox.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/SingleSelectRootGridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
Cleanup work around GridEntry flags.
- Change some methods to properties to better reflect their lack of side-effects.
- Use HasFlag for clarity where possible.
- Fix a brush leak in RedrawExplorerTreeViewClosedGlyph.
- More terminology cleanup for clarity.
> Document more GridEntry flags.

- src/System.Windows.Forms/src/System/Windows/Forms/RadioButton.cs
Fixes #5235
- The issue is reproduced because we are calling the `RaiseAutomationPropertyChangedEvent` method with the wrong parameters.
- Fixed parameters for `RaiseAutomationPropertyChangedEvent` method
**After fix:**
- Yes
- Minimal
- CTI team
- Narrator
- .NET Core SDK 6.0.100-rc.1.21430.12
> Fixing announcement of information about RadioButton

- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/KeyboardToolTipStateMachine.SmEvent.cs
- src/System.Windows.Forms/src/System/Windows/Forms/KeyboardToolTipStateMachine.SmState.cs
- src/System.Windows.Forms/src/System/Windows/Forms/KeyboardToolTipStateMachine.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolTipTests.Designer.cs
- src/System.Windows.Forms/tests/TestUtilities/CommonTestHelperEx.cs
- src/System.Windows.Forms/tests/UnitTests/KeyboardTooltipStateMachineTests.cs
- src/System.Windows.Forms/tests/UnitTests/OsVersionTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ButtonBaseTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/SplitterTests.cs
If tooltips do not set `AutoPopDelay` or `AutomaticDelay`, windows 11 assumes that they should be accessible:
1. persistent - not dismissible by a timer but only by a user action
2. dismissible by a keyboard (Ctrl or Esc keys)
Changes:
1. do not start the dismissal timer for tooltips that had not set any dismissal delays
2. Dismiss all "accessible" tooltips when any control receives `Ctrl` or `Esc` key up message
> Support Win11 accessibility features in tooltips displayed by keyboard focus 

- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObjectTests.cs
Fixes #4150
- The issue is reproduced because we are limiting the size of the first ListViewSubItem, regardless of the `FullRowSelect` property. Added additional condition for `FullRowSelect` property.
**After fix:**
- Yes
- Minimal
- Unit tests
- CTI team
-  Inspect
- .NET Core SDK 6.0.100-rc.1.21430.12
> Fixing behavior of ListViewSubItem.Bounds when FullRowSelect = true

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.cs
- src/System.Windows.Forms.Primitives/src/System/ComponentModel/TypeDescriptorHelper.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/AttributeTypeSorter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/CategoryGridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MergePropertyDescriptor.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiPropertyDescriptorGridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiSelectRootGridEntry.PropertyMerger.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiSelectRootGridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/SingleSelectRootGridEntry.cs
- Make more methods that should have been properties, properties.
- More devirtualization, sealing, and access modifier restriction.
- Move more collections to generics for clarity
- Move outline rectangle reset into GridEntry.
- Start on helper class for TypeDescriptor.
- Remove BinaryFormatter from MergePropertyDescriptor.
- Fix issue in SingleSelectRootGridEntry where Children would potentially be created for disposal.
> More PropertyGrid related cleanup.

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CategoryGridEntryAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ChildAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridView.GridViewListBoxItemAccessibleObjectTests.cs
- `ComboBox.ChildAccessibleObject`
- `GridViewListBoxItemAccessibleObject`
Reworked `ctor` test for class `CategoryGridEntryAccessibleObject`
- No
- No
- Minimal
> Filling empty test files for missing ao (part 2)

- pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config/template.json
- pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-CSharp/.template.config/template.json
- pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/.template.config/template.json
Fixes dotnet/winforms-designer#3724
By default *.user files are excluded/removed by the template engine. Template owners need to override this with `exclude` flag and remove the *.user files form exclusion list.
Related #5547 
Related #3510
> Update template to include *.user file while creating new applications.

- src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetWindowRect.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildListUiaProvider.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxChildListUiaProviderTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListVIew.ListViewAccessibleObjectTests.cs
Fixes #4404. Currently BoundingRectangle for ComboBox and ListView doesn't take into account a vertical scrollbar if it's present. This problem is not present in .NET Framework 4.7.2 because UIA providers for these controls was added later and we need to fix this issue to keep the old behavior. When UIA provider is not present for the control UIAutomationCore uses GetWindowRect as a fallback. So, one of the possible solutions is to use GetWindowRect in the BoundingRectangle implementation. Another solution is to return an empty rectangle from the BoundingRectangle, that will trigger the fallback code in the UIAutomationCore. Using GetWindowRect directly should be the best solution since we won't rely on the internals of UIAutomationCore.
- Added `BoundingRectangle` implementation that …
> Fixing focus rectangle width for controls with vertical scrollbar

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewColumnHeaderCellAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowHeaderCellAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewSelectedCellsAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewSelectedRowCellsAccessibleObjectTests.cs
- `DataGridViewColumnHeaderCellAccessibleObject`
- `DataGridViewRowHeaderCellAccessibleObject`
- `DataGridViewSelectedCellsAccessibleObject`
- `DataGridViewSelectedRowCellsAccessibleObject`
- No
- No
- Minimal
> Filling empty test files for missing ao (part 3)

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.DataGridViewCellAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellAccessibleObjectTests.cs
Fixes #5792. To fix custom `DataGridViewCell`s we're providing default control type for the base `DataGridViewCellAccessibleObject`.
- Added `ControlTypePropertyId` with `DataItemControlTypeId` value to the `GetPropertyValue` of `DataGridViewCellAccessibleObject`.
- Control type of custom `DataGridViewCell`s is correctly recognized by accessibility tools.
- No
- Minimal
- Unit tests
- CTI (planned)
- Microsoft Windows [Version 10.0.19043.1237]
- .NET 7.0.0-beta.21474.2
> Fixing missing control type for custom `DataGridViewCell`s

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProvider.ControlItem.ControlItemAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProvider.ErrorWindow.ErrorWindowAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripControlHost.ToolStripControlHostAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripDropDownItemAccessibleObjectTests.cs
- `ToolStripControlHostAccessibleObject`
- `ToolStripDropDownItemAccessibleObject`
- `ControlItemAccessibleObject`
- `ErrorWindowAccessibleObject`
- No
- No
- Minimal
> Filling empty test files for missing ao (part 4)

- src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
Fixes #5853.
The regression came from dotnet#4317, the previous implementation didn't not take into account gray dates of a display range. So the max index was 11, but in real, 13 is the max month index (including the first and last gray months)
Related PR #5869 for 7.0.
- .NET 6.0
- Windows
> Fixed getting an month index of a bolded date of a MonthCalendar (port 6.0)

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.DataGridViewCheckBoxCellAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCheckBoxCellAccessibleObjectTests.cs
Fixes #5886 
- Reworked incorrect condition in ToggleState method
- Added unit test
- Has no incorrect behavior of properties during work with this control.
- No
- Minimal
- Manually
- Unit test
- Accessibility tests
- Inspect
- Narrator
- dotnet version: 6.0.100-rc.2.21456.2
> Fix incorrect ToggleState of DataGridViewCheckBoxCellAO class

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CategoryGridEntryAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTopLeftHeaderCellAccessibleObjectTests.cs
- `CategoryGridEntryAccessibleObject`
- `DataGridViewTopLeftHeaderCellAccessibleObject`
- No
- No
- Minimal
> Filling empty test files for missing ao (part 6)

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellCancelEventArgs.cs
- Enable nullability in DataGridViewCellCancelEventArgs
> Enable nullability in DataGridViewCellCancelEventArgs

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItemMouseHoverEventArgs.cs
- Enable nullability in ListViewItemMouseHoverEventArgs
> Enable nullability in ListViewItemMouseHoverEventArgs

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewButtonCellAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCheckBoxCellAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewImageCellAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewLinkCellAccessibleObjectTests.cs
- `DataGridViewButtonCellAccessibleObject`
- `DataGridViewCheckBoxCellAccessibleObject`
- `DataGridViewImageCellAccessibleObject`
- `DataGridViewLinkCellAccessibleObject`
- No
- No
- Minimal
> Filling empty test files for missing ao (part 5)

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewAutoSizeColumnModeEventArgs.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewAutoSizeColumnsModeEventArgs.cs
- Enable nullability in DataGridViewAutoSizeColumnModeEventArgs and DataGridViewAutoSizeColumnsModeEventArgs
> Enable nullability in DataGridViewAutoSizeColumnModeEventArgs and DataGridViewAutoSizeColumnsModeEventArgs

- src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Calendar.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
Fixes #5853
The regression came from #4317, the previous implementation didn't not take into account gray dates of a display range. So the max index was 11, but in real, 13 is the max month index (including the first and last gray months).
- Rework getting current month index when setting a new bolded date
- A user can bold a MonthCalendar date correctly
- Yes (from #4317)
- Minimal
MonthCalendar doesn't show bolded dates:
MonthCalendar shows bolded dates:
- CTI
- Unit tests
- .NET 7.0-alpha
- Windows 10
> Fixed getting an month index of a bolded date of a MonthCalendar

- src/System.Windows.Forms/src/Resources/SR.resx
- src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
Fixes #5795
- Extracted moving focus backward to separate method with special treatment for ToolStrip, because it's not a simple control, but control with children controls and they should be parsed in a `while` cycle
- Changed `forward` condition at the `GetNextItem` method at the `ToolStrip` class because it is called after moving focus to the ToolStrip, but when `TabStop` is true the first item should be always focused
- Added unit test for checking focus cycling
- Before the fix (focus was trapped at the last ToolStrip item while pressing `Shift`+`Tab`):
- After the fix (focus isn't trapped at the last ToolStrip item while pressing `Shift`+`Tab`):
- No
- Minimal
- Unit test
- CTI team
Microsoft Windows [Version 10.0.19043.1237]
.NET SDK 7.0.0-alpha.1.21471.1
> Fixing switching focus between ToolStrips where TabStop=true with Shift-Tab

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ColumnReorderedEventArgs.cs
- Enable nullability in ColumnReorderedEventArgs
> Enable nullability in ColumnReorderedEventArgs

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs
- Remove 'using' from DrawItemEventArgs_TestData
Based on the comments from https://github.com/dotnet/winforms/pull/5899#discussion_r721783556
> Remove 'using' from DrawItemEventArgs_TestData

- src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiMonthCalendarTests/MauiMonthCalendarTests.cs
- Ignored `MauiMonthCalendarTests` for `SelectedDate` event
- Yes
- Minimal
- Unit tests
- Microsoft Windows [Version 10.0.19041.804]
- .NET Core SDK: 7.0.0-alpha.1.21528.1
> Ignoring MauiMonthCalendarTests for "SelectedDate" event

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
Fixes #5493 
- Remove the disabled `ToolStripItem` selected bits when the `ToolStrip` fires `MouseLeave`.
- A consistent ToolStripItem selected behavior experience after the mouse leaves, whether the item is enabled or not.
- No.
- Possible risk if customers depend on and/or have implemented workarounds, those could break.
https://user-images.githubusercontent.com/5017479/138641139-8f4c037b-6604-4c2e-ba00-146caf813ce3.mp4
https://user-images.githubusercontent.com/5017479/138641152-2344e92f-6f11-4300-a367-2ec1dace7f71.mp4
- Wrote a unit test to demonstrate the bug. The proposed fix causes the test to pass.
- Manually tested the changes and have provided videos to demonstrate the before and after.
- Ran unit and integration tests.
Accessbility Insights for Windows
Windows 10.0.19043
.NET …
> Fix disabled ToolStripItem selected bits when ToolStrip fires MouseLeave

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItemClickedEventArgs.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItemEventArgs.cs
- Enable nullability in ToolStripItemClickedEventArgs and ToolStripItemEventArgs
> Enable nullability in ToolStripItemClickedEventArgs and ToolStripItemEventArgs

- azure-pipelines.yml
Disable Loc - We need disable loc here to enable it on servicing. This is still manual process.
Must be reenabled once servicing branch is up to date with loc and disable for loc there.
> Disable Loc on main until servicing branch is updated.

- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.PropertyTabCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.TabInfo.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
Combine tab related data into a record for clarity and safety. Use a List<> instead of an array to avoid complicated insert logic.
Maintain tab selection as an instance instead of an index.
Move error handling to CreateTab so thrown exceptions with messages (missing a bitmap / name for the tab) are actually thrown instead of a silent failure.
> Combine PropertyGrid tab information.

- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
Fixes #6093, the regression introduced in #2262.
Restore the required state after the handle was re-created.
#2262 has added a check to the method handling recreation of a control handle to verify that the control is created before any child controls can be re-parented on to it.
However it was missed that `DestroyHandle()` method resets the state (i.e. removes `Created` state), but `CreateHandle()` method doesn't set the state back. 
- Child controls sited on a form that recreates its handle while shown (e.g. while changing the value of `ShowInTaskbar` property) will be correctly rendered.
- Yes, introduced in https://github.com/dotnet/winforms/pull/2262 in .NET 5.0 Preview1.
- Small
On the left `ListBox` and `CheckedListBox` controls, on the right `ListView` controls.
- git bisect to …
> (Servicing) Resume invocation of OnParentHandleRecreated for child control when form recreates handle

- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
Fixes #6093, the regression introduced in #2262.
Restore the required state after the handle was re-created.
#2262 has added a check to the method handling recreation of a control handle to verify that the control is created before any child controls can be re-parented on to it.
However it was missed that `DestroyHandle()` method resets the state (i.e. removes `Created` state), but `CreateHandle()` method doesn't set the state back. 
- Child controls sited on a form that recreates its handle while shown (e.g. while changing the value of `ShowInTaskbar` property) will be correctly rendered.
- Yes, introduced in https://github.com/dotnet/winforms/pull/2262 in .NET 5.0 Preview1.
- Small
On the left `ListBox` and `CheckedListBox` controls, on the right `ListView` controls.
- git bisect to …
> Resume invocation of OnParentHandleRecreated for child control when form recreates handle

- src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Layout/DockAndAnchorLayout.cs
This issue was introduced in .NET Framework 4.8.  Control `AnchorInfo `is used in the determination of `Location `of the `Control`.  AnchorInfo was miscalculated (ignored `AnchorStyle `property) when controls scaled on higher DPI settings and thus location OFF as demonstrated in the linked issue.  In this change, we will be checking the `AnchorStyles `before overriding the `AnchorInfo`.
Fixes #5774
Fixes #4838
> Fix anchored controls mis-alignment when DPI of the display is higher than 100%

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItemTextRenderEventArgs.cs
- Enable nullability in ToolStripItemTextRenderEventArgs.
> Enable nullability in ToolStripItemTextRenderEventArgs

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewLinkCell.cs
Fixes #3883 
- Color of the link in the selected cell changed to white
- No
- Minimal
The link is scarcely visible
The link is clearly visible
- CTI
- Microsoft Windows [Version 10.0.19042.1237]
- .NET 6.0.100-rc.2.21505.57
> Fixing Color contrast for DataGridViewLinkCell when it is selected

- src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Layout/DockAndAnchorLayout.cs
* Fixes anchored controls mis-alignment when DPI of the display is higher than 100%. In .NET framework 4.7 timeframe, we made a change to improve the anchoring on higher DPI settings that introduced this bug. As explained in the linked bug below, Applications that anchor controls are currently broken in default SystemAware mode with >100% DPI settings ( which is also a default for most)
Fixes #5774 
- Yes, from .NET framework 4.6
- I would say minimum and associated with only controls that are anchored.  Currently they are broken even in `SystemAware `mode.
- Manual  CTI validation.
- Running customer provided applications and making sure change fixing them.
> [6.0][Servicing]Fix anchored controls mis-alignment when DPI of the display is higher than 100%

- src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
Fix nested `Container Controls` scaling that have `AutoscaleMode` as `Inherit`.  In this change we are making sure to traverse hierarchy all the way up until we get a container parent whose `AutoScaleMode `is not Inherit and use it s `AutoScaleFactor `to scale children.
Fixes #5957.
fixes #6152
> Fix nested container controls scaling that have AutoscaleMode as Inherit

- src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
* Fix nested ContainerControls that have `AutoscaleMode `as `Inherit`.
A change in supporting scaling for `MDI `child windows in PermonV2 mode applications regressed this. Issue impact Winforms applications that are running in `PerMonV2 `mode. While winforms not yet fully support  PerMonV2 mode, customers are creating and using this mode for their applications, since .NET Framework 4.7.3, and get it working for less complex winforms applications with some work arounds. 
Fixes #6152.
- Yes, from .NET 5.0. 
- Low. Fix is already in 7.0 and tested for `PermonV2 `mode.
- 
- Manual  CTI validation.
- Running customer provided applications and making sure change fixing them.
> [6.0][Servicing] Fix nested container controls scaling that have AutoscaleMode as Inherit

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.AccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewAccessibleObjectTests.cs
Fixes #2178  
- Reworked the property `HasKeyboardFocusPropertyId` of DGV AO. If no inner item then focus on the entire DGV else focus on the inner cell instead of entire DGV. This works also for DGV in Virtual mode. This doesn't break focusing border on the cell if DGV is not empty. It works also when form doesn't have any row (e.g. row for edit) see this case in after screens below.
- Turned off `TablePattern` support for DGV without rows. It needs to avoid incorrect announcement of the control:
if focus on empty DGV then it has no message "enter table", although if leave then it has message "exit table". So we turn off "enter table" and "exit table" messages for the empty DGV. This approach doesn't make a new accessibility problems in Accessibility Insights.
- Added unit tests for it. …
> Fixing no focus border on the empty DGV in the Narrator

- src/System.Windows.Forms/src/Resources/SR.resx
- src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/CategoryGridEntry.CategoryGridEntryAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CategoryGridEntryAccessibleObjectTests.cs
Fixes #6037
- A new localized control type for category of property grid was introduced. Set it for CategoryGridEntryAccessibleObject.
- Added a unit test.
- Resolved an accessibility error of the control.
- No
- Minimal
An error was detected by Accessibility Insights.
A category of property grid has a `tree view` value of `LocalizedControlType` property.
In Narrator Buddy
No errors were detected by Accessibility Insights.
A category of property grid has a `PropertyGrid category` custom value of `LocalizedControlType` property.
No changes in the Narrator Buddy.
- Manual
- Unit
- CTI
- Inspect
- Narrator
- dotnet version: 6.0.100
- OS version: 10.0.19043
> Adding a new localized control type for category of property grid

- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
Fixes #3796 
- Refactored `DropDownControl` method: set sending a focus and change expand-collapse state events before focusing on dropdown control.  
- Has a correct highlighting of opened and focused dropdown in the Inspect.
- No
- No
No highlighting on the focused dropdown of property grid item in the Inspect.
Has highlighting on the focused dropdown of property grid item in the Inspect.
- Manual
- Unit
- CTI
- Inspect
- Narrator
- dotnet version: 6.0.100
- OS version: 10.0.19043
> Fixing highlighting of property grid item dropdown in the Inspect

- src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Fixes #6173
Container controls whose Font is explicitly set are not scaled well if they inherit `AutoScaleMode `from parent. Inherited `AutoScaleMode `containers use `AutoScaleFactor `from parents to scale themselves. However, in a `PerMonitorV2 `mode applications, parent receive the `DpiChangedEvent `after all their children receive it and scale themselves. `ContainerControls `that inherit scaling, will end up using `AutoScaleFactor `from parent that was not yet updated to the new Dpi as Parent yet to receive the DPI event. To fix this, we are tracking such containers with `IsDpiChangeScalingRequired `flag and scale them once the Parent `AutoScaleFactor ` is updated.
> Fixing scaling issue on explicitly set Font containers but Inherit AutoScaleMode

- src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Fixes #4816. ListView allows editing the label by clicking on any subitem of a row. On the other hand, Windows Explorer allows label editing only by clicking on the first subitem (which is actually a label) of a row. Windows Explorer behavior should be more appropriate for a common user. The logic of the label editing is located in ComCtl32.dll which is provided by Windows and therefore can't be changed on our side. In order to change the behavior we can rely on the fact that this internal logic sets a timer before an actual editing begins.
ListView provides a standard way to cancel a pending label edit - `LVM_CANCELEDITLABEL` message. The problem is that this message is only implemented in 6.0 version of ComCtl32.dll. It also doesn't work as expected under 6.0, so it can't be actually …
> Adding prevention of label editing when clicking on subitems of ListView

- src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObjectTests.cs
Fixes #5960
- Collapsing/expanding `ListView` groups from a keyboard is handled automatically inside the native control, there's no special code at `.Net Core`. We need only to raise the `GroupCollapsedStateChanged` event and set `CollapsedState` of the `ListViewGroup`
- We need to set `CollapsedState` without sending a Windows message `LVM.SETGROUPINFO` because all collapse/expand handling is already happening automatically, that's why we're adding an internal method `SetCollapsedStateInternal`
- No
- No
- Minimal
- Unit tests
- CTI team
- Manual testing scenarios:
1. Collapsed and expanded `ListViewGroup` from the keyboard with writing to log at the event handler:
2. Examined Narrator's text while collapsing and expanding `ListViewGroup` from the keyboard:
3. Watched the …
> Fixing ListView not firing GroupCollapsedStateChanged event from keyboard

- src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
- src/System.Windows.Forms/tests/InteropTests/NativeTests/AccessibleObjectTests.cpp
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjectTests.cs
Fixes #6020. This regression was introduced by #5404 that removed `InternalAccessibleObject` wrappers around regular accessible objects. The issue appeared because `GetIAccessiblePair` was implemented differently by `InternalAccessibleObject` and `AccessibleObject` classes. `InternalAccessibleObject` had a working implementation whereas `AccessibleObject` basically had a stub which was never called before `InternalAccessibleObject` was removed. The fix is to copy the implementation of `GetIAccessiblePair` from removed `InternalAccessibleObject` to `AccessibleObject` class.
- Implemented `AccessibleObject.GetIAccesiblePair` the same as `InternalAccesibleObject.GetIAccessiblePair` was implemented.
- Narrator doesn't announce TextPattern stuff like the displayed text, the selected text, …
> Fixing announcing TextPattern elements by Narrator

- src/System.Windows.Forms.Analyzers.CSharp/src/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilder.cs
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.GenerateInitialize_DefaultFont=SansSerif.verified.txt
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.GenerateInitialize_DefaultFont=Tahoma.verified.txt
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.GenerateInitialize_DefaultFont=default.verified.txt
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/MockData/ApplicationConfigurationGeneratorTests.GenerateInitialize_user_settings_boilerplate.cs
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/MockData/ApplicationConfigurationGeneratorTests.GenerateInitialize_user_top_level.cs
Resolves #6191
-  Set the font after we set the DPI scaling, as it affects how we scale the font.
- Customer using DPI scaling can use the new [application bootstrap functionality](https://aka.ms/applicationconfiguration) introduced in .NET 6.0.
- No
- Minimal
> Set the font after we set the DPI scaling, as it affects how we scale the font

- src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjectTests.cs
Fixes #6165.
- Added a branch for `systemWrapper` in `AccessibleObject.RuntimeId` with an empty array return value
- There is no impact as release builds don't have assertions compiled
- Yes (from .NET 6)
- Minimal
- Unit-tests
- CTI
-  Microsoft Windows [Version 10.0.19043.1288]
- .NET 7.0.0-alpha.1.21551.1
> Fixing `RuntimeId` for system accessible wrapper in AccessibleObject

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItemImageRenderEventArgs.cs
- Enable nullability in ToolStripItemImageRenderEventArgs
> Enable nullability in ToolStripItemImageRenderEventArgs

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.ToolStripAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MdiControlStripTests.cs
Fixes #6231
- `MdiControlStrip` is the class that implements merged `MenuStrip` when an MDI child is maximized and the `MainMenuStrip` property of the `Form` is set. 
- `MdiControlStrip` has three `ControlBoxMenuItems` with `Alignment` property set to `Right`: `_minimize`, `_restore` and `_close`.
- The item collection of `MdiControlStrip` after merging will look like this:
for this menu bar:
- That's okay for the `MenuStrip` rendering because the right-aligned items will be placed on the right side correctly, but not okay for the `ToolStripAccessibleObject`, which picks the item by its sequential `fragmentIndex` at the `GetChildFragment` method. 
- To fix this issue we need to re-order the local item collection at `GetChildFragment` to make it consistent with the visual layout.
**Before …
> Fixing missing ControlBox buttons at maximized MDI child window for UIA

- src/System.Windows.Forms.Analyzers.CSharp/src/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilder.cs
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.GenerateInitialize_DefaultFont=SansSerif.verified.txt
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.GenerateInitialize_DefaultFont=Tahoma.verified.txt
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.GenerateInitialize_DefaultFont=default.verified.txt
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/MockData/ApplicationConfigurationGeneratorTests.GenerateInitialize_user_settings_boilerplate.cs
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/MockData/ApplicationConfigurationGeneratorTests.GenerateInitialize_user_top_level.cs
Resolves #6191
-  Set the font after we set the DPI scaling, as it affects how we scale the font.
- Customer using DPI scaling can use the new [application bootstrap functionality](https://aka.ms/applicationconfiguration) introduced in .NET 6.0.
- No
- Minimal
> [6.0.2](Servicing) Set the font after we set the DPI scaling, as it affects how we scale the font

- src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Fixes #6173
Container controls whose Font is explicitly set are not scaled well if they inherit `AutoScaleMode `from parent. Inherited `AutoScaleMode `containers use `AutoScaleFactor `from parents to scale themselves. However, in a `PerMonitorV2 `mode applications, parent receive the `DpiChangedEvent `after all their children receive it and scale themselves. `ContainerControls `that inherit scaling, will end up using `AutoScaleFactor `from parent that was not yet updated to the new Dpi as Parent yet to receive the DPI event. To fix this, we are tracking such containers with `IsDpiChangeScalingRequired `flag and scale them once the Parent `AutoScaleFactor ` is updated.
Customers with PerMonitorV2 mode applications migrating from .NET 5.0 to .NET 60 would experience regression in scaling …
> [6.0.2] [Servicing]Fixing scaling issue on explicitly set Font containers but still Inherit AustoScaleMode.

- src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/ButtonStandardAdapter.cs
Fixes #4538
- After zooming in it's visible that dotline rectangle for the focused `Button` with FlatStyle set to `Standard` is still there, but it intersects with the blue border:
- At .Net 5.0 there's no such intersection:
- This intersection happens because the focus rectangle is inflated for one pixel, and to fix this issue we should add a condition on this inflating to exclude the `Standard` FlatStyle case
- ![image](https://user-images.githubusercontent.com/87859299/145019797-713ff86e-9bf3-46de-bf17-01c5e5658ef6.png)
- ![buttonsBeforeFix](https://user-images.githubusercontent.com/87859299/145020580-a20358f8-562b-4991-9387-7ed5dddb1e1c.gif)
- ![image](https://user-images.githubusercontent.com/87859299/145019827-55050b73-15c6-4b02-9b88-36b8bcf0a4ea.png)
- …
> Fixing dotline rectangle for focused `Button` with `Standard` FlatStyle

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewLinkCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/LinkUtilities.cs
Fixes #6116
- Color for link in the selected cell switched to `SystemColors.HighLightText`
- Font for the active link inside selected cell switched to bold
- Before fix:
- After fix:
- No
- Minimal
- CTI team
- Accesssibility Insights
- Microsoft Windows [Version 10.0.19042.1237]
- .NET 6.0.100-rc.2.21505.57
> Fixing color contrast for DataGridViewLinkCell active link when cell is selected

- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms/src/Resources/SR.resx
- src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
- src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.Vista.cs
- src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
- src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.cs
- src/System.Windows.Forms/src/System/Windows/Forms/SaveFileDialog.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FileDialogTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FolderBrowserDialogTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/OpenFileDialogTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/SaveFileDialogTests.cs
Fixes #5405 
Add missing feasible file and folder dialog options and expose them via public properties.
- AddToRecent
- CheckWriteAccess
- ExpandedMode
- OkRequiresInteraction
- SelectReadOnly
- ShowHiddenFiles
- ShowPinnedPlaces
- ShowPreview
```csharp
namespace System.Windows.Forms
{
public partial class FileDialog
{
[DefaultValue(true)]
public bool AddToRecent { get; set; } = true;
[DefaultValue(false)]
public bool ShowHiddenFiles { get; set; }
[DefaultValue(true)]
public bool ShowPinnedPlaces { get; set; } = true;
[DefaultValue(false)]
public bool OkRequiresInteraction { get; set; }
}
public partial class OpenFileDialog
{
[DefaultValue(false)]
public bool ShowPreview { get; set; }
[DefaultValue(true)]
public bool SelectReadOnly { get; set; } = true;
}
public partial class …
```
> Add missing feasible file and folder dialog options

- src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2ExtendedTypeConverter.cs
- Enable nullability in Com2ExtendedTypeConverter.
> Enable nullability in Com2ExtendedTypeConverter

- src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Fixes #6353
- The issue is reproduced because we are trying to access a `ListViewGroup` that the `ListViewItem` may not contain it.
- Added a condition so that the code for working with `ListViewGroups` is called only when the `ListViewGroups` are enabled (`GroupsEnabled` property).
- Fixed condition for cases when the `Group` property has `null` value. 
**After fix:**
- Yes (from #5960)
- Minimal
- Unit tests
- CTI team
- Microsoft Windows [Version 10.0.19041.1348]
- .NET Core SDK: 7.0.0-alpha.1.21576.4
> Fixing NRE when the user press the left / right arrow in ListView

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemAccessibleObject.cs
- Enable nullability in ToolStripItemAccessibleObject.
> Enable nullability in ToolStripItemAccessibleObject

- src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MdiControlStripTests.cs
Fixes #6339
- The fix is based on PR #4465. Looks like something was changed in WinAPI: now not the latest build of 5.0 nor this specifically checked out commit doesn't fix the issue.
- Now we need to recreate the dummy menu every time we're setting the `MainMenuStrip` property of the `Form`.
**Before the fix** 
**After the fix** 
- Yes
- Minimal
- Manual testing (see the screenshots above)
- Unit tests
- CTI team
Windows 10 10.0.19043.1415
.NET SDK 7.0.0-alpha.1.21606.7
> Fixing multiple adding of `ControlBox` buttons to MDI child form

- src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripCustomIComparer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs
- Use generic list in FindMergeableToolStrips.
> Use generic list in FindMergeableToolStrips

- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ObjectCollection.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
Fixes #6304.
Fixes `ArgumentOutOfRangeException` when `SelectedItem` removed from `ComboBox.Items` and then `SelectedItem` property is subsequently accessed.
No more `ArgumentOutOfRangeException`
- Fixes bug in .NET Core 7 alpha
Unit test added. Fails on unpatched code. Passes on patched.
> ComboBox: fix SelectedItem/SelectedIndex when SelectedItem removed from Items

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainItemAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainItemListAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainUpDownAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DomainUpDown.DomainItemAccessibleObjectTests.cs
- Enable nullability in DomainUpDown accessible objects.
> Enable nullability in DomainUpDown accessible objects

- src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
- Use generic list in GetMnemonicList.
> Use generic list in GetMnemonicList

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.RestoreFocusMessageFilter.cs
- Enable nullability in RestoreFocusMessageFilter.
> Enable nullability in RestoreFocusMessageFilter

- src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2ShouldRefreshTypes.cs
- Enable nullability in Com2ShouldRefreshTypes.
> Enable nullability in Com2ShouldRefreshTypes

- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs
Stems from #6334
Replaced direct point coordinates assessment to the small range of pixels
- Let occur small inaccuracies in the coordinates in the MoveMouseToControlAsync
> ControlTestBase: less sensitive point coordinates assessment

- src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Fixes #4042 
`ListView` attempts to cache `CheckedItems` when setting `CheckBoxes` to `false`. This results in an `InvalidOperationException` in `CheckedItems.Count` when the `ListView` is in virtual mode. Since `CheckedItems` cannot be used in virtual mode anyway, the fix is to skip this caching logic when `VirtualMode == true`.
Note: there was a unit test that ensured this behavior. It's not clear why since it seems undesirable. The error is trivial to repro. All you have to do is drop a new `ListView` into the forms designer, set `VirtualMode` to `true`,  and then try toggling `CheckBoxes` to `true` and then back to `false`, all within the properties tool window. The existing unit test was modified to ensure the error does not happen.
Customer should be able to toggle `CheckBoxes` from …
> Do not attempt to cache CheckedItems if in virtual mode

- src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
- Use generic list in Lines property of TextBoxBase.
> Use generic list in Lines property of TextBoxBase

- src/System.Windows.Forms/src/System/Windows/Forms/ProgressBar.ProgressBarAccessibleObject.cs
- Enable nullability in ProgressBarAccessibleObject.
> Enable nullability in ProgressBarAccessibleObject

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ImageIndexConverter.cs
- Enable nullability in ImageIndexConverter.
> Enable nullability in ImageIndexConverter

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/SelectionRange.cs
- src/System.Windows.Forms/src/System/Windows/Forms/SelectionRangeConverter.cs
- Enable nullability in SelectionRange and SelectionRangeConverter.
> Enable nullability in SelectionRange and SelectionRangeConverter

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItemStateImageIndexConverter.cs
- Enable nullability in ListViewItemStateImageIndexConverter.
> Enable nullability in ListViewItemStateImageIndexConverter

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripButton.ToolStripButtonAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripControlHost.ToolStripControlHostAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripLabel.ToolStripLabelAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSeparator.ToolStripSeparatorAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitButton.ToolStripSplitButtonAccessibleObject.cs
- Enable nullability in classes that inherit from ToolStripItemAccessibleObject.
> Enable nullability in classes that inherit from ToolStripItemAccessibleObject

- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.MouseHook.MouseHookObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.MouseHook.cs
- Enable nullability in MouseHook and MouseHookObject.
> Enable nullability in MouseHook and MouseHookObject

- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
This PR is the result of regressions caused by #6114 and #2262.
`State.Created` must be set only when `Handle` and the `Control `associated with it is created. Otherwise, recreating `Control `scenarios would be out of sync.  Changes in this PR is basically bringing the source code back to 6.0 GA state with respect to setting flag on `State.Created`.
Setting `State.Created` when the `Handle `is created but the associated `Control `is not, have repercussions mentioned in #6464. We cache this state and check before creating the control. Incorrect state would skip this. ex: https://github.com/dotnet/winforms/blob/0d4484331f57113d3303275c6aa5717fcd4b6c25/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs#L5044
fixes #6464
> Fixing incorrect state set for State.Created flag on the Control

- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
this fix is already in main here: https://github.com/dotnet/winforms/pull/6477
This PR is the result of regressions caused by #6114 and #2262.
`State.Created` must be set only when `Handle` and the `Control `associated with it is created. Otherwise, recreating `Control `scenarios would be out of sync.  Changes in this PR is basically bringing the source code back to 6.0 GA state with respect to setting flag on `State.Created`.
Setting `State.Created` when the `Handle `is created but the associated `Control `is not, have repercussions mentioned in #6464. We cache this state and check before creating the control. Incorrect state would skip this. ex: https://github.com/dotnet/winforms/blob/0d4484331f57113d3303275c6aa5717fcd4b6c25/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs#L5 …
> [servicing6.0*] Fixing incorrect state set for State.Created flag on the Control 

- src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolTipTests.cs
Fixes #5835. There are some controls that are adding their own tools (e.g. TabControls adds a tool for each TabPage) and for these tools we don't have an associated caption. Moreover these tools are typically retrieving the caption using TTN_NEEDTEXT notification.
The simplest way to fix this issue is to retrieve the caption using the `GetWindowText` function. At `WmShow` we know that the caption was already retrieved and set by the tooltip, so it can be retrieved using this API function. This way works for both static and dynamic captions.
The more complex way is to change the logic of the current tool retrieval and also the most important to change the logic of the caption retrieval, to support the dynamic ones.
The first approach was chosen as it is very simple and works without any …
> Fixing announcing the tooltip for the TabPage

- src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolTipTests.cs
Fixes #4750. The DELTOOL message of tooltip causes moving of the last tool to the slot of the deleted tool in the tool array (e.g. deleting `Button` from the `[Button, TabControl, TabPage1, TabPage2]` results in `[TabPage1, TabControl, TabPage2]`). This breaks the hit-test logic of the tooltip that checks the tools in the reverse order. Thus the TabControl may be checked earlier than any of TabPages and tooltip will be shown for the TabControl and not for the TabPage.
A possible fix is to reorder the tools in the tools array, but there is no way to access it directly. It is possible to change the array through GETTOOLINFO and SETTOOLINFO messages but this may have undesirable side-effects of breaking caches and other things.
The other way is to remove deletion from the keyboard tooltips …
> Fixing incorrect mouse tooltip for TabPage of TabControl

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripGripRenderEventArgs.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripRenderEventArgs.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripGripRenderEventArgsTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripRenderEventArgsTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripRendererTests.cs
- Make toolStrip non-nullable in ToolStripGripRenderEventArgs and ToolStripRenderEventArgs.
- Addresses feedback in https://github.com/dotnet/winforms/pull/6391.
> Make toolStrip non-nullable in ToolStripGripRenderEventArgs and ToolStripRenderEventArgs

- src/System.Windows.Forms/src/System/Windows/Forms/SendKeys.SendKeysHookProc.cs
- src/System.Windows.Forms/src/System/Windows/Forms/SendKeys.cs
- Addresses post-merge feedback in https://github.com/dotnet/winforms/pull/6428.
> Make s_events non-nullable in SendKeys

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItemImageRenderEventArgs.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItemRenderEventArgs.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSeparatorRenderEventArgs.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripGripRenderEventArgsTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemImageRenderEventArgsTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemRenderEventArgsTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripRenderEventArgsTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripRendererTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripSeparatorRenderEventArgsTests.cs
- Make ToolStripItem non-nullable in ToolStripItemRenderEventArgs.
- Addresses feedback in https://github.com/dotnet/winforms/pull/6391.
> Make ToolStripItem non-nullable in ToolStripItemRenderEventArgs

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewEditingControlShowingEventArgs.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewEditingControlShowingEventArgsTests.cs
- Enable nullability in DataGridViewEditingControlShowingEventArgs.
> Enable nullability in DataGridViewEditingControlShowingEventArgs

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripContentPanelRenderEventArgs.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripContentPanelRenderEventArgsTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripRendererTests.cs
- Make contentPanel non-nullable in ToolStripContentPanelRenderEventArgs.
> Make contentPanel non-nullable in ToolStripContentPanelRenderEventArgs

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRenderEventArgs.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripContentPanelRenderEventArgsTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripPanelRenderEventArgsTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripRendererTests.cs
- Enable nullability in ToolStripPanelRenderEventArgs.
> Enable nullability in ToolStripPanelRenderEventArgs

- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.FlatComboAdapter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
Fixes #6494
`ComboBox.FlatComboAdapter.ValidateOwnerDrawRegions` contained a bug in its initial null check that prevented the method from executing. This bug existed under Framework 4.8 (and possibly quite earlier):
https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/ComboBox.cs,6102
The bug was fixed in #6300, which resulted in a regression when drawing a `ComboBox` with `FlatStyle.Flat` or `FlatStyle.Popup`. 
While the stated purpose of `ValidateOwnerDrawRegions` was to reduce screen flicker, the fact remains that the method never actually executed and allowing it to execute now is causing problems. This PR fixes the issue by just removing the method altogether.
`ComboBox` will draw itself correctly again.
- Yes
- Should be minimal. This simply …
> Fix FlatStyle drawing of ComboBox

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownButton.ToolStripDropDownButtonAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.ToolStripMenuItemAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripOverflowButton.ToolStripOverflowButtonAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitButton .ToolStripSplitButtonUiaProvider.cs
- Enable nullability in classes that inherit from ToolStripDropDownItemAccessibleObject.
> Enable nullability in classes that inherit from ToolStripDropDownItemAccessibleObject

- src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/ButtonBaseAdapter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/ButtonStandardAdapter.cs
- Reverting fix with drawing a border for a standard button
- No
- Minimal
-  Manual testing
- Microsoft Windows [Version 10.0.19044.1469]
- .NET Core SDK: 7.0.0-alpha.1.22067.10
> Reverting fix with drawing a border for a standard button

- .github/fabricbot.json
- docs/infra/automation.md
Migrates FabricBot automation for the dotnet-api-docs to [Config-as-Code](https://microsoft.sharepoint.com/teams/FabricBot/SitePages/Config-as-code.aspx). The file is a dump of the automation rules that are currently active and doesn't contain any additional changes.
Similar to https://github.com/dotnet/runtime/pull/62297 and https://github.com/dotnet/dotnet-api-docs/pull/7442.
> Move FabricBot rules to Configuration-As-Code

- .github/fabricbot.json
1. Respond to comments on closed issues.
2. Respond to comments on closed PRs.
3. Lock closed issues and PRs after 30 days of inactivity.
These rules are already applied in dotnet/runtime and dotnet/aspnetcore repos, e.g., https://github.com/dotnet/aspnetcore/pull/39568#issuecomment-1016822325.
> Add new msftbot rules

- src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.CoGetClassObject.cs
- src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.OleCreatePictureIndirect.cs
- src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.OleCreateFontIndirect.cs
- src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/Mocks/MockAxHost.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxComponentEditor.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxContainer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxPerPropertyBrowsingEnum.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxPropertyDescriptor.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxPropertyTypeEditor.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.ClsidAttribute.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.ConnectionPointCookie.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.EnumUnknown.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.InvalidActiveXStateException.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.OleInterfaces.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.PropertyBagStream.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.State.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.VBFormat.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PictureConverter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXFontMarshaler.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataObject.OleConverter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
Specifically targeting a few things:
- Use interpolated strings
- Clean up field naming style
- General reduction of blue info messages
I tweaked some interop definitions to allow using readonly Guids when requesting interfaces.
Note that AxHost.State custom serializes- I went through it carefully to make sure updating the fields wouldn't impact serialization.
Most of the strings are in Debug tracing. Moving to interpolated strings will avoid a lot of needless string formatting when debugging. I'm skeptical of the value of maintaining these at all actually, but for now I'm not going to push leaving them in. (They make reading the code significantly more difficult.)
> Clean up code in AxHost/DataObject/ContainerControl

- src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.EnumVariantObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjectTests.cs
- Use standard field naming
- Use interpolated strings
> Clean up AccessibleObject

- src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.DirectionButtonAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.cs
- Enable nullability in UpDownButtonsAccessibleObject.
> Enable nullability in UpDownButtonsAccessibleObject

- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
While watching how `BeginInvoke` is implemented, I noticed that `MarshaledInvoke` in the case of an asynchronous call (`BeginInvoke`) always makes two extra Win32 calls. Why call extra code if it's not needed?
Sorry if this doesn't meet your [contribution bar](https://github.com/dotnet/winforms/blob/main/CONTRIBUTING.md#contribution-bar) :blush:
`BeginInvoke` will be _slightly_ faster.
- No
- Minimal, if any.
Existing tests.
> Speedup BeginInvoke a little.

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
- src/System.Windows.Forms.Primitives/src/Interop/Oleacc/Interop.LresultFromObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildNativeWindow.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
I cannot make `IID.IAccessible` as auto-property, since I have to pass that value by reference. I prefer to mark function as `in` instead of `ref`
> Prevent accidental changing of IID.IAccessible

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.TopRowAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainItemAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainItemListAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.Link.LinkAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.GridEntryAccessibleObject.cs
Resolve comment from pr #6432 
- Remove call empty ctor of Accessible Object class in inherited classes.
- No
- No
- No
> Remove using empty base AO ctor

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MdiControlStripTests.cs
Fixes #6535
PR #4650 introduced a refresh of the `MdiControlStrip` icon when a maximized MDI child form's icon changes. That surfaced a bug ultimately resulting in a `NullReferenceException`. The fix is trivial, with most work spent understanding the root cause and proving the fix to be correct.
The NRE was triggered when a maximized MDI child form's icon changed if the new icon's size caused the `MdiControlStip`'s size to change. The Rube Goldberg-like chain of events went like this:
- The `ToolStripItem` containing the icon would invalidate its layout
- This would trigger a call to `LayoutTransaction.DoLayout` on the item's owner (the `MdiControlStrip`)
- The `MdiControlStrip` would resize
- The area available to the maximized MDI child form would change due to `MdiControlStrip` taking …
> Fix NRE in ToolStripItem.InvalidateItemLayout

- src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewNativeItemCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItemTests.cs
Fixes #6230 
- The issue is reproduced because we have cached the `ListViewItem.AccessibilityObject`. After the changes in #4910, we added logic that, with each call to the `AccessibilityObject` property, checked that the `ListView` exists and, if absent, threw an exception. Now we return null as a `ListViewItem.AccessibilityObject` instead of returning an exception.
- Also, after the focused `ListViewItem` is removed, it remains cached in the `FocusedItem` property. It also forces the Accessibility tool to try to retrieve the data of the `ListViewItem` that is not displayed. As a fix, a logic was added to reset the Focused flag from the `ListViewItem`.
**After fix:**
- Yes (from #4910)
- Minimal
- CTI team
- Unit tests
- Inspect 
- Narrator
- …
> Fixing issue with getting ListViewItem.AccessibilityObject when ListView does not exist

- eng/Version.Details.xml
- eng/Versions.props
- eng/common/templates/job/job.yml
- eng/common/templates/steps/source-build.yml
- global.json
- pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/Microsoft.Dotnet.Winforms.ProjectTemplates.csproj
PR reenables template localization disabled in https://github.com/dotnet/winforms/pull/6441
Issue was fixed in https://github.com/dotnet/templating/pull/4267 and available in latest version of arcade https://github.com/dotnet/arcade/pull/8395.
> update arcade version and re-enable template localization

- src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewNativeItemCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItemTests.cs
Fixes #6230 
- The issue is reproduced because we have cached the `ListViewItem.AccessibilityObject`. After the changes in #4910, we added logic that, with each call to the `AccessibilityObject` property, checked that the `ListView` exists and, if absent, threw an exception. Now we return null as a `ListViewItem.AccessibilityObject` instead of returning an exception.
- Also, after the focused `ListViewItem` is removed, it remains cached in the `FocusedItem` property. It also forces the Accessibility tool to try to retrieve the data of the `ListViewItem` that is not displayed. As a fix, a logic was added to reset the Focused flag from the `ListViewItem`.
**After fix:**
- Yes (from #4910)
- Minimal
- CTI team
- Unit tests
- Inspect 
- Narrator
- …
> Fixing issue with getting ListViewItem.AccessibilityObject when ListView does not exist (port to 6.0)

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.AccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.TopRowAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.DataGridViewCellAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnHeaderCell.DataGridViewColumnHeaderCellAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.DataGridViewRowAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowCollection.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewColumnHeaderCellAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTopRowAccessibleObjectTests.cs
Fixes #6471
- The issue is reproduced because when getting information about a `DataGridViewCell`/`DataGridViewRow`, we do not take into account that `DataGridViewColumn` and `DataGridViewRow` may be hidden.
- Added refactoring for some methods. Added additional checks to avoid exceptions.
- Fixed the logic for getting the following properties:
- `DataGridViewRowAccessibleObject`
* `ColumnCount`
* `GetColumnHeaders`
* `GetItem`
* `GetRowHeaders`
* `RowCount`
- `DataGridViewCellAccessibleObject`
* `Column`
* `Name`
* `Row`
- `DataGridViewRowAccessibleObject.Name`
**After fix:** 
- No
- Minimal
- CTI team
- Unit tests
- Inspect
- Narrator
- Microsoft Windows [Version 10.0.19041.1348]
- .NET Core SDK: 7.0.0-alpha.1.22061.11
> Fixing announcement of information about hidden columns and rows for DGV

- src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.CoCreateInstance.cs
- src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.IFileDialogEventsVtbl.cs
- src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
- src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.cs
That's piggyback on the previous work. I have to provide CCW for `IFileDialogEvents`. The multiselect did not use `ComWrappers`, since it requires me to provide RCW for `IShellItemArray`, but selection works using build-in COM.
> Operate open file dialog using ComWrappers

- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ImageListTests.cs
- src/System.Windows.Forms/tests/TestUtilities/ConditionalWinFormsFactAttribute.cs
- src/System.Windows.Forms/tests/TestUtilities/ConditionalWinFormsTheoryAttribute.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
Related Issues:
- #6597
- #6609 
- #6610
- #6635 
- Skipped unit tests that fail sometimes in arm64 and x86 environments, that blocks fixes deployment.
- No
- No
- Minimal
- CI build
> Added "Skip" attribute for fail unit tests in arm64 and x86

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionItem.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSettingsManager.cs
The regex source generator is new in .NET 7.  It does all the parsing and compilation of the regex that would have been done at run-time instead at compile time, improving startup and enabling additional optimizations that wouldn't otherwise be performed.  This updates the regexes used in winforms to use the generator.
> Use RegexGenerator in WinForms

- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/TabControlTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
Related Issue #6610 and Issue #6654
These tests fail sometimes in x86 CI build, that blocks deployment of fixes into sdk.
- Skipped unit tests that fail sometimes in arm64 and x86 environments, that blocks fixes deployment.
- No
- No
- Minimal
- CI build
> Adding more `Skip` attributes for flaky tests

- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.SnappableControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/CommandsPane.cs
- Enable nullability in SnappableControl and CommandsPane.
> Enable nullability in SnappableControl and CommandsPane

- Directory.Build.props
- eng/Versions.props
- pkg/Microsoft.Private.Winforms/Directory.Build.targets
- pkg/Microsoft.Private.Winforms/sdk/dotnet-windowsdesktop/UpdateFileClassification.ps1
- src/System.Windows.Forms.Analyzers.CSharp/src/System.Windows.Forms.Analyzers.CSharp.csproj
- src/System.Windows.Forms.Analyzers/src/System.Windows.Forms.Analyzers.csproj
Relates to #6663
Ping assembly versions similar to https://github.com/dotnet/runtime/blob/bbc766a7c65716305919bc691d696b1e46fa6f62/eng/Versions.props#L14 and https://github.com/dotnet/aspnetcore/blob/c0575788ecadd6e5cfeb4eab635c13b5fd433d37/Directory.Build.targets#L88 to avoid revving assembly versions in servicing releases.
> Pin assembly versions to prevent revving those in servicing releases

- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ACNativeWindow.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildNativeWindow.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlNativeWindow.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.ErrorWindow.cs
- src/System.Windows.Forms/src/System/Windows/Forms/NotifyIcon.NotifyIconNativeWindow.cs
- src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.WebBrowserBaseNativeWindow.cs
- Enable nullability in classes that inherit from NativeWindow.
> Enable nullability in classes that inherit from NativeWindow

- src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePicker.DateTimePickerAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePickerTests.cs
Fixes #6590
- Return formatted `Value` in the getter of the `Text` property to make the behavior of this property consistent with the documentation:
https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.datetimepicker.text?view=windowsdesktop-6.0
- `Text` property will return a formatted Value instead of an empty string:
- No
- Minimal
- Unit tests
- CTI testing
.NET SDK 7.0.0-preview-2.22103.2
Microsoft Windows [Version 10.0.19043.1466]
> Fixing Text property of the DateTimePicker

- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/SplitContainer.SplitContainerAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/SplitContainer.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/SplitContainer.SplitContainerAccessibleObjectTests.cs
Partially implements #3421
- Added and implemented splitContainer accessible object
**Before update:**
**After update:**
- No
- Minimal
- CTI team
- Narrator
- Inspect
- Microsoft Windows [Version 10.0.22000.318]
- .NET Core SDK: 7.0.0-alpha.1.21562.1
> Added UIA support for split container

- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/PrintPreviewControl.PrintPreviewControlAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PrintPreviewControl.PrintPreviewControlAccessibleObjectTests.cs
Partially implements #3421
- Added and implemented printPreviewControlaccessible object
- **Before update:**
- **After update:**
Provider was changed.
- No
- Minimal
- Unit tests
- CTI team
- Narrator
- Inspect
- Microsoft Windows [Version 10.0.22000.318]
- .NET Core SDK: 7.0.0-alpha.1.21562.1
> Adding UIA support for PrintPreviewControl

- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/RichTextBoxTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePickerTests.cs
Main issue #6713.
Relased issues:
- #6609 
- #6729 
- #6730 
- #6597 
- Fix `DateTimePickerTests` test ([comment](https://github.com/dotnet/winforms/issues/6713#issuecomment-1045056854))
- Add `Skip` attributes for new flaky tests
- No
- No
- Minimal
> Skipped more flaky tests

- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.DateTimePickerAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ControlAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePicker.DateTimePickerAccessibleObjectTests.cs
Implements part of #3421
- Switched on `SupportsUiaProviders` property of `DateTimePicker` class.
- Added needed automation events to fix behavior in Narrator.
- Reworked `DateTimePickerAccessibleObject`, added unit tests.
- Added workaround to check `AccessKey` for dtp in `ControlAccessibleObjectTests`.  
- Improving development experience for `DateTimePicker` control accessibility.
- No
- Minimal
Changes in accessibility tools.
The behavior in Narrator was restored after the fix. Seems was resolved problem described in issue #5487.
The Narrator doesn't work with dtp calendar. Seems, it is native control problem, because the Narrator doesn't work with dtp in MFC app at all. You can see it on following gif below.
I attach the test MFC app with dtp: …
> Implementing uia provider support for DTP control

- src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
This fixes .NET designer issue - https://github.com/dotnet/winforms-designer/issues/3399 and https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1419310
.NET Winforms designer is not usable with accessible tech. 
This change prevents client notifications from being sent from the designer server process, where we will be setting the opt-out switch. These notifications are problematics as clients might send messages to the server process and cause a deadlock.
This is ported from the 6.0 GA change -  https://github.com/dotnet/winforms/pull/6035. I then searched for all instances of the problematic API - `UIARaise`* and `NotifyWinEvent` to ensure that they are hidden under this switch.
Tested controls that send WinEvents in the common design-time scenarios under JAWS, Narrator, NVDA, AI …
> [5.0] WinForms .NET designer freezes when JAWS is narrating 

- src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
.NET designer bug - https://github.com/dotnet/winforms-designer/issues/3399 and https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1419310
Winforms designer is not usable with accessible tech. 
This change prevents client notifications from being sent from the designer server process, where we will be setting the opt-out switch. These notifications are problematics as clients might send messages to the server process and cause a deadlock.
This is ported from the 6.0 GA change - https://github.com/dotnet/winforms/pull/6035. I then searched for all instances of the problematic API - `UIARaise`* and `NotifyWinEvent` to ensure that they are hidden under this switch.
Tested controls that send WinEvents in the common design-time scenarios under JAWS, Narrator, NVDA, AI and Inspect.
> [3.1] WinForms .NET designer freezes when JAWS is narrating

- src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/ButtonBaseAdapter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/ButtonPopupAdapter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
Fixes #6556, #6560 
- The #6556 is reproduced because in the case described in the repro steps, an additional border is drawn by the `DrawDefaultBorder` method. Since they use a different color, the `Button` comes with a two-color border.
- Changed the logic for drawing borders so that the same color is used for both methods as it was before. 
- The #6560 is reproduced because the original color has low contrast.
- Added logic for color darkening.
* Issue #6556
**After fix:**
* Issue #6560
**After fix:**
- Yes (from #6021)
- Minimal
- CTI team 
- Microsoft Windows [Version 10.0.19044.1469]
- .NET Core SDK: 7.0.0-preview.2.22075.9
> Fixing Popup button border color 

- src/System.Windows.Forms/src/Resources/SR.resx
- src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
- src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownEdit.UpDownEditAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/UpDownBase.UpDownEdit.UpDownEditAccessibleObjectTests.cs
Fixes #6359
- The issue is reproduced when the NumericUpDown.AccessibleObject has no name. In this case, we simply announce the "edit" for text field. This behavior can be considered expected by default. But in accordance with the behavior of the combobox, I suggest announcing the default name for the editor (spinner) if the NumericUpDown.AccessibleObject  did not return a name.
- Added default name for text field inside NumericUpDown.
**After fix:**
- No
- Minimal
-  Unit tests
- CTI team
- Narrator
- NVDA
- JAWS
- Inspect
- .NET Core SDK: 7.0.0-preview.2.22113.2
> Fixing incorrect name for NumericUpDown editor

- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.DateTimePickerAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePicker.DateTimePickerAccessibleObjectTests.cs
Fixes #6317 
- Overridden `DefaultAction` property of DateTimePicker AO to return `Expand` value if the control is collapsed. Otherwise, return `Collapse` if the control is expanded.
- Overridden `DoDefaultAction` method to perform `Collapse()` or `Expand()` methods.
- Added test case for it.
- Receive the correct `DefaultAction` value of a dtp control and improve accessibility.
- No
- Minimal
Property returns empty value.
Returns `Expand` or `Collapse` value.
Also has no additional errors in AI.
- Manually
- Unit tests
- CTI
- Inspect
- AI
- Narrator
- .Net version:   6.0.100
- OS version: 10.0.19044
> Fixing empty value of DefaultAction of DateTimePicker control

- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewTextBox.GridViewTextBoxAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewTextBox.GridViewTextBoxAccessibleObjectTests.cs
Fixes #6704
- The issue is reproduced because for `FragmentRoot` we return `PropertyGridView.AccessibilityObject` and not `PropertyGrid.AccessibilityObject`.
- Now `FragmentRoot` returns `PropertyGrid.AccessibilityObject`. This matches the behavior of other accessibility objects in the `PropertyGrid`.
**After fix:**
- Yes
- Minimal
- CTI team
- Unit-tests
- JAWS
- NVDA
- Narrator
- Inspect 
- .NET Core SDK: 7.0.0-preview.3.22121.13
> Fixing a JAWS exception in a PropertyGrid

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
- Enable nullability in FolderBrowserDialog.
> Enable nullability in FolderBrowserDialog

- src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileDialogWrapper.cs
- src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileOpenDialogWrapper.cs
- src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.FileSaveDialogWrapper.cs
- src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.ShellItemArrayWrapper.cs
- src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.Vista.cs
- src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.VistaDialogEvents.cs
- src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.cs
- src/System.Windows.Forms/src/System/Windows/Forms/SaveFileDialog.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FileDialogTests.cs
Do not use COM interfaces for file dialogs at all except IFileDialogEvents
Right now each CoClass created using CoCreateInstance represented as unique RCW
That RCW still uses interfaces, but all important methods are implicitly declares
No explicit interface method of IFileDialog, IOpenFileDialog and ISaveFileDialog
are used.
IShellItem and IShellItemArray still used, but that usage comes from IXXXFileDialog
interfaces. If I remove them, I can be explicit about wrappers.
After this point, there two options
- Leave interfaces as is, wasteful RCW, good for documentation
- Remove interfaces, simplify RCW even more. Keeping track of method table would be problematic.
Related to #5163
> Explicitly use ComWrappers for file dialogs

- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewEdit.GridViewEditAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewEdit.GridViewEditAccessibleObjectTests.cs
Fixes #6704
- The issue is reproduced because for `FragmentRoot` we return `PropertyGridView.AccessibilityObject` and not `PropertyGrid.AccessibilityObject`.
- Now `FragmentRoot` returns `PropertyGrid.AccessibilityObject`. This matches the behavior of other accessibility objects in the `PropertyGrid`.
**After fix:**
- Yes
- Minimal
- CTI team
- Unit-tests
- JAWS
- NVDA
- Narrator
- Inspect 
- .NET Core SDK: 6.0.2
> Fixing a JAWS exception in a PropertyGrid (port to 6.0)

- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Properties.cs
This should had been removed when we removed CAS-related code. ControlAccessibleObject was demanding unmanaged code permissions and that is why we did not allow controls to override it. In .NET CAS is deprecated, and this type check is not relevant any more.
> Removed old constraint related to CAS.

- src/System.Windows.Forms/src/System/Windows/Forms/NumericUpDown.NumericUpDownAccessibleObject.cs
- Enable nullability in NumericUpDownAccessibleObject.
> Enable nullability in NumericUpDownAccessibleObject

- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.PropertyGridViewAccessibleObject.cs
- Enable nullability in PropertyDescriptorGridEntryAccessibleObject.
> Enable nullability in PropertyDescriptorGridEntryAccessibleObject

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.DataGridViewTextBoxEditingControlAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.PropertyGridAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/CommandsPane.CommandsPaneAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/DetailsButton.DetailsButtonAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/HelpPane.HelpPaneAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.PropertyGridViewAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridToolStrip.PropertyGridToolStripAccessibleObject.cs
- Enable nullability in PropertyGridAccessibleObject.
> Enable nullability in PropertyGridAccessibleObject

- src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Label.cs
- Remove Image null check before calling ImageAnimator.UpdateFrames
- Reflects the changes from https://github.com/dotnet/runtime/pull/65949.
> Remove Image null check before calling ImageAnimator.UpdateFrames

- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Fixes #6259 
When moving the Form to a new monitor with different DPI settings, Windows changing the Dpi
on the handle and sending DPI changed message to the Form are not in sync. Due to this,
method User32.GetClientRect are returning the incorrect value.  This method is not
accurate with respect to adornments metrics and their Dpi. Hence this work around.
This method is expected to be called whenever there is WINDOWSPOSITION_CHANGED message is triggered.
We will be calling UpdateBounds(x, y, width, height) explicitly, instead, for MDI child windows
if we had to change the size. for every other control, bounds are changed here.
- No
- Low. Impacts only MDI child forms
- Manual.
> Fixing layout issues of Anchored/Docked controls in the MDI child forms

- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TreeView.TreeViewAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNode.TreeNodeAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeView.TreeViewAccessibleObjectTests.cs
Implemented accessible objects for TreeView and TreeNode. Added needed automation events and unit tests.
Implements part of #3421
- Switched on `SupportsUiaProviders` property of `TreeView` class.
- Implemented accessible objects for `TreeView` and `TreeNode` classes.
- Added needed automation events and unit tests.
- Improving development experience for `TreeView` control accessibility.
- No
- Minimal
There is no specific errors. You can see errors on next image, but they are not about accessibility changes were created in this PR.
This realization sets calling node as `TopNode`  of `TreeView` if the node is invisible. Looks like it works the same. 
By default, when we focus on a `TreeView` control, Inspect and Narrator highlight the `SelectedNode` of
this control. As I know it takes …
> Implementing support UIA Provider for TreeView control

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.DateTimePickerAccessibleObject.cs
- Enable nullability in DateTimePickerAccessibleObject.
> Enable nullability in DateTimePickerAccessibleObject

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintControllerWithStatusDialog.BackgroundThread.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintControllerWithStatusDialog.StatusDialog.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintControllerWithStatusDialog.cs
- Enable nullability in PrintControllerWithStatusDialog.
> Enable nullability in PrintControllerWithStatusDialog

- src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObjectTests.cs
Fixes #6306
`ListViewGroupAccessibleObject.GetNativeGroupId` attempted to retrieve information about a group from the native control based on its positional index. However, the position in `ListView.Groups` does not always correspond to the position in the native control (see more information here: https://github.com/dotnet/winforms/issues/6306#issuecomment-1020301155). Specifically, there is a difference when:
- The user adds a `ListView` to a `Form` and groups to the `ListView` using the visual designer, in which case the `ListView` handle will be created after groups have been added
- The user adds a `ListView` to a `Form` and then creates groups programmatically after the form has been displayed. In this case, the `ListView` handle will be created before groups are added
In the former …
> Fix ListViewGroupAccessibleObject.GetNativeGroupId returning incorrect value

- src/System.Windows.Forms/tests/IntegrationTests/NativeHost.ManagedControl/NativeHost.ManagedControl.csproj
EnableDynamicLoading properly set right now in the Microsoft.NET.Sdk.targets
> Remove no longer needed workaround

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripHighContrastRenderer.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripButtonTests.Rendering.cs
Fixes #5676
- Added logic for drawing dotted borders for selected `ToolStripButton` in contrast mode.
**Before:**
System render mode:
Professional render mode:
**After:**
System render mode:
Professional render mode:
- No
- Minimal
- Manual
- CTI team
- . NET Core SDK: 7.0.0-preview.3.22123.2
> Fixed visibility of selected ToolStripButtons in High Contrast mode

- src/System.Windows.Forms/src/ILLink.Substitutions.xml
- src/System.Windows.Forms/src/Resources/SR.resx
- src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
- src/System.Windows.Forms/src/System.Windows.Forms.csproj
- src/System.Windows.Forms/src/System/Windows/Forms/PictureBox.cs
Indirectly related to #1756 because if that would work, I would be able to fix #1756 using the same approach.
WebRequest bring ton of code to WinForms which is old, and not really interesting. NativeAOT suffer from this.
Inspired by https://github.com/dotnet/runtime/pull/38397
By itself if applying `<RuntimeHostConfigurationOption Include="System.Windows.Forms.PictureBox.UseWebRequest" Value="false" Trim="true" />` it will shave 1Mb from 20Mb  of my sample application which compiled under NativeAOT. I include all controls in that application.
> Option to not use WebRequest for PictureBox

- src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2ColorConverter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2DataTypeToManagedDataTypeConverter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2FontConverter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PictureConverter.cs
- Enable nullability in some COM2 converters.
> Enable nullability in some COM2 converters

- eng/packageContent.targets
Without these changes in binlog I see paths with `\\/` which is distraction and Explorer and a lot of other apps do not like paths like this.
> Pedantically construct paths for XML files

- eng/pipelines/post-build.yml
There no TRX files produced during tests runs anywhere.
Practically this is does not affects anything (<1sec), buy whole idea "to have step which do nothing" seems to be off.
> Remove publishing TRX files from public CI

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.ConnectionPointCookie.cs
- Enable nullability in ConnectionPointCookie.
> Enable nullability in ConnectionPointCookie

- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxEditingControl.DataGridViewComboBoxEditingControlAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxControlAccessibleObject.cs
- Enable nullability in DataGridViewComboBoxEditingControlAccessibleObject.
> Enable nullability in DataGridViewComboBoxEditingControlAccessibleObject

- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Reverts dotnet/winforms#6752
Related to #6259 
This is a recent fix but we found a regression in further testing the scenarios. Will be looking at this issue again and will be coming with broader fix. Re opened the issue again.
> Revert "Fixing layout issues of Anchored/Docked controls in the MDI child forms"

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/NumericUpDownAcceleration.cs
- src/System.Windows.Forms/src/System/Windows/Forms/NumericUpDownAccelerationCollection.cs
- Enable nullability in NumericUpDownAcceleration and NumericUpDownAccelerationCollection.
> Enable nullability in NumericUpDownAcceleration and NumericUpDownAccelerationCollection

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripOverflow.ToolStripOverflowAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripOverflow.cs
- Move ToolStripOverflowAccessibleObject to a separate file and enable nullability to it.
> Move ToolStripOverflowAccessibleObject to a separate file and enable nullability to it

- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridErrorDialog.cs
- Enable nullability in GridErrorDialog.
> Enable nullability in GridErrorDialog

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupItemCollection.cs
- Enable nullability in ListViewGroupCollection and ListViewGroupItemCollection.
> Enable nullability in ListViewGroupCollection and ListViewGroupItemCollection

- src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupTests.cs
Fixes #6468
Previously, `ListView` would toggle `CollapsedState` of current `ListViewGroup` between `Expanded` and `Collapsed` if a `ListViewItem` was selected and:
- The left arrow key was pressed and the group state was `Expanded`
- The right arrow key was pressed and the group state was `Collapsed`
It did this regardless of whether the key press triggered an actual change in native state resulting in repeated `GroupCollapsedStateChanged` events and the group's `CollapsedState` property becoming out of sync with native state.
This change reads native state on arrow key press and updates `CollapsedState`/raises `GroupCollapsedStateChanged` only when the state is different.
`ListViewGroup.CollapsedState` should no longer be out of sync with native state and phantom …
> Update ListViewGroup.CollapsedState from native when changed by keyboard

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.DataGridViewSelectedRowCellsAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewSelectedRowCellsAccessibleObjectTests.cs
- Enable nullability in DataGridViewSelectedRowCellsAccessibleObject.
> Enable nullability in DataGridViewSelectedRowCellsAccessibleObject

- src/System.Windows.Forms/src/System/Windows/Forms/ListView.IconComparer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
- Enable nullability in IconComparer.
> Enable nullability in IconComparer

- src/System.Windows.Forms.Design/src/System/Drawing/Design/ColorEditor.CustomColorDialog.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/Drawing/Design/ColorEditorTests.CustomColorDialogTests.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/Drawing/Design/ColorEditorTests.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Dialogs.Designer.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Dialogs.cs
Resolves #6915
The regression was caused by the migration of types and resources from System.Drawing.Design to System.Windows.Forms.Design, and the resource is now getting embedded as `System.Windows.Forms.Design.colordlg.data` instead of `System.Drawing.Design.colordlg.data`.
* .NET 6 version embeds the resource as follows:
* The .NET Framework version embeds it as:
There are few ways of addressing this regression - update the `GetManifestResourceStream()` call and pass an updated resource name, or embed the resource under a different name. The latter felt a little more opaque from the maintenance perspective.
I presume we missed this because:
* we had no test coverage for this dialog as it can only be invoked via the `PropertyGrid` when editing a color, and it's not possible to invoke …
> Correctly retrieve the embedded resource

- src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FormTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FormTests.cs
Fixes #6153. 
`System.Windows.Forms.Form` caches size and location upon becoming maximized and restores it when exiting maximized state. This creates a problem when using Windows snap layout since the form will be brought out of a maximized state and "docked" to a specific location by Windows only have its size and location subsequently changed to the internally cached values when the form processes `WM_WINDOWPOSCHANGED`.
~~If it were possible to not use internally cached values when coming out of a maximized state due to a snap layout command, this problem should be resolved. It does not appear that Windows provides any way to detect that. Instead, this PR assumes that any position change not initiated by the user or by a programmatic change of `Form.WindowState` is instead initiated by …
> Fix Form snap layout when in maximized state

- src/System.Windows.Forms/src/System/Windows/Forms/HtmlElement.HtmlElementShim.cs
- src/System.Windows.Forms/src/System/Windows/Forms/HtmlShim.cs
- src/System.Windows.Forms/src/System/Windows/Forms/HtmlShimManager.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.FeedbackRectangle.cs
Fixes #6858
Remove unnecessary empty finalizers.
- [ResXResourceReader](https://github.com/dotnet/winforms/blob/55e1755b579395e7e22fecf340905c79ccfa9b1a/src/System.Windows.Forms/src/System/Resources/ResXResourceReader.cs#L194)
- [ResXResourceWriter](https://github.com/dotnet/winforms/blob/55e1755b579395e7e22fecf340905c79ccfa9b1a/src/System.Windows.Forms/src/System/Resources/ResXResourceWriter.cs#L549)
- [ApplicationContext](https://github.com/dotnet/winforms/blob/55e1755b579395e7e22fecf340905c79ccfa9b1a/src/System.Windows.Forms/src/System/Windows/Forms/ApplicationContext.cs#L91)
- [DataGridViewBand](https://github.com/dotnet/winforms/blob/55e1755b579395e7e22fecf340905c79ccfa9b1a/src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewBand.cs#L817)
- …
> Empty finalizers removed.

- src/System.Windows.Forms/src/System/Windows/Forms/StringSource.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ComboBoxTests.cs
That way we do not re-use released RCW
Fixes #6953
> Create unique instance for each AutoComplete object

- src/System.Windows.Forms.Design/src/System/Drawing/Design/ColorEditor.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/Drawing/Design/ColorEditorTests.CustomColorDialogTests.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/Drawing/Design/ColorEditorTests.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Dialogs.Designer.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Dialogs.cs
Resolves #6915
The regression was caused by the migration of types and resources from System.Drawing.Design to System.Windows.Forms.Design, and the resource is now getting embedded as `System.Windows.Forms.Design.colordlg.data` instead of `System.Drawing.Design.colordlg.data`.
* .NET 6 version embeds the resource as follows:
* The .NET Framework version embeds it as:
There are few ways of addressing this regression - update the `GetManifestResourceStream()` call and pass an updated resource name, or embed the resource under a different name. The latter felt a little more opaque from the maintenance perspective.
I presume we missed this because:
* we had no test coverage for this dialog as it can only be invoked via the `PropertyGrid` when editing a color, and it's not possible to invoke …
> Servicing: Correctly retrieve the embedded resource 

- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ButtonTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
Related issues: 
* https://github.com/dotnet/winforms/issues/6713
* https://github.com/dotnet/winforms/issues/6610
* https://github.com/dotnet/winforms/issues/6714 
* https://github.com/dotnet/winforms/issues/6739
* https://github.com/dotnet/winforms/issues/6926
- Skip tests that sometimes fail in CI and block deployment. 
- Some tests were already skipped for certain architecture but turned out to be flaky for other architectures as well (#6610, #6926, #6739). This PR removes skip condition for such tests so that they are skipped for all architectures.
- Another test (#6714) was reported to be flaky but not skipped yet.
- No
- No
- Minimal
- CI build
> Adding Skip attribute or adjusting skip condition for flaky tests

- src/System.Windows.Forms/src/System/Windows/Forms/Splitter.SplitData.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Splitter.SplitterMessageFilter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Splitter.cs
- Move SplitData and SplitterMessageFilter to separate files.
> Move SplitData and SplitterMessageFilter to separate files

- src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2ExtendedUITypeEditor.cs
- Enable nullability in Com2ExtendedUITypeEditor.
> Enable nullability in Com2ExtendedUITypeEditor

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.cs
I assume that this is a bug which we all living with .NET 2.0
Highly unlikely this is ever would be fixed, but would like to discuss possible options.
> Cut working incorrectly in ToolStripTextBox

- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
Fixes #6155.
`ComboBox.FlatStyle` has two modes that do not show up correctly when in high contrast mode:
- `FlatStyle.Flat` renders the `ComboBox` with no border
- `FlatStyle.Popup` renders the same as `FlatStyle.Flat` except when focused/moused over, in which case it attempts to simulate the natively drawn border
Since high contrast mode uses the same color for `ComboBox.BackColor` as it does for `Form.BackColor` and since the control has no border, it is not visually perceptible except for its chevron. This PR checks for high contrast mode and renders the same as `FlatStyle.Standard`.
- `ComboBox` will be visible in high contrast mode
- No
Should be minimal with the exception of fringe cases such as:
- Possibility of a developer deriving from `ComboBox` and performing their own custom …
> Do not use flat style in high contrast mode

- src/Microsoft.VisualBasic/tests/IntegrationTests/VisualBasicRuntimeTest/VisualBasicRuntimeTest.csproj
- src/System.Windows.Forms/tests/AccessibilityTests/AccessibilityTests.csproj
- src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/DemoConsole.csproj
- src/System.Windows.Forms/tests/IntegrationTests/NativeHost.ManagedControl/NativeHost.ManagedControl.csproj
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/WinformsControlsTest.csproj
Error window in Visual Studio displays the following
```
Warning	NU1505	Duplicate 'PackageDownload' items found. Remove the duplicate items or use the Update functionality to ensure a consistent restore behavior. The duplicate 'PackageDownload' items are: 
Microsoft.NETCore.App.Host.win-x64 [7.0.0-preview.4.22214.7], 
Microsoft.NETCore.App.Host.win-x64 [7.0.0-preview.4.22214.7],
Microsoft.NETCore.App.Host.win-x64 [7.0.0-preview.4.22214.7],
Microsoft.NETCore.App.Host.win-x64 [7.0.0-preview.4.22214.7].
AccessibilityTests	D:\winforms\src\System.Windows.Forms\tests\AccessibilityTests\AccessibilityTests.csproj
```
The warning is supposed to report downloads of the same package with different versions - https://docs.microsoft.com/en-us/nuget/reference/errors-and-warnings/nu1505
> Disable nuget warning NU 1505 until https://github.com/dotnet/sdk/issues/24747 is fixed.

- src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/Com2IPerPropertyBrowsingHandler.Com2IPerPropertyEnumConverter.cs
- Enable nullability in Com2IPerPropertyEnumConverter.
> Enable nullability in Com2IPerPropertyEnumConverter

- src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
- src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/MainFormControlsTabOrder.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/FormShowInTaskbar.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FormTests.cs
Fixes  https://github.com/dotnet/winforms/issues/6421.
If you set ShowInTaskbar=false, the winforms will recreate the Handle. It will call RecreateHandleCore() from Control.cs.
In method WmNCDestroy(ref Message m) from class Form.cs, The program needs to confirm whether the handle is being recreated before setting the value of the DialogResult.
If the program is in the process of recreating the handle, setting DialogResult = DialogResult.Cancel will cause the Form to be automatically closed.
> Fixing ShowInTaskbar=false doesn't work in some cases (#6421)

- src/System.Windows.Forms.Primitives/src/Interop/VSSDK/Interop.IProvidePropertyBuilder.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IProvidePropertyBuilderHandler.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyBuilderUITypeEditor.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyPageUITypeConverter.cs
- Enable nullability in classes that inherit from Com2ExtendedUITypeEditor.
> Enable nullability in classes that inherit from Com2ExtendedUITypeEditor

- eng/CodeAnalysis.src.globalconfig
- eng/CodeAnalysis.test.globalconfig
- eng/CodeStyle.props
- eng/CodeStyle.targets
- src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Helpers/FileSystemUtils.vb
- src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Logging/FileLogTraceListener.vb
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerHost.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/DesignerSerializationManager.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DocumentDesigner.AxToolboxItem.cs
- src/System.Windows.Forms.Primitives/tests/TestUtilities/NoAssertContext.cs
- src/System.Windows.Forms/src/System/Resources/AssemblyNamesTypeResolutionService.cs
- src/System.Windows.Forms/src/System/Resources/ResXFileRef.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.OleInterfaces.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IManagedPerPropertyBrowsingHandler.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs
- src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridToolTip.cs
- src/System.Windows.Forms/src/System/Windows/Forms/SendKeys.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutSettingsTypeConverter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
- src/System.Windows.Forms/tests/UnitTests/SRCategoryAttributeTests.cs
- src/System.Windows.Forms/tests/UnitTests/SRDescriptionAttributeTests.cs
- Use Microsoft.CodeAnalysis.NetAnalyzers instead of Microsoft.CodeAnalysis.FxCopAnalyzers which is deprecated.
- Similarly to https://github.com/dotnet/winforms/pull/3541, I took the settings from https://github.com/dotnet/runtime/blob/release/6.0/eng/CodeAnalysis.src.globalconfig of the release/6.0 branch of the runtime repository. I disabled some rules that produced new warnings with `TODO:`.
- I also took `_SkipUpgradeNetAnalyzersNuGetWarning` from https://github.com/dotnet/roslyn-analyzers/blob/3393ecfccd4331ced6423e9b875187ee377f1ce2/Directory.Build.props#L28 to avoid build warnings as described in https://docs.microsoft.com/en-us/dotnet/fundamentals/code-analysis/overview.
- I removed some `TODO`s in subsequent commits.
> Use Microsoft.CodeAnalysis.NetAnalyzers instead of Microsoft.CodeAnalysis.FxCopAnalyzers

- src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarBodyAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarRowAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.MonthCalendarAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
Fixes #6852
- Use the `UiaDisconnectProvider` method cascade through the hierarchy of the classes to free objects held by accessibility tool
- Only static comparers are left at memory and their amount aren't increasing after several recurrences of the repro steps described in issue
- MonthCalendar memory will stop leaking
- No
- Minimal
- Manual testing (_using WinDbg, see the screenshots above_)
- CTI team
- Microsoft Windows [Version 10.0.19043.1586]
- .NET 7.0.0-preview.3.22159.12
> Fixing MonthCalendar accessible object leaks

- src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNode.TreeNodeAccessibleObjectTests.cs
Fixes #6732
This allows a screen reader announce nodes states correctly (expand/collapse and checked/unchecked)
These changes don't affect any UIA properties, patterns and actions (except control type).
These changes affect the case when `CheckBoxes` is **true** only.
This fix is the reworked implementation of #6940.
See [comment](https://github.com/dotnet/winforms/pull/6940#issuecomment-1096780371)
- Change `TreeNode` accessible object control type to `tree item` despite CheckBoxes property
- A user can hear correct and full info about nodes (affect the case when `CheckBoxes` is true)
- A user will hear `tree item` as tree node control type even it has a check box
- No
- Middle, the fix changes the familiar control type for nodes
Narrator doesn't announce:
- "expand-collapse" state of a …
> Fixing `TreeNode` accessible object status announcement by a screen reader

- src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewNativeItemCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
- Replace hashtable with generic dictionary in ListView.
> Replace hashtable with generic dictionary in ListView

- src/System.Windows.Forms/src/System/Windows/Forms/Screen.MonitorEnumCallback.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Screen.cs
- Use generic list in MonitorEnumCallback.
> Use generic list in MonitorEnumCallback

- src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeCollectionTests.cs
- Replace hashtable with generic list in TreeView.
> Replace hashtable with generic dictionary in TreeView

- src/System.Windows.Forms/src/Properties/AssemblyInfo.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/DropDownButton.DropDownButtonAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.DropDownHolderAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewListBoxAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewTextBox.GridViewTextBoxAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridInternal/DropDownButton.DropDownButtonAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridInternal/PropertyGridView.DropDownHolder.DropDownHolderAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridInternal/PropertyGridView.GridViewListBox.GridViewListBoxAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridInternal/PropertyGridView.GridViewTextBox.GridViewTextBoxAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/System.Windows.Forms.UI.IntegrationTests.csproj
- src/System.Windows.Forms/tests/TestUtilities/Properties/InternalsVisibleTo.cs
- src/System.Windows.Forms/tests/TestUtilities/PropertyGridInternal/SubPropertyGrid.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/DropDownButton.DropDownButtonAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.DropDownHolderAccessibleObjectTests.cs
Resolves dotnet#2848 by fixing sibiling relationship between child property descriptors and selected entry controls. Also resolves dotnet#4876 by fixing parent-child relationship between drop-down holder and listbox.
The fixes are implemented by adding helper methods to retrieve a sibling node for a specified child node. This implementation removes the need for copy-paste throughout different child nodes of property descriptor entry, it greatly simplifies the implementation and helps to avoid mistakes in future because the implementation is now located in a single place.
- Fix sibling relationship between child property descriptors and selected entry controls
- Fix parent-child relationship between dropdown holder and listbox
- Accessibility tools may incorrectly navigate through the …
> Fixing PGV accessibility tree for property descriptors and dropdown holders

- src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IDispatchConverter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IVsPerPropertyBrowsingHandler.cs
- Enable nullability in Com2IDispatchConverter.
> Enable nullability in Com2IDispatchConverter

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.AccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewAccessibleObjectTests.cs
Property value was ignoring whether DGV was focused or not.
Now for empty DGV  `HasKeyboardFocusProperty` will have the same value as owner's Focused property. For non-empty DGV it will remain always false as focus will be acquired by inner cells.
Fixes #7026
- Change empty `DataGridView`'s `HasKeyboardFocus` property calculation to reflect DGV focused state.
- `HasKeyboardFocus` will have correct value for empty `DataGridView`.
- No
- Minimal
Without focus - `HasKeyboardFocus` is true:
With focus (note the dotted line on DGV) - `HasKeyboardFocus` is true:
Without focus - `HasKeyboardFocus` is false:
With focus (note the dotted line on DGV) - `HasKeyboardFocus` is true:
- Manual (with Inspect tool)
- Unit
- CTI
Tested following cases with Inspect tool:
- Have an empty DataGridView without …
> Fix empty DataGridView HasKeyboardFocus property being always true

- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.AnchorInfo.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Layout/DockAndAnchorLayout.cs
- src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/MainFormControlsTabOrder.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/AnchorLayoutTests.Designer.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/AnchorLayoutTests.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/AnchorLayoutTests.resx
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DockLayoutTests.Designer.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DockLayoutTests.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DockLayoutTests.resx
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
Fixes #5774
Updating `AnchoriInfo `is only needed when control is ready for layout. `InitLayoutCore()` does call `UpdateAnchorInfo()`.
At the least, we are checking if control is parented before updating `AnchorInfo`. This helps avoid calculating
`AnchorInfo `with default initial values of the Control. They are always overridden when layout happens.
We have one other issue in the `AnchorInfo `calculations that is being investigated but this change will indirectly fix the #5774.
> Fixing Anchor Info calculations.

- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Form.FormAccessibleObjectTests.cs
Fixes #6896
This is a regression from .NET 3.1 after #2096. (.NET Core 3.0 and .NET Framework work well)
- Raise the focus event for a form or its active control, when the form is opening. Thereby a screen reader will focus on the form and announce its title.
**We can't raise the UIA focus event in `OnGotFocus`, `OnShown`, `OnLoad` event handlers, because when they work AccessibleObject is not created yet and we can't be sure that a UIA tool (eg. Narrator) is working. It's a Form control issue only, when it's showing and if the form is empty. So we have to use `OnAccessibleObjectCreated` and check a focus state there.
If the form has enabled and visible controls, we need to do nothing.**
- Now a user can know from Narrator that a form has been opened
- Yes (from #2096)
- Minimal
- Manual …
> Fixed Narrator announcement of an empty form or its inner controls when opening

- Directory.Build.targets
- eng/CodeStyle.targets
- src/System.Windows.Forms/tests/InteropTests/NativeTests/NativeTests.proj
* Reduce CMake verbosity
* Mark all projects under **\tests\* folders as non-shippable (relates to #7049 and #7065)
> Chores for test projects

- src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.CHARFORMAT2W.cs
- src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.CHARRANGE.cs
- src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.EDITSTREAM.cs
- src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.ENDROPFILES.cs
- src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.ENLINK.cs
- src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.ENPROTECTED.cs
- src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.FINDTEXTW.cs
- src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.GETTEXTEX.cs
- src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.GETTEXTLENGTHEX.cs
- src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.GTL.cs
- src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.PARAFORMAT.cs
- src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.REQRESIZE.cs
- src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.RichEditPack.cs
- src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.SELCHANGE.cs
- src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.TEXTRANGE.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Message.cs
- src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
- src/System.Windows.Forms/tests/InteropTests/NativeTests/CMakeLists.txt
- src/System.Windows.Forms/tests/InteropTests/NativeTests/RichTextBoxTests.cpp
- src/System.Windows.Forms/tests/InteropTests/RichTextBoxTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MessageTests.cs
That remove one warning from linker.
> Remove Message.GetLParam since it is linker unfriendly

- src/Common/tests/TestUtilities/XUnit/UseCultureAttribute.cs
- src/Common/tests/TestUtilities/XUnit/UseDefaultXunitCultureAttribute.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MdiControlStripTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendar.CalendarCellAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
Mu OS default locale is set to "en-AU", and these tests kept failing for me. Add two new XUnit attributes to specify the desired locale.
/cc: @weltkante @vladimir-krestov I know that in the past you had troubles with some locale-dependent tests on your ends. If you could run these changes and confirm that (at least) these tests pass for you - it would be awesome. 
Also, if you see any other tests that may benefit from the new decoration - please let me know (or sent a PR in :)).
Thank you.
> Run selected tests in en-US culture

- docs/debugging.md
That change allow build just `System.Windows.Forms.Primitives` for example, and then pickup changes without need for building `System.Windows.Forms`.
> Use different paths for faster inner loop

- src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildEditUiaProvider.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.DataGridViewTextBoxEditingControlAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewTextBox.GridViewTextBoxAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.ToolStripTextBoxControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.ToolStripTextBoxControlAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownEdit.UpDownEditAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTextBox.ToolStripTextBoxControlAccessibleObjectTests.cs
Fixes #7080
- Move the real implementation into derived types (`TextBoxBaseAccessibleObject` and `ComboBoxChildEditUiaProvider`) like we did for the rest patterns in `AccessibleObject.cs` (eg. ExpandCollapse pattern)
- Reduce the logic of edit fields that have TextPattern behavior, inherit them from TextBoxBaseAccessibleObject, thereby taking many members from it and reducing the size of the types, making them simpler.
The main reason for this change - ~95% of accessible objects don't implement TextPattern and they don't know about this pattern and shouldn't keep text providers that are not used. The decision is based on discussions of CF #377144 (Bug 1043396)
PS. `ToolStripTextBoxControlAccessibleObject` doesn't need to inherit `FragmentNavigate` and `FragmentRoot` from …
> Reworking the base TextPattern implementation

- src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
- src/System.Windows.Forms/src/System/Windows/Forms/NotifyIcon.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
Some private methods have unused `Message m` parameters, so we can remove them.
- Remove unused m parameters
> Remove unused Message m parameters

- eng/CodeAnalysis.src.globalconfig
- Enable CA2014 warnings for src files.
> Enable CA2014 warnings for src files

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.DataGridViewRowAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowAccessibleObjectTests.cs
- Enable nullability in DataGridViewRowAccessibleObject.
> Enable nullability in DataGridViewRowAccessibleObject

- src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.CheckedIndexCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.CheckedIndexCollection.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CheckedListBox.CheckedIndexCollectionTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListView.CheckedIndexCollectionTests.cs
Addresses https://github.com/dotnet/winforms/pull/7018/files#r856669700
- Use OrThrowIfNull in CheckedIndexCollection constructor.
> Use OrThrowIfNull in CheckedIndexCollection constructor

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/TreeViewImageIndexConverter.cs
- Enable nullability in TreeViewImageIndexConverter.
> Enable nullability in TreeViewImageIndexConverter

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItemConverter.cs
- Enable nullability in ListViewItemConverter.
> Enable nullability in ListViewItemConverter

- src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
- src/System.Windows.Forms/tests/UnitTests/TextBoxBaseTests.cs
Fixes #6885
- Use the `UiaDisconnectProvider` method cascade through the hierarchy of the classes to free objects held by accessibility tool
- Nullify needed objects
- TextBox memory will stop leaking
- No
- Minimal
This fix isn't clearing all possible memory leaks. In the future nulling the `Owner` property at the `ControlAccessibleObject` class could be added:
1. This method should be added to the ControlAccessibleObject class:
```
internal void ClearOwnerControl()
{
this.Owner = null;
}
```
2. Owner property shoud be changed from this
`public Control Owner { get; }`
to something like this
`public Control? Owner { get; private set; }`
3. Calling of the `ClearOwnerControl` should be added/uncommented at the `ClearObjects` method of the `TextBoxBaseAccessibleObject` class
4. These changes …
> Fixing TextBox accessible object leaks

- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.ExceptionConverter.cs
- Enable nullability in ExceptionConverter.
> Enable nullability in ExceptionConverter

- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms/src/Resources/SR.resx
- src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.ToolStripAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItemAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownMenu.ToolStripDropDownMenuAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownMenu.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripOverflow.ToolStripOverflowAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripOverflowButton.ToolStripOverflowButtonAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripScrollButton.StickyLabel.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripScrollButton.StickyLabelAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripScrollButton.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitButton .ToolStripSplitButtonUiaProvider.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripDropDownMenu.ToolStripDropDownMenuAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripOverflow.ToolStripOverflowAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripScrollButton.ToolStripScrollButtonAccessibleObjectTests.cs
Fixes #6652
- The issue is reproduced because we don't have support for `ToolStripScrollButton` accessibility objects in the .NET Core.
- Added `StickyLabelAccessibleObject` for `ToolStripScrollButton`.
- Added support for `StickyLabelAccessibleObject` by other `ToolStrip` accessibility objects.
**After fix:**
- No
- Minimal
- Unit tests
- CTI team
- Inspect
- Narrator
- NVDA
- JAWS
- Microsoft Windows [Version 10.0.19044.1526]
- .NET Core SDK: 7.0.0-preview.4.22174.1
> Fixing ToolStripScrollBtton display issue

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewBand.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumn.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewElement.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewHeaderCell.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewElementTests.cs
Contribute to #6858.
This is continuation of https://github.com/dotnet/winforms/pull/6878 based on discussion.
Documentation for calling `GC.SuppressFinalize` on users subclasses also need to be updated some how...
- Existing UT.
- New UT for all subclasses coverage.
- Manual.
> Workaround for empty finalizers in DataGridView.

- src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNode.TreeNodeAccessibleObjectTests.cs
Fixes #7043
TreeView TreeNode accessible object supports Expand-Collapse pattern even if the node can't expand.
Changed TreeNode.TreeNodeAccessibleObject.cs at line 123:
UiaCore.UIA.ExpandCollapsePatternId => _owningTreeNode.childCount > 0
**Added unit tests:**
TreeNodeAccessibleObject_HasChildren_ExpandCollapsePatternAvailable
changed test TreeNodeAccessibleObject_IsPatternSupported_IfNodesAreEditable
User has no wrong options to expand or collapse a node which can't expand.
No
Minimal
TreeView TreeNode accessible object supports Expand-Collapse pattern even if the node can't expand.
TreeView TreeNode accessible object doesn't support Expand-Collapse pattern if the node can't expand.
Manual testing
Unit tests
CTI
Inspect
Microsoft Windows [Version 120.2212.4170.0]
.NET Core SDK: …
> Fixing TreeView TreeNode accessible object supports Expand-Collapse pattern even if the node can't expand.

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.AccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewAccessibleObjectTests.cs
Fixes #7079
Empty DataGridView has unexpected NotSortedAccessibleStatus item status.
Added additional check for empty DataGridView in DataGridViewAccessibleObject.GetPropertyValue() (DataGridView.AccessibleObject.cs- line 279).
Added unit tests:
DataGridViewAccessibleObject_ItemStatusProperty_IsExpected_ForNonSortedDGV
DataGridViewAccessibleObject_ItemStatusProperty_IsNull_ForEmptyDGV
User has correct UI properties.
Yes. Regression from https://github.com/dotnet/winforms/pull/6498
Minimal
Empty DataGridView has unexpected NotSortedAccessibleStatus item status:
Empty DataGridView has no item status:
Manual testing
Unit tests
CTI
Inspect
Microsoft Windows [Version 120.2212.4170.0]
.NET Core SDK: 7.0.100-preview.3.22179.4
> Removing an extra NotSortedAccessibleStatus for an empty DataGridView by adding check for empty DVG

- src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
Fixes #6096
Optimizing virtual mode checking when user uses keyboard to change checkbox state.
Changed ListView.cs at line 6702:
if (CheckBoxes) 
to 
if (CheckBoxes && !VirtualMode)
Existing unit test:
ListView_WmReflectNotify_LVN_KEYDOWN_SpaceKey_HasCheckBoxes_WithoutGroups_CheckedExpected
Optimized algorithm enhances performance and is easy to support. 
No
Minimal
Unit tests
Microsoft Windows [Version 120.2212.4170.0]
.NET Core SDK: 7.0.100-preview.3.22179.4
> Optimizing virtual mode checking when user uses keyboard to change checkbox state

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.Vista.cs
- src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.cs
- Enable nullability in OpenFileDialog.
> Enable nullability in OpenFileDialog

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
- src/System.Windows.Forms/src/System/Windows/Forms/SaveFileDialog.cs
- Enable nullability in SaveFileDialog.
> Enable nullability in SaveFileDialog

- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
This is a regression caused by #6778 that was helping optimize anchor info calculation.
However, in certain scenarios, we access `AnchorInfo` by assuming it was initialized at the time of handle creation and resetting it to null with `size change` is causing null reference exception in those scenarios.  Given regression was introduced in the current preview, taking this revert while we are investigating on how to get anchor layout working for higher DPI machines.
Fixes #7159 and #7090
> Reverse resetting the Anchorinfo when size chnages.

- src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Fixes #6381.
Nested controls are disabled for scaling once their parent layout is finished.
However, Parent might be reparented and could go through a new layout based on
its parent's scale dimensions.
We are maintaining multiple flags around scaling here and can be cleaned but require full testing. Making a scoped fix here to limit the risk.
> Fix nested/User control scaling.

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripHighContrastRenderer.cs
- Enable nullability in ToolStripHighContrastRenderer.
> Enable nullability in ToolStripHighContrastRenderer

- src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
Fixing an overflow exception in `TreeView` control in 32 bit process due to incorrect cast from `uint -> IntPtr`.
Fixes #7098 
- Cast return value (`nint`) of `GetMessagePos()` in the `TreeView `control to `int` before casting it to `IntPtr`
- Customer should be able to use `TreeView `control in a 32-bit process.
- Regressed from .NET 3.1
- Low. Similar change is in .NET 7.0 since Preview 1
> Fix TreeView overflow exception

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewAdvancedBorderStyle.cs
- Enable nullability in DataGridViewAdvancedBorderStyle.
> Enable nullability in DataGridViewAdvancedBorderStyle

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItemAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownMenu.ToolStripDropDownMenuAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripOverflow.ToolStripOverflowAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripOverflowButton.ToolStripOverflowButtonAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripDropDownMenu.ToolStripDropDownMenuAccessibleObjectTests.cs
Fixes #6763
- The issue is reproduced because we don't actually have interaction between the `ToolStripButtons` (`ToolStripSplitButton`, `ToolStripDropDownButton`, `ToolStripMenuItem`, `ToolStripOverflowButton`) and the `ToolStripDropDownMenu`  of those `ToolStripButtons`.
- Added logic for interacting `ToolStripButtons`with their `ToolStripDropDownMenus` and `ToolStripButtons`with parent `ToolStripDropDownMenu`.
**After fix:**
- No
- Minimal
- CTI team
- Unit tests
- Inspect
- Narrator
- .NET Core SKD: 7.0.0-preview.3.22167.1
> Fixing  UIA tree for ToolStripDropDownMenu 

- src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.IDropSourceVtbl.cs
- src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.IDropTargetVtbl.cs
- src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.IEnumFORMATETCVtbl.cs
- src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.IEnumStringVtbl.cs
- src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.IFileDialogEventsVtbl.cs
- src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.IStreamVtbl.cs
This PR ensures that methods marked as `UnmanagedCallersOnly` wrapped in the try/catch.
Also rename `inst` to `instance` to conform to code style
> Prevent exceptions to pops up from CCW

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/Design/ToolStripItemDesignerAvailabilityAttribute.cs
- Enable nullability in ToolStripItemDesignerAvailabilityAttribute.
> Enable nullability in ToolStripItemDesignerAvailabilityAttribute

- src/System.Windows.Forms/src/Resources/SR.resx
- src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
- src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemDetailsAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemListAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemTileAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItemTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Fixes #6230 
- The issue is reproduced because we believed that if an `ListViewItem` does not have a `ListView`, then it is inaccessible to the user and has no interaction with the Accessibility tool (Inspect, Narrator).
- Unfortunately, after deleting an `ListViewItem`, the Accessibility tool still tries to get information about it, although the `ListViewItem` no longer has a `ListView`. Therefore, the logic has been updated to work with an `ListViewItem` that does not have a `ListView`.
- Also, after the focused `ListViewItem` is removed, it remains cached in the `FocusedItem` property. It also forces the Accessibility tool to try to retrieve the data of the `ListViewItem` that is not displayed. As a fix, a logic was added to reset the `Focused` flag from the `ListViewItem`.
**Before …
> Fixing NullReferenceException when user removes ListViewItem

- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/NumericUpDownTests.cs
This is successfully catches bug in the https://github.com/dotnet/winforms/pull/7145 implementation
I need just call to `GetFocused`, but if some additional check can be made, I can add them.
> Test that numeric up-down successfully focused

- src/System.Windows.Forms/src/Resources/SR.resx
- src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItemTests.cs
This prevents exception in control disposal
> revert Exception on accessing accessible object after control is disposed

- src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/Oleaut32/VARIANTTests.cs
- src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/PARAMTests.cs
Can't build in the latest IntPreview Dev17 without this change.
`unchecked` - fixes a build break, `#pragma` suppression is only a warning.
> Removed build warning in VS

- docs/designer/troubleshooting.md
Changes:
- Title of designer's troubleshooting guide should be "How to troubleshoot the Windows Forms Out-Of-Process designer"
- Warning for logs classification is not required anymore
- Fixed a typo
> Updating designer troubleshooting guide

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSettings.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSettingsManager.SettingsStub.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSettingsManager.cs
- Enable nullability in ToolStripSettings and ToolStripSettingsManager.
> Enable nullability in ToolStripSettings and ToolStripSettingsManager

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.DataGridViewHitTestTypeInternal.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.DataGridViewValidateCellInternal.cs
- Enable nullability in DataGridViewHitTestTypeInternal and DataGridViewValidateCellInternal.
> Enable nullability in DataGridViewHitTestTypeInternal and DataGridViewValidateCellInternal

- docs/roadmap.md
I find this document via announcement to .NET 7 Preview 3
and I think it give bad vibes, and not adequately show efforts which is made in this repository.
So I take liberty and slice and dice this document with explanation how I think it should be improved and why.
- Removed *Past* section, since this is roadmap. WinForms deliver past achievements and even if it was glorious past, it may outshine Future goals. Also since it is on first place, it outshines even present
- Move *Present* to backyard. Technically that section is fine, but `Windows Forms runtime` is so bland and gives impression that there no goals for WinForms. Everybody who is familiar with corporate speak may think that "we consider everything, but do not commit to anything". I do not know how to rephrase, but want to point …
> Improve roadmap

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewEditingControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.cs
- Enable nullability in DataGridViewTextBoxEditingControl and IDataGridViewEditingControl.
> Enable nullability in DataGridViewTextBoxEditingControl and IDataGridViewEditingControl

- src/System.Windows.Forms.Primitives/src/System.Windows.Forms.Primitives.csproj
- src/System.Windows.Forms.Primitives/src/System/TrimmingConstants.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Message.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/PaddingConverter.cs
- IL2050 requires more ComWrappers work, don't want touch that
- IL2026 is `RequiresUnreferencedCodeAttribute` which require a bit more
brainpower.  Better keep that for later when more code would be annotated.
Jab at https://github.com/dotnet/winforms/issues/4649
> Cleanup trimming warnings from Primitives project

- src/System.Windows.Forms.Primitives/src/Interop/Imm32/Interop.ImmAssociateContext.cs
- src/System.Windows.Forms.Primitives/src/Interop/Imm32/Interop.ImmCreateContext.cs
- src/System.Windows.Forms.Primitives/src/Interop/Imm32/Interop.ImmGetContext.cs
- src/System.Windows.Forms.Primitives/src/Interop/Imm32/Interop.ImmGetConversionStatus.cs
- src/System.Windows.Forms.Primitives/src/Interop/Imm32/Interop.ImmGetOpenStatus.cs
- src/System.Windows.Forms.Primitives/src/Interop/Imm32/Interop.ImmNotifyIME.cs
- src/System.Windows.Forms.Primitives/src/Interop/Imm32/Interop.ImmReleaseContext.cs
- src/System.Windows.Forms.Primitives/src/Interop/Imm32/Interop.ImmSetConversionStatus.cs
- src/System.Windows.Forms.Primitives/src/Interop/Imm32/Interop.ImmSetOpenStatus.cs
- Use LibraryImport in Interop Imm32.
> Use LibraryImport in Interop Imm32

- src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.ImageList.Add.cs
- src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.ImageList.Create.cs
- src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.ImageList.Destroy.cs
- src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.ImageList.Draw.cs
- src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.ImageList.DrawEx.cs
- src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.ImageList.Duplicate.cs
- src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.ImageList.GetIconSize.cs
- src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.ImageList.GetImageCount.cs
- src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.ImageList.GetImageInfo.cs
- src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.ImageList.Remove.cs
- src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.ImageList.Replace.cs
- src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.ImageList.ReplaceIcon.cs
- src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.ImageList.SetBkColor.cs
- src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.InitCommonControls.cs
- src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.InitCommonControlsEx.cs
- src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TaskDialogIndirect.cs
- Use LibraryImport in some Interop Comctl32.
> Use LibraryImport in some Interop Comctl32

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemInternalLayout.ToolStripLayoutData.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemInternalLayout.cs
- Enable nullability in ToolStripItemInternalLayout.
> Enable nullability in ToolStripItemInternalLayout

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
- src/System.Windows.Forms/src/System/Windows/Forms/GroupBox.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ProgressBar.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DesignBehaviorsTests.cs
- Enable nullability in some Control members.
> Enable nullability in some Control members

- src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewNativeItemCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
Hashtable is rather forgiving, and if a supplied key does not exist in the table, the result is null. Dictionary, however, throws if the key can't be found.
This reverts commit 6da845914ff924e56bbea3271003539730848e0d.
I had to revert NRTA as well, as `this[int]` _can_ result in a null, and additional safe guards will be required.
Closes #7089
/cc: @gpetrou  @dreddy-work
> Revert "Replace hashtable with generic dictionary in ListView (#7029)"

- src/System.Windows.Forms/src/System/Windows/Forms/LisstView.DisposingContext.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewItemCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewNativeItemCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
When `ListView` is disposed, we first "un-host" all managed items by setting `ListView` field to null, then send message to the native control to delete all items.
If edit box is open, native control closes it, as edit box closes, it moves focus to the `ListView`. As a result, when edit box is open and `ListView` control is disposed, `ListView` gets `OnGotFocus` event which results in an attempt to re-create accessible object which leads to an exception. When edit box is closed while the `ListView` is disposed, the focus message is not sent by the native control. Thus, the test is fixed by closing the edit box before the `ListView` control is going out of focus. The real live scenario is fixed by ignoring the focus move if we know that the `ListView` control is being disposed.
``` …
```
> fix Exception on accessing accessible object after control is disposed

- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.WebBrowserAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ControlAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/WebBrowser.WebBrowserAccessibleObjectTests.cs
Partially implements https://github.com/dotnet/winforms/issues/3421
For .Net 7
- Updated "SupportsUiaProviders" flag to WebBrowser
- Added and implemented WebBrowser.WebBrowserAccessibleObject
- Testing application 
[WebBrowserWinFormsApp.zip](https://github.com/dotnet/winforms/files/8919406/WebBrowserWinFormsApp.zip)
ProviderDescription:	"[pid:22832,providerId:0x402AA Main:Nested [pid:27400,providerId:0x402AA Main(parent link):Microsoft: MSAA Proxy (unmanaged:UIAutomationCore.dll)]; Hwnd(parent link):Microsoft: HWND Proxy (unmanaged:uiautomationcore.dll)]"
ProviderDescription:	"[pid:25792,providerId:0x70BA2 Main:Nested [pid:30696,providerId:0x70BA2 Main(parent link):Unidentified Provider (unmanaged:coreclr.dll)]; Hwnd(parent link):Microsoft: HWND Proxy …
> Adding UIA support for WebBrowser

- src/System.Windows.Forms/src/System/Windows/Forms/Form.AccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Form.FormAccessibleObjectTests.cs
Fixes #7245
- Recalculate a nested Form BoundingRectangle location regarding its Parent position on screen.
- Nested Forms have correct BoundingRectangle value
- Yes (since #2096)
- Minimal
- Manual
- CTI
- Unit tests
- Using AI and Inspect. Tested cases when:
- The nested form is placed on the root form
- The nested form is places on a Panel inside the root form
- The nested form has different location coordinated inside the parent control
- 7.0.100-preview.6.22281.2
- Windows 11
> Fixed accessibility BoundingRectangle of nested Forms

- src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
- Replace hashtables with generic dictionaries in ToolTip.
> Replace hashtables with generic dictionaries in ToolTip

- src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.CreateWindowExW.cs
- src/System.Windows.Forms.Primitives/src/System.Windows.Forms.Primitives.csproj
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/ClientUtils.cs
Supressing new CS8981 warning for the Primitives assembly.
We match Win32 casing for intereop.
Moved obsolete warning into code.
> Supress C# keword warning.

- src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
Fixes #7387 
- Use parent's accessible object for notification because RIchTextBox doesn't support UIA providers — its own accessibility object doesn't gets created, and notification is not raised.
- Add missing IsAccessibilityObjectCreated check for TextBoxBase (not directly related to this issue, found while working in this area)
- Narrator announces text of RichTextBox when it's focused. This behavior was present in .NET 6 but missing from .NET 7.
- Yes 
- Minimal
- Unit test
- Manual testing with Narrator
- CTI
* Using Narrator
- .NET 7.0.100-preview.6.22281.2
- Microsoft Windows: 10.0.22000 (Windows 11)
> Fix Narrator not announcing content of RichTextBox

- src/System.Windows.Forms/tests/IntegrationTests/VisualBasicTemplate/VbWinForms.vbproj
Using the below syntax performs a complete replacement of warning codes which should be treated as errors.
```xml
<WarningsAsErrors>aaaaa;bbbbb;ccccc;...</WarningsAsErrors>
```
Instead, the following syntax should be used, which inherits the base list coming from the SDK and augments the list with your desired warning codes.
```xml
<WarningsAsErrors>$(WarningsAsErrors);aaaaa;bbbbb;ccccc;...</WarningsAsErrors>
```
> Exception: If you're intentionally trying to suppress the SDK's base list, please ignore this rule.
> Fix incorrect WarningsAsErrors element

- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ButtonTests.cs
Skip Button_Anchor_ResizeOnWindowSizeWiderAsync test
Related to https://github.com/dotnet/winforms/issues/7297
> Skip Button_Anchor_ResizeOnWindowSizeWiderAsync test

- src/Microsoft.VisualBasic/tests/IntegrationTests/VisualBasicRuntimeTest/VisualBasicRuntimeTest.csproj
- src/System.Windows.Forms/tests/AccessibilityTests/Accessibility_Core_App.csproj
- src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/DemoConsole.csproj
- src/System.Windows.Forms/tests/IntegrationTests/NativeHost.ManagedControl/NativeHost.ManagedControl.csproj
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/WinformsControlsTest.csproj
> Remove NoWarn for nuget warnings because fix for false positives reached VS2022 IntPreview

- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ButtonTests.cs
Skip Button_Anchor_ResizeOnWindowSizeTallerAsync test
Related to #7407
> Skip Button_Anchor_ResizeOnWindowSizeTallerAsync test

- src/System.Windows.Forms/src/System/Windows/Forms/DataObject.BitmapBinder.cs
And simplify some nested ifs.
We save one array allocation (by replacing the static readonly array with the `ReadOnlySpan` property), and code gets shortened.
> Use SequenceEqual instead of a handwritten loop in one case.

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItem.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MenuStripAndCheckedListBox.Designer.cs
Fix #6987.
The problem happens due to the fact that we first show the tooltip, and then show the dropdown, which will overlap the tooltip. In such situations I suggest to refresh the tooltip after dropdown shown.
ToolTip on `MenuStrip` item with dropdown elements will be fully visible.
- No
- minimal.
https://user-images.githubusercontent.com/17767561/179411168-77d2976b-a9fc-4d69-a3e4-53cefa00dced.mp4
https://user-images.githubusercontent.com/17767561/179411173-cbf626ff-bf9b-4572-94c1-8d8f158cef13.mp4
Existing UT.
Manual.
> Fix ToolTip on MenuStrip with dropdown.

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.DataConnection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewDataErrorEventArgs.cs
- Enable nullability in DataGridViewDataErrorEventArgs.
> Enable nullability in DataGridViewDataErrorEventArgs

- src/System.Windows.Forms/tests/TestUtilities/ThreadExceptionFixture.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs
Attempt to investigate DGV flaky tests. https://github.com/dotnet/winforms/issues/6926 https://github.com/dotnet/winforms/issues/6739
Both tests fail due to extra invalidate. To investigate further we need to understand 2 things:
Fails by run №:
11: [Windows_x86-xunit
System.Windows.Forms.Tests.ToolStripItemTests.ToolStripItem_ImageKey_ShouldSerializeValueWithOwnerWithImageList_Success](https://dev.azure.com/dnceng/public/_build/results?buildId=1722813&view=ms.vss-test-web.build-test-results-tab&runId=46748528&resultId=110931&paneView=debug)
27: [Windows_arm64-xunit
System.Windows.Forms.Tests.DataGridViewTests.DataGridView_DefaultCellStyles_Rendering](https://dev.azure.com/dnceng/public/_build/results?buildId=1723543&view=ms.vss-test-web.build-test-results-tab&runId=46761178&resultId=10655 …
> DataGridView flaky tests.

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownButton.ToolStripDropDownButtonInternalLayout.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripLabel.ToolStripLabelLayout.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.ToolStripMenuItemInternalLayout.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitButton .ToolStripSplitButtonButtonLayout.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripStatusLabel.ToolStripStatusLabelLayout.cs
- Enable nullability in classes that inherit from ToolStripItemInternalLayout.
> Enable nullability in classes that inherit from ToolStripItemInternalLayout

- src/System.Windows.Forms.Primitives/src/Interop/UiaCore/Interop.UIA.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Form.AccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Form.FormAccessibleObjectTests.cs
Fixes #2907
- Added new  UIAutomation PropertyId IsDialogPropertyId.
- Set IsDialogPropertyId in FormAccessibleObject.GetPropertyValue(UiaCore.UIA propertyID)
- The form will programmatically be exposed as a dialog, which is the correct match for its semantics. 
- No
- Minimal
- Manually tested the change in a winforms app
- Unit tests 
- Used Inspect
> Setting UIA_IsDialogPropertyId correctly when Form.ShowDialog() was called

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/LayoutEventArgs.cs
- Enable nullability in some Control members and LayoutEventArgs.
> Enable nullability in some Control members and LayoutEventArgs

- src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
Fixes #6708
- Processed all unique groups of selected items through collapse. The collapse state had been validated in cycle and correct group(s) triggered for GroupCollapsedStateChanged.
- ListView.GroupCollapsedStateChanged event works correctly in case of multiple groups selection.
- No
- Minimal
- Manually tested the change in a winforms app
- Windows 11
> Fixing incorrect selection of ListViewGroup for ListView.GroupCollapsedStateChanged event (#6708)

- src/System.Windows.Forms.Analyzers.CSharp/src/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilder.cs
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.GenerateInitialize_DefaultFont=SansSerif.verified.txt
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.GenerateInitialize_DefaultFont=Tahoma.verified.txt
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.GenerateInitialize_DefaultFont=default.verified.txt
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.GenerateInitialize_DefaultFont=null.verified.txt
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.GenerateInitialize_EnableVisualStyles=false.verified.txt
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.GenerateInitialize_EnableVisualStyles=true.verified.txt
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.GenerateInitialize_UseCompTextRendering=false.verified.txt
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.GenerateInitialize_UseCompTextRendering=true.verified.txt
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/MockData/ApplicationConfigurationGeneratorTests.GenerateInitialize_default_boilerplate.cs
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/MockData/ApplicationConfigurationGeneratorTests.GenerateInitialize_default_top_level.cs
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/MockData/ApplicationConfigurationGeneratorTests.GenerateInitialize_user_settings_boilerplate.cs
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/MockData/ApplicationConfigurationGeneratorTests.GenerateInitialize_user_top_level.cs
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/MockData/ApplicationConfigurationInitializeBuilderTests.default_boilerplate.cs
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/MockData/ApplicationConfigurationInitializeBuilderTests.default_top_level.cs
Fixes #7346
- Added full qualifier to ApplicationConfiguration generated code by creating a type string variable named 'qualifier' which is equaled to the full qualifier and then adding it to the controls.
-  Changed expected result in test file by adding the full qualifier.
``` C#
static string GenerateCode(ApplicationConfig projectConfig, string? defaultFont, string indent)
{
StringBuilder code = new();
string qualifier = "global::System.Windows.Forms.Application.";
if (projectConfig.EnableVisualStyles)
{
code.AppendLine($"{indent}{qualifier}EnableVisualStyles();");
}
code.AppendLine($"{indent}{qualifier}SetCompatibleTextRenderingDefault({projectConfig.UseCompatibleTextRendering.ToString().ToLowerInvariant()});");
code.AppendLine($"{indent}{qualifier}SetHighDpiMode(HighDpiMode.{projectCo …
```
> Fully qualify code in `ApplicationConfiguration.Initialize`

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlTabOrderComparer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlTabOrderHolder.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/AttributeTypeSorter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/SplitContainer.cs
- Enable nullability in some Control members, ControlTabOrderHolder and ControlTabOrderComparer.
> Enable nullability in some Control members, ControlTabOrderHolder and ControlTabOrderComparer

- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.ToolStripPanelAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripPanel.ToolStripPanelAccessibleObjectTests.cs
Partially implements #3421
- Updated "SupportsUiaProviders" flag to ToolStripPanel
- Added and implemented ToolStripPanel.ToolStripPanelAccessibleObject
- Improving development experience for ToolStripPanel control accessibility.
- No
- Minimal
- Manually
- Unit testing
- Inspect
> Adding supports of UIA provider for ToolStripPanel

- src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
Fixes #4883
- The TreeView will respect the DoubleBuffered property.
- Double buffering can be enabled in a derived class without needing to use P/Invoke.
- No
Probably minimal.
- Manually tested the change in a winforms app
- 7.0.100-preview.5.22307.18 (x64)
> Make the TreeView respect the DoubleBuffered property

- src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHGSI.cs
- src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHGetStockIconInfo .cs
- src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHSTOCKICONID.cs
- src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHSTOCKICONINFO.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs
Fixes #7390
- ErrorProvider will attempt to get the default error icon from the operating system.
- The error icon should now match the one used by the MessageBox/TaskDialog.
- No
- Minimal
- Manually tested the change in a winforms app
- 7.0.100-preview.5.22307.18 (x64 and x86)
> Attempt to get the default error icon from the OS

- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ColumnHeader.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.ColumnHeaderCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemDetailsAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemListAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItemCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ColumnHeader.ListViewColumnHeaderAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemDetailsAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObjectTests.cs
Fixes #7385
- Add a call of `UiaDisconnectProvider` for `ListView` elements (items, subitems, groups, column headers) for cases when:
- `ListView` is destroyed
- Collection is cleared
- Element is removed from a collection
- Element is replaced in a collection (where applicable)
- Change `RuntimeId` of some accessible objects to be independent from its index in a collection. When collection is modified, e.g. some elements are removed or inserted at the beginning, indexes (and therefore `RuntimeId`s) of elements change. It then leads to a possible disconnection of wrong items, which had the index initially.
- Less memory leaks for `ListView`
- No
- Minimal
- CTI
- Unit tests — we don't always add unit tests for memory leaks fixes, but here I wanted to make sure that …
> Fix ListView memory leaks

- src/System.Windows.Forms/src/System/Windows/Forms/DragDropFormat.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DragDropFormatTests.cs
There is an over release in `DragDropFormatTests.cs`. The main issue is the `DragDropFormat` class has a "copy" semantic that is default in all tests. Since there are no copies being made, ownership of the passed in artifacts is implied so calling [`DragDropFormat.Dispose()`](https://github.com/dotnet/winforms/blob/de1f12d7404f627539ab81cc98a054a12d8020aa/src/System.Windows.Forms/src/System/Windows/Forms/DragDropFormat.cs#L115-L130) means they will be released then and there is no need to call `Ole32.ReleaseStgMedium()` as well.
https://github.com/dotnet/winforms/blob/de1f12d7404f627539ab81cc98a054a12d8020aa/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DragDropFormatTests.cs#L63
https://github.com/dotnet/winforms/blob/de1f12d7404f627539ab81cc98a054a12d8020aa/src/System.Win …
> Address over release in DragDropFormat tests

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObjectTests.cs
This is continue of PR #7412.
The test check case, described in Issue #6708.
- Add a unit test, that check the case of collapsing of the second ListView group, when several group items are selected.
- .NET 7.0.0-rc.1.22371.7
- Windows 11
> Adding a unit test to check ListView.GroupCollapsedStateChanged event work

- src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeCollection.cs
Fixes #7504
Use `Remove` and `Insert` methods to correctly replace `TreeNode` in a `TreeNodeCollection`. It will still execute the same code as before but with a few additional important methods.
- Calling `Remove` sends missing `TVM.DELETEITEM` message for the replaced node which fixes appending blank space.
- Additionally, `Remove` method disposes Keyboard ToolTip for the node. `Insert` hooks it to the new tree node and its children, which also fixes not working keyboard tooltip after replacement.
- Memory leak of replaced node's accessible object will be fixed with https://github.com/dotnet/winforms/pull/7296 which adds a `UiaDisconnectProvider` call in `Remove` method.
- This is also how it's implemented for setter by index in `ListViewNativeItemCollection` and …
> Fix replacing TreeNode by index in TreeView

- src/System.Windows.Forms/src/Resources/SR.resx
- src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
Fixes https://github.com/dotnet/winforms/issues/6656
Finishes PR https://github.com/dotnet/winforms/pull/6737
- The problem is being reproduced due to competitive requests to Narrator. Periodically it announces expanded state information and periodically skips.
- A possible fix is to replace the standard method RaiseAutomationPropertyChangedEvent with the InternalRaiseAutomationNotification (RaiseAutomationNotification) method. In this case, we force the expanded state information to be announced, which helps avoid a possible contention problem.
- Unit test **PropertyGridView_GridEntry_AccessibleObject_GetsNotification**
- Yes (we have unstable behavior)
- Minimal
- CTI team
- Manually
- Unit test
- Narrator
- JAWS
- NVDA
Microsoft Windows [Version 120.2212.4170.0]
.NET Core SDK: …
> Fixing issue with announcing of PropertyGrid expanded state

- src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObject.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObjectTests.cs
Fixes #3261
- Raised a notificatoin contained a subtitle values on setting focus.
- Added check for focus state in SetState method.
- Added unit test.
- User can hear a subtitle of ListViewGroup.
- No
- Minimal
- Manually
- Narrator
- Unit test
- Narrator
> Adding notification to Narrator about a subtitle.

- src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Follow-up for #7385 (see https://github.com/dotnet/winforms/pull/7478#discussion_r934996360)
Accessing DefaultGroup forces its creation, so we need to make sure it exists before releasing to prevent unwanted creation.
- Add not null check for `DefaultGroup` before releasing its provider
- Unnecessary `DefaultGroup` object is not created for ListViews without groups when ListView releases its UIA provider
- No
- Minimal
- Unit testing
- Manual
- .NET 7.0.100-rc.1.22368.24
- Windows 11
> Add not null check for ListView's DefaultGroup before releasing its UIA provider

- src/System.Windows.Forms/src/System/Windows/Forms/ListBox.AccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ObjectCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxAccessibleObjectTests.cs
Fixes #7197.
- Add call to `UiaDisconnectProvider` for `ListBoxItemAccessibleObject`s for cases when:
- `ListBox` is destroyed (now it only releases provider for `ListBoxAccessibleObject`)
- All items are cleared from `ListBox`
- An item is removed from `ListBox`
- Add unit tests for above scenarios
- `ListBoxItemAccessibleObject`s memory will stop leaking 
- No
- Minimal
After executing steps from issue description for ListBox with 18 items:
After `ListBox.Items.Clear()`:
One `ListBoxItemAccessibleObject` instance may be held by `ListBox._focusedItem` field, which doesn't create a memory leak, because the AO was disconnected from UIA provider and will be garbage-collected normally once form is closed.
After  `ListBox.Items.RemoveAt(0)` 5 times:
- Unit testing
- Manual testing with WinDbg …
> Fix ListBox items accessible objects memory leak 

- src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNode.TreeNodeAccessibleObjectTests.cs
Fixes #7196
- Add call to `UiaDisconnectProvider` for `TreeNodeAccessibleObject`s for cases when:
- `TreeView` is destroyed (now it only releases `TreeViewAccessibleObject`)
- All nodes are cleared from `TreeView`
- A node is removed from `TreeView`
- Add unit tests for above scenarios
- `TreeNodeAccessibleObject` memory will stop leaking 
- No
- Minimal
After executing steps from issue description for `TreeView` with 16 nodes:
Ideally there should be 0 objects, but two empty `TreeNode[]` are still left. I tried to find the cause of it but couldn't quickly do so. It would also be present even without using accessibility tools, therefore out of scope of this task. Considering it has a very small footprint, I don't think we should raise a separate issue for it.
After …
> Fix TreeNode accessible objects memory leak

- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Automation/UiaTextProvider.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Automation/UiaTextRange.cs
- src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/Automation/UiaTextRangeTests.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxUiaTextProvider.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseUiaTextProvider.cs
- src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/MainFormControlsTabOrder.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/TextBoxes.Designer.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/TextBoxes.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/TextBoxes.resx
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextBoxBase.TextBoxBaseUiaTextProviderTests.cs
Fixes #6661
- Rework `GetMultilineBoundingRectangles` method to:
+ calculate correct rectangles
+ make it simpler
- Now a user can see more correct text ranges in a muliline TextBox
- No
- Minimal
- TextPattern doesn't show empty lines;
- In RTL mode some text ranges are not shown:
- UIA shows all text ranges correctly:
- CTI
- Unit tests
- Using Narrator and Isnpect
- Windows 10
- .NET 7.0.0-preview.2.22108.17
> Fixing text pattern of a multiline text box

- src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.SetWinEventHook.cs
- src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.UnhookWinEvent.cs
- src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.WINEVENT.cs
- src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.WINEVENTPROC.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewLabelEditAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewLabelEditNativeWindow.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewLabelEditUiaTextProvider.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewLabelEditAccessibleObjectTests.cs
Fixes #4810. Implements an accessible object for label edit control in ListView. This object now is the last child of the ListView (the same behavior as in the Windows Explorer). The object now also has a non-empty name according to its value (Windows Explorer behavior). The original object wasn't producing automation events related to the text, it was done by the UIAutomationCore proxy -- this was also implemented along with the text pattern support for the new accessible object, so the Narrator announces its text correctly.
- Implemented native window wrapper and accessible object for label edit control in ListView
- Implemented text pattern provider for label edit control (and added triggering automation events about label edit text)
- Made label edit accessible object be the last …
> Improving accessible object for label edit in ListView

- src/System.Windows.Forms/src/System/Windows/Forms/ListViewLabelEditUiaTextProvider.cs
The last merged PR wasn't completely rebased on the latest main -  a class didn't implement an updated interface method.
> fixing a build break

- src/System.Windows.Forms.Primitives/src/Interop/IHandle.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.BitBlt.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetAncestor.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetClientRect.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetParent.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetSystemMenu.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetWindow.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetWindowRect.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.IsChild.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.IsWindow.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.IsWindowVisible.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.MapWindowPoints.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.PostMessage.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.SetActiveWindow.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.SetFocus.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.SetParent.cs
- src/System.Windows.Forms/src/GlobalUsings.cs
- src/System.Windows.Forms/src/System/Windows/Forms/CachedItemHdcInfo.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
With an explicit `IHandle<T>.Wrapper` we can avoid boxing when `IHandle<T>` is implmented on a struct and passing `IHandle<T>` to `GC.KeepAlive()`.
> Make wrapper explicit on IHandle<T>

- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObjectTests.cs
Fixes #4690 (Common Case 1)
- Changed ListViewItemBaseAccessibleObject: added announcement by Narrator the same way as in TreeView
- Added the unit test ListViewItemBaseAccessibleObject_IsCheckable_IfListViewHasCheckBoxes
- Narrator announces ListViewItem with checkbox as either selected or not selected
- No
- Minimal
- CTI
- Manually
- Using Inspect and Narrator
.NET 7.0 Preview 6
Windows 10
> Adding the ListViewItem CheckBox check announcement

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs
Skip DataGridView_RowHeadersWidth_SetWithHandle_GetReturnsExpected test
Related to https://github.com/dotnet/winforms/issues/6739
> Skip DataGridView_RowHeadersWidth_SetWithHandle_GetReturnsExpected test

- src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TabPage.TabAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPage.TabAccessibleObjectTests.cs
Fixes #7415 
- Changed TabPage class
- Changed TabCollection class
- Changed TabPageAccessibleObject class
Unit tests affected:
- TabPage_TabAccessibleObjectTests.TabAccessibleObject_RuntimeId_ReturnsExpected (test changed)
- added a new unit test TabAccessibilityObject_IsDisconnected_WhenTabPageReleasesUiaProvider which checks for _tabAccessibilityObject to be disconnected.
- Less memory leaks of TabPage 
- No
- Minimal
- CTI
- .NET 7.0 Preview 5
- Windows 10
> Fixing TabPage memory leaks

- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildNativeWindow.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ObjectCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxChildNativeWindowTests.cs
Fixes #7318
Has the similar approach like in PR #7284
⚠️Doesn't fix memory leaks of TextPattern. It will be fixed as another fix for TextBox as well.
- Add a call of `UiaDisconnectProvider` for `ComboBox` elements (its List, TextBox, Label) and ComboBoxItemAccessibleObjects for cases when:
- ComboBox is destroyed
- All items are cleared from a ComboBox
- An item is removed from a ComboBox
- Using TextPattern explorer of Inspect
- Less memory leaks of ComboBox
- No
- Minimal
- There are some kept object in the memory after disposing a ComboBox:
- These are no ComboBox elements or items objects in the memory after disposing (without TextPattern):
- CTI
- Using AI, Inspect, Narrator for cases:
- Dispose a ComboBox
- Close a form with a ComboBox (works same as …
> Fixing memory leaks of ComboBox elements and items accessible objects

- src/System.Windows.Forms/tests/TestUtilities/KeyboardSimulator.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Fixes #7506
- Added KeyboardHelper class in System.Windows.Forms.TestUtilities project.
- Used this class instead of copy-pasted code in unit tests.
- It's a technical refactoring.
- No
- Minimal
- Unit tests
> Moving common logic of keyboard's simulation into the helper class.

- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
- src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarBodyAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarRowAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.MonthCalendarAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
Fixes #7567
- Added Properties.SetObject(s_accessibilityProperty, null); in Control.ReleaseUiaProvider(IntPtr handle).
- Less memory leaks
- No
-
- CTI
- Unit tests
- Manual
- NET 7.0 Preview 5
- Windows 10
> Change ReleaseUiaProvider method to set Accessibility object to null

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownMenu.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemTests.cs
Fixes #7375
- Changed ToolStrip class
- Changed ToolStripItem and ToolStripDropDownItem classes
- Less memory leaks of ToolStrip
- No
- Minimal
- CTI
- .NET 7.0 Preview 5
- Windows 10
> Fixing of ToolStrip elements accessible objects

- src/System.Windows.Forms.Primitives/src/Interop/UiaCore/Interop.UiaDisconnectProvider.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ColumnHeader.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListBox.AccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemDetailsAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewLabelEditNativeWindow.cs
- src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarBodyAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarRowAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.MonthCalendarAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
- src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolTipTests.cs
Fixes #7357
- Keep argument and result checks inside a static separate method. It allows to simplify using of `UiaDisconnectProvider`
- No
- No
- Minimal
- CTI
- Using Narrator/Inspect/AI and WinDbg
- .NET 7.0 Preview 6
- Windows 11
> Refactoring of `UiaDisconnectProvider` usage implementation

- docs/list-of-diagnostics.md
- src/System.Windows.Forms.Analyzers.CSharp/ApplicationConfigurationGenerator.Help.md
- src/System.Windows.Forms.Analyzers.CSharp/src/System.Windows.Forms.Analyzers.CSharp.csproj
- src/System.Windows.Forms.Analyzers/AppManifestAnalyzer.Help.md
- src/System.Windows.Forms.Analyzers/src/System.Windows.Forms.Analyzers.csproj
> Add analyzer diagnostics docs

- eng/Versions.props
This change is an addendum to commit: https://github.com/dotnet/winforms/pull/7571
Roslyn team has provided newer version of Microsoft.CodeAnalysis.*.Testing.XUnit packages which consume newer version of Newtonsoft.Json v13.0.1.
> Updating Microsoft.CodeAnalysis.*.Testing.XUnit Packages version

- src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/KeysConverterTests.cs
Fixes #7610
- Add test for regression.
- Use `TryGetValue` and `Enum.Parse` instead of Dictionary indexer. The changes resemble the state of the code before #6448.
- `new KeysConverter().ConvertFrom("Ctrl + N")` throws KeyNotFoundException.
- Yes
- Low
- Added test
> Fix KeyNotFoundException in KeysConverter.ConvertFrom

- pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config/template.json
- pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-CSharp/.template.config/template.json
- pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/.template.config/template.json
In the templates, the generators which determine minimum language version in use were not considering C#11. 
Fixed regex to support it.
Without this fix, using C# 11.0 via `--langVersion` option will result in old style template (no top level statements, file scoped namespaces, implicit usings)
Automated
Very low. 
Language version option is only available in CLI and not exposed in Visual Studio.
> added support of C#11 to templates

- azure-pipelines-richnav.yml
- azure-pipelines.yml
- eng/pipelines/build.yml
Fixes #
- 
- 
- 
- 
- 
- Yes / No
-
- 
- 
- 
-
> Move to -Svc pool provider in release branches

- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DragDropTests.cs
Fixes #7547 
- Fix the intermittent test failure by performing the whole operation in one async method, rather than three.
- Don't assert the cursor location since that isn't the intent of the test, and the location is expected to change.
- Alleviates the intermittent test failure.
- I see that this test failed in CI on 8/11/2022.
- Minimal.
- Ran unit and integration tests.
- 7.0.0-preview.1.22076.8
> Fixing DragDropTests intermittent test failure

- Directory.Build.targets
Prepare branch for release.
This change was tested on https://dev.azure.com/dnceng/internal/_git/dotnet-winforms?version=GB7.0.0-test, in the .NET 7 stable test build
> Set Targeting Ref pack version to MicrosoftNETCoreAppRuntimewinx64PackageVersion

- eng/Versions.props
This reverts commit 14292089e35cb1fdf484ee80b2804793596a53bd.
Compiler version was pinned until we get the updated version from Arcade. Until this happens, this change will not build.
> Revert "update CSC version to  4.4.0-1.22358.14"

- src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarBodyAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarRowAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.MonthCalendarAccessibleObject.cs
Fixes https://github.com/dotnet/winforms/issues/7714
.NET 8.0 PR #7738
The reason of the bug was calling RebuildAccessibilityTree 2 times at the same time via CalendarViewChanged and DisplayRangeChanged events.
Removed CalendarViewChanged event using because it duplicates the work of DisplayRangeChanged and leads to the exception. We release elements the first rebuilding time and catch the exception while the second call.
- The regression breaks accessibility work of `MonthCalendar` in .NET 7.0 only after [#7362](https://github.com/dotnet/winforms/pull/7362) and [#7569](https://github.com/dotnet/winforms/pull/7569)
- Remove extra `CalendarViewChanged` usage
- Remove extra cleaning methods that duplicate disconnection methods work
- There is no the exception while using Narrator with …
> [Servicing] Fixing "Collection was modified ..." exception while MonthCalendar AO tree rebuilding

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.AccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewAccessibleObjectTests.cs
Fixes #7723
- Restored condition as suggested (https://github.com/dotnet/winforms/pull/6102/files#r851568124)
- Fixed unit tests 
- The Narrator has correct focus on non-empty DGV.
- Yes
- Minimal
_Not modal window._
_Modal window._
_Not modal window._
_Modal window._
- Manually.
- Narrator.
- Unit testing.
- Narrator.
- 8.0.100-alpha.1.22423.9
In modal window announces the content of the dialog up to the focused control. (https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-automation-element-propids, see UIA_IsDialogPropertyId)
> Fixed HasKeyboardFocusProperty for DGV's AO

- src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarBodyAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarRowAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.MonthCalendarAccessibleObject.cs
Fixes #7714
Port to .NET 7.0 is PR #7739
The reason of the bug was calling `RebuildAccessibilityTree` 2 times at the same time via `CalendarViewChanged` and `DisplayRangeChanged` events.
Removed `CalendarViewChanged` event using because it duplicates the work of `DisplayRangeChanged` and leads to the exception. We release elements the first rebuilding time and catch the exception while the second call.
- Remove extra `CalendarViewChanged` usage
- Remove extra cleaning methods that duplicate disconnection methods work
- There is no the exception while using Narrator with MonthCalendar
- Yes ([#7362](https://github.com/dotnet/winforms/pull/7362) and [#7569](https://github.com/dotnet/winforms/pull/7569) exposed the problem in [#4758](https://github.com/dotnet/winforms/pull/4758))
- Minimal
- …
> Fixing "Collection was modified ..." exception while MonthCalendar AO tree rebuilding

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DataGridViewTests.cs
Fixes #7552
The bug was a regression from PR #1681, where `GetToolTipText` was used incorrectly for mouse tooltips.
- Use the old method implementation of getting text for mouse toolTips. `GetToolTipText` was used previously, but #1681 changed this method name to `GetInternalToolTipText`. The current `GetToolTipText` is used to get keyboard toolTip text.
- User doesn't see extra unexpected mouse toolTips
- Yes (since #1681)
- Minimal
- Mouse tooltips appear for all cells after any cell in row was selected
- Mouse tooltips work in accordance with [docs](https://docs.microsoft.com/ru-ru/dotnet/api/system.windows.forms.datagridview.showcelltooltips?view=windowsdesktop-6.0) (are shown for truncated cells)
- Manual
- UI tests
- CTI
- .NET 8.0
- Windows 11
> Fixing DataGridView mouse toolTips regression

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.ToolStripTextBoxControl.cs
Fixes #7740
- Changed the border's color for `ToolStripTextBoxControl` for HC.
- A `TextBox` inside `MenuStrip` will be looked clear.
- No
- Minimal
- Manually
- AI
- HC
.NET SDK: 
Version:   8.0.100-alpha.1.22423.9
OS Version:  10.0.22000
> Fixing the border's color of TextBox inside MenuStrip

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripButton.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripButtonTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
Fixes #7601 
- Disabled the `CanSelect` property of a `ToolStripItem` when the `Enabled` property is `false`.
- Narrator won't announce disabled items from a `ToolStrip`.
- No
- Minimal
- Manually
- Narrator
- Narrator
- 7.0.100-preview.7.22377.5
> Skipping disabled items from ToolStrip.

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DataGridViewTest.Designer.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/app.manifest
Fixes #1953
- Used correct colors to Text when HC is on.
- Improved test application to check ComboBox with values and Button inside DGV.
- Text inside DGV controls looks like same controls outside. They become more clear.
- No
- Minimal
- Manual using HC theme
- High contrast
- 7.0.100-preview.7.22377.5
> Fixing text's color of DataGridViewComboBoxCell and DataGridViewTextBoxCell

- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildEditUiaProvider.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildListUiaProvider.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripControlHost.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItem.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripControlHost.ToolStripControlHostAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripDropDownItemAccessibleObjectTests.cs
Fixes #7713 
- Added a condition to access `AccessibleObject` via `FragmentNavigate` for `ComboBoxChildEditUiaProvider` and `ComboBoxChildListUiaProvider` if an owning `ComboBox` wasn't created.
- Released `Grip` and `OverflowButton` with `ToolStrip` releasing.
- Released `Control` with `ToolStripControlHost` releasing.
- Released `DropDown` with `ToolStripDropDownItem` releasing.
- No memory leaks from `ToolStrip`.
- No
- Minimal
- Manually
- WinDbg
- Inspect
- 8.0.0-alpha.1.22464.17
> Released AccessibleObjects of ToolStripItems

- src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MaskedTextBox.MaskedTextBoxAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextBoxAccessibleObjectTests.cs
Fixes #7816.
IsPassword property determines whether keystrokes should be read out by screen reader as the user types them.
This is a regression from https://github.com/dotnet/winforms/pull/6640, which sets `IsPassword` as false for every control. Before it, `IsPassword` was `null` for `TextBoxBaseAccessibleObject` and therefore its value was taken from MSAA provider.
- Use `TextBoxBase.PasswordProtect` to determine `IsPassword` property value
- When `TextBox` is configured as password input, screen readers will not announce keystrokes as the user types them, because it may expose private information.
- Yes
- Minimal
`IsPassword` value is `False` for `TextBox` with `UseSystemPasswordChar = true`:
Narrator Buddy output as "qwerty" is entered into the `TextBox`:
> edit, 
> <say-as …
> Set IsPassword property for TextBoxBaseAccessibleObject

- src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MaskedTextBox.MaskedTextBoxAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextBoxAccessibleObjectTests.cs
Fixes #7816.
.NET 8.0 PR: #7825
IsPassword property determines whether keystrokes should be read out by screen reader as the user types them.
This is a regression from https://github.com/dotnet/winforms/pull/6640, which sets `IsPassword` as false for every control. Before it, `IsPassword` was `null` for `TextBoxBaseAccessibleObject` and therefore its value was taken from MSAA provider.
- This regression makes screen readers announce content entered into TextBoxes configured for password input, which may expose sensitive information for screen reader users.
- Use `TextBoxBase.PasswordProtect` to determine `IsPassword` property value
- When `TextBox` is configured as password input, screen readers will not announce keystrokes as the user types them, because it may expose private …
> [release/7.0] Set IsPassword property for TextBoxBaseAccessibleObject

- src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemDetailsAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemImageAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemImageAccessibleObjectTests.cs
Fixes #4690 Details.Case 2
- Added ListViewItemImageAccessibleObject
- Used AO for image inside ListViewItemDetailsAccessibleObject
- User can see information about ListViewItem's image via accessibility tools
- No
- Minimal
- Manually
- Unit tests
- AI
- AI
- 7.0.100-preview.7.22377.5
> Adding AccessibleObject for ListViewItem's image

- src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.Vista.cs
Fixes #7850
Expected input for FileDialog filter is in format : "filterName1|filterSpec1|filterName2|filterSpec2|filterName3|filterSpec3....etc". When processing the filter, we split it with separator "|" into an array and we were mismatching filter name/spec pairs, e.g. we were grabbing filterSpec2 and filterName3, leading to IndexOutOfRangeException once getting to the end of the array.
- Yes, regressed in [#7674](https://github.com/dotnet/winforms/pull/7674)
- Minimal
Received IndexOutOfRangeException whenever 
FileDialog opens as expected
> Fix IndexOutOfRangeException When Opening FileDialog with Filters

- src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/Com2IPerPropertyBrowsingHandler.Com2IPerPropertyBrowsingEnum.cs
- Enable nullability in Com2IPerPropertyBrowsingEnum.
> Enable nullability in Com2IPerPropertyBrowsingEnum

- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DragDropTests.cs
Fixes #7875 
- Add UI tests which drag and drop serialized and non-serialized data to the application.
- I've written 2 tests covering both the serialized and non-serialized scenarios, with the serialized case working as expected, and the non-serialized case failing, as reported by the customer.
- Initial results show that the fix in https://github.com/dotnet/winforms/pull/7869 alleviates the issue described in https://github.com/dotnet/winforms/issues/7864.
- Supports the work being done in #5163 
- Regression test for #7864 
- Yes
- Minimal
- Ran unit and integration tests.
- .NET 7 RC1
> Add serialized and non-serialized object drag and drop UI tests

- src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.DoDragDrop.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DragDropTests.cs
Port #7869 and #7876 
Fixes #7864
Revert ComWrapper usage to allow managed types to cycle through drag and drop.
Without this change, drag and drop does not work in many (most?) customer applications.
- Yes
- Low.
> Port fix for IDataObject.GetData with non-serializable type returns null

- src/System.Windows.Forms.Design/src/System/Drawing/Design/ContentAlignmentEditor.ContentUI.cs
- src/System.Windows.Forms.Design/src/System/Drawing/Design/SelectionPanelBase.cs
- src/System.Windows.Forms.Design/src/System/Drawing/SelectionPanelBase.SelectionPanelRadioButton.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DockEditor.DockUI.cs
Fixes #7800 
- Refactored `ContentAlignmentEditor.ContentUI` and `DockEditor.DockUI`.
- Moved common logic to `SelectionPanelBase`.
- Reworked `ContentAlignmentEditor.ContentUI`, currently it works in the same way as `DockEditor.DockUI`.
- Narrator announcements will be more transparent for users.
- No
- Minimal
> ImageAlign, 10 of 20, expanded, 
> Expanded
> Alignment Picker, Middle Center, radio button, selected, 
> Middle Center, radio button, non-selected, 
> Middle Right, radio button, selected, 
> Middle Right, radio button, non-selected, 
> Bottom Left, radio button, selected, 
> Bottom Left, radio button, non-selected, 
> Bottom Middle, radio button, selected, 
> Bottom Middle, radio button, non-selected, 
> Bottom Right, radio button, selected, 
> Bottom Right, radio button, …
> Refactored ContentAlignmentEditor. It should work as DockEditor

- eng/ApiCompatibility/PublicApiAnalyzer.targets
- eng/CodeAnalysis.src.globalconfig
- eng/CodeAnalysis.test.globalconfig
- eng/CodeStyle.targets
- eng/Versions.props
- src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.WinFormsAppContext.vb
- src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/ComputerInfo.vb
- src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Network.vb
- src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Helpers/NativeTypes.vb
- src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Logging/FileLogTraceListener.vb
- src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/MyServices/Internal/ProgressDialog.vb
- src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/MyServices/Internal/WebClientCopy.vb
- src/System.Windows.Forms.Design/src/System/Drawing/Design/ContentAlignmentEditor.ContentUI.cs
- src/System.Windows.Forms.PrivateSourceGenerators/src/System/Windows/Forms/SourceGenerators/EnumValidationInfo.cs
- src/System.Windows.Forms.PrivateSourceGenerators/src/System/Windows/Forms/SourceGenerators/SyntaxReceiver.cs
Fixes #7879
Singular warning for CA1812 supressed due to usage in interop.
Synced globalconfig with runtime and added #TODO to items that were warning.
```
Line  182: dotnet_diagnostic.CA1416.severity = none # TODO: warning
Line  260: dotnet_diagnostic.CA1727.severity = suggestion # TODO: warning
Line  273: dotnet_diagnostic.CA1810.severity = none # TODO: warning
Line  297: dotnet_diagnostic.CA1821.severity = none # TODO: warning
Line  394: dotnet_diagnostic.CA1853.severity =  none # TODO: warning
Line  397: dotnet_diagnostic.CA1854.severity =  none # TODO: warning
Line  406: dotnet_diagnostic.CA2007.severity = none # TODO: warning
Line  439: dotnet_diagnostic.CA2019.severity = none # TODO: warning
Line  466: dotnet_diagnostic.CA2208.severity = none # TODO: warning
Line  533: …
```
> Enable CA1852/CA1812 Analyzers

- Restore.cmd
- build.cmd
- global.json
This is a fix for the build errors, e.g.:
> Use native tools present on the machine rather than bootstraped tools in CI build

- eng/CodeAnalysis.src.globalconfig
- eng/CodeAnalysis.test.globalconfig
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxContainer.cs
Fix CA1853: Unnecessary call to 'Dictionary.ContainsKey(key)'
Enables analyzers that don't cause build failures that were tagged with TODO.
Related: #7887
> Enabling analyzers that don't cause build failures and fix CA1853

- eng/Versions.props
- src/System.Windows.Forms.Primitives/src/System.Windows.Forms.Primitives.csproj
- src/System.Windows.Forms.Primitives/src/Windows/Win32/Graphics/Gdi/LOGFONTW.cs
- src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/EmfRecord.cs
- src/System.Windows.Forms/src/System.Windows.Forms.csproj
As well as fixups and upgrade `System.Runtime.CompilerServices.Unsafe` to version Cswin32 is using
> Upgrade Cswin32 Version

- src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.IDropSourceNotifyVtbl.cs
- src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.IDropSourceVtbl.cs
- src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.IEnumFORMATETCVtbl.cs
- src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.IEnumStringVtbl.cs
- src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.IFileDialogEventsVtbl.cs
- src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.IStreamVtbl.cs
- src/System.Windows.Forms.Primitives/src/NativeMethods.txt
- src/System.Windows.Forms.Primitives/src/System.Windows.Forms.Primitives.csproj
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/FileDialogCustomPlacesCollection.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/Foundation/HRESULT.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/System/Com/FORMATETC.cs
- src/System.Windows.Forms/src/GlobalUsings.cs
- src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.VistaDialogEvents.cs
- Convert `IStreamVtbl`,`IFileDialogEventsVtbl`,`IEnumStringVtbl`,`IEnumFORMATETCVtble`,
`IDropSourceVtbl`,`IDropSourceNotifyVtbl`
- Add implicit operators for `Exception` > `HRESULT` and  `ComType.FORMATETC` > `FORMATETC`
> Start Converting Com Vtbls to Cswin32

- eng/CodeAnalysis.src.globalconfig
- src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CollectionCodeDomSerializer.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/TypeCodeDomSerializer.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/Behavior.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DragAssistanceManager.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/ResizeBehavior.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CommandSet.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ComponentTray.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlCommandSet.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TextBoxBaseDesigner.cs
- src/System.Windows.Forms/src/System/Windows/Forms/BindingSource.cs
- src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Layout/FlowLayout.cs
- src/System.Windows.Forms/src/System/Windows/Forms/NumericUpDown.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.GridEntryAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Enables IDE0100 Remove redundant equality
Related: #7887
> Enable IDE0100 Remove redundant equality

- eng/CodeAnalysis.src.globalconfig
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CommandSet.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/EventHandlerService.cs
Enables IDE0200 (remove unnecessary lambda expression).
Related #7887
> Enable IDE0200 (remove unnecessary lambda expression)

- eng/actions/backport/index.js
Clarify the error message on backport github action
None - purely internal engineering change
- No
- Minimal
Backport GHA can fail for contributers without publicly visible membership within the org owning the repo. Current error message is missleading (by hardcoding the org to 'microsoft').
Thanks to @dreddy-work for helping to investigate this case!
> Adjust error message on backport GHA

- src/System.Windows.Forms.Design/src/System/Drawing/Design/ContentAlignmentEditor.ContentUI.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DockEditor.DockUI.cs
Fixes #7830 
- Added `Name` to buttons in `DockUI` and `ContentUI`.
- The `AutomationId` property will be filled.
- No
- Minimal
_ContentUI_
_DockUI_
_ContentUI_
_DockUI_
- Manually
- Inspect
- Inspect
.NET SDK:
Version:   8.0.100-alpha.1.22423.9
Commit:    b9635390c8
> Fixing the AutomationId property for AccessibleObject of options in ContentUI and DockUI forms

- eng/CodeAnalysis.src.globalconfig
- src/System.Windows.Forms.Design/src/System/Resources/Tools/StronglyTypedResourceBuilder.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
Enable SA1001 analyzer.
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1001.md
Used solution wide code fix.
Related: #7887
> SA1001 Commas should not be preceded by whitespace

- eng/CodeAnalysis.src.globalconfig
- src/System.Windows.Forms.Design/src/System/Drawing/Design/ContentAlignmentEditor.ContentUI.cs
- src/System.Windows.Forms.Design/src/System/Drawing/Design/SelectionPanelBase.cs
- src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.IEnumFORMATETCVtbl.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/Graphics/Gdi/FW.cs
- src/System.Windows.Forms/src/System/Windows/Forms/BindableComponent.cs
- src/System.Windows.Forms/src/System/Windows/Forms/CommonDialog.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.PageSelector.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DragDropHelper.cs
- src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Form.AccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ICommandBindingTargetProvider.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListBox.AccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.cs
- src/System.Windows.Forms/src/System/Windows/Forms/SystemInformation.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripComboBox.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripControlHost.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripProgressBar.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSeparator.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.ToolStripTextBoxControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
- src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
Enable SA1028 analyzer
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1028.md
Used solution wide code fix.
Related: #7887
> SA1028 Code should not contain trailing whitespace

- eng/CodeAnalysis.src.globalconfig
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripDesignerUtils.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/CheckBoxBaseAdapter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ButtonRenderer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/CheckBoxRenderer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComboBoxRenderer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/GroupBoxRenderer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ProgressBarRenderer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/RadioButtonRenderer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ScrollBarRenderer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TabRenderer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TextBoxRenderer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSystemRenderer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TrackBarRenderer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleInformation.cs
Enable CA2019 Analyzer.
Manually fixed based on message: `'ThreadStatic' fields should not use inline initialization`. All values were `default`, so the initializations were removed.
Related: #7887
> CA2019 Improper 'ThreadStatic' field initialization

- src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.GetOpenFileName.cs
I copied from the Win32 metadata directly and it had `PreserveSig = false`, which is only valid with HRESULT returns.
Fixes #7975
> Fix the original save dialog

- src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Dpi/DpiMessageHelper.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Dpi/FormTests.Dpi.cs
In PermonV2 mode applications, We have been using linear sizes for top-level windows that are provided by the Windows irrespective of the AutoScaleMode.  This has been problematic for AutoScaleMode.Font, where Form scaling should be non-linear given its child controls are scaled non-linearly and depend on the Font that was assigned to Form/child controls.
We are making changes to utilize [GetDpiScaledSize](https://learn.microsoft.com/en-us/windows/win32/hidpi/wm-getdpiscaledsize) message and let Windows know that Form may need non-linear sizes depending on AutoScaleMode.
> Fix top-level window size for non-linear dimensions based on AutoScaleMode

- src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
In order for properties to be exposed to `IPropertyBag` they must have a TypeConverter to and from either string (preferred) or `byte[]`.
These were always the first choice, `ISerializable` was the final fallback. This matches what we've done elsewhere when we've removed `BinaryFormatter`.
cc: @GrabYourPitchforks, @merriemcgaw
> Remove BinaryFormatter support from Control's ActiveX projection.

- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxPerPropertyBrowsingEnum.cs
- Enable nullability in AxPerPropertyBrowsingEnum.
> Enable nullability in AxPerPropertyBrowsingEnum

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripNumericUpDown.cs
- Enable nullability in ToolStripNumericUpDown.
> Enable nullability in ToolStripNumericUpDown

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripButton.cs
- Enable nullability in ToolStripButton.
> Enable nullability in ToolStripButton

- src/System.Windows.Forms/src/System/Windows/Forms/SplitContainer.cs
- src/System.Windows.Forms/tests/UnitTests/SplitContainerTests.cs
Fixes #3168 in combination with https://github.com/dotnet/winforms/pull/7956
- Scaling SplitterDistance property when DPI changed event occurs.
- Updating Panel sizes when FixedPanel property is set and DPI changed event occurs.
- Add unit test for future reference.
> Fix scaling in SplitContainer controls for high DPI machines

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.cs
- Enable nullability in ToolStripTextBox.
> Enable nullability in ToolStripTextBox

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripOverflowButton.cs
- Enable nullability in ToolStripOverflowButton.
> Enable nullability in ToolStripOverflowButton

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripStatusLabel.cs
- Enable nullability in ToolStripStatusLabel.
> Enable nullability in ToolStripStatusLabel

- src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
> Fix `FolderBrowserDialog.ShowDialog`

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DragEventArgs.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropTargetManager.cs
- Enable nullability in ToolStripDropTargetManager.
> Enable nullability in ToolStripDropTargetManager

- src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
WM_GETDPISCALEDSIZE is sent once per device and when moved back to same device, we only get DPI_CHANGED message but not WM_GETDPISCALEDSIZE. Windows cache the result from the first time and reuse it. This isn't very clear from the [documentation](https://learn.microsoft.com/en-us/windows/win32/hidpi/wm-getdpiscaledsize) and is found while experimenting and validating the scenarios.
> Fix WM_GETDPISCALEDSIZE message handling.

- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridToolStripButton.cs
- Enable nullability in PropertyGridToolStripButton.
> Enable nullability in PropertyGridToolStripButton

- eng/CodeAnalysis.src.globalconfig
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.DataGridViewTextBoxEditingControlAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.ControlItem.ControlItemAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.ControlItem.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.ErrorWindow.ErrorWindowAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.ErrorWindow.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.IconRegion.cs
Enabled SA1205 analyzer.
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1205.md
Applied solution wide code fix.
Related: #7887
> SA1205 Partial elements should declare an access modifier

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripCustomIComparer.cs
- Enable nullability in ToolStripCustomIComparer
> Enable nullability in ToolStripCustomIComparer

- eng/CodeAnalysis.src.globalconfig
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Formatter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
Enable SA1121 analyzer.
https://github.com/DotNetAnalyzers/StyleCopAnalyzers/blob/master/documentation/SA1121.md
Used solution wide code fix.
Related: #7887
> SA1121 Use built-in type alias

- eng/CodeAnalysis.src.globalconfig
- src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb
Enabled CA2007 analyzer.
https://learn.microsoft.com/en-us/dotnet/fundamentals/code-analysis/quality-rules/ca2007
Manually fixed. 
**Team needs to verify whether `ConfigureAwait(False)` or `ConfigureAwait(True)` is appropriate.**
Related: https://github.com/dotnet/winforms/issues/7887
> CA2007 Consider calling ConfigureAwait on the awaited task

- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridToolStrip.cs
- Enable nullability in PropertyGridToolStrip.
> Enable nullability in PropertyGridToolStrip

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitButton.cs
- Enable nullability in ToolStripSplitButton.
> Enable nullability in ToolStripSplitButton

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitStackDragDropHandler.cs
- Enable nullability in ToolStripSplitStackDragDropHandler.
> Enable nullability in ToolStripSplitStackDragDropHandler

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitButton.ToolStripSplitButtonButton.cs
- Enable nullability in ToolStripSplitButtonButton.
> Enable nullability in ToolStripSplitButtonButton

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripHighContrastRenderer.cs
Fixes #7724
- Changed ToolStrip overflow button arrow color when the button is in selected state. Affects HC themes only.
- Better button arrow visibility on HC themes
- No
- Minimal
Windows 11:
Windows 10:
Windows 11:
Windows10:
- Accessibility Insights for Windows - Color contrast analyzer
- Windows 10: .NET SDK 7.0.100-rc.2.22477.23
- Windows 11: .NET SDK 7.0.100-rc.2.22477.23
> Fixed ToolStrip overflow button arrow color in HC themes

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowHeaderCellAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTopLeftHeaderCellAccessibleObjectTests.cs
Part of #6094
- Add missing unit tests to check the method behavior in base class and derived classes
- .NET 7.0.0-rc.1.22426.10
- Windows 11
> Added unit tests for "AccessibleObject.FragmentNavigate" method in DataGridViewCell-related classes

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DirectionButtonAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.DirectionButtonAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObjectTests.cs
Part of #6094
- Add missing unit tests to check the method behavior in these classes: UpDownButtonsAccessibleObject, DirectionButtonAccessibleObject, DomainUpDownAccessibleObject
- .NET 7.0.0-rc.2.22472.3
- Windows 11
> Added unit tests for "AccessibleObject.FragmentNavigate" method in UpDown-related classes

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemListAccessibleObjectTests.cs
Part of https://github.com/dotnet/winforms/issues/6094
- Fixed tests for ListView in virtual mode
- Added comments on related test cases code location
- .NET 7.0.0-rc.2.22472.3
- Windows 11
> Fixed unit tests for "AccessibleObject.FragmentNavigate" method in ListViewItem-related classes

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendar.CalendarAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendar.CalendarBodyAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendar.CalendarCellAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendar.CalendarDayOfWeekCellAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendar.CalendarHeaderAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendar.CalendarNextButtonAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendar.CalendarPreviousButtonAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendar.CalendarRowAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendar.CalendarTodayLinkAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendar.CalendarWeekNumberCellAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendar.MonthCalendarAccessibleObjectTests.cs
Part of https://github.com/dotnet/winforms/issues/6094
Added missing unit tests to check the method behavior in these classes:
- MonthCalendarAccessibleObject
- CalendarAccessibleObject
- CalendarPreviousButtonAccessibleObject
- CalendarNextButtonAccessibleObject
- CalendarTodayLinkAccessibleObject
- CalendarBodyAccessibleObject
- CalendarHeaderAccessibleObject
- CalendarDayOfWeekCellAccessibleObject
- CalendarWeekNumberCellAccessibleObject
- CalendarRowAccessibleObject
- CalendarCellAccessibleObject
- .NET 7.0.0-rc.1.22426.10
- Windows 11
> Added unit tests for "AccessibleObject.FragmentNavigate" method in MonthCalendar-related classes

- src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.MaskedTextBoxAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MaskedTextBox.MaskedTextBoxAccessibleObjectTests.cs
Fixes #7938
- Overriden `Name` property in `MaskedTextBoxAccessibleObject`.
- Added new unit tests. 
- The `Name` of `MaskedTextBoxAccessibleObject` is more clarify.
- Yes
- Minimal
- Manually
- Unit testing 
- Inspect
.NET SDK:
> Fixed MaskedTextBoxAccessibleObject.Name if Owner.Mask is filled

- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Message.cs
Historically our first four fields matched the layout of MSG. Keeping it that way for better back compat.
As Message doesn't match MSG, they shouldn't be blitted over each other, but for those that might be doing this we can keep the order. Note that other future changes to the struct could break doing this sort of thing even if the first four fields stay the same.
> Reorder Message fields

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.ToolStripPanelRowManager.cs
- Enable nullability in ToolStripPanelRowManager.
> Enable nullability in ToolStripPanelRowManager

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripNumericUpDown.ToolStripNumericUpDownControl.ToolStripNumericUpDownAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripNumericUpDown.ToolStripNumericUpDownControl.cs
- Enable nullability in ToolStripNumericUpDownControl.
> Enable nullability in ToolStripNumericUpDownControl

- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiSelectRootGridEntry.cs
- Enable nullability in MultiSelectRootGridEntry.
> Enable nullability in MultiSelectRootGridEntry

- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiPropertyDescriptorGridEntry.cs
- Enable nullability in MultiPropertyDescriptorGridEntry.
> Enable nullability in MultiPropertyDescriptorGridEntry

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripContainer.ToolStripContainerTypedControlCollection.cs
- Enable nullability in ToolStripContainerTypedControlCollection.
> Enable nullability in ToolStripContainerTypedControlCollection

- src/System.Windows.Forms.Primitives/src/NativeMethods.txt
Removed a duplicate instance of WIN32_ERROR line in NativeMethods.txt file.
> Removed a duplicate WIN32_ERROR from  NativeMethods.txt 

- src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/AnchorLayoutTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Layout/AnchorLayoutTests.cs
We have multiple [issues](https://github.com/dotnet/winforms/issues?q=is%3Aissue+is%3Aopen+anchor+-label%3Atest-bug+-label%3A%22%3Aconstruction%3A+work+in+progress%22+-label%3Aapi-suggestion+-label%3Aapi-approved+-label%3Atenet-localization) reported in WinForms around the anchor layout being problematic on higher DPI scale monitors, irrespective of application DPI mode. This document outlines the changes being made in .NET 8.0 to address these issues along with setting the goal to support all supported application DPI modes in WinForms.
**Problem in Scope:**
Anchored control’s position with respect to its parent should be able to determine at the design time and would only need to be changed if there were explicit changes in the control’s Bounds or when the control is scaled in response …
> Update Anchor Layout to support high DPI machines.

- src/System.Windows.Forms/src/Resources/SR.resx
- src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemDetailsAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemLargeIconAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemListAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemSmallIconAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemTileAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemWithImageAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListVIew.ListViewAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemWithImageAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Part of #4690 
- Added base class `ListViewItemIconAccessibleObject` and its implementations `ListViewItemLargeIconAccessibleObject` and `ListViewItemSmallIconAccessibleObject`.
- Used `ListViewItemIconAccessibleObject` as base class of `ListViewItemListAccessibleObject`.
- Refactored `ListViewItemBaseAccessibleObject` and implementations. Moved common logic to the base class.
- Removed unused resource string `ListViewItemAccessibilityObjectInvalidViewsException`.
- Configured `ListViewItem` to support new item AO.
- Modified ListViewAccessibleObject to support image's AO in `LargeIcon`, `SmallIcon` and `List`  views.
- Fixed old unit tests.
- Added new unit tests.
- User can see information about ListViewItem's image via accessibility tools in `LargeIcon`, `SmallIcon` and `List` views.
- …
> Adding the ListViewItemImageAccessibleObject as a child in a ListViewItem in LargeIcon, SmallIcon and List views.

- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObjectTests.cs
Fixes #8025
- Fixed value in the `Column` property of `ListViewSubItemAccessibleObject` class.
- Covered `ListViewSubItemAccessibleObject.GetColumnHeaderItems` method with tests.
- Customer will see correct header info from a sub-item.
- Yes
- Minimal
- Manually
- Unit tests 
- Inspect
.NET SDK:
> Fixing incorrect Column value in ListViewSubItemAccessibleObject

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.cs
- Replace Hashtable with generic dictionary in ToolStrip.
> Replace Hashtable with generic dictionary in ToolStrip

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.ModalMenuFilter.HostedWindowsFormsMessageHook.cs
- Enable nullability in HostedWindowsFormsMessageHook.
> Enable nullability in HostedWindowsFormsMessageHook

- eng/pipelines/azure-pipelines-codeql.yml
Fix CodeQL 3000 configuration to 
1. properly pass intent to publish results to TSA 
2. properly discover TSA configuration file
None
No
None
This is the same pattern Arcade uses. I've also confirmed this specific configuration by build logs:
Build [20221031.1](https://dev.azure.com/dnceng/internal/_build/results?buildId=2033070&view=logs&j=eb2c8817-e906-5459-8080-1a4c8ed1e2e2&t=3d80e413-4872-527d-85b5-8fd7d891cc14) is a regular, scheduled build and scan. This build also shows the problem. The `CodeQLInit` task logging shows that `TSAEnabled` was not correctly detected (and thus set to false).
```
...
Configuration:
Cadence = 0
Enabled = true
LogLevel = 4
CLIVersion = 2.8.4
TSAEnabled = false
...
```
Build [20221101.2](https://dev.azure.com/dnceng/internal/_build/results?buildId=2034406&vi …
> Fix CodeQL TSA reporting

- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/TestAccessors.PropertyGridTestAccessor.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridTests.cs
Hi,
My name is Alex M. I am a software developer at DevExpress WinForms Team.
I created a pull request that fixes the following issue. It's related only for .NET 7 after this PR - [Combine PropertyGrid tab information.](https://github.com/dotnet/winforms/pull/6108).
"Invalid cast error" in the TryGetSavedTabSelection method. PropertyGrid saves information about selectedTab in a [SaveTabSelection ](https://github.com/dotnet/winforms/blob/7ef35233ec820db47dce981b9ba403850b98d7ec/src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs#L3628) method. After change the _selectedTab field from int to a TabInfo record we should use a _tabs.IndexOf(_selectedTab) method. In a [TryGetSavedTabSelection ](https://github.com/dotnet/winforms/blob/7ef35233ec820db47dce981b9ba403850b98d7ec/src/Sys …
> Fix a SaveTabSelection method

- src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
- src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
fixes: #8087
In PermonitorV2 mode applications, when moving the Form from one monitor to the other, Form gets an invalid display rectangle for a brief period during the scaling of its child controls. Updating anchors, because of layout, during this period would end up invalid anchor calculations. For all scaling scenarios due to DPI changed event, we will be scaling anchors and avoid/skip recalculation of anchors to prevent using this invalid display rect.
Following is the snippet where we see invalid DisplayRect of the Form for a brief period while moving from one monitor to the other.
**Invalid state:**
**Final state:**
Amending #7956
> Fix Anchors in PermonitorV2 mode applications.

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListControlTests.cs
Fixes #8046
- Used `Assert.Same` instead of `Assert.Equal` for `CultureInfo`.
- Unit tests shouldn't fail.
- No
- Minimal
- Unit testing
.NET SDK:
> Fixed comparing  of CultureInfo in unit tests.

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripHighContrastRenderer.cs
Fixes #7980
- Disabled checkmark is now rendered with the same code as other disabled images on ToolStrip
- Better visual difference between enabled and disabled menu items
- No
- Minimal
Windows 11, .NET 7:
Windows 10, .NET 7:
Windows 11, .NET 7:
Windows 10, .NET 7:
- .NET SDK 7.0.100-rc.2.22477.23
- Windows 11
> Fixed disabled ToolStripMenuItem checkmark rendering in HC themes

- docs/list-of-diagnostics.md
Fixed unavailable links and replaced with working ones. Previous links were based on the format for dotnet/runtime obsoletions from  https://github.com/dotnet/runtime/blob/main/docs/project/list-of-diagnostics.md, but for WinForms these pages were added to .NET Desktop docs instead of general .NET docs.
> Clean up docs/list-of-diagnostics.md

- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
- Replace hashtables with generic dictionaries in AxHost.
> Replace hashtables with generic dictionaries in AxHost

- src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.PostAssignedPositionComparer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.PreAssignedPositionComparer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.SorterObjectArray.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.SpanComparer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.cs
- Enable nullability in PostAssignedPositionComparer, PreAssignedPositionComparer and SpanComparer.
> Enable nullability in PostAssignedPositionComparer, PreAssignedPositionComparer and SpanComparer

- src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.Vista.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/OpenFileDialogTests.cs
- src/System.Windows.Forms/tests/TestUtilities/MSGF.cs
> Prevent OpenFileDialog From Throwing When Opening With Non-Existing Initial Directory

- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.State.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.PropertyBagStream.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataStreamFromComStream.cs
- src/System.Windows.Forms/tests/UnitTests/DataStreamFromComStreamTests.cs
Addresses https://github.com/dotnet/winforms/pull/8105#discussion_r1017451431
~~Update `Dispose(bool disposing)` methods for `AxHost.State` and `DataStreamFromComStream` to avoid releasing COM references on finalizer thread.~~
Ensure `_comStream` in `DataStreamFromComStream` does not get over released
- ~~Add field indicating whether `DataStreamFromComStream` takes ownership of the stream passed into constructor~~
- ~~Check if `DataStreamFromComStream` owns the stream before releasing~~
- Do not take ownership of `_comStream` in `DataStreamFromComStream` and remove its finalizer
> Prevent Over Releasing of IStream

- docs/list-of-diagnostics.md
- src/Common/src/Obsoletions.cs
- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainUpDownAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.cs
Fixes #7587 
- Remove `DomainUpDownAccessibleObject` usage as an accessible object for `DomainUpDown` because this class is obsolete now
- Promote obsoletion from warning to error
- If customer used `DomainUpDownAccessibleObject` in their code, they would have to change it to `ControlAccessibleObject` or `AccessibleObject`. Otherwise, no impact.
- No
- Minimal
- .NET 7.0 RC1
- Windows 11
> Removed obsolete  `DomainUpDownAccessibleObject` usage

- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxPropertyDescriptor.cs
Refactored `AxPropertyDescriptor` to replace `ArrayList` with `List<T>`
Related: #8140
> Refactor `AxPropertyDescriptor` to replace `ArrayList`

- src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.cs
Refactored TableLayout to replace `ArrayList` with `List<T>`, then removed unnecessary casts via code analyzer.
Related: #8140
> Refactor TableLayout to replace ArrayList

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnCollection.ColumnOrderComparer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnCollection.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewColumnCollectionTests.cs
Refactored `DataGridViewColumnCollection` to replace `ArrayList` with `List<T>`
Related: #8140
> Refactor DataGridViewColumnCollection to replace ArrayList

- eng/actions/backport/action.yml
🚨 Node 12 has an end of life on April 30, 2022.
The GitHub Actions workflow gives the following warning while running the action:
> Node.js 12 actions are deprecated. For more information see: github.blog/changelog/2022-09-22-github-actions-all-actions-will-begin-running-on-node16-instead-of-node12.
Similar dep: https://github.com/dotnet/templating/pull/5576
This PR updates the default runtime to [node16](https://github.blog/changelog/2021-12-10-github-actions-github-hosted-runners-now-run-node-js-16-by-default/) rather then node12. 
This is supported on all Actions Runners v2.285.0 or later.
Signed-off-by: Enes <ahmedenesturan@gmail.com>
> Update backport action environment to Node 16

- src/System.Windows.Forms/src/System/Windows/Forms/AutoCompleteStringCollection.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FolderBrowserDialogTests.cs
> Refactor `AutoCompleteStringCollection` to use `List<string>` instead of `ArrayList`

- src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs
> Refactor `ThreadContext` to use `Dictionary<uint, ThreadContext>` instead of `Hashtable`

- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridErrorDialog.cs
GridError dialog is missing `AutoScaleDimension` property resulting in default scale factor `1`. Thus, not scaled according to the DPI of the primary monitor. This property is auto generated if dialog was designed in the designer.
Fixes #5111 .
> GridError dialog missing AutoScaleDimensions property

- src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollBarTests.cs
When original fix to scale scrollbars was introduced, we hide change under a switch and introduced public property to help developers control the scaling. In .NET, we removed all switches and accidentally removed developer control via public property `ScaleScrollBarForDpiChange`.
Bringing parity with Framework here.
Fixes #2742
> Scrollbar scaling according to Dpi is controllable via public property in Framework

- src/System.Windows.Forms/src/System/Windows/Forms/MergeHistoryItem.cs
- Enable nullability in MergeHistoryItem.
> Enable nullability in MergeHistoryItem

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.ToolStripPanelRowControlCollection.ToolStripPanelCellToControlEnumerator.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.ToolStripPanelRowControlCollection.cs
- Enable nullability in ToolStripPanelCellToControlEnumerator.
> Enable nullability in ToolStripPanelCellToControlEnumerator

- src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewNativeItemCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
> Refactor `ListView` to use `Dictionary` instead of `Hashtable`

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DocumentDesigner.cs
> Refactor DocumentDesigner to use List<T> instead of ArrayList

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripKeyboardHandlingService.cs
Plus other refactors.
Related: #8140, #3459
> Refactor ToolStripKeyboardHandlingService to use List<T> instead of ArrayList

- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/WeakRefCollection.cs
> Refactor WeakRefCollection to use List<WeakRefObject?> instead of ArrayList 

- .github/fabricbot.json
The task appears to have not been run for awhile, tweak the settings in hope to revive the task.
> Tweak "Add no recent activity label to issues and pull requests" task

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.AccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxEditingControl.DataGridViewComboBoxEditingControlAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxEditingControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.DataGridViewTextBoxEditingControlAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.cs
Fixes #7347
⚠️Should be merged after #7319 because uses the ComboBox leaks fix.
⚠️Doesn't fix memory leaks of TextPattern. It will be fixed as another fix for TextBox as well.
- Add a call of UiaDisconnectProvider for DataGridView elements (rows, cells, headers) for cases when:
DataGridView is destroyed
A row is removed from a DataGridView
A column is removed from a DataGridView
Using TextPattern explorer of Inspect, Narrator
- Less memory leaks of DataGridView
- No
- Minimal
- There are some kept object in the memory after disposing a DataGridView:
- These are no DataGridView elements objects in the memory after disposing (without TextPattern):
- CTI
- .NET 7.0 Preview 4
- Windows 11
> Fixing memory leaks of DataGridView elements accessible objects

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/MenuCommandService.cs
> Refactor MenuCommandService to use List<T> instead of ArrayList

- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridPositionData.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
> Refactor PropertyGridView to use List<GridEntryCollection> instead of ArrayList

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.ItemComparer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.ObjectCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewSelectedCellCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewSelectedColumnCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewSelectedRowCollection.cs
Related: https://github.com/dotnet/winforms/issues/8140
> Refactor several data grid view classes to use List<T> instead of ArrayList

- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
Fixes #8218
- Add MSAA focus event on ComboBox dropdown close. This event lets NVDA correctly switch focus from dropdown to ComboBox edit field when the dropdown is closed. NVDA recognizes ComboBox as IAccessible object, therefore it ignores existing UIA focus events.
- NVDA will announce value change by arrows after the dropdown was closed
- No
- Minimal
Test using NVDA screen reader. Scenario: a form with a ComboBox having items "1", "2" and "3", focus is set to ComboBox.
Steps:
1. Press Alt + Down: expand ComboBox
2. Press Down: select item "1"
3. Press Enter: close dropdown
4. Press Down: change selection to item "2"
5. Press Down: change selection to item "3"
NVDA speech output:
> combo box  collapsed
> expanded
> 1
> list
> 1
No announcement of value change by …
> Add MSAA focus event on ComboBox dropdown close

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.cs
> Refactor ComponentDesigner to use Dictionary<TKey, TValue> instead of Hashtable

- src/System.Windows.Forms/src/System/Windows/Forms/HelpProvider.cs
Refactor `HelpProvider` to use `Dictionary` instead of `Hashtable`
Related: #8143
> Refactor `HelpProvider` to use `Dictionary` instead of `Hashtable`

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationServiceTests.cs
> Refactor CodeDomComponentSerializationService to use List<T> instead of ArrayList

- src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserContainer.cs
Refactored WebBrowserContainer to replace HashTable and Enable Nullability.
Related to #8143
> Refactor WebBrowserContainer to replace HashTable and Enable Nullability

- src/System.Windows.Forms/src/System/Resources/AssemblyNamesTypeResolutionService.cs
Replaced the Hashtables, enabled nullability, removed `AssemblyName.CodeBase` call.
Related: #8143, #7308
> Refactor AssemblyNamesTypeResolutionService to replace HashTable

- src/System.Windows.Forms/src/System/Resources/ResXResourceWriter.cs
Refactor `ResXResourceWriter` to use `Dictionary<string, string>` instead of `Hashtable`.
Related: #8143
> Refactor `ResXResourceWriter` to use `Dictionary<string, string>` instead of `Hashtable`

- src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/Com2AboutBoxPropertyDescriptor.AboutBoxUITypeEditor.cs
- Make component nullable in AboutBoxUITypeEditor.
> Make component nullable in AboutBoxUITypeEditor

- src/System.Windows.Forms/src/misc/ImageListUtils.cs
- Make currentComponent nullable in ImageListUtils.GetImageListProperty.
> Make currentComponent nullable in ImageListUtils.GetImageListProperty

- src/System.Windows.Forms.Analyzers.CSharp/src/System/Windows/Forms/Generators/ProjectFileReader.FontConverter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
Refactors `System.Windows.Forms` to use `is not null` instead of `!= null` using [CSharpIsNull](https://github.com/AArnott/CSharpIsNull) analyzer code fix.
Related: #3459
> `System.Windows.Forms` Refactor `!= null` to `is not null`

- src/System.Windows.Forms.Design/src/System/Drawing/BitmapSelector.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/Behavior.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ComboBoxDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CommandSet.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlCommandSet.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignBindingValueUIHandler.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerExtenders.NameExtenderProvider.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DocumentDesigner.AxToolboxItem.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DocumentDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ImageIndexEditor.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ListBoxDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ListViewDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.CfCodeToolboxItem.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.ComponentDataObject.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/PanelDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ParentControlDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/PbrsForward.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/PictureBoxDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/RichTextBoxDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SelectionUIHandler.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TabOrder.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TextBoxDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripItemDesigner.cs
Refactors `System.Windows.Forms.Design` to use `is null` instead of `== null` using [CSharpIsNull](https://github.com/AArnott/CSharpIsNull) analyzer code fix.
Related: https://github.com/dotnet/winforms/issues/3459
> `System.Windows.Forms.Design` Refactor `== null` to `is null`

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Resources/AssemblyNamesTypeResolutionService.cs
- src/System.Windows.Forms/src/System/Resources/DataNodeInfo.cs
- src/System.Windows.Forms/src/System/Resources/IAliasResolver.cs
- src/System.Windows.Forms/src/System/Resources/ResXDataNode.cs
- src/System.Windows.Forms/src/System/Resources/ResXFileRef.cs
- src/System.Windows.Forms/src/System/Resources/ResXResourceReader.ReaderAliasResolver.cs
- src/System.Windows.Forms/src/System/Resources/ResXResourceReader.cs
- src/System.Windows.Forms/src/System/Resources/ResXResourceSet.cs
- src/System.Windows.Forms/src/System/Resources/ResXResourceWriter.cs
- src/System.Windows.Forms/src/System/Resources/ResXSerializationBinder.cs
- src/System.Windows.Forms/src/System/Resources/ResxFileRef.Converter.cs
There are two commits here. The first cleans up the code, with particular attention to reducing the nesting by inverting if statements and returning out early.
The second null annotates all of types that weren't already annotated.
> Clean up and null annotate Resx code

- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MergePropertyDescriptor.MergedAttributeCollection.cs
Refactor MergedAttributeCollection to replace HashTable and enable nullability.
Related: #8143
> Refactor MergedAttributeCollection to replace HashTable

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/BindingContext.HashKey.cs
- src/System.Windows.Forms/src/System/Windows/Forms/BindingContext.cs
- Enable nullability in BindingContext and HashKey.
> Enable nullability in BindingContext and HashKey

- eng/Versions.props
Internal build is failing with compliance on one of the dependencies.  This version is not updated by arcade.
refer: https://dev.azure.com/dnceng/internal/_componentGovernance/dotnet-winforms/alert/7454535?typeId=6663759&pipelinesTrackingFilter=0
> Update MicrosoftCodeAnalysisPackagesVersion for compliance

- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxContainer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
This change refactors AxHost to remove arraylist and simplifies some Dictionary<Control, Control> to Hashset<Control>.
Related #8140
> Refactor `AxHost` to remove `ArrayList`

- src/Common/tests/TestUtilities/CustomConverter.cs
- src/System.Windows.Forms.Design/tests/UnitTests/Properties/launchSettings.json
- src/System.Windows.Forms.Design/tests/UnitTests/System.Windows.Forms.Design.Tests.csproj
- src/System.Windows.Forms.Design/tests/UnitTests/System/Resources/Tools/StronglyTypedResourceBuilderTests.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.State.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.StateConverter.cs
- src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj
- src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceReaderTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs
- Minor clean ups for `State` and `StateConverter`
- Add serialization test for `AxHost` using `BinaryFormatter`
- Add test for serializing `AxHost` using `StronglyTypedResourceBuilder`
- `StateConverter` was never hooked up properly so manually register `StateConverter` as the `TypeConverter` for `State` using `CustomConverter` class
- Fix `State` constructor utilized by `StateConverter` to not save the passed in stream since extra information to build the State is contained in it.
- Add test for `ResXResourceReader` verifying AxHosts can be deserialized from resx file
> Add Serialization Tests for AxHost

- src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FormTests.cs
Backport of https://github.com/dotnet/winforms/pull/8283 to release/7.0
Fixes #8280
Form.Show/ShowDialog(IWin32Window owner) method should set form's Owner property, however this logic had been inadvertently inverted for not TOPLEVEL windows during refactoring (#5791) and form owner property would be `null`. This fix restores the previous logic.
- `null` owner property might lead to window shown on an incorrect desktop or in the wrong place.
- This regression may cause serious UI issues described in https://github.com/dotnet/winforms/issues/8280, to the point of being a ship blocker.
- Check if owner doesn't have a `TOPMOST` style to correctly initialize it with a top-level Control in this case
- Owner property will be correctly set for a form if it was shown with a Control as owner
- Yes …
> [release/7.0] Fix setting Form.Owner in Form.Show/ShowDialog(IWin32Window owner) if owner is a Control 

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.ShadowPropertyCollection.cs
> Refactor ComponentDesigner.ShadowPropertyCollection to use Dictionary<TKey, TValue> instead of Hashtable

- src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Layout/ArrangedElementCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItemCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.ToolStripPanelControlCollection.XYComparer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.ToolStripPanelControlCollection.YXComparer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.ToolStripPanelRowCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.ToolStripPanelRowControlCollection.ToolStripPanelCellToControlEnumerator.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.ToolStripPanelRowControlCollection.cs
> Refactor ArrangedElementCollection to use List<IArrangedElement> instead of ArrayList

- src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FormTests.cs
This restores a behavior until #5791, where this condition was inverted as a part of refactoring.
Fix #8280 on .NET 8
- Check if owner doesn't have a `TOPMOST` style to correctly initialize it with a top-level Control in this case
- Owner property is correctly set for a form if it was shown with a Control as owner
- Yes 
- Minimal - restores previous behavior
- Unit test
- Manual test with sample app from https://github.com/dotnet/winforms/issues/8280#issuecomment-1326776047
- CTI
- .NET 8.0.100-alpha.1.22565.7
> Fix setting Form.Owner in Form.Show/ShowDialog(IWin32Window owner) if owner is a Control

- src/System.Windows.Forms/src/System/Windows/Forms/StatusStrip.StatusStripAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.ToolStripAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripScrollButton.ToolStripScrollButtonAccessibleObjectTests.cs
Fixes #8033
- Removed duplicate items reordering in GetChildFragment and GetChildFragmentIndex methods
- Modified FragmentNavigate to return null if ToolStrip's handle is not created
- Modified unit tests to properly follow handle creation
Before
After
> Fixed FragmentNavigate issue in ToolStripAccessibleObject

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.ModifierConverter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/CursorConverter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/MdiWindowListItemConverter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/SpecialFolderEnumConverter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TextBoxAutoCompleteSourceConverter.cs
> Refactor GetStandardValues implementations to remove ArrayList

- eng/Versions.props
- src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.VARIANT.cs
- src/System.Windows.Forms.Primitives/src/NativeMethods.json
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/FileDialogCustomPlacesCollection.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/Foundation/GlobalInterfaceTable.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/System/Ole/IPicture.cs
- src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/Oleaut32/IDispatchTests.cs
- src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/Oleaut32/ITypeInfoTests.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.State.cs
- src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.Vista.cs
- src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.cs
- src/System.Windows.Forms/src/System/Windows/Forms/SaveFileDialog.cs
- src/System.Windows.Forms/src/System/Windows/Forms/StringSource.cs
- src/System.Windows.Forms/src/System/Windows/Forms/SystemInformation.cs
The default behavior now in CsWin32 is to not PreserveSig. Individual opt-outs are in NativeMethods.json.
> Update to the latest CsWin32.

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollBarTests.cs
Fixes #8270
in .NET 6, we streamlined scaling of child controls to use `AutScaleFactor` in PMv2 mode applications. This is a change from .NET framework, where we were scaling child controls with DPI factor even when `AutoScaleMode` was `Font`. As a result, scaling is centralized under `OnParentFontChanged` event and any controls that were doing explicit scaling in `RescaleConstants` method become redundant in .NET.
When it comes to `ScrollBars`, we added public property in .NET Framework 4.8 to let developer's opt-in/out of DPI scaling for scroll bars.
> Fix double scaling for scrollbars

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.ToolStripMenuItemAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripMenuItem.ToolStripMenuItemAccessibleObjectTests.cs
Fixes #8307
- Added Toggle pattern support for menu items with CheckOnClick set to true and pre-checked menu items
- Added unit tests for ToolStripMenuItemAccessibleObject to verify pattern implementation
- Narrator announces checked state of checkable menu item
- Checkable menu item can be checked or unchecked using UI Automation API
- No
- Minimal
No checked state announcement:
No toggle pattern support:
Checked state announcement:
Toggle pattern support: 
- Accessibility Insights for Windows
- 7.0.0
> Adding the ToolStripMenuItem checked state announcement

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionUI.DesignerActionToolStripDropDown.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionUI.cs
Also moved DesignerActionToolStripDropDown.cs to its own file. Maybe it should be inside DesignerActionUI with DesignerActionUI being a partial class?
Related: #8143
> Refactor `DesignerActionUI` to use Dictionary

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.ToolStripMenuItemInternalLayout.cs
- Make image nullable in ImageRectangle property of ToolStripMenuItem.
- Addresses https://github.com/dotnet/winforms/pull/8100#discussion_r1012382425
> Make image nullable in ImageRectangle property of ToolStripMenuItem

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyPageUITypeConverter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/ICOM2PropertyPageDisplayService.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/IComPropertyBrowser.cs
- Enable nullability in IComPropertyBrowser and ICom2PropertyPageDisplayService.
> Enable nullability in IComPropertyBrowser and ICom2PropertyPageDisplayService

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourceCodeDomSerializer.SerializationResourceManager.cs
- src/System.Windows.Forms/src/System/Resources/ResXResourceReader.cs
- Refactored `ResourceCodeDomSerializer.SerializationResourceManager` to replace usages of `Hashtable`. 
- Refactored `ResXResourceReader` to use `Dictionary` instead of `ListDictionary`
Related: #8143
> Refactor `SerializationResourceManager` to use `Dictionary` instead of `HashTable`

- src/System.Windows.Forms/src/System/Windows/Forms/Cursor.cs
> Fix `Cursor(Stream)` to avoid incomplete reads and possible exception

- src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.AnchorInfo.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
Fixes #8266.
In PermonV2 mode applications, when moved from one monitor to the other, Form/Container is scaled with scale factor computed with respect to new DPI on the monitor. However, scaling ratio between non-client and client area is not linear. This is causing few pixels variance when anchors are also scaled with same scale factor.
Anchors are relative to display rectangle. Hence, making change to computing anchor scale factor with respect to change in DisplayRect instead of change in the bounds (a.k.a: scale factor computed with respect to new DPI).
This PR follows #8201.
> Fix scaling anchors in PMv2 applications.

- eng/common/templates/steps/send-to-helix.yml
- Removes the isExternal configuration option from Helix
- N/A
- No
- None
- Verified that the isExternal config option is not used anywhere else.
> Remove isExternal config option from Helix

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/MenuCommandsChangedEventArgs.cs
- Enable nullability in MenuCommandsChangedEventArgs.
> Enable nullability in MenuCommandsChangedEventArgs

- src/System.Windows.Forms/src/System.Windows.Forms.csproj
These were added by the designer when nested classes were [split into the dedicated files](https://github.com/dotnet/winforms/commit/d0974fc45e7be195721091b4a8d09caf7394397b). Subtype informs the IDE what file view to use with these files, however it would had deduced this information from the type and visual designer does not work with these files.
> Removed designer-added tags from the project file

- pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config/template.json
- pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-CSharp/.template.config/template.json
- pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/.template.config/template.json
Inverted `langVersion` conditions in C# templates
Background: the new language version is released each year, and it is easy to change regex in template definition.
Inversion of condition doesn't need an update with new  `langVersion`  released.
This was already done in Common and WPF templates.
Related to: https://github.com/dotnet/templating/issues/5668
> inverted `langVersion` conditions in C# templates

- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/TabControlTests.cs
Fixes #7837
- Fix logic in TabPageCollection.RemoveAt to avoid removing incorrect TabPage when TabControl.Controls collection is out of sync with TabControls._tabPages. This can happen when Control.WmWindowPosChanged calls _parent.UpdateChildControlIndex, which calls Controls.SetChildIndex.
- None
- No
- Low
- Adhoc testing. There's just one of code, and the new implementation calls only public methods.
> Fix bug in TabPageCollection.RemoveAt (#7837)

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TabOrder.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IManagedPerPropertyBrowsingHandler.cs
There are several places where I had to do some unusual null checks where I think the code previously just assumed the they were not null. Such as any of the collections (`tabComplete`, ect), or `Control.Parent`.
Related: #8342, #8143, #8140
> Refactor `TabOrder` to enable Nullability and replace `ArrayList`/`HashTable`

- src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/TrackBars.Designer.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/TrackBars.cs
Allow users to set large a range of values on the trackbar without excessive memory consumption.
Fixes #329
- Solving the issue of Memory consumption for the trackbar for large range of values on trackbar.
- Turning `TBS_AUTOTICKS` off when the the tick range is larger then the physical limitations of the trackbar by checking this with the Boolean method `ShouldAutoDrawTicks()`. This sets the flag `_autoDrawTicks` in `CreateParams`.
- The fix will be put behind a feature switch called `TrackBarModernRendering` in `LocalAppContextSwitches ` because of the significant risk - primarily due to the use of `RecreateHandle()` method. If they opt out of the feature the `ShouldAutoDrawTicks()` then it will always return true. This means that the way of rendering ticks will be reverted back to the …
> Avoid excessive memory usage and slow `TrackBar` control 

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/HtmlHistory.cs
- Enable nullability in HtmlHistory.
> Enable nullability in HtmlHistory

- src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs
Fixes #8424
- Add simple test.
- Fix InvalidCastException in ErrorProvider
> Fix InvalidCastException in ErrorProvider

- src/System.Windows.Forms/src/System/Windows/Forms/FontDialog.cs
The native font dialog does not currently support PermonitorV2 mode. We are setting DpiAwareness to SystemAware as a workaround. This action has no effect when the application is not running in PermonitorV2 mode.
Windows tracking bug: https://microsoft.visualstudio.com/OS/_workitems/edit/42835582
Fixes #8265
> Set Dpiawareness on Font Dialog.

- eng/Versions.props
- src/System.Windows.Forms.Analyzers.CSharp/src/System.Windows.Forms.Analyzers.CSharp.csproj
- src/System.Windows.Forms.Analyzers/src/System.Windows.Forms.Analyzers.csproj
- src/System.Windows.Forms.PrivateSourceGenerators/src/System.Windows.Forms.PrivateSourceGenerators.csproj
Fixes #8387 - Replace Workspaces nuget packages with compiler only packages
> Replace Workspaces nuget packages with compiler only packages

- src/System.Windows.Forms.Primitives/src/Interop/UiaCore/Interop.UiaReturnRawElementProvider.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildNativeWindow.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxEditingControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewLabelEditNativeWindow.cs
- src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripControlHost.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItem.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
- src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.cs
- src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ColumnHeader.ListViewColumnHeaderAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPage.TabAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNode.TreeNodeAccessibleObjectTests.cs
Fixes #8217
- Changed type to `HWND`.
- Refactored `Control.HWNDInternal` property to remove extra convert.
- Used `HWND` value instead of `Handle`.
- Used `HWND.Null` value instead of `IntPtr.Zero`.
- Method becomes more clear and an argument type is unified.
- No
- Minimal
- Manual
- Unit tests
- Inspect 
.NET SDK:
> Changed type of the `handle` parameter from `IntPtr` to  `HWND` in the `Control.ReleaseUiaProvider` method

- src/System.Windows.Forms.Analyzers.CSharp/src/System/Windows/Forms/Generators/ApplicationConfigurationGenerator.cs
- src/System.Windows.Forms.Analyzers.CSharp/src/System/Windows/Forms/Generators/ProjectFileReader.cs
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.GenerateInitialize_DefaultFont=SansSerif.verified.txt
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.GenerateInitialize_DefaultFont=Tahoma.verified.txt
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.GenerateInitialize_DefaultFont=default.verified.txt
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.cs
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/MockData/ApplicationConfigurationGeneratorTests.GenerateInitialize_user_settings_boilerplate.cs
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/MockData/ApplicationConfigurationGeneratorTests.GenerateInitialize_user_top_level.cs
- src/System.Windows.Forms.Analyzers/src/System/Windows/Forms/ApplicationConfig.FontDescriptor.cs
- src/System.Windows.Forms.Analyzers/src/System/Windows/Forms/ApplicationConfig.FontStyle.cs
- src/System.Windows.Forms.Analyzers/src/System/Windows/Forms/ApplicationConfig.GraphicsUnit.cs
- src/System.Windows.Forms.Analyzers/src/System/Windows/Forms/ApplicationConfig.cs
- src/System.Windows.Forms.Analyzers/tests/UnitTests/System/Windows/Forms/Analyzers/ApplicationConfigTests.FontDescriptor.cs
Fixes #8386
- 
- 
- 
- 
- 
- Yes / No
-
- 
- 
- 
-
> Fix generator incrementality

- src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs
Porting from main. Please refer  https://github.com/dotnet/winforms/pull/8425 for more details
Fixes #8424 
- We are moving to generic collections across Winforms code base. This is a regression from that change resulting in exception with type cast.
- Add simple test.
- Fix InvalidCastException in ErrorProvider
- Will see exceptions with ErrorProvider usage.
- 
- Yes 
- Low.  Unit tests added.
- Manul and Unit test.
> [Porting] Fix InvalidCastException in ErrorProvider

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.ToolStripPanelRowControlCollection.ToolStripPanelCellToControlEnumerator.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.ToolStripPanelRowControlCollection.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripPanelTests.cs
Fixes #8415
- Add simple test.
- Pass enumerator as parameter to fix the exception.
> Fix InvalidCastException when adding a second ToolStrip in ToolStripPanel

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ToolStripTests.cs
Fixes #7884
First commit contains the test to prove the failure. Thus proving the subsequent fix actually fixes it.
> Fix exception caused by `ToolStripMenuItem.DropDownClosed` hiding itself.

- src/System.Windows.Forms/src/System/Windows/Forms/MenuStrip.MenuStripAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownMenu.ToolStripDropDownMenuAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MenuStrip.MenuStripAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripDropDownMenu.ToolStripDropDownMenuAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemAccessibleObjectTests.cs
Fixes #8433
- Fix values of IsControlElementProperty and IsContentElementProperty properties in MenuStrip, ToolStripDropDown and ToolStripItem accessible objects as described in 
[UI Automation Support for the Menu Control Type](https://learn.microsoft.com/en-us/dotnet/framework/ui-automation/ui-automation-support-for-the-menu-control-type) and [UI Automation Support for the MenuItem Control Type](https://learn.microsoft.com/en-us/dotnet/framework/ui-automation/ui-automation-support-for-the-menuitem-control-type)
- JAWS for Windows announces top-level menu item without adding "sub menu"
- No
- Minimal
> Menu bar
> File sub menu
> To navigate press Left or Right Arrow.
> f
> Edit sub menu
> e
> Tools sub menu
> t
> menu
> Customize
> To move through items press up or down arrow.
> c
> …
> Fix UIA tree structure for MenuStrip

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/Drawing/Design/BitmapEditor.cs
- src/System.Windows.Forms.Design/src/System/Drawing/Design/ColorEditor.ColorUI.cs
- src/System.Windows.Forms.Design/src/System/Drawing/Design/ColorEditor.cs
- src/System.Windows.Forms.Design/src/System/Drawing/Design/IconEditor.cs
- src/System.Windows.Forms.Design/src/System/Drawing/Design/ImageEditor.cs
- src/System.Windows.Forms.Design/src/System/Drawing/Design/MetafileEditor.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ImageListImageEditor.cs
Enable Nullability in multiple Design classes
Related: #8342
> Enable Nullability in multiple `Design` classes

- src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageListTests.cs
Fixes #7021
In the linked issue, the suggestion was to change the default `ColorDepth` to `32bit`. Thus having the best looking image by default. For modern applications this makes a lot of sense.
Side effects from this include a branch in `GetBitmap` which checks the alpha information, which may decrease performance slightly when interacting with the `ImageCollection`. It could also result in higher memory usage. But I cannot see any documentation on whether the `ColorDepth` setting reduces the image quality to save on memory. It's just a hunch.
> Change default `ImageList.ColorDepth` to 32bit

- src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
- src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/LocalAppContextSwitchesTest.cs
- src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/SynchronousCollection.cs
There is a problem with the parsing of the TargetFramework, which is causing an invalid value to be set. static nullable private property needs to be assigned before its use.
Because the AppContext flags are read-only for .NET apps, and the incorrect TargetFramework is bypassing the logic behind these flags.
Found while verifying #6381.
> Fix read only static member evaluation order

- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolStripTests.Designer.cs
Fixes #8395
- Set MSAA focus on edit field when dropdown is closed for ComboBox with 'DropDown' style. If focus is set to the ComboBox itself, NVDA will not announce changes to the edit field, e.g. when selecting items by arrows. Focus on edit field also matches the focus when ComboBox is selected by Tab key.
- Add ToolStripComboBox to WinformsControlsTest app
- NVDA will announce item changes by arrows after dropdown is closed.
- No
- Minimal
* For `ComboBox`:
> combo box  collapsed
> ComboBox  edit  blank
> 1
> list
> 1
> ComboBox  1 collapsed
* For `ToolStripComboBox`:
Same issue is present:
> combo box  collapsed
> ComboBox  edit  blank
> list
> 1
> ComboBox  1 collapsed
* For `DataGridViewComboBoxCell` there is no issue because its own `ComboBox` has `DropDownList` style without an …
> Fix announcing ComboBox item change by arrows in NVDA when DropDownStyle set as "DropDown"

- src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
> [CSY] ‘Details’ and ‘Continue’ have the same hotkey "P" in unhandled exception

- src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
- src/System.Windows.Forms/src/System/Windows/Forms/ThreadExceptionDialog.cs
> [RUS] The ‘Details’ button text overlaps its drop down arrow in unhandled exception dialog

- src/System.Windows.Forms/src/System/Windows/Forms/Cursor.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CursorTests.cs
Change Cursor ctor to reset the stream parameters position ready for the copyTo call.
This is a guess on the fix, but would make sense.
Related: #8367, #8373
> Copying begins at the current position in the current stream, and does not reset the position of the destination stream after the copy operation is complete.
https://learn.microsoft.com/en-us/dotnet/api/system.io.stream.copyto?view=net-7.0
> Improve `Cursor` `Stream` constructor to be more robust

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.ToolStripMenuItemAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripMenuItem.ToolStripMenuItemAccessibleObjectTests.cs
Fixes #3471
- Added UIA's PositionInSet and SizeOfSet properties to ToolStripMenuItemAccessibleObject
- Screen readers can announce menu items order information 
- No
- Minimal
- Manually
- .NET 7.0.1
- Windows 11
> Adding UIA's PositionInSet and SizeOfSet properties to ToolStripMenuItemAccessibleObject

- src/System.Windows.Forms/src/System/Windows/Forms/Keys.cs
- src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/KeysConverterTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripMenuItemTests.cs
Also added some tests to better cover the KeysConverter.
Fixes #8456
> Fix issues in `KeysConverter.ConvertTo` introduced in #8255

- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewListBoxAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewTextBox.GridViewTextBoxAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.PropertyGridViewAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
Fixes #6943 (except cases when leaking is caused by `UiaTextRange`)
- Added `ReleaseUiaProvider` method to `GridEntry` to release it and its children.
- Override `ReleaseUiaProvider` method in `PropertyGrid` and `PropertyGridView` classes to release their items too.
- Fewer leaks in memory when `PropertyGrid` is used.
- No
- Minimal
- Manualy utilizing WinDbg 
- Inspect
- AI
- Narrator
.NET SDK:
> Fixed memory leaking of PropertyGrid

- src/System.Windows.Forms/src/System/Windows/Forms/Help.cs
See issue for discussion on fix.
Fixes #4422
> Specify `Font` in `HH_POPUPW` when calling `ShowHTML10Help` in `Help.ShowPopup` to allow for unicode characters

- src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
- src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/MainFormControlsTabOrder.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/FormOwnerTestForm.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
> Fixes `Form.Show(IWin32Window)` causing memory leaks by removing setting of `PropDialogOwner`

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.AdornerWindow.MouseHook.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DropSourceBehavior.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SelectionUIService.cs
Related: #8515
I have fixed the exceptions in `DropSourceBehavior` and `SelectionUIService`. But the resize via the editor still doesn't work.
> Fix control select and exception when moving controls

- src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/InputLanguageTests.cs
Properly convert HKL to KLID string according to the comment from Windows team at https://github.com/dotnet/winforms/issues/4345#issuecomment-759161693
Don't need to look at `HKEY_CURRENT_USER\Keyboard Layout\Substitutes` at all since HKL is already have all needed information.
Fixes #4345
> Fix keyboard layout name returned from System.Windows.Forms.InputLanguage.LayoutName

- src/System.Design/src/System.Design.Forwards.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DateTimePickerDesigner.cs
- src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/DesignerAttributeTests.cs
Related to #8501, #8508, #2411
- Port DateTimePickerDesigner to runtime
- DateTimePicker can be designed in runtime
- No
- Minimal
DateTimePicker is not available in runtime designer scenario
DateTimePicker can be designed in runtime
- Manually (added DateTimePicker to DemoConsole test app)
- .NET 8.0.0-alpha.1.23067.11
- Windows 10.0.22621
> Port DateTimePickerDesigner to runtime

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripControlHost.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripControlHostTests.cs
Refactored `ToolStripControlHost.Control` property to throw `ObjectDisposedException` if null.
Also some minor refactoring using expression bodies
Fixes #2466
> Refactor `ToolStripControlHost.Control` property to throw `ObjectDisposedException` if null

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/SelectionService.cs
Refactored `ISelectionService` to replace `ArrayList` and enable Nullability.
I had to submit a PR to Runtime to fix the nullability on `ISelectionService.PrimarySelection`, this PR will need to be rebased to main once that change has been made available. Until then this will have build errors.
https://github.com/dotnet/runtime/pull/81254
Related: #8140
> Refactor `SelectionService` to replace `ArrayList` and enable Nullability

- azure-pipelines-richnav.yml
- azure-pipelines.yml
- eng/pipelines/azure-pipelines-codeql.yml
- eng/pipelines/build.yml
Cherry pick of changes from https://github.com/dotnet/winforms/pull/8564 for main.  This will cause future release/ branches forked off from main to get this behavior.
Fixes #
- 
- 
- 
- 
- 
- Yes / No
-
- 
- 
- 
-
> Automatic Pool provider selection (Main branch)

- src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
- src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/LocalAppContextSwitchesTest.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PictureBox.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PictureBoxTests.cs
Related: [CodeQL](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1666879/) , https://github.com/dotnet/winforms/issues/8561
- Introduces a switch for turning on `ServicePointManager.CheckCertificateRevocationList`
- Fixes tests and adds test to check for same behavior when switch is both on and off
- Add CodeQL suppression in case it tries to reflag this because of the switch
- General clean up
**Background:**
Before creating a `WebClient` or `WebRequest`, it is best practice to set `ServicePointManager.CheckCertificateRevocationList` to `true` beforehand so that revoked certificates are not accepted by `WebClient`s or `WebRequest`s as valid. 
Now that we are checking certificate revocation list, the behavior should remain the same as before, however there is a rare case when it …
> Enable CheckCertificateRevocationList Under a Switch

- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewBand.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellStyle.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewHeaderCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewLinkCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.cs
- Use TryGetObject instead of ContainsObject and GetObject.
> Use TryGetObject instead of ContainsObject and GetObject

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewBand.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewHeaderCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyStore.cs
- Add ContainsObjectThatIsNotNull method in PropertyStore and use it where possible
- Addresses https://github.com/dotnet/winforms/pull/8575#discussion_r1099644647
> Add ContainsObjectThatIsNotNull method in PropertyStore and use it where possible

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs
Fixes #7799 (the main Issue containing a complete list of flaky tests)
Fixes #6597
Fixes #6739
Fixes #6926 (along with #8535)
- This fix omits check for `invalidatedCallCount` in unstable unit tests with a commentary reference to this Issue to keep a track record (as [proposed](https://github.com/dotnet/winforms/issues/6926#issuecomment-1246567369) by @RussKie).
- Theory data objects/inline data sets changed as well.
**Tests changed:**
- DataGridView_ColumnHeadersHeightSizeMode_SetNonResizeThenResize_RestoresOldValue
- DataGridView_ColumnHeadersHeightSizeMode_SetWithHandle_GetReturnsExpected
- DataGridView_ColumnHeadersHeight_SetWithHandle_GetReturnsExpected
- DataGridView_ColumnHeadersHeight_SetWithParentWithHandle_GetReturnsExpected
- …
> Removed extra validation in flaky DataGridView unit tests.

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
Fixes #8587
- Fix ToolsStrip.TabStop property value handling in calculating the next ToolStripItem to switch to.
- Modify unit tests to ensure GetNextItem method handles TabStop true value correctly.
- Arrow keys work correctly when navigation ToolStrip/MenuStrip/StatusStrip items from keyboard.
- No
- Minimal
Focus goes *right* on both Left and Right keys:
https://user-images.githubusercontent.com/113603457/217533909-e7af42f1-b48c-40e8-b670-bce1797ccac1.mp4
Focus goes *left* on Left key and *right* on the Right key:
https://user-images.githubusercontent.com/113603457/217534004-530e0969-86f0-4470-a9d9-60dd8a06362a.mp4
Tab and Shift+Tab navigation is not affected:
https://user-images.githubusercontent.com/113603457/217534084-6c900fa3-001e-4f39-8c21-6ba12f3df049.mp4
- Manual
- .NET …
> Fix ToolStrip/MenuStrip/StatusStrip arrow keys navigation

- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/AnchorLayoutTests.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DragDropTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComponentModel/Com2Interop/COM2PictureConverterTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/EmbeddedResourceTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
Related to:
#8602
#8601
#8598
#6610
> Skip or fix flaky tests blocking CI

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItem.cs
Fixes #8591
- Handle Up and Down keys in ToolStripDropDownItem class in case when item has no sub-items.
- Screen readers do not announce other controls when a user tries to open menu item without sub menu.
- No
- Minimal
When empty menu item is focused, Down key switches focus to form button:
https://user-images.githubusercontent.com/113603457/217564499-a7878c2e-ec87-4d39-ab1d-94eb4976b001.mp4
When empty menu item is focused, Down key does nothing, menu is still focused:
https://user-images.githubusercontent.com/113603457/217564561-48b9c782-3251-4aae-a9be-a7d976ac82c9.mp4
- Manual
- .NET 8.0.0-alpha.1.23057.5
> Fix menu item without sub menu leaking focus on arrow keys

- src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.VARIANT.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.PropertyBagStream.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.PropertyBagStream.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataStreamFromComStream.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHost.PropertyBagStreamTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ActiveXImplTests.cs
`PropertyBagStream` wasn't converting it's values correctly to/from string/object.
Also reinstate `BinaryFormatter` property handling which I removed under the misunderstanding that `BinaryFormatter` would be completely removed.
Add tests.
> Fix Control COM interface serialization

- eng/Localize/LocProject.json
Updating to match with what is generated. CI has been failing on Loc job for some time now.
Refer for failure info: https://dev.azure.com/dnceng/internal/_build/results?buildId=2109625&view=logs&j=c2111129-d6a3-58de-e667-00e5a0966c99&t=04624205-1088-500d-206a-392ceb108efa
`Existing LocProject.json differs from generated LocProject.json. Download LocProject-generated.json and compare them.`
> Fix localize job by updating the static LocProj.json

- src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs
The name of the class `PreviewPrintController` is misspelled in a debug message.
If a developer is searching the debug output for messages related to this class, this may not be found.
- None
- No
- None
> Fix spelling of debug message

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutPanelCellPosition.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutPanelCellPositionTypeConverter.cs
- Enable nullability in TableLayoutPanelCellPosition and TableLayoutPanelCellPositionTypeConverter
> Enable nullability in TableLayoutPanelCellPosition and TableLayoutPanelCellPositionTypeConverter

- src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs
We regressed this issue here: https://github.com/dotnet/winforms/pull/8486.
by accidentally disposing Icons that may not be owned or created by us. In this scenario, It was default Icon that is getting disposed.
Added unit test.
Fixes #8513.
> Prevent disposing Icons that are not owned by the caller.

- src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2TypeInfoProcessor.cs
Refactor `Com2TypeInfoProcessor` to replace Hashtable  with generic dictionary.
Related: #8143
> Refactor `Com2TypeInfoProcessor` to replace `Hashtable`

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/WindowsFormsSynchronizationContext.cs
- Enable nullability in WindowsFormsSynchronizationContext.
> Enable nullability in WindowsFormsSynchronizationContext

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItem.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
Fixes #8432
- Fire AutomationFocusChanged UIA-event after dropdown is closed
- When dropdown menu is opened, it's first item is automatically selected and AutomationFocusChanged UIA-event is fired. At this moment, check MenuStrip's AccessibilityObject, not DropDown's, because it might not be created yet
- Screen readers announce menu item selection on drop down first opening
- Screen readers announce focus returning back to menu item after dropdown closing
- No
- Minimal
https://user-images.githubusercontent.com/113603457/211337891-2b890e41-6d62-49cd-ba1a-e8251214c942.mp4
> .NET 8.0.0-alpha.1.23057.5 window, MenuStrip and CheckedListBox window, 
> Exit .NET 8.0.0-alpha.1.23057.5 window, Enter MenuStrip and CheckedListBox window, menuStrip1 menu bar, Project, menu item, collapsed, 
> …
> Fix MenuStrip item focus announcement when opening/closing dropdown menu

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
> Refactor `DataGridView.Methods` to remove `ArrayList` usage

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/BindingsCollection.cs
> Refactor BindingCollection to replace ArrayList with List<Binding>

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
> Refactor `ControlDesigner` to replace `ArrayList` with `List<T>`

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/BaseContextMenuStrip.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripItemDesigner.cs
> Refactor `BaseContextMenuStrip` to replace `ArrayList` with `List<T>`

- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
Fixes #8495 
Fixes #8489 
A condition check in Control.cs was incorrectly inverted. 
Originally the condition was : 
```c#
bool ready = !GetState(States.Created);
ready = ready && Visible;
if (ready || fIgnoreVisible)
{
// code...
}
```
and incorrectly inverted to : 
```c#
if (!ignoreVisible && !GetState(States.Created) && !Visible)
{
return;
}
// code...
```
Regression [commit](https://github.com/dotnet/winforms/pull/8398/commits/3fa23fdff157ff51402b3d591255549d153214d5#diff-07a0a87cedab0d76c974ce8b105912a1b986c87116c7ee0ac73d6d5d65e4b48a)
This meant that a control could go through `CreateControl()` codepath even though it is already created or visible leading to many unexpected behavior.
#8495 :  user control overrode `OnCreateControl()` with a call to `RecreateHandle()` (indirectly). …
> Fix Incorrect Conditional Check in CreateControl()

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/SelectionManager.cs
> Refactor `SelectionManager` to replace `Hashtable` with `Dictionary`

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/LocalizationCodeDomSerializer.cs
> Enable nullability and refactor `LocalizationCodeDomSerializer` to replace `Hashtable` with `HashSet`

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerHost.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/BasicDesignerLoader.cs
> Refactor `DesignerHost` to replace `ArrayList` with `List<T>`

- src/System.Windows.Forms.Design/src/System/Resources/Tools/StronglyTypedResourceBuilder.cs
> Refactor `StronglyTypedResourceBuilder` to replace `Hashtable` with `Dictionary`

- src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs
Fixes #4463 (partially, see also #8640)
- Introduces a new private property `DefaultHeight` with **the intended value** equals Winforms Control.DefaultFont.Height (for example in Windows.Forms it is **Segoe UI, Size 9, Height 16** by default).
- Removes the DefaultValue attribute from the `ListBox.ItemHeight` property;
- Implements `ResetItemHeight` and `ShouldSerializeItemHeight` methods ([see more](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/controls/defining-default-values-with-the-shouldserialize-and-reset-methods?view=netframeworkdesktop-4.8)).
- The ListBox.DefaultItemHeight constant marked as obsolete. The `ListBox.ItemHeight` is now depended on actual `DefaultFont.Height` value.
- The `ListBox.ItemHeight` property still returns the value of the  `_itemHeight` …
> Removed the DefaultValue attribute from ListBox.ItemHeight property

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowTests.cs
Fixes #4461
- Introduces a new private property `DefaultHeight` with **the intended value** (by default in Winforms Control.DefaultFont is **Segoe UI, Size 9, Height 16** which gives us **default Row height = 25**).
- Removes the DefaultValue attribute from the `DataGridViewRow.Height` property;
- Implements `ResetHeight` and `ShouldSerializeHeight` methods ([see more](https://learn.microsoft.com/en-us/dotnet/desktop/winforms/controls/defining-default-values-with-the-shouldserialize-and-reset-methods?view=netframeworkdesktop-4.8)).
- The `DataGridViewRow.Height` property still returns the value of the  `Thickness` property.
- Existing unit tests weren't changed.
- New unit test `DataGridViewRow_Height_NotEqualDefaultHeight_IfDefaultFontIsChanged` is added.
- Fixes the Issue which impacts …
> Removed DefaultValue attribute from the RowTemplate.Height property

- src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.ControlCollectionTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.TabPageCollectionTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs
- Use TabPage generic list instead of array in TabControl.
- Addresses some of the feedback in https://github.com/dotnet/winforms/pull/7316.
> Use TabPage generic list instead of array in TabControl

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.HitTestInfo.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.LayoutData.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewAdvancedBorderStyle.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewBand.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewButtonCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewButtonColumn.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellStyle.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxColumn.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumn.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnHeaderCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxColumn.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewImageColumn.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewLinkCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewLinkColumn.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowHeaderCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxColumn.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellStyleTests.cs
This changes span all the DataGridView-related files. A lot of the changes are about StringBuilder removal.
static code analysis
8.0.100-preview.1.23115.2
> Use interpolated strings in DataGridView

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignSurface.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignSurfaceManager.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.MethodLine.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.PropertyLine.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionUI.DesignerActionToolStripDropDown.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionUI.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/InheritanceService.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/InheritedPropertyDescriptor.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/MenuCommandService.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ReferenceService.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializer.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerBase.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CollectionCodeDomSerializer.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/EnumCodeDomSerializer.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/PrimitiveCodeDomSerializer.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/PropertyMemberCodeDomSerializer.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourceCodeDomSerializer.SerializationResourceManager.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourceCodeDomSerializer.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/UndoEngine.cs
Changes encompass all files in src/System.Windows.Forms.Design/src/System/ComponentModel/Design
There are more string.Format usages in the [`CodeDomSerializerBase.Trace`](https://github.com/dotnet/winforms/blob/190f292dbcaca33edbc7a0d5ac48ddcf31cf4627/src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerBase.cs#L491) method that I can remove in a follow-up PR using a custom interpolated string handler.
Static code analysis, CI
> Use interpolated strings in System.ComponentModel.Design

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripControlHost.ToolStripControlHostAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripControlHost.cs
- Enable nullability in ToolStripControlHost.
We seem to have many tests where we call `Dispose` and therefore `_control = null!;`. Since this is the only place where we set _control to null, what should we do? Update/remove the tests or make `_control` nullable? For example, in https://github.com/dotnet/winforms/pull/6404 we decided to use `_comStream = null!;` in Dispose.
> Enable nullability in ToolStripControlHost

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DragAssistanceManager.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/ResizeBehavior.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/SnapLine.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CollectionEditVerbManager.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CommandSet.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ComponentTray.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlCodeDomSerializer.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlCommandSet.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignBindingValueUIHandler.LocalUIItem.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerUtils.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DocumentDesigner.AxToolboxItem.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DocumentDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/EditorServiceContext.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/MaskDescriptor.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.CfCodeToolboxItem.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.ComponentDataObject.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ParentControlDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/StandardMenuStripVerb.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TabOrder.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TableLayoutPanelCodeDomSerializer.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripDropDownDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripItemDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripMenuItemDesigner.cs
Changes encompass all files in src/System.Windows.Forms.Design/src/System/Windows/Forms/Design
Static code analysis, CI
> Use interpolated strings in System.Windows.Forms.Design

- src/System.Windows.Forms/src/System/Windows/Forms/Application.ModalApplicationContext.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ApplicationContext.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ApplicationContextTests.cs
Contribute to https://github.com/dotnet/winforms/issues/6858.
This is continuation of https://github.com/dotnet/winforms/pull/6878 based on discussion.
Documentation for calling `GC.SuppressFinalize` on users subclasses also need to be updated some how...
The benefit of this change is not obvious like with `DataGridView`. The one I see is that `ModalApplicationContext` is never disposed after `ShowDialog` call, so it's ending up in Freachable queue.
Existing UT.
New UT for all subclasses coverage.
> Workaround for empty finalizer in ApplicationContext.

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerHost.DesignerHostTransaction.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerHost.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/UndoEngine.cs
Fixes #8728
Convert `Stack` usage to `Stack<T>` in DesignerHost and UndoEngine
> Replace Stack with Stack<T> across codebase

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
Method `CodeDomComponentSerializationService.Trace` is only called 5 times, including one time where it performs a useless check. I thought it would be simpler to just inline the method rather than adding a dedicated interpolated string handler.
> Inline CodeDomComponentSerializationService.Trace method

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/UndoEngine.cs
It's the same story as in #8743. This time I'm inlining a lot more calls though, around 15, so we're paying a higher cost to make the most of interpolated strings.
> Inline UndoEngine.Trace method

- src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Label.cs
- src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TextExtensions.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TextFormatFlags.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TextRenderer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemInternalLayout.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItemTextRenderEventArgs.cs
The problem was actually in ControlPaint.DrawStringDisabled that takes an IDeviceContext. In the big refactoring it lost the application of TextFormatFlags to decide whether or not to apply Graphics state. LinkLabel never set those flags historically so it didn't get the clipping it applied to the Graphics object applied to the HDC. Fix is to apply the flags properly.
I've also cleaned up the LinkLabel code and did a thorough pass of the TextExtensions to bring the code up to snuff.
Fixes https://github.com/dotnet/winforms/issues/7341
> Fix disabled text label rendering.

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/Drawing/Design/ColorEditor.ColorPalette.ColorPaletteAccessibleObject.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.ControlDesignerAccessibleObject.cs
- Enable nullability in ColorPaletteAccessibleObject and ControlDesignerAccessibleObject
> Enable nullability in ColorPaletteAccessibleObject and ControlDesignerAccessibleObject

- src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ByteViewerTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Handlers.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/GroupBoxTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PaintEventArgsTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollableControlTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/StatusStripTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TableLayoutPanelTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripButtonTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripContentPanelTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripControlHostTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripSeparatorTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.Rendering.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/UpDownBaseTests.cs
- Dispose PaintEventArgs in tests.
> Dispose PaintEventArgs in tests

- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Dpi/ToolStripItemTests.Dpi.cs
- Locally, the tests are failing for me and it looks like it is because we are using `DpiHelper.LogicalDpi` which is always `96.0`. I used `Form.DeviceDpi` instead.
> Fix ToolStripItems_FontScaling tests

- src/System.Drawing.Common/src/System.Drawing.Common.csproj
- src/System.Drawing.Common/src/packaging.targets
Use the floating TFM properties defined in Arcade
Enable ApiCompat's optional rules
Remove obsolete commentMinor clean-up from Drawing migration
> Minor clean-up from Drawing migration

- src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/Mocks/MockCursor.cs
- src/System.Windows.Forms/src/Resources/SR.resx
- src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
- src/System.Windows.Forms/src/System/Windows/Forms/Cursor.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Cursors.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CursorTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CursorsTests.cs
While investigating flaky tests, found that Cursor Handle is being set to null even if the cursor is not owned by the specific scope. This has been the case since .NET framework. Disposing handle only if owned by creator. 
Some static Cursors in WinForms are incorrectly categorized as `owned`. Making any change around `owned` flag on these could break existing applications. In this change, we are recreating static cursors if their handle is disposed.
Related #8810 
fixes #8373
> Dispose Cursor only if it is owned by the creator.

- src/System.Windows.Forms/src/System/Windows/Forms/Form.EnumThreadWindowsCallback.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FormTests.cs
Should be storing the child, not the parent.
Fixes #8803
> Repopulate owner HWNDs correctly

- src/Common/src/TraceSwitchExtensions.cs
As stated in #8715, TraceSwitchExtensions.TraceVerbose doesn't handle interpolated strings despite replacing code that does (`Debug.WriteLineIf`). This is a proposed fix. Note that unlike `Debug.WriteIfInterpolatedStringHandler`, which is an obvious inspiration to this PR, we don't pull (yet?) `StringBuilder` instances as the caching mechanism is internal to corelib.
> Add interpolated string handler to TraceSwitchExtensions.TraceVerbose

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CursorConverterTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CursorTests.cs
> Dispose Cursor in tests

- eng/custom-cibuild.ps1
- src/System.Windows.Forms.Primitives/src/NativeMethods.txt
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs
- Close ServerManager window on build agents that may interfere with UI tests.
- Take screenshots and save them in case any UI test fails.
> Close ServerManager window on build agents and save screenshot in UI test failures.

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializer.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerBase.TraceIfInterpolatedStringHandler.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerBase.TraceInterpolatedStringHandler.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerBase.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CollectionCodeDomSerializer.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ComponentCodeDomSerializer.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ContainerCodeDomSerializer.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/EnumCodeDomSerializer.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/EventMemberCodeDomSerializer.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/PrimitiveCodeDomSerializer.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/PropertyMemberCodeDomSerializer.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourceCodeDomSerializer.SerializationResourceManager.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourceCodeDomSerializer.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/TypeCodeDomSerializer.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlCodeDomSerializer.cs
This one is more involved than the previous ones. Here, we remove all the format-string overloads of the (internal) `CodeDomSerializerBase.Trace*` methods to replace them with interpolated-string-accepting ones.
If you think the changes are too big, I can add the new overloads and port the code to them over multiple PRs
> Refactor CodeDomSerializerBase.Trace methods for string interpolation

- src/System.Drawing.Common/src/System/Drawing/GdiplusNative.cs
- src/System.Drawing.Common/src/System/Drawing/Graphics.cs
- src/System.Drawing.Common/tests/mono/System.Drawing/GraphicsTests.cs
- src/System.Drawing.Common/tests/mono/System.Imaging/MetafileTest.cs
Adds `ReadOnlySpan<char>` overloads to `Graphics.DrawString`, `MeasureCharacterRanges`, and `MeasureString`.
Cleaned up docs for these methods as well and called span/string overloads in existing tests.
Fixes: #8844
cc: @ericstj, @ViktorHofer, @carlossanlop
> Add Span overloads for Graphics text methods

- eng/Version.Details.xml
- eng/Versions.props
Contributes to https://github.com/dotnet/windowsdesktop/pull/3516
Unblocks https://github.com/dotnet/wpf/pull/7681
Microsoft.Windows.Compatibility is being migrated from runtime to windowsdesktop and depends on packages from dotnet/runtime. As there's already a subscription from `runtime -> winforms`, a new one can't be added directly between `runtime -> windowsdesktop` as that would cause coherency issues. Instead, we need to flow the dependencies through winforms and wpf.
The `git diff` is confusing. I just added the new dependencies at the end of the product dependencies section and removed the ones that already existed from above so that all the ones that are required by windowsdesktop are grouped together.
Note that I also removed the `Microsoft.Windows.Compatiblity` dependency as …
> Add dependencies required by windowsdesktop

- src/Common/tests/TestUtilities/AppContextSwitchNames.cs
- src/Common/tests/TestUtilities/AppContextSwitchScope.cs
- src/Common/tests/TestUtilities/BinaryFormatterScope.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
- src/System.Windows.Forms/tests/UnitTests/SerializableTypesTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceReaderTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHost.PropertyBagStreamTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ActiveXImplTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageList.NativeImageListTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageListStreamerTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageListTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Layout/TableLayoutSettingsTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewSubItemTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/OwnerDrawPropertyBagTests.cs
- src/System.Windows.Forms/tests/UnitTests/runtimeconfig.template.json
Adds the `BinaryFormatterScope` ref struct for explicitly setting `BinaryFormatter` enabled state.
Ran through System.Windows.Forms.Tests with the `BinaryFormatter` explicitly disabled to identify tests that were dependent and add the context to said tests.
The intent is to follow this change with additional changes to do the same for the other test assemblies. I'll be using what I find here to open additional issues or add additional context to existing ones. For example, it wasn't clear that CSV text uses the `BinaryFormatter` for the clipboard until I ran through this set of tests.
After all assemblies are scoped I'll be then looking to close test gaps.
> Add AppContext switch scope functionality

- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Buttons.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Program.cs
Change the main form icon to a stock icon and add a button using a stock icon to get some manual usages of the new System.Drawing API.
> Add a couple stock icon usages to controls test

- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/ArgumentValidation.cs
The null-checking extension methods defined in ArgumentValidation are lacking an annotation stating that the first argument is checked for null. This PR adds it back.
> Fix nullability of ArgumentValidation class

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/DesignerSerializationManager.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/Serialization/DesignerSerializationManagerTests.cs
Refactor dictionary usage to use `TryGetValue`.
Addresses feedback from:
https://github.com/dotnet/winforms/pull/8353#issuecomment-1443195430
> Refactor `DesignerSerializationManager` dictionary usage to use `TryGetValue`

- eng/CodeAnalysis.test.globalconfig
- eng/CodeStyle.targets
All duplicate items have been removed, leaving only the unique configuration for tests. The specific configuration behavior is not changed.
> Use CodeAnalysis.test.globalconfig only for overrides

- src/System.Drawing.Common/src/Interop/Windows/User32/Interop.GetDC.cs
- src/System.Drawing.Common/src/System/Drawing/Font.cs
- src/System.Drawing.Common/src/System/Drawing/Graphics.cs
- src/System.Drawing.Common/tests/BitmapTests.cs
- src/System.Drawing.Common/tests/BrushTests.cs
- src/System.Drawing.Common/tests/FontTests.cs
- src/System.Drawing.Common/tests/GraphicsTests.cs
- src/System.Drawing.Common/tests/Imaging/ImageAttributesTests.cs
- src/System.Drawing.Common/tests/Imaging/ImageFormatTests.cs
- src/System.Drawing.Common/tests/PenTests.cs
- src/System.Drawing.Common/tests/System.Drawing.Common.Tests.csproj
- src/System.Drawing.Common/tests/mono/System.Drawing/BitmapTests.cs
- src/System.Drawing.Common/tests/runtimeconfig.template.json
- src/System.Windows.Forms.Primitives/tests/TestUtilities/PlatformDetection.Windows.cs
`[KnownIssue]` doesn't actually skip tests in the Test Explorer. This change fixes the tests that were "skipped" and actually failing.
- GDI+ no longer accepts negative pen widths
- Some tests were ported from Mono and skipped as they validated Mono's behavior, not GDI+
- Graphics.CopyFromScreen would call ReleaseHDC even if GetHDC was not called.
- CopyFromScreen assumed -1, -1 was an invalid screen coordinate. Not true for multimonitor.
- SetNativeBrush tests should not be disposing the invalid handle- random badness will occur.
- Prevent using a Graphics object with a null pointer in Font.GetHeight (to avoid AV).
I've also disabled the BinaryFormatter by default for these tests.
> Handle a few skipped test failures in System.Drawing

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewBand.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumn.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewElement.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewHeaderCell.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewElementTests.cs
Rework of empty finalizers fix in DataGridView due to [this discussion](https://github.com/dotnet/winforms/pull/7431#issuecomment-1423140820).
Also added a benchmark for clarity.
- `HashSetB` - previous variant where types were in `HashSet`.
- `GetTypeB` - new variant with `if (GetType() == typeof(DataGridViewBand) || GetType() == typeof(DataGridViewColumn) ...`
- `GetTypeVarB` - `var t = GetType(); if (t == typeof(D1) || t == typeof(D2) ...`
- `HelperMB` - helper method `NeedSuppressFinalize(Type t)` with `return t == typeof(E1) || t == typeof(E2) ...`
[Bench.zip](https://github.com/dotnet/winforms/files/11129968/Bench.zip)
> Rework of empty finalizers fix in DataGridView

- src/System.Windows.Forms/src/System/Windows/Forms/Form.EnumThreadWindowsCallback.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FormTests.cs
Porting #8870 
and
Fixes #8803
When a Form's handle is recreated it looks for child Windows so it can update them with the new handle. The list of child windows was mistakingly storing the parent handle instead of the child handle.
In the reported case, the parent form was created while the child form was still in CreateWindow. After parenting against the child a property was set that caused recreation of the parent's handle. As the handle reparenting logic was broken the child would be left with an invalid parent window handle, causing CreateWindow to return and error and WinForms would throw an unhandled exception.
> Servicing:  Repopulate owner HWNDs correctly

- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ButtonTests.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DataGridViewTests.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DesignBehaviorsTests.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DragDropTests.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/IMouseSimulatorExtensions.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/RichTextBoxTests.cs
* Wait for WM_MOUSEMOVE processing before sending more messages.
* Match WM_LBUTTONDOWN with WM_LBUTTONUP
Closes #6609
Closes #6714
Closes #7297
Closes #7407
Closes #8635
> Update tests to use DragMouseBy and DragMouseTo

- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ScreenshotService.cs
I was really surprised that all the resources on this topic online use `Graphics.CopyFromScreen`, but seem to complicate the cursor drawing.
> Draw the cursor on screenshots

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/MultilineStringEditor.MultilineStringEditorUI.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.MetafileDCWrapper.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.PageSelector.cs
- src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarButtonAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
This is a simplification of some code using a computed property instead of calculating the value in-line.
> Use Width and Height properties where applicable

- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/RichTextBoxTests.cs
Many of the integration tests move the mouse as part of the test implementation. This change updates the base control helper to record the mouse position at the start of the test and restore it at the end.
I verified locally that this implementation works even when the mouse is initially on a different monitor in multi-monitor configurations.
> Restore the cursor position at the end of each integration test

- src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DpiChangedEventArgs.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewInsertionMark.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewLabelEditUiaTextProvider.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/MonthCalendarTests.cs
An implicit conversion `RECT` &lrarr; `Rectangle` already existed in code. This change simplifies code manually converting between these types to instead rely on this operator.
> Simplify code using RECT/Rectangle conversions

- eng/pipelines/build.yml
Re-runs just the integration test step up to one more time if a test failure occurs. Helps prevent flakiness in the system from impacting CI runs, but doesn't have any impact on developer scenarios.
> Automatically retry integration tests on failure

- eng/pipelines/build.yml
Logs for #8952 showed copies of **mscorsvw** running in the background. This change pauses the NGEN queue to prevent **mscorsvw** from consuming CPU and potentially interfering with the integration tests.
> Pause NGEN to avoid CPU interference during the run

- src/System.Drawing.Common/src/Interop/Windows/Shell32/Interop.SHDefExtractIcon.cs
- src/System.Drawing.Common/src/Interop/Windows/Shell32/Interop.SHGetStockIconInfo.cs
- src/System.Drawing.Common/src/Resources/Strings.resx
- src/System.Drawing.Common/src/System.Drawing.Common.csproj
- src/System.Drawing.Common/src/System/Drawing/Icon.cs
- src/System.Drawing.Common/src/System/Drawing/SystemIcons.cs
- src/System.Drawing.Common/tests/IconTests.cs
- src/System.Drawing.Common/tests/SystemIconsTests.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Buttons.cs
This adds Icon.Extracticon to allow extracting icons from icon files and native resources from PE files at any specified resolution.
Also adds an overload to SystemIcons.GetStockIcon() to get a specified size.
Fixes #8929
> Add ExtractIcon functionality to Icon

- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/MonthCalendarTests.cs
Matches other click operations in both production code and tests.
> Use the cell center in MonthCalendarTests

- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridToolStripButton.PropertyGridToolStripButtonAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripButton.ToolStripButtonAccessibleObject.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolStripTests.Designer.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridToolStripButton.PropertyGridToolStripButtonAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripButton.ToolStripButtonAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripMenuItem.ToolStripMenuItemAccessibleObjectTests.cs
Fixes #8961
* Added Toggle pattern support for ToolStripButton
* Disabled pattern support for PropertyGridToolStripButton (e.g. "Categorized", "Alphabetical" buttons on a PropertyGrid) because they may have `Checked = true`, but will not behave like a toggle button in that case. Instead they behave like radio buttons and screen readers already announce their selected state
* Added unit tests
* Added `TabStop = true` for tool strips on a test form to make them selectable via keyboard for easier testing. The form already contained ToolStripButton-s with different checked states so there was no need to add it.
- Screen readers will announce toggle state of a checkable `ToolStripButton`
- No
- Minimal
- Unit tests
Screen reader announcements for a ToolStrip with following …
> Add UIA Toggle pattern to ToolStripButton

- src/System.Drawing.Common/src/System.Drawing.Common.csproj
- src/System.Drawing.Common/src/System/Drawing/GdiplusNative.cs
- src/System.Drawing.Common/src/System/Drawing/Graphics.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/CachedBitmap.cs
- src/System.Drawing.Common/tests/GraphicsTests.cs
- src/System.Drawing.Common/tests/Imaging/BitmapDataTests.cs
- src/System.Drawing.Common/tests/Imaging/CachedBitmapTests.cs
- src/System.Drawing.Common/tests/System.Drawing.Common.Tests.csproj
Implements GDI+ `CachedBitmap` wrapper which allows caching a device dependent copy of `Bitmap`. Rendering is signficantly faster (5x+), although it has a few caveats:
- It needs to be regenerated if color depth changes
- It cannot be rendered to a Graphics object that has a tranform other than translation (no rotation, scaling)
Fixes #8822
> Implement CachedBitmap

- src/System.Windows.Forms/src/System/Windows/Forms/AutoCompleteStringCollection.cs
Fixes #9008
Regression was introduced in https://github.com/dotnet/winforms/pull/8142 (from .NET 8). Replacing cast to be similar to other `CopyTo` overrides, for example:
https://github.com/dotnet/winforms/blob/024a9ab98d4bea535ce9fe6c473326bcd00464b7/src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellCollection.cs#L48
https://github.com/dotnet/winforms/blob/024a9ab98d4bea535ce9fe6c473326bcd00464b7/src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutStyleCollection.cs#L130
- Replace invalid cast to string[] with cast to ICollection
- AutoCompleteCustomSource property can be edited
- Yes
- Minimal
- Manual
- .NET 8.0.100-preview.4.23218.21
> Fix error dialog on editing AutoCompleteCustomSource in PropertyGrid

- src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.Vista.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.cs
- src/System.Windows.Forms/src/System/Windows/Forms/SaveFileDialog.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FileDialogTests.cs
We weren't releasing the native dialog classes we create. Use scopes and don't throw/catch, just return if we're unable to create the dialog.
> Ensure the native dialogs are released

- src/System.Windows.Forms/tests/AccessibilityTests/Menu_Toolbars_controls.Designer.cs
Fixes part of [9005](https://github.com/dotnet/winforms/issues/9005)
Add ToolStripMenuItems and ToolStripButtons to cover different checked combinations.
Easier to test CheckState values of ToolStripMenuItems and ToolStripButtons from winforms repo
No
None
Manual
Narrator announce:
Unchecked_CheckOnClick(F), button, 
Unchecked_CheckOnClick(F)
Unchecked_CheckOnClick(T), button, off, 
Unchecked_CheckOnClick(T)
Checked_CheckOnClick(T), button, on, 
Checked_CheckOnClick(T)
Checked_CheckOnClick(F), button, on, 
Checked_CheckOnClick(F)
Indeterminate_CheckOnClick(T), button, indeterminate, 
Indeterminate_CheckOnClick(T)
Indeterminate_CheckOnClick(F), button, indeterminate, 
Indeterminate_CheckOnClick(F)
CheckState Samples, menu item, collapsed, <say-as interpret-as="spell">5</say-as> of <say-as …
> Add checked ToolStripMenuItems and ToolStripButtons to Accessibility App

- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
Created bitmap wasn't being released.
Fixes #9028
> Fix bitmap leak in GridEntry

- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/TaskDialog.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TaskDialogLinkClickedEventArgs.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TaskDialogPage.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/TaskDialogSamples.cs
Closes #1199
- Exposes the Windows Task Dialog API in regard to enabling hyperlinks to be shown (TDF_ENABLE_HYPERLINKS) and hyperlink clicks to be reacted to (TDN_HYPERLINK_CLICKED). This is conceptually 1:1 with the underlying Windows API and does not contain code that interprets or executes the contents of hrefs.
- Customers who show task dialogs containing links are unable to move to the new Windows Forms API, away from handwritten implementations or community libraries for TaskDialog which have fewer capabilities in other regards than the Windows Forms API.
- No
- Minimal; this feature is opt-in, and behavior without opting in remains the same as without this feature being implemented.
- A new Task Dialog demo is added along with the existing ones, putting all aspects of this feature …
> Implement task dialog hyperlink proposal

- src/System.Windows.Forms.Design/tests/UnitTests/System/Resources/Tools/StronglyTypedResourceBuilderTests.cs
- src/System.Windows.Forms/src/System/Resources/ResXResourceReader.cs
- src/System.Windows.Forms/tests/TestUtilities/ResxHelper.cs
- src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceReaderTests.cs
Fixes #8295 
- Added additional unit tests for System.Resources.ResXResourceReader 
- Constructors
- GetEnumerator()
- GetMetaDataEnumerator
- None
- No
- Low
- PR only has unit tests
> Issue/8295 - Added additional unit tests to System.Resources.ResXResourceReader

- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/TaskDialogSamples.cs
Replace manual coordinate calculation with autosizing with FlowLayoutPanel so that the contributor samples window is readable on systems with high-DPI settings.
- Makes no difference to customers, only contributors to the repository.
- Not that I know of
- None, does not affect shipping code
> Make task dialog sample menu window readable on high-DPI settings

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripRenderer.cs
Null check should be explicit to avoid further access of the Item object. It is not uncovered until we enabled PermonV2 mode for the designer.
Fixes #[5125](https://github.com/microsoft/winforms-designer/issues/5125)
Fixes #[5124](https://github.com/microsoft/winforms-designer/issues/5124)
> Fix null reference in PermonV2 mode.

- src/System.Windows.Forms/src/System/Windows/Forms/ContextMenuStrip.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItem.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.cs
Fixes #9044
There are two problems we're facing when trying to scale `ContextMenuStrip`:
1. `ContextMenuStrip `is a top level window and thus only receive "WM_DPICHANGED" message but not WM_DPICHANGED_BEFOREPARENT/WM_DPICHANGED_AFTERPARENT.  Unfortunately, we do not handle scaling of controls in "WM_DPICHANGED" message. In WinForms, "WM_DPICHANGED" message is intended for Top-level Forms/ContainerControls.              As a result, the `ContextMenuStrip `window doesn't scale itself when moved from one monitor to another on the "PerMonitorV2" process.
2. When `ContextMenuStrip `changes to invisible (with "visible" set to false), owner of the window is changed to a `ParkingWindow `that may possibly be parked on primary monitor. The `GetDpiForWindow()` API on `ContextMenuStrip` thus returns …
> Scale ContextMenuStrip for high DPI devices

- eng/pipelines/build.yml
Do not run tests (Unit and integration) on internal CI.
We run tests against PRs and i do not see a reason why we need to repeat them against internal CI. Few repos already opted out running tests on internal CI. (ex: WPF, SDK and installer).
I am also blocking our ARM64 tests until we get specific pool for ARM64 or move to Helix. They currently are simply using X64.
> Do not run tests on internal CI

- .github/fabricbot.json
Clearing intermediate labels once the issue is resolved/closed.
> Remove intermidiate label from closed issues

- src/System.Windows.Forms.Primitives/src/NativeMethods.txt
- src/System.Windows.Forms.Primitives/src/Windows/Win32/Pinvoke.RegLoadMUIString.cs
- src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
- src/System.Windows.Forms/src/System/Windows/Forms/RegistryKeyExtensions.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/InputLanguageTests.cs
I have extracted part of #8573 into separate PR until decision is made on some aspects of that PR.
- Use `RegLoadMUIString` instead of the `SHLoadIndirectString` API as recommended at https://learn.microsoft.com/windows/win32/intl/locating-redirected-strings#load-a-language-neutral-registry-value
- Move InputLanguage `GetKeyboardLayoutNameForHKL` method implementation to the internal `LayoutId` property (to ease debugging)
- Added proper testing of InputLanguage.LayoutName
- Added InputLanguage_Culture_ThrowsArgumentException and InputLanguage_LayoutName_UnknownExpected tests
- Use `PARAM.ToInt` instead of casts in `GetHashCode` implementation
- Shouldn't have any visible customer impact
- No
- Little
Auto test:
- InputLanguage_InputLanguageLayoutId_Expected (updated)
- …
> InputLanguage: Use RegLoadMUIString instead of SHLoadIndirectString API

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/AutoCompleteStringCollection.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AutoCompleteStringCollectionTests.cs
- Enable nullability in AutoCompleteStringCollection.
> Enable nullability in AutoCompleteStringCollection

- src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceWriterTests.cs
Adds to #8295 - Added tests to ResXResourceWriter
- Additional unit tests for ResXResourceWriter
- None
-  No
- Low
- PR only has unit tests
- Successful Unit Tests
> 8295 - ResXResourceWriterTests

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewRowCollectionCodeDomSerializer.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Message.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.SelectionScope.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.SetBkModeScope.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.SetMapModeScope.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.SetRop2Scope.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.SetTextAlignmentScope.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.SetTextColorScope.cs
- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/Layout/CommonProperties.cs
- src/System.Windows.Forms/src/System/Windows/Forms/MDIWindowDialog.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TextRenderer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.ToolStripPanelRowCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.VerticalRowManager.cs
- Enable nullability in ToolStripPanelRowCollection.
- Remove some unnecessary DEBUG pre-processor checks.
> Enable nullability in ToolStripPanelRowCollection and remove some unnecessary DEBUG pre-processor checks

- src/System.Windows.Forms.Design/src/System/Drawing/Design/ColorEditor.CustomColorDialog.cs
- Enable nullability in CustomColorDialog.
> Enable nullability in CustomColorDialog

- src/System.Windows.Forms/src/System/Windows/Forms/HtmlToClrEventProxy.cs
- Enable nullability in HtmlToClrEventProxy.
> Enable nullability in HtmlToClrEventProxy

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItemCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSettingsManager.cs
- Enable nullability in ToolStripItemCollection.
> Enable nullability in ToolStripItemCollection

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.ToolStripPanelRowControlCollection.cs
- Enable nullability in ToolStripPanelRowControlCollection.
> Enable nullability in ToolStripPanelRowControlCollection

- src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.VARIANT.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/BinaryFormatReader.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/BinaryFormatWriter.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/BinaryFormattedObject.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/BinaryFormattedObjectExtensions.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/ClassRecord.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/MemberPrimitiveTyped.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/MemberTypeInfo.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/Record.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/System/Com/CY.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/System/Com/StructuredStorage/PropertyBagExtensions.cs
- src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/BinaryFormat/HashTableTests.cs
- src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/BinaryFormat/ListTests.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.PropertyBagStream.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.State.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.PropertyBagStream.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHost.PropertyBagStreamTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ActiveXImplTests.cs
The PropertyBags now serialize without it where possible. This allows a standard Control to completely serialize without the BinaryFormatter enabled.
For the AxHost case, I've left the BinaryFormatter as a fall-back.
I've also extended the Hashtable serialization to handle all primitive types. Note the two line change to make this happen. :)
This change also moves the "Reader" methods to "BinaryFormattedObjectExtensions". Due to our layering and the need to check multiple states I realized that we need to have all of the reading of objects directly using an existing BinaryFormattedObject instance.
Fixes a few bugs and adds more tests. Some random cleanup related to VARIANT (as I was exploring the scope of things).
> Move away from BinaryFormatter for ActiveX purposes

- src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
fixes #8946 
fixes #9004
By default, control handles are created with the DPI (dots per inch) of the primary monitor. If we assign an owner or parent to a control that is not on the primary monitor and has a different DPI than the primary monitor, it may trigger a DPICHANGED event. This situation leads to issues linked above.
When the DPICHANGED event occurs, we adjust the font and scale the control according to the new DPI. However, if the child control is a top-level window and explicitly or by default placed on the primary monitor, it generates another DPICHANGED message within the first one, causing the scaling process to repeat. This behavior is expected. The problem arises from the current order in which we attempt to scale the font and the control itself. We encounter the second …
> Update/Scale Font on each DPICHNAGED message

- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/BinaryFormatWriter.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/ClassWithMembersAndTypes.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/MemberTypeInfo.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/SystemClassWithMembersAndTypes.cs
List<T> isn't necessary here. Using params and arrays directly saves some memory and makes writing in the binary format more succinct.
Made a few arrays lazy to save a little memory bloat.
> Use array[] and params array[]

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.SplitButton.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.EditorPropertyLine.EditorButton.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.EditorPropertyLine.cs
- Enable nullability in classes that inherit from Button in System.Windows.Forms.Design.
> Enable nullability in classes that inherit from Button in System.Windows.Forms.Design

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripButton.ToolStripButtonAccessibleObject.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolStripTests.Designer.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripButton.ToolStripButtonAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripButtonTests.cs
Fixes #9108
* Changed ControlType for checkable/checked `ToolStripButton` from `Button` to `CheckBox` to allow having both Toggle and Invoke patterns. We cannot remove Invoke pattern for compatibility reasons, and Toggle pattern is needed to announce checked state. This is done by removing hardcoded `Button` type.
* Extend condition on which accessible object will get `CheckButton` role to include buttons with only `Checked = true` (without `CheckOnClick = true`), so that screen readers can also announce it as "checked";
* Allow setting custom role even if button is checkable/checked. For instance, this enables setting `RadioButton` role for `PropertyGridToolStripButton`, which can have `Checked = true` but shouldn't have `CheckBox` type because it doesn't behave like one.
- No errors in …
> Fix ToolStripButton errors in Accessibility Insights

- src/System.Windows.Forms/src/System/Windows/Forms/PrintPreviewControl.PrintPreviewControlAccessibleObject.cs
Fixes #8892
- Override `AccessibleObject.Bounds` property for `PrintPreviewControlAccessibleObject`
- No
- Mininmal
- NET 8.0.0-preview.4.23259.5
- Accessibility Insights 1.1.2213.1
> Fixed PrintPreviewControlAccessibleObject.Bounds

- src/System.Windows.Forms.Primitives/src/System/Collections/Generic/ListConverter.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/BinaryFormatWriter.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/BinaryFormattedObjectExtensions.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/BinaryLibrary.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/ClassWithMembersAndTypes.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/MemberPrimitiveTyped.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/Record.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/Support/ListConverter.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/Support/StringRecordsCollection.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/Support/TypeInfo.cs
- src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/BinaryFormat/ArrayTests.cs
- src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/BinaryFormat/BinaryFormatWriterTests.cs
- src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/BinaryFormat/ListTests.cs
- src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/BinaryFormat/NullTests.cs
- src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/BinaryFormat/PrimitiveTypeTests.cs
- src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/BinaryFormat/StringRecordsCollectionTests.cs
- src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/BinaryFormat/SystemDrawingTests.cs
Now have saving/reading from object for supported types. This will allow plugging in more generically for property and resource serialization.
- Adds support for Array, ArrayList, and PointF/RectangleF.
- Tweaks ListConverter<T> to support more usages
- Create primitive ListConverter<T> helper in ListConverter static class.
- Have StringRecordsCollection maintain id to allow ListConverter helper above.
- Move type info into TypeInfo class.
Next step is hooking into IPropertyBag Control serialization and ResxDataNode.
> Complete binary format object round-tripping

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PrintPreviewControl.PrintPreviewControlAccessibleObjectTests.cs
Fixes #8892
This is a follow-up to PR #9136
- Add a unit test to ensure `PrintPreviewControlAccessibleObject.Bounds` is calculated correctly
- No
- Minimal
- NET 8.0.0-preview.4.23259.5
> Add a unit test for PrintPreviewControlAccessibleObject.Bounds property

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripButton.ToolStripButtonAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripButton.cs
Fixes #9137
- Fire ToggleStatePropertyChanged UIA event when ToolStripButton's `CheckState` changes.
- Screen readers announce checked state change of ToolStripButton
- No
- Minimal
https://github.com/dotnet/winforms/assets/113603457/525781bb-2a75-4fe2-8fe8-ab863141f90c
Narrator output:
> ToolStripTests window, toolStrip1 tool bar, Checkable button (unchecked) check box unchecked,
Notice that nothing is announced when button is checked or unchecked.
https://github.com/dotnet/winforms/assets/113603457/c986f680-aecb-4754-9de5-50f9b2f4e2c2
Narrator output:
> ToolStripTests window, toolStrip1 tool bar, Checkable button (unchecked) check box unchecked,
> checked
> unchecked
> checked
> unchecked
- ,NET  8.0.0-preview.4.23259.5
> Added ToggleStatePropertyChanged UIA event for ToolStripButton.

- src/System.Windows.Forms/src/System/Windows/Forms/PrintPreviewControl.PrintPreviewControlAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PrintPreviewControl.PrintPreviewControlAccessibleObjectTests.cs
Fixes #9175
PR #9136 has changed calculation of `AccessibilityObject.Bounds` property of `PrintPreviewControl` to include non-client area of the control. That fixed bounds of UIA object but broke MSAA object.
This PR modifies calculations to make bounds correct in both MSAA and UIA modes.
- Override PrintPreviewControlAccessibleObject's `BoundingRectangle` instead of `Bounds`.
- Fix unit tests for `PrintPreviewControlAccessibleObject.Bounds` property.
- Add unit tests for `PrintPreviewControlAccessibleObject.BoundingRectangle` property.
- Yes
- Minimal
Before PR #9136 MSAA client  and non-client bounds were correct, but UIA bounds were too small.
MSAA non-client bounds:
MSAA client bounds:
UIA bounds:
PR #9136 fixed UIA bounds, but broke MSAA client bounds, which now include non-client …
> Fixed PrintPreviewControl accessibility bounds calculation

- src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/BinaryFormat/HashTableTests.cs
- src/System.Windows.Forms/src/System/Resources/ResXDataNode.cs
- src/System.Windows.Forms/src/System/Resources/ResXSerializationBinder.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataFormats.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataObject.BitmapBinder.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataObject.OleConverter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
- src/System.Windows.Forms/src/misc/MultitargetUtil.cs
- src/System.Windows.Forms/tests/UnitTests/System/Resources/ResxDataNodeTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ActiveXImplTests.cs
This uses the BinaryFormat support classes to handle common framework types before falling back to the BinaryFormatter.
There is some cleanup in the Resx code and simplification in DataObject by adding internal constant strings for known DataFormats.
Also move MultitargetUtil to the normal CriticalException handler.
> Hook BinaryFormatter replacement in Resx / Clipboard

- src/System.Windows.Forms.Primitives/src/NativeMethods.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataObject.OleConverter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs
The OleConverter class had significant readability issues. This brings it closer to standard and cuts over 100 lines of code. Getting the code into better shape is important with BinaryFormatter changes and the need to move this to ComWrappers moving forward.
Recommend reviewing split.
Notable bits:
- The class is never derived, and is now sealed
- Members that do nothing now clearly do nothing (write methods)
- Moved some single call methods inline callees
The name isn't great so I'm going to follow up with a change to ComDataObjectAdapter for increased clarity.
Also add a few tests related to #9180.
> Clean up OleConverter code

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.HorizontalRowManager.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.VerticalRowManager.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripPanelRow.ToolStripPanelRowControlCollectionTests.cs
- Add test from https://github.com/dotnet/winforms/issues/9126
- Remove unused controlToPushAside variable
> Remove unused controlToPushAside variable

- src/System.Windows.Forms/src/System/Windows/Forms/DataObject.ComDataObjectAdapter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs
Following logic should be significantly easier now.
- Move methods inline in ComDataObjectAdapter
- Make methods static and pass in state
- Move a few methods inlinein DataObject
- Use Span to save filelist
- Use HGLOBAL terms
> Final round of clipboard cleanup

- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/BinaryFormatWriter.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/BinaryFormattedObjectExtensions.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/BinaryObjectString.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/Support/TypeInfo.cs
- src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/BinaryFormat/ExceptionTests.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataObject.BitmapBinder.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataObject.ComDataObjectAdapter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataObject_BitmapBinderTests.cs
Windows swallows all errors when getting data for the clipboard. This was resulting in seeming success, but a return of a null when trying to get the data out (as the data would be invalid and we would swallow that error on data retrieval).
There aren't great answers to this. To give some indication of the source of the failure I've implemented binary format support for NotSupportedException and put that on the clipboard if we need the BinaryFormatter.  Getting the value will give this object, with the message that the BinaryFormatter is disabled.
While we could check on settting the data it would involve deserializing to see that it is what is on the clipboard. I don't want to take that performance hit for every (normally working) usage of the clipboard.
cc @GrabYourPitchforks
> Handle BinaryFormatter being disabled with the Clipboard

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ContextMenuStripActionList.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.DockingActionList.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerActionVerbList.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ListControlUnboundActionList.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ListViewActionList.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/MaskedTextBoxDesignerActionList.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/PictureBoxActionList.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/RichTextBoxActionList.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TextBoxActionList.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripActionList.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TreeViewActionList.cs
- Enable nullability in classes that inherit from DesignerActionList.
> Enable nullability in classes that inherit from DesignerActionList

- eng/pipelines/build.yml
> [Release/6.0] Disable tests on internal CI or ARM64

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ControlAccessibleObjectTests.cs
Extend test for Fixes #9164 
- Add test "ControlAccessibleObject_DoesNotRootControls_AllPublicControl" to cover all Accessible objects that use weak referenced public controls to be successfully collected
- No
- Minimal
- Unit tests
- dotnet 8.0.100-preview.6.23304.3
> Extend test for pr#9164

- src/System.Windows.Forms/src/System/Windows/Forms/Label.LabelAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Panel.PanelAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ControlAccessibleObjectTests.cs
- Update the control owning field of Label and Panel to using weak references
- Enable the GC collect test for the Label and Panel control in unit test cases
- No
- Unit tests
- dotnet 8.0.100-preview.6.23307.24
> Update control owning field of Label and Panel to using weak references

- src/System.Windows.Forms/src/System/Windows/Forms/CheckBox.CheckBoxAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/CheckBox.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MultipleControls.Designer.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CheckBox.CheckBoxAccessibleObjectTests.cs
Fixes #9157
- Update TogglePattern ToggleState property implementation in `CheckBoxAccessibleObject`.
- Trigger StateChange accessible event when CheckBox is switched to Indeterminate state.
- Add unit tests to verify CheckBoxAccessibleObject.ToggleState property value and CheckBoxAccessibleObject.Toggle method behavior;
- Add three-state check box to WinformsControlsTest app.
- Screen readers announce CheckBox state correctly.
- Yes, the issue cannot repro in .Net Core 3.1, and repro in .Net 5, 6, 7 versions
- Minimal
Narrator announces Indeterminate state as Checked:
Narrator does not announce switching from Checked to Indeterminate state:
https://github.com/dotnet/winforms/assets/113603457/48630969-36ff-430a-8f80-d00d2e5c4d3e
ToogleState value is On for Indeterminate checkbox: …
> Fix CheckBox indeterminate state announcement in screen readers

- eng/pipelines/build.yml
Disable UI testing release/6.0
> Porting: Disable UI tests in release/6.0 branch

- eng/pipelines/build.yml
This is fixing an error in reading branch name in the PR https://github.com/dotnet/winforms/pull/9284
> Fix branch name while disabling UI tests

- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/DropDownButton.DropDownButtonAdapter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
Fixes #7721 
- Add HighContrast judgment when drawing dropdown button in file DropDownButton.DropDownButtonAdapter.cs
- Under the HC black theme, call the method "CreateBitmapWithInvertedForeColor" to invert the icon color
- When the button gets the focus, judge whether to revert the image color 
- The icon of "Browse..." in PropertyGrid control is unclear when non-selecting it
- No
- DotNet 8.0.100-preview.6.23307.24
> Fix issue #7721 by inverting the color of the Browse button

- eng/pipelines/build.yml
Please see linked issue for more details. We are disabling UI tests until we figure out on how to make them reliable.
Related to https://github.com/dotnet/winforms/issues/9318
> Disable UI tests.

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.EditorPropertyLine.cs
- src/System.Windows.Forms.Primitives/src/Interop/IHandle.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/MessageDecoder.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs
- src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Timer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
IHandle<T> is the better way to do things and now that we have removed all of the dependencies I'm removing the non generic version.
Also includes a small tweak to parameter names in MessageDecoder.
> Remove non-generic IHandle

- src/System.Windows.Forms/src/System/Windows/Forms/ImageListStreamer.cs
- Remove unnecessary nullable preprocessor directive in ImageListStreamer.
> Remove unnecessary nullable preprocessor directive in ImageListStreamer

- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System.Windows.Forms.Analyzers.CSharp.Tests.csproj
Fixing compliance issue by removing unused reference.
> Remove unused reference to Microsoft.Windows.Compatibility package

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorDragDropEventArgs.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.AdornerWindow.MouseHook.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.AdornerWindow.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.MenuCommandHandler.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorServiceAdornerCollectionEnumerator.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/Glyph.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SplitContainerDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripItemGlyph.cs
- Enable nullability in `Glyph`, `GlyphCollection`, `ToolStripItemGlyph` and `BehaviorService`
> Enable nullability in Glyph classes and BehaviorService

- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripButton.cs
Fixes #9199
- Do **not** unselect checkable ToolStripButton (with CheckOnClick=true) on click
ToolStripButton can handle consecutive Space key pressings:
- Screen readers announce checked state change every time.
- Click event is triggered every time.
- No
- Minimal
Narrator announces only the first Space key press:
https://github.com/dotnet/winforms/assets/113603457/839fbfd7-643d-4f32-9cc3-1e7c96c19476
Narrator announces every Space key press:
https://github.com/dotnet/winforms/assets/113603457/e93e3c51-da1c-4897-9b57-4d641ff767ed
- Manual
- .NET 8.0.100-preview.4.23260.5
> Prevent checkable ToolStripButton from losing focus on check/uncheck

- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/DisposalTracking.cs
Fixes #9304
Originally marked as draft because this is a real bug that needs to be investigated. If someone has the ability to update CI to collect a heap dump when one of these crashes occurs, it would be significantly preferred to just hiding it with a workaround like this.
Now marked ready for review due to the performance impact. Local testing showed this as a significant contributor to allocations and execution time for integration tests, where deferring the `ToString()` call resolved more than 50% of the overhead.
> Defer StackTrace rendering

- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/DataCollectionService.cs
Sometimes the first chance exception stack is incomplete, so the additional stack collected at the point where it's written to the log can help narrow down code locations.
> Include stack trace from log method

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripOverflow.ToolStripOverflowAccessibleObject.cs
Fixes #9384
- Fix values of IsControlElementProperty and IsContentElementProperty properties in `ToolStripOverflowAccessibleObject` to support UI tree structure as described in 
[UI Automation Support for the MenuItem Control Type](https://learn.microsoft.com/en-us/dotnet/framework/ui-automation/ui-automation-support-for-the-menuitem-control-type#required-ui-automation-tree-structure)
- Correct UIA tree structure
- No
- Minimal
Menu is visible in content view:
Menu is hidden in **content** view:
Menu is still visible in **control** view: 
- Manual
- .NET 8.0.0-preview.4.23259.5
- Accessibility Insights 1.1.2360.01
> Fix UIA tree structure for ToolStrip overflow menu

- src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
Fixes #9394
- Fix using of `TreeViewNodeSorter.Compare` method: compare tree nodes, not nodes' `Text` values.
- Add a unit test to ensure TreeNodes are compared while sorting TreeView.
> Fixed TreeView custom sorting failure when TreeNode has child nodes

- src/System.Windows.Forms/src/System/Windows/Forms/ThreadExceptionDialog.cs
Fixes #9251 
- Add AutoScaleMode.Dpi for ThreadExceptionDialog
- ThreadExceptionDialog doesn't scaled well when DPI is differ
-  No
- Minimal
- Manually 
- .net 8.0.100-preview.7.23328.8
> Add AutoScaleMode for ThreadExceptionDialog

- src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.Link.cs
- src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/LinkLabel.LinkLabelAccessibleObjectTests.cs
Fixes #9327 
- Override function ReleaseUiaProvider to LinkLabel.cs
- Add unit test for the function ReleaseUiaProvider 
- LinkLabel accessible object memory leak
-  No
- Minimal
- .net 8.0.100-preview.7.23325.3
> Add ReleaseUiaProvider for LinkLabel

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignSurface.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerHost.DesignerHostTransaction.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerHost.Site.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerHost.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/SiteNestedContainer.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignerHostTests.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/SiteNestedContainerTests.cs
- Enable nullability in `DesignerHost` and `SiteNestedContainer` 
- Change `Hashtable` with `Dictionary<object, object>` in `DesignerHost` (contributes to #8143)
- Stop throwing null-reference exceptions when adding or removing null components from `DesignHost` and `SiteNestedContainer`. The idea behind this change (that is obviously open for debate) is that it makes those method match the behaviour of the ones they override (from class `Container`). This one is the second commit, that can easily be rollbacked.
> Enable nullability in DesignerHost and SiteNestedContainer

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorServiceAdornerCollectionEnumerator.cs
Fixes #9410 - The parameter must be cast first before calling `GetEnumerator`.
Repeated frames:
```
System.Windows.Forms.Design.dll!System.Windows.Forms.Design.Behavior.BehaviorServiceAdornerCollectionEnumerator.BehaviorServiceAdornerCollectionEnumerator(System.Windows.Forms.Design.Behavior.BehaviorServiceAdornerCollection mappings) Line 13	C#
System.Windows.Forms.Design.dll!System.Windows.Forms.Design.Behavior.BehaviorServiceAdornerCollection.GetEnumerator() Line 217	C#
System.Windows.Forms.Design.dll!System.Windows.Forms.Design.Behavior.BehaviorServiceAdornerCollectionEnumerator.BehaviorServiceAdornerCollectionEnumerator(System.Windows.Forms.Design.Behavior.BehaviorServiceAdornerCollection mappings) Line 15	C#
[The 2 frame(s) above this were repeated 9584 times]	
```
Caused by #9341
> Fix stack overflow in BehaviorServiceAdornerCollectionEnumerator

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.HitTestInfo.cs
- Enable nullability in HitTestInfo.
> Enable nullability in HitTestInfo

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/HtmlElementEventArgs.cs
- Enable nullability in HtmlElementEventArgs.
> Enable nullability in HtmlElementEventArgs

- src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.DateTimePickerAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePicker.DateTimePickerAccessibleObjectTests.cs
Fixes #9281 
- 
- fix DateTimePicker's KeyboardShortcut property
- add unit tests
- 
- No
- 
- Manually and Unit Test 
- 
8.0.0-preview.7.23330.6
> DateTimePicker has incorrect AccessKey and KeyboardShortcut accessibility properties when Text contains '&' character

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataObject_BitmapBinderTests.cs
This is an experiment to see if this is the right kind of a suppression. THe next CodeQL run will validate it.
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1845201
> suppress CodeQL warning in one test

- src/System.Windows.Forms/src/Resources/SR.resx
- src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
- src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/KeysConverterTests.cs
Fixes #2886 
- Added support for the `culture` parameter in `ConvertFrom` and `ConvertTo` methods.
- Dictionaries with localization are loaded per request.
- `KeysConverter` becomes more independent and doesn't contain the logic of choosing the "right" locale. 
- No crashes when an application is run in different locales.
- A developer's locale doesn't impact values in the .resx file.
- The placeholder when the shortcut isn't set becomes more apparent.
- Yes (after migration to .net core).
- Old applications that contain localized values of `ShortcutKeys` (e.g. Strg for de-DE) are crashed.
- `ShortcutKeysEditor` seems inconsistent due to `KeysConverter` receiving `CultureInfo.CurrentCulture` while `ShortcutKeysUI` is localized with `CultureInfo.CurrentUICulture`.
- Manually 
.NET SDK: …
> Fixing runtime crash if an application contains `ToolStripMenuItem` with configured shortcut and launched in other locales.

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourceCodeDomSerializer.SerializationResourceManager.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/GlyphCollection.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SplitContainerDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/StringCollectionEditor.StringCollectionForm.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ObjectCollection.Entry.cs
- src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/DemoConsole.csproj
- src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DesignSurfaceExt/DesignSurfaceExt.cs
Fixes #9412
Fixes #9416
Fixes #9420
Fixes #9389
> Changes to fix issues in `DemoConsole`

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ControlAccessibleObjectTests.cs
Related to https://github.com/dotnet/winforms/issues/9224
- Update the test data used for test case.
- Test case ControlAccessibleObject_DoesNotRootControls_AllPublicControl can run normally through.
- No
- Unit tests
- 8.0.100-preview.7.23324.2
> Update the test data used for test case ControlAccessibleObject_DoesNotRootControls_AllPublicControl

- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.PropertyGridAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ControlAccessibleObjectTests.cs
- Update the control owning field of PropertyGrid to using weak references
- Enable the GC collect test for the PropertyGrid control in unit test cases
-  No
- Unit tests
- dotnet 8.0.0-preview.7.23358.3
> Update control owning field of PropertyGrid to using weak reference

- src/System.Windows.Forms/src/System/Windows/Forms/TabPage.TabPageAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ControlAccessibleObjectTests.cs
- Update the control owning field of TabPage to using weak references
- Enable the GC collect test for the TabPage control in unit test cases
-  No
- Unit tests
- dotnet 8.0.0-preview.7.23358.3
> Update control owning field of TabPage to using weak reference

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/ContainerSelectorGlyph.cs
> Change `ContainerSelectorGlyph` to use Icon internally

- src/System.Windows.Forms/src/System/Windows/Forms/TreeView.TreeViewAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ControlAccessibleObjectTests.cs
- Update the control owning field of TreeView to using weak references
- Enable the GC collect test for the TreeView control in unit test cases
-  No
- Unit tests
- dotnet 8.0.0-preview.7.23358.3
> Update control owning field of TreeView to using weak reference

- src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ControlAccessibleObjectTests.cs
- Update the control owning field of ListView  to using weak references
- Enable the GC collect test for the ListView  control in unit test cases
-  No
- Unit tests
- dotnet 8.0.0-preview.7.23358.3
> Update control owning field of ListView to using weak reference

- src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs
Fixes #9392
Regression was introduced in #9309 and specifically in ListBox change:
```diff
using var e = new DrawItemEventArgs(
-      dis->hDC,
+      dis->hDC.CreateGraphics(),
Font,
bounds,
-      dis->itemID,
-      dis->itemState,
+      (int)dis->itemID,
+      (DrawItemState)(int)dis->itemState,
ForeColor,
BackColor);
```            
`DrawItemEventArgs.Graphics` object started to be created by `hDC.CreateGraphics()`, which only calls `Graphics.FromHdcInternal(hdc)`, but previously it was a more complex initialization in `DrawingEventArgs`:
https://github.com/dotnet/winforms/blob/ea36ea9229ef001ffe21629d1c4e2fb3047a04f9/src/System.Windows.Forms/src/System/Windows/Forms/Internal/DrawingEventArgs.cs#L94-L118
There are different constructors for `DrawItemEventArgs`, so I restored it to …
> Fix ListBox rendering issues on horizontal scroll

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerBase.cs
- src/System.Windows.Forms.Primitives/src/System/ComponentModel/Design/Serialization/DesignerSerializationManagerHelper.cs
This PR is pretty big, apologies for that. It enables nullability in CodeDomSerializerBase to get one foot in the door to annotate more serializers down the road,
One issue I had doing this is the lack of annoations in System.CodeDom (see https://github.com/dotnet/runtime/issues/41720, https://github.com/dotnet/runtime/issues/78036)
Contributes to #8342
- Enable nullability in CodeDomSerializerBase
- Refactor CodeDomSerializerBase and fix an apparent bug
- Introduce new helper functions to simplify more parts of the code
Each change is its own commit.
> Enable nullability in CodeDomSerializerBase

- src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs
Fixes #9474
- Reset `exceptionPrinting` flag when `Document` property is set.
- User is able to preview different documents without re-creating `PrintPreviewControl`.
- No
- Minimal
After clicking "Print with error" button other buttons have no effect, `PrintPreviewControl` always shows error message:
https://github.com/dotnet/winforms/assets/113603457/60106600-1d2b-42f6-ab1e-b43c0ff2f427
"Print successfully" and "Reset" buttons work as expected:
https://github.com/dotnet/winforms/assets/113603457/2257e70a-f1f8-4e92-9f09-bcfe9e4adce0
- Manual
- .NET 8.0.100-preview.4.23260.5
> Fix PrintPreviewControl persisting print failure.

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
Fixes #9438 
When the GripStyle = Visible, the ToolStrip control can correctly find out the first item of can be selected by Keyboard.
but when we set the GripStyle = hidden, the ToolStrip control will find out the second item of can be selected by Keyboard, not the first. It may be caused this issue.
- Modify the method of finding the starting item - GetStartItem(bool forward, bool isDropDown).
- Refine test cases to cover more scenarios.
- Whatever the value of GripStyle is, when typing Left/Right arrow keyboard, ToolStrip  can find the correct starting item.
- Yes
- Minimal
Setting GripStyle = hidden, when selecting on a ToolStripButton using mouse or typing "enter" keyboard and then typing "right or left" keyboard, the next focus position is first item on the left, regardless of …
> Fix issue 9438: when setting GripStyle = hidden, the next focus position is not correct.

- src/System.Windows.Forms.Design/tests/UnitTests/ControlDesignerTests.cs
- src/System.Windows.Forms.Design/tests/UnitTests/TestControlDesigner.cs
Related to https://github.com/dotnet/winforms/issues/721
- Add unit test for System.Windows.Forms.Design.ControlDesigner.#ctor
- The test cases for SelectionRules already exist, here is the link:  [SelectionRulesProperty ](https://github.com/SimonZhao888/v-weidzh-winforms/blob/4b56c489bbe0858806bee1a0365824b945c06949/src/System.Windows.Forms.Design/tests/UnitTests/ControlDesignerTests.cs#L55C21-L55C21)
- The new test case can run normally through.
- No
- Unit test
- 8.0.100-preview.7.23324.2
> Add unit test for System.Windows.Forms.Design.ControlDesigner.#ctor

- src/System.Windows.Forms.Design/tests/UnitTests/System/Resources/Tools/StronglyTypedResourceBuilderTests.cs
Fixes #8295 
- Add test cases for function "VerifyResourceName" of the class "StronglyTypedResourceBuilder"
- None
-  No
- Low
- PR only has unit tests
- Unit Tests
- .net 8.0.100-preview.7.23357.8
> Add test for VerifyResourceName of StronglyTypedResourceBuilder

- src/System.Drawing.Common/src/SRDescriptionAttribute.cs
Fixes #3822
Only used in `PrintDocument`.
> Fix `System.Drawing.Common` `SRDescriptionAttribute`

- src/System.Windows.Forms/src/System/Windows/Forms/LayoutEventArgs.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/LayoutEventArgsTests.cs
Attempting to fix #165
Which is a memory leak in `System.Windows.Forms.Control.CachedLayoutEventArgs`.
> Refactor `LayoutEventArgs` to use a `WeakReference` for the `AffectedComponent` property with a backing field

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ThreadExceptionDialog.cs
- Use the new `SystemIcons.GetStockIcon()` method to display up-to-date icons from the OS
- Negligible
- Customers will no longer think these User Interface elements look like they're from Windows Vista/7
- No
-
Exception Dialog (this screenshot was taken at 200% scaling)
Paint exception in Winforms Designer
Exception Dialog (this screenshot was taken at 200% scaling)
Paint exception in Winforms Designer
(I didn't know how to get the Winforms Designer to use the DLL I built, so testing was simulated by copying code from `ControlDesigner.cs`  into a test control. Which is why it doesn't show the same call stack in this screenshot)
- Manual
- tested the Exception Dialog at 100% and 200% scaling
- tested at 100% in the Winforms Designer
-
> Utilize StockIcons in a couple interfaces

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxEditingControl.cs
- Enable nullability in DataGridViewComboBoxEditingControl.
> Enable nullability in DataGridViewComboBoxEditingControl

- src/System.Windows.Forms/src/Resources/SR.resx
- src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
fixes #8440
Some of the keyboard button names should not be translated for all the languages.  Following internal document outlines which keys to be translated and which or not, based on Window's On screen keyboard, for .Net supported languages.
> Fix loc for the keyboard buttons.

- src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.cs
Fix items property for multiple checked list boxes shouldn't be displayed in properties window #5337
Fixes [5337](https://github.com/microsoft/winforms-designer/issues/5337)
- 
- add attribute MergableProperty(false)
- 
-  No
8.0.0-preview.7.23364.11
> Fix items property for multiple checked list boxes shouldn't be displayed in properties window #5337

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellPaintingEventArgs.cs
- Enable nullability in DataGridViewCellPaintingEventArgs.
> Enable nullability in DataGridViewCellPaintingEventArgs

- src/System.Design/src/System.Design.Forwards.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/MonthCalendarDesigner.cs
- src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/DesignerAttributeTests.cs
Related to #4908 
- Port MonthCalendarDesigner to runtime
- MonthCalendarDesigner can be designed in runtime
-  No
- Minimal
- Manually (added MonthCalendarDesigner to DemoConsole test app)
- .Net 8.0.100-preview.7.23364.1
- Windows 10 Enterprise 22H2
> Port MonthCalendarDesigner to runtime

- src/System.Windows.Forms/src/Resources/SR.resx
- src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
Related to #9556
loc team says ll-CC format is not working for some reason and suggested to change the format to LCID.
> Update language format from ll_CC to LCID

- src/System.Windows.Forms.Primitives/src/System/DisposeHelper.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/Foundation/AgileComPointer.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/System/Com/StandardDispatch.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxContainer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.State.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
Releasing a COM interface can lead to a call back. We need to clear fields before releasing so we don't attempt to release twice.
Fixes #9551
> Guard against re-entry in ActiveXImpl / AgileComPointer.

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowCollection.RowComparer.cs
- Enable nullability in RowComparer.
> Enable nullability in RowComparer

- .editorconfig
CLI has warnings as errors enabled for most of the projects, thus the CLI build is less affected.
Before
After
> IDE to report unused usings as errors. 

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewButtonCell.DataGridViewButtonCellRenderer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewButtonCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewHeaderCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewLinkCell.cs
- Enable nullability in DataGridViewButtonCell.
> Enable nullability in DataGridViewButtonCell

- src/System.Windows.Forms/src/System/Windows/Forms/TextRenderer.cs
This assert has come up a number of times recently. Adding some informational text to clarify why this assert exists and what the guidelines are.
> Add commentary to TextRenderer assert

- src/System.Design/src/System.Design.Forwards.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/PrintDialogDesigner.cs
- src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/DesignerAttributeTests.cs
Related to #4908 
- Port MonthCalendarDesigner to runtime
- PrintDialogDesigner can be designed in runtime
- No
- Minimal
The default value of the property "UseEXDialog" is false
The default value of the property "UseEXDialog" is true
- Manually (added PrintDialogDesigner to DemoConsole test app)
- .Net 8.0.100-rc.1.23375.11
- Windows 10 Enterprise 22H2
> Add PrintDialogDesigner.cs

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/Drawing/Design/FontEditor.cs
- src/System.Windows.Forms.Design/src/System/Drawing/Design/FontNameEditor.cs
- Enable nullability in `FontEditor`
- Enable nullability in `FontNameEditor` and use target-typed new
> Enable nullability in FontEditor and FontNameEditor

- src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control_ActiveXControlInterfaces.cs
This is the last audit change of `ActiveXImpl`. Changes were vetted against docs and MFC implementations.
- `QuickActivate`` was releasing pointers it shouldn't have been.
- `SetAdvise` and `GetAdvise` were not AddRef'ing appropriately.
- Update comments.
> Fix a few more ref counts in ActiveXImpl

- eng/Versions.props
- src/System.Drawing.Common/src/System/Drawing/DrawingCom.ComWrappers.cs
- src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
- src/System.Windows.Forms.Primitives/src/System.Windows.Forms.Primitives.csproj
- src/System.Windows.Forms.Primitives/src/Windows/Win32/Foundation/BSTR.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/Foundation/ComScope.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.FillRect.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
A number of Libarary APIs have had their parameters changed from `ref` to `in` (or `readonly ref`).
This change modifies code that we control and disables the "passing ref to in" warning for the interop assembly until we can get https://github.com/microsoft/CsWin32/issues/1014 resolved.
This change requires a more current Roslyn build and as such I've updated it. Note that VS Intellisense does not support this new feature yet. You can filter out intellisense errors by selecting "Build Only" in the error pane in the meantime (this will not remove red squiggles unfortunately).
> Handle `ref` to `in` change

- src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs
Fixes #9596
When  PrintPreviewControl is created and the handle is created, then change the size of the PrintPreviewControl to a very little size ,for example (0,0) , an exception will be thrown.
- 
- Add parameter check before throwing Exception
- 
- 
- Manually 
- 
8.0.0-rc.1.23379.8
> fix System.ArgumentOutOfRangeException: Value of '-22' is not valid for 'LargeChange'#9596

- .editorconfig
Related #9615 
- when adding the file_header_template  for .vb in .editorconfig , the build error "[.dotnet\sdk\8.0.100-preview.6.23330.14\Roslyn\Microsoft.VisualBasic.Core.targets(43,5): error MSB6006: (NETCORE_ENGINEERING_TELEMETRY=Build) "vbc.dll" exited with code 1](https://dev.azure.com/dnceng-public/public/_build/results?buildId=358645&view=logs&j=fdea2036-e6b2-512d-a259-98f88c972586&t=e85b1de4-8dce-50bb-88c3-24524432e33a&l=176)." appeared, so remove the template for vb files and a comment for it.
> Update .editorconfig to add comment for file_header_template

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Resources/AssemblyNamesTypeResolutionService.cs
- src/System.Windows.Forms/src/System/Resources/ResXDataNode.cs
This is extracted from #9663. That PR is bound to be merged in .Net 9, but hopefully we can still fix the annotation of ResXDataNode before it's released in .Net 8
@dreddy-work 
- Fix nullability annotations of ResXDataNode
> Fix nullability annotations of ResXDataNode

- src/System.Windows.Forms.Design/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionListCollection.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/AdornerCollection.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/GlyphCollection.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.DesignerControlCollection.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CustomMenuItemCollection.cs
- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/AutoCompleteStringCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ObjectCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ImageList.ImageCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListBox.IntegerCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ObjectCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.ColumnHeaderCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewItemCollection.IInnerList.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewItemCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewNativeItemCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupItemCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItemCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItemCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.ToolStripPanelRowCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.ToolStripPanelRowControlCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeCollection.cs
Add `params` keyword to arguments of `ControlCollection.AddRange` method.
Fixes #8938
Based on: #8928
> Refactor `ControlCollection.AddRange` to use `params` keyword

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/LoadedEventArgs.cs
Sorry about the tiny PRs. I keep on looking for public types that are safe to annotate before .Net 8 cutoff, and push them as I find them.
- Enable nullability in `LoadedEventArgs`
> Enable nullability in LoadedEventArgs

- src/System.Windows.Forms.Primitives/src/NativeMethods.txt
- src/System.Windows.Forms/src/System/Windows/Forms/Help.cs
- src/System.Windows.Forms/src/System/Windows/Forms/HelpProvider.cs
> Fix `Help.ShowHelp` to use `FindExecutable` to enable passing full local URL to default browser

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripRenderer.cs
Fixes #9166 
- Add HighContrast judgment when drawing indeterminate image in file ToolStripRenderer.cs
- When the item is selected or under HC black theme, revert the image color
- The color contrast of indeterminate state icon can be showed clearly
-  No
- Minimal
**Windows 11 non-focused:**
**Windows 11 mouse over:**
- Manually
- .net 8.0.0-rc.1.23409.17
> Fixing indeterminate image color

- src/Common/tests/TestUtilities/ComparisonHelpers.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/NullRecord.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.TopRowAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellCancelEventArgs.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellEventArgs.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellFormattingEventArgs.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellMouseEventArgs.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellValueEventArgs.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnDividerDoubleClickEventArgs.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnHeaderCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewHeaderCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.DataGridViewRowAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowContextMenuStripNeededEventArgs.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowDividerDoubleClickEventArgs.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTopLeftHeaderCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/LinkClickedEventArgs.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TaskDialog.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.ToolStripPanelRowControlCollection.cs
I applied the CA1512 fixer across the codebase, and just deleted some blank lines manually.
There are places that the analyzer did not fix. I'm doing a manual pass locally and can follow-up on that.
Also, in dotnet/runtime#79460, custom error messages were replaced by the standard one. If that's something that we are willing to consider here, I can follow-up with another commit/PR
- Apply CA1512 fixer: Use ArgumentOutOfRangeException throw helper
- low: changes are from anaylzers
- CI
> Use throw helpers for ArgumentOutOfRangeException

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourceCodeDomSerializer.SerializationResourceManager.cs
As discussed in #9457.
#8332 introduced bugs in `ResourceCodeDomSerializer.SerializationResourceManager`, in method `GetResourceSet`. When we fail to get a resource reader, the original code used to return a resource set for the invariant culture, and null otherwise. After #8332,,
- we're returning `null` the first time we fill the `ResourceTable` cache
- for the non-invariant culture case, we started filling the `ResourceTable` cache with a static dictionary,  which looks like a pretty big issue
These bugs were introduced in .Net 8 and we still have a chance to fix them before the release
@dreddy-work, @elachlan
> Fix bugs in ResourceCodeDomSerializer.SerializationResourceManager

- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Automation/UiaTextRange.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewHeaderCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowHeaderCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/LinkClickedEventArgs.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItemCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TaskDialog.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TaskDialogProgressBar.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeCollection.cs
This is the first follow-up to #9713. These are all the cases not caught by CA1512 but are legitimate uses of the new `ArgumentOutOfRangeException` throw helpers, because the error message is not overridden.
- Use ArgumentOutOfRangeException throw helpers
- low, but higher than the pure fixer modifications. I still used the IDE as much as possible (e.g. to break if clauses into 2) so that CA1512 could apply
- CI
> Use throw helpers for ArgumentOutOfRangeException: manual cases

- src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.TabControlAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPage.TabPageAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TrackBar.TrackBarAccessibleObjectTests.cs
Our interop handle structs (such as HWND) cannot be marshalled directly and will fail "silently" on callbacks (they will throw but the marshaller will convert that to an HRESULT that we won't see unless first-chance exceptions are on when we're debugging).
> Fix IRawElementProviderSimple.GetPropertyValue

- src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.TabControlAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPage.TabPageAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TrackBar.TrackBarAccessibleObjectTests.cs
Our interop handle structs (such as HWND) cannot be marshalled directly and will fail "silently" on callbacks (they will throw but the marshaller will convert that to an HRESULT that we won't see unless first-chance exceptions are on when we're debugging).
> Fix IRawElementProviderSimple.GetPropertyValue (#9732)

- src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FormTests.cs
Fixes #9210 
In #7561 the result for `WM_QUERYENDSESSION` was accidentally flipped causing the return for `WM_QUERYENDSESSION` to be `false`, which would prevent shutdown/log off. This change fixes this and also adds a test that ensures that `Form` will return `true` for a `WM_QUERYENDSESSION` message.
> Ensure Form Doesn't Prevent Shutdown

- src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
- src/System.Windows.Forms.Design/tests/UnitTests/BinaryEditorTests.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/EmbeddedResourceTests.cs
The BinaryEditor dialog resources were not in the right namespace which was preventing the modal editor from launching successfully.
Fixes #7356
> Fix resource namespace for BinaryEditor

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/KeysConverterTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PaddingConverterTests.cs
Contributes to #2734
- add missing UseDefaultXunitCulture attributes
- none, only affects unit tests on developer machines
- no
- minimal, should only affect developers running tests locally
- tests failing when running on german machine.
- less tests failing when running on german machine.
- run tests in Visual Studio on a german machine.
- german machine (de-de culture)
> add missing UseDefaultXunitCulture attributes

- src/System.Windows.Forms.Design/src/Resources/xlf/SR.cs.xlf
- src/System.Windows.Forms.Design/src/Resources/xlf/SR.de.xlf
- src/System.Windows.Forms.Design/src/Resources/xlf/SR.es.xlf
- src/System.Windows.Forms.Design/src/Resources/xlf/SR.fr.xlf
- src/System.Windows.Forms.Design/src/Resources/xlf/SR.it.xlf
- src/System.Windows.Forms.Design/src/Resources/xlf/SR.ja.xlf
- src/System.Windows.Forms.Design/src/Resources/xlf/SR.ko.xlf
- src/System.Windows.Forms.Design/src/Resources/xlf/SR.pl.xlf
- src/System.Windows.Forms.Design/src/Resources/xlf/SR.pt-BR.xlf
- src/System.Windows.Forms.Design/src/Resources/xlf/SR.ru.xlf
- src/System.Windows.Forms.Design/src/Resources/xlf/SR.tr.xlf
- src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hans.xlf
- src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hant.xlf
Noticed that while trying to port some localization changes from https://github.com/dotnet/winforms/pull/9739 to release/8.0 that some changes translated strings to english, which seems unintentional. Undoing these in main branch. 
@cristianosuzuki77 Is there something that needs to be fixed with the setup on our side?
> Undo Localization Changes

- src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
- src/System.Windows.Forms.Design/tests/UnitTests/BinaryEditorTests.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/EmbeddedResourceTests.cs
The BinaryEditor dialog resources were not in the right namespace which was preventing the modal editor from launching successfully.
> Fix resource namespace for BinaryEditor (#9746)

- src/System.Windows.Forms.Primitives/src/System/DisposeHelper.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/Foundation/AgileComPointer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxContainer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.OleInterfaces.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
COM code audit fixes:
- AxContainer.IOleInPlaceFrame.SetActiveObject was not ref counting correctly or checking for null
- OleInterfaces.IOleControlSite.GetExtendedControl was unnecessarily using Marshal
- OleIntefaces.IOleInPlaceSite.GetWindowContext brought in line with MFC behavior with null pointers
- Use static char array in ActiveXImpl (minor perf fix)
- ActiveXImpl.InPlaceActivate was incorrectly ref counting
- ActiveXImpl Save/Load were releasing IPropertyBag when it was passed directly from native code, move the using local to the internal code
- ActiveXImpl.QuickActivate should not fail if we cannot get IConnectionPointContainer
- Add DisposeHelper.NullAndRelease helper for safer release of pointer fields
- Harden AgileComPointer a bit more by using Interlocked
> Additional COM fixes

- src/System.Windows.Forms.Primitives/src/System/DisposeHelper.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/Foundation/AgileComPointer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxContainer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.OleInterfaces.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
Port of #9769 - do not squash
COM code audit fixes:
- AxContainer.IOleInPlaceFrame.SetActiveObject was not ref counting correctly or checking for null
- OleInterfaces.IOleControlSite.GetExtendedControl was unnecessarily using Marshal
- OleIntefaces.IOleInPlaceSite.GetWindowContext brought in line with MFC behavior with null pointers
- Use SearchValues in ActiveXImpl (minor perf fix)
- ActiveXImpl.InPlaceActivate was incorrectly ref counting
- ActiveXImpl Save/Load were releasing IPropertyBag when it was passed directly from native code, move the using local to the internal code
- ActiveXImpl.QuickActivate should not fail if we cannot get IConnectionPointContainer
- Add DisposeHelper.NullAndRelease helper for safer release of pointer fields
- Harden AgileComPointer a bit more by using …
> Additional COM fixes (#9769)

- src/System.Design/src/System.Design.Forwards.cs
- src/System.Windows.Forms.Design/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DataSourceDescriptor.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DataSourceDescriptorCollection.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DataSourceGroup.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DataSourceGroupCollection.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DataSourceProviderService.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/BindingNavigatorDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/BindingSourceDesigner.cs
- src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/DesignerAttributeTests.cs
Related to https://github.com/dotnet/winforms/issues/4908
- Port BindingSourceDesigner, BindingNavigatorDesigner to runtime.
- BindingSourceDesigner can be designed in runtime
- No
- Minimal
BindingSourceDesigner can be designed in runtime.
- Manually (add BindingSourceDesigner to DemoConsole test app)
- .Net 8.0.100-rc.1.23377.5
> Port BindingSourceDesigner, BindingNavigatorDesigner to runtime

- src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewLabelEditAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewLabelEditAccessibleObjectTests.cs
Fixes #7263
- Add a variable to the ListView to record the ListViewSubItem to which the Label Edit belongs.
- Remove the code related to Label Edit in ListViewAccessibleObject class.
- Adjust the ListViewSubItemAccessibleObject and ListViewLabelEditAccessibleObject classes so that the Label Edit will be displayed under the ListViewSubItem node when constructing the tree structure.
- The control of LabelEdit will show under ListViewSubItem.
- No
- Minimal
Label Edit is at the same level as the List item and is displayed under the root node of the List.
Label Edit displays under the edited cell.
- Manual (using inspect )
> Make sure the Label Edit in ListView has correct position in accessibility tree 

- src/System.Windows.Forms.Primitives/src/Windows/Win32/Foundation/AgileComPointer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObjectExtensions.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxContainer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlTabOrderComparer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlTabOrderHolder.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.OleCallback.cs
- src/System.Windows.Forms/tests/InteropTests/PropertyGridTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjectTests.cs
- AccessibleObject.Navigate was not returning results from SysNavigate
- Change SysNavigate to return AccessibleObject to allow both use cases
- Update comments around SysNavigate/GetSysChild
- Add release for IDispatch in TryGetAccessibleObject when it fails
- Various other comment cleanup
- Tolerate incoming VT_INT in AccessibleObjectExtensions
- Turn ControlTabOrderHolder into record struct with clearer terms
- Make ControlTabOrderComparer static and add comments
- Use Assert.Fail for clarity in PropertyGridTests
- Add tests for AccessibleObject.Navigate
> Fix Accessibility COM related issues

- src/System.Windows.Forms/src/System/Windows/Forms/BindableComponent.cs
> Fix missing category attribute for BindableComponent's DataBinding property.

- src/System.Windows.Forms.Primitives/src/Windows/Win32/Foundation/AgileComPointer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObjectExtensions.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxContainer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlTabOrderComparer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlTabOrderHolder.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.OleCallback.cs
- src/System.Windows.Forms/tests/InteropTests/PropertyGridTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjectTests.cs
- AccessibleObject.Navigate was not returning results from SysNavigate
- Change SysNavigate to return AccessibleObject to allow both use cases
- Update comments around SysNavigate/GetSysChild
- Add release for IDispatch in TryGetAccessibleObject when it fails
- Various other comment cleanup
- Tolerate incoming VT_INT in AccessibleObjectExtensions
- Turn ControlTabOrderHolder into record struct with clearer terms
- Make ControlTabOrderComparer static and add comments
- Use Assert.Fail for clarity in PropertyGridTests
- Add tests for AccessibleObject.Navigate
- Avoid potential issues trying to use the original AgileComPointer pointer.
> Fix Accessibility COM related issues (#9804)

- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxComponentEditor.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxContainer.ExtenderProxy.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxContainer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxPropertyDescriptor.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.OleInterfaces.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.PropertyBagStream.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.State.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.VBFormat.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
We have trace statements everywhere in AxHost and most of our trace statements do not seem to add much value as it just highlights what methods were entered. If needed, we can use debug actions in VS to output messages capturing points of interest when debugging instead of having traces throughout our code, so removing them.
> Remove Tracing from AxHost

- src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.VARIANT.cs
- src/System.Windows.Forms.Primitives/src/Interop/WinFormsComStrategy.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/ComHelpers.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/Foundation/GlobalInterfaceTable.UnknownStrategy.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/Foundation/GlobalInterfaceTable.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.AxSourcingSite.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DropTarget.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
- src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
- src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserContainer.cs
- src/System.Windows.Forms/tests/UnitTests/TextBoxBaseTests.cs
Create a Global Interface Table IUnknownStrategy so we can use the same machinery the runtime uses to expose COM interfaces as objects with AgileComPointer-like support.
Change all of the direct Marshal calls to use a ComHelpers wrapper method.
> Create IUnknownStrategy for GlobalInterfaceTable
