dotnet/winforms

THIRD-PARTY-NOTICES.TXT, src/System.Windows.Forms/ref/System.Windows.Forms.cs, src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/FileDialog_Vista_Interop.cs, src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/NativeMethods.cs, src/System.Windows.Forms/tests/UnitTests/FolderBrowserDialog.cs, src/System.Windows.Forms/tests/functests/Runner_WinformsControlsTest/run_individual_exe.ps1, src/System.Windows.Forms/tests/functests/WinformsControlsTest/MainForm.Designer.cs, src/System.Windows.Forms/tests/functests/WinformsControlsTest/MainForm.cs
This PR fixes #1 by implementing a Vista-style folder dialog.
Current dialog:
With this PR, the Vista-style dialog:
=> Modernize folderdialog

README.md
The link "Porting guide" is leading to a non-existent file. This PR includes the fix to the link.
=> Corrected the link to the Porting guide

global.json
Adding an Sdk section to global.json. This is needed to ensure that CI servers deterministically use the version of .NET Core 3.0 Sdk specified here to build the projects in the repo.
=> Adding an Sdk section to global.json

src/System.Windows.Forms/src/System/Windows/Forms/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/misc/CommonUnsafeNativeMethods.cs, src/System.Windows.Forms/src/misc/DpiHelper.DpiAwarenessContext.cs, src/System.Windows.Forms/tests/UnitTests/CommonUnsafenativeMethods.cs, src/System.Windows.Forms/tests/UnitTests/DpiHelper.cs
* changes to src
- UnsafeNativeMethods use nameof instead of string to find, will throw at compile in method name changes
- CommonUnsafeNativeMethods use nameof instead of string to find, will throw at compile in method name changes
- CommonUnsafeNativeMethods fix for equality check now that windows confirms if the enum is a member of theirs, throws if attempt to set thread dpi context to unspecified as windows will refuse to do this
- change to DpiHelper.DpiAwarenessContext to use TryFindDpiAwarenessContextsEqual middle-man method
* Some tests for CommonUnsafeNativeMethods and for DpiHelper to catch recent bugs fixes should they appear again.
=> common unsafe unit tests & fixes to code that unit tests revealed

src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
These fixes are related to the keyboard tooltips feature and the Managed Debugging Assistant ‘NonComVisibleBaseClass’ exception.
Related to #182
=> Ported three accessibility bug fixes from .NET 4.8

CODE_OF_CONDUCT.md
https://github.com/dotnet/winforms/community does not recognize our Code of Conduct (same problem on other repos, e.g. CoreFX).
Attempt to fix it by changing title of the file to match the one from GitHub template (it may not help).
=> Change top of Code of Conduct

src/System.Windows.Forms.Design.Editors/src/Misc/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataFormats.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolBar.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs, src/System.Windows.Forms/src/System/Windows/Forms/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/control.ime.cs, src/System.Windows.Forms/src/misc/GDI/DeviceContext2.cs, src/System.Windows.Forms/src/misc/GDI/NativeMethods.cs, src/System.Windows.Forms/src/misc/GDI/UnsafeNativeMethods.cs
As much as I fondly remember Windows 95/98 I don't think we need the code to support it any more. :)
This removes a large chunk of 9x specific code as well as some other dead/unused code in interop.
I have some other interop correctness and performance fixes that I'll follow this with.
=> Clean out Windows 9x code

src/System.Windows.Forms.Design.Editors/src/System/Windows/Forms/Design/ShortcutKeysEditor.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionListCollection.cs, src/System.Windows.Forms/src/System.Windows.Forms.csproj, src/System.Windows.Forms/src/System/Windows/Forms/UnsafeNativeMethods.cs
Contributes to https://github.com/dotnet/winforms/issues/48 
- Restore compiler warning CS0649: there actually no unused field in this project
- Fix warnings due to SecurityCriticalScope being obsolete
=> Suppress SecurityCritical attributes

src/System.Windows.Forms/src/System/Resources/IAliasResolver.cs, src/System.Windows.Forms/src/System/Resources/ResXDataNode.cs, src/System.Windows.Forms/src/System/Resources/ResXFileRef.cs, src/System.Windows.Forms/src/System/Resources/ResXNullRef.cs, src/System.Windows.Forms/src/System/Resources/ResXResourceReader.cs, src/System.Windows.Forms/src/System/Resources/ResXResourceSet.cs, src/System.Windows.Forms/src/System/Resources/ResXResourceWriter.cs
SYSTEM_WEB, UNUSED, SOAP_FORMATTER, aren't set anywhere. SoapFormatter is obsolete since .NET 2.0, and there is no System.Web in .NET Core :)
=> Remove unused symbols and commented code from resx code

eng/ci.yml
test signing is running into sporadic failures on build machines, so disable it for now
=> disable test signing for now

Documentation/issue-guide.md
We found there was a need to include labels for requesting that a PR's history not be squashed at merge-time. We also found that we needed to better communicate when testing was required internally before a PR could be merged. 
These two labels were added to resolve these needs.
=> update issue-guide.md to include new PR labels

README.md
There was no license badge in the readme; it is common practice among github repositories to have this, especially among popular repos. 
examples:
- https://github.com/hyperium/hyper
- https://github.com/GokuMohandas/practicalAI
=> Add License badge to readme

src/System.Windows.Forms/src/System.Windows.Forms.csproj, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2TypeInfoProcessor.cs, src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs
Removed the unused fields when compiling in release mode
Contributes to https://github.com/dotnet/winforms/issues/48
=> Fix warning CS0649

src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutSettings.cs
`TypeDescriptor.GetConverter` will *always* return a non-null value
=> Delete dead checks in serialization code in TableLayoutSettings

src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.cs
`desiredScaleSpace` is never set, so will always be `0`, so all the code is dead:
```cs
if(/*!dontHonorConstraint && */hasAutoSizeColumn && remainingSpace > 0) {
float scaleAdjustment = 1.0f; // not used anyway
if(remainingSpace < desiredScaleSpace) { // Dead, as `remainingSpace > 0`
scaleAdjustment = remainingSpace / desiredScaleSpace;
}
remainingSpace -= (int) Math.Ceiling(desiredScaleSpace); // Dead, as `X - 0 = X`
....
```
=> Remove dead variables from TableLayout

src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.cs, src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutSettings.cs, src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutSettingsTypeConverter.cs
Extracted from https://github.com/dotnet/winforms/pull/285
- All can be triggered from the tests in that PR
/cc @zsd4yr @sharwell
=> Remove incorrect debug.asserts in table code

.github/CONTRIBUTING.md, .vscode/settings.json, CODE_OF_CONDUCT.md, Documentation/building.md, Documentation/contributing.md, Documentation/debugging.md, Documentation/developer-guide.md, Documentation/getting-started.md, Documentation/issue-guide.md, Documentation/porting-guidelines.md, Documentation/testing.md, Documentation/winforms-designer.md, README.md, roadmap.md
Inconsistency in formatting of markdown files in the repo. I used [markdownlint](https://marketplace.visualstudio.com/items?itemName=DavidAnson.vscode-markdownlint) to normalize formatting in all source files and [Code Spell Checker](https://marketplace.visualstudio.com/items?itemName=streetsidesoftware.code-spell-checker) to fix all current spelling errors, clarify wording, insert oxford commas, remove contractions; also move all links to bottom
=> Standardize docs formatting

src/System.Windows.Forms/src/System/Windows/Forms/FileDialog_Vista.cs, src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs, src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleState.cs
Fixing GitHub issue #317. VisualstyleState was a numeric check that is broken in latest windows  version (where it added a new flag to its Enum).  Changing the state validation to bit-wise to fix it.
=> VisualStyleState check is now converted in to bit-wise.

README.md
`See here for a workaround invoking the Classic Framework Designer` incorrectly points to a file in `./` instead of `./Documentation/`
=> Fix link path

src/System.Windows.Forms/src/System/Windows/Forms/ListItemConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupConverter.cs
`ctor` is never null when getting the instancedescriptor
the other changes are formatting cleanups
=> Remove dead ctor checks in ListItemConverter

pkg/Microsoft.Private.Winforms.csproj
@zsd4yr requested that XML files produced during the build not be included in the NuGet package produced for the repository. This change implements that request.
If this request was documented by an issue, please feel free to link it. 👍
=> Exclude documentation files from NuGet package

.gitignore
The issues with obj/ directories were a carry-over from the migration to arcade. Users were not aware that a **git clean** was required to remove the extraneous files and folders because they did not show up in source control views. After this change, it will be clear when files are left over from a checkout of an earlier revision, and a git clean operation will restore the repository to a properly working state.
Supersedes #490
=> Remove unnecessary exclusions from .gitignore

src/System.Windows.Forms/src/System/Windows/Forms/ListBindingHelper.cs
Fixes #388 
Fixes #389
Fixes #390
Fixes #391
Fixes #392
This is an obvious win - we now return something meaningful (and usable) in these examples rather than throwing NRE. There are no changes in exceptions, only exceptions in edge cases that are no longer an issue!
=> Fix binding null refs

src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/ButtonBaseAdapter.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/DropDownButton.cs
Before:
The appropriate color is now used for the icon's dots when the HC Black or HC White theme is enabled
After:
=> The focused PropertyGrid button with 3 dots is not following HC standards on HC Black/White theme

src/System.Windows.Forms.Design.Editors/src/System/ComponentModel/Design/ArrayEditor.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/ArrayEditorTests.cs
The ArrayEditor is needed to enable runtime designer functionality for the Chart control (WinForms Core DataVisualization).
=> Port the ArrayEditor from the classic framework and add unit test.

eng/Version.Details.xml, eng/Versions.props, global.json
Add a new, unused dependency on Microsoft.NETCore.App. Then add coherent parent attributes to the corefx and coreclr dependencies.  This ensures that those dependencies correspond to a Microsoft.NETCore.App that was produced, rather than getting ahead.
=> Add coherent parent dependencies

src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs, src/System.Windows.Forms/tests/UnitTests/VisualStyleRendererTests.cs
According to the MS docs, the parameter `LPCRECT prc` is missing:
```c
THEMEAPI GetThemeMargins(
HTHEME  hTheme,
HDC     hdc,
int     iPartId,
int     iStateId,
int     iPropId,
LPCRECT prc,
MARGINS *pMargins
);
```
This PR adds this missing parameter.
Fixes #526
=> Fix GetThemeMargins p/invoke signature

Directory.Build.props, Directory.Build.targets, eng/packageContent.targets, global.json, pkg/Microsoft.Private.Winforms.csproj, src/Common/tests/CommonTestHelper.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ColumnHeaderConverterTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Layout/TableLayoutSettingsTypeConverterTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupConverterTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItemConverterTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewSubItemConverterTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/OpacityConverterTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PaddingConverterTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TableLayoutPanelCellPositionTests.cs
fixes
```diff
- E:\winforms\.dotnet\sdk\3.0.100-preview4-010924\Sdks\Microsoft.NET.Sdk\targets\Microsoft.NET.Sdk.targets(115,5): error NETSDK1085: The 'NoBuild' property was set to true but the 'Build' targetcrosoft.NET.Sdk.targets(115,5): error NETSDK1085: The 'NoBuild' property was set to true but the 'Build' target was invoked. [E:\winforms\pkg\Microsoft.Private.Winforms.csproj]
```
=> Update SDK, remove NoBuild (now deprecated), and fix tests for InstanceDescriptor Conversion

src/System.Windows.Forms.Design.Editors/src/Resources/SR.resx, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hant.xlf
This is take 2, I added a comment to resx file and the xlf files were generated by the build. This seems to be consistent with what Roslyn has in their repo.
=> locked string "Web" because it should not be localized

src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Buttons.cs
For some reason, the FlatStyle of each control was not being set in this form's constructor, which makes testing the different FlatStyles rather difficult. This is now fixed.
=> Fix strange oversight in Buttons test form

src/System.Windows.Forms/src/System/Windows/Forms/Application.cs, src/System.Windows.Forms/tests/UnitTests/ThreadContextTests.cs
This was using ArrayList, which should be updated, especially in Core 3.0.
In addition, uses a List rather then an array for the filter snapshot to avoid requiring allocation every filter, but instead only the first time a filter gets added.
=> Update MessageFilters to use List<T>

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/LoadedEventArgs.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/LoadedEventHandler.cs, src/System.Windows.Forms.Design/src/System/Drawing/Design/IToolboxService.cs, src/System.Windows.Forms.Design/src/System/Drawing/Design/IToolboxUser.cs, src/System.Windows.Forms.Design/src/System/Drawing/Design/ToolboxComponentsCreatedEventArgs.cs, src/System.Windows.Forms.Design/src/System/Drawing/Design/ToolboxComponentsCreatingEventArgs.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorDragDropEventArgs.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerActionListsChangedEventArgs.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerActionListsChangedEventHandler.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerActionListsChangedType.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerActionUIStateChangeEventArgs.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerActionUIStateChangeType.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignerActionListsChangedEventArgsTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignerActionUIStateChangeEventArgsTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/LoadedEventArgsTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/Drawing/Design/ToolboxComponentsCreatedEventArgsTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/Drawing/Design/ToolboxComponentsCreatingEventArgsTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/Behavior/BehaviorDragDropEventArgsTests.cs
=> Implement and cleanup System.Windows.Forms.Design event args

azure-pipelines.yml, eng/ci.yml
Relates to: https://github.com/dotnet/arcade/issues/2443
Goal: mitigate `lock on the feed problem` and add further validations. [More details here.](https://github.com/dotnet/arcade/blob/master/Documentation/CorePackages/AsyncPublishing_HowToUse.md)
Test build was here: https://dnceng.visualstudio.com/internal/_build/results?buildId=149725
Test release: https://dnceng.visualstudio.com/internal/_apps/hub/ms.vss-releaseManagement-web.cd-release-progress?_a=release-pipeline-progress&releaseId=4446
=> Onboard on async publishing

src/System.Windows.Forms.Design.Editors/src/System/Windows/Forms/Design/FileNameEditor.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/System/Windows/Forms/Design/FileNameEditorTests.cs
=> Add FileNameEditor tests, fix bugs and Debug Asserts

src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/WinFormsUtils.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ButtonBaseTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
Already tested across winforms in various functions
=> Cleanup WinFormsUtils, ButtonBase, Toolstrip, ToolstripItem + Tests

src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowHeaderCell.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/DataGridViewCellAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/DataGridViewRowsAccessibleObjectTests.cs
The change is related to the issue #710.
=> Accessibility: fixing DataGridView BoundingRectangle property for row, data cells and header cells

src/System.Windows.Forms.Design/src/Resources/SR.resx, src/System.Windows.Forms.Design/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerBase.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/TypeCodeDomSerializer.cs, src/System.Windows.Forms.Design/tests/UnitTests/Serialization/TypeCodeDomSerializerTests.cs
This component is required by the new .net core designer.
17 files changed, but only one class added with unit tests, the rest is translation resource resx files.
Related issue: #608
=> Port TypeCodeDomSerializer

src/System.Windows.Forms.Design/src/System/Drawing/Design/ToolboxItem.cs, src/System.Windows.Forms/src/System/Resources/ResXDataNode.cs
The GAC is not supported in .NET Core - `Assembly.GlobalAssemblyCache` always returns false, for example.
Therefore this is all dead in .NET Core. However, there may be a breaking change. Consider that the user defines their own non-runtime assembly by directly subclassing `Assembly` instead of using `typeof(int).Assembly` for example. If they overrode `GlobalAssemblyCache` to return `true` in .NET Core then the code that I deleted would have been run. However, the entire GAC feature has been removed in .NET Core so I firstly don't see this happening and secondly the code is actually meaningless anyway.
Contributes to #485
=> Remove references to GlobalAssemblyCache

src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
=> Fixing some identation

src/System.Windows.Forms.Design/src/System/Runtime/InteropServices/UCOMITypeLib.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/AxImporter.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerOptions.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/MenuCommands.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/StandardGroups.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ThemedScrollbarMode.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ThemedScrollbarWindow.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/WindowsFormsDesignerOptionService.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DesignerOptionsTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/MenuCommandsTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/WindowsFormsDesignerOptionServiceTests.cs
=> Add misc Design tests and fix a NullRef bug

src/Common/src/CompModSwitches.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System.Windows.Forms.csproj, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
WIN95_SUPPORT - It is always defined in this project, which contains the only use of it.
WINDOWS_FORMS_SWITCHES - It is always defined, and build fails if it is not defined.
Relates to #39
=> Remove redundant defines

src/System.Windows.Forms/src/System/Windows/Forms/Application.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataFormats.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataFormatsTests.cs
Previously, the maximum buffer size for `GetClipboardFormatName` was 128, but now it is 256. This means that we'd chop off up to half of the string when retrieving strings longer than 128. Fix this by updating the buffer size
Also cleanup the code and add complete test coverage
Fixes #696
=> Fix buffer size passed to GetClipboardFormatName in DataFormats

src/System.Windows.Forms.Design.Editors/src/System/Drawing/Design/FontEditor.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/System/Drawing/Design/FontEditorTests.cs
=> Add FontEditor tests, fix bugs and debug asserts

src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewBand.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs
Fixes #879 
Problem was the order of precedence between `&&` and `||`
/cc @zsd4yr @Amy-Li02
=> Fix DataGridViewBand.DefaultCellStyle setter

src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2TypeInfoProcessor.cs
Follow-up to #791. ~~I will rebase this change after the change from @hughbe is merged.~~
=> Remove StructCache

src/System.Windows.Forms.Design.Editors/src/System/ComponentModel/Design/CollectionEditor.cs
Previously the code was:
```cs
int c = _listbox.Items.Count;
if (c < 2)
{
c = 2;  //for c-1 should be greater than zero.
}
```
This was incorrectly cleaned up to `Min`, but should be `Max`.
Will resist the urge to clean cases like this up in future
=> Fix CollectionEditor min/max

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignSurfaceServiceContainer.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignSurfaceTests.cs
In the constructor of this class, we immediately call `AddFixedService(...)`
```cs
internal DesignSurfaceServiceContainer(IServiceProvider parentProvider) : base(parentProvider)
{
AddFixedService(typeof(DesignSurfaceServiceContainer), this);
}
```
The implementation of `AddFixedService` is:
```cs
internal void AddFixedService(Type serviceType, object serviceInstance)
{
AddService(serviceType, serviceInstance);
if (_fixedServices == null)
{
_fixedServices = new Hashtable();
}
_fixedServices[serviceType] = serviceType;
}
```
Since we call `AddFixedService` in the constructor, `_fixedServices` will be initialised immediately in the constructor. All future calls to `AddFixedService` therefore perform pointless null checking of `_fixedServices == null`.
`_fixedServices` can be thus allocated …
=>  Allocate DesignSurfaceServiceContainer._fixedServices in constructor and add tests

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerBase.cs
In DEBUG, `CodeDomSerializerBase.TraceScope(...)` initializes the field `traceScope` with a new stack and pushes a string to it. Later , in `TracingScope.Dispose()`, there is call to `traceScope.Pop()` if `traceScope` isn't null. However, the line to initialize `traceScope` was left outside of the `#if DEBUG` block while the call to `traceScope.Push(...)` was left inside. So, `TracingScope.Dispose()` attempts to pop the stack that has nothing in it.
It looks like this was just a simple misport. Moving the line back under DEBUG introduces an uninitialized field warning, and I suspect that's why it was moved out of DEBUG in the first place. However, setting the field to null in its initializer is the proper fix for that warning.
=> Fix bug in CodeDomSerializerBase that only occurs in Release config

src/Common/src/UnsafeNativeMethods.cs
Follow-up to #818, per a request in https://github.com/dotnet/winforms/pull/835#discussion_r277804970.
=> Use Unsafe.AsRef to implement UnsafeNativeMethods.PtrToRef

eng/FacadeAssemblies.props
Changes to the build caused ResolveMatchingContract to run after
conflict resolution which was removing the desktop reference to
System.Drawing in preference to the one in the NETCoreApp refs.
Avoid this completely by directly setting ResolvedMatchingContract
using the path to the targeting pack package.
Alternative to https://github.com/dotnet/winforms/pull/1005 that doesn't include arcade update.
=> Refactor ResolvedMatchingContract calculation

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/Microsoft.Dotnet.Winforms.ProjectTemplates.csproj, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/xlf/Form1.cs.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/xlf/Form1.de.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/xlf/Form1.es.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/xlf/Form1.fr.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/xlf/Form1.it.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/xlf/Form1.ja.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/xlf/Form1.ko.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/xlf/Form1.pl.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/xlf/Form1.pt-BR.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/xlf/Form1.ru.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/xlf/Form1.tr.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/xlf/Form1.zh-Hans.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/xlf/Form1.zh-Hant.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/xlf/Form1.cs.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/xlf/Form1.de.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/xlf/Form1.es.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/xlf/Form1.fr.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/xlf/Form1.it.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/xlf/Form1.ja.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/xlf/Form1.ko.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/xlf/Form1.pl.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/xlf/Form1.pt-BR.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/xlf/Form1.ru.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/xlf/Form1.tr.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/xlf/Form1.zh-Hans.xlf, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/xlf/Form1.zh-Hant.xlf
This is a fix for a regression in the WinForms templates. When they were ported to this repo these templates incorrectly include xlf files in the nuget packages for the templates.
Without the changes in this PR `dotnet new` will generate a bunch of unused files
=> do not include xlf files in the winforms templates

eng/ci.yml
Some unit tests are failing on helix machines that do not fail on the build machines. This change is to get us unblocked. We already run debug unit tests locally (for code coverage), so this is no different than what we already have, and integration tests are still running on helix.
Here's the fix from Matt Galbraith:
I’m pretty sure, having now run your test locally, what’s going on. Specifically, I think you’re running afoul of dialog handler, which is a thing we have on all the Helix Windows machines to dismiss things like modal invariant / debug assert dialogs and such.
We need this to prevent folks’ Checked and debug test runs from timing out and preventing logging of legitimate failures, but you need it to be gone. 
To disable it, you can choose to explicitly kill dhandler.exe …
=> disable helix unit tests for now

src/System.Windows.Forms/src/System/Windows/Forms/OSFeature.cs, src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleInformation.cs
The Themes feature is supported on operating systems since Windows Server 2003 (https://docs.microsoft.com/en-us/windows/desktop/api/uxtheme/nf-uxtheme-isappthemed)
Importantly, this does *not* necessarily mean that visual styles are enabled, but that they are present in the feature set.
If you look at the implementation of the `OSFeature` check for themes, we don't actually check if `IsAppThemed` returns `true`, but rather that it does not throw.. More specifically we check that it does not throw a `EntryPointNotFoundException`, which won't happen in .NET Core since we're supported since Windows 7
The actual check for whether visual styles are enabled is `VisualStyleInformation.IsEnabledByUser`
=> Remove dead code relating to support for themes

src/Common/src/Interop/Interop.Libraries.cs, src/Common/src/Interop/UxTheme/Interop.GetCurrentThemeName.cs, src/Common/src/Interop/UxTheme/Interop.GetThemeDocumentationProperty.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms/src/System.Windows.Forms.csproj, src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleInformation.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/VisualStyles/VisualStyleInformationTests.cs
- Avoid allocated a large `StringBuilder`. Instead use a stackallocated span. 512 is an appropriate size for stack allocation
- Move to the `Interop.XYZ` model to match .NET Foundation interop guidelines
=> Cleanup VisualStyleInformation interop

src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs
This change ensures Segoe UI is used by default on Windows Vista and later, while still not breaking compatibility with Windows XP or systems compatible with it. Fixes #524.
Note that while I have not yet been able to test the code in System.Design.Editors as requested in https://github.com/dotnet/winforms/issues/524#issuecomment-469832174 due to #632 not yet being merged, I have tested with the WinformsControlTest project, and all of its forms/controls (including the ThreadExceptionDialog) are sized properly to avoid clipping text, with _no_ changes needed. While I do not think any changes will be needed to the designer code either, I am willing to hold on this PR until that can be tested. Thanks!
=> Set Control.Defaultfont to SystemFonts.MessageBoxFont

src/Common/tests/CommonTestHelper.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/PrimitiveCodeDomSerializer.cs, src/System.Windows.Forms.Design/tests/UnitTests/Serialization/PrimitiveCodeDomSerializerTests.cs
Serializer was adding unnecessary casts to primitive expressions.
For example ((int)(42)) instead of 42.
=> Fixed CodeDOM serialization of primitives

src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests/TestHelpers.cs
- The integration tests were failing locally when there was no private sdk install (.dotnet folder) which happens when the version specified in the global.json is already installed machine-wide.
- This fixes the code to check for a private .dotnet install first, then look for a matching machine-wide one if a private one is not found.
=> allow integration tests to work with machine-wide installed dotnet sdk

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CommandSet.cs
As discovered in #1079 `parent` is incorrectly set, that essentially means it is always set to `null`.
The fix removes the redundant incorrect assignment.
Closes #1079.
=> fix: Incorrect parent assignment

build-local.ps1
Add a PowerShell script that simplifies and streamlines the UX around installing a new version of SDK and getting VS to pick it up.
Our local build scripts download and install a required version of SDK into a local folder (.\.dotnet\sdk). This is done to accommodate build infrastructure requirement.
VS is only loading SDKs from under C:\Program Files\dotnet\sdk folder. This folder is also protected and requires an elevation to write into it.
The script can be run as follows:
PS> .\build-local.ps1                   # to simply build and launch the solution in VS
PS> .\build-local.ps1 -FullClean        # resets the SDK and the local dev environment
The new script does a number of things:
- Checks whether the version of SDK required in global.json is installed both locally and system-wide. …
=> Streamline local dev configuration

eng/ci.yml
The dialog handler is most likely responsible for sporadically causing our unit tests to time out, since many of our tests open UI windows. The suggestion from dnceng was to disable it in this way.
=> disable helix dialog handler in ci builds

roadmap.md
This is currently a circular link to the wrong roadmap.
=> Fix link to .NET Core roadmap

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BindingContextTests.cs
Fixes #1104
Problem is that the entry contains a `WeakReference` and can be GC'ed
=> Fix flaky BindingContext tests

src/System.Windows.Forms.Design.Editors/src/System/Drawing/Design/FontNameEditor.cs
* Reduce the preview font size to provide a better visual parity with NET Fx since the change of the default font in Core.
* Prefer to align the preview to the bottom, if possible
* Remove a vertical line to the right of the preview box as it serves no purpose
Closes #1106
=> fix: Reduce preview font size

build-local.ps1
A follow up for https://github.com/dotnet/winforms/pull/1125
* Fix path to SDK (it should be `...\.dotnet` and not `...\.dotnet\sdk`)
* Use `%PROGRAMFILES%` variable instead of hardcoded path
* Remove changes to `%PATH%` - since we symlink local SDKs to the system-wide location (`%PROGRAMFILES%\dotnet\sdk`)  there is no reason to modify the `%PATH%` variable
* Create a symlink from the local `.\.dotnet\shared\Microsoft.NETCore.App\3.0.0-previewXXX` to the system-wide `%PROGRAMFILES%\dotnet\shared\Microsoft.NETCore.App\3.0.0-previewXXX`
=> Streamline local dev configuration, part 2

src/System.Windows.Forms.Design.Editors/src/Resources/SR.resx, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hant.xlf
Fixes #1076
- Add a missing new line to the resources
- Build a local version of System.Windows.Forms.Design.Editors.dll
- Copy to C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\3.0.0-preview6-27804-01
- Run the app
=> fix: [Loc] incorrect description text in MultilineStringEditor dropdown

src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
Fixes #1178. 
It needs review translation.
=> Accessibility: Fixing Name property of "Description” pane and "ToolBar" pane in PropertyGrid

Documentation/intellisense.md, Restore.cmd, eng/configure-toolset.ps1, eng/packageContent.targets, global.json
@AdamYoblick Here is a basic outline that on-boards the intellisense blob to your build process. You can build on top of this and add relevant targets to integrate the right xmls into your transport package. 
Feel free to close the PR and cherry-pick the relevant commit directly, or use the change shown here however you want.
=> Add intellisense blob as part of native toolset restore and integrate xmls into package

src/System.Windows.Forms/src/System/Windows/Forms/Application.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/HtmlElement.cs, src/System.Windows.Forms/src/System/Windows/Forms/Label.cs, src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs, src/System.Windows.Forms/src/System/Windows/Forms/StringSource.cs
CA2122 was an FxCop violation related to code access security. Removing them as CAS isn't supported in .NET Core. (And all of the CAS attributes have been removed.)
Also remove a no-op debug track of the AppDomain for window handles. Multiple AppDomains aren't supported in .NET Core.
=> Remove CAS related suppressions

Winforms.sln
I like that the other repo has a build folder with build-common and build-related files;
I also think there might be some use for a documentation folder; I did not really like having all of the solution-level stuff in their own folder because I don't think that meaningfully organizes them. I would prefer to divide stuff up in some way. This is just one way we could go
=> move solution items to build, documentation, or rmv them

src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/SystemInformation.cs
This parameter is actually used as out. Per https://docs.microsoft.com/en-us/dotnet/framework/interop/blittable-and-non-blittable-types these parameters must be marked as such ("you must apply the InAttribute and OutAttribute attributes if you want to marshal the argument as an In/Out parameter"). The code currently works, because it's taking advantage of the pinning optimization that the CLR does, otherwise it would be treated as "in" only. It will keep working the same with the extra metadata, but the metadata will be correct.
Hit this while running on a runtime that doesn't do the pinning optimization (and this annotation is a fix for that).
=> Mark pvBuffer as In/Out

src/Common/src/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2TypeInfoProcessor.cs
ELEMDESC doesn't contain a pointer. This fixes a regression introduced in #818.
Fixes #896
This particular bug is breaking Office interop on WPF and WinForms. Repro is to reference the following COM components:
- Microsoft.Office.Interop.Outlook
- Office
- stdole
In a WPF app, add the following to the main Window xaml:
``` xml
<ComboBox ItemsSource="{Binding}" DisplayMemberPath="DisplayName" Height="27" Width="332" />
```
And the following to the code behind for Window_Loaded:
``` C#
using Microsoft.Office.Interop.Outlook;
using Outlook = Microsoft.Office.Interop.Outlook;
// ...
private void Window_Loaded(object sender, RoutedEventArgs e)
{
List<Account> Accounts = new List<Account>();
Outlook.Application outlook = new Outlook.Application();
foreach (Account account in …
```
=> Fix COM interop ELEMDESC

src/Common/src/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2TypeInfoProcessor.cs
ELEMDESC doesn't contain a pointer. This fixes a regression introduced in #818.
Fixes #896
Has been approved for preview7. CC @JeremyKuhne @danmosemsft 
Cherry-pick of https://github.com/dotnet/winforms/pull/1254
=> Fix COM interop ELEMDESC (#1254)

src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
=> LOC CHECKIN | dotnet/winforms master | 20190702

src/System.Windows.Forms.Design.Editors/src/Properties/InternalsVisibleTo.cs, src/System.Windows.Forms.Design.Editors/src/Resources/StringCollectionEditor.resx, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/StringCollectionEditor.cs.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/StringCollectionEditor.de.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/StringCollectionEditor.es.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/StringCollectionEditor.fr.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/StringCollectionEditor.it.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/StringCollectionEditor.ja.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/StringCollectionEditor.ko.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/StringCollectionEditor.pl.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/StringCollectionEditor.pt-BR.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/StringCollectionEditor.ru.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/StringCollectionEditor.tr.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/StringCollectionEditor.zh-Hans.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/StringCollectionEditor.zh-Hant.xlf, src/System.Windows.Forms.Design.Editors/src/System.Windows.Forms.Design.Editors.csproj, src/System.Windows.Forms.Design.Editors/src/System/Windows/Forms/Design/StringCollectionEditor.cs, src/System.Windows.Forms/tests/IntegrationTests/WinFormsControlsClassicTests/WinFormsControlsClassicTests.csproj, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.Designer.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/UserControls/UserControlWithCollectionEditors.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/WinformsControlsTest.csproj
Closes #1270
- Port StringCollectionEditor from NET Fx
- Fix xml-docs
- Fix names
- Remove unused usings
- Remove `this.`
- Add missing braces
- Use arrow functions, where appropriate
- TODO
=> Fix 1270 port `StringCollectionEditor`

src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
Fixes #1300.
- Add static `LastKeyData` variable to store information about the last button or combination pressed by the user
- Change `forward` variable when call `GetNextItemHorizontal` method for ToolStrip
- Tab navigation: 1-2-9
- Shift-tab navigation: 9-7-1 (**8** is skipped because of it not the selectable item)
> Similarly RTL
- Tab navigation: 1-2-9
- Shift-tab navigation: 9-2-1
> Similarly RTL
=> Accessibility: Fixing ToolStrip shift-tab navigation

src/Common/src/CommonUnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs
**Issue:** When PMA mode is enabled, smart tag window does not render correctly or some of the options in the window are not accessible through mouse. It happens because of DPI awareness context mismatch between the control window and its corresponding mouse hook.
**Fix**: Determine DPI awareness context of the control window and set it in its mouse hook.
**Note:** This fix is a port from net fx runtime
**Testing done:** Since smart tags is a design time feature and is not supported by netcore designer yet, it cannot be tested. However I ran few sample netcore apps and ensured that there is no regression.
=> Porting bug fix: Smart Tag window does not render at all\correctly on secondary monitor when PMA is enabled

src/System.Windows.Forms/src/Resources/System/Windows/Forms/PrintPreviewDialog.resx, src/System.Windows.Forms/src/Resources/System/Windows/Forms/xlf/PrintPreviewDialog.cs.xlf, src/System.Windows.Forms/src/Resources/System/Windows/Forms/xlf/PrintPreviewDialog.de.xlf, src/System.Windows.Forms/src/Resources/System/Windows/Forms/xlf/PrintPreviewDialog.es.xlf, src/System.Windows.Forms/src/Resources/System/Windows/Forms/xlf/PrintPreviewDialog.fr.xlf, src/System.Windows.Forms/src/Resources/System/Windows/Forms/xlf/PrintPreviewDialog.it.xlf, src/System.Windows.Forms/src/Resources/System/Windows/Forms/xlf/PrintPreviewDialog.ja.xlf, src/System.Windows.Forms/src/Resources/System/Windows/Forms/xlf/PrintPreviewDialog.ko.xlf, src/System.Windows.Forms/src/Resources/System/Windows/Forms/xlf/PrintPreviewDialog.pl.xlf, src/System.Windows.Forms/src/Resources/System/Windows/Forms/xlf/PrintPreviewDialog.pt-BR.xlf, src/System.Windows.Forms/src/Resources/System/Windows/Forms/xlf/PrintPreviewDialog.ru.xlf, src/System.Windows.Forms/src/Resources/System/Windows/Forms/xlf/PrintPreviewDialog.tr.xlf, src/System.Windows.Forms/src/Resources/System/Windows/Forms/xlf/PrintPreviewDialog.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/System/Windows/Forms/xlf/PrintPreviewDialog.zh-Hant.xlf
Fixes #1353 
- Removing "button" text from PrintButton control's Accessible name to have "Print" accessible name instead of "Print button".
- Updating resource string for PrintButton AccessibleName.
- Reassigning to translators for updating localized strings.
Please see the bug #1353 
- Narrator announcement
- Inspect tool
Narrator announces "Print button" with the fix and "Print button, button" without the fix.
Inspect shows "Print" instead of "Print button" as accessible name property.
Version:   3.0.100-preview8-012929
Commit:    795f8aeaa8
OS Version:  10.0.18362
Base Path:   C:\Program Files\dotnet\sdk\3.0.100-preview8-012929\
=> Fix 1353 Accessibility: Removing 'button' text from PrintButton accessible name of PrintPreviewDialog

eng/Version.Details.xml, eng/Versions.props, eng/common/SigningValidation.proj, eng/common/performance/perfhelixpublish.proj, eng/common/performance/performance-setup.ps1, eng/common/performance/performance-setup.sh, eng/common/pipeline-logging-functions.ps1, eng/common/post-build/nuget-validation.ps1, eng/common/post-build/promote-build.ps1, eng/common/post-build/trigger-subscriptions.ps1, eng/common/sdl/execute-all-sdl-tools.ps1, eng/common/sdl/extract-artifact-packages.ps1, eng/common/sdl/packages.config, eng/common/sdl/run-sdl.ps1, eng/common/templates/job/execute-sdl.yml, eng/common/templates/job/performance.yml, eng/common/templates/job/publish-build-assets.yml, eng/common/templates/post-build/channels/internal-servicing.yml, eng/common/templates/post-build/channels/public-release.yml, eng/common/templates/post-build/channels/public-validation-release.yml, eng/common/templates/post-build/common-variables.yml, eng/common/templates/post-build/post-build.yml, eng/common/templates/post-build/promote-build.yml, eng/common/templates/post-build/setup-maestro-vars.yml, eng/common/templates/post-build/trigger-subscription.yml, eng/common/templates/steps/perf-send-to-helix.yml, eng/common/tools.ps1, global.json
Manual update since maestro didn't seem to triggering https://github.com/dotnet/winforms/pull/1309
@AdamYoblick @RussKie @zsd4yr
=> Update to build '20190717.6' of 'https://github.com/dotnet/arcade'

eng/Versions.props, src/Common/tests/CommonTestHelper.cs, src/System.Windows.Forms/src/System/Windows/Forms/Layout/DockAndAnchorLayout.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HScrollBarTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollBarTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/VScrollBarTests.cs
I removed the `Debug.Assert` in `DockAndAnchorLayout.SetAnchor` because it is a genuinely invalid. For example, in `Anchor_Set_TestData()`:
```cs
public static IEnumerable<object[]> Anchor_Set_TestData()
{
// ...
yield return new object[] { (AnchorStyles)(-1), AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right };
yield return new object[] { (AnchorStyles)int.MaxValue, AnchorStyles.Top | AnchorStyles.Bottom | AnchorStyles.Left | AnchorStyles.Right };
}
[Theory]
[MemberData(nameof(Anchor_Set_TestData))]
public void Control_Anchor_Set_GetReturnsExpected(AnchorStyles value, AnchorStyles expected)
{
var control = new Control
{
Anchor = value
};
Assert.Equal(expected, control.Anchor);
Assert.Equal(DockStyle.None, control.Dock);
// Set same.
control.Anchor = value; …
```
=> Add more Control tests

src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewBand.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewElement.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewHeaderCell.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowCollection.cs
Prefer using `internal set` rather than `XInternal` properties
=> Cleanup access levels in DataGridViewElement and subclasses

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/EventHandlerService.cs
This change makes the test accessor fully transparent for testing purposes.
=> Field accessors for tests should return by reference

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/ComponentEditorPageTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PanelTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollBarTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
Fixes tests broken in VS only. Assert.Same does not work in VS because xUnit MemberData is populated in a different AppDomain, which means the references are not equal.
Assert.Equal should be used for string compares anyway 😉
=> fixing tests broken in VS only

src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Printing/PrintPreviewControlTests.cs
Fixes #1396 
- Changing the default value of the PrintPreviewControl back color in HC mode. For the non-HC themes default back color remains unchanged. If back color is not default and thus should be serialized, then back color will take this custom color in both HC and non-HC mode.
- Default back color for the PrintPreviewControl in HC theme is changed to ControlDark.
- ControlDark color makes the color difference between work area and control's back contrast, this also makes the color difference between form background and control's back contrast as well.
Please see #1396 
- Manual testing in standard and different HC themes.
- Contrast comparison.
- Evaluation in accessibility contrast analyzer:
Contrast ratio for white:
Contrast ratio for black:
.NET Core SDK (reflecting any …
=> Fix 1396 Accessibility: High Contrast - PrintPreview - The border of the PrintPreviewControl is inconsistent in the four themes of High Contrast

eng/Versions.props
=> Remove RestoreSources from Versions.props since they now live in Nuget.config

src/System.Windows.Forms/src/System/Windows/Forms/KeyboardToolTipStateMachine.cs, src/System.Windows.Forms/tests/UnitTests/KeyboardTooltipStateMachineTests.cs
The dictionary of delegates isn't needed for this state machine's decision making. This improves perf and removes allocations from form startup.
Add some basic tests for hooking. Can't exercise the entire state machine in unit tests as it will fire timers and UI.
=> Simplify the tooltip state machine

src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs, src/System.Windows.Forms/tests/UnitTests/TextBoxTests.cs
Fixes #1110 
Fixes #1168
Fixes #1109
- PlaceholderText default value to ""
- Make PlaceholderText virtual to keep it consistent with the other properties (#1110)
- PlaceholderText is not used by accessibility (#1168)
- Use TextLength instead Text property when drawing PlaceholderText (#1109)
- PlaceholderText default value was null which was different from Text default value.
- PlaceholderText was not virtual.
- Text property was used in WM_PAINT which breaks VMWare infrastructure client.
- Text was set when AccessibilityObject is created even when no Text or PlaceholderText was set.
- PlaceholderText default value is "" to be consistent with Text default value.
- PlaceholderText is virtual.
- In WM_PAINT TextLength so Text property is not accessed.
- AccessibilityObject no longer set …
=> Fix several issues with PlaceholderText property

src/System.Windows.Forms/src/System/Windows/Forms/ToolstripProfessionalRenderer.cs
Fixes #1408
- Change background color for a drop-down menu item to a non-drop-down item background color (Change items color to the File color, see screenshots)
- .NET Core SDK (3.0.100-preview8-013392)
- Microsoft Windows [Version 10.0.18362.239]
=> Fixing background color for MenuStrip/ContextMenuStrip/ToolStrip items

Directory.Build.props, eng/Versions.props
We need this for the fix in https://github.com/tonerdo/coverlet/pull/375 to be taken in
Also add another test project exclusion
=> Fix coverlet code coverage

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripNumericUpDown.cs
Fixes #1470 
- Adding accessible name providing by ToolStripNumericUpDownAccessibleObject.
- Accessible name is provided by default when we are in MSAA mode.
- In UIA mode we need to explicitly provide accessible name.
- Accessible name is stored in Name property of AccessibleObject, passed it to the main UIA entry point - GetPropertyValue method. 
Please see #1470 
- Need an approval from QA team.
- Unit test to be implemented.
Version: 3.0.100-preview8-012929
Commit: 795f8aeaa8
OS Version: 10.0.18362
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\3.0.100-preview8-012929\
=> Fixing #1470: PageNumericUpDown accessible name is not correct

src/System.Windows.Forms/src/System/Windows/Forms/ButtonInternal/CheckableControlBaseAdapter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXFontMarshaler.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXVerbEnum.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.AmbientProperty.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.AxSourcingSite.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlNativeWindow.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlTabOrderHolder.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlVersionInfo.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.FontHandleWrapper.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.MetafileDCWrapper.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.MultithreadSafeCallScope.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.PrintPaintEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ThreadMethodEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/VScrollBar.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
Break out all of the nested classes in Control into separate files.
Pull most of the field names into line with coding styles.
Clean up some comments and collapse some code.
Remove dead code.
VS was choking with all of the style violations in Control. This should hopefully make working on Control a lot less painful and set us up for further cleanup.
No functional changes were made.
=> Break up Control class

src/System.Windows.Forms/src/System/Windows/Forms/DrawItemEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/DrawListViewColumnHeaderEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/DrawListViewItemEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/DrawListViewSubItemEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/DrawToolTipEventArgs.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DrawItemEventArgsTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DrawListViewColumnHeaderEventArgsTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DrawListViewItemEventArgsTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DrawListViewSubItemEventArgsTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DrawToolTipEventArgsTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/StatusBarDrawItemEventArgsTests.cs
We would throw NREs in all DrawXYZ methods.
Discussion of alternatives which I am very happy to consider
- Return (i.e. nop) if Graphics is null
- Throws ANE in the constructor of the event args
- Throw something like an InvalidOperationException in the draw methods
I preferred to do a `nop`, as it appears to me the intention would be not to draw anything if you don't pass any graphics to the event args
=> Fix NREs in Draw*EventArgs

src/System.Windows.Forms/tests/IntegrationTests/WinFormsControlsClassicTests/WinFormsControlsClassicTests.csproj
I opted to do it this way because it is an old-style project that only supports .NET Framework. Therefore by overriding `Build` to be a nop on Unix we can avoid failures in the build
Old error:
> /Users/hugh/Documents/GitHub/winforms/.dotnet/sdk/3.0.100-preview6-012264/Microsoft.Common.CurrentVersion.targets(1175,5): error MSB3644: The reference assemblies for .NETFramework,Version=v4.7.2 were not found. To resolve this, install the Developer Pack (SDK/Targeting Pack) for this framework version or retarget your application. You can download .NET Framework Developer Packs at https://aka.ms/msbuild/developerpacks [/Users/hugh/Documents/GitHub/winforms/src/System.Windows.Forms/tests/IntegrationTests/WinFormsControlsClassicTests/WinFormsControlsClassicTests.csproj]
=> Disable WinFormsControlsClassicTests.csproj on non-windows platforms

src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxEditingControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.cs
Fixes #1098 
- Reworking `DataGridViewCell.InitializeEditingControl()` method to delay EditingControlAccessibleObject initialization until DataGridView EditingControl is initialized and its handle is created.
- Delaying EditingControlAccessibleObject initialization is done by moving dgv.EditingControlAccessibleObject.get() call to dgv.EditingControl.HandleCreated event handler, so we have EditingControlAccessibleObject accessed only after the control's handle creation.
* For the first time control's handle is created when accessing EditingControlAccessibleObject.
* For the first time control's handle is created and the EditingControlAccessibleObject is accessed.
- Manual testing, debugging, Narrator announcement - passed.
- Need QA approval.
- Need to test near cases and search for …
=> The CellParsing event of the datagridview can't be invoked when changing the value of the cell firstly #1098

src/Common/src/NativeMethods.cs
[StructLayout] inadvertently got removed from an interop class that is being used like a struct.
Audited the other interop classes- they all have the attribute.
fixes #1558
Moving the mouse after changing some properties without committing can throw.
Yes
Very low
=> Add missing StructLayout

src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
Fixes #1556
- Verify that the underlying control contains children before attempting to query those.
- None
- No
- None
- manual runs with IDE attached breaking on `System.ArgumentException` to ensure no exceptions are thrown
- run Narrator to verify elements are still read correctly
=> fix: `AccessibleObject` throws 'Value does not fall within the expected range.' creating `CollectionEditor`

src/System.Windows.Forms/src/System/Windows/Forms/BindingContext.cs, src/System.Windows.Forms/src/System/Windows/Forms/BindingSource.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BindingContextTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BindingSourceTests.cs
In this PR I fix a NullReferenceException in BindingContext for circular components without a BindableComponent and remove dead code
Fixes NRE. Now throws ArgumentException with a correct error message
No
Could break people who caught NRE - in practice unlikely and not something we consider breaking.
Added new unit tests
=> Fix some Binding bugs

src/System.Windows.Forms.Design/src/Resources/SR.resx, src/System.Windows.Forms.Design/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataMemberFieldConverter.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DataMemberFieldConverterTests.cs, src/System.Windows.Forms/src/AssemblyRef.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumn.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxColumn.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListControl.cs
Porting DataMemberFieldConverter to System.Windows.Forms.Design.dll and changing the references from System.Design to this assembly wherever required. 
Fixes #1542
**Proposed changes**
- Porting DataMemberFieldConverter into core. 
**Customer Impact**
- Some of the winforms properties have added this converter as member attribute and thus use of those properties, by third party applications, resulting in 'MissingMethodExceptions'.
**Regression?**
Yes
**Risk**
None
**Screenshots 
Before**
**After**
No Exception.
=> Porting DataMemberFieldConverter into core

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/SnapLine.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/Behavior/SnapLineTests.cs
Closes #1412
* Port the functionality from NET Fx
* Discover and fix an old bug that incorrectly compared `MarginBottom` filter against `MarginTop OR PaddingBottom`
* Fix incorrect spacing in `ToString` implementation
* Add unit tests as well.
- More things working, less throwing `NotImplementedException`
- No
- None, unless the ported code is buggy
- Designer to provide real testing
=> fix SnapLine is not implemented

src/System.Windows.Forms/src/System/Windows/Forms/Screen.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScreenTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/SystemInformationTests.cs
Add tests for Screen and SystemInformation and fix NRE by adding argument validation in Screen static From* methods
ANE instead of NRE
No
Could break people who catch NRE but this is unlikely and not considered breaking
Unit tests included
=> Add Screen/SystemInformation tests 

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CursorTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScreenTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/SystemInformationTests.cs
Recently added tests are not multimonitor friendly. Screens frequently have negative coordinates. The common case is with the primary screen to the right of the secondary screen. The primary screen origin is 0,0. Anything to the left or above will have negative coordinates (including the virtual screen).
None- this is a test break.
No
None, test only change.
- Ran tests on multimonitor system
=> Fix screen related tests

src/System.Windows.Forms/src/System.Windows.Forms.csproj
So far System.Windows.Forms is the superset of Interop usage. There was one existing wildcard that wasn't properly defined, including all of interop as one wildcard to make continued work here easier (less conflicts, easier to add files).
If we need to exclude individual files we can add those explicitly. If needed we can break this out into individual subdirectories as well.
The other projects include only a subset of the interop definitions, so keeping those explicit.
None
No
Very low
- Built, ran tests.
=> Wilcard include interop files for System.Windows.Forms

global.json
We like to do this now and again so that we are:
1. building on latest bits aside from the RuntimeFrameworkVersion
1. demonstrating an up-to-date .NET sdk version global.json (are good examples to others looking to build on our stack)
1. find problems as a result of this earlier
This should be the last rev until we update to 3.1 RTM
=> update SDK used to build winforms to latest release channel SDK

src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/DataGridViewCellAccessibleObjectTests.cs
Fixes #1578 
- Override the IsReadOnly property for DataGridViewCell AccessibleObject
- The Narrator will say "readonly" for readonly cells
- No
- None, this is a minimal extension.
- Unit test (DataGridViewCellAccessibleObjectTests.cs) 
- Manual testing with using the Inspect tool
- Manual testing with using the Narrator
- .NET Core SDK: 3.0.0-preview9-19407-06
- Microsoft Windows [Version 10.0.18362.239]
=> Fixing DataGridViewCell AccessibleObject Value.IsReadOnly property

src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
Fixes #1582 
**Original bug:**
- [Bug 937670:](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/937670) [Screen Reader - SSMA - Create new project] Incorrect control type is defined for all menus like 'File and Edit and View and Tools...' on SSMA.
Fix the accessibility navigation tree for MenuStrip, ContextMenuStrip, ToolStrip, StatusStrip, BindingNavigator controls.
Implement ToolStrip behavior like as the Notepad:
- Implement ElementProviderFromPoint method for ToolStrip to the Inspect tool can get access to item's AccessibleObject when the mouse is over it
- Implement Accessible properties for ToolStripDropDown as menu
- Remove not localized DropDown name
- Change the fragment navigate to change accessibility tree
Items will not have children. Instead, the dropdown pane is in the …
=> Fixing menu control type and menu items navigation

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/Program.cs
Fixes #1634
- Set DPI mode to System Aware in the project templates
- Winforms applications will be system aware by default
- Customers can always change this behavior by modifying the program.cs
- No
- Very low
See https://github.com/dotnet/winforms-designer/pull/637
- Manual testing (instructions are at https://github.com/dotnet/winforms/blob/63a29cea7f717aea6b614dc3d5d317c4b7a996d4/pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/readme.md)
=> Set system aware mode in project templates c#

eng/Version.Details.xml, eng/Versions.props, src/System.Windows.Forms/src/System.Windows.Forms.csproj
Fixes error when building locally, but only with VS int-preview installed. Error looks like this:
```
C:\Program Files (x86)\Microsoft Visual Studio\2019\IntPreview\MSBuild\Current\Bin\Microsoft.Common.CurrentVersion.targets(3056,5): error : MSB3822: Non-string resources require the System.Resources.Extensions assembly at runtime, but it
was not found in this project's references. [E:\src\repos\github\winforms\src\System.Windows.Forms\src\System.Windows.F
orms.csproj]
```
- Add the package reference specified by the error
- None, the CI build is passing without this. This is only needed if you build locally with VS int-preview installed.
- Might be a regression on the VS side, we submitted a feedback ticket to find out
- Very low
=> Add system.resource.extensions as a dependency from corefx

src/Common/src/Interop/ComCtl32/Interop.TTDT.cs, src/Common/src/Interop/ComCtl32/Interop.TTTOOLINFOW.cs, src/Common/src/Interop/Interop.PARAM.cs, src/Common/src/Interop/Interop.WindowMessages.cs, src/Common/src/Interop/User32/Interop.SendMessageW.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridToolTip.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs, src/System.Windows.Forms/src/System/Windows/Forms/IHandle.cs, src/System.Windows.Forms/src/System/Windows/Forms/KeyboardToolTipStateMachine.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridToolTip.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/StatusBar.cs, src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolBar.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
The tooltip class will cause Windows to AV when attempting to get the tooltip bubble size when there isn't an actively showing tooltip. (Really Windows should be checking before derefing their internal pointer, but this has been there forever.) Fixing this by making sure to check that one is active when sending the query message.
The existing TooInfo usage was not safe and could crash with bad timing with a GC. I've hardened usage of the TTTOOLINFO struct and made it blittable, which should make things both safe and more performant as we're not instantiating a class anymore.
Fixes #1602.
- Refactor TTOOLINFO to guard against AVs
- Fix the explicit AV in #1602
- Won't easily AV
- Better performance
- Yes - Introduced in 4.8
- Reasonably low- it is much easier to reason about the code with …
=> Fix tooltip crash and harden

eng/ci.yml
Latest internal build is failing in SDL validation due to an arcade tool. 
https://dnceng.visualstudio.com/internal/_build/results?buildId=306069
This is a fix recommended by the arcade team to prevent the failure before the official arcade PR goes out.
This is build related, does not affect the shipping bits in any way, so it doesn't have to go to shiproom.
=> sdl validation fix while we wait for arcade PR

src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewDialog.cs
…ns contrasted.
Fixes #1421
- Disabling System RenderMode for the PrintPreview ToolStrip to prevent ToolStripSystemRenderer to draw buttons with not contrasted color in HC themes.
- The change works and is effective only in HC mode. To enable change the ToolStrip control should be recreated or app should be restarted in HC mode enabled environment.
- In non-HC mode environment RenderMode.System is enabled by default (as it was before)
- In HC mode PrintPreview ToolStrip buttons are enough contrasted.
- in non-HC mode PrintPreview ToolStrip buttons are rendered as before the change.
- App should be restarted to make the change effective if system HC mode is turned on/off.
- No
- Minimal
Please see the #1421 
- Awaiting QA approval.
- HC analyzer - contrast level is …
=> Disabling SystemRendering mode for ToolStrip in HC mode to make buttons contrasted

src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/ComboBoxAccessibleObjectTests.cs
_**Needs review translation!**_
Fixes #1691
**Original bug:**
- [Bug 956710:](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/956710) ToolbarStripContainer: (CoreTesting/edit '') The Name property of a focusable element must not be null.
- Add default accessible name ("_ComboBox_") for `ComboBox` edit element to resources
- Use a default accessible name if AccessibleName property value is null
- Narrator adds default accessible name when reading
- No
- None
- If no accessible name is given then it is null
- If no accessible name is given then it is the default
- The unit test: ComboBoxAccessibleObjectTests.cs 
- Using Narrator and Inspect tools
- .NET Core Version: 3.0.100-preview9-013722
- Microsoft Windows [Version 10.0.18362.295]
=> [Accessibility]: Fixing ToolStripComboBox/ComboBox edit element AccessibleName property value

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PowerStatusTests.cs
PowerStatus_BatteryChargeStatus_Get_ReturnsExpected was not correctly validating combination of flags.
The test was likely written on a workstation permanently connected to a power point. As a result the test did not account for combination of flags that can occur on laptops that are not permanently connected, e.g. if a laptop was being charged querying power would result in a combination of flags, such as `HIGH | CHARGING`.
Enhance the test to assert on combinations of valid flags.
- None, test change only
- No
- None, test change only
- manually running on a laptop partially discarged plugged and unplugged.
=> fix `PowerStatus_BatteryChargeStatus_Get_ReturnsExpected` test

src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/tests/IntegrationTests/WinFormsControlsClassicTests/WinFormsControlsClassicTests.csproj, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/RichTextBoxes.Designer.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/RichTextBoxes.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/RichTextBoxes.resx, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/RichTextBoxes.cs.xlf, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/RichTextBoxes.de.xlf, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/RichTextBoxes.es.xlf, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/RichTextBoxes.fr.xlf, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/RichTextBoxes.it.xlf, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/RichTextBoxes.ja.xlf, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/RichTextBoxes.ko.xlf, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/RichTextBoxes.pl.xlf, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/RichTextBoxes.pt-BR.xlf, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/RichTextBoxes.ru.xlf, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/RichTextBoxes.tr.xlf, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/RichTextBoxes.zh-Hans.xlf, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/xlf/RichTextBoxes.zh-Hant.xlf
Fixes #1631
Relates to #1139
The newer RichEdit controls (v4.1+) in specific cases had troubles detecting "friendly named" hyperlinks as the `Text` property was reportig less characters than the rage of the actual hyperlink.
- "friendly named" hyperlinks raise `LinkClicked` events in RichEdit v4.1+.
- Yes
- Low
- manual
-
=> fix: RichTextBox `LinkClicked` event for "friendly named" hyperlinks

src/Common/src/Interop/User32/Interop.SetClassLong.cs, src/Common/src/Interop/User32/Interop.SetWindowLong.cs, src/Common/src/UnsafeNativeMethods.cs, src/Common/tests/NoAssertContext.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.WindowClass.cs, src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs, src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs, src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/NativeWindowTests.cs
- Break NativeWindow subclass into separate file
- Fix naming
- Remove custom hashset
Following what is going on in NativeWindow is more confusing than it needs to be with the custom hashset implementation. Switching to Dictionary, which didn't exist when this code was originally written.
I have three commits to make this easier to follow. Note that I've other changes that build on this, moving more into Interop and using a WindowMessage enum as we do in the designer. (These will be follow up PR's in the future.)
=> Use Dictionary in NativeWindow

src/Common/src/Interop/UxTheme/Interop.GetThemeDocumentationProperty.cs, src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleInformation.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/VisualStyles/VisualStyleInformationTests.cs
This was a regression when we changed local variable from `StringBuilder` to `Span<char>` for optimization.
We allocate fixed size char that was a 'null terminated' and span.ToString() method was not trimming those null terminated chars.
This is causing all string comparisons that were converted from span<char> to fail.
for the end user, this means that accessibility strings will be wrong. And all users who use the public class `VisualStyleInformation`
Fixes #1597 
Trimming the string for 'null terminated' chars before returning.
Checked boxes rendering on menu strip, in customer application, behave differently  when Visual Styles or ON/OFF.
- Yes 
- Low
- manual validation of the scenario
=> Fixing ToolStripMenu  checked box rendering issue when Visual Styles are ON

src/Common/src/Interop/Interop.HRESULT.cs, src/Common/src/Interop/Ole32/Interop.CLSCTX.cs, src/Common/src/Interop/Ole32/Interop.CoCreateInstance.cs, src/Common/src/Interop/Ole32/Interop.CoGetClassObject.cs, src/Common/src/Interop/Ole32/Interop.IClassFactory2.cs, src/Common/src/Interop/Ole32/Interop.LICINFO.cs, src/Common/src/Interop/Ole32/Interop.OleInitialize.cs, src/Common/src/Interop/Ole32/Interop.OleUninitialize.cs, src/Common/src/Interop/Ole32/Interop.ReadClassStg.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design.Editors/src/Misc/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design.Editors/src/System.Windows.Forms.Design.Editors.csproj, src/System.Windows.Forms.Design.Editors/src/System/ComponentModel/Design/MultilineStringEditor.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/StringSource.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
- Cleanup CoCreateInstance/CoGetClassObject: don't use `PreserveSig` but instead use `HRESULT`s
- Fix OleInitialize incorrect definition (should take IntPtr not int)
- Fix OleUnitialize incorrect definition (should return `void` not int)
- Cleanup definition of `IClassFactory2`
- Structify `LICINFO`
=> Cleanup misc Ole32 interop

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/CategoryGridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
Fixes #1746
- Adding triggering ScreenReader announcement by raising UIA property changed event for ExpandedCollapsed automation property.
- Changed accessibility control type of Category items to TreeItem to allow announcement (as DataItem control type does not support ExpandCollapse property announcement: https://docs.microsoft.com/en-us/windows/win32/winauto/uiauto-controlpatternmapping 
- Screen reader users will get to know that if PropertyGrid Category item is expanded or collapsed.
- No
- Minimal
- Manual testing. Verified using Screen Reader apps.
- Unit tests implemented.
- QA verified.
Version:   3.0.100-preview8-012929
Commit:    795f8aeaa8
OS Version:  10.0.18362
RID: …
=> Fix issue 1746 - Screen reader is not announcing change in expanded/collapsed state of PropertyGrid Category item

src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/DataGridViewComboBoxCellAccessibleObjectTests.cs
Fixes #1703
- Adding ExpandCollapsePatternProvider to DataGridViewComboBox cell as corresponding cell has ComboBox control type. So adding pattern is obligatory.
- ExpandCollapsePattern is also presented in child ComboBox control: made the value of ExpandCollapseState synced between ComboBox and DataGridViewComboBoxCell.
- DataGridView UI will be more accessible for users with visual impairment. 
- Users will be notified about the control state during DataGridView cell navigation without necessity to expand/collapse the ComboBox.
- No, but conditionally is dependent on the changes with DataGridView (.NET Framework 4.7.2)
- Lowest.
- Manual testing, accessibility validation tools.
- Waiting for test results from QA.
- Automated tests and apps.
The change does not modify current UI itself, …
=> Fix issue 1703 - Adding ExpandCollapse pattern to DataGridViewComboBoxCell

src/Common/src/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/CategoryGridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/PropertyGridViewAccessibleObjectTests.cs
Fixes #1705
- Adding Grid and Table accessibility patterns to PropertyGridView child of PropertyGrid control.
- Adding GridItem and TableItem accessibility patterns to PropertyGrid entries.
- Implemented related accessibility properties to provide information about rows and columns.
- Users will be able to get more informative description about PropertyGrid control when navigating and entering data.
- PropertyGrid control becomes more accessible.
- No
- Low
- Manual testing: validation in accessibility tools.
- Need to add automation tests.
- Need to get approval from QA.
- No UI changes, only accessibility improvements.
Version: 3.0.100-preview8-012929
Commit: 795f8aeaa8
OS Version: 10.0.18362
OS Platform: …
=> Fix issue 1705 - Accessibility: PropertyGridView should support Table and Grid accessibility patterns

eng/CodeCoverage.proj, eng/Version.Details.xml, eng/Versions.props, global.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/Microsoft.Dotnet.Winforms.ProjectTemplates.csproj, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/Company.WinFormsApplication1.csproj, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/Company.ClassLibrary1.csproj, pkg/Microsoft.Private.Winforms/Microsoft.Private.Winforms.csproj, src/Accessibility/src/Accessibility.ilproj, src/Accessibility/ver/Accessibility-version.csproj, src/Common/tests/InternalUtilitiesForTests/InternalUtilitiesForTests.csproj, src/System.Design/src/System.Design.Facade.csproj, src/System.Drawing.Design/src/System.Drawing.Design.Facade.csproj, src/System.Drawing/src/System.Drawing.Facade.csproj, src/System.Windows.Forms.Design.Editors/src/System.Windows.Forms.Design.Editors.csproj, src/System.Windows.Forms.Design.Editors/tests/UnitTests/System.Windows.Forms.Design.Editors.Tests.csproj, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms.Design/tests/UnitTests/System.Windows.Forms.Design.Tests.csproj, src/System.Windows.Forms/src/System.Windows.Forms.csproj, src/System.Windows.Forms/tests/AccessibilityTests/AccessibilityTests.csproj, src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiButtonTests/MauiButtonTests.csproj, src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiComboBoxTests/MauiComboBoxTests.csproj, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/System.Windows.Forms.IntegrationTests.Common.csproj, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/TestHelpers.cs, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests/System.Windows.Forms.IntegrationTests.csproj, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/System.Windows.Forms.Maui.IntegrationTests.csproj, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/WinformsControlsTest.csproj, src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj
=> update TFM SDK, rev packages

src/System.Windows.Forms/src/System/Windows/Forms/Binding.cs, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests/Mocks/MainObject.cs, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests/WinformsControlsTest.cs
A regression introduced in #854 that resulted in making use of target control owner's `BindingManagerBase` instead of using the target control's own.
Fixes #1679
- Restore the original behavior
- Add tests 
- Bindings operate as expected
- Yes 
- Low
- manual
- CTI
=> fix: DataBindings.Remove/Clear unsubscribe from the INotifyPropertyChanged.PropertyChanged event

src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserHelper.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserSiteBase.cs
- Avoid allocations of COMRECT and instead use optional pointers
- Harden code to invalid pointers passed
=> Cleanup COMRECT interop in some IOle interfaces

src/Common/src/Interop/User32/Interop.TME.cs, src/Common/src/Interop/User32/Interop.TrackMouseEvent.cs, src/Common/src/NativeMethods.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
- Convert to struct and update null checks to check for `default` instead
- Use `TrackMouseEvent` in `user32.dll` as this is available in all recent versions of Windows supported by .NET Core
=> Structify TRACKMOUSEEVENT

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ContainerControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridTableStyleTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/ComponentEditorPageTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FlowLayoutPanelTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HScrollBarTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PanelTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PictureBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollBarTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollableControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/VScrollBarTests.cs
- Add ListView tests and tests for other Control properties
Extracted from https://github.com/dotnet/winforms/pull/1925 
Fixes https://github.com/dotnet/winforms/pull/1935
=> Add ListView tests and tests for other Control properties

Documentation/winforms-designer.md
Docs only update for Master - updating current docs to point more obviously to the Core Designer or Framework Designer.
=> Make the Core Designer part of the doc

src/Common/src/Interop/Kernel32/Interop.GMEM.cs, src/Common/src/Interop/Kernel32/Interop.GlobalAlloc.cs, src/Common/src/Interop/Kernel32/Interop.GlobalFree.cs, src/Common/src/Interop/Kernel32/Interop.GlobalLock.cs, src/Common/src/Interop/Kernel32/Interop.GlobalReAlloc.cs, src/Common/src/Interop/Kernel32/Interop.GlobalSize.cs, src/Common/src/Interop/Kernel32/Interop.GlobalUnlock.cs, src/Common/src/Interop/Ole32/Interop.OleFlushClipboard.cs, src/Common/src/Interop/Ole32/Interop.OleGetClipboard.cs, src/Common/src/Interop/Ole32/Interop.OleSetClipboard.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/Clipboard.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/Printing/PageSetupDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintDialog.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs
- Cleanup Ole32 Clipboard and HGlobal related interop
- Add Clipboard tests
- Fix #1951
=> Cleanup clipboard interop and add tests

src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/DocComment.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/HotCommands.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
Fixes #1864
- Added providing indexable accessible name for PropertyGrid control (by default). New default accessible name equals to default control name, for instance "propertyGrid1", "propertyGrid2" and so on.
- Added providing indexable accessible name for PropertyGrid's inner table.
- With the fix available, multiple tables in Form have different names. Screen reader will also announce PropertyGrid's names and table names correctly..
- No
- Low
- Manual testing. Tools: Inspect, Accessibility insights.
- Automation, need QA approval.
- Unit tests (to be implemented)
2.1.700-preview-009601 [C:\Program Files\dotnet\sdk]
2.1.801 [C:\Program Files\dotnet\sdk]
3.0.100-preview8-012929 [C:\Program Files\dotnet\sdk]
3.0.100-preview9-014004 [C:\Program Files\dotnet\sdk]
.NET Core runtimes …
=> Fix issue 1864 - Different accessible names for property grids

src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewButtonCell.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewImageCell.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewLinkCell.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxCell.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellTests.cs
Fixes #1680
**Original bug:**
- [Bug 528682:](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/528682) Accessibility: WinForm DataGridView's CellErrorTextNeeded tooltip data isn't accessible to customers only using the keyboard
- Implement `IKeyboardToolTip` interface for `DataGridViewCell` class to use the `KeyboardToolTipStateMachine`
- Add `ProcessControlShiftF10Keys` method to have the ability to activate/deactivate a cell tooltip using hotkeys (Control+Shift+F10 like as WPF)
- Add `IsActivatedByKeyboard` property which stores keyboard tooltip state
- Add `KeyboardToolTip` property which stores keyboard tooltip info and settings
> - Propose to set for the keyboard tooltip `InitialDelay` and `ReshowDelay` equal to 0.5 seconds (see gif below).
- <del>Add [**_public …
=> [Keyboard][Accessibility]: Fixing activation DataGridView cell tooltips with using a keyboard

src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs
Fixes #1951
A cherry pick of the fix applied to the master 13c624b13e5a890f2d43c458dad503466d278aca
- Fix to a common mistake when switching from a string building API that wasn't sized to a sized one and ending up with garbage at the end. 
- With the fix retrieval of HTML data from the clipboard will only have the expected data.
- Yes
- Minimal
- unit tests
=> Fix 1951 clipboard.get text adds garbage terminator

src/Common/src/Interop/OleAut32/Interop.GetErrorInfo.cs, src/Common/src/Interop/OleAut32/Interop.IErrorInfo.cs, src/Common/src/Interop/OleAut32/Interop.ISupportErrorInfo.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
- Cleanup `IErrorInfo` and `ISupportErrorInfo`
- Fix bug where we'd get the error info even if we didn't support it. According to the docs, if `ISupportErrorInfo::InterfaceSupportsErrorInfo method` returns `S_FALSE` then it is not supported so we shouldn't get the `IErrorInfo` which would throw
/cc @JeremyKuhne for the interop fix :)
=> Cleanup IErrorInfo and ISupportErrorInfo

src/Common/src/Interop/User32/Interop.GetKeyState.cs, src/Common/src/Interop/User32/Interop.HARDWAREINPUT.cs, src/Common/src/Interop/User32/Interop.INPUT.cs, src/Common/src/Interop/User32/Interop.INPUTENUM.cs, src/Common/src/Interop/User32/Interop.KEYBDINPUT.cs, src/Common/src/Interop/User32/Interop.KEYEVENTF.cs, src/Common/src/Interop/User32/Interop.MOUSEEVENTF.cs, src/Common/src/Interop/User32/Interop.MOUSEINPUT.cs, src/Common/src/Interop/User32/Interop.SendInput.cs, src/Common/src/Interop/User32/Interop.VK.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ComponentTray.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/RadioButton.cs, src/System.Windows.Forms/src/System/Windows/Forms/SendKeys.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs
- Move `INPUT`, `MOUSEINPUT` and `KEYBDINPUT` to Interop
- Cleanup `VK_` constants
- Cleanup `GetKeyState`
- Cleanup `SendInput`
- Avoid allocating arrays, prefer stackallocated `Span<INPUT>`
=> Cleanup INPUT related interop

src/Common/src/Interop/ComCtl32/Interop.ICC.cs, src/Common/src/Interop/ComCtl32/Interop.InitCommonControls.cs, src/Common/src/Interop/ComCtl32/Interop.InitCommonControlsEx.cs, src/Common/src/NativeMethods.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridToolTip.cs, src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs, src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs, src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs, src/System.Windows.Forms/src/System/Windows/Forms/ImageListStreamer.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs, src/System.Windows.Forms/src/System/Windows/Forms/ProgressBar.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridToolTip.cs, src/System.Windows.Forms/src/System/Windows/Forms/StatusBar.cs, src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolBar.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs, src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
- Cleanup `InitCommonControls` and `InitCommonControlsEx`
- Cleanup enum usages
- Structify `INITCOMMONCONTROLSEX`
=> Cleanup InitCommonControls and InitCommonControlsEx

src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs
Fixes #
Text box scenario -
a form with 2 textboxes with ImeMode property set to NoControl. In CHS pinyin keyboard, when focus moves to the second textbox, ImeMode is unexpectedly turned off and ENG characters are typed in.
ComboBox scenario - 
1.	Form has 3 controls - TextBox, RadioButton and a CombBox, all with IMEMode property set to NoControl (this means they get the current OS IME mode)
2.	CHS Pinyin is set in the OS (Window key + space bar), before the app is started
3.	When the app is started, user moves focus with mouse from textbox to radio button and then to the ComboBox, 
Result - ComboBox shows ENG characters instead of the IME. 
textbox - reverted an old change that regressed this scenario
Combobox - not a regression. The fix is to propagate the WM_SETFOCUS message to the …
=> ImeMode.NoControl in Text and Combo boxes on CHS pinyin was switching to ENG

src/Common/src/Interop/OleAut32/Interop.OCPFIPARAMS.cs, src/Common/src/Interop/OleAut32/Interop.OleCreatePropertyFrameIndirect.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
- Cleanup `OleCreatePropertyFrameIndirect`
- Cleanup and structify `OCPFIPARAMS`
=> Cleanup OleCreatePropertyFrameIndirect

src/Common/src/UnsafeNativeMethods.cs
Extracted from https://github.com/dotnet/winforms/pull/1961
- `IEnumConnectionPoints` is unused
- `ITypeComp` is unused
- `ITypeLib` is unused
=> Remove unused interop interfaces

src/Common/tests/InternalUtilitiesForTests/src/BinarySerialization.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/SerializableAttributeTest.cs, src/System.Windows.Forms.Design/tests/UnitTests/SerializableAttributeTests.cs, src/System.Windows.Forms/tests/UnitTests/SerializableAttributeTests.cs
As discovered in #1133, our tests checking types with `SerializableAttribute` were made a little too greedy and considered compiler-generated types.
Relax the tests to only verify no `SerializableAttribute` applied to user-generated types
- None, tests related changes
/cc: @kpreisser
=> Scope `EnsureSerializableAttribute` tests to user-generated types

src/Common/src/Interop/User32/Interop.GetDoubleClickTime.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/SystemInformation.cs
- Cleanup GetDoubleClickTime and correct interop definition to be uint not int
=> Cleanup GetDoubleClickTime

src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs
- We initialize `originals` to non-null directly above
=> Removed dead code from ImageList

src/Common/src/ExternDll.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design.Editors/src/Misc/ExternDll.cs, src/System.Windows.Forms/src/System/Windows/Forms/SystemInformation.cs
- Cleanup GetComputerName and make unicode
- Cleanup GetUserName and make unicode
Existing tests
```cs
[Fact]
public void SystemInformation_ComputerName_Get_ReturnsExpected()
{
string name = SystemInformation.ComputerName;
Assert.InRange(name.Length, 1, 256);
Assert.Equal(name, name.Trim('\0'));
Assert.Equal(name, SystemInformation.ComputerName);
}
[Fact]
public void SystemInformation_UserName_Get_ReturnsExpected()
{
string name = SystemInformation.UserName;
Assert.InRange(name.Length, 1, 256);
Assert.Equal(name, name.Trim('\0'));
Assert.Equal(name, SystemInformation.UserName);
}
```
=> Cleanup ComputerName and UserName interop

src/Common/src/Interop/VSSDK/Interop.ICategorizeProperties.cs, src/Common/src/Interop/VSSDK/Interop.PROPCAT.cs, src/Common/src/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2ICategorizePropertiesHandler.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2Properties.cs
- Cleanup ICategorizeProperties to match interop standards
- Remove catch blocks from these interop code as 1) they are bad code smell and 2) they are not necessary as the interface methods are `PreserveSig` and should not throw
=> Cleanup ICategorizeProperties

src/Common/src/Interop/Shell32/Interop.AUTOCOMPLETEOPTIONS.cs, src/Common/src/Interop/Shell32/Interop.IAutoComplete2.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/AutoCompleteMode.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/StringSource.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs
- Cleanup IAutoComplete2 interface
- Harden against invalid pointers
- Check HRESULTs rather than catch throwing PInvokes
=> Cleanup IAutoComplete2

src/Microsoft.VisualBasic/tests/IntegrationTests/Microsoft.VisualBasic.IntegrationTests/InteractionTests.cs
Fixes failing Microsoft.VisualBasic.IntegrationTests.
Handle the case where test modal dialog is closed automatically.
None.
Test regression in https://github.com/dotnet/winforms/commit/187f3007da2d64e43ce38e50bc57bbea9850ad8a
Low. This is a test change only.
=> Handle case where modal dialog is closed automatically

src/Common/src/Interop/User32/Interop.CallNextHookEx.cs, src/Common/src/Interop/User32/Interop.HC.cs, src/Common/src/Interop/User32/Interop.HOOKPROC.cs, src/Common/src/Interop/User32/Interop.SetWindowsHookExW.cs, src/Common/src/Interop/User32/Interop.UnhookWindowsHookEx.cs, src/Common/src/Interop/User32/Interop.WH.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/SendKeys.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs
- Turn HC_ constants into enum
- Cleanup SetWindowsHookEx and made unicode
- Cleanup CallNextHook
- Cleanup UnhookWindowsHookEx
=> Cleanup Hook functions

src/Common/src/ExternDll.cs, src/Common/src/Interop/Interop.BOOLEAN.cs, src/Common/src/Interop/Interop.Libraries.cs, src/Common/src/Interop/Kernel32/Interop.GetSystemPowerStatus.cs, src/Common/src/Interop/Kernel32/Interop.SYSTEM_POWER_STATUS.cs, src/Common/src/Interop/Powrprof/Interop.GetTickCount.cs, src/Common/src/Interop/Powrprof/Interop.SetSuspendState.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design.Editors/src/Misc/ExternDll.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.cs, src/System.Windows.Forms/src/System/Windows/Forms/PowerStatus.cs
- Cleanup GetPowerStatus
- Cleanup SetPowerStatus
=> Cleanup PowerStatus interop

src/Common/src/Interop/User32/Interop.CreateMenu.cs, src/Common/src/Interop/User32/Interop.CreatePopupMenu.cs, src/Common/src/Interop/User32/Interop.DestroyMenu.cs, src/Common/src/Interop/User32/Interop.EnableMenuItem.cs, src/Common/src/Interop/User32/Interop.GetMenu.cs, src/Common/src/Interop/User32/Interop.GetMenuItemCount.cs, src/Common/src/Interop/User32/Interop.GetMenuItemID.cs, src/Common/src/Interop/User32/Interop.GetSubMenu.cs, src/Common/src/Interop/User32/Interop.GetSystemMenu.cs, src/Common/src/Interop/User32/Interop.MF.cs, src/Common/src/Interop/User32/Interop.RemoveMenuItem.cs, src/Common/src/Interop/User32/Interop.SC.cs, src/Common/src/Interop/User32/Interop.SetMenu.cs, src/Common/src/Interop/User32/Interop.SetMenuDefaultItem.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/MDIControlStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/MainMenu.cs, src/System.Windows.Forms/src/System/Windows/Forms/Menu.cs, src/System.Windows.Forms/src/System/Windows/Forms/MenuItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/MenuStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownMenu.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs, src/System.Windows.Forms/tests/UnitTests/MainMenuTestsTests.cs, src/System.Windows.Forms/tests/UnitTests/MenuTests.cs
- Cleanup Menu related interop
- Add some menu tests
=> Cleanup Menu related interop

src/Common/src/Interop/ComCtl32/Interop.NMTVDISPINFOW.cs, src/Common/src/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
- Turn NMTVDISPINFOW into a (blittable) struct
- Rename to NMTVDISPINFOW
- Move to interop
https://docs.microsoft.com/en-us/windows/win32/api/commctrl/ns-commctrl-nmtvdispinfow
=> Structify NMTVDISPINFOW

eng/Shipping.ruleset, src/Common/src/OsVersion.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DragAssistanceManager.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/SnapLine.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripKeyboardHandlingService.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGrid.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridTableStyle.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnHeaderCell.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxEditingControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Layout/DockAndAnchorLayout.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/MdiWindowListStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/MenuItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/NumericUpDown.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs, src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/SplitContainer.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitStackLayout.cs, src/System.Windows.Forms/tests/UnitTests/OsVersionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComponentModel/Com2Interop/Com2PropertyDescriptorTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollableControlTests.cs
- fix warning SA1408: Conditional expressions should declare precedence
As per docs `&&` operator has precedence over `||` and thus the following changes are to increase readability and make SCA happy. The code was correct, it could not have been interpreted any different. 
- `ScrollableControl.SetDisplayRectLocation` had an incorrect order of precedence by which a `ScrollWindowEx` message could get sent to the control even though the control did not have a valid handle.
Fixes #1955
- `COM2PropertyDescriptor.SetValue` had an incorrect order of precedence that would lead to IOORE if error info string was empty.
Extract the code in question in a standalone method so it could be tested. After the tests, the implementation is rewritten to reduce allocations.
An alternative and significantly …
=> Fix conditional order of precedence

src/Common/src/Interop/User32/Interop.BlockInput.cs, src/Common/src/Interop/User32/Interop.EVENTMSG.cs, src/Common/src/Interop/User32/Interop.GetAsyncKeyState.cs, src/Common/src/Interop/User32/Interop.GetKeyboardState.cs, src/Common/src/Interop/User32/Interop.OemKeyScan.cs, src/Common/src/Interop/User32/Interop.SetKeyboardState.cs, src/Common/src/NativeMethods.cs, src/Common/src/SafeNativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/SendKeys.cs
- Cleanup GetKeyboardState/SetKeyboardState
- Cleanup BlockInput
- Cleanup GetAsyncKeyState
- Cleanup OemKeyScan
- Structify EVENTMSG
=> Cleanup SendKeys interop

src/Common/src/Interop/Ole32/Interop.OLEINPLACEFRAMEINFO.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserSiteBase.cs
- Rename tagOIFI to OLEINPLACEFRAMEINFO
- Structify
- Cleanup
https://docs.microsoft.com/en-us/windows/win32/api/oleidl/ns-oleidl-oleinplaceframeinfo
=> Rename and structify OLEINPLACEFRAMEINFO

src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.MetafileDCWrapper.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/Label.cs, src/System.Windows.Forms/src/System/Windows/Forms/Panel.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/WinFormsUtils.cs
- Remove new HandleRef(null, ...) usage in Control.PrintToMetaFile
- Update dependencies to use IntPtr instead of HandleRef because a `new HandleRef(null, HDC)` has the same meaning as `HDC`
=> Remove new HandleRef(null, ...) usage in Control.PrintToMetaFile

src/Common/src/NativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CommandSet.cs
- Remove duplicate GetCursor/GetCursorPos interop
=> Remove duplicate GetCursor interop

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
Fixes #1986 
- Adding tests SelectedGridEntry property and selectedGridEntry field for null before accessing their properties.
- In some conditions (recreating PropertyGrid) slectedGridEntry may be null and accessing its property leads to NullReference exception. Added the tests where this is necessary.
- Before the fix customers may experience application crash in case there are the conditions leading to accessing null-value selected grid entry (submitting new value to the field by enter-press)
- No
- None
App crash with the following stack:
Callsatcks:
```cs
System.Windows.Forms.dll!System.Windows.Forms.PropertyGridInternal.PropertyGridView.GridViewEdit.ProcessDialogKey(System.Windows.Forms.Keys keyData) Unknown
System.Windows.Forms.dll!System.Windows.Forms.PropertyGridInternal.PropertyG …
```
=> Adding test for null for PropertyGridView's SelectedGridEntry

src/Common/src/Interop/Ole32/Interop.IOleContainer.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.AxSourcingSite.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserContainer.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserSiteBase.cs
- Cleanup IOleContainer interface: use HRESULT, move to Ole32, use BOOL
- Follow interop guidelines: remove arrays, use pointers
=> Cleanup IOleContainer

src/System.Windows.Forms.Design.Editors/src/Resources/SR.resx, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms.Design.Editors/src/System/Drawing/Design/IconEditor.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/EnsureEditorsTests.cs, src/System.Windows.Forms/src/System/Drawing/Design/UITypeEditor.cs
Port Icon Editor for 3.1
Closes #2020
=> Port IconEditor; add test

src/System.Windows.Forms.Design.Editors/src/System/Windows/Forms/Design/TabPageCollectionEditor.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/EnsureEditorsTests.cs
=> Port TabPageCollectionEditor; enable test

src/Common/src/Interop/ComCtl32/Interop.NMTOOLBARW.cs, src/Common/src/Interop/ComCtl32/Interop.TB.cs, src/Common/src/Interop/ComCtl32/Interop.TBBUTTON.cs, src/Common/src/Interop/ComCtl32/Interop.TBBUTTONINFOW.cs, src/Common/src/Interop/ComCtl32/Interop.TBIF.cs, src/Common/src/Interop/ComCtl32/Interop.TBSTATE.cs, src/Common/src/Interop/ComCtl32/Interop.TBSTYLE.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolBar.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolBarButton.cs
- Cleanup NMTOOLBAR
- Cleanup TBBUTTONINFOW
- Cleanup TBBUTTON
=> Cleanup NMTOOLBARW/TBBUTTONINFOW/TBBUTTON

src/Common/src/Interop/Richedit/Interop.SEL.cs, src/Common/src/Interop/Richedit/Interop.SELCHANGE.cs, src/Common/src/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBoxConstants.cs
- Structify SELCHANGE
- Correct definition to use `WORD` instead of `int`
=> Structify SELCHANGE

src/Common/src/Interop/User32/Interop.SetCapture.cs, src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGrid.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/SplitContainer.cs, src/System.Windows.Forms/src/System/Windows/Forms/Splitter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs, src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.cs
CaptureInternal was only necessary for perf on framework as the public property asserted code permissions. Removed it and cleaned up some comments around the changed code. Also removed the unnecessary HandleRef.
=> Clean up Capture method

eng/ci.yml
Fixes #2068
- Clean up yaml variables
- Only build debug config in public builds
- See https://github.com/dotnet/winforms-designer/pull/963 for related change in designer repo
- None, infra only
- No
- Low
- CI build, private build won't run until PR gets merged
=> clean up variables, and only build debug in public builds

src/System.Windows.Forms/src/System/Windows/Forms/Form.AccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
- Form doesn't support UIA so it blocks #2074 because Narrator can't announce tooltip text if no controls on a form don't support UIA provider.
- Set SupportsUiaProviders property as true
- Use FormAccessibleObject as AccessibleObject instead default
**This allows customizing Form AccessibleObject how we want. 
For example, fix UIA navigation in the accessibility tree. It changes the focus order of Narrator. 
Form AccessibleObject works as before.**
- <del>Improved Bounds</del> No
- No
- No
- Using Inspect tool
- .NET Core Version: 3.1.0-preview1.19458.7
- Microsoft Windows [Version 10.0.18362.356]
=> Implementing UIA supporting for Form control

src/Common/src/Interop/Ole32/Interop.ELEMDESC.cs, src/Common/src/Interop/Ole32/Interop.FUNCDESC.cs, src/Common/src/Interop/Ole32/Interop.IDLDESC.cs, src/Common/src/Interop/Ole32/Interop.PARAMDESC.cs, src/Common/src/Interop/Ole32/Interop.TYPEATTR.cs, src/Common/src/Interop/Ole32/Interop.TYPEDESC.cs, src/Common/src/Interop/Ole32/Interop.VARDESC.cs, src/Common/src/NativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2TypeInfoProcessor.cs
- Extract `ELEMDESC`, `IDLDESC`, `PARAMDESC`, `TYPEDESC`, `VARDESC` and friends to `Interop.Ole32` namespace
- Structify `DISPPARAMS`
=> Extract misc Ole32 data types

eng/ci.yml
Disable SDL validation to unblock the 3.1-preview2 builds
=> Disable SDL validation in release/3.1

src/System.Design/src/System.Design.Forwards.cs, src/System.Windows.Forms.Design.Editors/src/Resources/SR.resx, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms.Design.Editors/src/System/Windows/Forms/Design/ListControlStringCollectionEditor.cs
Fixes #1271 
Have you experienced this same bug with .NET Framework?: No
- Add System.Windows.Forms.Design.ListControlStringCollectionEditor class
- Add resources for DataSourceLocksItem
- Implement TypeForwardedTo method
- Changed collection editor for controls which use ListControlStringCollectionEditor (TextBox, ComboBox, ListBox, etc.) to compliance with .Net 4.8.
- No
- No
- ComboBox (and others) has ObjectCollectionEditor as Items editor
- ComboBox (and others) has ListControlStringCollectionEditor as Items editor 
- .Net Core version: 3.1.0-preview1.19458.7
=> Porting System.Windows.Forms.Design.ListControlStringCollectionEditor

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
Fixes #1997 
- Adding test for null before announcement changed item details as changed item can be disposed in case Property grid is recreated on new value submit.
- Announcement is not broken and this case is rare. It is ok to not announce the value of disposed and recreated PropertyGrid.
- Customers will not experience application crash in case the PropertyGrid control can be recreated in Form lifecycle.
- Yes (before introducing announcements for PropertyGrid value updates there was no issue)
- None (just one additional null value test)
Crash stack:
```cs
System.Windows.Forms.dll!System.Windows.Forms.PropertyGridInternal.PropertyGridView.GridViewEdit.ProcessDialogKey(System.Windows.Forms.Keys keyData) Line 6808 C# Symbols loaded. …
```
=> Accessibility: NRE announcing changed item in `PropertyGrid`

src/System.Design/src/System.Design.Forwards.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/EnsureEditorsTests.cs
Fixes `release/3.1-uitypeeditors` branch unit tests to correct building.
- Remove `ImageIndexEditor` property test case because `TreeNode` hasn't this property
- Add `TypeForwardedTo` statements to get correct editors
- No, fixed only tests
- Low
- Unit tests
- .Net Core version: 3.1.0-preview1.19458.7
=> Fixing editors unit tests and the branch building

src/Common/tests/InternalUtilitiesForTests/InternalUtilitiesForTests.csproj, src/Common/tests/InternalUtilitiesForTests/src/NoAssertContext.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ApplicationTests.cs
The assert context listener would deadlock sometimes and wasn't particularly efficient. @weltkante discovered this in #2184 and encouraged me to rethink how to approach this.
Fixes #1999
=> Fix NoAssertContext deadlock

src/Common/src/NativeMethods.cs
- Remove some constants that seem to be unused. Alternatively, we could add the corresponding enum if they are needed for near-future changes.
=> Remove SHGFI constants

src/Common/src/Interop/Gdi32/Interop.RGBQUAD.cs, src/Common/src/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.MetafileDCWrapper.cs
- Move RGBQUAD from NativeMethods.cs to a separate file in Gdi32.
=> Move RGBQUAD struct to Gdi32

src/Common/src/Interop/User32/Interop.PostMessageW.cs
Fixes #1981
- Change PostMessageW return type from IntPtr to Interop.BOOL. It seems the return value is not currently used in NativeWindow.
=> Fix Interop.User32.PostMessageW return type

src/Common/src/Interop/Gdi32/Interop.GetPaletteEntries.cs, src/Common/src/Interop/Gdi32/Interop.PALETTEENTRY.cs, src/Common/src/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.MetafileDCWrapper.cs
- Add Interop.PALETTEENTRY struct.
- Replace usages of PALETTEENTRY with the above struct.
=> Use separate file for PALETTEENTRY in Gdi32

src/System.Design/src/System.Design.Forwards.cs, src/System.Windows.Forms.Design/src/Properties/InternalsVisibleTo.cs, src/System.Windows.Forms/src/AssemblyRef.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumn.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxColumn.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListControl.cs
Relates to #1545
Closes #2171
- Partially revert "Porting DataMemberFieldConverter" f477b2a
Whilst we do not support nor cant be expected to support customers who reference our internals, in some scenarios like `UITypeEditor`s and `TypeConverter`s may still be used by consumers to enhance their runtime experience. E.g. https://github.com/dotnet/winforms/pull/2078#discussion_r337777751
Type forward `DataMemberFieldConverter` to avoid breaking existing customers.
- Fixed for those porting .NET desktop apps to 3.0 and then to 3.1
- Unaffected for those porting .NET desktop apps to 3.1
- Yes
- None
=> Partially revert "Porting DataMemberFieldConverter"  f477b2a

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
Resolves #2122
Original https://github.com/dotnet/winforms/pull/2140
- `ToolStripImageIndexEditor` does not exist, replace it with `ImageIndexEditor`
=> Repalce `ToolStripImageIndexEditor` with `ImageIndexEditor`

src/System.Windows.Forms.Design.Editors/src/System/ComponentModel/Design/DateTimeEditor.cs
Fixes #2019
Related PR: #2165
Have you experienced this same bug with .NET Framework?: No
- Add System.ComponentModel.Design.DateTimeEditor class
- Changed DateTime editor to compliance with .Net 4.8.
- Yes
- Low
- TextBox editor:
- DateTime editor:
- .Net Core version: 3.1.0-preview1.19458.7
=> Porting System.ComponentModel.Design.DateTimeEditor

src/Common/src/Interop/Ole32/Interop.IOleClientSite.cs, src/Common/src/Interop/Ole32/Interop.OLEGETMONIKER.cs, src/Common/src/Interop/Ole32/Interop.OLEWHICHMK.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxContainer.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.OleInterfaces.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.AxSourcingSite.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserContainer.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserSiteBase.cs
- Cleanup IOleClientSite
- Introduce and use `OLEWHICHMK`/`OLEGETMONIKER` enums
- Make IOleObject.GetClientSite `PreserveSig` and remove associated catch blocks for COMException
=> Cleanup IOleClientSite

src/Common/src/Interop/UxTheme/Interop.MARGINS.cs, src/Common/src/NativeMethods.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
- Move MARGINS struct to a separate file in UxTheme.
=> Use separate file for MARGINS in UxTheme

src/System.Design/src/System.Design.Forwards.cs, src/System.Windows.Forms.Design.Editors/src/Resources/SR.resx, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms.Design.Editors/src/System/Windows/Forms/Design/ListViewSubItemCollectionEditor.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/EnsureEditorsTests.cs
Fixes #1277
- Add System.Windows.Forms.Design.ListViewSubItemCollectionEditor class
- Changed ListViewItems SubItems editor to compliance with .Net 4.8.
- Yes
- Low
- It made as in .Net 4.8:
- .Net Core version: 3.1.100-preview2-014533
=> Porting System.Windows.Forms.Design.ListViewSubItemCollectionEditor

src/Common/src/Interop/Ole32/Interop.ADVF.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- Move ADVF to `Interop.Ole32`.
- Make `IViewObject.SetAdvise` and `IViewObject.GetAdvise` `PreserveSig`
=> Cleanup ADVF constants

src/System.Design/src/System.Design.Forwards.cs, src/System.Windows.Forms.Design.Editors/src/System/Windows/Forms/Design/ListViewGroupCollectionEditor.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/EnsureEditorsTests.cs
Issue: `ListViewGroupCollectionEditor` from `System.Design` is missing.
- Add System.Windows.Forms.Design.ListViewGroupCollectionEditor class
- Changed ListViewGroup editor to compliance with .Net 4.8.
- Yes
- Low
- It made as in .Net 4.8:
- .Net Core version: 3.1.100-preview2-014533
=> Porting System.Windows.Forms.Design.ListViewGroupCollectionEditor 

src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
Fixes #2073
Original bug: [987952](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/987952)
- Add AnnounceText method to raise UIA notification (ScreenReader says notification text) when a tooltip is shown
<del>- Add IToolTip interface and implement it to unite elements (Control, ToolStripItem, DataGridViewElement) which can have a tooltip (this is necessary to the correct, simple and short implementation of raising UIA notification.)</del>
> ScreenReader reads the tooltip text of elements of in turn.
- A user can hear a text of a shown tooltip
- No
- No
- **A screen reader announces a text with a title of all tooltips (mouse and keyboard). &#x1F4D7;**
- Using NVDA and Narrator
- .NET Core Version: 3.1.0-preview1.19458.7
- Microsoft Windows [Version …
=> [Accessibility][ScreenReader]: Fixing tooltip text announcing by NVDA/Narrator

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
Fixes #1987
- Adding support for UI Automation ExpandCollapse pattern (added ExpandCollapse pattern provider) to PropertyDescriptorGridEntryAccessibleObject.
- Implementing Expand and Collapse action accessible UI and API via Expand and Collapse methods and via exposing ExpandCollapseState property.
- Refactoring accessible navigation methods to get parent PropertyGridView accessible object easier.
- Visually impaired customers will be able to distinguish expanded and collapsed ComboBox within the PropertyGrid control.
- Narrator and NVDA accessibility cline apps will announce expand and collapse actions of PropertyGrid ComboBox and the state of ComboBox.
- No
- Minimal
- Manual testing with Screen readers.
- Automation testing (to be performed)
- Unit tests (to be implemented)
- Verified …
=> [Accessibility] Adding announcement for PropertyGrid ComboBox Expand and Collapse actions

src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
- Change implementation of the `set` blocks of `ShowCellToolTips` and `ShowCellErrors` properties in `DataGridView.cs` to avoid possible problems
> ❗️ We must not use getters in setters.
We already had a serious bug (#1661) due to such use.
- No
- No
- No
- Microsoft Windows [Version 10.0.18362.295]
- .Net Core version: 3.0.0-rc1-19455-02
=> Fixing availability of ShowCellToolTips and ShowCellErrors setters

src/System.Design/src/System.Design.Forwards.cs, src/System.Windows.Forms.Design.Editors/src/System/Windows/Forms/Design/ListViewItemCollectionEditor.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/EnsureEditorsTests.cs
Fixes #1276
- Add System.Windows.Forms.Design.ListViewItemCollectionEditor class
- Changed ListViewItems editor to compliance with .Net 4.8.
- Yes 
- Low
- It made as in .Net 4.8:
- The unit testing
- .Net Core version: 3.1.100-preview2-014533
=> Porting System.Windows.Forms.Design.ListViewItemCollectionEditor

src/System.Windows.Forms/tests/IntegrationTests/MauiTests/Directory.Build.props, src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiButtonTests/MauiButtonTests.csproj, src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiComboBoxTests/MauiComboBoxTests.csproj, src/System.Windows.Forms/tests/IntegrationTests/MauiTests/References.targets
Investigate CI build failures - see #2107
Avoid References in Directory.Build.props.
None
Low
=> Remove References from Directory.Build.props

src/Common/src/Interop/Interop.COLORREF.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewInsertionMark.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
- Add COLORREF helper class.
- Move COLORREF methods from SafeNativeMethods there and update usages.
=> Add COLORREF helper class and move COLORREF methods there

src/Common/src/Interop/ComCtl32/Interop.CDDS.cs, src/Common/src/Interop/ComCtl32/Interop.CDIS.cs, src/Common/src/Interop/ComCtl32/Interop.CDRF.cs, src/Common/src/Interop/ComCtl32/Interop.LVCDI.cs, src/Common/src/Interop/ComCtl32/Interop.LVGA.cs, src/Common/src/Interop/ComCtl32/Interop.LVGF.cs, src/Common/src/Interop/ComCtl32/Interop.LVGROUP.cs, src/Common/src/Interop/ComCtl32/Interop.LVGS.cs, src/Common/src/Interop/ComCtl32/Interop.NMCUSTOMDRAW.cs, src/Common/src/Interop/ComCtl32/Interop.NMLVCUSTOMDRAW.cs, src/Common/src/Interop/ComCtl32/Interop.NMTVCUSTOMDRAW.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItemState.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeState.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
- Cleanup `NMCUSTOMDRAW` (including `CDDS_`, `CDIS_` and `CDRF_` constants)
- Cleanup `NMLVCUSTOMDRAW` (including `LVCDI_` and `LVGA_` constants)
- Structify `NMTVCUSTOMDRAW`
- Structify `LVGROUP` (including `LVGF_` and `LVGS_` constants)
=> Structify NMCUSTOMDRAW and dependencies

src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
Fixes #2036 
- Prevented accessible restructuring for the editing controls with custom accessible hierarchy (like masked editing control or IP editing control which may have several children under the cell) - in this case control WM processing can be broken on recreating handle.
- Added check for known editing controls (ComboBox and TextBox) - these controls' and DataGridView cell hierarchy should be updated in case there are multiple columns of the same type in the DataGridView.
- User will experience correct accessibility hierarchy of DataGridView cell and will not experience issues with incorrect handling of Window messages related to incorrect accessibility restructuring.
- Yes
- Minimal
- Incorrect accessibility hierarchy and broken visual representation of some custom editing …
=> Fixing UI and accessibility regression in DataGridView editing cell

src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxEditingControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.cs
Fixes #2138 
- Adding null reference check to DataGridView editing controls (DataGridViewComboBoxEditingControl, DataGridViewTextBoxEditingControl) to their OnHandleCreated method to prevent throwing null reference exception when the controls are outside of DataGridView control (developers potentially may put these controls anywhere on the Form)
- Users will not experience the exception in case DataGridView editing controls are outside the DataGridView control.
- No
- No
```
System.NullReferenceException: Object reference not set to an instance of an object.
at System.Windows.Forms.DataGridViewComboBoxEditingControl.OnHandleCreated(EventArgs e) in /_/src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxEditingControl.cs:line 164
at …
```
=> DataGridViewEditingControl: Adding null reference check for parent DataGridView control

src/Common/src/Interop/Mshtml/Interop.DOCHOSTUIDBLCLK.cs, src/Common/src/Interop/Mshtml/Interop.DOCHOSTUIFLAG.cs, src/Common/src/NativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.cs
- Create files for DOCHOSTUIDBLCLK and DOCHOSTUIFLAG enums.
- Remove corresponding enums from NativeMethods.cs and replace their usages with the above enums.
- Update DOCHOSTUIINFO definition.
=> Move DOCHOSTUIDBLCLK and DOCHOSTUIFLAG enums to separate files

src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs
- The setter for `Multiline` calls `RecreateHandle`
```cs
public bool Multiline
{
get => GetState(State.Multiline);
set
{
if (Multiline != value)
{
SetState(State.Multiline, value);
if (Multiline == false && (_alignment == TabAlignment.Left || _alignment == TabAlignment.Right))
{
_alignment = TabAlignment.Top;
}
RecreateHandle();
}
}
}
```
But the setter for `Alignment` does this too
```cs
[
SRCategory(nameof(SR.CatBehavior)),
Localizable(true),
DefaultValue(TabAlignment.Top),
RefreshProperties(RefreshProperties.All),
SRDescription(nameof(SR.TabBaseAlignmentDescr))
]
public TabAlignment Alignment
{
get
{
return _alignment;
}
set
{
if (_alignment != value)
{
//valid values are 0x0 to 0x3
if (!ClientUtils.IsEnumValid(value, (int)value, (int)TabAlignment.Top, (int)TabAlignment.Right))
{ …
```
=> Don't recreate the handle twice in TabControl.Alignment setter

src/System.Windows.Forms/src/System/Windows/Forms/Binding.cs
-  Removes second assignment to _formattingEnabled which duplicates [this one](https://github.com/dotnet/winforms/blob/master/src/System.Windows.Forms/src/System/Windows/Forms/Binding.cs#L82)
=> Remove assignment duplication

src/System.Design/src/System.Design.Forwards.cs, src/System.Windows.Forms.Design.Editors/src/Resources/SR.resx, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms.Design.Editors/src/System/Windows/Forms/Design/FolderNameEditor.cs, src/System.Windows.Forms.Design.Editors/src/System/Windows/Forms/Design/SelectedPathEditor.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/EnsureEditorsTests.cs
Fixes issue #2282
Related issue #1115
- Port `SelectedPathEditor`
- Add **`TypeForwardedTo`** statement for `SelectedPathEditor`
- Add a unit test case to check SelectedPathEditor
- Changed SelectedPath editor to compliance with .Net 4.8.
- Yes 
- Low
- CTI
- Unit testing
- .Net Core version: 3.1.0-preview3.19553.2
=> Port SelectedPathEditor

src/System.Design/src/System.Design.Forwards.cs, src/System.Windows.Forms.Design.Editors/src/Resources/SR.resx, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms.Design.Editors/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms.Design.Editors/src/System/Windows/Forms/Design/HelpNamespaceEditor.cs, src/System.Windows.Forms.Design.Editors/tests/UnitTests/EnsureEditorsTests.cs
Fixes #2283
Related issue #1115
- Port `HelpNamespaceEditor`
- Add `TypeForwardedTo` statement for `HelpNamespaceEditor`
- Add a unit test case to check HelpNamespaceEditor
- Changed HelpNamespace editor to compliance with .Net 4.8.
- Yes
- Low
- CTI
- Unit testing
- .Net Core version: 3.1.0-preview3.19553.2
=> Port HelpNamespaceEditor

src/Common/src/Interop/Ole32/Interop.OLEVERB.cs, src/Common/src/Interop/Ole32/Interop.OLEVERBATTRIB.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXVerbEnum.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
=> Cleanup OLEVERB

src/Common/src/Interop/User32/Interop.KillTimer.cs, src/Common/src/Interop/User32/Interop.SetTimer.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Timer.cs
- Cleanup `Timer` interop
- Make the timer ID an `IntPtr` to match https://docs.microsoft.com/en-us/windows/win32/api/winuser/nf-winuser-settimer
=> Cleanup and fix Timer interop

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerHost.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignerHostTests.cs
Fixes #2325
Initialize IServiceContainer in the nested container as soon as INestedContainer is created, otherwise site has no access to the DesignerHost's services. Initialize IServiceContainer in the nested container as soon as INestedContainer is created, otherwise site has no access to the DesignerHost's services.
- No
low
unit test
=> Porting a VS fix to designer host site nested container

src/Common/src/Interop/ComCtl32/Interop.TVHITTESTINFO.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design.Editors/src/Misc/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewHitTestInfoTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
- Cleanup TVHITTESTINFO
- Add more TreeView tests
- Don't force creation of Handle in TreeView.OnHandleCreated
=> Structify TVHITTESTINFO and add more TreeView tests

src/Common/src/Interop/User32/Interop.GetWindow.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- Add IHandle/HandleRef overloads to GetWindow.
- Based on similar feedback on https://github.com/dotnet/winforms/pull/2277
=> Add IHandle and HandleRef overloads to GetWindow

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/Microsoft.Dotnet.Winforms.ProjectTemplates.csproj, pkg/Microsoft.Private.Winforms/Microsoft.Private.Winforms.csproj
- Suppress specific nuget warnings that are breaking our builds
- See https://github.com/dotnet/arcade/issues/4337 for details
- None, our builds are broken
- No
- None
- Ran .\build.cmd -pack locally before this, and it was broken.
- Ran .\build.cmd -pack locally after this, and it was fixed.
=> suppress nuget package generation warnings NU5131 and NU5128

src/Common/src/Interop/Gdi32/Interop.SetTextColor.cs
Fixes #2052
- Change the incorrect implementation of SetTextColor methods
- A user sees correct LinkLabel colors
- Yes
- Minimal
- CTI
- Unit testing
- SDK Version: 5.0.100-alpha1-015730
- Microsoft Windows [Version 10.0.18363.418]
=> Fixing LinkLabel text color setting

src/Common/src/Interop/Ole32/Interop.IErrorLog.cs, src/Common/src/Interop/Ole32/Interop.IPropertyBag.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.PropertyBagStream.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.State.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- Move IErrorLog and IPropertyBag interfaces to interop
=> Move IErrorLog and IPropertyBag interfaces to interop

src/Common/src/Interop/User32/Interop.ActivateKeyboardLayout.cs, src/Common/src/Interop/User32/Interop.GetKeyboardLayout.cs, src/Common/src/Interop/User32/Interop.GetKeyboardLayoutList.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs
- Move KeyboardLayout methods to Interop User32 and update their usages.
=> Move KeyboardLayout methods to Interop User32

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/Microsoft.Dotnet.Winforms.ProjectTemplates.csproj, pkg/Microsoft.Private.Winforms/Microsoft.Private.Winforms.csproj
Port supression to allow upgrade to 3.0.100 SDK
=> suppress nuget package generation warnings NU5131 and NU5128 (#2373)

src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserHelper.cs
- Make `PreserveSig`
- Use `RECT*` instead of `COMRECT` for `prcBounds` and `lprcWBounds`
- Use `uint` for `dwContinue` parameter
=> Cleanup IViewObject.Draw interop

src/Common/src/NativeMethods.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripAdornerWindowService.cs
- Remove  WS_EX_TRANSPARENT from NativeMethods.cs and replace its usages with the appropriate enum value.
=> Remove WS_EX_TRANSPARENT from NativeMethods.cs

src/System.Windows.Forms/src/System/Windows/Forms/WindowsFormsSynchronizationContext.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/WindowsFormsSynchronizationContextTests.cs
- Add WindowsFormsSynchronizationContext tests
- Remove WindowsFormsSynchronizationContext dead code
- Remove invalid debug asserts that are already handle
=> Add WindowsFormsSynchronizationContext tests and remove some dead code

src/System.Design/src/System.Design.Forwards.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/DesignerAttributeTests.cs
Add tests to ensure that strings specified in designer attributes correspond to existing metadata
Contributes to #2185, #2172, #1115 
- Attributes may specify strings to refer to types and other metadata (properties, events). Make sure these actually still exist in the product. These tests help preventing dead references when porting from Desktop to Core and also can detect regressions in future refactoring when renaming something which is technically internal but forgetting that it may have been referenced by attribute strings.
- Raise product quality by detecting dead metadata references in attributes
- Yes (most of the references which are dead now did exist in Desktop Framework)
- None, the change is test-only and exists only to detect regressions.
- Some types and properties carry …
=> Add designer attribute tests

NuGet.config
The dotnet-eng feed is the new feed for arcade bits. Should fix an internal build break.
CC @mmitche @AdamYoblick @RussKie
=> Add dotnet-eng feed to nuget.config

eng/packageContent.targets, src/Microsoft.VisualBasic.Forms/src/Microsoft.VisualBasic.Forms.vbproj
Closes #2395
- Copy the project's intellisense file to the ref folder as a temporary fix until the intellisense file will be added to the main docs bundle.
Without the file we were unable to pack.
- Once the intellisense file is added to the main docs bundle, the task will start breaking and remind us to revert the change.
=> fix: Unable to pack Microsoft.VisualBasic.Forms

eng/Versions.props
winforms does not stabilize so there is no need to add confusion.
=> [release/3.1] Remove stabilize package versions block

src/Microsoft.VisualBasic.Forms/src/Microsoft.VisualBasic.Forms.vbproj
Builds randomly fail with "Type 'System.Windows.Forms.IWin32Window' is not defined" error, estimated about 10% of builds failed because of this.
Investigations suggest that there may be MSBuild bug that `GetCopyToOutputDirectoryItemsDependsOn` property stomps over previous property value without including itself, thus leading to incorrect behaviours later in a build.
More info: https://github.com/microsoft/msbuild/issues/4923#issuecomment-554265394
Closes #2107
=> fix: Type 'System.Windows.Forms.IWin32Window' is not defined

src/Common/src/Interop/UxTheme/Interop.DrawThemeBackground.cs, src/Common/src/Interop/UxTheme/Interop.DrawThemeEdge.cs, src/Common/src/Interop/UxTheme/Interop.DrawThemeParentBackground.cs, src/Common/src/Interop/UxTheme/Interop.DrawThemeText.cs, src/Common/src/Interop/UxTheme/Interop.GetCurrentThemeName.cs, src/Common/src/Interop/UxTheme/Interop.GetThemeSysBool.cs, src/Common/src/Interop/UxTheme/Interop.GetThemeSysInt.cs, src/Common/src/Interop/UxTheme/Interop.IsThemePartDefined.cs, src/Common/src/Interop/UxTheme/Interop.SetWindowTheme.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerUtils.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
- Move SetWindowTheme to Interop UxTheme.
- Remove some unused namespaces.
- Fix GetCurrentThemeName return type.
=> Move SetWindowTheme to Interop UxTheme

src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.cs, src/System.Windows.Forms/src/System/Windows/Forms/NumericUpDown.cs, src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/DomainUpDownAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/NumericUpDownAccessibleObjectTests.cs
- Fixes #2370
- Fixes #2406
- Fixes ScreenReader navigation using CapsLock+arrows
- Add default AccessibleNames for Domain/NumericUpDown AccessibleObjects
- Add unit tests
- Implement UIA provider for UpDown control to fix ScreenReader navigation
- Changed default AccessibleNames that announced by Narrator
- Fixed navigation regression #2406
- Changed ScreenReader navigation using CapsLock+arrow combination
- Yes
- Minimal
- Domain/NumericUpDown AccessibleObjects have "Spinner" default AccessibleNames
- Narrator navigation using **CapsLock+keyboard arrows**:
1. Forward:
Narrator skips an UpDown container and up/down buttons announcing an edit pane only
2. Backward:
Narrator announces an edit pane and UpDown container but skips up/down buttons
- Domain/NumericUpDown …
=> Fixing Domain/NumericUpDown AccessibleNames and navigation

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjectTests.cs
=> Add AccessibleObject tests

src/Common/src/Interop/User32/Interop.GA.cs, src/Common/src/Interop/User32/Interop.GetAncestor.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs, src/System.Windows.Forms/src/System/Windows/Forms/WinFormsUtils.cs
- Move GetAncestor to Interop User32.
- Add GA enum.
- Remove GA constants and replace their usages with the above enum.
=> Move GetAncestor to Interop User32 and add GA enum

src/Common/src/Interop/User32/Interop.GetMessageTime.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs
- Move GetMessageTime to Interop User32
=> Move GetMessageTime to Interop User32

src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.cs
Fixes #2462
- During the refactor in d52e526 a number of calls to `PeekMessageW` lost `PM.REMOVE` argument that led to situations where callers would get stuck in a infinite loop peeking for messages.
For example, a form with a `TabControl` with two `TabPage` controls added to it would dead lock and hang.
Fix affected calls by restoring the correct argument.
- `TabControl` and other affected controls will work again
- Yes 
- manual creation of a test app as described in #2462 and checking that it works as expected
=> fix: Incorrect invocation of `PeekMessageW`

src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
Adding IsHandleCreated checks to prevent accessing AccessibleObject properties and calls to UIAutomation which may lead to application crash/hung.
Fixes #2432 
- Adding IsHandleCreated checks to prevent accessing AccessibleObject properties for not fully initialized control.
- Fixed the reference to child list window to prevent NullReferenceException on child control recreating.
- Customers will not experience application crash/hung in some cases when ComboBox control is being reinitialized while application/form lifecycle.
- Yes
- Minimal
Exception and application hung.
`NullReferenceException` and application crash:
```
System.NullReferenceException: Object reference not set to an instance of an object.
at System.Windows.Forms.ComboBox.WmParentNotify(Message& m)
at …
```
=> Fixing ComboBox handlers and accessibility object initialization

src/Common/src/Interop/User32/Interop.PostMessageW.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms.Design.Editors/src/Misc/NativeMethods.cs, src/System.Windows.Forms.Design.Editors/src/System.Windows.Forms.Design.Editors.csproj, src/System.Windows.Forms.Design.Editors/src/System/Drawing/Design/ColorEditor.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.ParkingWindow.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/CommonDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/MenuStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/NotifyIcon.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/Timer.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
=> Cleanup PostMessage interop

src/Common/src/Interop/UxTheme/Interop.IsThemeBackgroundPartiallyTransparent.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/VisualStyles/VisualStyleRendererTests.cs
- Move IsThemeBackgroundPartiallyTransparent to Interop UxTheme
=> Move IsThemeBackgroundPartiallyTransparent to Interop UxTheme

src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.ControlItemAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.ErrorWindowAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/ErrorProviderAccessibleObjectTests.cs
Fixes #2016
- Implement AccessibleObject for ErrorProvider.ErrorWindow
- Implement AccessibleObject for ErrorProvider.ControlItem
- Narrator announces error description if a user uses CapsLock+keyboard arrow combination to navigation
- No
- Minimal, it is a new feature
- ErrorProvider AccessibleObject is not implemented
- Implemented accessibility tree and correct announcing by Narrator
- CTI
- Using Inspect and Narrator tools
- SDK Version: 5.0.100-alpha1-015730
- Microsoft Windows [Version 10.0.18363.418]
=> Implementing UIA provider for ErrorProvider

src/Common/src/Interop/User32/Interop.SetWindowLong.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.cs
- SafeNativeMethods class seems to be unused, so remove it.
=> Remove NativeMethods, SafeNativeMethods and UnsafeNativeMethods classes from DesignerActionPanel.cs

src/Common/src/NativeMethods.cs
- Remove unused ATTR and IDM constants.
=> Remove unused ATTR and IDM constants

src/Common/src/Interop/Imm32/Interop.IMN.cs, src/Common/src/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs
- Add IMN enum to Interop Imm32
- Remove corresponding constants from NativeMethods.cs and replace their usages with the above enum.
=> Add IMN enum to Interop Imm32

src/Common/src/Interop/User32/Interop.EnumThreadWindows.cs, src/Common/src/Interop/User32/Interop.EnumWindows.cs, src/Common/src/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
- Move EnumWindows to Interop User32.
=> Move EnumWindows to Interop User32

src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.cs
- Remove always false Control.HasMenu
=> Remove always false Control.HasMenu

eng/Version.Details.xml, eng/Versions.props, global.json, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Layout/TableLayoutSettingsTests.cs
Temporarily, revert versions to [f3ac1266 ](https://github.com/wpfcontrib/winforms/commit/f3ac1266) level, where `MicrosoftNETCoreApppackageVersion=5.0.0-alpha1.19514.1`. 
This version is very likely compatible with the WPF repo right now.
--
In https://github.com/dotnet/wpf/pull/2118, transport packages originating from WinForms are unable to build successfully due to a CoreCLR + Compiler problem. This prevents WinForms work from flowing into [dotnet/windowsdesktop](https://github.com/dotnet/windowsdesktop) and ultimately into [dotnet/core-sdk](https://github.com/dotnet/core-sdk). 
WPF currently ingests `Microsoft.NETCore.App` version `5.0.0-alpha1.19514.1` - this can be seen in the LHS of `eng/Version.Detail.xml` in https://github.com/dotnet/wpf/pull/2118/files. This version comes from …
=> Revert versions to f3ac1266 level, where MicrosoftNETCoreApppackageVersion=5.0.0-alpha1.19514.1

src/Common/src/Interop/User32/Interop.IsZoomed.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/MenuStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/StatusStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs, src/System.Windows.Forms/src/System/Windows/Forms/WinFormsUtils.cs
- Make `GetAncestor` `IHandle`
- Cleanup `IsZoomed`
- Replace `WinFormsUtils.GetRootHWnd` with `User32.GetAncestor(this, User32.GA.Root)` as this is cleaner
=> Remove WinFormsUtils.GetRootHWnd

eng/Versions.props
These versions were unintentionally changed in b17f8d94. Fixes coverage-related build failures.
=> Fix codecov package versions

src/Common/src/Interop/User32/Interop.GetWindowText.cs, src/System.Windows.Forms/tests/UnitTests/InteropTests/GetWindowTextTests.cs
Fixes #2424
Fix the following issues that appear to have been overlooked in the review of #923:
- Ensure the buffer passed to `GetWindowTextW()` has at least the length specified in that call, to prevent an out-of-bounds write.
- Fix the condition to detect if the text length has increased, to ensure the returned text is not truncated.
- Avoid an infinite loop (if the control text changes back and forth between a small and long text) by keeping the `actualTextLength` value as minimum text length.
Additional improvements:
- Avoid unnecessary loops by specifying the full buffer length as maximum number of characters, rather than the initial text length value.
Customers will not experience invalid memory access, an infinite loop, or truncated text being returned when the window/control text …
=> Fix issues in Interop.User32.GetWindowText

src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewInsertionMark.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewInsertionMarkTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs
- Cleanup Control.SendMessage ref rect overload
=> Cleanup Control.SendMessage ref rect overload

src/Common/src/Interop/User32/Interop.HBMMENU.cs, src/Common/src/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.cs
- Add HBMMENU enum to Interop User32.
- Remove HBMMENU constants and replace their usages with the above enum.
=> Add HBMMENU enum to Interop User32

src/Common/src/Interop/ComCtl32/Interop.LVCF.cs, src/Common/src/Interop/ComCtl32/Interop.LVCFMT.cs, src/Common/src/Interop/ComCtl32/Interop.LVCOLUMNW.cs, src/Common/tests/ThreadExceptionFixture.cs, src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ColumnHeaderTests.cs
- Add ColumnHeader tests with an extra focus on making sure #1913 does not regress things
(Sort of) relies on #1913 and #2521
=> Add more ColumnHeader tests

src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.TabPageCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs
- Don't force create handle in TabPageCollectionTests.Clear
Fixes #2275
=> Don't force create handle in TabPageCollectionTests.Clear

src/Common/src/Interop/Interop.HRESULT.cs, src/Common/src/NativeMethods.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.OleInterfaces.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IPerPropertyBrowsingHandler.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/FileDialog_Vista.cs, src/System.Windows.Forms/src/System/Windows/Forms/StringSource.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.cs
- Remove HRESULT constants from NativeMethods.cs.
- Add E_OUTOFMEMORY in HRESULT enum.
- Replace the usages of the constants with the enum values.
=> Remove HRESULT constants from NativeMethods.cs

src/Common/src/UnsafeNativeMethods.cs
- Remove unused SetClassLong, SetClassLongPtr32 and SetClassLongPtr64 from UnsafeNativeMethods.cs
=> Remove unused SetClassLong, SetClassLongPtr32 and SetClassLongPtr64 from UnsafeNativeMethods.cs

Documentation/contributing.md, Documentation/debugging.md, Documentation/getting-started.md, Documentation/issue-guide.md, Documentation/porting-guidelines.md, README.md
Resolves #2501
- Update readmes to include links to breaking changes between .NET Framework and .NET Core versions
- Remove out-dated sections
- Update readmes to refer to v3.1 instead of 3.0
=> Update readme to refer to v3.1 and link to breaking changes

src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/FileDialog_Vista.cs, src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
Fixes #2506
- When creating an instance of the `NativeFileOpenDialog` or `NativeFileSaveDialog` fails with a `COMException`, fall back to the legacy file dialog instead of letting the exception bubble up to the caller.
Note: I'm not sure if there's another way to check if the COM object will be available without actually throwing (and catching) a `COMException`.
- When using the [`OpenFileDialog`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.openfiledialog?view=netcore-3.1), [`SaveFileDialog`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.savefiledialog?view=netcore-3.1), or [`FolderBrowserDialog`](https://docs.microsoft.com/en-us/dotnet/api/system.windows.forms.folderbrowserdialog?view=netcore-3.1) (with **`AutoUpgradeEnabled=true`**) on a Windows …
=> Fall back to the legacy file/folder dialog on COMException

src/Common/src/Interop/User32/Interop.GetProcessWindowStation.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/SystemInformation.cs
- Move GetProcessWindowStation to Interop User32.
=> Move GetProcessWindowStation to Interop User32

src/Common/src/Interop/Gdi32/Interop.BitBlt.cs
Fixes #2525
- Fix wrong argument passed to the native `BitBlt` function, which was introduced with #2144.
- ToolStrip will be drawn correctly.
- Yes
-
- Manual testing by using sample project from #2525
Version:   5.0.100-alpha1-015777
Commit:    cea32db3f2
OS Version:  10.0.17134
Base Path:   C:\Program Files\dotnet\sdk\5.0.100-alpha1-015777\
Version: 5.0.0-alpha.1.19564.1
Commit:  c77948d92a
.NET Core SDKs installed:
3.1.100 [C:\Program Files\dotnet\sdk]
5.0.100-alpha1-015777 [C:\Program Files\dotnet\sdk]
=> Fix wrong argument in Interop.Gdi32.BitBlt

src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutSettings.cs, src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutSettingsTypeConverter.cs
- Remove TableLayoutSettings.IsValid
- Remove dead null check in StyleConverter.ConvertTo
=> Remove dead code from TableLayoutSettings

src/Common/src/Interop/Gdi32/Interop.SetBkColor.cs
Fixes #2523
Fixes #2524
//cc @hughbe 
- Fix `Interop.Gdi32.SetBkColor` to correctly call `SetBkColor` rather than `GetTextColor`, which has been broken with #1922.
- Background Color will be applied correctly, e.g. in PropertyGrid.
- Yes
-
- Manual testing using sample code from #2523 and #2524
Version:   5.0.100-alpha1-015777
Commit:    cea32db3f2
OS Version:  10.0.17134
Base Path:   C:\Program Files\dotnet\sdk\5.0.100-alpha1-015777\
Version: 5.0.0-alpha.1.19564.1
Commit:  c77948d92a
.NET Core SDKs installed:
3.1.100 [C:\Program Files\dotnet\sdk]
5.0.100-alpha1-015777 [C:\Program Files\dotnet\sdk]
=> Fix incorrect call to GetTextColor in Interop.Gdi32.SetBkColor

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripControlHost.cs
- This if statement can never be true as `Control` always implements `IArrangedElement`, and we checked for its non-nullness before. Collapse the `is` check into the `!= null` check
=> Remove dead check from ToolStripControlHost. OnBoundsUpdated

eng/Version.Details.xml, eng/Versions.props, src/Common/tests/InternalUtilitiesForTests/InternalUtilitiesForTests.csproj, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ApplicationTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CommonDialogTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/GroupBoxTests.cs
This is needed for various tests that test Application.RenderWithVisualStyles, because calling `Application.UseVisualStyles` poisons the whole test process, meaning that all subsequent tests will be run in visual style enabled mode. Since we want to avoid one test affecting any others, these sorts of tests should be run in their own process.
I'm submitting this on its own since PRs using this could take some time and arcade package updates makes it an absolute nightmare to add new package references as there will be an almost daily merge conflict!
See #2564
=> Add Microsoft.DotNet.RemoteExecutor package reference to tests

src/Common/src/Interop/User32/Interop.GetDesktopWindow.cs, src/Common/src/Interop/User32/Interop.GetForegroundWindow.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs
- Move GetDesktopWindow and GetForegroundWindow to Interop User32.
=> Move GetDesktopWindow and GetForegroundWindow to Interop User32

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PanelTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripContentPanelTests.cs
- Add ToolStripContentPanel tests and related Panel subclasses
=> Add ToolStripContentPanel tests and related Panel subclasses

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListControlTests.cs
Was going to write some test for subclasses of `ListControl` but noticed the tests were a bit messy - not disposing/using `WinFormsFact` etc. so went through and cleaned up the test class
=> Cleanup ListControl tests

src/Common/src/Interop/Shell32/Interop.DragAcceptFiles.cs, src/Common/src/Interop/Shell32/Interop.ShellExecuteW.cs, src/Common/src/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
- Move DragAcceptFiles to Interop Shell32.
=> Move DragAcceptFiles to Interop Shell32

src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System.Windows.Forms.csproj
Fixes https://github.com/dotnet/winforms/issues/1435
- Remove DRAWING_DESIGN_NAMESPACE from csproj files.
=> Remove DRAWING_DESIGN_NAMESPACE from csproj files

src/Common/src/NativeMethods.cs
- Remove unused MCM, MCHT and MCSC constants.
=> Remove unused MCM, MCHT and MCSC constants

src/Common/src/NativeMethods.cs, src/System.Windows.Forms.Design.Editors/src/Misc/NativeMethods.cs, src/System.Windows.Forms.Design.Editors/src/System.Windows.Forms.Design.Editors.csproj, src/System.Windows.Forms.Design.Editors/src/System/ComponentModel/Design/CollectionEditor.cs, src/System.Windows.Forms.Design.Editors/src/System/ComponentModel/Design/ObjectSelectorEditor.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CommandSet.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerFrame.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerUtils.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormDocumentDesigner.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripTemplateNode.cs
- Cleanup NativeMethods SendMessage overloads
=> Cleanup NativeMethods SendMessage overloads

src/Common/src/Interop/Comdlg32/Interop.PD.cs, src/Common/src/Interop/Comdlg32/Interop.PD_RESULT.cs, src/Common/src/NativeMethods.cs, src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintDialog.cs
- Add PD and PD_RESULT enums in Interop Comdlg32.
- Replace PD and PD_RESULT constants with the above enums.
=> Add PD and PD_RESULT enums in Interop Comdlg32

src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
- If `SingleMonthSize` is a certain size, (e.g. `new Size(6, 6)`) then a `DivideByZeroException` is thrown.
- Fix this by avoiding the `DivideByZeroException` by not checking for this case and not dividing by zero
Extracted from https://github.com/dotnet/winforms/pull/2482
=> Fix DivideByZeroException in MonthCalendar

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewInsertionMarkTests.cs
- Add ListViewInsertionMark ComCtl32 tests
- Cleanup ListViewInsertionMark interop (extracted from #2459 with cleanup)
=> Add ListViewInsertionMark ComCtl32 tests 

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.LWA.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.SetLayeredWindowAttributes.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs
- Move SetLayeredWindowAttributes to Interop User32.
- Add LWA enum.
- Remove LWA constants and replace their usages with the above enum values.
=> Move SetLayeredWindowAttributes to Interop User32 and add LWA enum

src/System.Windows.Forms.Design.Editors/src/System/Drawing/Design/ColorEditor.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.EC.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.EN.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.ES.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
- Add EC, EN and ES enums in Interop User32.
- Remove EC, EN and ES constants and replace their usages with the above enum values.
=> Add EC, EN and ES enums in Interop User32

src/System.Design/src/ApiCompatBaseline.netcoreapp.txt, src/System.Windows.Forms.Design/src/Resources/SR.resx, src/System.Windows.Forms.Design/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionMethodItem.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/MenuCommandService.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/MenuCommandsChangedEventArgs.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/MenuCommandsChangedEventHandler.cs, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/MenuCommandsChangedType.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2TypeInfoProcessor.cs
- Add `MenuCommandService` and a few dependency types that are already identified as missing yet required for .NET 5.
- No tests have been ported (yet)
=> Add MenuCommandService

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.CWP.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.ChildWindowFromPointEx.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/GetChildAtPointSkip.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
- Move ChildWindowFromPointEx to Interop User32 and add CWP enum
- Remove CWP_SKIPINVISIBLE and replace its usage with the above enum value.
=> Move ChildWindowFromPointEx to Interop User32 and add CWP enum

pkg/Microsoft.Private.Winforms/Microsoft.Private.Winforms.csproj
Our downstream consumers are broken missing System.Windows.Forms.Primitives.dll, e.g. https://github.com/dotnet/wpf/pull/2399
Follow up for #2518
=> Fix missing reference

src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.LVGROUPW.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
- Fix setting ListViewGroup.HeaderAlignment if the handle is already created
- Avoid marshalling using `Marshal.PtrToStringAuto` and instead pin a `string`
- Add tests to make sure we are calling into comctl32 correctly
Fixes https://github.com/dotnet/winforms/issues/2554
=> Cleanup LVGROUPW interop and fix HeaderAlignment refresh bugList view group tests

src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.SB.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.SBT.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.SBS.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.SS.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/HScrollBar.cs, src/System.Windows.Forms/src/System/Windows/Forms/Label.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.cs, src/System.Windows.Forms/src/System/Windows/Forms/StatusBar.cs, src/System.Windows.Forms/src/System/Windows/Forms/StatusBarPanel.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/VScrollBar.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
- Add SB and SBT enums in Interop ComCtl32 and SBS and SS enums in User32. 
- Remove SB, SBT, SBS and SS constants from NativeMethods.cs and replace their usages with the above enums.
=> Add SB and SBT enums in Interop ComCtl32 and SBS and SS enums in User32

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Properties.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FormTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PictureBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/SplitterPanelTests.cs
- Make Control.AssignParent private protected
- Remove related test - our tests for `Control.Parent` already cover this, so no need for new tests
=> Add tests for Control.AssignParent

src/System.Windows.Forms/src/System.Windows.Forms.csproj
See https://github.com/dotnet/winforms/issues/2636 for context
- Fix all resource files referenced in `System.Windows.Forms` to have the same casing as they have in the file system.
- `System.Windows.Forms` will compile on file systems with sensitive casing (e.g. ext4)
- `dotnet build` passes before and after
- `dotnet test` yields same results before and after
=> fix casing in csproj

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/ClientUtils.cs, src/System.Windows.Forms/src/System/Windows/Forms/WinFormsUtils.cs
Same functionality, `BitOperations` is faster
Verification:
```cs
using System;
using System.Numerics;
public class Program
{
public static void Main()
{
for (uint i = 0; i < uint.MaxValue; i++)
{
if ((i % 1000) == 0)
{
Console.WriteLine($"{i}/{uint.MaxValue}");
if (GetBitCount(i) != BitOperations.PopCount(i))
{
throw new Exception();
}
}
}
Console.WriteLine("Completed");
}
public static int GetBitCount(uint x)
{
int count = 0;
while (x > 0)
{
x &= x - 1;
count++;
}
return count;
}
}
```
=> Use BitOperations.PopCount instead of GetBitCount

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetUpdateRect.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
- Move GetUpdateRect to Interop User32.
=> Move GetUpdateRect to Interop User32

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.IsWindow.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadWindows.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/Timer.cs
- Remove IsWindow from UnsafeNativeMethods.cs.
- Replace is usages with the Interop User32 methods.
=> Remove IsWindow from UnsafeNativeMethods.cs

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.EnumChildWindows.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.EnumThreadWindows.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.EnumWindows.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadWindows.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
In `EnumWindows`, `EnumChildWindows`, and `EnumThreadWindows`, instead of passing the supplied callback delegate to the native function, use a (fixed) static delegate, and specify a handle pointer of the supplied callback in the `lParam` parameter (that is available for storing application-provided data).
That way, the CLR no longer needs to allocate memory for each delegate instance in order to store a native code block (that contains the closure pointer), thus improving performance in many cases (see comparison below). (On the other hand, the invoked callback delegate now has a little bit more work to do, by dereferencing a `GCHandle` and calling another method.)
This can especially improve speed when running x86 applications on **ARM64** systems, as it avoids the need for the emulation …
=> Improve performance of Enum*Windows() interop functions

src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs
It appears we have a bug in `ThreadContext`, specifically how it adds new instances of TC to the hashtable (line:110):
https://github.com/dotnet/winforms/blob/0f6796745088c68bb77bdc5abfb32d6eeece7969/src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs#L95-L111
Note, there is no synchronisation when executing `s_contextHash[_id] = this`. [Hashtables are not thread-safe](https://docs.microsoft.com/en-us/dotnet/api/system.collections.hashtable?view=netcore-3.1#thread-safety) (for writing), so when we execute thousands of concurrent tests, each wiring to `Application.ThreadException` we end up creating a lot of instances of `ThreadContext`, all of which get written int to the shared hashtable.
This causes `InvalidOperationException: Hashtable insert failed. Load …
=> fix: Race conditions adding `ThreadContext` to TLS

src/System.Windows.Forms/src/System/Windows/Forms/Application.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ApplicationTests.cs
Depends on #2565 
The implementation of `Application.RenderWithVisualStyles` is the following:
```cs
public static bool RenderWithVisualStyles
=> ComCtlSupportsVisualStyles && VisualStyleRenderer.IsSupported;
```
The implementation of `Application.ComCtlSupportsVisualStyles` is the following:
```cs
/// <summary>
///  Typically, you shouldn't need to use this directly - use RenderWithVisualStyles instead.
/// </summary>
internal static bool ComCtlSupportsVisualStyles
{
get
{
if (!s_comCtlSupportsVisualStylesInitialized)
{
s_comCtlSupportsVisualStyles = InitializeComCtlSupportsVisualStyles();
s_comCtlSupportsVisualStylesInitialized = true;
}
return s_comCtlSupportsVisualStyles;
}
}
private static bool InitializeComCtlSupportsVisualStyles()
{
if (UseVisualStyles)
{
// At this point, we may …
```
=> Clear ComCtlSupportsVisualStyles initialization status when enabling visual styles

src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutSettingsTypeConverter.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Layout/TableLayoutSettingsTypeConverterTests.cs
- Fix NullReferenceException serializing TableLayoutSettings for controls without name
The problem is that we would not set the `ControlInformation.Name` property so throw NRE serializing it
=> Fix NullReferenceException serializing TableLayoutSettings for controls without name

global.json
Fixes #2729
- Remove the vs and xcopy-msbuild entries from our global.json
- This will make us build with dotnet instead of msbuild
- Customers will be able to build without having to install VS
- Yes, we were able to do this before
- None
- Built on a clean VM
=> remove VS and roslyntools msbuild dependencies from our global.json

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/PaddingConverter.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PaddingConverterTests.cs
Fixes #2677
- The context argument may be null for callers other than the PropertyGrid, this should not lead to an exception, in particular since `GetCreateInstanceSupported` returns true for a null context. Also every other implementation of CreateInstance I could find in WinForms and System.Drawing supports a null context, so PaddingConverter is an outlier.
- No
- Callers which depend on an exception being thrown in a previously unsupported scenario will no longer see an exception
- `PaddingConverter.CreateInstance(null, properties)` throws an exception even though `PaddingConverter.GetCreateInstanceSupported(null)` returns true
- `PaddingConverter.CreateInstance(null, properties)` creates an instance based on the given properties like any other TypeConverter defined in WinForms and …
=> Improve PaddingConverter CreateInstance implementation

src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/Devices/MouseTests.cs
Fails on remote desktop or anywhere where we don't have a mouse wheel, e.g.
```cs
[xUnit.net 00:00:08.38]     Microsoft.VisualBasic.Devices.Tests.MouseTests.Properties [FAIL]
X Microsoft.VisualBasic.Devices.Tests.MouseTests.Properties [9ms]
Error Message:
System.InvalidOperationException : No mouse wheel is present.
Stack Trace:
at Microsoft.VisualBasic.Devices.Mouse.get_WheelScrollLines() in C:\Users\hughbe\Documents\GitHub\winforms\src\Microsoft.VisualBasic.Forms\src\Microsoft\VisualBasic\Devices\Mouse.vb:line 69
at Microsoft.VisualBasic.Devices.Tests.MouseTests.<>c__DisplayClass0_0.<Properties>b__2() in C:\Users\hughbe\Documents\GitHub\winforms\src\Microsoft.VisualBasic\tests\UnitTests\Microsoft\VisualBasic\Devices\MouseTests.cs:line 18
at …
```
=> Fix VisualBasic Mouse tests

src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.IFont.cs, src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.IPicture.cs, src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.IPictureDisp.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComponentModel/Com2Interop/COM2PictureConverterTests.cs
- Add missing `IFont` methods
- Make `IFont` and `IPicture` tests `WinFormsFact` to run on STA thread
- Make `HDC`/`HPALETTE`/`HBITMAP`/`HENHMETAFILE`/`HMETAFILE`/`HFONT` `int`s not `uint`s  due to sign extension bugs
/cc @weltkante @JeremyKuhne 
Fixes #2002, Fixes #2003, Fixes #2004, Fixes #2005, Fixes #2007
=> Fix IFont and IPicture definitions

src/System.Windows.Forms.Design.Editors/src/System/Drawing/Design/ColorEditor.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetDlgItem.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/FontDialog.cs
- Move GetDlgItem to Interop User32.
=> Move GetDlgItem to Interop User32

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
- Remove unused ACM, CP, CONNECT, GCL, IMAGE, LOCK, MB, MSH and PSM constants.
=> Remove unused ACM, CP, CONNECT, GCL, IMAGE, LOCK, MB, MSH and PSM constants

src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs
- Don't force TabControl handle creation in OnHandleCreated
=> Don't force TabControl handle creation in OnHandleCreated

src/System.Windows.Forms/src/System/Windows/Forms/TrackBar.cs, src/System.Windows.Forms/tests/UnitTests/TrackBarTests.cs
- Don't force handle creation in TrackBar.OnHandleCreated
=> Don't force handle creation in TrackBar.OnHandleCreated

src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs
- Add ListBox/ComboBox tests
- Cleanup ListBox.SendMessage overloads
=> Add ListBox/ComboBox tests and cleanup ListBox.SendMessage overloads

src/System.Windows.Forms/src/System/Windows/Forms/BindingContext.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BindingContextTests.cs
- Make `ICollection.SyncRoot` return non-null value
~We have the following warnings~
> System/Windows/Forms/BindingContext.cs(377,38): warning CS8605: Unboxing a possibly null value. [/Users/hugh/Documents/GitHub/winforms/src/System.Windows.Forms/src/System.Windows.Forms.csproj]
System/Windows/Forms/BindingContext.cs(379,38): warning CS8600: Converting null literal or possible null value to non-nullable type. [/Users/hugh/Documents/GitHub/winforms/src/System.Windows.Forms/src/System.Windows.Forms.csproj]
System/Windows/Forms/BindingContext.cs(380,21): warning CS8602: Dereference of a possibly null reference. [/Users/hugh/Documents/GitHub/winforms/src/System.Windows.Forms/src/System.Windows.Forms.csproj]
3 Warning(s)
Happens in cases like below in `foreach (DictionaryEntry de in …
=> Fix nullability bug in BindingContext

src/System.Windows.Forms.Design.Editors/src/System/ComponentModel/Design/ObjectSelectorEditor.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.DLGC.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
- Add DLGC enum to Interop User32.
- Remove DLGC constants and replace their usage with the above enum values.
=> Add DLGC enum to Interop User32

src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.FOS.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/FileDialog_Vista_Interop.cs, src/System.Windows.Forms/src/System/Windows/Forms/FileDialog_Vista.cs, src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
- Move FOS to Interop Shell32.
=> Move FOS to Interop Shell32

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.ScrollWindow.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs
- Move ScrollWindow to Interop User32.
=> Move ScrollWindow to Interop User32

src/System.Windows.Forms.Primitives/src/System/ExternDll.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/SafeNativeMethods.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2TypeInfoProcessor.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXFontMarshaler.cs, src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs
- Remove Succeeded and Failed methods from NativeMethods.cs
- Remove unused constants from ExternDll.cs
- Replace int with HRESULT return type.
=> Remove Succeeded and Failed methods from NativeMethods.cs

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.SetForegroundWindow.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/NotifyIcon.cs
- Move SetForegroundWindow to Interop User32.
=> Move SetForegroundWindow to Interop User32

src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.LVIF.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.LVN.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.LV_VIEW.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/View.cs
- Add LVN and LV_VIEW enums in Interop ComCtl32
- Remove corresponding constants and replace their usages with the above enum values.
=> Add LVN and LV_VIEW enums in Interop ComCtl32

eng/ApiCompatibility/PublicApiAnalyzer.props, eng/ApiCompatibility/PublicApiAnalyzer.targets, src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
Initially the analyzer was enabled in Release mode only. However most of development happens in Debug mode, resolving build breaking warnings will require additional cycles.
To streamline the process enable the analyzer by default.
=> Enable PublicApiAnalyzers by default

src/System.Windows.Forms.Design/src/System/Drawing/Design/ColorEditor.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.COLOR.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.DialogItemID.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.SendDlgItemMessageW.cs, src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.TMT.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/FontDialog.cs
- Add SendDlgItemMessageW and COLOR enum to Interop User32.
- Remove SendDlgItemMessage from UnsafeNativeMethods.cs
- Remove COLOR constants and replace their usage with the above enum values.
=> Add SendDlgItemMessageW and COLOR enum to Interop User32

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetUserObjectInformationW.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.UOI.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.USEROBJECTFLAGS.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.WSF.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/SystemInformation.cs
- Add GetUserObjectInformationW, UOI and USEROBJECTFLAGS in Interop User32.
- Remove corresponding method, enum and constant from NativeMethods.cs and UnsafeNativeMethods.cs  and replace their usages.
=> Add GetUserObjectInformationW, UOI and USEROBJECTFLAGS in Interop User32

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ObjectSelectorEditor.cs
- Use SendMessageW directly and remove TreeView_GetExtendedStyle and TreeView_SetExtendedStyle
=> Use SendMessageW directly and remove TreeView_GetExtendedStyle and TreeView_SetExtendedStyle

src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.MCGRIDINFO.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.MCHITTESTINFO.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarBodyAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.MonthCalendarAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/MonthCalendar.CalendarHeaderAccessibleObjectTests.cs
- Make `MCGRIDINFO` blittable by using `Span`
- Cleanup `MCHITTESTINFO` interop
=> Cleanup MonthCalendar interop definitions

eng/Versions.props
Avoids issues if we have more than 10 previews.
Original change was incorrectly reverted at some point a few months ago.
=> Use Label.N form of prerelease label

src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.CFE.cs, src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.CFM.cs, src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.CHARFORMATW.cs, src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.SCF.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms.Primitives/tests/Interop/Richedit/CHARFORMATWTests.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBoxConstants.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
- Cleanup CHARFORMATW
- Only cleanup necessary is to move the file and use enums instead of `int` fields
=> Cleanup CHARFORMATW

src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
Resolves #1143 following the advice from @swaroop-sridhar in https://github.com/dotnet/runtime/issues/11201#issuecomment-506480041
In .NET artifacts are DLLs even for executable projects. With some automagic they get bundled into executables.
However `Assembly.GetEntryAssembly()` always returns the dll instead of the exe.
Following the guidance from the Runtime team retrieve the path to the executable via `GetModuleFileNameW` call.
- Customers can now retrieve a path to the applications executable instead of the application's dll.
- Yes
- Small-medium due to possibly unaccounted use cases
- I have created several app targeting net472 and netcoreapp5.0 to capture outputs of calling `Application.ExecutablePath` in the following scenarios:
- a single project app:
```powershell …
```
=> fix: `Application.ExecutablePath` returns dll instead of exe

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/MultilineStringEditor.cs, src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.DeleteDC.cs, src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.ExtTextOutW.cs, src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.OffsetViewportOrgEx.cs, src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.RestoreDC.cs, src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.ActivateActCtx.cs, src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.FreeLibrary.cs, src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.CreateILockBytesOnHGlobal.cs, src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHGetPathFromIDListLongPath.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetClassInfoW.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.SetCursorPos.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/ThemingScope.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.State.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.MetafileDCWrapper.cs, src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.WindowClass.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
- Use BOOL instead of bool in some DllImports in Interop.
=> Use BOOL instead of bool in some DllImports in Interop

src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.GMR.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.MCHITTESTINFO.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
- Add GMR enum in Interop ComCtl32.
- Remove GMR constants and replace their usage with the above enum values.
=> Add GMR enum in Interop ComCtl32

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CommandSet.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripAdornerWindowService.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.HT.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/Label.cs, src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridToolTip.cs, src/System.Windows.Forms/src/System/Windows/Forms/SplitContainer.cs, src/System.Windows.Forms/src/System/Windows/Forms/StatusStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.cs, src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/HitTestCode.cs
- Add HT enum in Interop User32.
- Remove HT constants and replace their usages with the above enum values.
=> Add HT enum in Interop User32

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/MultilineStringEditor.cs, src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.IRichEditOleCallback.cs, src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.RECO.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
- Add RECO enum to Interop Richedit.
- Remove RECO constants and replace their usages with the above enum values.
=> Add RECO enum to Interop Richedit

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.SetWindowRgn.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs, src/System.Windows.Forms/src/System/Windows/Forms/MDIClient.cs
- Add SetWindowRgn to Interop User32.
- Remove unused FindWindow and SetActiveWindow DllImports.
=> Add SetWindowRgn to Interop User32

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.MDITILE.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/MDIClient.cs
- Add MDITILE enum in Interop User32.
- Remove MDITILE constants and replace their usages with the above enum values.
=> Add MDITILE enum in Interop User32

src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.CDCS.cs, src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.FDEOR.cs, src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.FDESVR.cs, src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SIATTRIBFLAGS.cs, src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SIGDN.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/FileDialog_Vista_Interop.cs, src/System.Windows.Forms/src/System/Windows/Forms/FileDialog_Vista.cs, src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs
- Add CDCS, FDEOR, FDESRV, SIATTRIBFLAGS and SIGDN enums in Interop Shell32.
=> Add CDCS, FDEOR, FDESRV, SIATTRIBFLAGS and SIGDN enums in Interop Shell32

src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/ProgressBar.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/ProgressBarAccessibleObjectTests.cs
- Fix missing name: The Name property of a focusable element must not be null. [Section 508 502.3.1](https://www.access-board.gov/guidelines-and-standards/communications-and-it/about-the-ict-refresh/final-rule/single-file-version#502-interoperability-assistive-technology)
=> Add missing ProgressBar AccessibleName

src/System.Windows.Forms.Primitives/src/Interop/Interop.ERROR.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs
- Move ERROR_INSUFFICIENT_BUFFER to Interop ERROR class.
=> Move ERROR_INSUFFICIENT_BUFFER to Interop ERROR class

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.EndDialog.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
- Move EndDialog to Interop User32.
=> Move EndDialog to Interop User32

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.DrawEdge.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Border3DStyle.cs, src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
- Move DrawEdge to Interop User32.
=> Move DrawEdge to Interop User32

src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutControlCollection.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.ControlCollection.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.ControlCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.TabPageControlCollection.cs
NREs are thrown when adding/using the collection, so just validate this upfront.
=> Fix NullReferenceExceptions in Control.ControlCollection with a null owner

src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.NIM.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/NotifyIcon.cs
- Add NIM enum to Interop Shell32.
- Remove NIM constants and replace their usages with the above enum values.
=> Add NIM enum to Interop Shell32

src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.GDTR.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
- Add GDTR enum to Interop ComCtl32.
- Remove GDTR constants and replace their usages with the above enum values.
=> Add GDTR enum to Interop ComCtl32

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
- Remove unused FADF constants.
=> Remove unused FADF constants

src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.NIF.cs, src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.NIIF.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/NotifyIcon.cs
- Add NIF and NIIF enums to Interop Shell32.
- Remove NIF and NIIF constants and replace their usages with the above enum values.
=> Add NIF and NIIF enums to Interop Shell32

src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/ColumnHeader.cs, src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ColumnHeaderTests.cs
Fixes #2867 
The `name` field is not set in this code, however it is read in ShouldSerializeName. Thus ShouldSerialize always returns `false` and ColumnHeader names are never serialized into `InitializeComponent` method. Thus `Name` property is always null at run time. However this property is used as a key  when accessing column display order. See issue for details. 
listView1.Columns.IndexOfKey("columnHeader1") - always return `-1`
- No
-Winforms Core designer will be generating different code compared to the Framework designer.  
Unit test
=> Read Name property instead of name field when serializing ColumnHeader.Name 

src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj, src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
As @weltkante pointed out, DesignerCategory attribute is inheritable and if we have this attribute on Form class, we are enforsing this category on all user forms/controls and blocking designer. Thank you!
I'm removing this attribute in this change.
=> removed DesignerCategory attribute from Form class

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.NFR.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- Add NFR enum to Interop User32.
- Remove NFR constants and replace their usages with the above enum values.
=> Add NFR enum to Interop User32

src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/PropertyGridAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/PropertyGridViewAccessibleObjectTests.cs
Fixes #1832
- Add unit tests for PropertyGridViewAccessibleObject
- Move PropertyGrid tests to PropertyGridAccessibleObjectTests class
- No
- No
- Minimal
- SDK Version: 5.0.100-alpha1-016143
- Microsoft Windows [Version 10.0.18363.592]
=> Adding PropertyGridViewAccessibleObject unit tests

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs
- Remove unused MSAA_MENU_SIG and MSAAMENUINFO.
=> Remove unused MSAA_MENU_SIG and MSAAMENUINFO

src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.CreateICW.cs, src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.PatBlt.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
- Add CreateICW to Interop Gdi32.
- Remove CreateIC from UnsafeNativeMethods and replace its usages.
=> Add CreateICW to Interop Gdi32

src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TTS.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridToolTip.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
- Add TTS enum in Interop ComCtl32.
- Remove TTS constants and replace their usages with the above enum values.
- Remove unused TV and TTI constants.
=> Add TTS enum in Interop ComCtl32

src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.IProvideClassInfo.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2TypeInfoProcessor.cs
- Move IProvideClassInfo to Interop OleAut32.
=> Move IProvideClassInfo to Interop OleAut32

src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/TrackBarAccessibleObjectTests.cs
- Fixes #2818  TrackBar accessibility issue 
Fix based off code in `NumericUpDown`:
```cs
public override string Name
{
get => base.Name ?? SR.DefaultNumericUpDownAccessibleName;
set => base.Name = value;
}
```
=> Add TrackBar accessible object tests

src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.DTS.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs
- Add DTS enum to Interop ComCtl32.
- Remove DTS constants and replace their usages with the above enum values.
- Remove unused DI_NORMAL constant.
=> Add DTS enum to Interop ComCtl32

src/System.Windows.Forms/tests/UnitTests/WebBrowserTests.cs
IE browser is now an optional Windows component, and it may not be present in all environments we run tests.
`Type.GetTypeFromCLSID` returns `System.__ComObject` regardless of whether the CLSID is valid. Which leaves us checking whether an IE browser is installed and handling the exception.
Further xUnit does not support dynamic skipping of tests https://github.com/xunit/xunit/issues/2073 that forces us to abandon the test if the IE browser is not detected, marking the test as success.
Relates to #2889 and dotnet/core-eng#9068
=> fix: WebBrowser_AttachInterfaces_Invoke_Success fails if IE browser not installed

Winforms.sln, eng/FacadeAssemblies.props, eng/Versions.props, pkg/Microsoft.Private.Winforms/FrameworkListFiles.props, pkg/Microsoft.Private.Winforms/Microsoft.Private.Winforms.csproj, src/System.Windows.Forms.Design.Editors/Directory.Build.props, src/System.Windows.Forms.Design.Editors/src/System.Windows.Forms.Design.Editors.Facade3x.csproj
As part of consolidation initiative (refer to #2781) we have merged System.Windows.Forms.Design.Editors.dll into System.Windows.Forms.Design.dll.
However doing so we broke roll-forward upgrades for any app depending on types declared in System.Windows.Forms.Design.Editors.dll.
Resolves #2921.
- Create a facade assembly that forwards types from original assembly.
- Customers can roll forward from .NET Core 3.x to .NET 5.0
- Yes 
* [Use the repro app](https://github.com/RussKie/Test-TypeForwards/commit/c5f76dca248dee7fd69d95fc9b5af0f76c32578e) or generate a new Windows Forms app targeting .NET Core 3.0 (or 3.1) and set it to rollforward:
```json
{
"sdk": {
"rollForward": "major"
}
}
```
* Add the following line to `Form1`:
```cs
AnchorEditor editor = new AnchorEditor();
```
* Ensure no .NET …
=> fix: Fail roll forward .NET Core 3.x -> .NET 5.0

src/System.Windows.Forms/src/System.Windows.Forms.csproj
#Fixes #2939
The [ToolStripDropDownMenu.ico file](https://github.com/dotnet/winforms/blob/b666dc7a94d8ac87a7d300cfb4fa86332fb79bae/src/System.Windows.Forms/src/Resources/System/Windows/Forms/ToolStrip/ToolStripDropDownMenu.ico) is already there, but the reference was missing.
=> Add reference to ToolStripDropDownMenu.ico

src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.NIN.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/NotifyIcon.cs
- Add NIN enum to Interop Shell32.
- Remove NIN constants and replace their usages with the above enum values.
=> Add NIN enum to Interop Shell32

src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.AccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/DataGridViewAccessibleObjectTests.cs
Fixes #1833
- Add unit tests
- Fix IsReadOnly property for DataGridViewAccessibleObject and DataGridViewRowAccessibleObject
- No
- No
- Minimal
- SDK Version: 5.0.100-alpha1-016143
- Microsoft Windows [Version 10.0.18363.592]
=> Adding unit tests for DataGridViewAccessibleObject

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetWindowDC.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.cs
- Move GetWindowDC to Interop User32.
=> Move GetWindowDC to Interop User32

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs, src/System.Windows.Forms.Primitives/src/Interop/Interop.Libraries.cs, src/System.Windows.Forms.Primitives/src/Interop/Oleacc/Interop.LresultFromObject.cs, src/System.Windows.Forms.Primitives/src/System/ExternDll.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- Move LresultFromObject to Interop Oleacc.
=> Move LresultFromObject to Interop Oleacc

src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.EDITSTREAM.cs, src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.EDITSTREAMCALLBACK.cs, src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.SF.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms.Primitives/tests/Interop/Richedit/EDITSTREAMTests.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBoxConstants.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
=> Cleanup EDITSTREAM

src/System.Windows.Forms/src/PublicAPI.Unshipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Fixes #2653 
- Add ListViewGroup.Footer
- Add ListViewGroup.FooterAlignment
- New APIs to align with native comctl32 feature set
- No
- Minimal
- Unit tests
- Integration tests
- Manual tests
- Inspect.exe and accessibility checker
=> Add ListViewGroup.Footer/FooterAlignment

src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs, src/System.Windows.Forms/tests/UnitTests/TextBoxBaseTests.cs
- Cleanup WM_CONTEXTMENU handler in TextBox following removal of `ContextMenu` and the like
=> Cleanup WM_CONTEXTMENU handler in TextBox

src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.DTN.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.HDN.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
- Add HDN enum in Interop ComCtl32.
- Remove HDN constants and replaces their usages with the above enum values.
=> Add HDN enum in Interop ComCtl32

src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.MCN.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs
- Add MCN enum to Interop ComCtl32.
- Remove MCN constants and replace their usages with MCN enum values.
=> Add MCN enum to Interop ComCtl32

src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
There are no security checks in Core so ExitInternal is unnecessary (the security checks were already removed).
=> Remove ExitInternal

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-VisualBasic/.template.config/template.json
Resolves #2981
- Fix the packages identities and add framework choices.
Given that the identity lacked the version, the new template package targeting netcoreapp5.0 would supersede and replace the ones targeting netcoreapp3.x.
This breaks developer's ability to create app targeting netcoreapp3.x from command line (via `dotnet new winforms`) and rom VS (because the VS Template Engine Host will only install the highest versioned package for any given identity).
- Yes 
- Low. The change is to “dotnet new” templates only. No changes to Windows Forms runtime.
=> Add missing template identity version information

src/System.Windows.Forms.Primitives/src/Interop/Comdlg32/Interop.PrintDlg.cs, src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.MultiByteToWideChar.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.InvalidateRgn.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/SafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- Move InvalidateRgn to Interop User32.
- Replace some ExternDll usages with Libraries instead.
=> Move InvalidateRgn to Interop User32

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/WebBrowserTests.cs
The test may intermittently fail in internal CI agents. Presumably due to either no IE installer or a different version of IE, that yeilds `DocumentType` as "HTM File" instead of "HTML Document".
Fixes: https://github.com/dotnet/winforms/pull/2962#discussion_r394735398
- Assert that `DocumentType` is set without asserting the string itself, as we don't control the content
=> Fix flaky test

src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Handlers.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTextBoxEditingControlTests.cs, src/System.Windows.Forms/tests/UnitTests/TextBoxBaseTests.cs, src/System.Windows.Forms/tests/UnitTests/TextBoxTests.cs
- Add DataGridViewTextBoxEditingControl tests and fix bugs
- Validate `dataGridViewCellStyle` in `ApplyCellStyleToEditingControl`: fixes NRE
- Fix NRE in `NotifyDataGridViewOfValueChange` without `EditingControlDataGridView`
- Fix NRE in `ApplyCellStyleToEditingControl` without `EditingControlDataGridView`
- Don't force handle creation in `OnGotFocus` or `OnHandleCreated`
- Fix NRE in `OnMouseWheel` without `EditingControlDataGridView`
=> Add DataGridViewTextBoxEditingControl tests and fix bugs

src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Testing a fix for #2970
Unconditionally set footer even if it is empty
=> Test fix for ListViewGroup footer

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.ICON.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/MDIControlStrip.cs
- Add ICON enum in Interop User32.
- Remove ICON constants and replace their usages with the above enum values.
=> Add ICON enum in Interop User32

src/System.Windows.Forms/src/System/Windows/Forms/RichTextBoxConstants.cs
- Remove unused RichTextBoxConstants.
=> Remove unused RichTextBoxConstants

src/Common/tests/InternalUtilitiesForTests/src/ArchitectureDetection.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.MCGRIDINFO.cs, src/System.Windows.Forms.Primitives/tests/Interop/ComCtl32/MCGRIDINFOTests.cs, src/System.Windows.Forms.Primitives/tests/Interop/Comdlg32/PRINTDLGWTests.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.MonthCalendarAccessibleObject.cs
Fixes #2912 
Related issue #2475
`MonthCalendarAccessibleObject` gets incorrect `SYSTEMTIME `info when sending Windows messages due to incorrect `MCGRIDINFO `definition.
- Edit MCGRIDINFO to avoid SYSTEMTIME value errors
- A user can use a correct MonthCalendar without exceptions
- Yes, from PR #2090
- Minimal
- Incorrect SYSTEMTIME value
- Correct SYSTEMTIME value
- CTI
- Unit testing
- Using Inspect and Narrator tools
- .NET Core SDK: 5.0.0-alpha.1.20072.3
- Microsoft Windows [Version 10.0.18363.592]
=> Fixing MCGRIDINFO definition

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.WINDOW_SIZE.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
- Add SIZE enum in Interop User32.
- Remove SIZE constants and replace their usages with the above enum values.
=> Add WINDOW_SIZE enum in Interop User32

src/Common/tests/InternalUtilitiesForTests/InternalUtilitiesForTests.csproj, src/Common/tests/InternalUtilitiesForTests/InternalsVisibleTo.cs, src/Common/tests/InternalUtilitiesForTests/src/WindowClass.cs, src/System.Windows.Forms.Primitives/src/Interop/Interop.RECT.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.CS.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.CreateWindowExW.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.LoadCursorW.cs, src/System.Windows.Forms.Primitives/tests/Interop/User32/GetWindowTextTests.cs, src/System.Windows.Forms/src/System/Windows/Forms/Cursor.cs, src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs
Adds WindowClass for testing windows messages.
Adds InternalsVisibleTo so we can expose helpers for Interop testing from internal test utility.
Ref to SWF in internal test utility should be removed. This is one step. Tests using AxHost should refactor AxHost helper methods into SWF.Primitives (don't move the whole AxHost down).
Fix a bug in Cursor interop.
=> Add a low level window class

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs, src/System.Windows.Forms/tests/UnitTests/PropertyGridInternal/PropertyGridView.GridViewListBoxAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/PropertyGridInternal/PropertyGridViewTests.cs
Fixes #2316 
- Adding the test selected item for null before accessing the selected item accessible object in PropertyGrid's ListBox property.
- Users will not experience error even the ListBox property has
null values.
- Yes
- Minimal
Application crash. Error with callstack ( please see #2316 )
No error.
- Manual testing;
- Unit test (to be implemented);
- UI automation.
Version:   5.0.100-alpha.1.20073.10
Commit:    29f4d693a9
Base Path:   C:\Program Files\dotnet\sdk\5.0.100-alpha1-05536\
Version: 5.0.0-alpha.1.20072.3
Commit:  c3dc1fdfdc
Previous PR (was cancelled): #2789
=> PropertyGridView crashes on editing ListBoxProperty with null values

src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.ICM.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBoxConstants.cs
- Add ICM enum in Interop RichEdit.
- Remove ICM constants and replace their usages with the above enum values.
=> Add ICM enum in Interop RichEdit

src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/PropertyGridViewAccessibleObjectTests.cs
Fixes #2802
- Use a PropertyGrid entry name if a list AccessibleName isn't set
- A user can see a non-empty accessible name of a values list using Inspect 
(Does not affect Narrator announcing)
- Fixed MAS requirement:
- No
- Minimal
- An empty AccessibleName
- A non-empty AccessibleName (<del>"{Property name}"</del> -> "{Property name} property values")
- CTI
- Unit testing
- Using Narrator, Accessibility Insights and Inspect
- .NET Core SDK: 5.0.0-alpha.1.20072.3
- Microsoft Windows [Version 10.0.18363.592]
=> [Accessibility] Fixing a default accessible name of a list of a dropdown entry value in PropertyGridView

src/System.Windows.Forms/src/System/Windows/Forms/Application.ParkingWindow.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Application.ParkingWindowTests.cs
Fixes #2947 
- Changing call to Handle with call to HandleInternal to prevent throwing an error when garbage collection is in progress.
- Customers will not see an error in case garbage collector cleans up the references to WinForms controls which are not used anymore.
- The case is applicable on high load environments when running application may require garbage collector to clean up controls to free memory.
- Yes
- Low
Cross-thread error on garbage collection.
No error.
- Manual testing;
- Unit tests (to be implemented);
- UI tests.
Version:   5.0.100-alpha.1.20073.10
Commit:    29f4d693a9
Base Path:   C:\Program …
=> Fixing 2947: Call to ParkingWindow.RemoveReflectChild() causes Cross-thread exception under load

eng/Version.Details.xml, eng/Versions.props, global.json, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Layout/TableLayoutSettingsTests.cs
- Updates dependencies from `dotnet/runtime`
- Includes a miscellaneous fix for how ILAsm tools are used. Without this, nuget restore failures happen. 
- Defines `$(MicrosoftNETCoreILAsmVersion)` required by `Microsoft.NET.SDK.IL.targets`
- Disables a couple of tests. 
- Opened https://github.com/dotnet/winforms/issues/3046 to track this. 
This is Part 1 (of 4) of changes needed to ingest updated runtime bits in WindowsDesktop. Once WinForms publishes to .NET 5 Dev channel, more changes are needed in dotnet/wpf and dotnet-wpf-int, and dotnet/windowsdesktop. 
In addition to this, I've re-enabled the subscription from `dotnet/runtime` to `dotnet/winforms`
```
λ darc get-subscriptions --source-repo dotnet/runtime --target-repo dotnet/winforms
https://github.com/dotnet/runtime (.NET 5 Dev) …
```
=> Re-enable flow from dotnet/runtime

src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs
Fixes #2979
- Make `NativeWindow.CreateWindow` reentrant
- Creating a control may execute user code, if such user code creates additional controls this causes reentrancy which under some conditions can lead to an exception because NativeWindow.CreateWindow isn't prepared for this case.
- No
- Fixes a data structure corruption, probably not going to get worse
- Manual testing of the scenario in #2979
=> Make NativeWindow.CreateHandle reentrant

src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.Designer.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FormTests.cs
Fixes #3022
- Correct a regression introduced in #695 when a condition was flipped that stopped setting form's [extended style flag `WS_EX_DLGMODALFRAME`](https://docs.microsoft.com/en-us/windows/win32/winmsg/extended-window-styles).
Customers now able to hide form's icon at runtime by setting `myform.ShowIcon = false`.
Workarounds involve either 
* setting an icon on a form to a transparent blank icon, or 
* performing an interop call to hide the icon _before_ hiding the icon:
```cs
if (myform.ShowIcon)
{
int extendedStyle = (int)User32.GetWindowLong(myform.Handle, User32.GWL.EXSTYLE);
User32.SetWindowLong(myform.Handle, User32.GWL.EXSTYLE, (IntPtr)(extendedStyle | (int)User32.WS_EX.DLGMODALFRAME));
}
myform.ShowIcon =false;
```
- Yes, introduced in .NET Core 3.0
- Minimal
- manual tests …
=> fix: Hide icon when `ShowIcon = false`

azure-pipelines.yml, eng/Screenshots.win.psm1, eng/common/build.ps1
- While tests are running capture screenshots every 3 minutes to try to gain visibility as to why tests are currently stalling.
=> Take screenshots on build agents during tests

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs
=> Fixed minor typo in AxHostTests

src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/DesignerAttributeTests.cs
Fixes #2413
Add reference to System.Drawing facade in order to be able to unit-test it. If you don't do this you inherit the System.Drawing from shared framework `Microsoft.NetCore.App` which does not contain the same redirects as the WinForms version, in particular the `UITypeEditor` redirect is missing.
* In the issue discussion it was noted that WinForms should not update the facade versions to 5.0 but instead keep them at 4.0 like the shared framework does.
* The facades don't contain any code, they'll always be a redirect of the Desktop Version for compatibility and not get any new stuff
* WinForms and the shared framework should agree about versioning, if the base framework doesn't level its facades for 5.0 neither should do WinForms for facades its replacing.
The versioning problem …
=> Fix facade reference and unskip unit test

eng/Version.Details.xml
Remove the unnecessary coherency attributes. These coherency attributes
are not needed because the packages are produced in the same build as
the CPD parent.
This also prepares this repo for 'strict' coherency
https://github.com/dotnet/arcade/issues/5195. Strict coherency is
significantly simpler and resolves a few cases where legacy CPD can
downgrade dependencies in incremental servicing. It looks in the CPD
parent's version.details.xml file to find the the CPD dependency, then
updates to that version. In winforms case, the CPD's dependencies are not
dependended on within runtime's own build, and the CPD attribute should be removed.
=> Remove unnecessary coherency attributes and prepare for strict coherency

src/System.Windows.Forms/src/System/Windows/Forms/TaskDialogPage.cs
- Remove code which would set `TaskDialogRadioButton.Checked` to `false` after binding it, in case another radio button was already checked.
This code (`radioButton.Checked = false;`) will never execute since `TaskDialogPage.Validate()` will already have ensured that only a single button is checked. Additionally, that code would actually throw if executed here as the button has already been bound.
- None; the condition (more than one radio button is checked) cannot be met in the current code.
- No
-
- Manual testing and code review
Thanks!
=> Remove dead code in TaskDialogPage.Bind()

src/System.Windows.Forms/src/System/Windows/Forms/Clipboard.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataFormats.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataFormatsTests.cs
Contributes to tests stability work.
Certain clipboard tests failed because they fed in `null` and empty string as formats. These would ultimately lead to failure when we attempted to register these formats with `RegisterClipboardFormatW` call.
```
[xUnit.net 00:00:09.54]     System.Windows.Forms.Tests.ClipboardTests.Clipboard_ContainsData_InvokeMultipleTimes_Success(format: "") [FAIL]
[xUnit.net 00:00:09.54]     System.Windows.Forms.Tests.ClipboardTests.Clipboard_ContainsData_InvokeMultipleTimes_Success(format: null) [FAIL]
X System.Windows.Forms.Tests.ClipboardTests.Clipboard_ContainsData_InvokeMultipleTimes_Success(format: "") [3ms]
Error Message:
System.ComponentModel.Win32Exception : Clipboard format registration did not succeed.
Stack Trace:
at …
```
=> Validate requested clipboard formats

src/System.Windows.Forms/src/System/Drawing/Design/UITypeEditor.cs
Fixes #3049 
- Add a mapping for `StringCollection` in `UITypeEditor`so correct editor opens 
- Customers will see the correct editor for an editor on type `StringCollection`
- Yes
- Low
**Incorrect Editor:**
**Correct Editor shown:**
- manual testing
=> Fix: Incorrect Editor for StringCollection

src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CursorTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripDropDownTests.cs
Fixes #3121
Make tests more robust against machine specific environments:
* taskbar not docked to the bottom
* having more than one monitor (or a real large monitor)
* having monitors with different DPI settings
- none outside of this repository, this only affects tests
- for developers on this repository, more people should be able to successfully run tests locally
- arguably adding tests which are written against a specific machine are a regression ;-)
- making tests slightly more tolerant may hide something, but its unlikely
- running tests locally now succeeds
- manually debugging tests to make sure the changes are minimal invasive
- a machine with two monitors having different DPIs
- secondary monitor placed to the right of the primary monitor
- task bar docket to the left on the …
=> make tests more robust

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/CollectionEditorTests.cs
Relates to issue mentioned in comments of #3049
- Explicit checks if `itemType` is of type `string` so user will still be able to create instances of a `string` if we don't have a mapping for the editor on the collection of `string` that the user is trying to invoke
- Customers will no longer see an error message when trying to create instances of `string` with an editor on a collection of `string` we don't have a mapping to
- No
- Low
**Error Message:**
**Fixed error for the case we don't have mapping for an editor on the collection of string user is trying to invoke:**
- Did some manual testing, but will need to be tested further
=> Fix: StringCollectionEditor Unable to Create Instance of Type System.String

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntryAccessibleObjectTests.cs
Fixes #3099
- Adding the test to reveal the issue with providing incorrect Collapsed/expanded accessible status for PropertyDescriptorGridEntries (like for expandable Font property).
- Fixing the issue with providing incorrect Collapsed/expanded accessible status for PropertyDescriptorGridEntries - with the fix if property row is expanded then Expanded accessible state is provided.
- Screen reader users will be able to distinguish the state of expandable PropertyGrid entries (like Font).
- There will be no inaccuracy when providing accessible collapsed/expanded state for PropertyGrid entries.
- No
- Minimal
- Unit tests.
- Automation.
C:\Users\v-milipi>dotnet --info
Version:   5.0.100-alpha.1.20073.10
Commit:    29f4d693a9 …
=> Fixing issue 3099 property descriptor grid entry accessible collapsed is incorrect

Documentation/contributing.md
There was a broken link pointing to CoreFX contributing doc.  Updated to point to dotnet/runtime contributing doc.
=> Updating contributing for broken link

Documentation/building.md
`System.Windows.Forms.sln` no longer part of repository,
and was replaced by `WinForms.sln`
=> Fix solution name in documentation

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowTests.cs
=> Disable dealocking tests

eng/Versions.props, src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupTests.cs
- Nullable annotate ListViewGroup
- Fix NRE bug
=> Nullable annotate ListViewGroup

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Layout/TableLayoutSettingsTests.cs
=> Fix skipping TableLayoutSettings_Serialize_InvalidStringConverter_DeserializeThrowsSerializationException

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetSystemMetrics.cs
We shouldn't have this throw an error because some machines run on windows 8, for example, which we support
Fixes #534
Contributes to #3121
=> Remove invalid debug assert in GetSystemMetricsForDpi

src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs
- Avoid allocating array for ListBox SelectionMode.One
=> Avoid allocating array for ListBox SelectionMode.One

src/System.Windows.Forms/src/System/Windows/Forms/ListBox.IntegerCollection.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBox.IntegerCollectionTests.cs
Proposed Changes
- Validate owner in ListBox.IntegerCollection constructor: fixes #3092
- Validate index in ListBox.IntegerCollection item accessor
- Validate destination in LisBox.IntegerCollection.CopyTo
- ~Make ListBox.IntegerCollection.IsSynchronized return false: contributes to #3088~
Should I create issues for each of the other fixes?
=> Add ListBox.IntegerCollection tests and fix bugs

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewColumnTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowTests.cs
=> Cleanup DataGridViewRow tests and add sync with DataGridViewColumn

src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
Relates to #3032 and #3100
- Make default encoding retrieval resilient in cases where user's encoding is not recognised by .NET's implementation, e.g. `codepage = 65001`. Refer to the [docs](https://docs.microsoft.com/dotnet/api/system.text.codepagesencodingprovider).
Hundreds of tests failing with:
```
************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
at System.Windows.Forms.RichTextBox.StreamOut(SF flags) in C:\Development\winforms\src\System.Windows.Forms\src\System\Windows\Forms\RichTextBox.cs:line 3101
at System.Windows.Forms.RichTextBox.get_Rtf() in C:\Development\winforms\src\System.Windows.Forms\src\System\Windows\Forms\RichTextBox.cs:line 686
at …
```
=> Make default encoding retrieval resilient

src/Common/tests/InternalUtilitiesForTests/src/ITestAccessor.cs, src/Common/tests/InternalUtilitiesForTests/src/TestAccessor.cs, src/Common/tests/InternalUtilitiesForTests/src/TestAccessors.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/EventHandlerService.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/EventHandlerServiceTests.cs, src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Printing/PrintPreviewControlTests.cs, src/System.Windows.Forms/tests/UnitTests/TestAccessorTests.cs, src/System.Windows.Forms/tests/UnitTests/TextBoxTests.cs
Add internals accessor helpers
Introduces ITestAccessor and related classes to keep test specific code out of the shipping assemblies.
Allows easy dynamic access to private/internal fields and members and provides a pattern for writing typed accessors.
Also supports creating of delegates, which allows for access to members that utilize ref structs which are not yet supported in reflection.
Removes existing TestAccessor classes from the shipping code. Updates most of the internal virtual methods on TextBox to private protected to encapsulate. Various comment / line spacing fixes to TextBox.
There are three commits in this PR. The first two clean up tests and internal access for the EventHandlerService. I kept them separate as they don't depend on the new functionality as I removed all of …
=> Provide internals test utilities

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BindingContextTests.cs
- Don't reuse theory data in same `IEnumerable<T>`. Move test out of `Theory` and into a `Fact` - I think there were some `WeakReference` bugs in that the lifetime of a `WeakReference` is only in the theory data and not in the test
Also dispose of all `IDisposable` objects.
Also reduce calling of `internal` APIs by using subclasses (this let me copy-paste the test into .NET Framework and everything built successfully)
Fixes https://github.com/dotnet/winforms/issues/1031
=> Fix BindingContext tests

global.json
We know this is going to be used in https://github.com/dotnet/winforms/pull/1932
But annoyingly we need to constantly rebase global.json in that PR because we get merge conflicts every time we add update arcade.
Instead, lets add this sdk to global.json in this PR which can be merged rapidly so we don't have to keep rebasing #1932
=> Add Microsoft.DotNet.CMake.Sdk to global.json

build-local.ps1, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/tests/UnitTests/RichTextBoxTests.cs
Fixes #3032
Cherry-picked from 9729e9cd6d4289150969bc3b481518b71f37a086
- .NET Core Encoding.Default gets UTF-8, not the default code page. Change our code to get the code page as we're sending data to the control as ASCII.
- Customers who may have relied on the original behaviour of RTB to have ASCII as the default code page will be able to continue porting their apps to .NET Core 3.1.
- Yes
- Limited to RTB use in .NET Core 3.1
After assigning to `richTextBox.Rtf` some rtf code with nonbreaking space (160 char code), RichTextBox converts it to `\'c2\~` insted of `\~`.
=> Fix RichTextBox Rtf encoding

src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
Fixes #2797 
Relates to #3062
- Adding the test that reveals the issue with forcing control handle creation on changing SelectedItem and SelectedIndex of the ComboBox control.
- Adding the fix that prevents executing accessibility logic in case the control handle is not yet created and prevents preliminary handle creation (forcing handle creation) in this case.
- Users will not experience side effects related to forcing preliminary handle creation.
- Yes
- Minimal
- Manual test.
- Unit test.
- Already tested and verified in 5.0 - no regression.
- 
.NET Core SDKs installed:
3.1.100 [C:\Program Files\dotnet\sdk]
3.1.200-preview-014883 [C:\Program Files\dotnet\sdk]
3.1.201 …
=> Issue 2797 combo box selected item change forces handle creating

.github/ISSUE_TEMPLATE/config.yml
This .yml adds quick links to other repos below the existing issue template buttons in your new issue flow.
For an example of what this looks like, see https://github.com/danmosemsft/runtime/issues/new/choose (the white buttons below your existing green buttons)
We are adding this in dotnet/runtime (https://github.com/dotnet/runtime/pull/36431). Reasoning: it's sometimes confusing which is the correct repo to open an issue in. The goal here is to make it easier to open an issue in the correct repo first time so we need to move fewer issues and they more quickly get attention from the right people.
=> Add links in "new issue" flow to other related repos

src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
Fixes #3251
(cherry picked from commit 7a5e6e589d97cb585db29233e1f6c5709c52dc22)
- Porting .NET Framework fix for DataGridViewComboBox cell issue related to the control handle recreating when restructuring accessibility hierarchy tree.
- Costumers will not experience application error when working with the DataGridView containing ComboBox cell. 
- Yes
- Minimal
=> Fixing DataGridViewComboBoxCell: ComboBox causes application crash on handle recreating related to accessibility hierarchy tree restructuring

src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ObjectCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBox.ObjectCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs
- Validate owner in ListBox.ObjectCollection constructor
- Validate destination in ListBox.ObjectCollection.CopyTo
- Validate owner.CheckDataSource in ListBox.ObjectCollection.Remove
=> Add ListBox.ObjectCollection tests and fix bugs

src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.ReleaseStgMedium.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataObject.FormatEnumerator.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataObject.OleConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs, src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataObjectTests.cs
Fixes #3025
Contributes to #1268
- use ReleaseStgMedium for ownership handling as suggested by win32 docs
- do not assume third party implementations of IDataObject.GetData return the medium which was asked for (Office sometimes ignores the medium the caller asks for and always returns the medium it happens to be using internally). Since Windows/OLE does not pose constraints on what the DataObject source returns WinForms needs to be robust and handle this case instead of crashing the whole process.
- clean up dead code related to metafiles, most code supporting them is already gone
- no more crashing when asking Office for "EnhancedMetafile"
- Yes (earlier Desktop Framework versions which still supported metafiles did not crash; latest Desktop Framework however also crashes the whole …
=> Fix DataObject.GetData issues

src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignSurfaceTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignerHostTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/SiteNestedContainerTests.cs
So I'm investigating #1460 and #1151. 
It seems like the failure in `DesignerHost_Add_ComponentDisposeThrowsDuringUnloadingDispose_ThrowsInvalidOperationException` and `DesignSurface_View_GetWithInvalidSupportedTechnologies_ThrowsNotSupportedException` etc. etc. are related to locking of `LicenseManager`. Not really sure how to fix this in the tests.
It seems like the failure in `DesignerHost_Add_DuringUnload_ThrowsException` and `SiteNestedContainer_Add_Unloading_Nop` are unrelated to this and instead related to `DesignSurface.CreateDesigner` returning null. See https://github.com/dotnet/winforms/issues/1460#issuecomment-515985498
Looking at the stack trace of the failure in #1560
```cs
System.Exception : There is no designer for the class …
```
=> Dispose everything in DesignerSurface related tests

src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellTests.cs
- Cleanup and enhance DataGridViewCell testing
Basically I started by removing instances of creating `DataGridView` in test data, but ended up doing way more :)
=> Cleanup and enhance DataGridViewCell testing

src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeTests.cs
- Add TreeNode property tests
- Fix TreeNode image index validation and make idempotent
- Return from `UpdateNode` the node's tree view is disposed: fixes #3127
=> Add TreeNode property tests, add missing argument validation and make idempotent

src/System.Windows.Forms.Primitives/tests/Interop/Oleaut32/ITypeInfoTests.cs
Fixes #3305
Fixes #3271
Release ITypeInfo RCW manually instead of letting the GC clean up
I'm doing this seperately from PR #3276 so it can be reviewed and merged before figuring out all the problems of the package updates.
Tests should become more stable regardless how they are run
Yes (after merging PR #3276)
no known risk
Tests start failing after PR #3276
Tests should succeed before and after PR #3276
Locally running tests both with and without PR #3276
local
=> manually release ITypeInfo references

src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ButtonBaseTests.cs
- Make ButtonBase setters idempotent: setting the same value shouldn't invalidate, layout etc
Might have some perf wins but mostly just for good consistency
=> Make ButtonBase setters idempotent

src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.IShellItem.cs, src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHCreateItemFromParsingName.cs, src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHCreateShellItem.cs, src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHILCreateFromPath.cs, src/System.Windows.Forms.Primitives/src/System/ExternDll.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/FileDialogCustomPlace.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/FileDialogCustomPlacesCollection.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/FileDialog_Vista_Interop.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/FileDialog_Vista.cs, src/System.Windows.Forms/src/System/Windows/Forms/FolderBrowserDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/SaveFileDialog.cs
- Cleanup remaining ExternDll.Shell32 interop
There's still a bunch left in `FileBrowserNative` for vista stuff, but that can wait for another day. Priority is to clean things out of `UnsafeNativeMethods`!
=> Cleanup remaining ExternDll.Shell32 interop

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitButton.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripDropDownItemTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
- Add ToolStripDropDownItem tests and related test
- Remove dead code from ToolStripItem - `invalidatePainting`  always true
=> Add ToolStripDropDownItem tests and related test

src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
Fixes #2769
Implemented the [suggested fix](https://github.com/dotnet/winforms/issues/2769#issuecomment-579180352) from @stephentoub.
This fixes a method broken by changes in .NET Core. Most customers are probably unaware of the broken method since it is not a documented breaking change, nor are there other issues reporting the breakage.
- Yes
There should be no risk. I have tested this fix myself and confirmed that it works.
=> fix: Application.Restart throws InvalidOperationException

src/System.Windows.Forms.Primitives/tests/Interop/Oleaut32/IDispatchTests.cs, src/System.Windows.Forms.Primitives/tests/Interop/Oleaut32/ITypeInfoTests.cs
Fixes #3305
Relates to #3271
Release ITypeInfo RCW manually instead of letting the GC clean up. Original PR #3315 missed one reference, this generally made the test run more stable but it was still flaky.
Tests should become more stable regardless how they are run
Yes (after merging PR #3276)
no known risk
Tests start failing after PR #3276
Test were still failing occasionally after PR #3315
Tests should succeed even more before and after PR #3276
* Locally running (a lot of) tests with PR #3276
* Running PR #3276 with this fix on the CI machine (this PR is extracted from the nuget package update since it may still need some time)
* going through the test file and looking for ITypeInfo references
local & CI
=> manually release ITypeInfo references (missed one)

eng/Versions.props, src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/MyServices/ClipboardProxyTests.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/CheckedListBoxAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/ListBoxAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Handlers.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/WindowsFormsSynchronizationContextTests.cs, src/System.Windows.Forms/tests/UnitTests/WebBrowserBaseTests.cs
Fixes #3122
Update Xunit.StaFact package to consume bugfixes made upstream
None, test infrastructure only
No
Unknown issues may be introdcued by updating 3rd party packages, but getting fixes for already known issues should outweight that risk.
Unable to run WinFormsTheory with complex MemberData inside VS
Able to run WinFormsTheory with complex MemberData inside VS
(+ various other fixes I don't know exactly how to test for, like calling OleRequired to initialize OLE on the STA thread)
Making sure one of the known issues is actually fixed. I didn't explicitly test for other fixes that have been merged.
local
=> update Xunit.StaFact to include bugfixes

src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.EN.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBoxConstants.cs
- Add EN enum in Interop RichEdit.
- Remove EN constants and replace their usages with the above enum values.
=> Add EN enum in Interop RichEdit

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItem.cs
Fixes #3248
- Avoid accessing the `DropDown` property of menu items when there is no drop-down present. The property would always create one which is unintended.
- Less memory used
- Not sure. I couldn't track down when the code for keyboard hooks was first added, the rest of the code tries to avoid unintentionally creating the drop-down objects.
- Low
- Tested on production application running under SciTech Memory Profiler
- .NET 5 (master, winforms@d851dac649d74c3a1d2b416713dd22de14b93fe1)
- .NET Core 3.1.200 with backported fix
=> Avoid unnecessarily creating ToolStripDropDownMenu due to keyboard tooltip hook

src/System.Windows.Forms.Primitives/src/Interop/UxTheme/Interop.TMT.cs, src/System.Windows.Forms/src/PublicAPI.Unshipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/FontProperty.cs, src/System.Windows.Forms/src/System/Windows/Forms/VisualStyles/VisualStyleRenderer.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/VisualStyles/VisualStyleRendererTests.cs
Fixes #3340
- Add `FontProperty.TextFont`, which maps to `TMT_FONT` on the native side.
- I can now get the font used by "instruction text" in Windows using class name `TEXTSTYLE`, part 1, state 0, and `FontProperty.TextFont`.
- No, this was never before possible.
- This is a new feature, it should not break anything.
- No unit tests yet. Guidance here would be appreciated.
```
Version:   5.0.100-preview.5.20264.10
Commit:    b0f362349a
OS Version:  10.0.19631
Base Path:   C:\Program Files\dotnet\sdk\5.0.100-preview.5.20264.10\
Version: 5.0.0-preview.6.20264.1
Commit:  bdd7235c43
3.0.100 [C:\Program Files\dotnet\sdk] …
```
=> Add FontProperty.TextFont

src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiComboBoxTests/DerivedComboBox.cs, src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiComboBoxTests/MauiComboBoxTests.cs
Fixes #3354
Fix the condition that incorrectly handled the overflow.
Regression introduced in #1837
- manual tests
- MAUI tests
=> Don't measure invalid ComboBox items

src/System.Windows.Forms/src/PublicAPI.Unshipped.txt, src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupCollapsedState.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupEventArgs.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.Designer.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.resx, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupEventArgsTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupTests.cs
Fixes #3067 
- Add CollapsedState API to `ListViewGroup`
- Customers will have the ability to make their ListViewGroups collapsible and collapse/expand items in the group
- Unit testing
- The user can either collapse item(s) through single click on chevron or double click on group header
=> Implement Collapsible/Collapsed for ListViewGroup

src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs, src/System.Windows.Forms/src/System/Windows/Forms/ColumnHeader.cs, src/System.Windows.Forms/src/System/Windows/Forms/ImageList.Indexer.cs, src/System.Windows.Forms/src/System/Windows/Forms/Label.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ButtonBaseTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ColumnHeaderTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/LabelTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeTests.cs
Resolves #3353
- Setters for `ImageKey` and `ImageIndex` properties were made idempotent in #3126, however the change didn't account for the fact that the default `ImageKey == ""` and not `null`.
This caused failures to reset `ImageIndex`, when `ImageKey` was set to `""`; and in reverse - failure to reset `ImageKey` when `ImageIndex` was set to `-1`.
Tweak the setters to continue execution for default values.
- In addition apply NRT annotations to ` ImageList.Indexer` type, and expose the defaults in a reusable manner.
- unit tests
=> Correct ImageKey/ImageIndex properties

src/System.Windows.Forms/src/System/Windows/Forms/GroupBox.GroupBoxAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/GroupBox.cs
Fixes #3229 
- Moving GroupBox accessible object to a separate file.
- Minor refactoring and code style changes.
- No functional changes.
- Improving development experience for GroupBox control accessibility.
- No
- Minimal
- Separated accessible object should be covered by unit test.
- UI automation.
- Inspect too.
- Accessibility client apps.
.NET Core 5.0
Version: 5.0.100-alpha.1.20073.10
Commit: 29f4d693a9
OS Version: 10.0.18363
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\5.0.100-alpha1-05536
Version: 5.0.0-alpha.1.20072.3
Commit: c3dc1fdfdc
=> Moving GroupBox accessible object to a separate file

src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.LVGROUPW.cs, src/System.Windows.Forms/src/PublicAPI.Unshipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupTests.cs
Fixes #2655
- Add subtitle API to `ListViewGroup`
- Customers will have the ability to add subtitles to their ListViewGroups
- No
- Unit testing
- Correct me if I'm wrong, but for accessibility purposes I believe we'll need to expose the UIA Text Pattern
=> Implement Subtitle Property for ListViewGroup

src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.LIF.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.LIS.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.LITEM.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.NMLVLINK.cs, src/System.Windows.Forms/src/PublicAPI.Unshipped.txt, src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupEventArgs.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/GroupLinkClickEventArgsTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupTests.cs
Fixes #2656
- Add Task API to `ListViewGroup`
- Add GroupLinkClick event handler/args in `ListView`
- Customers will be able to add tasks to their ListViewGroups
- Customers will receive callback to do as they please once group task clicked
- No
- Unit testing
=> Implement Task Property for ListViewGroup

src/System.Windows.Forms.Primitives/src/Interop/UiaCore/Interop.UiaDisconnectProvider.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/OsVersion.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
Partially fixes #3182
- Call `UiaDisconnectProvider` to explicitly detach UIA providers when a control or form is being disposed. This ensures that clients that leak UIA objects cannot leak them in the target application indefinitely. It follows the pattern from the [Windows SDK sample](https://github.com/microsoft/Windows-classic-samples/tree/master/Samples/UIAutomationCleanShutdown).
- UIA objects for disposed controls won't cause memory leak
- UIA clients accessing UIA providers for disposed controls will get `UIA_E_ELEMENTNOTAVAILABLE` error
- No
- There should be no risk when the application is accessed by properly implemented UIA clients. These clients should be prepared to handle `UIA_E_ELEMENTNOTAVAILABLE` error and also release the UIA objects in timely manner. For misbehaving …
=> Call UiaDisconnectProvider from Control.ReleaseUiaProvider

global.json, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Contributes to dotnet/arcade#5583
- Install x86 runtime for testing.
- Ensures proper testing in a 32 bit process.
- No
- None, other than increased download at first build and potential test failures from the increased coverage.
- This adds no functionality so no added tests.
- Using default runtimes and SDK already used for testing.
=> Add x86 runtime for testing

src/System.Windows.Forms/src/System/Windows/Forms/Clipboard.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataObject.FormatEnumerator.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataObjectTests.cs
- Cleanup DataObject.FormatEnumerator and add DataObject FormatEnumerator tests
- Remove dead CAS code
=> Cleanup DataObject.FormatEnumerator and add DataObject FormatEnumerator tests

src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs, src/System.Windows.Forms/tests/UnitTests/CheckedListBoxTests.cs
See https://github.com/dotnet/winforms/pull/3174#discussion_r422615154
It now returns "ABC\0", which is unintended.
So I wrote some more tests in #3107 that exercise this code path and the tests passed on .NET Framework and .NET Core. It seems like we also already had tests testing this code path as well.
I was a little confused why the tests passed until I realised that the only place where this method was called was in code like
```cs
if (string.Compare(owner.GetItemText(value), owner.NativeGetItemText(index), true, CultureInfo.CurrentCulture) != 0)
```
So I tested in my sandbox and found that 
```cs
Console.WriteLine(string.Compare("abc", "abc\0", true, CultureInfo.CurrentCulture));
```
prints out
```cs
0
```
Essentially meaning that whilst this changed behaviour, it didn't break …
=> Fix trailing null in NativeGetItemText

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ByteViewer.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ByteViewerTests.cs, src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.CP.cs, src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.MultiByteToWideChar.cs, src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.WideCharToMultiByte.cs, src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.DROPFILES.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageList.ImageCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TableLayoutPanelTests.cs
- Cleanup CopyMemory/WideCharToMultiByte
=> Cleanup CopyMemory/WideCharToMultiByte

src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
In a multi DPI environment, DPI changed events triggered only when there is a DPI change happened for the Handle directly or via its parent. So, it is necessary to **not** set the
owner before creating the Form handle. Otherwise, the window may never receive DPI changed
event even if its parent Form has different DPI. Users at runtime, has to move the Form window
between the screens to get the DPI changed events triggered.
Please see associated issue for more details and screen shots the behavior at runtime.
Fixes #3390 
Changing the order when setting the owner of a child form.
-No
=> Fixing DPI changed events by changing the order in setting child Form owner

src/System.Windows.Forms.Design/src/System/Drawing/Design/ImageEditor.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ImageListImageEditor.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/Drawing/Design/BitmapEditorTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/Drawing/Design/ImageEditorTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ImageListImageEditorTests.cs
Fixes #3309
Loading an image from a stream passes ownership, do not dispose the stream
* Fix regression in ImageEditor
* Fix regression in ImageListImageEditor
* Add test to ensure BitmapEditor doesn't regress
Using ImageEditor or ImageListImageEditor through a property grid or designer was producing partially defunct images whose underlying stream was disposed, depending on the operation performed on the image this could load to errors.
Yes
unlikely to have any risk, this restores behavior from before the regression
Image loaded from ImageEditor or ImageListImageEditor could throw exceptions on various operations
Image loaded from ImageEditor or ImageListImageEditor should operate normally
Ensure unit tests perform an operation accessing the underlying stream.
=> do not dispose stream owned by image

src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/ErrorProviderAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/PropertyGridInternal/PropertyGridView.GridViewListBoxAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PictureBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolTipTests.cs
Contributes to #3361
Dispose controls instead of letting GC collect them
- Add missing using statements
- Make `ErrorProviderAccessibleObjectTests` disposable
Not doing so may hang CI if their UI thread terminates before GC collects them
- lower risk of hanging CI test runs
- minimal, unlikely to break any test
- tests were leaving controls for GC to collect
- controls are disposed before UI thread terminates
- making sure tests still succeed
- logging finalizer calls like described in #3361
=> Dispose controls in unit tests

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/WebBrowserTests.cs
```
[xUnit.net 00:04:07.67]     System.Windows.Forms.Tests.WebBrowserTests.WebBrowser_DocumentText_SetValidHtml_GetReturnsExpected [FAIL]
X System.Windows.Forms.Tests.WebBrowserTests.WebBrowser_DocumentText_SetValidHtml_GetReturnsExpected [700ms]
Error Message:
Assert.Equal() Failure
Expected: 6
Actual:   7
Stack Trace:
at System.Windows.Forms.Tests.WebBrowserTests.WebBrowser_DocumentText_SetValidHtml_GetReturnsExpected() in C:\Users\hughbe\Documents\GitHub\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\WebBrowserTests.cs:line 806
--- End of stack trace from previous location ---
```
The number of times the document title changed handler is called depends on the version of windows etc.
Just verify that it was called at least once
=> Fix local WebBrowser tests

src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.CHARFORMAT2W.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/UnsafeNativeMethods.cs, src/System.Windows.Forms.Primitives/tests/Interop/Richedit/CHARFORMAT2WTests.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs, src/System.Windows.Forms/tests/UnitTests/TextBoxBaseTests.cs
- Consolidate CHARFORMATW and CHARFORMAT2W
We only need one definition of `CHARFORMATW`, and that is the one with the most functionality, i.e. `CHARFORMAT2W`
=> Consolidate CHARFORMATW and CHARFORMAT2W

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HtmlDocumentTests.cs
- Make HtmlElement tests machine agnostic - make sure its not empty and doesn't contain garbage like trailing null chars
=> Make HtmlElement tests machine agnostic

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HtmlDocumentTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HtmlElementTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/WebBrowserTests.cs
Workaround for #3358
Prevent running WebBrowser control tests on multiple UI threads in parallel as that seems to cause memory corruption (unknown whether root cause is in WinForms or native control)
no random crashes due to memory corruption in unit tests, should improve CI sucess rates
no
may slow down tests a bit
random CI crashes or test failures that made no sense due to memory corruption
prevent memory corruption, allowing CI runs to perform normally
isolated repro scenario into a separate application, it doesn't seem to cause memory corruption when only one UI thread is running the WebBrowser control
=> WebBrowser doesn't like multiple UI threads

src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ControlAccessibleObjectTests.cs
Fixes #3410
- Set `IsPatternSupported` for `LegacyIAccessiblePatternId` as true in `ControlAccessibleObject`. It will cause all control accessible objects to implement LegacyIAccessible.
- A customer can see correct some accessible properties for accessible objects, which didn't implement LegacyIAccessiblePattern.
- No
- Minimal
- manual testing
- unit testing
- CTI
- using Inspect tool
- Microsoft Windows [Version 10.0.18363.836]
- .Net Version:   5.0.100-preview.7.20305.3
=> Implementing LegacyIAccessiblePattern supporting for ControlAccessibleObject

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CursorsTests.cs, start-vs.cmd
Use the developer command prompt VS if available, fall back on devenv
in the path, then finally to file association for .sln.
Normalize casing of the commands.
cc: @lonitra
=> Update start-vs.cmd to use current VS

src/Accessibility/src/Accessibility.ilproj
Fixes failures to resolve `IAccessible` in **System.Windows.Forms.Primitives** inside the IDE.
=> Define a CompileDesignTime target for Accessibility.ilproj

src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupTests.cs
Fixes #3424 
- throw `InvalidEnumArgumentException` when the `CollapsedState` of a `ListViewGroup `
is set to a value outside the range of the `ListViewGroupCollapsedState` enum
- Prevents user from having invalid enum for `ListViewGroup.CollapsedState`
- No
- Low
- Unit testing
=> Throw Exception setting invalid value for 'ListViewGroupCollapsedState'

src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.ENM.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBoxConstants.cs
- Add ENM enum in Interop RichEdit.
- Remove ENM constants from RichTextBoxConstants.cs.
=> Add ENM enum in Interop RichEdit

eng/configure-toolset.ps1, eng/packageContent.targets
Example log from running `build.ps1`
```
PS C:\Users\hughbe\Documents\GitHub\winforms> .\build-local.ps1
Building the solution...
Processing C:\Users\hughbe\Documents\GitHub\winforms\eng\..\global.json
File 'C:\Users\hughbe\.netcoreeng\native\temp\cmake-3.14.2-win64-x64.zip' already exists, skipping download
File 'C:\Users\hughbe\.netcoreeng\native\temp\WinShimmer.zip' already exists, skipping download
VERBOSE: Extracting 'C:\Users\hughbe\.netcoreeng\native\temp\WinShimmer.zip' to
'C:\Users\hughbe\Documents\GitHub\winforms\eng\..\.tools\native\bin\WinShimmer'
File 'C:\Users\hughbe\.netcoreeng\native\temp\dotnet-api-docs_netcoreapp3.0-0.0.0.1-win64-x64.zip' already exists, skipping download
dotnet-api-docs_netcoreapp3.0 was not found in .
Native tools bootstrap failed
The property 'path' …
```
=> Avoid initializing native tools twice

src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs, src/System.Windows.Forms/src/System/Windows/Forms/ColumnHeader.cs, src/System.Windows.Forms/src/System/Windows/Forms/Label.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeTests.cs
Resolves #3425
Relates to #3364
- Setters for `ImageKey` and `ImageIndex` properties were made idempotent in #3126, however the change didn't account for the fact that the default `ImageKey == ""` and not `null`.
This caused failures to reset `SelectedImageIndex` or `StateImageIndex`, when `SelectedImageKey` or `StateImageKey` were set respectively to `""`; and in reverse - failure to reset keys when indices were set to `-1`.
Tweak the setters to continue execution for default values.
- More clean up to use const instead of magic number.
- unit tests
=> Correct SelectedImageKey/SelectedImageIndex/StateImageKey/StateImageIndex properties

src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs, src/System.Windows.Forms/tests/UnitTests/PropertyGridInternal/PropertiesTabTests.cs, src/System.Windows.Forms/tests/UnitTests/PropertyGridTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Handlers.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/PropertyTabTests.cs
This is not supported in .NET Core
=> Remove PropertyGrid remoting code

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.CLIENTCREATESTRUCT.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/MDIClient.cs
- Add CLIENTCREATESTRUCT in Interop User32 and remove the corresponding class from NativeMethods.cs.
- Remove unused COMRECT.
=> Add CLIENTCREATESTRUCT in Interop User32 and remove unused COMRECT

src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ControlAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTextBoxEditingControlTests.cs
Fixes #3419
Added check for "IsHandleCreated" flag to "RaiseAutomationEvent" and "RaiseAutomationPropertyChangedEvent" methods. Added wrapper of RaiseAutomation methods to ControlAccessibleObject
- No
- Minimal
- Unit testing
- Microsoft Windows [Version 10.0.18363.836]
- .Net Version: 5.0.100-preview.7.20308.6
=> Adding check for "IsHandleCreated" flag to RaiseAutomation methods

start-vs.cmd
After repaving I discovered my previous changes weren't correct. You can't check exists on partial paths. Quoting was wonky, etc.
I've tested this one thoroughly for all three handled states and it appears to work fine.
=> Fix start-vs.cmd

src/System.Windows.Forms/src/System/Windows/Forms/Label.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MultipleControls.Designer.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/GroupBoxAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/LabelAccessibleObjectTests.cs
Fixes #3294
- Adding LegacyIAccessiblePattern provider to LabelAccessibleObject.
- Adding LegacyIAccessiblePattern provider to GroupBoxAccessibleObject.
- By adding LegacyIAccessiblePattern properties values from AccessibleName and AccessibleRole is provided to Inspect's LegacyIAccessible.Name and LegacyIAccessible.Role fields and corresponding MSAA fields if UIA support for control is enabled.
- Adding tests to verify the fix.
- Developers will be able to specify custom AccessibleName and AccessibleRole for the Label control.
- Yes (introduced in .NET Framework 4.8)
- Minimal
Setting custom AccessibleName and AccessibleRole has no effect on the values of AccessibleName and AccessibleRole fields shown in Inspect or Accessibility Insights.
Custom AccessibleName and AccessibleRole are …
=> Fixing Issue 3294 to allow specify custom AccessibleName and AccessibleRole for Label control

src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxPropertyDescriptor.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHost.AxPropertyDescriptorTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs
- Test AxHost ICustomTypeDescriptor implementation
=> Test AxHost ICustomTypeDescriptor implementation

src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.ES.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBoxConstants.cs
- Add ES enum in Interop Richedit.
- Remove ES and ES_X constants from RichTextBoxConstants.cs and replace their usages with the above enum values.
=> Add ES enum in Interop Richedit

src/System.Windows.Forms/src/System/Windows/Forms/AxHost.State.cs
- Looks like that some disposables should be disposed in this class.
=> Dispose BinaryReader, BinaryWriter and MemoryStream in AxHost.State

src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.ECO.cs, src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.ECOOP.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBoxConstants.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
- Add ECO and ECOOP enums in Interop Richedit.
- Remove ECO and ECOOP constants from RichTextBoxConstants.cs and replace their usages with the above enum values.
- Remove unused WCH_EMBEDDING constant.
=> Add ECO and ECOOP enums in Interop Richedit

src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewHeaderCellTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs
- Fix DataGridView.OnRowHeadersWidthSizeModeChanged event invocation
- Fix DataGridView.OnColumnHeaderHeightChanged forcing handle creation
Fixes #3371
Fixes #3372
=> Fix DataGridView.OnRowHeadersWidthSizeModeChanged event invocation

eng/Version.Details.xml, eng/Versions.props
Strict coherency means that if your repo declares a dependency with a CPD attribute, the CPD parent must have a direct dependency on that dependency.
This means that for WPF, there are a few dependencies where it declares Microsoft.Private.Winforms to be the parent, but winforms does not have a dependency on those dependencies. Add them.
Reasons for this approach over the current approach:
- This eliminates some ambiguous tie-breaking scenarios that are very problematic and dangerous in servicing
- Those tie breaking scenarios require the use of BAR to break the ties. If the DB data were to be lost then the tie-breaking would do unexpected things.
=> Prepare for strict coherency

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageListTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
During investigation of #3358 I noticed that some ImageLists were finalized.
ImageLists are designer components that need to be disposed.
none
no
none
ImageList handles were collected by GC and released in the finalizer
ImageList handles should be disposed by the test that created them
setting a breakpoint in the `NativeImageList` finalizer and ensure its not hit
=> ImageList must be disposed

src/System.Windows.Forms/src/System/Windows/Forms/CursorConverter.cs
- Looks like that a MemoryStream used in ConvertFrom method should be disposed.
=> Dispose MemoryStream in ConvertFrom method of CursorConverter

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.DpiAwarenessContext.cs
Resolves #2969.
W10 1607 is not fully compatible with PerMonv2, and this leads to crashes interacting with `ContextMenuStrip`.
`CommonUnsafeNativeMethods.SetThreadDpiAwarenessContext` may return `DPI_AWARENESS_CONTEXT_UNSPECIFIED` result that is never checked, however we set `dpiAwarenessScopeIsSet` flag assuming the scope was set.
When disposing the scope we pass the obtained context to `TrySetThreadDpiAwarenessContext` that tries to restore the scope back to the original. However in event the original was `DPI_AWARENESS_CONTEXT_UNSPECIFIED` it leads to ANE, that was observed in #2969.
- Customers on W10 1607 will now be able to use `ContextMenuStrip` in `HighDpiMode.PerMonitorV2`
- 
- Yes
- Minimal
=> fix: ContextMenuStrip leads to crash on W10 1607

src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
- Use generic lists in MonthCalendar.
=> Use generic lists in MonthCalendar

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.BeginPaintScope.cs
Getting the DC again was a copy/paste mistake
=> Fix HDC in BeginPaintScope

src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Disposing a listview control that has shared instances of `ImageList` wired to any of its properties will cause memory leaks due to incorrect unwiring of associated `ImageList` events.
Rework wire/unwire routines to match `TreeView` implementation.
Resolves #3494
- No memory leaks disposing `ListView` controls.
- 
- No
- Manual using the provided sample at https://blog.ramondeklein.nl/2009/05/18/listview-may-leak-with-imagelists/
- unit test (courtesy of @weltkante)
=> Fix ImageList memory leaks

src/System.Windows.Forms/src/PublicAPI.Unshipped.txt, src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupImageIndexer.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItemImageIndexer.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Fixes #3301 
- Add `TitleImageIndex` and `TitleImageKey` API to `ListViewGroup`
- Add `GroupImageList` to `ListView`
- Customers will be able to set icons next to `ListViewGroup` header
- No
- Unit testing
=> Implement TitleImageIndex/Key to ListViewGroup

src/System.Windows.Forms/src/PublicAPI.Unshipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/PictureBox.PictureBoxAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/PictureBox.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/PictureBox.PictureBoxAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/PictureBoxAccessibleObjectTests.cs
Fixes #3232 
- Adding UIA accessibility support for PictureBox control.
- Moving PictureBox accessible object implementation to a separate file.
- Improving development experience for ListView control accessibility.
- Prerequisite for #2164.
- No
- Minimal
- Manual testing;
- Unit tests (to be implemented);
- UI automation.
- Inspect;
- Accessibility Insights;
- Narrator and other accessibility client apps.
.NET Core 5.0
Version: 5.0.100-alpha.1.20073.10
Commit: 29f4d693a9
OS Version: 10.0.18363
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\5.0.100-alpha1-05536
Version: 5.0.0-alpha.1.20072.3
Commit: c3dc1fdfdc
=> Adding UIA accessibility support for PictureBox control

src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.HRGN.cs, src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.RegionScope.cs, src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/Gdi32/RegionTests.cs, src/System.Windows.Forms/src/System/Windows/Forms/DCMapping.cs
- Need a temporary region to get a region
- Add tests
- Remove unused code from DCMapping and use RegionScope
=> Fix getting existing region in RegionScope

src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.ImageList.Duplicate.cs, src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/ImageList.NativeImageList.cs, src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs, src/System.Windows.Forms/src/System/Windows/Forms/ImageListStreamer.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs, src/System.Windows.Forms/tests/UnitTests/SerializableTypesTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
- Centralise lifetime management of native ImageList
Move calls to Create, Duplicate and Destroy into NativeImageList to reduce a chance of interleaved calls to Win32 API.
- Track disposal of NativeImageList
- Dispose  and do not reuse `ImageList` instances in tests. 
Quite likely the observe AVE were a result of use reusing a shared instance of an `ImageList` across theory runs. Quite likely xUnit would dispose the instance while another test was run, leading to a corrupt heap. Resolves #3358
- Prevent ImageList allocation disposing PropertyGrid. Resolves #3485
- Refactor `ToolStripItem.Animate` and `ToolStripItem.set_Image` methods to reduce nesting
=> Solve image list woes

src/System.Windows.Forms.Primitives/src/Interop/UiaCore/Interop.IRawElementProviderHwndOverride.cs
Fixes #3452
- Just remove `[ComImport]` attribute
- ComboBox doesn't break Narrator and Inspect
- Yes, from 423b2bc5726b4109741f189e34e5f37f90140d01
- Minimal
- Inspect doesn't response after selecting ComboBox editing control
- ComboBox AccessibleObject works well
- Manual testing 
- CTI
- Using Narrator and Inspect
- .Net Version: 5.0.0-preview.8.20326.9
=> [Accessibility] Fixing ComboBoxAccessibleObject issue when Narrator and Inspect don't respond

src/System.Windows.Forms.Primitives/src/Interop/UiaCore/Interop.ILegacyIAccessibleProvider.cs, src/System.Windows.Forms.Primitives/src/Interop/UiaCore/Interop.IRawElementProviderHwndOverride.cs, src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/InternalAccessibleObject.cs
Running the following test 
```cs
[WinFormsFact]
public void AccesibleObject_ILegacyIAccessibleProviderGetSelection_Invoke_ReturnsExpected()
{
var o = new AccessibleObject();
Test_ILegacyIAccessibleProviderGetSelection(o);
}
[DllImport(NativeTests, ExactSpelling = true)]
private static extern void Test_ILegacyIAccessibleProviderGetSelection(
[MarshalAs(UnmanagedType.IUnknown)] object pUnk);
```
```cpp
#define TEST extern "C" __declspec(dllexport)
TEST void WINAPI Test_ILegacyIAccessibleProviderGetSelection(IUnknown* pUnknown)
{
HRESULT hr;
ILegacyIAccessibleProvider* pLegacyIAccessibleProvider;
hr = pUnknown->QueryInterface(IID_ILegacyIAccessibleProvider, (void**)&pLegacyIAccessibleProvider);
assert(hr == S_OK);
#if false
SAFEARRAY *result = (SAFEARRAY*)(long)0xdeadbeef;
hr = …
```
=> Fix ILegacyIAccessibleProvider.GetSelection return type

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ColumnHeaderTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageListTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollableControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/VisualStyles/VisualStyleRendererTests.cs
Contributes to #3487
Use factory methods instead of sharing disposable objects across MemberData sets
Sharing disposable objects relies on undocumented behavior of xunit (it does not guarantee that disposal happens after all tests are run, it could just as well dispose each set individually after running it). It also introduces hidden dependencies between tests that may lead to undesired interaction between tests.
none
no
none
sometimes disposable objects were shared between MemberData sets
disposable objects should not be shared between MemberData sets
code review
=> Reduce sharing of disposable objects across MemberData sets

eng/sdl-tsa-vars.config
This enables nightly SDL validation to run, rather than running during the build
=> Add sdl config

eng/ci.yml
Reduces overall build time. These validations are being run nightly and on every build candidate
=> Disable per-build SDL + other validations

eng/MemDump.win.psm1, eng/Screenshots.win.psm1, eng/ci.yml, eng/custom-cibuild.ps1
Resolves #3298
- Spin up a background thread that signals at 15 minute mark, and looks for a dotnet.exe process that runs our tests. 
- If one is or more processes are found, collect their heap dumps and kill those processes.
=> Collect memory dumps for hung tests

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItemCollection.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemCollectionTests.cs
- Add tests for ToolStripItemCollection Find method.
=> Add tests for ToolStripItemCollection Find method

src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
- Use generic lists in FileDialog.
=> Use generic lists in FileDialog

eng/Version.Details.xml, eng/Versions.props, global.json
Also run a general update
CPD strict means the following:
```
<Dependency Name="Microsoft.Win32.Registry.AccessControl" Version="5.0.0-preview.8.20361.2" CoherentParentDependency="Microsoft.Private.Winforms">
<Uri>https://github.com/dotnet/runtime</Uri>
<Sha>f37dd6fc8595e130909dcb3085a56342d04aa20c</Sha>
</Dependency>
```
This is from windowdesktop. In this case, Maestro will look up to find a direct dependency on Microsoft.Win32.Registry.AccessControl in runtime@f37dd6fc8595e130909dcb3085a56342d04aa20c.
If none exists, it fails. This contrasts to the current CPD algorithm which will attempt to find the newest Microsoft.Win32.Registry.AccessControl in any build within the graph below runtime@f37dd6fc8595e130909dcb3085a56342d04aa20c.
This is prone to error in some servicing cases, is slow, …
=> Add dependencies required for CPD strict

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/Company.WinFormsApplication1.csproj.user
Porting fix for bug #3510 to 3.1 servicing release.
Master branch commit: #3527 
Changes:
1. Added *.user file so as to add Form subtype.
2. By default template engine removes *.user files.
To override it, I have added sources in template.json to remove *.user from "exclude"
Verified that:
1. .user file gets dropped on creating new project from dotnet CLI
2. It works when project gets created from VS. Now Form1.cs opens directly in designer
3. .user file has BOM (0xEF, 0xBB, 0xBF) characters in the beginning and the files have UTF 8 encoding
4. On adding a new Form to an existing project, the new Form opens directly in designer
=> [Port to 3.1 servicing]: Adding Form subtype in WinForms C# template

src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb, src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Audio.vb, src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Network.vb, src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Interaction.vb, src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Logging/FileLogTraceListener.vb, src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/MyServices/ClipboardProxy.vb, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CommandSet.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ExceptionCollectionTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationServiceTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/Serialization/CodeDomSerializerExceptionTests.cs, src/System.Windows.Forms/src/System/Resources/ResXDataNode.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.PropertyBagStream.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataObject.OleConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MergePropertyDescriptor.cs, src/System.Windows.Forms/tests/TestUtilities/BinarySerialization.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageListTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Layout/TableLayoutSettingsTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewSubItemTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/OwnerDrawPropertyBagTests.cs
Some types and members were recently made obsolete in dotnet/runtime, and dependency flow into dotnet/winforms is broken because of it.
To keep darc running smoothly, I've suppressed these warnings individually.
I've built locally from both command line and VS, and all errors are now gone.
=> Suppress warnings about obsolete types and members

src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.PBST.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.PFTASKDIALOGCALLBACK.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TASKDIALOGCONFIG.IconUnion.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TASKDIALOGCONFIG.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TASKDIALOG_BUTTON.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TDCBF.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TDE.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TDF.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TDIE.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TDM.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TDN.cs, src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TaskDialogIndirect.cs
Remove now unnecessary NRT directives that were added by #1133, since #3451 enabled nullable reference types for `System.Windows.Forms.Primitives` globally in the project file.
- Remove remaining `#nullable enable` directives in `System.Windows.Forms.Primitives` files.
- None
- No
-
- Changed one of the field types in `PFTASKDIALOGCALLBACK` to `object?` and verified that the compiler doesn't raise `CS8632`.
- 
Version:   5.0.100-rc.1.20367.2
Commit:    0dd3ff77c7
Base Path:   C:\Program Files\dotnet\sdk\5.0.100-rc.1.20367.2\
Version: 5.0.0-preview.8.20361.2
Commit:  f37dd6fc85 …
=> Remove unnecessary NRT directives from TaskDialog interop files

src/System.Windows.Forms/src/System/Windows/Forms/ImageList.NativeImageList.cs, src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Fixes #3358
Disable sharing ImageList handles because they are implemented incorrectly and can double-free handles, which will crash if the handle was reused already (#3358). Instead of sharing ImageLists this PR creates an explicit duplicate when assigning an ImageList to the native control, and destroys the previous instance. This guarantees the handle used by the native control is always unique and can be safely destroyed. To avoid leaks all ImageLists are removed when the handle is destroyed.
#3531 is tracking proper implementation of ImageList ownership
For TreeViews the StateImageList is never shareable and it had similar bugs, so the correct solution is also to create unique handles and destroy them. Part of the logic already was there, but it was too eager and destroyed ImageLists …
=> Workaround for bad ImageList ownership management

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/DeviceContextExtensions.cs, src/System.Windows.Forms/src/System/Windows/Forms/CheckedListBox.cs
Didn't actually set a color for the GDI case. Add an assert to FillRectangle to try and flush out this sort of mistake earlier.
Fixes #3628
=> Set the color when drawing text in CheckedListBox.

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.GetKeyboardState.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.SetKeyboardState.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/SendKeys.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Properties.cs
There were significantly more allocations in `SendKeys` than were necessary. This cuts them down by:
1. Using structs instead of classes
2. Using a generic queue
3. Using stack allocated space to get key state
We hit the key state in `Control` as well. Also cleaned up the tracking of modifier keys a bit.
The first commit is just style cleanup. The second is the functional change.
@KlausLoeffelmann
=> Improve SendKeys performance

src/System.Windows.Forms.Primitives/src/Interop/Comdlg32/Interop.PRINTPAGERANGE.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintDialog.cs
- Move PRINTPAGERANGE to Interop Comdlg32.
=> Move PRINTPAGERANGE to Interop Comdlg32

src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.Rectangle.cs, src/System.Windows.Forms/src/System/Windows/Forms/GroupBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextRenderer.cs
Grid entry text was being shifted out of the control window as we were applying the Graphics transform manually when the centralized code now does this for us.
This change no longer double applies and changes the code to use TextRenderer, removing the local HFONT caching.
Also fix GroupBox to use FillRect instead of Rectangle. Remove an uncalled overload for Rectangle.
Fixes #3580
=> Don't double apply Graphics transform

src/System.Windows.Forms/src/System/Windows/Forms/TaskDialog.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TaskDialogTests.cs
Contributes to dotnet/winforms#3222
- The `TaskDialog.Handle` getter will now throw an `InvalidOperationException` when `Control.CheckForIllegalCrossThreadCalls` is `true`, the task dialog is currently being shown, and the current thread is not the one which created the handle.
This is a "best-effort" mechanism to make developers aware of incorrect thread usage, as the task dialog implementation is not thread-safe. (However, because the code is not thread-safe, you cannot rely on the exception being thrown.)
- Because the `TaskDialog.Handle` property is also used internally by code that updates the dialog while it is shown, such code may also throw the `InvalidOperationException` in such cases, for example:
- `TaskDialogPage.Text.set`
- `TaskDialogButton.PerformClick()`
- …
=> Check for illegal cross-thread calls in the TaskDialog

Winforms.sln, eng/configure-toolset.ps1, global.json, src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.IOleClientSite.cs, src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.IOleControlSite.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.OleInterfaces.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.AxSourcingSite.cs, src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserSiteBase.cs, src/System.Windows.Forms/tests/InteropTests/InteropTestBase.cs, src/System.Windows.Forms/tests/InteropTests/NativeTests/CMakeLists.txt, src/System.Windows.Forms/tests/InteropTests/NativeTests/NativeTests.proj, src/System.Windows.Forms/tests/InteropTests/NativeTests/WebBrowserSiteBaseInteropTests.cpp, src/System.Windows.Forms/tests/InteropTests/NativeTests/testhelpers.h, src/System.Windows.Forms/tests/InteropTests/System.Windows.Forms.Interop.Tests.csproj, src/System.Windows.Forms/tests/InteropTests/WebBrowserSiteBaseInteropTests.cs
- Add C++ interop tests for WebBrowserSiteBase
@JeremyKuhne @RussKie @zsd4yr
=> Add initial interop testing framework

src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.GetBkColor.cs, src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.GetBrushOrgEx.cs, src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.GetTextAlign.cs, src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.GetTextColor.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.EXTLOGFONTW.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.LOGFONTW.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.PANOSE.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/SpanHelpers.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/DeviceContextState.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/HdcDeviceContextAdapter.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/EMRENUMRECORD.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/EMREXTCREATEFONTINDIRECTW.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/EMREXTTEXTOUTW.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/EMRTEXT.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/EmfRecord.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/EmfScope.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextRenderer.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextRendererTests.cs
`(Color)default` is not the same as `Color.Empty`. `Color.Empty` is used to determine that we should not be writing opaque. Adds regression test.
This change starts introducing another layer on the metafile parsing to allow accumulating state. It also adds additional records.
=> Fix rendering text with a transparent background

src/System.Windows.Forms/src/System/Windows/Forms/Internal/DrawingEventArgs.cs
If we try to create a `Graphics` object from it we'll get an `OutOfMemoryException` which is not actually what is happening- GDI+ just reports that whenever you don't pass a valid HDC. Throwing when we see this so we don't chase down the wrong rabbit hole.
=> Throw if we're given a null HDC in a message.

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripDropDownTests.cs
Fixes #2058
- Fix porting regression. Context menus for NotifyIcon are allowed to cover the taskbar, the corresponding property stored the setting but did not read it out.
- Allow context menus for taskbar icons to cover the taskbar (instead of getting shifted off the taskbar)
- Yes
- Minimal. The property was internal and only set by `NotifyIcon` caller.
- context menu for NotifyIcon is moved off the taskbar and does not appear where the user clicked
- context menu for NotifyIcon is allowed to cover the taskbar, depending where the user clicked (same as Desktop Framework)
- added unit test to verify the property returns the value stored in it (test fails without fix)
- manual testing to verify the reported behavior was fixed (cannot automate this test as it requires nontrivial user …
=> Fix porting regression in ToolStripDropDown

src/System.Windows.Forms/tests/AccessibilityTests/StripControls.Designer.cs
Added accessible name property to ToolStrip combo box in the test app
Fixes #3663
=> Fixes #3663

src/System.Windows.Forms/tests/AccessibilityTests/PrintingTesting.Designer.cs
Don't allow keyboard focus move to the PrintPreviewControl because it's not editable.
Fixes #3660
=> Fixes #3660

src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.DataGridViewTextBoxEditingControlAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.cs
- Extract `DataGridViewTextBoxEditingControlAccessibleObject` and nest under `DataGridViewTextBoxEditingControl`
- Clean `DataGridViewTextBoxEditingControlAccessibleObject`
- Apply NRT
=> Extract and clean `DataGridViewTextBoxEditingControlAccessibleObject` up

src/System.Windows.Forms/src/System/Windows/Forms/DataObject.DataStore.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataObject.OleConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs
- Use generic hash sets in DataObject.
=> Use generic hash sets in DataObject

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/Company.WinFormsApplication3x1.csproj, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/Company.WinFormsApplication3x1.vbproj, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-CSharp/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-CSharp/Company.ControlLibrary3x1.csproj, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-VisualBasic/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-VisualBasic/Company.ControlLibrary1.vbproj, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-VisualBasic/Company.ControlLibrary3x1.vbproj, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-CSharp/Company.ClassLibrary3x1.csproj, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-VisualBasic/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsLibrary-VisualBasic/Company.ClassLibrary3x1.vbproj
Works for
```
dotnet new wpf -n wpf1 -f netcoreapp3.1
dotnet new wpf -n wpf2
dotnet new wpf -n wpf3 -f netcoreapp3.1 --target-framework-override net461
dotnet new wpf -n wpf3 -f net5.0 --target-framework-override net6.0
dotnet new wpf -n wpf4 -f net5.0 --target-framework-override net6.0
```
-----------------------
Now I have updated all existing templates. I tested with a script running the combination of all templates, c#/VB, net5.0/netcoreapp3.0/netcoreapp3.1/override with net46. And I sampled some test case manually in VS too. It is not likely to have any mistake slip through.
=> Update to net5.0 template with backcompact

src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb, src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourceCodeDomSerializer.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlCodeDomSerializer.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
Contributes to #3546
- Replace Dev10 with .NET Framework 4.0 in comments.
=> Replace Dev10 with .NET Framework 4.0 in comments

src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/Person.cs, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/TestDataSources.cs, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests/System.Windows.Forms.IntegrationTests.csproj, src/System.Windows.Forms/tests/IntegrationTests/WinFormsControlsClassicTests/WinFormsControlsClassicTests.csproj, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxes.Designer.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxes.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/WinformsControlsTest.csproj, src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
This is a regression from .NET Framework version 4.7.2. AccessibleObject.Name property for data-driven ComboBox items was broken because it was invoking ToString method instead of reading content of property that is named in DisplayMember databinding property.
Fixes #3584
use method that accesses DisplayMember property
* User of accessible technologies does not have access to values of combo box items, when these items are data-bound.
* Automation tests that rely on UIA accessible name would not work
- Yes, from  .NET Framework 4.7.2
Low - we now use an existing method that is used to populate combobox drop down UI 
PR in Core 5.0: https://github.com/dotnet/winforms/issues/3549
Fix is a port from the .NET Framework and is cherry-picked from Core 5.0:
git cherry-pick …
=> [Port to 3.1 servicing] Fix regression in accessible name for data-bound combo box items

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/ClientUtils.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
And simplify a little
Remaining question: we should move this out of ClientUtils -where to?
=> Convert GetWordBoundaryStart to take string not char[]

src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.GETTEXTEX.cs, src/System.Windows.Forms.Primitives/src/Interop/Richedit/Interop.GT.cs, src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.EM.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
Resolves #3399
In .NET 4.7 instead of using the old RichEdit2.0/3.0 a new version of RichEdit4.1 was used, which no longer allows to provide hidden text via the existing mechanics of EM_STREAMOUT.
However in .NET Desktop allowed switching to the old RichEdit control via configuration quirks.
In .NET Core 3.0 we have deprecated the old control, which essentially
breaks certain scenarios.
Restore the ability to read hidden text.
- Customers relying on RichTextBox's behaviour to retrieve hidden text can now migrate to .NET 5.0
- Yes
- Minimal
- Manual
- Unit tests
Co-authored-by: mavnorthwind <mavnorthwind@users.noreply.github.com>
=> fix: RTB retrieve hidden text

src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScrollBarTests.cs
Just fixed string interpolation in ScrollBar.
=> Fix string interpolation in ScrollBar

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripComboBox.cs
Fixes #3661
- Fixed invalid condition for right arrow on keyboard.
- No
- No
- Minimal
- CTI 
- NET Core 5.0.100-rc.1.20411.10
=> Fixing issue when keyboard focus cannot use alt+right arrow to leave ComboBox/TextBox clockwise

src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.StockObject.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/EmfRecord.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/RecordTypes/EMRRECTRECORD.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/RectangleValidator.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/Validate.cs, src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/Gdi32/GetStockObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ButtonRenderingTests.cs
Stock objects have a different define in metafile records. Correct values for API usage.
Add rectangle validation to the EMF validator and add regression tests for button and the Interop definitions.
Fixes #3770
- Flat style buttons and other controls that use a null/hollow brush don't render correctly.
- Yes
- Low
=> Fix getting stock objects

src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.StockObject.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/EmfRecord.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/RecordTypes/EMRRECTRECORD.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/RectangleValidator.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/Validate.cs, src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/Gdi32/GetStockObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ButtonRenderingTests.cs
Stock objects have a different define in metafile records. Correct values for API usage.
Add rectangle validation to the EMF validator and add regression tests for button and the Interop definitions.
Ported from https://github.com/dotnet/winforms/pull/3774 / https://github.com/dotnet/winforms/commit/6f4b818cdc3fd3a76492cfd1fb6947a3482635c9
- Flat style buttons and other controls that use a null/hollow brush don't render correctly.
- Yes
- Low
=> Fix getting stock objects (#3774)

Directory.Build.targets
When runtime builds stable, the runtime framework version and targeting pack versions will no longer be the same.
Microsoft.NETCore.App's version is non-shipping, and so should not be used for the RuntimeFrameworkVersion.
The targeting package version should be set based on the ref pack version, since it won't rev with the runtime.
=> Correctly set the targeting pack and runtime framework version

src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewDialog.PrintPreviewDialogToolStripButton.cs, src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewDialog.cs
Fixes #3598
- Added special control that doesn't remove focus when user clicks Page buttons on PrintPreviewDialog
- No
- No
- Minimal
- CTI 
- NET Core 5.0.100-rc.1.20411.10
=> Print preview dialog incorrect focus after pressing 'Enter' on any button

src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.DataGridViewCheckBoxCellAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellTests.cs
Fixes #3597
- Added logic for reading of state of the CheckBox by Narrator when user changes state of checkbox in DataGridViewCheckBoxColumn
- No
- No
- Minimal
- Unit tests 
- CTI
- NET Core 5.0.100-rc.1.20411.10
=> Correctly announce `DataGridViewCheckBoxColumn.CheckBox` state

src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ButtonRenderingTests.cs
GDI renders rectangle outlines different than GDI+ (System.Drawing). Adding the GDI code path to ControlPaint.DrawBorderSimple did not need the adjustment to the bounds rect.
Validated rendering to the pixel and wrote standalone tests to validate GDI+ behavior.
Fixes #3789
- Border rendering for some variants of buttons and checkboxes are off by one pixel. Sometimes this is very visible as it leaves a 1 pixel gap in the UI.
- Yes
- Low. Worst case is that we introduce a 1 pixel off problem somewhere else, but this is unlikely.
- Wrote direct GDI/GDI+ rectangle code to validate behavior
- Updated existing test to correct coordinates
=> Use proper size rectangle with GDI

src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ButtonRenderingTests.cs
Cherry-picked from https://github.com/dotnet/winforms/pull/3815's commit https://github.com/dotnet/winforms/commit/40c24e3f4e495cb4bd209132e815969859c65ebe
GDI renders rectangle outlines different than GDI+ (System.Drawing). Adding the GDI code path to ControlPaint.DrawBorderSimple did not need the adjustment to the bounds rect.
Validated rendering to the pixel and wrote standalone tests to validate GDI+ behavior.
- Border rendering for some variants of buttons and checkboxes are off by one pixel. Sometimes this is very visible as it leaves a 1 pixel gap in the UI.
- Yes
- Low. Worst case is that we introduce a 1 pixel off problem somewhere else, but this is unlikely.
- Wrote direct GDI/GDI+ rectangle code to validate behavior
- Updated existing test to correct coordinates
@Pilchie for …
=> Use proper size rectangle with GDI (#3815)

src/System.Windows.Forms/src/System/Windows/Forms/ListBox.AccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ItemAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBox.ListBoxItemAccessibleObjectTests.cs
Fixes #3706 
When reading AccessibleObject.Name from the ListBox item, use the helper API that is used to access test that the list box displays instead of the ToString method becasue that API takes into account data binding.
1. Accessibility tools users will not know what UI element they are working with.
2. Automation tools that are looking up UI elements by the accessible name will not find list box items
- Yes  - from Core 3.1 and .NET Framework
- low
manual and unit test
done
-
=> Read accessible name of a data bound ListBox from the DisplayMember of the data source

.github/CONTRIBUTING.md, .github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/feature_request.md, README.md, Winforms.sln, docs/testing.md, src/System.Windows.Forms/src/System/Windows/Forms/TaskDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/TaskDialogRadioButton.cs
This PR updates some links pointing to nowhere. The folder for most of the documentation files has been renamed from `Documentation` to `docs` and there are some links that were not updated. This PR fixes some of them.
- When opening a feature request, this link is in the issue template: `Read https://github.com/dotnet/winforms/blob/master/Documentation/issue-guide.md`, which points to 404.
- When fixing this, the user will more likely find and read the issue guide.
- No
- Some external documentation generators or script might map `Documentation` to a valid path. This would break in that case.
- Ctrl+F `Documentation` and check if its affected
=> Update some links to docs

src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
Fixes #3778
The default behaviour of EM_GETTEXTEX is to normalise line endings to '\r' (see: GT_DEFAULT, https://docs.microsoft.com/en-au/windows/win32/api/richedit/ns-richedit-gettextex#members),
whereas previously we would normalise to '\n'.
Setting GT.USECRLF flag we can only ask for '\r\n' line endings, but unable to ask for '\n'.
Unless GT.USECRLF was set, convert '\r' with '\n' to retain the original behaviour.
- The original behaviour from .NET Framework/.NET Core is retained
- Yes, introduced in https://github.com/dotnet/winforms/pull/3726
- Minimum
- Locally reverted https://github.com/dotnet/winforms/pull/3726
- Added unit tests to capture the original behaviour
- Restored https://github.com/dotnet/winforms/pull/3726
- Added the new fix to adhere to the original behaviour and …
=> Restore original RichTextBox.Text EoL

src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/DataGridView.DataGridViewEditingPanelAccessibleObjectTests.cs
1. Create application with DataGridView.
2. Add any default data to DataGridView.
3. Run application
4. Start to edit existing cell.
5. Select cell from new row and start to edit
6. Select existing row and start to edit.
- Add check that EditingControl is not null 
- Customers using accessibility tools won't get NRE when modifying a datagrid
- No
- Minimal
-  Manual testing
- .NET Core SDK 5.0.100-rc.1.20420.14
=> Fixing exception when switching between DataGridViewCell with active Narrator

src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs
Actually change the GridColor when set. Add a test for GridColor.
Fixes #3829
- Fix missing property set 
- Can't set the grid color without this change 
- Yes
- Very low
See #3829, grid was black.
- Add test for property
- Validate visually in WinForms app
- Examine GDI calls involved (Tests for the calls forthcoming, need to fill out the emf validation more. The records are a bit complicated as we're using GDI+ to draw the grid and it uses transforms and polylines to draw)
=> Change DataGridView.GridColor when set.

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
Under stress there's likely a race condition loading/unloading RichEdit20W control that leads to test runner crashes.
Disabling the test to unblock 5.0 release. The test will be reworked and fixed in 6.0 branch.
Relates to https://github.com/dotnet/winforms/issues/3867
None, test infra changes
/cc: @Pilchie
=> Disable `RichTextBox_Text_GetWithHandle_ReturnsExpected`

src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs
Actually change the GridColor when set. Add a test for GridColor.
Fixes #3829
- Fix missing property set 
- Can't set the grid color without this change 
- Yes
- Very low
See #3829, grid was black.
- Add test for property
- Validate visually in WinForms app
- Examine GDI calls involved (Tests for the calls forthcoming, need to fill out the emf validation more. The records are a bit complicated as we're using GDI+ to draw the grid and it uses transforms and polylines to draw)
cc: @Pilchie for RC2
=> Change DataGridView.GridColor when set. (#3869)

src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/TextOutValidator.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/Validate.cs, src/System.Windows.Forms/src/System/Windows/Forms/GroupBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextExtensions.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextRenderer.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextRendererTests.cs, src/System.Windows.Forms/tests/UnitTests/Text/FontMetrics.cs
Text padding got lost in the rendering refactor. Pushed the public type down to `TextExtensions` to avoid some of the obfuscation and added rendering and measurement tests for padding.
Fixes #3823
- Pass through padding options
- Add missing tests
- Without this you cannot change padding options
- Yes
- Low
- Manual testing in sample apps
- Add tests to validate rendering and measurement
=> Respect padding options when rendering text

src/System.Windows.Forms/src/System/Windows/Forms/ListBox.AccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ItemAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBox.ListBoxItemAccessibleObjectTests.cs
Fixes #3706 - when reading AccessibleObject.Name from the ListBox item, use the helper API that is used to access test that the list box displays instead of the ToString method becasue that API takes into account data binding.
This is a cherry pick of commit https://github.com/dotnet/winforms/pull/3831/commits/c4360bb27d221dbc1d72a3f177f7c3640f052548
=> Port from rc2 - fixed accessible name for data bound ListBoxes

src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/TextOutValidator.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/Validate.cs, src/System.Windows.Forms/src/System/Windows/Forms/GroupBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextExtensions.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextRenderer.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextRendererTests.cs, src/System.Windows.Forms/tests/UnitTests/Text/FontMetrics.cs
Text padding got lost in the rendering refactor. Pushed the public type down to `TextExtensions` to avoid some of the obfuscation and added rendering and measurement tests for padding.
Fixes #3823
- Pass through padding options
- Add missing tests
- Without this you cannot change padding options
- Yes
- Low
- Manual testing in sample apps
- Add tests to validate rendering and measurement
cc: @Pilchie for RC2
=> Respect padding options when rendering text (#3872)

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
Reset all DpiHelper statics when setting the DPI mode.
Fixes #3832
- Reset all DpiHelper state when setting DPI mode
- DeviceDpi doesn't dynamically update when not using a manifest
- Yes
- Low
- Manually ran repro project
- Walked through message handling and statics
=> Reset all DpiHelper statics when setting the DPI mode

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
Reset all DpiHelper statics when setting the DPI mode.
Fixes #3832
- Reset all DpiHelper state when setting DPI mode
- DeviceDpi doesn't dynamically update when not using a manifest
- Yes
- Low
- Manually ran repro project
- Walked through message handling and statics
cc: @Pilchie for RC2
=> Reset all DpiHelper statics when setting the DPI mode (#3881)

src/System.Windows.Forms/src/System/Windows/Forms/Internal/DrawingEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/PaintEventArgs.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PaintEventArgsTests.cs
Move the shared logic to a class from a struct to avoid working on a copy of the nested data.
Fixes #3910
- Change shared logic container from struct to class
- Without this, the Graphics object is always recreated when the args are created from an HDC
- Modifcations to the Graphics object are never retained
- Yes
- Low, changing to a class avoids copies
- Add specific test to make sure we're retaining the right instance on an args created from an HDC
=> Fix PaintEventArgs Graphics property

src/System.Windows.Forms/src/System/Windows/Forms/Internal/DrawingEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/PaintEventArgs.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PaintEventArgsTests.cs
Move the shared logic to a class from a struct to avoid working on a copy of the nested data.
Fixes #3910
- Change shared logic container from struct to class
- Without this, the Graphics object is always recreated when the args are created from an HDC
- Modifcations to the Graphics object are never retained
- Yes
- Low, changing to a class avoids copies
- Add specific test to make sure we're retaining the right instance on an args created from an HDC
=> Fix PaintEventArgs Graphics property (#3913)

src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowConverter.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowConverterTests.cs
Resolves #3932
- Correct the typo in `DataGridViewRowConverter` that led to CodeDom serialization to fail for `DataGridView`.
- `DataGridView` serialization is correctly emitted by the designer
- Yes
- Minimal
- 
- 
-
=> Correct regression introduced in #659

src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.cs, src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs, src/System.Windows.Forms/tests/UnitTests/NumericUpDownTests.cs
GDI and GDI+ don't end their lines and rectangles on the same pixel. Lines end on the prior pixel and rectangles draw the right and bottom one pixel over. This wasn't caught at first as the color behind the control just happened to match the default on first render.
- Fix the GDI coordinates to match the GDI+ rendering
- Remove the GDI+ fork as it is impossible to set a transparent background color for NumericUpDown
- Add initial rendering tests
Validated with A/B testing between 3.1 and 5.0 with a loud background color. Validated with and without visual styles, enabled and disabled, and with different border styles.
Fixes #3931
- Correct GDI rendering for NumericUpDown
- Remove unhittable GDI+ branches
- Without this you get whatever random garbage is behind the form around the edges of …
=> Fix rendering of NumericUpDown control

src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.DataGridViewTextBoxEditingControlAccessibleObject.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTextBoxEditingControl.DataGridViewTextBoxEditingControlAccessibleObjectTests.cs
Fixes #2786
Original Bug: [1159872](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1159872)
Based on PR #2701
- Enable **Text pattern** support for `DataGridViewTextBoxEditingControlAccessibleObject`
- Visually impaired users will be able to read and interact with the text content of a DataGridViewTextBoxCell
- No
- Mininmal
- Narrator does not announce the text navigation and selection of a DataGridViewTextBoxCell
- Narrator announces the text content of a DataGridViewTextBoxCell (navigation, selection)
- CTI
- Unit tests
- Using Narrator and Inspect
- .Net 5.0 Version: 5.0.0-rc.1.20431.5
- Microsoft Windows [Version 10.0.19041.450]
=> Adding Text pattern to DataGridViewTextBoxCell

src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/EmfRecord.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/EmfScope.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/RecordTypes/EMRPOLYPOLY16.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/PolyPoly16Validator.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/PolyPolygon16Validator.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/PolyPolyline16Validator.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/Validate.cs, src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlPaintTests.Rendering.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlPaintTests.cs
Fixes #3944
- Move return statement so it doesn't double draw
- Add regression tests
- Move return statement
- Dotted/dashed line rendering looks terrible, with no workaround
- Yes
- Very low
Bad on left, good on right.
- Add detailed rendering tests
- Manually validate output between 3.1 and 5.0
=> Fix ControlPaint.DrawBorder dashed/dotted drawing

src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.cs, src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs, src/System.Windows.Forms/tests/UnitTests/NumericUpDownTests.cs
GDI and GDI+ don't end their lines and rectangles on the same pixel. Lines end on the prior pixel and rectangles draw the right and bottom one pixel over. This wasn't caught at first as the color behind the control just happened to match the default on first render.
- Fix the GDI coordinates to match the GDI+ rendering
- Remove the GDI+ fork as it is impossible to set a transparent background color for NumericUpDown
- Add initial rendering tests
Validated with A/B testing between 3.1 and 5.0 with a loud background color. Validated with and without visual styles, enabled and disabled, and with different border styles.
Fixes #3931
- Correct GDI rendering for NumericUpDown
- Remove unhittable GDI+ branches
- Without this you get whatever random garbage is behind the form around the edges of …
=> Fix rendering of NumericUpDown control (#3939)

src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.cs, src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs, src/System.Windows.Forms/tests/UnitTests/NumericUpDownTests.cs
=> Revert "Fix rendering of NumericUpDown control (#3939)"

src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
Fixes #3945
The DrawBorder overload that takes individual side parameters needed to adjust line ends when drawing in GDI.
Manually validated output at different widths and transparencies between 3.1 and 5.0. Will follow up with automated regression tests in a separate PR.
- Adjust line ends when drawing with GDI
- ControlPaint.DrawBorder leaves a gap in the border- there is no workaround
- Customer controls built on this API render incorrectly
- Yes
- Very low
Good is on the left, bad on the right. The dotted/dashed are ok as that always draws with GDI+.
- Ran pixel level comparison between 3.1 and 5.0 with all options and with/without transparency
(Automated tests will be in a follup-up PR- these require several hundred lines of code.)
=> Fix ControlPaint.DrawBorder rendering

src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs
End point needed adjusted for GDI to match GDI+
Fixes #3953
- Adjust the end points so the grip draws without a gap
- Control.DrawSizeGrip draws with a new gap
- Forms without visual styles enabled draw the size grip with a gap
- Yes
- Very low
Good is on left, bad is on right: (while the right may look more appealing out of context making it "centered" would require all users to upgrade their code to get their existing behavior)
- Manually verified pixel-by-pixel
=> Fix DrawSizeGrip

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewEdit.GridViewEditAccessibleObject.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridViewEdit.GridViewEditAccessibleObjectTests.cs
Fixes #3683
Original Bug: [1159883](https://dev.azure.com/devdiv/DevDiv/_workitems/edit/1159883)
Based on PR #2701
- Enable **Text pattern** support for `GridViewEditAccessibleObject`
- Visually impaired users will be able to read and interact with the text content of a ToolStripTextBox
- No
- Minimal
- Narrator does not announce the text navigation and selection of a PropertyGridView.GridViewEdit
- Narrator announces the text content of a PropertyGridView.GridViewEdit (navigation, selection)
- CTI
- Unit tests
- Using Narrator and Inspect
- Net 5.0 Version: 5.0.0-rc.1.20431.5
- Microsoft Windows [Version 10.0.19041.450]
=> Adding Text pattern to PropertyGridView.GridViewEdit

src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/EmfScope.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/FontFaceNameValidator.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/State.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/TextOutValidator.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/Validate.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DataGridViewHeaders.Designer.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DataGridViewHeaders.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.Rendering.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextRendererTests.cs
Fixes #3033
- Do not override user-configured font styles in the `DataGridView` whenever ambient (e.g. form's) font changes. 
This scenario is likely to occur when users migrate their applications from .NET Framework to .NET Core/.NET and wish to retain the original default font. 
Whilst the behaviour goes all the way back to .NET Framework, it becomes a significant migration issue for projects that want to keep the original default font (that was changed in #656).
- User will be able to migrate existing applications while retaining original default font (for .NET Framework).
- Not direct, however a side effect of Default Font change in https://github.com/dotnet/winforms/pull/656
- Small
- manual (via WinformsControlsTest project)
- unit tests
=> Do not reset user fonts in DataGridView

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/.template.config/template.json, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/ApplicationEvents.vb, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/Company.WinFormsApplication1.vbproj, pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/Program.vb
This fixes #3893, and also is needed to make https://github.com/dotnet/templates/pull/375 work.
Enables the following experiences for Visual Basic WinForms templates:
* Creates a new VB WinForms App V3.1 from the CLI. (Default: `dotnet new winforms --language VB` )
* Creates a new VB WinForms App net5.0 ( `--Framework net5.0` )
* Creates a new VB WinForms App net5.0 WITH Application Framework support ( `--Framework net5.0 --use-app-framework=true` )
* New: Works together with the newly activated VS VB template (which have been disabled before).
Will enable the Customer to use the Visual Basic Application Framework for Windows Forms Apps for >=net 5.0.
No.
Low. Only affecting VB templates.
Manual testing of the new templates.
=> Prepare CLI VB template for vs16.8 P4 VS templates.

src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb, src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Audio.vb, src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Network.vb, src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Interaction.vb, src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Logging/FileLogTraceListener.vb, src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/MyServices/ClipboardProxy.vb, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ExceptionCollectionTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationServiceTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/Serialization/CodeDomSerializerExceptionTests.cs, src/System.Windows.Forms/src/System/Resources/ResXDataNode.cs, src/System.Windows.Forms/src/System/Windows/Forms/AxHost.PropertyBagStream.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataObject.OleConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MergePropertyDescriptor.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageListTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Layout/TableLayoutSettingsTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewSubItemTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/OwnerDrawPropertyBagTests.cs
Remove security no-ops in VB code
Add SYSLIB0011 to quiet our other analyzers for binary formatter
=> Cut down warnings in VS

src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/EmfRecord.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/EmfScope.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/RecordTypes/EMRPOLYPOLY16.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/PolyPoly16Validator.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/PolyPolygon16Validator.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/PolyPolyline16Validator.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/Validate.cs, src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs, src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.cs, src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs, src/System.Windows.Forms/tests/UnitTests/NumericUpDownTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlPaintTests.Rendering.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlPaintTests.cs
Proposing porting the changes that fix the class of off by one bugs for the end point of lines that were switched from GDI+ to GDI (for performance and memory usage). Note that the majority of the code in these commits are test code.
Fixes #3953
Fixes #3945 
Fixes #3931
Fixes #3944
- Adjust end points one over to render correctly
- Remove unreachable code
- Move misplaced return statement
- Control vendors controls render incorrectly as they build on our helper code
- Customer UI has gaps in numerous controls and strange artifacts in the NumericUpDown and DomainUpDown controls.
- Yes
- Very low
UpDownControl example, before and after:
Good grab handle is on left, bad is on right: (while the right may look more appealing out of context making it "centered" would require all users to …
=> Fix ControlPaint regressions

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/DeviceContextHdcScope.cs, src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/DeviceContextHdcScopeTests.cs
Logic was off for some of the cases where we set up an `HDC` for drawing and we weren't applying clipping or translation transforms when we needed to. For the `ToolStrip` this causes the background of the parent to fill over the `ToolStrip` background.
This has implications for most rendering where a clip or transform is applied.
Add tests for the `HDC` handling struct to validate application of `Graphics` properties.
Fixes #3975
- Fix logic in `DeviceContextHDCScope`
- Add tests for property application
- Background color isn't visible in Toolstrip (possibly other internal controls, testing hasn't surfaced any others yet)
- Customer or control vendor's controls that utilize clipping or origin transforms may not render correctly if they utilize ControlPaint or base class rendering
- Yes
- …
=> Apply clipping and translation transforms correctly

src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObject.cs
Fixes #3957
- Updating logic for scrolling to item. Added calling of EnsureVisible method that scrolled to required item
Before fixing, "ListViewItem.ListViewItemAccessibleObject.ScrollIntoView" method was available for user, but this method did not work. If user or some program (Inspector, Accessibility Insights) tries to execute this then ListView will not scroll and the user will not see the required item in visible area. As result this method is useless.
After fixing, this method starts to work correctly and user or program have ability to see required element after calling of "ScrollIntoView" method.
- No
- Minimal
- Manually 
- NET Core 5.0.100-rc.1.20420.14
=> Fixing "ListViewItem.ListViewItemAccessibleObject.ScrollIntoView" method

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/DeviceContextHdcScope.cs, src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/DeviceContextHdcScopeTests.cs
Logic was off for some of the cases where we set up an `HDC` for drawing and we weren't applying clipping or translation transforms when we needed to. For the `ToolStrip` this causes the background of the parent to fill over the `ToolStrip` background.
This has implications for most rendering where a clip or transform is applied.
Add tests for the `HDC` handling struct to validate application of `Graphics` properties.
Fixes #3975
- Fix logic in `DeviceContextHDCScope`
- Add tests for property application
- Background color isn't visible in Toolstrip (possibly other internal controls, testing hasn't surfaced any others yet)
- Customer or control vendor's controls that utilize clipping or origin transforms may not render correctly if they utilize ControlPaint or base class rendering
- Yes
- …
=> Apply clipping and translation transforms correctly (#3990)

eng/packageContent.targets, global.json
Fixes #3998
There are two main changes going on in this PR:
1. Consume the new dotnet-api-docs_net5.0 blob, which has already been uploaded to Azure storage
2. Make our package ALWAYS use the xml from this blob instead of our locally generated xml.
- If we build a non-facade assembly, and the blob does NOT contain xml for this assembly, this is an error
=> use new intellisense blob, change package composition logic

src/System.Windows.Forms.Primitives/tests/TestUtilities/DeviceContextState.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/EmfScope.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/RecordTypes/EMREXTSELECTCLIPRGN.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/BitBltValidator.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/ClippingValidator.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/State.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/Validate.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.Rendering.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs
Adds basic clipping support to the EMF validation system and a validation test for the background rendering of ToolStrip.
=> Add regression test for ToolStrip

eng/packageContent.targets, start-vs.cmd
Relates to #3998
- #3998 has regressed VS experience due to changed packageContent.targets, that no longer could resolve `$(IntellisenseXml)` variable. This prevented VS from resolving tooling and dependencies.
To fix this move all properties within `GetPackageContent` target.
- Also run `restore.cmd` before launching VS. This is required to ensure the intellisense bundle, as well as all required SDK and tooling are downloaded.
This streamlined the DevEx.
- None, infra changes
- Cleaned repo `git clean -xfd`
- Launched VS via `start-vs.cmd` to record the issue
- Run `restore.cmd` to observe the intellisense bundle downloaded, restart VS and still observe failures to build
- Correct packageContent.targets, restart VS via the script and build the solution
- Also run `build -pack` from cli …
=> Fix VS experience

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs, src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.cs, src/System.Windows.Forms.Design/tests/UnitTests/ControlDesignerTests.cs, src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ComponentDesignerTests.cs
- Add usings for disposable objects
- Make necessary changes to mocks now that we're disposing
- Update ControlDesigner to not throw when getting WM_PAINT
=> Clean up Control/ComponentDesigner tests

src/System.Windows.Forms/tests/UnitTests/VScrollBar.VScrollBarAccessibleObjectTests.cs
Fixes #3856
- Skip the test until .Net 6.0
- No
- No
- Minimal
- Unit testing
- .Net Version: 5.0.100-rc.2.20473.8
- Microsoft Windows [Version 10.0.19041.508]
=> Skip VScrollBarAccessibleObject_Ctor_Default to avoid intermittent CI build fails

src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
- Unlike [WM_DPICHANGED message](https://docs.microsoft.com/en-us/windows/win32/hidpi/wm-dpichanged#parameters), [WM_GETDPISCALEDSIZE message](https://docs.microsoft.com/en-us/windows/win32/hidpi/wm-getdpiscaledsize#parameters) only contains the new DPI value, not X- and Y-axis values. So the assert is being incorrectly triggered in Debug builds when DPI changes.
=> Remove incorrect assert

src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListVIew.ListViewAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Fixes #3962
- implemented using SelectedIndices instead of SelectedItems when getting Accessible Objects, because SelectedIndices property is available in any mode (virtual and default);
- added a check for methods from ListViewGroup that the ListView is not in virtual mode, since ListViewGroups are not supported for virtual mode;
- replaced "groups.Count > 0" condition on "GroupsEnabled" in logic for navigation on ListView by keyboard. Together with the "groups.Count > 0" condition, it also checks that Groups is displayed and ListView is in default (not virtual) mode;
- updated logic for "ExpandCollapseState" property ;
- added the condition that if a ListViewItem is located in a ListViewGroup and this ListViewGroup is collapsed we return empty rectangle otherwise we call old logic for …
=> Fix ListView is in virtual mode

src/System.Windows.Forms/src/PublicAPI.Unshipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Fixes #4030
- added calling of "RaiseAutomationEvent" method to "OnGotFocus" method for ListViewItem that had focus. This call returns the Narrator focus (blue rectangle) back to the element;
- added unit tests
Narrator focus doesn't switches between ListView when user presses Tab button:
After fixing, Narrator focus works correctly:
- Yes
- Minimal
- Manually
-  Unit tests
=> Fixing issue that Narrator cannot focus on ListView second time

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/readme.md
This PR fixes broken link in README.md for "Windows Forms Projects Templates" . 
Currently, the README.md has broken link in the link to template check installation:
- only update the link 
- 
- 
- no impact
- 
- No
- No risk, as this PR is not changing codes at all
- 
- 
- 
-
=> Fix broken link in README.md for Windows Forms Projects Templates

src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObject.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObjectTests.cs
- Fixes #4029
- Relates to PR #3963 and PR #3224
- Implement Toggle pattern for ListViewItemAccessibleObject if CheckBoxes is true
- Add on/off Narrator announcement for ListView items if CheckBoxes is true
- Now a user can hear if a ListView item is checked(on) or unchecked(off) using Narrator
- Yes
- Minimal
- Unit tests
- using Inspect and Narrator
- .Net Version: 5.0.0-rc.2.20472.5
- Microsoft Windows [Version 10.0.19041.508]
=> Adding Toggle pattern support for ListView items with checkboxes

src/System.Windows.Forms.Primitives/src/Interop/User32/Interop.BeginPaintScope.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/BackgroundModeValidator.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/State.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextRenderer.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MultipleControls.Designer.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MultipleControls.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextRendererTests.cs, src/System.Windows.Forms/tests/UnitTests/TextBoxTests.Rendering.cs, src/System.Windows.Forms/tests/UnitTests/TextBoxTests.cs
Whenever the `PlaceHolderText` property was set on a disabled textbox the placeholder text would be drawn with an opaque background.
Correct the text background transparency.
Fixes #3642.
Closes https://github.com/dotnet/winforms/pull/4008 as obsolete
Copied from https://github.com/dotnet/winforms/pull/4008
- manual
- tests
=> Correct TextBox.PlaceholderText font transparency

src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
Fixes #3897
- Raise `Text_TextChangedEvent` to Narrator shows the correct blue rectangle when typing new characters in Edit controls (should work as in Win32 RichTextBox)
- Do not raise the event for RichTextBox because Win32 provides unmanaged Text pattern for it
- A user orientates on the blue rectangle when entering text, and the current behavior can be confusing. This fix implements expected behavior for all text controls as in RichTextBox
- No
- Minimal
- Narrator doesn't show the blue rectangle correctly
- The correct blue rectangle
- CTI
- Using Narrator
- .Net 5.0 Version: 5.0.0-rc.1.20431.5
- Microsoft Windows [Version 10.0.19041.450]
=> Fixing the incorrect ScreenReader blue rectangle for a new character when typing (Text pattern area)

src/System.Windows.Forms.Primitives/src/Interop/UiaCore/Interop.IAccessibleEx.cs, src/System.Windows.Forms.Primitives/src/Properties/AssemblyInfo.cs, src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.EnumVariantObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/InternalAccessibleObject.cs, src/System.Windows.Forms/tests/InteropTests/AccessibleObjectTests.cs, src/System.Windows.Forms/tests/InteropTests/NativeTests/AccessibleObjectTests.cpp, src/System.Windows.Forms/tests/InteropTests/NativeTests/CMakeLists.txt, src/System.Windows.Forms/tests/InteropTests/NativeTests/testhelpers.h, src/System.Windows.Forms/tests/InteropTests/System.Windows.Forms.Interop.Tests.csproj
- Add AccessibleObject native tests
=> Add AccessibleObject native tests

src/System.Windows.Forms/src/System/Windows/Forms/ImageList.ImageCollection.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageList.ImageCollectionTests.cs
The original implementation incorrectly referenced elements in the collection.
It also double disposed elements in the collection that under stress could lead to instabilities.
And it was too verbose that made it harder to maintain the test.
Closes #3898
=> Correct and simplify `ImageCollection_Item_Get32bppColorDepth_Success`

src/System.Windows.Forms.Primitives/src/Interop/Shell32/Interop.SHILCreateFromPath.cs, src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/Shell32/ShellItemTests.cs
`FileDialog.InitialDirectory` and `FileDialog.CustomPlaces` do not work as paths we're incorrectly marshalled as ANSI.
Wrote an interop regression test and manually validated the two scenarios.
Fixes #3513
- Add the appropriate charset marshalling directive
- `InitialDirectory` and `CustomPlaces` do not work for `FileDialog`
- No customer workaround
- Yes
- Very low
- Wrote regression interop test
- Manually tested the file dialog
=> Fix initial directory and custom places in file dialogs

src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/EmfValidator.cs
=> Output the full EMF log whenever EMF validation fail.

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageList.ImageCollectionTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageListTests.cs
`ImageList` appears to behave badly under stress and in heavy multy-threaded environments, e.g. https://github.com/dotnet/winforms/issues/3898#issuecomment-708958624.
A shot from a hip in attempt to reduce concurrency.
Relates to #3898
=> Attempt to reduce concurrency while accessing `ImageList`

src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.SystemIAccessibleWrapper.cs, src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildDropDownButtonUiaProvider.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjectTests.cs
`IAccessible` wrapper class was being used in some places instead of the actual `IAccessible` object.
Based on #4114. Narrows diff and adds an additional regression test (`TestAccessibleObjectFromPoint`).
Fixes #4100.
- Use actual `IAccessible` object instead of wrapper class
- MSAA does not work, preventing any accessibility tools or UI automation based on MSAA (`IAccessible`) from working
- No known workaround
- Yes
- Possible we're missing other issues
- Moderately low outside of `IAccessible` usage, which is effectively unusable without this change.
- Automated tests
- Manual testing (see #4114)
- Walk through code paths to look for appropriate null checks
=> Fix MSAA accessibility

src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.SystemIAccessibleWrapper.cs, src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjectTests.cs
Port of #4117 - see for more details
* Fix MSAA accessibility
IAccessible wrapper class was being used in some places instead of the actual IAccessible object.
Based on #4114. Narrows diff and adds an additional regression test (`TestAccessibleObjectFromPoint`).
Fixes #4100.
* Add a second test and validate the varItem type.
=> Fix MSAA accessibility (#4117)

src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObjectTests.cs
Fixes #4032 
- Change the first subitem `ControlType` depending `ListView.LabelEdit` value. 
The first subitem has "text" ControlType if `LabelEdit` is false
and it has "edit" `ControlType` if `LabelEdit` is true.
The rest subitems always are "text". 
The implementation is consistent with .Net Framework 4.7.2 behavior.
- A user can see a correct `ControlType` value of the first subitem in a ListView if `ListView.LabelEdit` is true
- Yes (since #3224)
- Minimal
- The first subitem always has "text" `ControlType` (`ListView.LabelEdit` is true or false)
- The first subitem has the correct `ControlType` value:
1.`ListView.LabelEdit` is true - "edit"
2.`ListView.LabelEdit` is false - "text"
- CTI
- Unit tests
- Using Inspect
- .Net 6.0.100-alpha.1.20479.7
- Microsoft Windows …
=> Fixing the incorrect ControlType value of ListView subitem

src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.ACTCTXW.cs, src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.ACTCTX_FLAG.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/ThemingScope.cs, src/System.Windows.Forms/src/System.Windows.Forms.csproj, src/System.Windows.Forms/src/System/Windows/Forms/Application.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ApplicationTests.cs
Application.EnableVisualStyles gives Windows a manifest that enables the v6 common controls. We normally pull this manifest from a native resource in System.Windows.Forms.dll. In single file mode there is no "dll" to load from so this feature was not working as intended.
In the case where we can't get a Win32 HMODULE we now fall back to pulling the manifest from a managed resource and dumping it to the temp folder.
Make ACTCTXW blittable.
Fixes #4145
=> Fix Application.EnableVisualStyles in single file publishing mode

src/System.Windows.Forms/src/System/Windows/Forms/DomainUpDown.DomainUpDownAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/NumericUpDown.NumericUpDownAccessibleObject.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/DomainUpDownAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/NumericUpDownAccessibleObjectTests.cs
Fixes #4123
I tracked the current behavior to this PR: https://github.com/dotnet/winforms/pull/2382
- DomainUpDown/NumericUpdown should return true when queried for IsKeyboardFocusablePropertyId and they are visible and enabled. This is the behavior of the base class, so we shouldn't override it here.
- Yes.
- Someone might be relying on the current behavior.
- Added new tests.
=> DomainUpDown/NumericUpdown should be KeyboardFocusable

src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellTests.cs
Fixes #3925
- Added logic for restoring of parent during reattaching of EditingControlAccessibleObject. 
Fixed issue with hanging of Accessibility Insights during getting of data about textbox from DataGridViewTextBoxCell
- Yes
- Minimal
- Manually 
- Narrator
- Inspector
=> Fixing issue with getting of textbox from DataGridViewTextBoxCell  by Accessibility Insights

src/System.Windows.Forms/src/System/Windows/Forms/ImageIndexConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ImageList.Indexer.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItemStateImageIndexConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeViewImageIndexConverter.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItemStateImageIndexConverterTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/NoneExcludedImageIndexConverterTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewImageIndexConverterTests.cs
Resolves #4131
- `TreeViewImageIndexConverter` besides having a special meaning for -1 (which identifies the "default image index"), has a special meaning for -2 (which identifies "no image selected"). The latter is used whenever a `TreeNode` images is edited in a property grid.
During a code refactor in #3126 the meaning for -2 was lost, which broke the property grid experience.
- Refactor `TreeViewImageIndexConverter` and replace -1 with a const, add rudimentary tests.
- `TreeNode` can now have image indicies reset to "(none)".
- Yes, regressed in #3126
- Minimal
- manual
- unit tests
- CTI
=> Allow setting `TreeNode` image index to magic number `-2`

NuGet.config, azure-pipelines-richnav.yml, eng/ci.yml
I've altered two files:
1. Add a Rich Navigation specific build (which will appear as a new build pipeline), indexing on every push to master. This will allow you to use Rich Navigation in Visual Studio to enable cross-repository searches, serverless navigation at https://online.visualstudio.com/github/dotnet/msbuild, and integrated GitHub C# navigation once that is released (or, comment below if you want to be added to the preview now 😊).
1. Added the Rich Navigation task to your normal unit test CI. This has all the same benefits of ^, but also indexes your pull requests for a richer code review experience. This does come at the cost of increasing the time of your CI.
Based on your team's preference, only one of these changes is necessary.
[Docs …
=> Add Rich Navigation to CI, a new Rich Nav pipeline

src/System.Windows.Forms.Primitives/src/Interop/UiaCore/Interop.IRawElementProviderHwndOverride.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxAccessibleObject.cs
Fixes #3452
Issue is reproduced due to incorrect implementation of the "ComboBoxAccessibleObject.IRawElementProviderHwndOverride" method. After [adding of "ComImport" attribute](https://github.com/dotnet/winforms/commit/423b2bc5726b4109741f189e34e5f37f90140d01), the "ComboBoxAccessibleObject.IRawElementProviderHwndOverride" method started to be used, which lead to an issue. As fix for it, [we removed "ComImport"](https://github.com/dotnet/winforms/pull/3524) and stopped to using it.
I suggest to restore "ComImport" and remove overriding "ComboBoxAccessibleObject.IRawElementProviderHwndOverride" method.
No
- Yes
- Minimal 
- CTI 
- Manually
- Inspect
- Narrator
- .Net SDK 5.0.100-rc.2.20479.15
=> Narrator and Inspect become unresponsive inspecting `Combobox` control

src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.ACTCTXW.cs, src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.ACTCTX_FLAG.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/ThemingScope.cs, src/System.Windows.Forms/src/System.Windows.Forms.csproj, src/System.Windows.Forms/src/System/Windows/Forms/Application.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ApplicationTests.cs
Fixes #4145 
(cherry picked from commit 082cbf243b3c258e666f388825be9cfe2749ec48)
- `Application.EnableVisualStyles` gives Windows a manifest that enables the v6 common controls. We normally pull this manifest from a native resource in System.Windows.Forms.dll. In single file mode there is no "dll" to load from so this feature was not working as intended.
In the case where we can't get a Win32 HMODULE we now fall back to pulling the manifest from a managed resource and dumping it to the temp folder.
- Make `ACTCTXW` blittable.
- No, but makes the feature 'Self-contained + Produce Single File' virtually unsuitable for Windows Forms apps.
- Minimal
=> Fix Application.EnableVisualStyles in single file publishing mode  (servicing)

src/System.Windows.Forms/src/System/Windows/Forms/ImageIndexConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ImageList.Indexer.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItemStateImageIndexConverter.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeViewImageIndexConverter.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItemStateImageIndexConverterTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/NoneExcludedImageIndexConverterTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewImageIndexConverterTests.cs
Resolves #4131
- `TreeViewImageIndexConverter` besides having a special meaning for -1 (which identifies the "default image index"), has a special meaning for -2 (which identifies "no image selected"). The latter is used whenever a `TreeNode` images is edited in a property grid.
During a code refactor in #3126 the meaning for -2 was lost, which broke the property grid experience.
- Refactor `TreeViewImageIndexConverter` and replace -1 with a const, add rudimentary tests.
- `TreeNode` can now have image indicies reset to "(none)".
- Yes, regressed in #3126
- Minimal
- manual
- unit tests
- CTI
=> Allow setting `TreeNode` image index to magic number `-2` (servicing)

src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.EnumVariantObject.cs
Fixes #4120 (`LinkLabel` accessiblity tree)
Fixes #4121 (`CheckedListBox` accessiblity tree)
Fixes #4130 (MSAA `UpDown` controls)
Fixes #4172 (MSAA `CheckedListBox`)
Regression from 0c4d3cb9198d9246e85af732c8fa81c3f3e0d88c
- Cast `currentChild` from `uint` to `int` before using in Marshal.GetNativeVariantForObject
- A user can see a correct accessibility tree for controls that don't support the UIA provider using Inspect tool
- Yes (from 0c4d3cb9198d9246e85af732c8fa81c3f3e0d88c)
- Minimal
- `CheckedListBox` doesn't have internal items AccessibleObjects in the accessibility tree
- `CheckedListBox` has the correct accessibility tree with the internal items
- CTI
- Using Inspect tool
- .Net Version: 6.0.0-alpha.1.20513.9
- Microsoft Windows [Version 10.0.19042.572]
=> Fixing the argument type definition of Marshal.GetNativeVariantForObject method in EnumVariantObject

Directory.Build.targets, docs/testing-in-vs.md, eng/Version.Details.xml, eng/Versions.props, global.json
The Microsoft.NETCore.App package is being removed in https://github.com/dotnet/runtime/pull/38457/. The usage in WinForms can be replaced with the .NET Core Shared Framework VS insertion package, which has a nonshipping version number that matches a runtime.
=> Remove reference to the legacy Microsoft.NETCore.App package and use a different non-shipping package instead.

src/System.Windows.Forms/src/System/Windows/Forms/ImageList.ImageCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.Designer.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.cs
Fixes #4169
Changes in `ImageList` ownership model in #3601 means that very are now two  instances of imagelists - one instance is tracked by Windows Forms (i.e. managed) side, and another one tracked by the underlying Win32 (unmanaged) side. This was done due to an observed ownership disconnect between the managed and unmanaged code, that led to situations where the unmanaged code would effectively destroy and instance of an imagelist, which the managed code was oblivious to.
However with the above change changes to images in an imagelist on the managed side, i.e. a user adding or replacing an image in the imagelist, would not be reflected in the imagelist on the unmanaged side, and thus would not be reflected in the UI (which is drawn by the Win32).
The fix reuses the established …
=> Fix `ListView` no longer displays images

Winforms.sln, src/System.Windows.Forms.Primitives/tests/TestUtilities.Tests/Metafiles/Validators/RepeatValidatorTests.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities.Tests/System.Windows.Forms.Primitives.TestUtilities.Tests.csproj, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/Validators/RepeatValidator.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Properties/InternalsVisibleTo.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ButtonRenderingTests.cs
Button rendering with visual styles off is a set of the following operations:
```
[ENHMETAHEADER] Bounds: {0, -1, 74, 22 (LTRB)} Device Size: {Width=3840, Height=2160} Header Size: 108
[EMRCREATEBRUSHINDIRECT] Index: 1 Style: SOLID Color: [R=240, G=240, B=240] (COLOR_MENU, COLOR_BTNFACE, COLOR_MENUBAR)
[EMRSELECTOBJECT] Index: 1
[EMRBITBLT] Bounds: {2, 2, 72, 20 (LTRB)} Destination: {2, 2, 73, 21 (LTRB)} Rop: PATCOPY Source DC Color: [R=0, G=0, B=0] (COLOR_BACKGROUND, COLOR_MENUTEXT, COLOR_WINDOWTEXT, COLOR_CAPTIONTEXT, COLOR_BTNTEXT, COLOR_INACTIVECAPTIONTEXT, COLOR_INFOTEXT)
[EMRSELECTOBJECT] StockObject: WHITE_BRUSH
[EMRDELETEOBJECT] Index: 1
[EMRSETROP2] Mode: R2_COPYPEN
[EMRSETBKMODE] Mode: BKMODE_TRANSPARENT
[EMRCREATEPEN] Index: 1 Style: ENDCAP_ROUND Width: {X=1,Y=0} Color: [R=255, …
```
=> `RepeatValidator` must flag success once the counter has reached zero.

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripControlHost.ToolStripHostedControlAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripProgressBar.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/ToolStripControlHost.ToolStripHostedControlAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/ToolStripItemAccessibleObjectTests.cs
Fixes #3884
- updated implementation for IsOffscreen property. Now, in addition to the Placement of the ListViewItem, it also respects its size. In this way Inspector or Accessibility Insights see that element is not displayed and don't try to get its BoundingRectangle
- added unit tests;
Accessibility Insight show exception for Form containing a ToolStripStatusLabel with a zero size:
After fixing, Accessibility Insight doesn't show errors:
- No
- Minimal
- Unit tests
- Manually
- Inspector
- Accessibility Insight 
=> Fixing issue with null BoundingRectangle property of ToolStripStatusLabel

src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
Fixes #4243
- Added the "RaiseAutomationNotification" method to announce that a new row was added to the DataGridView
- Narrator will start to announce that a row has been added to the DataGridView
- No
- Minimal
- Manually
- Narrator
- .Net SDK 5.0.100-rc.2.20479.15
Alternatively, we can add the following changes to the application code (for example: [TestApplication.zip](https://github.com/dotnet/winforms/files/5545955/TestApplication.zip)):
```
{
....
this.dataGridView1.UserAddedRow += DataGridView1_UserAddedRow;
....
}
private void DataGridView1_UserAddedRow(object sender, DataGridViewRowEventArgs e)
{
(sender as DataGridView).AccessibilityObject.RaiseAutomationNotification(System.Windows.Forms.Automation.AutomationNotificationKind.ItemAdded …
```
=> Fix the issue with announcing that a new row was added to the DataGridView

src/System.Windows.Forms.Primitives/src/Interop/UiaCore/Interop.IRawElementProviderHwndOverride.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
(cherry picked from commit 2195c2c5687f695b1cdbf51db57af11eabe292d0)
Fixes #3452
Issue is reproduced due to incorrect implementation of the `ComboBoxAccessibleObject.IRawElementProviderHwndOverride` method. The presence of [`ComImport` attribute](https://github.com/dotnet/winforms/commit/423b2bc5726b4109741f189e34e5f37f90140d01) leads to the use of `ComboBoxAccessibleObject.IRawElementProviderHwndOverride`, which causes the issue. As fix for it, [we removed `ComImport`](https://github.com/dotnet/winforms/pull/3524) and stopped to using it.
However the issue is not with `ComImport` but the override of `ComboBoxAccessibleObject.IRawElementProviderHwndOverride` method.
- Customers will be able to use accessibility tools for forms that contain `ComboBox` controls.
- Yes
- Minimal 
- CTI 
- …
=> Narrator and Inspect become unresponsive inspecting `Combobox` control (servicing)

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripSettingsManagerTests.cs
- Add Save/Load test for ToolStripSettingsManager.
=> Add Save/Load test for ToolStripSettingsManager

src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.EnumVariantObject.cs
(cherry picked from commit 5af42bfbe9047fc744ff08db120129e87808481d)
Fixes #4120 (`LinkLabel` accessiblity tree)
Fixes #4121 (`CheckedListBox` accessiblity tree)
Fixes #4130 (MSAA `UpDown` controls)
Fixes #4172 (MSAA `CheckedListBox`)
Regression from 0c4d3cb9198d9246e85af732c8fa81c3f3e0d88c
- Cast `currentChild` from `uint` to `int` before using in Marshal.GetNativeVariantForObject
- A user can see a correct accessibility tree for controls that don't support the UIA provider using Inspect tool
- Yes (from 0c4d3cb9198d9246e85af732c8fa81c3f3e0d88c)
- Minimal
- `CheckedListBox` doesn't have internal items AccessibleObjects in the accessibility tree
- `CheckedListBox` has the correct accessibility tree with the internal items
- CTI
- Using Inspect tool
- .Net Version: …
=> Correct `EnumVariantObject` definition (servicing)

src/System.Windows.Forms/src/System/Windows/Forms/ImageList.ImageCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.Designer.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.cs
(cherry picked from commit d0608e72a356ad991f9c9d12518e29b43a1fb4f0)
Fixes #4169
Changes in `ImageList` ownership model in #3601 means that very are now two  instances of imagelists - one instance is tracked by Windows Forms (i.e. managed) side, and another one tracked by the underlying Win32 (unmanaged) side. This was done due to an observed ownership disconnect between the managed and unmanaged code, that led to situations where the unmanaged code would effectively destroy and instance of an imagelist, which the managed code was oblivious to.
However with the above change changes to images in an imagelist on the managed side, i.e. a user adding or replacing an image in the imagelist, would not be reflected in the imagelist on the unmanaged side, and thus would not be reflected in the UI …
=> Fix `ListView` no longer displays images (servicing)

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridToolStripButton.cs
Fixes #3659 
- added a new "DrawButtonBorder" method to the ToolStripRender for drawing a dotted border around the ToolStripButtons in the PropertyGrid
- added unit tests
Focus is not clearly visible on "Categorized", "Alphabetical" and " Property Pages" when user uses Keyboard for navigating.
As a fix, we show a dotted border around the ToolStripButtons in the PropertyGrid
- No
- Minimal
- .Net SDK 5.0.100-rc.1.20420.14
=> Add focus rectangle focus to ToolStripButtons on PropertyGrid

src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
Fixes #4264
The native callback can be garbage collected even in a simple app, which leads to an app crash with ExecutionEngineException.
The issue can be observed even in an app as simple as:
```cs
namespace repro_listview
{
static class Program
{
[STAThread]
static void Main()
{
Application.SetHighDpiMode(HighDpiMode.SystemAware);
Application.EnableVisualStyles();
Application.SetCompatibleTextRenderingDefault(false);
var f = new Form();
var listView = new ListView();
f.Controls.Add(listView);
listView.Items.Add("A");
listView.Items.Add("Z");
listView.Items.Add("X");
listView.ListViewItemSorter = new TestComparer();
Application.Run(f);
}
class TestComparer : Comparer<ListViewItem>
{
public override int Compare(ListViewItem x, ListViewItem y)
{
GC.Collect();
Thread.Sleep(10);
return 0;
} …
```
=> fix: Prevent GC'on of native callback

src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.TTOOLINFOW.cs, src/System.Windows.Forms.Primitives/src/Interop/Ole32/Interop.GPStream.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/DeviceContextHdcScope.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/FileDialogCustomPlacesCollection.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/GdiPlus/GdiPlusCache.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/NativeMethods.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/WeakRefCollection.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/ObjectCache.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/RefCountedCache.Scope.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/SinglyLinkedList.cs
Contributes to https://github.com/dotnet/winforms/issues/3459
- Use 'is not null' in System.Windows.Forms.Primitives.
=> Use 'is not null' in System.Windows.Forms.Primitives

src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewItemCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItemCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSettings.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeCollection.cs
- Use generic list in FindInternal and FindControls methods of some classes.
=> Use generic list in FindInternal and FindControls methods of some classes

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridToolStripButton.cs
Fixes #4268
- Added a special method for high contrast mode that draws a black and white dashed border
- Added a special method for normal mode that draws a dashed border
**After fix:**
Normal mode:
High Contrast 1:
High Contrast 2:
High Contrast Black:
High Contrast White:
- No
- Minimal
- Manually 
=> Adding border for focused ToolStripButton in PropertyGrid

src/System.Windows.Forms.Primitives/src/Interop/Interop.PARAM.cs, src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/PARAMTests.cs, src/System.Windows.Forms/src/System/Windows/Forms/TaskDialog.cs
- Resolve TODOs in the TaskDialog code by using native-sized integers (`nint`/`nuint`) where applicable, to reduce overhead for 32-bit platforms and to avoid having to use the `unsafe` keyword.
- In class `PARAM`, cast `IntPtr` to `nint` instead of `long` where applicable.
- None
- No
-
- Testing the changed code running as `x86` and `x64` with various inputs, including values where an overflow could happen, to make sure it behaves the same as the previous code.
- Added tests for `PARAM`.
Version:   6.0.100-alpha.1.20472.11
Commit:    e55929c5a5
Base Path:   C:\Program Files\dotnet\sdk\6.0.100-alpha.1.20472.11\ …
=> Use native-sized integers to avoid overhead for 32-bit platforms

src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/MainFormControlsTabOrder.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ErrorProviderTest.Designer.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ErrorProviderTest.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ErrorProviderTest.resx, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
Fixes #2390
Original bug: [987891](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/987891)
Based on PR #2391
- Raise an automation notification when setting an error for a control
- Don't add a tooltip announcing as in PR #2391 because it leads to Issue #2538
- Add a UI test app to check an `ErrorProvider`
- A screen reader can announce an `ErrorProvider` error text
- No
- Minimal
- Narrator doesn't announce an error text:
- Narrator announces an error text when a red icon of an `ErrorProvider` appears:
- Added `ErrorProviderTest` app to `WinformsControlsTest` project
- UI testing
- CTI
- Using Narrator and NVDA
- Microsoft Windows [Version 10.0.19042.630]
- .NET Version:   6.0.100-alpha.1.20554.10
=> Fixing ErrorProvider error text announcing by a screen reader

src/System.Windows.Forms/tests/UnitTests/VScrollBar.VScrollBarAccessibleObjectTests.cs
- Removed ignore for the "VScrollBarAccessibleObject_Ctor_Default" test
- No 
- No
- Minimal
- Unit tests 
- .Net SDK 5.0.100-rc.2.20479.15
=> Removing ignore for the "VScrollBarAccessibleObject_Ctor_Default" test

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CursorConverterTests.cs
Ensure static Cursor accessors are initialized before testing return value consistency in multithreaded environments
Fixes #4309
as mentioned in the issue returning different instances during multithreaded access is acceptable and the test needs to take that into consideration
none, product behavior remains as-is, only the test is changed
no
no new risks, test made incorrect assumptions
If two threads are accessing the static cursor properties at the same time both may have observed the backing field as null and created their own cursor instance. Only one of them "wins" the write to the backing field, the other will return a different instance than on subsequent calls to the property. The test was making the assumption that the value returned from static properties never changes which is …
=> Fix flaky Cursor accessor test

src/System.Windows.Forms/src/System/Windows/Forms/ImageList.ImageCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ImageList.NativeImageList.cs, src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
This reverts commit 03db3fbfcc6884356f70141f882433638b23bb49.
Resolves #4169
Resolves #4275
Revert "Explicit ImageList ownership management. (#3601)"
This reverts commit 03db3fbfcc6884356f70141f882433638b23bb49.
Revert "Fix `ListView` no longer displays images (#4184)"
This reverts commit d0608e72a356ad991f9c9d12518e29b43a1fb4f0.
We have observed an instability of tests under stress (and reasonably high degree of concurrency) presumably caused by ImageList lifetime handling (notably #3358).
The changes introduced in #3601 have helped with tests stability, however resulted in a number of regressions, such as #4169 and #4275.
Restore the original implementation given it worked reasonably well for the past so many years.
- The `ImageList` behaviours should be the same as in .NET Framework …
=> Revert "Explicit ImageList ownership management"

src/System.Windows.Forms/tests/UnitTests/NumericUpDownTests.cs
Fixes #4211 
- Split `NumericUpDown_VisualStyles_off_BasicRendering` into 2 smaller tests that assert a single case, enabled and disabled.
- None
- No
- Low
- Ran the rendering tests.
=> Granular NumericUpDownTests (#4211)

src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.cs
Resolves #4310
Resolves dotnet/winforms-designer#2057
ListViewGroups can't have title images set via either key or index, as propertygrid is unable to discover the bound imagelist.
Correct the missing binding by applying `RelatedImageListAttribute` to respective properties.
- Currently it is impossible to set title images via UI tools (this includes Visual Studio designer). Thus affects the perception of working state of the Windows Forms designer.
- No, support for `ListViewGroup` title images was introduced in .NET 5.0 in #3490.
- Minimal
- By substituting binaries under C:\Program Files\dotnet\shared\Microsoft.WindowsDesktop.App\6.0.0-alpha.1.20570.2 and running a sample project
=> Correct imagelist binding for ListView groups

.gitignore, src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.LoadLibrary.cs, src/System.Windows.Forms/src/System.Windows.Forms.csproj, src/System.Windows.Forms/src/System/Windows/Forms/Application.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Properties/launchSettings.json
Provide functionality to load a custom comctl32.dll from the application startup folder, if comctl32.dll is present in that location.
This allows loading debug and custom builds of the library.
- Adding a debug version comctl32.dll to /src/System.Windows.Forms/src
- Build and run WinformsControlsTest project
- Observe the comctl32.dll is copied to the output folder
- Run "ListView" example and observe debug asserts being hit in the comctl32 source
- Check loaded modules in "Modules" window
=> Allow loading custom comctl32.dll

.editorconfig
From https://github.com/dotnet/runtime/blob/master/docs/coding-guidelines/coding-style.md:
`We only use var when it's obvious what the variable type is (e.g. var stream = new FileStream(...) not var stream = OpenStandardInput()).`
=> ensure that editor config follows runtime coding style (vars when type is obvious)

src/System.Windows.Forms/src/System/Windows/Forms/ImageList.ImageCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/ImageList.NativeImageList.cs, src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
This reverts commit 03db3fbfcc6884356f70141f882433638b23bb49.
Resolves #4169
Resolves #4275
Revert "Explicit ImageList ownership management. (#3601)"
This reverts commit 03db3fbfcc6884356f70141f882433638b23bb49.
Revert "Fix `ListView` no longer displays images (#4184)"
This reverts commit d0608e72a356ad991f9c9d12518e29b43a1fb4f0.
We have observed an instability of tests under stress (and reasonably high degree of concurrency) presumably caused by ImageList lifetime handling (notably #3358).
The changes introduced in #3601 have helped with tests stability, however resulted in a number of regressions, such as #4169 and #4275.
Restore the original implementation given it worked reasonably well for the past so many years.
- The `ImageList` behaviours should be the same as in .NET Framework …
=> Revert "Explicit ImageList ownership management" (servicing)

src/System.Windows.Forms/src/System/Windows/Forms/ControlPaint.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.cs
Order statics so sizing is correctly calculated. Change ControlPaint.DrawSizeGrip to use GDI+ to get fully applied transforms.
Fixes #4238
=> Fix resize grip in DropDown editor

src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeCollection.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeCollectionTests.cs
Fixes #3437
- Setter of method this[int index] of class TreeNodeCollection is replacing the existing TreeNode instead of adding it
=> Setting a new TreeNode in a TreeNodeCollection will replace existing one

src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiListViewTests/MauiListViewTests.cs, src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiTestsHelper/MouseHelper.cs
Fixes #4156
- Added virtual mode validation for a double click
The checkbox will not change its value on a double click when ListView is in virtual mode.
Before fix:
After fix:
- No
- Minimal
- Manually
- .Net SDK 5.0.100-rc.2.20479.15
=> Adding virtual mode validation for a double click

src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxes.Designer.cs
Fixes #4323
- Added logic that makes an index shift, which helps to draw a bounding rectangle with the correct position 
Before:
After:
- No
- Minimal
- Manually
- Inspector
=> Fixed position of bounding rectangle for ComboBox items when drop down shows a scrollbar

src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
Fixes #4283
- Use [MCM_SETDAYSTATE](https://docs.microsoft.com/windows/win32/controls/mcm-setdaystate) message to a native control instead of recreating its `Handle` in the Month view
- Change unit tests, because we don't create a `Handle` anymore when setting `BoldedDates`, `AnnuallyBoldedDates`, and `MonthlyBoldedDates`
- A calendar doesn't reset a display dates range after calling [UpdateBoldedDates](https://docs.microsoft.com/dotnet/api/system.windows.forms.monthcalendar.updateboldeddates) method now.
- The flickers have not disappeared but there are fewer of them than before. 
> The flickers reproduce for a native [MonthCalendar](https://docs.microsoft.com/windows/win32/controls/month-calendar-control-reference) control too, it seems it is a native control issue.
- No
- Middle, we …
=> Fixing MonthCalendar a display dates range resets and flickers after calling UpdateBoldedDates 

src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/NotifyIcon.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/NotifyIconTests.cs
Fixes #4361
- Change character limit for text in NotifyIcon.Text from 63 to 127 characters.
- This matches the Windows Control that was changed in an OS released before .Net is supported.  
- No
- Very low, all tests updated and all supported OS's support 127.
- Update all tests to of this code to use 127 instead of 63
The underlying windows control supports 127 characters and the testing now uses 127 allowing the text to support longer descriptions.  
- 5.0.200-preview.20601.7 [C:\Program Files\dotnet\sdk]
=> Fix NotifyIcon.Text limits text to 63 characters, but should be 127

src/System.Windows.Forms/src/misc/CompatibleIComparer.cs, src/System.Windows.Forms/src/misc/WeakHashtable.cs
- Enable nullability in CompatibleIComparer and WeakHashtable.
=> Enable nullability in CompatibleIComparer and WeakHashtable

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ConvertEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListControlConvertEventArgs.cs
- Enable nullability in ConvertEventArgs and ListControlConvertEventArgs.
=> Enable nullability in ConvertEventArgs and ListControlConvertEventArgs

src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Helpers/NativeTypes.vb, src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Interaction.vb
Fixes #4385 for VB
- Change Not "Is" tp IsNot for VB
- Ignore IDE1006 for 1 constant that came from Framework
- This cleans up all Code Cleanup issues for VB
- Cleans up issue for VB Source, no impact on Binaries
- 
- No
- Minimal added attribute and used equivalent comparison in VB that makes code easier to understand
- Runs existing test, this is more about IDE issues not runtime
-  
- N/A All existing test should see no impact
=> Fix #4385 for VB and fixed constant name from Framework

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/DragEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/ItemDragEventArgs.cs
- Enable nullability in DragEventArgs and ItemDragEventArgs.
=> Enable nullability in DragEventArgs and ItemDragEventArgs

src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellTests.cs
Fixes #3925
Based on changes from #4124
- Added logic for restoring of parent during reattaching of EditingControlAccessibleObject. 
- Added missing validation for "EditingControlAccessibleObject" property.
Fixed issue with hanging of Accessibility Insights during getting of data about textbox from DataGridViewTextBoxCell
- Yes
- Minimal
- Manually 
- Narrator
- Inspector
=> Fixing issue with getting of textbox from DataGridViewTextBoxCell by Accessibility Insights (port to 3.1) 

src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellTests.cs
Fixes #3925
Based on changes from #4124
- Added logic for restoring of parent during reattaching of EditingControlAccessibleObject. 
Fixed issue with hanging of Accessibility Insights during getting of data about textbox from DataGridViewTextBoxCell
- Yes
- Minimal
- Manually 
- Narrator
- Inspector
=> Fixing issue with getting of textbox from DataGridViewTextBoxCell by Accessibility Insights (port to 5.0)

src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/MainFormControlsTabOrder.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxesWithScrollBars.Designer.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxesWithScrollBars.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ComboBoxesWithScrollBars.resx, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
Fixes #4335
Fixes #4323
Based on changes from #4350
⚠️ A port of a .NET Framework servicing fix 
- Implement `ScrollIntoView `method of `ScrollItemPattern`
- Fix getting of `Bounds`
- Accessibility tools or users can scroll a combo box drop-down list to some item
- A user can see a correct item Bounds position when combobox scrolling
- These 2 bugs were approved for servicing in .NET Framework 4.8 in February release
- Yes (from .NET Framework 4.7.2)
- Minimal
- ComboBox items don't support `ScrollItemPattern` - `ScrollIntoView` is not available
- ComboBox items support `ScrollItemPattern` - ensure that the item is visible when invoking `ScrollIntoView`.
For example, in the gif below I call `ScroolIntoView` for the **9th** item, and the `ComboBox` shows the **9th** item.
- Unit tests
- …
=> Implemented ScrollItemPattern for ComboBoxItemAccessibleObject (port to 5.0)

src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/MDIControlStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/MdiControlStrip.ControlBoxMenuItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/MdiControlStrip.SystemMenuItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/MenuTimer.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MdiParent.cs
Fixes #3029
With the deprecation and removal of `MainMenu` control in #2091 one of MDI scenarios got broken where both parent and child forms don't have `MainMenuStrip` property set nor have `MainMenuStrip` instance added to their respective `Controls` collection.
The fix restores setting an MDI menu via `WM_MDISETMENU` message to the parent form.
Customers who use MDI scenarios without main menu in both parent or child forms won't be able to minimise maximised child forms
| net472 | netcoreapp3.1 |
| -- | --- |
| ![image](https://user-images.githubusercontent.com/4403806/84857263-fab0ac00-b0ab-11ea-9639-a6db8f04cff4.png) | ![image](https://user-images.githubusercontent.com/4403806/84860154-e96a9e00-b0b1-11ea-857f-e46b6916737e.png) |
- Yes
- Minimal.
<details>
<summary>👉 👉 👉  Click for …
=> fix MDI forms lost sub control box

src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildDropDownButtonUiaProvider.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxChildDropDownButtonUiaProviderTests.cs
Fixes #4391
- Changed logic for getting the name of the button. Now we check the state of the ComboBoxDropDownList and based on its state we return the required name
Before:
After:
- Yes
- Minimal
- Manual
- Unit tests
- Inspect
=> Fix endless recursion when getting "ComboBoxChildDropDownButtonUiaProvider.Name" property

NuGet.config
Fixes #4516
Clear the `disabledPackageSources` in `nuget.config` to prevent global settings affecting the locally setup sources. In particular it could happen that in Visual Studio UI a package source with the same key was defined but unchecked, in which case the local `nuget.config` would ignore the local definition of that source because it inherited the `disabledPackageSources` from the global settings.
This also matches what other projects like [arcade](https://github.com/dotnet/arcade/blob/8b7ec67401393a062292446cf9602c9a0b64c758/NuGet.config) are doing
Allow local builds independent of global nuget settings
unknown
none, other projects like arcarde are doing it too
local builds fail if a package source with the same key is defined but unchecked in the global Visual Studio settings …
=> Use local definition of disabledPackageSources

src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs
Resolves #4536
`Control.Invoke` incorrectly rethrown exception thrown from original invoked methods, thus losing the original stack, and the new exception appeared as though if began at `Control.MarshaledInvoke` method.
Use `ExceptionDispatchInfo.Throw` to preserve the original stack trace.
=> Correctly rethrow exceptions

src/System.Windows.Forms.Primitives/src/Interop/Gdi32/Interop.HENHMETAFILE.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/EmfScope.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextRenderer.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextRendererTests.cs
Translation and clipping should only be applied from Graphics objects when they are explicitly asked for in the TextFormatFlags.
Adds regression tests.
Fixes #4524
- Apply graphics properties only when requested
- Add regression tests
- This causes rendering to not work correctly when transforms and clipping are in play.
- This shows up in 3rd party control libraries, such as Telerik's. It can cause text to "vanish" as it isn't rendered in the clipped area.
- Workarounds are difficult, particularly when this shows up in 3rd party control libraries.
- Yes
- Very low
- Test Telerik provided repro
- Audit of legacy code
- Add regression tests
=> Properly apply translation and clipping in TextRenderer

src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
Fixes #4541 
- The issue is reproduced because the resize triggers the "OnResize" event which triggers the "InvalidateEverything" where we get the "Handle" property. As a fix, added "IsHandleCreated" check, before calling the "InvalidateEverything" method.
- No 
- No
- Minimal
- Unit tests
- .NET Core SDK 5.0.200-preview.20614.14
=> Fixing the problem with forced creation of a handle when resizing a ComboBox

src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageListTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Resolves #4265
- Prevent `ListView` detaching a shared `ImageList` multiple times
-  manual
- unit tests
=> Fix `ListView` detaches shared `ImageList`  twice

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/TreeViewHitTestInfo.cs
- Enable nullability in TreeViewHitTestInfo.
=> Enable nullability in TreeViewHitTestInfo

src/System.Windows.Forms/src/PublicAPI.Unshipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.IKeyboardToolTip.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroupTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.IKeyboardToolTipTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Fixes #4320
- Added support for "IKeyboardToolTip" interface in "ListViewItem" class.
- Added logic to show the tooltip for the focused ListViewItem when the user switches between items 
Before:
After:
- No
- Minimal
- Manually 
=> Support keyboard tooltips in `ListViewItem`

src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.Vista.cs, src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.VistaDialogEvents.cs, src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.FileOpenDialogRCW.cs, src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.NativeFileOpenDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/OpenFileDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/SaveFileDialog.FileSaveDialogRCW.cs, src/System.Windows.Forms/src/System/Windows/Forms/SaveFileDialog.NativeFileSaveDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/SaveFileDialog.cs
- Moved sub-classes of "FileDialog", "OpenFileDialog" and "SaveFileDialog" classes to their own files 
- No 
- No
- Minimal
- .NET Core SDK 6.0.0-alpha.1.21073.5
=> Moved sub-classes of "FileDialog", "OpenFileDialog" and "SaveFileDialog" classes to their own files

src/System.Windows.Forms/src/System/Windows/Forms/BindingNavigator.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs, src/System.Windows.Forms/tests/UnitTests/BindingNavigatorTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs
Fixes #4216
- Add Dispose event handlers to clear DataSource of DGV and BindingSource of BindingNavigator thereby update their data source actual state
- A user won't catch the exception when closing a form or disposing a BindingSource
- Yes and no. .NET Framework 4.8 throws an exception when closing a form. v.4.7 doesn't throw the exception in this case. But anyway every version throws the exception if to Dispose a BindingSource component
- Minimal
- A DataGridView doesn't update its Rows and Columns collections after its DataSource is disposed. And the DGV throws the exception when trying to redraw because the DGV is trying to draw items from a DataSource that doesn't already exist (send some index, eg. 4, to the collection that has 0 items, and catch IndexOutOfRangeException)
- …
=> Fixing IndexOutOfRangeException throwing by DGV when disposing its DataSource

src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
Fixes #4370
The issue fixes some code that was probably erroneously copied & pasted when porting from .NET framework here:
https://referencesource.microsoft.com/#System.Windows.Forms/winforms/Managed/System/WinForms/Control.cs,17065
- quite critical, as in certain situation .NET Core is totally unusable due to this. E.g. when using Core inside Office Add-Ins, it was not possible at all to use the task pane for building addins. This is a showstopper for our go-live.
- None introduced, hopefully
- unknown
- run build and test
- sorry, this project is quite tangential for me, and it is an obvious fix, once you confirmed this successfully for the main branch, it would be awesome to backport to 5.x, let me know if I should create a PR as well for that.
=> Fix NRE when instantiating UserControl as ActiveX object

src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/MDIControlStrip.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FormTests.cs
Fixes #4621
- The visibility of the Icon in the MDIControlStrip is dependent on the ShowIcon property on the target MDI child.
- When the icon gets updated in the target MDI child, the icon gets updated in the MDIControlStrip and its visibility is checked.
- The icon will now change dependent on ShowIcon and the icon in the target MDI child.
- No
- Icon can not be used to open context menu when icon is hidden.
With showicon = false and the icon set to error icon after it is maximized.
the icon set to error icon after it is maximized.
With showicon = false
- manual testing
- Unit test
=> Mdicontainer iconchanges

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/TreeViewCancelEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeViewEventArgs.cs
- Enable nullability in TreeViewCancelEventArgs and TreeViewEventArgs.
=> Enable nullability in TreeViewCancelEventArgs and TreeViewEventArgs

Winforms.sln, src/System.Windows.Forms.Primitives/src/Properties/AssemblyInfo.cs, src/System.Windows.Forms/src/Properties/AssemblyInfo.cs, src/System.Windows.Forms/src/PublicAPI.Unshipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/Label.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs, src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs, src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiTabControlTests/MauiTabControlTests.cs, src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiTabControlTests/MauiTabControlTests.csproj, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.Maui.IntegrationTests/WinformsMauiTabControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/LabelTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolTipTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/UpDownBaseTests.cs
Fixes #2717
Related Issue #4305
Based on PR #2719. But the changes were significantly reworked so I have created this new PR
Most of review points from #2719 were fixed here
- Notify `KeyboardToolTipStateMachine` about getting and losing a focus
- Inverted incorrect dependencies inside `ToolTip` class
- A user can see a TabPage toolTip when using a keyboard
- No
- Minimal
- TabControl shows mouse toolTips only:
- Keyboard toolTips are available for TabControl:
- Unit tests
- CTI
- .NET Version: 6.0.0-alpha.1.20554.7
- Microsoft Windows [Version 10.0.19042.685]
=> Adding the ability to get keyboard toolTips for TabPages of a TabControl

src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.TopRowAccessibleObject.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/DataGridViewTopRowAccessibleObjectTests.cs
Fixes #4242
- Fixed issue with getting of the non-existing item
Before fix:
After fix:
- No
- Minimal
- CTI team 
- Unit tests
- Inspector
- .NET Core Version: 5.0.200-preview.20614.14
=> Fix inspector crash moving cursor inside the `DataGridView` with `AllowUserToAddRows=false`

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridToolStripButton.PropertyGridToolStripButtonAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridToolStripButton.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/PropertyGridToolStripButton.PropertyGridToolStripButtonAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridToolStripButtonTests.cs
Fixes #4428
- Added logic to use `RadioButton` control type instead of `CheckBox` control type. In 4.7.2 these PropertyGrid buttons were of the `Checkbox` control type, which changed to `Button` from 4.8. After fixing #3618 we returned the behavior that was originally in 4.7.2, but we have lost support for the `Toggle` pattern. Since the buttons do not visually look like checkboxes, we wanted to change the `CheckBox` control type to `Button` control type that supports the `Toggle` pattern. Unfortunately, the "Accessibility Insights" rules prohibit the button to simultaneously support the `Invoke` and `Toggle` patterns. Therefore, based on the fact that the buttons have a behavior similar to radiobutons, as a fix, we decided to assign them a `RadioButton` control type.
- Added `SelectItem` …
=> Changing the "ComboBox" control type to "RadioButton" control type for buttons in PropertyGrid

src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowAccessibleObjectTests.cs
Fixes #4228
- Added skipped checks for null. The issue is reproduced because in some cases the "DataGridView" property may be null. Most of the methods and properties check that the "DataGridView" property is not null. But in some places (including the "FragmentRoot" property) we forgot to add this check and got an exception as a result.
- Added unit tests. 
**After fix:**
- Yes
- Minimal
- Unit tests
- CTI team
- Narrator
- .NET Core Version: 6.0.0-preview.2.21154.2
=> DataGridView throws NRE when Narrator is active

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Automation/UiaTextRange.cs, src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/Automation/UiaTextRangeTests.cs, src/System.Windows.Forms/src/PublicAPI.Unshipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildEditUiaProvider.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxUiaTextProvider.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseUiaTextProvider.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Properties/launchSettings.json, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxChildEditUiaProviderTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxUiaTextProviderTests.cs
Fixes #4409
- Added ComboBoxUiaTextProvider class to support TextPattern. Its logic is based on the TextBoxBaseUiaTextProvider, but we use the native control handle, which is responsible for editing
Before:
After:
- Yes, from #3654
- Minimal
- Unit tests
- CTI team
- Inspect
- Narrator
- .NET Core SDK 5.0.200-preview.20614.14
=> Adding support for text pattern to ComboBox

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/TabPage.TabPageControlCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.TipInfo.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.ToolTipNativeWindow.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.ToolTipTimer.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
- Move sub-classes of "ToolTip" and "TabPage" classes to their own files
- Fixed code sorting
- No 
- No
- Minimal
- .NET Core SDK 6.0.100-preview.2.21155.3
=> Move sub-classes of "ToolTip" and "TabPage" classes to their own files

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/DrawToolTipEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/DrawTreeNodeEventArgs.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DrawTreeNodeEventArgsTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
- Enable nullability in DrawToolTipEventArgs and DrawTreeNodeEventArgs.
=> Enable nullability in DrawToolTipEventArgs and DrawTreeNodeEventArgs

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowCancelEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowContextMenuStripNeededEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowDividerDoubleClickEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowErrorTextNeededEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowPostPaintEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowPrePaintEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowStateChangedEventArgs.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowDividerDoubleClickEventArgsTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowStateChangedEventArgsTests.cs
- Enable nullability in some DataGridView EventArgs.
=> Enable nullability in some DataGridViewRow EventArgs

CodeMaid.config, src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListVIew.ListViewAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObjectTests.cs
Fixes #4205
- Added conditions to ignore `ListViewGroupAccessibleObject` when groups or visual styles are disabled
- Updated unit tests. 
- Yes (from #3223) 
- Minimal
- Unit tests
- CTI team
- Inspector
=> Fix issue with showing groups in the Inspector when groups are disabled

src/System.Windows.Forms/src/PublicAPI.Unshipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
Fixes #3455
- Added logic for forced announcement of RichTextBox text
**After fix:**
- No
- Minimal
- CTI team 
- Inspector
- Microsoft Windows: Version 10.0.19041.388
- .NET Core SDK: 6.0.0-preview.2.21154.2
=> Fix issue with announcing RTB content by Narrator

Winforms.sln, src/System.Windows.Forms.Primitives/src/Properties/AssemblyInfo.cs, src/System.Windows.Forms/src/PublicAPI.Unshipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/LinkClickedEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs, src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiRichTextBoxTests/MauiRichTextBoxTests.cs, src/System.Windows.Forms/tests/IntegrationTests/MauiTests/MauiRichTextBoxTests/MauiRichTextBoxTests.csproj, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/RichTextBoxes.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/WinformsControlsTest.csproj, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs
Resolves #4431
Pass link span to `LinkClickedEventArgs` as they are not otherwise obtainable.
The clicked link span is available to user code, which is vital information if you use hidden text adjacent to the link for storing additional information. This was a common strategy for the old RTF textbox control and helps porting old code.
no
none, this is adding new API
link span was not available
link span is available and adjacent hidden text can be retrieved easily
added new unit tests to cover the usage scenarios of retrieving adjacent hidden text
not necessary, this API does not change the UI
unit tests
=> Add link span to LinkClickedEventArgs

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Padding.cs
Fixes #4561 
Padding is serialized in to Resx file and any serializable type that was 'TypeForwardedTo' should have 'TypeForwarededFrom' attribute to help is de-serialize it.
And also, we recently added dependency on this attribute, in core designer, while writing types in to Resx file.
Any resource file that has Padding serialized will fail to load it while de-serializing the type for the application. This attribute was missed while moving this type from System.Windows.Forms.dll
- Yes from .NETcore 3.1 and .NET framework.
-None
=> Adding 'TypeForwardedFrom' attribute for System.Windows.Forms.Padding.

src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.LinkCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.LinkComparer.cs, src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/LinkLabel.LinkComparerTests.cs
- Use generic lists in LinkLabel.
=> Use generic lists in LinkLabel

src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItemCollection.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewSubItemCollectionTests.cs
Fixes #4742
- Added missing logic for adding and removing owner. The problem is reproduced because when getting an accessibility object for a `ListViewSubItem`, the `ListViewSubItem` may not have an owner. This is because we have several ways to create and add an unowned `ListViewSubItem` to an `ListViewItem`.
- Added/updated unit tests
An app crash upon clicking on a listview subitem.
* **Before fix:**
* **After fix:**
- Yes
- Minimal
- Unit tests
- CTI team
- Microsoft Windows: Version 10.0.19041.388
- .NET Core SDK: 6.0.0-preview.2.21154.2
=> Fix ANE in the "ListViewSubItemAccessibleObjectin " constructor

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Padding.cs
Fixes #4561 (a cherrypick of  #4715)
Padding is serialized in to Resx file and any serializable type that was 'TypeForwardedTo' should have 'TypeForwarededFrom' attribute to help is de-serialize it.
And also, we recently added dependency on this attribute, in core designer, while writing types in to Resx file.
Any resource file that has Padding serialized will fail to load it while de-serializing the type for the application. This attribute was missed while moving this type from System.Windows.Forms.dll
- Yes from .NET core 3.1 and .NET framework.
None
=> Porting: Fixing missing 'TypeForwardedFrom' attribute

src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItemCollection.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewSubItemCollectionTests.cs
Fixes #4742
- Added missing logic for adding and removing owner. The problem is reproduced because when getting an accessibility object for a `ListViewSubItem`, the `ListViewSubItem` may not have an owner. This is because we have several ways to create and add an unowned `ListViewSubItem` to an `ListViewItem`.
- Added/updated unit tests
An app crash upon clicking on a listview subitem.
* **Before fix:**
* **After fix:**
- Yes
- Minimal
- Unit tests
- Microsoft Windows: Version 10.0.19041.388
- .NET Core SDK: 5.0.100
=> Fix ANE in the "ListViewSubItemAccessibleObjectin" constructor (#4744) (port to 5.0)

src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObject.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListVIew.ListViewAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObjectTests.cs
Fixes #4779
- An ListViewItem is considered invisible when it is in a ListViewGroup but not added to the ListView. In this case, the ListViewGroup contains data about it, but the ListViewItem is not displayed in the list. To solve this problem, the "VisibleItems" property was added, which contains a list of only displayed ListViewItems, in which the property "ListView" is not empty. Now, when receiving data about the ListViewItems of a ListViewGroup, we use this property and not "Items" property of the ListViewGroup.
- if the ListViewGroup is empty or contains invisible ListViewItems (case above), then this ListViewGroup is also not displayed in the ListView. This issue was solved in the same way as the issue above, by adding the "VisibleGroups" property that contains a list of only the …
=> Fix issue with displaying empty ListViewGroups

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/DeviceContextHdcScope.cs, src/System.Windows.Forms/src/System/Windows/Forms/Internal/DrawingEventArgs.cs
This is a new obsoletion in System.Drawing. Disabling so we can consume the new build. Will follow this change with another that consumes the newer API.
Unblocks https://github.com/dotnet/winforms/pull/4802
=> Disable SYSLIB0016 warning

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/DeviceContextHdcScope.cs, src/System.Windows.Forms/src/System/Windows/Forms/Internal/DrawingEventArgs.cs
Use new Graphics.GetContext overloads that minimize allocations and remove warning suppression.
=> Use new GetContext overloads

src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/ScrollBar.cs, src/System.Windows.Forms/src/System/Windows/Forms/ScrollProperties.cs, src/System.Windows.Forms/src/System/Windows/Forms/ScrollableControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
`sizeof` is a compile time constant and as a result, much faster.
=> Don't use Marshal.SizeOf for SCROLLINFO

src/System.Windows.Forms.Primitives/src/Interop/ComCtl32/Interop.LVGGR.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObject.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListVIew.ListViewAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObjectTests.cs
Fixes #4778
- The issue with the incorrect rectangle is reproduced because the "FragmentRoot" property was not overridden. Added an override for the "FragmentRoot" property.
- Fixed issue with getting a rectangle for a ListViewGroup. Now, instead of the ListViewGroup index, we use the group ID. Fixed a issue with getting an incorrect ListViewGroup index.
- Added unit tests. Fixed typos in unit-tests naming
**After fix:**
**After fix:**
- Yes (from #3224)
- Minimal
- CTI team
- unit tests
- Inspector
- .NET Core SDK: 6.0.100-preview.2.21155.3
=> Fix rectangle of the ListViewGroup

eng/ApiCompatibility/README.md, eng/ApiCompatibility/mark-shipped.cmd, eng/ApiCompatibility/mark-shipped.ps1
> _Imitation is the sincerest form of flattery_. 
Shamelessly stealing the work of @tmat from https://github.com/dotnet/roslyn/blob/main/scripts/PublicApi/ to ease the pain of shipping API each release.
=> Script to mark API as shipped

.editorconfig
https://marketplace.visualstudio.com/items?itemName=PaulHarrington.EditorGuidelines
=> Editor Guidelines config

src/System.Windows.Forms/src/System/Windows/Forms/Internal/WinFormsMetadataUpdateHandler.cs
.NET hot reload enables changes to be made to an app while it's running.  If you were to patch a control's OnPaint routine, for example, the next time that was invoked, it would end up running the newly patched code.  However, nothing at the runtime level applying updates automatically triggers Windows Forms to refresh its controls.  Instead, a notification mechanism is used to invoke any interested listeners about an update.  Windows Forms can have its own listener, which it can use to do anything it would like in response to the update notification.  This PR adds such a listener, and uses it to refresh every open form in the application.  Future updates to it could be used to do other things, like request that data bound controls rebind, in case the thing they're bound to has changed in …
=> Add MetadataUpdateHandler to WinForms to repaint all open forms

src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker.cs
This PR fixes an incorrect code in PR #4374. 
This code is using GetWindowLong and SetWindowLong on OnEnabledChanged. This could cause a handle creation before the control is displayed.
See discussion here : https://github.com/dotnet/winforms/pull/4374#discussion_r621914769
=> Fix handle creation on DateTimePicker.Enabled change

src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Fixes #4839
- The issue is reproduced because during the creation of the ListViewItemAccessibilityObject, we save the current value of the ListViewGroup and it is no longer updated. This is not the right approach because the user can change the ListViewGroup of a ListViewItem or remove ListViewGroups from the ListView. Currently we use the "OwningGroup" property, which, on each call, calculates whether the ListView has ListViewGroups and which ListViewGroup the ListViewItem is in.
- Also, an issue with an attempt to get "Bounds" property when the Handle is not created has been fixed. Now, in the absence of a Handle, we immediately return an empty rectangle
- Added and updated unit tests 
Before fix:
After fix:
- Yes (from #3223)
- Minimal
- CTI team
- Unit tests
- Inspector
- Microsoft …
=> ListViewItemAccessibleObject doesn't respect updating a group

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HtmlDocumentTests.cs
Currently all public CI builds are failing with
```
System.Windows.Forms.Tests.HtmlDocumentTests.HtmlDocument_Focus_Invoke_Success [FAIL]
Assert.False() Failure
Expected: False
Actual:   True
Stack Trace:
/_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HtmlDocumentTests.cs(1566,0): at System.Windows.Forms.Tests.HtmlDocumentTests.HtmlDocument_Focus_Invoke_Success()
--- End of stack trace from previous location ---
System.Windows.Forms.Tests.HtmlDocumentTests.HtmlDocument_Focused_GetFocused_ReturnsExpected [FAIL]
Assert.False() Failure
Expected: False
Actual:   True
Stack Trace:
/_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HtmlDocumentTests.cs(644,0): at System.Windows.Forms.Tests.HtmlDocumentTests.HtmlDocument_Focused_GetFocused_ReturnsExpected()
--- …
```
=> Fix HtmlDocument tests

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HtmlDocumentTests.cs
Porting https://github.com/dotnet/winforms/pull/4904 to release/5.0
Currently all public CI builds are failing with
System.Windows.Forms.Tests.HtmlDocumentTests.HtmlDocument_Focus_Invoke_Success [FAIL]
Assert.False() Failure
Expected: False
Actual:   True
Stack Trace:
/_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HtmlDocumentTests.cs(1566,0): at System.Windows.Forms.Tests.HtmlDocumentTests.HtmlDocument_Focus_Invoke_Success()
--- End of stack trace from previous location ---
System.Windows.Forms.Tests.HtmlDocumentTests.HtmlDocument_Focused_GetFocused_ReturnsExpected [FAIL]
Assert.False() Failure
Expected: False
Actual:   True
Stack Trace:
/_/src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HtmlDocumentTests.cs(644,0): at …
=> Fix HtmlDocument tests (#4904)

src/System.Windows.Forms/src/System/Windows/Forms/LinkLabel.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextFormatFlags.cs, src/System.Windows.Forms/src/System/Windows/Forms/TextRenderer.cs
While painting LinkedLabel we modify device context before drawing the
label's text. Because of that we hit the asserts in TextRenderer.GetApplyStateFlags.
Since the DC state is expected, skip the assertions.
Closes #4857
=> Allow to skip TextRenderer asserts

src/System.Windows.Forms.Primitives/tests/TestUtilities/Extensions/AssertExtensions.cs, src/System.Windows.Forms.Primitives/tests/TestUtilities/System.Windows.Forms.Primitives.TestUtilities.csproj, src/System.Windows.Forms/src/Properties/AssemblyInfo.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObject.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxItemAccessibleObjectTests.cs
Fixes #4372
- Added logic that checks that the drop down list is expanded and the item is in the visible area
- Added logic for supporting of the "OffScreen" state
CASE 1:
Before:
After:
CASE 2:
Before:
After:
- No
- Minimal
-  Manually
- Unit tests
=> Fixing issue with showing of the bounding rectangle for invisible items in ComboBox

src/System.Windows.Forms/src/System/Windows/Forms/Application.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ApplicationTests.cs
As pointed in https://github.com/dotnet/winforms/pull/4911#discussion_r632371636
=> Validate input in Application.SetHighDpiMode() method

src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
=> publishing APIs

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/OsVersion.cs, src/System.Windows.Forms/src/PublicAPI.Unshipped.txt, src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/Application.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.Designer.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MultipleControls.Designer.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MultipleControls.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Program.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ApplicationTests.cs
Resolves #3001
The default font has been updated in .NET Core 3.0 (#656) and documented. However for some users who built their apps in pixel-perfect manner this change has proved to be a significant hurdle in migrating their apps to .NET.
Allow setting application-wide default font in a similar manner we set high dpi or visual styles:
```diff
class Program
{
[STAThread]
static void Main()
{
Application.SetHighDpiMode(HighDpiMode.SystemAware);
Application.EnableVisualStyles();
Application.SetCompatibleTextRenderingDefault(false);
+       Application.SetDefaultFont(new Font(new FontFamily("Microsoft Sans Serif"), 8f));
Application.Run(new Form1());
}
}
```
* The application-wide default font can only be set before the first window is created by an application.
* The font will be scaled by …
=> Allow set application-wide default font

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutCellPaintEventArgs.cs
- Enable nullability in TableLayoutCellPaintEventArgs.
=> Enable nullability in TableLayoutCellPaintEventArgs

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/CategoryGridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs
Fixes #4475 
Related  #4945 
GridEntry was using the constant defined for 96% DPI. Replaced it with the scaled for DPI property.
Property grid at runtime will not render as expected.
- Yes from .NET framework.
None.
=> Fixing GridEntry padding

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridTests.cs
Contributes to #4913
Note that analysis of #4913 is not complete, merging this PR before the issue is fully analysed is ok (this PR is self-contained) but should not close the issue until it is verified that all leaks have been fixed.
- Fix a GDI handle leak discovered in the investigation of #4913
- When a system colors change is detected, the ImageList is reconstructed without disposing the old ImageList. Previously this was not an issue because ImageLists were collected and released by GC, but due to a different issue (#3567) this regressed. This change makes the implementation more robust and less reliant on the GC. Even once #3567 is fixed for everyone, disposing the ImageList early instead of waiting for the GC is good practice.
- prevents a leak of GDI handles when using …
=> Fix PropertyGrid leaking ImageList

src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildEditUiaProvider.cs
- Removing unnecessary logs from a ComboBoxChildEditUiaProvider
- No
- No
- Minimal
- .NET Core SDK: 6.0.100-preview.3.21202.5
=> Removing unnecessary logs from a ComboBoxChildEditUiaProvider

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/OwnerDrawPropertyBag.cs
- Enable nullability in OwnerDrawPropertyBag.
=> Enable nullability in OwnerDrawPropertyBag

eng/Version.Details.xml, eng/Versions.props
`Microsoft.NETCore.Targets` and `System.Security.Cryptography.Cng` got removed (see https://github.com/dotnet/runtime/pull/52261, https://github.com/dotnet/runtime/pull/51853) and cause incoherent builds.
=> Coherency fixes of runtime dependencies

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellMouseEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellParsingEventArgs.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellValueEventArgs.cs
- Enable nullability in some DataGridViewCell EventArgs.
=> Enable nullability in some DataGridViewCell EventArgs

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/DpiChangedEventArgs.cs
- Enable nullability in DpiChangedEventArgs.
=> Enable nullability in DpiChangedEventArgs

src/System.Windows.Forms/src/Resources/SR.resx, src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemDetailsAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemListAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemTileAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListVIew.ListViewAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
Fixes #4748 
During the separating of `ListViewAccessibilityObject`, two ways of separating were considered: `View` and `ListViewGroup` presence. 
Unfortunately, it makes no sense to separate `ListViewAccessibilityObject` by `View`, since the class contains almost no code specific to any `View`.
A `ListViewAccessibilityObject`  has code specific to the presence or absence of `ListViewGroups`, but the display of a `ListViewGroup` depends on many factors:
`ShowGroups` property;
`VirtualMode` property;
`View` property;
`Groups` property;
`Visual styles`.
Keeping track of all of these factors will lead to the need to add changes that will be much more difficult to support than the current code. Therefore, it was decided to leave the current code for the `ListViewAccessibilityObject`.
When …
=> Separating ListViewItemAccessibleObject

src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarCellAccessibleObject.cs
Fixes #4977 
- Fix a logical typo
- A user can hear a correct cell header using Narrator
- Yes
- Minimal
- UI manual testing
- Using Narrator and Inspect
- .NET SDK Version: 6.0.100-preview.6.21277.2
=> Fixing ColumnHeader of a MonthCalendar date cell

src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/MonthCalendar.CalendarBodyAccessibleObjectTests.cs
Fixes #4992
- Change one letter in the test name. 
There was used the russian "C" letter instead of english one.
I used global search to find the rest possible places where we used russian "C", there is one place only.
- No
- No
- Minimal
- Searching "C" letters in all code
=> Fixing a unit test name typo

src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/BindingCompleteEventArgs.cs
- Enable nullability in BindingCompleteEventArgs.
=> Enable nullability in BindingCompleteEventArgs

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/FontExtensions.cs, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItem.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ApplicationTests.cs
Fixes #4978
- Preserve font styles when rescale default font
See https://github.com/dotnet/winforms/issues/4978
- manual
- unit tests
=> Preserve font styles when rescale default font

src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.AccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxCell.DataGridViewTextBoxCellAccessibleObject.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/DataGridViewAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTextBoxCell.DataGridViewTextBoxCellAccessibleObjectTests.cs
Fixes #4031 
- Change DataGridView accessible object control type to "Data grid"
- Change DataGridView TextBox cell accessible object control type to "DataItem"
- A user will see\hear the new values of control types 
- AccessibilityInsights won't throw errors about supporting TextPattern for a text cell if it is not in the editing mode
- No
- Minimal
- AI throws the error, that a Text must support the Text pattern, because it has the "edit" control type. But a TextBox cell has an edit field that already supports the Text pattern. And it's impossible to implement the Text pattern for the cell, because it's just a container for its edit field.
- The accessibility tree is changed. AI doesn't throw the error, because the cell is "data item" now, so it shouldn't support the Text pattern, but …
=> Changing control types of DataGridView and its TextBox cell

src/System.Windows.Forms/src/System/Windows/Forms/ButtonBase.cs, src/System.Windows.Forms/src/System/Windows/Forms/CheckBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/Label.cs, src/System.Windows.Forms/src/System/Windows/Forms/RadioButton.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripControlHost.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/WinFormsUtils.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/LabelTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RadioButtonTests.cs
Fixes #4639
- Created tests to Label and RadioButton
- Remove Enum Validator on class
- None
- No
- None
- Unit Tests created before change
- 
Version: 6.0.100-preview.2.21155.3
Commit: 1a9103db2d
OS Version: 10.0.19042
RID: win10-x64
Base Path: C:\Program Files\dotnet\sdk\6.0.100-preview.2.21155.3\
Version: 6.0.0-preview.2.21154.6
Commit: 3eaf1f316b
3.1.407 [C:\Program Files\dotnet\sdk]
5.0.104 [C:\Program Files\dotnet\sdk]
5.0.201 [C:\Program Files\dotnet\sdk]
6.0.100-preview.2.21155.3 [C:\Program Files\dotnet\sdk]
.NET runtimes installed:
Microsoft.AspNetCore.All 2.1.26 [C:\Program Files\dotnet\shared\Microsoft.AspNetCore.All] …
=> Replace EnumValidator - Unit Tests and Changing the Validator

src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.cs
Fixes #5087
* Do not render empty ListViewGroup subtitles, tasks and footers.
* Do not serialize empty ListViewGroup subtitles, tasks and footers.
- ListViewGroup will be rendered correctly
- An incorrect implementation in .NET 5.0
- Minimal
- Manual
=> Fix ListViewGroup rendering

Winforms.sln, src/Microsoft.VisualBasic.Forms/tests/UnitTests/Microsoft.VisualBasic.Forms.Tests.vbproj, src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.vb, src/System.Windows.Forms/src/PublicAPI.Unshipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs
Closes #4608
Add overloads that takes `Action` and `Func<T>` as a parameter:
* `IAsyncResult BeginInvoke(Action method)`
* `void Invoke(Action method)`
* `T Invoke<T>(Func<T> method)`
- manual
- unit tests for both C# and VB
=> Enhance Invoke and BeginInvoke signatures

eng/Version.Details.xml, global.json, src/System.Windows.Forms.Primitives/src/System.Windows.Forms.Primitives.csproj, src/System.Windows.Forms.Primitives/tests/TestUtilities/System.Windows.Forms.Primitives.TestUtilities.csproj, src/System.Windows.Forms/src/System.Windows.Forms.csproj, src/System.Windows.Forms/tests/TestUtilities/System.Windows.Forms.TestUtilities.csproj
Relates to https://github.com/dotnet/runtime/pull/54147
Relates to https://github.com/dotnet/windowsdesktop/pull/1747
=> Remove refs provided by Microsoft.NETCore.App.Ref targeting pack

src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/CantStartSingleInstanceException.vb, src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/NoStartupFormException.vb, src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/StartupEventArgs.vb, src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/StartupNextInstanceEventArgs.vb, src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/UnhandledExceptionEventArgs.vb, src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.WinFormsAppContext.vb, src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb
This PR cleans up WindowsFormsApplicationBase, which is the base for the Visual Basic Application Framework.
Most of the changes are purely formatting or moving classes to dedicated files.
There is one functional clean up in/for the method `MainFormLoadingDone`, where we used to simply spinning with a `DoEvents` to prevent `FormLoad` of the main form to complete as long as the splash screen is shown. That of course maxed out one processor core for the time being, which I did not like much. I implemented a different approach with an `AutoResetEvent` and a `TaskCompletionSource` which works equally well, but doesn't spin and so doesn't raise the processor's workload.
=> Clean up WindowsFormsApplicationBase

src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObjectTests.cs
Fixes #4198 
- Change ListView subitem control type to "Text"
It's necessary to avoid Text pattern issues.
An "edit" element must support Text pattern,
but a ListView item is just a continer for an edit field, that already supports Text pattern.
- A user will see\hear a new control type for subitems
- No
- Minimal
- A subitem control type is "edit". It must support Text patter, but it's impossible:
- A subitem control type is "text". It mustn't support Text patter:
- Unit tests
- Using Narrator, Inspect and AI
- .NET 6.0.0-preview.6.21276.13
=> Changing ListView subitem control type to "Text"

src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.AccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.DataGridViewEditingPanelAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxEditingControl.DataGridViewComboBoxEditingControlAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.DataGridViewTextBoxEditingControlAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListBox.AccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.PropertyGridAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/DropDownButton.DropDownButtonAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/StatusStrip.StatusStripAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.ToolStripAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItemAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemAccessibleObject.cs, src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/MainFormControlsTabOrder.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolStripTests.Designer.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolStripTests.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolStripTests.resx, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ControlAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewComboBoxEditingControlAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTextBoxEditingControl.DataGridViewTextBoxEditingControlAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/DropDownButton.DropDownButtonAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxControlAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripProgressBar.ToolStripProgressBarControl.ToolStripProgressBarControlAccessibleObjectTests.cs
Fixes #4835
Original bug: [1313197](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1313197?src=WorkItemMention&src-action=artifact_link)
- Add a test app for ToolStrips 
- Implement FragmentRoot and FragmentNavigate for all controls to return correct value if a control is part of a ToolStrip
- Remove duplicate accessibility instances of native controls (that don't support UIA) from an accessibility tree 
- Accessibility tools don't freeze when navigate through a ToolStrip with a ToolStripControlHost 
- Yes (from .NET Framework 4.7.2)
- Minimal
- An accessibility tool (eg. Inspect) freezes on a ToolStrip if it has a ToolStripControlHost:
- An accessibility tool (eg. Inspect) works correctly and see the correct accessibility tree:
- CTI
- Manual
- Unit tests
- Using Inspect and …
=> Fix infinite accessibility loop when using ToolStripControlHost 

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.PropertyGridViewAccessibleObject.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/PropertyGridView.PropertyGridViewAccessibleObjectTests.cs
Fixes #4861
This issue is reproducible because in some scenarios (e.g. disposing), `OwnerGrid` property can have `null` value. For properties `FragmentRoot` and `Name` we check a similar scenario, but the `FragmentNavigate` method and `RowCount` property don't have this check.
- Added missing check for null. 
**Note:**
I think there are possible scenarios where this bug might be reproducible in *.NET Core 5.0* and *.NET Core 6.0*. So I would suggest fixing this case in *.NET Core 3.1*, *.NET Core 5.0*, *.NET Core 6.0*
When closing a form with PropertyGrid, the exception is no longer throwed
- Yes
- Minimal 
- Unit tests 
- CTI team
- .NET Core SDK: 6.0.0-preview.6.21310.1
=> Fix NullRefException for case when user closes Form with hidden PropertyGrid

src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Dpi/DpiMessageHelper.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Dpi/FormTests.Dpi.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Dpi/ToolStripItemTests.Dpi.cs
Fixes #4872
ToolStripItems are components and have Font property. Components does not receive DPICHANGED messages and ToolstripItems doesn't carry parent-child relationship with owner to get scaled by parent/Container. For these reasons, they need to be explicitly updated for the font when Dpi changes. If font was not explicitly set, DefaultFont, that is scaled to current Dpi, will be applied.
=> Scaling ToolStripItem text in PmV2 mode.

src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
Fixes #
- Change all calls in GetButtonsInitInfo from Show() to Show(this) so that MainForm will be the parent for all opened forms.  This way, when MainForm is moved from a monitor at 100% scaling to a monitor at 150% scaling, all forms will open on this new monitor and help surface any HDPI issues.
- None except for improved testing.
- No
- None
- 
- 6.0.0-preview.7.21323.1
=> Change to Show(this) so forms open on MainForm's monitor

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiSelectRootGridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/SingleSelectRootGridEntry.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridTests.cs
Fixes #5143
The fix returns the previous logic that was broken in c5e6890.
The main reason of the regression is that `Flags`'s getter calls `TypeConverter`,
that tries to get non-initialized `_propertyInfo` field.
- Change several `Flags` to `_flags` 
- A user doesn't catch NRE anymore
- Yes, from c5e6890.
- MInimal
- There is NRE when setting `PropertyGrid.Enabled`:
- There is no exception, when setting `PropertyGrid.Enabled`
- Unit tests
- CTI
- .NET 6.0.0-preview.7.21319.2
=> Reworking `Flags` to `_flags` in GridEntry

src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
Fixes #5180
- The issue is reproduced because if `dispInfo-> item.pszText` has `0x0000000000000000` value than the `new string (dispInfo-> item.pszText)` expression returns an empty string, although `dispInfo-> item.pszText is null` expression returns `true`.
- Added a condition, if `dispInfo-> item.pszText is null` expression is `true`, then return null, otherwise use `new string (dispInfo-> item.pszText)` code.
**After fix:**
- Minimal
- CTI team
- .NET Core SDK 6.0.0-preview.6.21305.3
=> Fixing the issue with cancel editing in ListView, which led to the wrong "LabelEditEventArgs.Label" parameter

src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
Fixes #5180
- The issue is reproduced because if `dispInfo-> item.pszText` has `0x0000000000000000` value than the `new string (dispInfo-> item.pszText)` expression returns an empty string, although `dispInfo-> item.pszText is null` expression returns `true`.
- Added a condition, if `dispInfo-> item.pszText is null` expression is `true`, then return null, otherwise use `new string (dispInfo-> item.pszText)` code.
- Port from #5186 
It will now be possible again to determine whether a label edit operation was cancelled by a user by correctly returning `null` in `LabelEditEventArgs` for `AfterLabelEdit` event.
**After fix:**
- Minimal
- CTI team
- .NET Core SDK 6.0.0-preview.6.21305.3
=> Wrong `LabelEditEventArgs.Label` parameters when cancel editing in ListView (port to 5.0)

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/PropertyGridViewAccessibleObjectTests.cs
Fixes #4861
This issue is reproducible because in some scenarios (e.g. disposing), `OwnerGrid` property can have `null` value. For properties `FragmentRoot` and `Name` we check a similar scenario, but the `FragmentNavigate` method and `RowCount` property don't have this check.
- Added missing check for null. 
**Note:**
Ported from #5077
When closing a form with PropertyGrid, the exception is no longer throwed
- Yes
- Minimal 
- Unit tests 
- CTI team
- .NET Core SDK: 3.1.9
=> Fix NullRefException for case when user closes Form with hidden PropertyGrid (port to 3.1)

src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.cs
Fixes #5087
* Do not render empty ListViewGroup subtitles, tasks and footers.
* Do not serialize empty ListViewGroup subtitles, tasks and footers.
- ListViewGroup will be rendered correctly
- An incorrect implementation in .NET 5.0
- Minimal
- Manual
=> Fix ListViewGroup rendering (servicing)

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/PropertyGridViewAccessibleObjectTests.cs
Fixes #4861
This issue is reproducible because in some scenarios (e.g. disposing), `OwnerGrid` property can have `null` value. For properties `FragmentRoot` and `Name` we check a similar scenario, but the `FragmentNavigate` method and `RowCount` property don't have this check.
- Added missing check for null. 
**Note:**
Ported from #5077
When closing a form with PropertyGrid, the exception is no longer throwed
- Yes
- Minimal 
- Unit tests 
- CTI team
- .NET Core SDK: 5.0.7
=>  Fix NullRefException for case when user closes Form with hidden PropertyGrid (port to 5.0)

src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObjectTests.cs
Removed warning suppression
Placed Environment.ProccessId instead of value
Added unit test for ProccessId property
Fixes #3982  
- Remove warning suppression
- Place `Environment.ProccessId` instead of value
- No
- No
- No
- Inspect
- Unit test
=> Fix issue 3982 "Use Environment.ProccessId"

src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildNativeWindow.cs, src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ObjectCollection.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
Fixes #5154
The previous implementation led to NRE, if a user set a custom accessible object for ComboBox via overriden CreateAccessibilityInstance
- Add an additional check of a ComboBox accessible object type 
- A user won't catch NRE when using a custom accessible object for a ComboBox
- Yes
- Minimal
- There is NRE when adding an item to a custom ComboBox
- There is no NRE
- Unit tests
- CTI
- .NET 6.0.0-preview.7.21319.2
=> Reworking ComboBox accessible object cast checks

src/System.Windows.Forms/src/System/Windows/Forms/Label.cs
Fixes #5196
- Ported fix for .NET Framework 4.8 ([changeset](http://codeflow/extensions/launcher.html?server=https%3a%2f%2fdevdiv.visualstudio.com%2f&projectId=0bdbc590-a062-4c3f-b0f6-9383f67865ee&reviewId=179226&projectshortname=DevDiv))
- [This code](https://github.com/dotnet/winforms/blob/3fd1247e1c3f0edd2af4dff5114db998f8b96803/src/System.Windows.Forms/src/System/Windows/Forms/Label.cs#L1308) was added to the .NET Framework, but later removed due to an ([792810](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/792810)) issue. Unfortunately, this line remains in the .NET Core 3.1 and next versions, so we see this bug. 
- Minimal
- Manually
- CTI team
Microsoft Windows [Version 10.0.19041.388]
.NET Core SDK: 6.0.0-preview.7.21352.2
=> Fixing wrong color for label in high contrast mode

src/System.Windows.Forms/src/System/Windows/Forms/Label.cs
Fixes #5196
- Ported fix for .NET Framework 4.8 ([changeset](http://codeflow/extensions/launcher.html?server=https%3a%2f%2fdevdiv.visualstudio.com%2f&projectId=0bdbc590-a062-4c3f-b0f6-9383f67865ee&reviewId=179226&projectshortname=DevDiv))
- [This code](https://github.com/dotnet/winforms/blob/3fd1247e1c3f0edd2af4dff5114db998f8b96803/src/System.Windows.Forms/src/System/Windows/Forms/Label.cs#L1308) was added to the .NET Framework, but later removed due to an ([792810](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/792810)) issue. Unfortunately, this line remains in the .NET Core 3.1 and next versions, so we see this bug. 
- Minimal
- Manually
- CTI team
Microsoft Windows [Version 10.0.19041.388]
.NET Core SDK: 6.0.0-preview.7.21352.2
=> Fixing wrong color for label in high contrast mode (port to 3.1)

src/System.Windows.Forms/src/System/Windows/Forms/Label.cs
Fixes #5196
- Ported fix for .NET Framework 4.8 ([changeset](http://codeflow/extensions/launcher.html?server=https%3a%2f%2fdevdiv.visualstudio.com%2f&projectId=0bdbc590-a062-4c3f-b0f6-9383f67865ee&reviewId=179226&projectshortname=DevDiv))
- [This code](https://github.com/dotnet/winforms/blob/3fd1247e1c3f0edd2af4dff5114db998f8b96803/src/System.Windows.Forms/src/System/Windows/Forms/Label.cs#L1308) was added to the .NET Framework, but later removed due to an ([792810](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/792810)) issue. Unfortunately, this line remains in the .NET Core 3.1 and next versions, so we see this bug. 
- Minimal
- Manually
- CTI team
Microsoft Windows [Version 10.0.19041.388]
.NET Core SDK: 6.0.0-preview.7.21352.2
=> Fixing wrong color for label in high contrast mode (port to 5.0)

pkg/Microsoft.Private.Winforms/Microsoft.Private.Winforms.csproj, pkg/Microsoft.Private.Winforms/sdk/dotnet-wpf/System.Windows.Forms.GlobalUsings.props, pkg/Microsoft.Private.Winforms/sdk/dotnet-wpf/System.Windows.Forms.GlobalUsings.targets
Resolves #5074 
Relates to https://github.com/dotnet/sdk/pull/18459
Global usings can be disabled in the following way:
* `DisableImplicitNamespaceImports` disables \*ALL\* global usings
* `DisableImplicitNamespaceImports_WindowsForms` disables Windows Forms specific global usings
It is possible to add additional usings via:
```xml
<ItemGroup>
<Import Add="MyCompany.Super.CoolStuff" />
</ItemGroup>
```
It is possible to remove selected usings 
```xml
<ItemGroup>
<Import Remove="System.Drawing" />
</ItemGroup>
```
Referenced through the Microsoft.NET.Sdk.WindowsDesktop.props this leads to the following:
- Manually locally modifying the installed SDK
- Building winforms -> wpf -> windowsdesktop
=> Add global usings and plumb through the WPF

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlCommandSet.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.ComponentManager.cs, src/System.Windows.Forms/src/System/Windows/Forms/Application.cs, src/System.Windows.Forms/src/System/Windows/Forms/ColumnHeader.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/Cursor.cs, src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxEditingControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/FontDialog.cs, src/System.Windows.Forms/src/System/Windows/Forms/Form.cs, src/System.Windows.Forms/src/System/Windows/Forms/InputLanguage.cs, src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewNativeItemCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/MaskedTextBox.cs, src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.cs, src/System.Windows.Forms/src/System/Windows/Forms/NotifyIcon.cs, src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/Screen.cs, src/System.Windows.Forms/src/System/Windows/Forms/SplitContainer.cs, src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.ModalMenuFilter.cs, src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs, src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/MonthCalendar.MonthCalendarChildAccessibleObjectTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComponentModel/Com2Interop/COM2PictureConverterTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTextBoxEditingControlTests.cs
Fixes #
- Rework cast using `(int)` and `ToInt32` constructions to `PARAM.ToInt` method
- No
- No
- Minimal
=> Rework casting IntPtr by using ParamToInt

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Properties.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripButtonTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripControlHostTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripDropDownItemTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripMenuItemTests.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripSeparatorTests.cs
Fixes #5223 (partially)
- The `SystemInformation.MenuAccessKeyUnderlined` property used as expected value for checking `Control.ShowKeyboardCues` and `Control.ShowFocusCues` default values for newly created controls in unit tests.
- None (unit-tests)
- No
- None
- Run unit tests on PC with the "Underline access keys when available" option enabled and disabled.
- .NET 6.0.100-preview.6.21317.3
- Windows 10 settings - "Ease of Access" -> "Keyboard" -> "Change how keybord shortcuts work"
=> Prevented unit tests failures (#5223)

.editorconfig, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.GridEntryAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/HotCommands.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/ImmutablePropertyDescriptorGridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MergePropertyDescriptor.MergedAttributeCollection.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MergePropertyDescriptor.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiPropertyDescriptorGridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiSelectRootGridEntry.PDComparer.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiSelectRootGridEntry.PropertyMerger.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiSelectRootGridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertiesTab.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObject.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridCommands.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/SingleSelectRootGridEntry.cs
Clean code to get to 0 messages in the Error List pane for most PropertyGrid related classes.
- Tweak var rules to only complain when using var for intrinsics
- Clean up comments
=> Clean messages for PropertyGrid classes

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Properties.cs
Fixes #5223 (completely)
- The `SystemInformation.MenuAccessKeyUnderlined` property used as expected value for checking `Control.ShowKeyboardCues` and `Control.ShowFocusCues` default values for newly created controls in unit tests.
- None (unit-tests)
- No
- None
- Run unit tests on PC with the "Underline access keys when available" option enabled and disabled.
- .NET 6.0.100-preview.6.21317.3
- Windows 10 settings - "Ease of Access" -> "Keyboard" -> "Change how keybord shortcuts work"
=> Prevented unit tests failures [part 2] (#5223)

docs/debugging.md
=> Add missing assembly required to use local WinForms build

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.Flags.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/DocComment.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.ErrorState.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.GridPositionData.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/PropertyGridToolStripButton.PropertyGridToolStripButtonAccessibleObjectTests.cs
Mostly changing the local and member variables to be more in line with current styles. Some general code cleanup as well.
This doesn't fix everything, but is another step towards readability.
=> Clean up PropertyGrid/View variable names

src/System.Windows.Forms.Primitives/src/Resources/SR.resx, src/System.Windows.Forms.Primitives/src/Resources/xlf/SR.cs.xlf, src/System.Windows.Forms.Primitives/src/Resources/xlf/SR.de.xlf, src/System.Windows.Forms.Primitives/src/Resources/xlf/SR.es.xlf, src/System.Windows.Forms.Primitives/src/Resources/xlf/SR.fr.xlf, src/System.Windows.Forms.Primitives/src/Resources/xlf/SR.it.xlf, src/System.Windows.Forms.Primitives/src/Resources/xlf/SR.ja.xlf, src/System.Windows.Forms.Primitives/src/Resources/xlf/SR.ko.xlf, src/System.Windows.Forms.Primitives/src/Resources/xlf/SR.pl.xlf, src/System.Windows.Forms.Primitives/src/Resources/xlf/SR.pt-BR.xlf, src/System.Windows.Forms.Primitives/src/Resources/xlf/SR.ru.xlf, src/System.Windows.Forms.Primitives/src/Resources/xlf/SR.tr.xlf, src/System.Windows.Forms.Primitives/src/Resources/xlf/SR.zh-Hans.xlf, src/System.Windows.Forms.Primitives/src/Resources/xlf/SR.zh-Hant.xlf, src/System.Windows.Forms.Primitives/src/System/Windows/Forms/ServiceExtensions.cs, src/System.Windows.Forms/src/PublicAPI.Shipped.txt, src/System.Windows.Forms/src/System/Windows/Forms/Control.Annotated.cs, src/System.Windows.Forms/src/System/Windows/Forms/Control.cs, src/System.Windows.Forms/src/System/Windows/Forms/Design/EventsTab.cs, src/System.Windows.Forms/src/System/Windows/Forms/Design/PropertyTab.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs, src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs, src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridTests.cs
Add ServiceProvider extensions from the designer code. For try methods allow for null provider. Add internal overloads to Control.
Annotate PropertyTab and use the new overloads in some of the PropertyGrid classes.
Handle unexpected/null ISite.
=> Add ServiceProvider extensions

src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.DirectionButtonAccessibleObject.cs, src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MultipleControls.Designer.cs, src/System.Windows.Forms/tests/UnitTests/AccessibleObjects/DirectionButtonAccessibleObjectTests.cs
- Overrided `DoDefaultAction` method in `DirectionButtonAccessibleObject` class
- Added init items list for domainUpDown1 placed on MultipleControls form
- The invoke action of `UpDownButtons` will be work correctly
- No
- Minimal
If you trigger the Invoke action, the value is not updated
You can see correct action result now
The `LegacyIAccessible.DefaultAction` property value is "Press" (not null) now:
- Manually
- Unit tests
- Accessibility tests
- Inspect
- .NET SDK:
Version:   6.0.0-preview.7.21358.2
=> Implementing invoke action of UpDownButton
