- docs/designer/readme.md
- src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs
> fixed a typo and a broken link

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/HtmlWindowCollection.cs
- Enable nullability in HtmlWindowCollection.
> Enable nullability in HtmlWindowCollection

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewItemCollection.cs
- Enable nullability in ListViewItemCollection.
> Enable nullability in ListViewItemCollection

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/MdiControlStrip.SystemMenuItem.cs
- src/System.Windows.Forms/src/System/Windows/Forms/MenuStrip.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.ToolStripAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItem.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropTargetManager.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripLabel.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.cs
- Enable nullability in remaining ToolStrip members.
> Enable nullability in remaining ToolStrip members

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ComboBoxDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TextBoxBaseDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripItemDesigner.cs
- Enable nullability in TextBoxBaseDesigner
> Enable nullability in TextBoxBaseDesigner

- src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/ApplicationServices/ApplicationBaseTests.cs
- src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/RecordTypes/EMREXTSELECTCLIPRGN.cs
- src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/RecordTypes/EMRPOLYPOLY16.cs
- src/System.Windows.Forms.Primitives/tests/TestUtilities/PlatformDetection.Windows.cs
- src/System.Windows.Forms.Primitives/tests/TestUtilities/SystemCOLORs.cs
- src/System.Windows.Forms.PrivateSourceGenerators/tests/UnitTests/EnumValidationTests.cs
- src/System.Windows.Forms/tests/AccessibilityTests/DataControls.cs
- src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/CustomControls/CustomButtonDesignerActionList.cs
- src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.cs
- src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/Program.cs
- src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DesignSurfaceExt/DesignSurfaceExt.cs
- src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DesignSurfaceExt/NameCreationServiceImp.cs
- src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DesignSurfaceExt/TabOrderHooker.cs
- src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/TestHelpers.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/RichTextBoxes.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/TaskDialogSamples.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/UserControls/UserControlWithObjectCollectionEditor.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Application.ParkingWindowTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/DesignerAttributeTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Layout/TableLayoutSettingsTypeConverterTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MessageTests.cs
> Use interpolated strings in test code

- eng/Versions.props
> Update branding to 6.0.16

- eng/Versions.props
> Update branding to 7.0.5

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ShortcutKeysEditor.ShortcutKeysUI.cs
- Enable nullability in ShortcutKeysUI.
> Enable nullability in ShortcutKeysUI

- src/System.Windows.Forms/src/System/Windows/Forms/MDIControlStrip.cs
- Enable nullability in MdiControlStrip.
> Enable nullability in MdiControlStrip

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeMethodMap.cs
Contributes to #1107 
The first commit is just about nulls. I cleaned up the code a bit in the second commit, but I can revert if that's not welcome
> Enable nullability in CodeMethodMap

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.SplitButton.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DesignerActionGlyph.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripDropDownDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripKeyboardHandlingService.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripMenuItemDesigner.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignerActionServiceTests.cs
- Remove some unused variables.
> Remove some unused variables

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/RootContext.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/SerializeAbsoluteContext.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/StatementContext.cs
> Add nullability to RootContext, SerializeAbsoluteContext, StatementContext

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/MultilineStringEditor.cs
- Enable nullability in MultilineStringEditor.
> Enable nullability in MultilineStringEditor

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ExpressionContext.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ExpressionTable.cs
> Enable nullability in ExpressionContext and ExpressionTable

- src/System.Windows.Forms/tests/UnitTests/TextBoxBaseTests.cs
> Dispose TextBox in tests

- src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ArrayEditorTests.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/CollectionEditorTests.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/CollectionFormTests.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignerActionServiceTests.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignerHostTests.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/SiteNestedContainerTests.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/Drawing/Design/ToolboxItemTests.cs
> Dispose Component in tests

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.HorizontalRowManager.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.VerticalRowManager.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.cs
- Enable nullability in ToolStripPanelRow.
> Enable nullability in ToolStripPanelRow

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ListBindingHelper.cs
- Enable nullability in ListBindingHelper.
> Enable nullability in ListBindingHelper

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ExtenderProviderService.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/TypeDescriptorFilterService.cs
> Add nullability to ExtenderProviderService and TypeDescriptorFilterService

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ComponentCache.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ComponentCodeDomSerializer.cs
Contributes to #1107
I did a bit of cleanup again in the second commit
> Enable nullability in ComponentCache 

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionList.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionListCollection.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionListsChangedEventArgs.cs
> Add nullability annotations to DesignerActionList and DesignerActionListCollection

- src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripComboBox.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripContainer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripContentPanel.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDown.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownItem.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownMenu.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.ToolStripItemAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItem.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripMenuItem.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanelRow.ToolStripPanelRowControlCollection.ToolStripPanelCellToControlEnumerator.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSettingsManager.SettingsStub.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSettingsManager.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitStackLayout.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripStatusLabelBorderSides.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripTextBox.cs
> Use interpolated strings in toolstrip-related code

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CodeMarkers.cs
> Enable nullability in CodeMarkers

- src/System.Drawing.Common/src/Interop/Windows/Shell32/Interop.SHGetStockIconInfo.cs
- src/System.Drawing.Common/src/System.Drawing.Common.csproj
- src/System.Drawing.Common/src/System/Drawing/GdiplusNative.cs
- src/System.Drawing.Common/src/System/Drawing/StockIconId.cs
- src/System.Drawing.Common/src/System/Drawing/StockIconOptions.cs
- src/System.Drawing.Common/src/System/Drawing/SystemIcons.cs
- src/System.Drawing.Common/tests/SystemIconsTests.cs
Fixes: #8802
I also manually saved the generated Icons from the new API to see that it behaves as expected (`Icon.Save()`).
> Add API to get Windows stock icons.

- src/System.Windows.Forms/tests/InteropTests/RichTextBoxTests.cs
Fixes #
fix comment typo in RichTextBoxTests.cs
None
- No
- merge conflict
> fix comment typo in RichTextBoxTests.cs

- eng/pipelines/build.yml
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/DataCollectionService.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ScreenshotService.cs
> Incorporate DataCollectionService from microsoft/vs-extension-testing

- src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/MainFormControlsTabOrder.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListBoxes.Designer.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListBoxes.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListBoxes.resx
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
Fixes #8904
- Added a new separate form for ListBox Control Test to the WinformsControlsTest application.
- This is an internal test. It has no impact on a customer experience.
- No
- Minimal
- Manual
- dotnet 8.0.100-preview.3.23165.5
> Added a new test for ListBox Control to the WinformsControlsTest

- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListBoxes.Designer.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListBoxes.cs
Fixes #8904 (some additional control tests)
- Additional test controls for the new ListBox test form introduced in #8916
- This is an internal test. It has no impact on a customer experience.
- No
- Minimal
- Manual
- dotnet 8.0.100-preview.3.23165.5
> Added additional new controls to test ListBox control in WinformsControlsTest.

- src/System.Windows.Forms/tests/UnitTests/ModuleInitializer.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs
> Do not reset cursor position during test discovery

- eng/Versions.props
> Update branding to 7.0.6

- eng/Versions.props
> Update branding to 6.0.17

- src/System.Drawing.Common/src/Interop/Windows/Gdi32/Interop.DEVMODE.cs
- src/System.Drawing.Common/src/Interop/Windows/User32/Interop.LOGFONT.cs
- src/System.Drawing.Common/src/System/Drawing/Brush.cs
- src/System.Drawing.Common/src/System/Drawing/Drawing2D/CustomLineCap.cs
- src/System.Drawing.Common/src/System/Drawing/Drawing2D/GraphicsPath.cs
- src/System.Drawing.Common/src/System/Drawing/Drawing2D/GraphicsPathIterator.cs
- src/System.Drawing.Common/src/System/Drawing/Drawing2D/SafeCustomLineCapHandle.cs
- src/System.Drawing.Common/src/System/Drawing/Graphics.cs
- src/System.Drawing.Common/src/System/Drawing/Icon.cs
- src/System.Drawing.Common/src/System/Drawing/Image.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/ImageAttributes.cs
- src/System.Drawing.Common/src/System/Drawing/Pen.cs
- src/System.Drawing.Common/src/System/Drawing/Printing/PrinterSettings.cs
- src/System.Drawing.Common/src/System/Drawing/Printing/PrinterUnitConvert.cs
- src/System.Drawing.Common/src/System/Drawing/Region.cs
- src/System.Drawing.Common/src/System/Drawing/StringFormat.cs
- src/System.Drawing.Common/src/misc/DbgUtil.cs
- src/System.Drawing.Common/src/misc/GDI/WindowsGraphics.cs
- src/System.Drawing.Common/tests/mono/System.Drawing/BitmapTests.cs
I'm not sure the newly added System.Drawing.Common project is in scope for #8203. If it is, I've addressed it here.
Note that I also touched some code inside `#if FINALIZATION_WATCH`, fixing some of it in the process
> Use interpolated strings in System.Drawing.Common

- src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj
> Remove inclusion of non-existent folder

- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs
This is an attempt to assert that a previous test has not left a keyboard or mouse key in a pressed state going into the test.
> Verify key state at the start of each test

- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Input/MouseSimulator.cs
Also updates the ToVirtualPoint algorithm according to the investigation in https://microsoft.visualstudio.com/Edge/_workitems/edit/23229357
> Bypass operating system settings for relative mouse movement

- src/System.Drawing.Common/src/System/Drawing/FontConverter.cs
- src/System.Drawing.Common/tests/System/Drawing/FontConverterTests.cs
When porting to Core the `InstanceDescriptor` conversion was simplified to work with only the values that were supported cross platform. This caused data loss on Windows when custom GDI options were present.
Now that `System.Drawing` is only supported on Windows, match the .NET Framework implementation.
Fixes #8838
> Fix FontConverter InstanceDescriptor conversion

- src/System.Drawing.Common/tests/BitmapTests.cs
- src/System.Drawing.Common/tests/GraphicsTests.cs
- src/System.Drawing.Common/tests/IconTests.cs
- src/System.Drawing.Common/tests/Printing/PageSettingsTests.cs
- src/System.Drawing.Common/tests/Printing/PrintDocumentTests.cs
- src/System.Drawing.Common/tests/Printing/PrinterSettingsTests.cs
- src/System.Drawing.Common/tests/ToolboxBitmapAttributeTests.cs
- src/System.Drawing.Common/tests/mono/System.Drawing.Imaging/BmpCodecTests.cs
- src/System.Drawing.Common/tests/mono/System.Drawing.Imaging/GifCodecTests.cs
- src/System.Drawing.Common/tests/mono/System.Drawing.Imaging/IconCodecTests.cs
- src/System.Drawing.Common/tests/mono/System.Drawing.Imaging/JpegCodecTests.cs
- src/System.Drawing.Common/tests/mono/System.Drawing.Imaging/TiffCodecTests.cs
- src/System.Drawing.Common/tests/mono/System.Drawing/BitmapTests.cs
- src/System.Drawing.Common/tests/mono/System.Drawing/GraphicsTests.cs
- src/System.Drawing.Common/tests/mono/System.Imaging/MetafileTest.cs
Also remove a .NET Framework specific code block.
> Update issue links to new URLs.

- src/System.Drawing.Common/src/System.Drawing.Common.csproj
- src/System.Drawing.Common/src/System/Drawing/Bitmap.cs
- src/System.Drawing.Common/src/System/Drawing/Graphics.cs
- src/System.Drawing.Common/src/System/Drawing/Image.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/CachedBitmap.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/EncoderParameter.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/EncoderParameterNative.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/EncoderParameterPrivate.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/EncoderParameters.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/EncoderParametersNative.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/EncoderParametersPrivate.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Metafile.cs
- src/System.Drawing.Common/src/System/Drawing/TextureBrush.cs
Was investigating whether there might be logic errors in the marshalling. I've typed the conversions more directly and removed the use of PtrToStructure for performance and avoiding unnecessary reflection.
> Clean up EncoderParameter code

- src/System.Drawing.Common/tests/Printing/PrintDocumentTests.cs
- src/System.Drawing.Common/tests/mono/System.Drawing/GraphicsTests.cs
- src/System.Drawing.Common/tests/mono/System.Imaging/MetafileTest.cs
Fixes #8203
NOTE: this fix will address update to string interpolation after System.Drawing.* is moved to Winforms.
- change/update string.Format to use string interpolation instead
- 
- 
- It should be none
- 
- No
- Minimal, as it only replace string.Format to use string interpolation instead
- No tests are added, as it is focusing on updating code to use string interpolation.
- 
- 
- 
```
C:\GITHUB-REPO\winforms>dotnet --info
Host:
Version:      7.0.5
Architecture: x64
Commit:       8042d61b17
5.0.416 [C:\Program Files\dotnet\sdk]
6.0.311 [C:\Program Files\dotnet\sdk]
7.0.203 [C:\Program Files\dotnet\sdk]
7.0.300-preview.23179.2 [C:\Program Files\dotnet\sdk]
.NET runtimes installed:
Microsoft.AspNetCore.App 3.1.32 [C:\Program …
```
> Update some System.Drawing.Common classes to use String interpolation where applicable

- .gitignore
- Winforms.sln
- src/System.Windows.Forms/tests/IntegrationTests/ScratchProject/Form1.Designer.cs
- src/System.Windows.Forms/tests/IntegrationTests/ScratchProject/Form1.cs
- src/System.Windows.Forms/tests/IntegrationTests/ScratchProject/Form1.resx
- src/System.Windows.Forms/tests/IntegrationTests/ScratchProject/Program.cs
- src/System.Windows.Forms/tests/IntegrationTests/ScratchProject/ScratchProject.csproj
- src/System.Windows.Forms/tests/IntegrationTests/ScratchProject/readme.txt
This is to simplify experimenting and looking at repros.
> Add a scratch project to the solution

- .github/fabricbot.json
- eng/Versions.props
> Branding and update bot

- src/System.Windows.Forms.Design/src/System/Drawing/Design/ColorEditor.ColorUI.ColorEditorTabControl.cs
- src/System.Windows.Forms.Design/src/System/Drawing/Design/ColorEditor.ColorUI.cs
- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/TabControl.TabPageCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TabPage.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.ControlCollectionTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControl.TabPageCollectionTests.cs
- Enable nullability in TabControl.
> Enable nullability in TabControl

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/MaskDescriptorTemplate.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/MaskDesignerDialog.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripKeyboardHandlingService.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripMenuItemDesigner.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/RefCountedCache.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ImageList.ImageCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripDropDownMenu.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitButton.cs
- Remove some unused variables and unnecessary assignments.
> Remove some unused variables and unnecessary assignments

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/Adorner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DesignerActionGlyph.cs
- Enable nullability in Adorner.
> Enable nullability in Adorner

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/BindingManagerBase.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyManager.cs
- Enable nullability in PropertyManager.
> Enable nullability in PropertyManager

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TextBoxDesigner.cs
- Enable nullability in TextBoxDesigner.
> Enable nullability in TextBoxDesigner

- src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserSiteBase.cs
- Enable nullability in WebBrowserSiteBase.
> Enable nullability in WebBrowserSiteBase

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SelectionUIService.ContainerSelectionUIItem.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SelectionUIService.SelectionUIItem.cs
- Enable nullability in ContainerSelectionUIItem and SelectionUIItem.
> Enable nullability in ContainerSelectionUIItem and SelectionUIItem

- src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.WebBrowserEvent.cs
- Enable nullability in WebBrowserEvent.
> Enable nullability in WebBrowserEvent

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupItemCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.IKeyboardToolTip.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemImageAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItemCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObjectTests.cs
- Enable nullability in some ListViewItem members.
> Enable nullability in some ListViewItem members

- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/BinaryFormatWriter.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/Support/BinaryFormatWriterScope.cs
Simplifies the code a little and ensures consistency.
> Add a scope for binary format writing

- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/BinaryFormatWriter.cs
Clean up WritePrimitive to be more efficient for expected cases and easier to read.
Also add static array for primitive member name. (Other non-static ones are expected to be rare.)
> Optimize and simplify WritePrimitive

- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
Control.ReflectParent holds onto the parent control so it can know if it needs to be recreated when the parent is recreated. Making this a WeakReference to allow the Parent to be collected if it isn't going to be reused.
While this fixes the rooting via ReflectParent, in testing the parent was still rooted by its ControlAccessibleObject.Owner reference's. It's COM callable wrapper was still ref counted. I don't see that we're doing anything obviously wrong with the interop there, but in any case it's sort of senseless to retain a ref to an unused Control. I'm exploring making the owner a WeakReference as well, but it is a pretty big change as we stash the handle in a number of derived classes.
> Fix rooting of ReflectParent

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
Auto generated form ApiCompatibility>mark-shipped.cmd
> Publish unshipped APIS for preview 5

- .github/fabricbot.json
- eng/Versions.props
> Update branding in main to Preview6

- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/BinaryFormatWriter.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/BinaryFormattedObject.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/BinaryFormattedObjectExtensions.cs
- src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/BinaryFormat/ArrayTests.cs
- src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/BinaryFormat/BinaryFormatWriterTests.cs
- src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/BinaryFormat/HashTableTests.cs
- src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/BinaryFormat/ListTests.cs
Ensure that the Try methods for BinaryFormat don't throw for unsupported data. Add some negative tests.
> Wrap binary format parse/write methods

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.cs
- Enable nullability in remaining ListViewItem members.
> Enable nullability in remaining ListViewItem members

- eng/Versions.props
> Update branding to 6.0.19

- eng/Versions.props
> Update branding to 7.0.8

- eng/pipelines/build.yml
> [Release/7.0] Disable tests on internal CI or ARM64.

- eng/Versions.props
- src/Microsoft.VisualBasic.Forms/tests/UnitTests/Microsoft.VisualBasic.Forms.Tests.vbproj
- src/Microsoft.VisualBasic/tests/UnitTests/Microsoft.VisualBasic.Tests.csproj
- src/System.Windows.Forms.Design/tests/UnitTests/System.Windows.Forms.Design.Tests.csproj
- src/System.Windows.Forms.Primitives/tests/UnitTests/System.Windows.Forms.Primitives.Tests.csproj
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/System.Windows.Forms.UI.IntegrationTests.csproj
- src/System.Windows.Forms/tests/InteropTests/System.Windows.Forms.Interop.Tests.csproj
- src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj
> Update to Xunit.StaFact 1.2.46-alpha

- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs
> Add Retry count.

- eng/pipelines/build.yml
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs
Disable UI tests in release branches while increasing retry count in main.
Will be ported to release branches.
> Disable UI tests in release branch.

- eng/pipelines/build.yml
Disable UI tests in release branches.
> port to release/7.0: Disable UI tests in release branches.

- eng/Versions.props
> Update intellisense version

- eng/Versions.props
> Update branding to 6.0.20

- eng/Versions.props
> Update branding to 7.0.9

- src/System.Windows.Forms/tests/AccessibilityTests/ContainerControls2.Designer.cs
- src/System.Windows.Forms/tests/AccessibilityTests/DialogControls.Designer.cs
- src/System.Windows.Forms/tests/AccessibilityTests/DialogControls.cs
- src/System.Windows.Forms/tests/AccessibilityTests/ToolStripContainer.Designer.cs
Fixes https://github.com/dotnet/winforms/issues/9273, https://github.com/dotnet/winforms/issues/9260, https://github.com/dotnet/winforms/issues/9229 by updating Accessibility app in this repo
https://github.com/dotnet/winforms/issues/9273: Update toolStripButton1 and toolStripSplitButton1 Text property
https://github.com/dotnet/winforms/issues/9260: Re-adjust the controls' TabOrder, and change Container's backColor in order to Button's focus visible
https://github.com/dotnet/winforms/issues/9229: Remove FontDialog as it's CommonDialog
> Update Accessibility app for GH issues: 9229, 9273, 9260

- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/WinformsControlsTest.csproj
> Fixes #9322

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ActiveDesignSurfaceChangedEventArgs.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignSurface.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignSurfaceCollection.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignSurfaceEvent.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignSurfaceManager.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignSurfaceServiceContainer.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerEventService.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ReferenceService.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DesignBehaviorsTests.cs
Contributes to https://github.com/dotnet/winforms/issues/8342
- Enable nullability in `DesignSurface`, `DesignSurfaceCollection`, `DesignSurfaceEventArgs`, `DesignSurfaceEventHandler`, `DesignSurfaceManager`, `DesignSurfaceServiceContainer`, `ReferenceService`, `DesignerEventService` and `ActiveDesignSurfaceChangedEventArgs`
> Enable nullability in DesignSurface related code

- .github/fabricbot.json
> Update fabricbot.json for preview7

- eng/Versions.props
> Update Versions.props for preview 7

- src/System.Windows.Forms/tests/AccessibilityTests/Accessibility_Core_App.csproj
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/WinformsControlsTest.csproj
This will make debugging more convenient
> add project reference to System.Drawing.Common to integration tests

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxChildNativeWindow.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.ComboBoxUiaTextProvider.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
- Enable nullability in ComboBox.
> Enable nullability in ComboBox

- src/System.Windows.Forms.Primitives/src/Interop/Mshtml/Interop.IDocHostUIHandler.cs
- src/System.Windows.Forms.Primitives/src/Interop/SHDocVw/Interop.DWebBrowserEvents2.cs
- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.WebBrowserEvent.cs
- src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.WebBrowserSite.cs
- Enable nullability in WebBrowserSite.
- Fix some annotations in WebBrowserEvent from https://github.com/dotnet/winforms/pull/9098.
> Enable nullability in WebBrowserSite and fix annotations in WebBrowserEvent

- Winforms.sln
- docs/designer/readme.md
Fixed solution links
Added link to the blog post about custom designers for OOP designer
> docs fixes

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ThreadMethodEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- Enable nullability in remaining Control members.
> Enable nullability in remaining Control members

- pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/readme.md
> updated templates location info

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/HtmlElementCollection.cs
- Enable nullability in HtmlElementCollection.
> Enable nullability in HtmlElementCollection

- src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/DemoConsole.csproj
> Added a reference to the Drawing project to the design console sample.

- eng/Versions.props
> Update branding to 6.0.21

- eng/Versions.props
> Update branding to 7.0.10

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ContainerControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
- src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.WebBrowserBaseNativeWindow.cs
- src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserBase.cs
- src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserContainer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserSiteBase.cs
- Enable nullability in WebBrowserBase.
> Enable nullability in WebBrowserBase

- src/System.Windows.Forms/src/System/Windows/Forms/PropertyManager.cs
- src/System.Windows.Forms/src/System/Windows/Forms/RelatedPropertyManager.cs
- Enable nullability in RelatedPropertyManager.
> Enable nullability in RelatedPropertyManager

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs
- src/System.Windows.Forms/src/System/Windows/Forms/UpDownBase.cs
- Enable nullability in remaining ToolTip members.
> Enable nullability in remaining ToolTip members

- src/System.Windows.Forms/src/System/Windows/Forms/HtmlShimManager.cs
- Enable nullability in HtmlShimManager.
> Enable nullability in HtmlShimManager

- src/System.Windows.Forms.Primitives/src/Interop/Mshtml/Interop.IDocHostUIHandler.cs
- src/System.Windows.Forms.Primitives/src/Interop/Mshtml/Interop.IWebBrowser2.cs
- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.WebBrowserEvent.cs
- src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.WebBrowserSite.cs
- src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.cs
- Enable nullability in WebBrowser.
> Enable nullability in WebBrowser

- src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
The `UIWindow` can be null, we need to check for that before trying to wrap it in an `AgileComPointer`. This was an oversight- we check to see if the object is null in the rest of the method. Also checking `pFrame` as it is possible we would fall out before trying to use it.
Also assert that the method succeeded for our own debugging purposes. Historically the result wasn't checked.
Lastly add a missing `AddRef()` and use `ThrowOnFailure()` instead of calling `Marshal` directly (for consistency).
> Fix ActiveXImpl.InPlaceActivate

- src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXResourceWriterTests.cs
Fixes #8295 
- Add test case for function "AddAlias" of the class "ResXResourceWriter"
- No 
- No
- Low
- Unit tests
- .Net 8.0.100-preview.7.23325.3
> Add test case for AddAlias of the class "ResXResourceWriter"

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/RichTextBox.cs
- Enable nullability in some RichTextBox members.
> Enable nullability in some RichTextBox members

- src/System.Windows.Forms/src/System/Windows/Forms/HtmlDocument.HTMLDocumentEvents2.cs
- Enable nullability in HTMLDocumentEvents2.
> Enable nullability in HTMLDocumentEvents2

- src/System.Windows.Forms/src/System/Windows/Forms/HtmlShim.cs
- Enable nullability in HtmlShim.
> Enable nullability in HtmlShim

- src/System.Drawing.Common/src/AssemblyRef.cs
- src/System.Drawing.Common/src/System.Drawing.Common.csproj
- src/System.Drawing.Common/src/System/Drawing/Bitmap.cs
- src/System.Drawing.Common/src/System/Drawing/ContentAlignment.cs
- src/System.Drawing.Common/src/System/Drawing/Drawing2D/LinearGradientMode.cs
- src/System.Drawing.Common/src/System/Drawing/Font.cs
- src/System.Drawing.Common/src/System/Drawing/FontStyle.cs
- src/System.Drawing.Common/src/System/Drawing/GraphicsUnit.cs
- src/System.Drawing.Common/src/System/Drawing/Icon.cs
- src/System.Drawing.Common/src/System/Drawing/Image.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Metafile.cs
- src/System.Drawing.Common/src/System/Drawing/Printing/InvalidPrinterException.Core.cs
Implements similar structure to `System.Windows.Forms` and `System.Windows.Forms.Design`.
> Add `AssemblyRef` to `System.Drawing.Common`

- src/System.Windows.Forms/src/System/Windows/Forms/HtmlWindow.HtmlWindowShim.cs
- Enable nullability in HtmlWindowShim.
> Enable nullability in HtmlWindowShim

- src/System.Windows.Forms/src/System/Windows/Forms/HtmlDocument.HtmlDocumentShim.cs
- src/System.Windows.Forms/src/System/Windows/Forms/HtmlShim.cs
- Enable nullability in HtmlDocumentShim.
> Enable nullability in HtmlDocumentShim

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs
- Enable nullability in some AxHost members.
> Enable nullability in some AxHost members

- src/System.Windows.Forms/src/System/Windows/Forms/HtmlElement.HtmlElementShim.cs
- Enable nullability in HtmlElementShim.
> Enable nullability in HtmlElementShim

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellLinkedList.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellLinkedListEnumerator.cs
- Enable nullability in DataGridViewCellLinkedList.
> Enable nullability in DataGridViewCellLinkedList

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
> Publish shipped APIs for Preview 7

- .github/fabricbot.json
- eng/Versions.props
> Branding for RC1

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripPanel.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSettingsManager.cs
- Enable nullability in some ToolStripManager members.
> Enable nullability in some ToolStripManager members

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripManager.cs
- Enable nullability in remaining ToolStripManager members.
> Enable nullability in remaining ToolStripManager members

- azure-pipelines.yml
Add new feature branch to CI pipeline.
> Add feature/9.0 branch to CI

- src/System.Windows.Forms/src/System/Windows/Forms/Cursor.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Cursors.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/WinformsControlsTest.csproj
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CursorsTests.cs
> Fix `Cursor.ToString()`

- src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/AnchorLayoutTests.cs
- Enable nullability in DefaultLayout.
> Enable nullability in DefaultLayout

- src/System.Windows.Forms/src/Resources/SR.resx
- src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
This change is ran through [pipeline ](https://dev.azure.com/dnceng/internal/_build/results?buildId=2230876&view=results) and results are validated with help of loc team.
Locbuild task isnot recognizing the `ll-CC` format either.
> Update loc resources for keyboard buttons text.

- src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.ContainerInfo.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutSettings.TableLayoutSettingsStub.cs
- Enable nullability in TableLayoutSettingsStub.
> Enable nullability in TableLayoutSettingsStub

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowCollection.RowArrayList.cs
- Enable nullability in RowArrayList.
> Enable nullability in RowArrayList

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewSelectedCellCollection.cs
- Enable nullability in DataGridViewSelectedCellCollection.
> Enable nullability in DataGridViewSelectedCellCollection

- src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
We were not adding a ref to the IOleClientSite pointer passed to SetClientSite, which was a mistake made when we moved this to directly utilizing COM pointers.
Fixes #9551
> Add ref to IOleClientSite in SetClientSite.

- src/System.Windows.Forms/src/System/Windows/Forms/FlowLayoutSettings.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Layout/FlowLayout.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutSettings.cs
- Enable nullability in FlowLayout.
> Enable nullability in FlowLayout

- src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
- simplified source code
- None
- No
- None
- I ran the tests
> Checking the dictionary once is enough

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripDesigner.cs
- src/System.Windows.Forms.Design/tests/UnitTests/ControlDesignerTests.cs
- src/System.Windows.Forms.Design/tests/UnitTests/ListViewDesignerTests.cs
- src/System.Windows.Forms.Design/tests/UnitTests/SplitContainerDesignerTests.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System.Windows.Forms.Design.Tests.csproj
- src/System.Windows.Forms.Design/tests/UnitTests/ToolStripDesignerTests.cs
Related to https://github.com/dotnet/winforms/issues/714
-  Add AssociatedComponents test of ControlDesigner ,ListViewDesigner ,SplitContainerDesigner ,ToolStripDesigner
- 
- Unit Tests
- 
- 8.0.0-preview.7.23364.11
> Add AssociatedComponents test of ControlDesigner ,ListViewDesigner ,SplitContainerDesigner ,ToolStripDesigner

- .editorconfig
- eng/Version.Details.xml
- eng/Versions.props
- global.json
- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FileNameEditor.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FolderNameEditor.FolderBrowser.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FolderNameEditor.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripDesigner.cs
- src/System.Windows.Forms.Design/tests/UnitTests/ControlDesignerTests.cs
- src/System.Windows.Forms.Design/tests/UnitTests/ListViewDesignerTests.cs
- src/System.Windows.Forms.Design/tests/UnitTests/SplitContainerDesignerTests.cs
- src/System.Windows.Forms.Design/tests/UnitTests/ToolStripDesignerTests.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/FlowLayoutSettings.cs
- src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Layout/FlowLayout.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutSettings.cs
> merge main into feature/9.0 branch

- eng/Versions.props
> Update branding to 6.0.22

- eng/Versions.props
> Update branding to 7.0.11

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/InheritanceService.cs
- Enable nullability in `InheritanceService`
> Enable nullability in InheritanceService

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/Drawing/Design/CursorEditor.CursorUI.cs
- src/System.Windows.Forms.Design/src/System/Drawing/Design/CursorEditor.cs
- Enable nullability in `CursorEditor`
> Enable nullability in CursorEditor

- eng/Version.Details.xml
- eng/Versions.props
- eng/common/templates/steps/source-build.yml
- global.json
- src/System.Drawing.Common/src/System/Drawing/DrawingCom.ComWrappers.cs
- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/Drawing/Design/ContentAlignmentEditor.cs
- src/System.Windows.Forms.Design/src/System/Drawing/Design/SelectionPanelBase.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DockEditor.cs
- src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs
- src/System.Windows.Forms.Primitives/src/System.Windows.Forms.Primitives.csproj
- src/System.Windows.Forms.Primitives/src/Windows/Win32/Foundation/BSTR.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/Foundation/ComScope.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.FillRect.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
Merge main into feature/9.0 branch
> Merge main into feature/9.0 branch - 8/4/2023

- src/System.Drawing.Common/src/NotSupported.cs
- src/System.Drawing.Common/src/System/Drawing/CharacterRange.cs
- src/System.Drawing.Common/src/System/Drawing/Font.cs
- src/System.Drawing.Common/src/System/Drawing/Interop/LOGFONT.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Message.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Padding.cs
- src/System.Windows.Forms/src/System/Windows/Forms/BindingMemberInfo.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs
- src/System.Windows.Forms/src/System/Windows/Forms/LinkArea.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutPanelCellPosition.cs
Fixes #9618
<details>
<summary>
API proposal
</summary>
```diff
namespace System.Drawing
{
public struct CharacterRange
{
-		public int First { get; set; }
+		public int First { readonly get; set; }
-		public int Length { get; set; }
+		public int Length { readonly get; set; }
-		public override bool Equals(object? obj);
+		public override readonly bool Equals(object? obj);
-		public bool Equals(CharacterRange other); //net7.0+
+		public readonly bool Equals(CharacterRange other); //net7.0+
-		public override int GetHashCode();
+		public override readonly int GetHashCode();
}
}
namespace System.Windows.Forms
{
-	public struct BindingMemberInfo
+	public readonly struct BindingMemberInfo
{
}
-	public struct ImeModeConversion
+	public readonly struct ImeModeConversion
{
}
public struct …
```
> Implement: Mark some properties and methods as `readonly`

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerException.cs
- Enable nullability in `CodeDomSerializerException`
> Enable nullability in CodeDomSerializerException

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ImageCollectionCodeDomSerializer.cs
- Enable nullability in `ImageListCodeDomSerializer`
> Enable nullability in ImageListCodeDomSerializer

- src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyStore.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStrip.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FormTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyStoreTests.cs
> Fix `Form.Dispose` `NullReferenceException`

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/BorderSidesEditor.BorderSidesEditorUI.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/BorderSidesEditor.cs
- Enable nullability in `BorderSidesEditor`
- Fix field names in `BorderSidesEditorUI`
> Enable nullability in BorderSidesEditor

- eng/Version.Details.xml
- eng/Versions.props
- global.json
- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/LoadedEventArgs.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/BorderSidesEditor.BorderSidesEditorUI.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/BorderSidesEditor.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ToolStripSplitStackLayout.cs
Merge main into feature/9.0 branch
> Merge main into feature/9.0 branch - 8/10/2023 

- src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/BinaryFormat/BinaryFormattedObjectTests.cs
Hi,
I just remove a useless semicolon from this file.
Good Luck
> remove useless semicolon

- eng/Version.Details.xml
- eng/Versions.props
- global.json
- src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/BinaryFormat/BinaryFormattedObjectTests.cs
Merge main into feature/9.0 branch
> Merge main into feature/9.0 branch - 8/14/2023

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
> Published unpublished API - run .\eng\ApiCompatibility\mark-shipped.cmd.

- eng/Versions.props
> Update release/8.0 to have pre-release iteration 2, pre-release label rc

- src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FormTests.cs
> Ensure Form Doesn't Prevent Shutdown (#9745)

- src/System.Windows.Forms.Primitives/src/NativeMethods.txt
- src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.PrintPreviewControlAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Printing/PrintPreviewControl.PrintPreviewControlAccessibilityObjectTests.cs
Fixes #9584
- 
- Add scroll pattern support
- 
- Yes 
- Minimal 
- 
-  Manually 
- 
.Net 8.0.0-rc.1.23404.1
> fix bug PrintPreviewControl lacks UI Automation Scroll pattern support

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/BinaryEditor.BinaryUI.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/BinaryEditor.cs
- Enable nullability in `BinaryEditor`
> Enable nullability in BinaryEditor

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/MaskDescriptor.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/MaskDescriptorComparer.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/MaskDescriptorTemplate.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/MaskDesignerDialog.cs
- Enable nullability in `MaskDescriptor`
> Enable nullability in MaskDescriptor

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/AnchorEditor.AnchorUI.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/AnchorEditor.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/AnchorEditorTests.cs
- Enable nullability in `AnchorEditor`
- Fix field names
- Remove unused field in `AnchorEditor.AnchorUI`
Each change is its own commit.
> Enable nullability in AnchorEditor

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/BasicDesignerLoader.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.ModifierConverter.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.ModifiersExtenderProvider.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.ModifiersInheritedExtenderProvider.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.cs
- src/System.Windows.Forms.Primitives/src/System/ComponentModel/MemberDescriptorExtensions.cs
- src/System.Windows.Forms.Primitives/src/System/ComponentModel/TypeDescriptorHelper.cs
- Enable nullability in `BasicDesignerLoader`
- Enable nullability in `CodeDomDesignerLoader`
This includes some code cleanup, and consolidation between the two classes
> Enable nullability in BasicDesignerLoader and CodeDomDesignerLoader

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TreeViewActionList.cs
- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.PageSelector.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs
- Enable nullability in some TreeView members.
> Enable nullability in some TreeView members

- eng/Versions.props
> Update branding to 7.0.12

- eng/Versions.props
> Update branding to 6.0.23

- src/System.Drawing.Common/README.md
This fixes https://github.com/dotnet/winforms/issues/9729.
> Update System.Drawing.Common README.md

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
- Enable nullability in some DataGridView members.
> Enable nullability in some DataGridView members

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/AxImporter.IReferenceResolver.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/AxImporter.Options.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/AxImporter.cs
Investigating porting the implementation, cleaning up the stub code.
> Break out and annotate AxImporter

- src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb
- src/System.Drawing.Common/README.md
- src/System.Windows.Forms/src/System/Windows/Forms/BindableComponent.cs
Insertion PR for .NET 8 RC2 updates for the following PRs:
* #9844
* #9817
* #9799
> RC2 dual checkin for fixes in AppFramework, DataBinding, Readme-Update

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/EventBindingService.EventPropertyDescriptor.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/EventBindingService.cs
- Enable nullability in `EventBindingService`
> Enable nullability in EventBindingService

- src/System.Windows.Forms.Design/tests/UnitTests/Mocks/MockSite.cs
- src/System.Windows.Forms.Design/tests/UnitTests/ToolStripMenuItemDesignerTest.cs
Releate #721 
- Add new unit test for ToolStripMenuItemDesigner
- Unit Tests 
> Add new unit test for ToolStripMenuItemDesigner

- eng/Version.Details.xml
- eng/Versions.props
- eng/common/sdl/trim-assets-version.ps1
- global.json
> Merging internal commits for release/8.0

- src/System.Windows.Forms/src/System/Windows/Forms/BindingManagerBase.cs
- src/System.Windows.Forms/src/System/Windows/Forms/RelatedCurrencyManager.cs
- Enable nullability in RelatedCurrencyManager.
> Enable nullability in RelatedCurrencyManager

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/Binding.cs
- src/System.Windows.Forms/src/System/Windows/Forms/BindingContext.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Formatter.cs
- Enable nullability in some Binding members.
> Enable nullability in some Binding members

- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Password.Designer.cs
- Update the text of Label to make sure the text is consistent with the MaskedTextBox content
- The text of Label is consistent with the MaskedTextBox content.
- No
-Minimal
- Manual(WinformsControlsTest App)
> Make sure the text of Label is consistent with the MaskedTextBox content

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolderTests.cs
Related to #3136
- Add unit tests for PropertyGridView.DropDownHolder.cs
-  No
- Minimal
- Unit test
- .net 8.0.0-rc.1.23421.3
> Add unit test for PropertyGridView.DropDownHolder.cs

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewCellStyleBuilder.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewColumnCollectionDialog.cs
- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellStyle.cs
- Enable nullability in DataGridViewCellStyle.
> Enable nullability in DataGridViewCellStyle

- Directory.Build.targets
Fixes: https://dev.azure.com/dnceng/internal/_build/results?buildId=2264519&view=results. Detected during the .NET 8 Test build
> [release/8.0] Correct TargetingPackVersion and RuntimeFrameworkVersion

- eng/Versions.props
Update Intellisense Version in the release branch.
> Update Intellisense Version in Release branch

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
This reverts commit 50098e42aab4fb429ab9f0bf9d325e104c530479, reversing changes made to fbc4f9be38b2d694d42853988ebce3186c9f20ee.
> Revert "Merge pull request #9935 from dotnet/Publish_unpublished_APIs"

- .github/fabricbot.json
- eng/Versions.props
> Update branding to RTM

- Directory.Build.props
- Directory.Build.targets
- global.json
- src/System.Drawing.Common/src/System.Drawing.Common.csproj
Update SDK version in main
This is usually expected via Arcade update but given the branch stabilization work is ongoing, manually updating to unblock the flow of WinForms into Installer.
> Update SDK version

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ISelectionUIService.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SelectionUIService.HitTestInfo.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SelectionUIService.SelectionUIItem.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SelectionUIService.cs
It's the first step to annotate `ComponentTray`
- Enable nullability in `SelectionUIService`
> Enable nullability in SelectionUIService

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/AdornerCollection.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/GlyphCollection.cs
- Fix field names in `BehaviorServiceAdornerCollection`
- Enable nullability in `BehaviorServiceAdornerCollection`
- Enable nullability in `GlyphCollection`
> Enable nullability in BehaviorServiceAdornerCollection and GlyphCollection

- src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutPanel.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutSettings.TableLayoutSettingsStub.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutSettings.cs
- Enable nullability in TableLayout.
> Enable nullability in TableLayout

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
- Enable nullability in DataGridViewRow.
> Enable nullability in DataGridViewRow

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
- Enable nullability in some DataGridView.Methods members.
> Enable nullability in some DataGridView.Methods members

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
> 2 nullability PRs had collided resulting in a bad merge, fixing that.

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/PictureBox.cs
- Enable nullability in some PictureBox members.
> Enable nullability in some PictureBox members

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignBindingPicker.cs
- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeMouseClickEventArgs.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
- Enable nullability in remaining TreeView members.
> Enable nullability in remaining TreeView members

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewLinkCell.cs
- Enable nullability in DataGridViewLinkCell.
> Enable nullability in DataGridViewLinkCell

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowCollection.RowArrayList.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowCollection.RowList.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowCollection.cs
- Enable nullability in DataGridViewRowCollection.
> Enable nullability in DataGridViewRowCollection

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumn.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxColumn.cs
- Enable nullability in some DataGridViewColumn members.
> Enable nullability in some DataGridViewColumn members

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/Drawing/Design/ToolboxItem.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DocumentDesigner.AxToolboxItem.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.CfCodeToolboxItem.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripContainerDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripPanelDesigner.cs
- src/System.Windows.Forms.Primitives/src/System/ComponentModel/TypeDescriptorHelper.cs
- src/System.Windows.Forms.Primitives/src/System/ServiceExtensions.cs
- Enable nullability in `ToolboxItem` and derived classes
> Enable nullability in ToolboxItem and derived classes

- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.PropertyGridViewAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridInternal/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridInternal/PropertyGridView.DropDownHolder.DropDownHolderAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridInternal/PropertyGridView.GridViewListBox.GridViewListBoxAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PropertyGridInternal/PropertyGridView.GridViewTextBox.GridViewTextBoxAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/TestUtilities/PropertyGridInternal/SubPropertyGrid.cs
- Enable nullability in some PropertyGridView members.
> Enable nullability in some PropertyGridView members

- Directory.Build.targets
Fixes: https://dev.azure.com/dnceng/internal/_build/results?buildId=2264519&view=results. Detected during the .NET 8 Test build
> Correct RuntimeFrameworkVersion and TargetingPackVersion

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/BindingManagerBase.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComboBox.cs
- src/System.Windows.Forms/src/System/Windows/Forms/CurrencyManager.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListControl.cs
- Enable nullability in some CurrencyManager members.
> Enable nullability in some CurrencyManager members

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellCollection.cs
- Enable nullability in DataGridViewCellCollection.
> Enable nullability in DataGridViewCellCollection

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/MenuCommandService.cs
- Enable nullability in `MenuCommandService`
> Enable nullability in MenuCommandService

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
- Enable nullability in remaining DataGridView members.
> Enable nullability in remaining DataGridView members

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomLocalizationProvider.LanguageCultureInfoConverter.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomLocalizationProvider.LanguageExtenders.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomLocalizationProvider.cs
- src/System.Windows.Forms.Primitives/src/System/ComponentModel/Design/Serialization/DesignerSerializationManagerHelper.cs
- Enable nullability in `CodeDomLocalizationProvider`
- Replace `Hashtable`s with generic dictionaries (contributes to #8143)
> Enable nullability in CodeDomLocalizationProvider and clean it up

- .github/fabricbot.json
Configuring BOT to close  OLD draft PRs.
> Close OLD draft PRs.

- eng/Localize/LocProject.json
Following PR failed to update static LocProj.json while adding new resource file. Correcting it to unblock CI and get Localization triggered in main. 
https://github.com/dotnet/winforms/pull/9990
Failing CI @ https://dev.azure.com/dnceng/internal/_build/results?buildId=2280975&view=logs&j=c2111129-d6a3-58de-e667-00e5a0966c99&t=04624205-1088-500d-206a-392ceb108efa&l=15
@LeafShi1 as FYI.
> Update static LocProj.json wrt to PR 9990

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewImageColumn.cs
- Enable nullability in DataGridViewImageColumn.
> Enable nullability in DataGridViewImageColumn

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewButtonColumn.cs
- Enable nullability in DataGridViewButtonColumn.
> Enable nullability in DataGridViewButtonColumn

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/HtmlElement.HtmlElementShim.cs
- src/System.Windows.Forms/src/System/Windows/Forms/HtmlElement.cs
- Enable nullability in HtmlElement.
> Enable nullability in HtmlElement

- eng/Versions.props
> Update branding to 7.0.13

- eng/Versions.props
> Update branding to 6.0.24

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/HtmlDocument.cs
- src/System.Windows.Forms/src/System/Windows/Forms/HtmlWindow.cs
- Enable nullability in HtmlWindow.
> Enable nullability in HtmlWindow

- src/System.Windows.Forms/src/System/Windows/Forms/HtmlElement.HTMLElementEvents2.cs
- Enable nullability in HTMLElementEvents2.
> Enable nullability in HTMLElementEvents2

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.IKeyboardToolTip.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DesignBehaviorsTests.cs
- src/System.Windows.Forms/tests/UnitTests/SerializableTypesTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNode.TreeNodeAccessibleObjectTests.cs
- Enable nullability in some TreeNode members.
> Enable nullability in some TreeNode members

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxContainer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.ConnectionPointCookie.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.OleInterfaces.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
- Enable nullability in remaining AxHost members.
> Enable nullability in remaining AxHost members

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/Binding.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ControlBindingsCollection.cs
- Enable nullability in ControlBindingsCollection.
> Enable nullability in ControlBindingsCollection

- src/System.Windows.Forms/src/System/Windows/Forms/Layout/CommonProperties.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Layout/FlowLayout.ContainerProxy.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Layout/FlowLayout.ElementProxy.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Layout/FlowLayout.VerticalElementProxy.cs
- Enable nullability in ElementProxy.
> Enable nullability in ElementProxy

- eng/Versions.props
- src/System.Drawing.Common/tests/Drawing2D/GraphicsPathTests.cs
- src/System.Drawing.Common/tests/GlobalUsings.cs
- src/System.Drawing.Common/tests/Helpers.cs
- src/System.Drawing.Common/tests/System.Drawing.Common.Tests.csproj
- src/System.Windows.Forms.Design/tests/UnitTests/CodeDomHelpers.cs
- src/System.Windows.Forms.Design/tests/UnitTests/GlobalUsings.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System.Windows.Forms.Design.Tests.csproj
- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/EmbeddedResourceTests.cs
- src/System.Windows.Forms.Primitives/tests/TestUtilities/Extensions/AssertExtensions.cs
- src/System.Windows.Forms.Primitives/tests/TestUtilities/FluentAssertions/FluentAssertExtensions.cs
- src/System.Windows.Forms.Primitives/tests/TestUtilities/FluentAssertions/PointFAssertions.cs
- src/System.Windows.Forms.Primitives/tests/TestUtilities/FluentAssertions/RectangleFAssertions.cs
- src/System.Windows.Forms.Primitives/tests/TestUtilities/System.Windows.Forms.Primitives.TestUtilities.csproj
- src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/Oleaut32/VARIANTTests.cs
- src/System.Windows.Forms/tests/UnitTests/GlobalUsings.cs
- src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/EmbeddedResourceTests.cs
Cherry pick of two commits. Do NOT squash.
> XUnit upgrade

- eng/Version.Details.xml
- eng/Versions.props
- eng/common/sdk-task.ps1
- eng/common/tools.ps1
- global.json
> [main] Update dependencies from dotnet/arcade

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatControl.CustomFormatType.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatControl.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatStringDialog.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormatStringEditor.cs
- Enable nullability in `FormatStringEditor`
- Enable nullability in `FormatControl`
> Enable nullability in FormatStringEditor and FormatControl

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.PageSelector.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
- src/System.Windows.Forms/src/System/Windows/Forms/TreeNodeCollection.cs
- Enable nullability in remaining TreeNode members.
> Enable nullability in remaining TreeNode members

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewAddColumnDialog.cs
- src/System.Windows.Forms.Primitives/src/System/ServiceExtensions.cs
- Enhance nullable annotations in `DataGridViewColumnCollectionDialog`, removing almost all `!` in the process
> Enhance nullable annotations in DataGridViewAddColumnDialog

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/InheritedPropertyDescriptor.cs
- Enable nullability in `InheritedPropertyDescriptor`
> Enable nullability in InheritedPropertyDescriptor

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
- Enable nullability in some PropertyGrid members.
> Enable nullability in some PropertyGrid members

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/BaseContextMenuStrip.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TableLayoutPanelDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripContentPanelDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripItemDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripPanelDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripTemplateNode.cs
Related #1107 
- Enabled nullability for BaseContextmenuStrip
- No
- Minimal
- 
- .net 9.0.100-alpha.1.23464.17
> Add nullability to BaseContextmenuStrip

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewButtonColumn.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewImageColumn.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewLinkColumn.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxColumn.cs
- Enable nullability in DataGridViewLinkColumn.
> Enable nullability in DataGridViewLinkColumn

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxColumn.cs
- Enable nullability in DataGridViewCheckBoxColumn.
> Enable nullability in DataGridViewCheckBoxColumn

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.ComponentListCodeDomSerializer.cs
The bug was introduced in #9120
Fixes #10096
- I ran DemoConsole and verified manually that the bug no longer reproduces
> Fix a bug in CodeDomComponentSerializationService.CodeDomSerializationStore.ComponentListCodeDomSerializer

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnCollection.ColumnOrderComparer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnCollection.cs
- Enable nullability in some DataGridViewColumnCollection members.
> Enable nullability in some DataGridViewColumnCollection members

- eng/Versions.props
> Update branding to 6.0.25

- eng/Versions.props
> Update branding to 7.0.14

- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/OsVersion.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/InputLanguageTests.cs
Related: https://github.com/dotnet/winforms/issues/10150
> Add OS Condition for InputLanguageTests.InputLanguage_FromCulture_SupplementalInputLanguages_Expected

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewButtonColumn.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxColumn.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxColumn.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewImageColumn.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewLinkColumn.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxColumn.cs
- Enable nullability in DataGridViewComboBoxColumn.
> Enable nullability in DataGridViewComboBoxColumn

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/BindingSource.cs
- Enable nullability in some BindingSource members.
> Enable nullability in some BindingSource members

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/StatusCommandUI.cs
- src/System.Windows.Forms.Primitives/src/System/ComponentModel/MemberDescriptorExtensions.cs
- Enable nullability in `StatusCommandUI`
> Enable nullability in StatusCommandUI

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewButtonCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.DataGridViewCellAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewImageCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowHeaderCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxCell.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTopLeftHeaderCell.DataGridViewTopLeftHeaderCellAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar.CalendarCellAccessibleObject.cs
- Enable nullability in some DataGridViewCell members.
> Enable nullability in some DataGridViewCell members

- src/System.Windows.Forms/src/System/Windows/Forms/Binding.cs
- Enable nullability in remaining Binding members.
> Enable nullability in remaining Binding members

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DropSourceBehavior.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerUtils.cs
Also extracted from #9381
- Modernisation of `DesignerUtils`' code
- Change signature of methods `GenerateSnapShotWithBitBlt` and `GenerateSnapShotWithWM_PRINT` to better reflect their action
> DesignerUtils refactorings

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DropSourceBehavior.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/ToolStripPanelSelectionBehavior.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerUtils.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TableLayoutPanelDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripItemBehavior.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripMenuItemDesigner.cs
Extracted from #9381. Contributes to #8140
- Replace `ArrayList`s with `List`s in `DesignerUtils`
> Replace ArrayList with List in DesignerUtils

- eng/Versions.props
> Enable Stable Branding .NET 8 RTM

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/SelectionManager.cs
Extracted from #9367
- Modernise `SelectionManager`
- Annotate `SelectionManager` for NRT
> Enable nullability in SelectionManager

- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/SendInput.cs
- Removed unused GetForegroundWindow method.
> Removed unused GetForegroundWindow method

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/EditorServiceContext.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ImageListActionList.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ListControlUnboundActionList.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ListViewActionList.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/NotifyIconDesignerActionList.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/PictureBoxActionList.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/RichTextBoxActionList.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TreeViewActionList.cs
- Enable nullability in `EditorServiceContext`
> Enable nullability in EditorServiceContext

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/CurrencyManager.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ListControl.cs
- Enable nullability in remaining CurrencyManager members
> Enable nullability in remaining CurrencyManager members

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.ComponentDataObject.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.ComponentDataObjectWrapper.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SelectionUIHandler.cs
Another step towards the annotation of `ComponentTray`
- Enable nullability in `OleDragDropHandler`
- Enable nullability in `SelectionUIHandler`
- Remove unused fields and fix field names
> Enable nullability in OleDragDropHandler and SelectionUIHandler

- README.md
> Update readme to reflect issue template changes for Designer Issues

- eng/Versions.props
> Update branding to 6.0.26

- eng/Versions.props
> Update branding to 7.0.15

- eng/Versions.props
> Update branding to 8.0.1

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/ToolboxItemSnapLineBehavior.cs
> Replace `ArrayList` with `List<T>` in `ToolboxItemSnapLineBehavior`

- src/System.Drawing.Common/src/System/Drawing/Printing/PreviewPrintController.cs
> Convert `System.Drawing.Printing.PreviewPrintController` `_list` from `ArrayList` to `List<T>`

- eng/Versions.props
> Change to servicing branding

- azure-pipelines.yml
> [release/6.0] Remove Blob Feed

- eng/Versions.props
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationGeneratorTests.cs
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/Verifiers/CSharpIncrementalSourceGeneratorVerifier.cs
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/Verifiers/CSharpSourceGeneratorTest`1.cs
> [release/7.0] Upgrade MicrosoftCodeAnalysisPackagesVersion

- eng/Versions.props
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationGeneratorTests.cs
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/Verifiers/CSharpIncrementalSourceGeneratorVerifier.cs
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/Verifiers/CSharpSourceGeneratorTest`1.cs
Upgrades MicrosoftCodeAnalysisPackagesVersion and NewtonsoftJsonVersion for compliance
> [release/6.0] Upgrade Dependency

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxColumn.cs
Fixes #
- Changing if statement
-  Just Applying ternary if to make easier to read
- 0
- Yes / No
- 0
> Update DataGridViewCheckBoxColumn.cs for defaultNullValue check

- Winforms.sln
- src/System.Windows.Forms/tests/IntegrationTests/TrimTest/Form1.Designer.cs
- src/System.Windows.Forms/tests/IntegrationTests/TrimTest/Form1.cs
- src/System.Windows.Forms/tests/IntegrationTests/TrimTest/Form1.resx
- src/System.Windows.Forms/tests/IntegrationTests/TrimTest/Program.cs
- src/System.Windows.Forms/tests/IntegrationTests/TrimTest/TrimTest.csproj
- src/System.Windows.Forms/tests/IntegrationTests/TrimTest/readme.txt
Adds a simple sample project for testing trimming. It has a TextBox, SplitContainer, Button, and ComboBox. It accepts text drops into the TextBox and uses the ClipBoard class to copy text out of the ComboBox.
This is meant to be a starting point to assess and fix the most important warnings / issues with trimming.
@vitek-karas, @LakshanF, @sbomer, @agocke
> Add a project for testing trimming

- src/System.Drawing.Common/Directory.Build.props
- src/System.Drawing.Common/src/Interop/Windows/Gdi32/Interop.DEVMODE.cs
- src/System.Drawing.Common/src/Interop/Windows/User32/Interop.CreateIconFromResourceEx.cs
- src/System.Drawing.Common/src/Interop/Windows/User32/Interop.GetSystemMetrics.cs
- src/System.Drawing.Common/src/Interop/Windows/Winspool/Interop.EnumPrinters.cs
- src/System.Drawing.Common/src/System/Drawing/Brush.cs
- src/System.Drawing.Common/src/System/Drawing/Drawing2D/GraphicsPath.cs
- src/System.Drawing.Common/src/System/Drawing/Drawing2D/GraphicsPathIterator.cs
- src/System.Drawing.Common/src/System/Drawing/Font.cs
- src/System.Drawing.Common/src/System/Drawing/Graphics.cs
- src/System.Drawing.Common/src/System/Drawing/Image.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/ImageAttributes.cs
- src/System.Drawing.Common/src/System/Drawing/Pen.cs
- src/System.Drawing.Common/src/System/Drawing/Printing/PreviewPrintController.cs
- src/System.Drawing.Common/src/System/Drawing/Region.cs
- src/System.Drawing.Common/src/System/Drawing/StringFormat.cs
- src/System.Drawing.Common/src/System/Drawing/Text/PrivateFontCollection.cs
- src/System.Drawing.Common/src/misc/DbgUtil.cs
Contributes to #10285
- Activate CA2229, CA1812 and IDE0005 for System.Drawing.Common and fix related warnings
> Activate CA2229, CA1812 and IDE0005 for System.Drawing.Common

- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGrid.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/ImmutablePropertyDescriptorGridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiPropertyDescriptorGridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolder.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/AccessibleObjects/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
- Enable nullability in some PropertyDescriptorGridEntry members.
> Enable nullability in some PropertyDescriptorGridEntry members

- src/System.Drawing.Common/src/System/Drawing/Brushes.cs
- src/System.Drawing.Common/src/System/Drawing/Gdiplus.cs
- src/System.Drawing.Common/src/System/Drawing/Pens.cs
- src/System.Drawing.Common/src/System/Drawing/SystemBrushes.cs
- src/System.Drawing.Common/src/System/Drawing/SystemPens.cs
> Replace `Gdip` `HashTable` with `Dictionary<object, object>`

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/BindingSource.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BindingSourceTests.cs
- Enable nullability in remaining BindingSource members.
> Enable nullability in remaining BindingSource members

- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView/DataGridViewCellLinkedList.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView/DataGridViewIntLinkedList.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataGridView/DataGridViewIntLinkedListEnumerator.cs
- Enable nullability in DataGridViewIntLinkedList.
> Enable nullability in DataGridViewIntLinkedList

- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/RefCountedCache.cs
- src/System.Windows.Forms/src/System/Windows/Forms/AxHost/AxHost.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.FontHandleWrapper.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
Do some non-functional cleanup of font related code. Primarily trying to reduce nesting before I do further cleanup to cache Fonts and HFONTs consistently.
> Control font code cleanup

- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms/src/Resources/SR.resx
- src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripItem.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemTests.cs
related to [PR_8409](https://github.com/dotnet/winforms/pull/8409), [Issue_8548](https://github.com/dotnet/winforms/issues/8548)
Since the author of this [PR_8409](https://github.com/dotnet/winforms/pull/8409) seems to unable to continue the PR, so create a new PR here
> [API Proposal]: add ToolStripItem.SelectedChanged event #8548

- src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/MultiPropertyDescriptorGridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyDescriptorGridEntry.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridTests.cs
> Change `PropertyDescriptorGridEntry.NotifyParentsOfChanges` to fix wrong behavior

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertySort.cs
- Add `Flags` attribute to `PropertySort`
> Add Flags attribute to PropertySort

- eng/SourceBuild.props
> Add SourceBuild.props for the VMR build

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.ShadowPropertyCollection.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/BindingNavigatorDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/BindingSourceDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.ControlDesignerAccessibleObject.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewColumnDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/NotifyIconDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/PrintDialogDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SplitContainerDesigner.OrientationActionList.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SplitContainerDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SplitterPanelDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripContainerDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripPanelDesigner.cs
- src/System.Windows.Forms.Design/tests/UnitTests/ControlDesignerTests.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ComponentDesignerTests.cs
- Enable nullability in `ComponentDesigner`
> Enable nullability in ComponentDesigner

- src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripItem.cs
[Related PR](https://github.com/dotnet/winforms/pull/10321)
Add comments to newly added API to ToolStripItem
> Add comments to newly added API to ToolStripItem

- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ImageListTests.cs
> Stabilize ImageList_FinalizerReleasesNativeHandle_ReturnsExpected

- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/Buttons/CheckBox.CheckBoxAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListBoxes/CheckedListBox.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/CheckBox.CheckBoxAccessibleObjectTests.cs
Fixes #10516 
- 
- add ValuePattern to CheckBox
- 
-  No
- minimal 
- 
- manual 
- 
- 9.0.0-alpha.1.23623.1
> fix isssue 10516 [Accessibility] CheckBox control should support ValuePattern property

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.ShadowPropertyCollection.cs
Fixes #8231
Winforms Team still would like to do a bit of investigation on the VS side of things so we can make sure that we don't run into something unexpected.
> Fix descriptors cache in `ShadowPropertyCollection`

- eng/Versions.props
> Update branding to 8.0.2

- eng/Versions.props
> Update branding to 7.0.16

- eng/Versions.props
> Update branding to 6.0.27

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FlowLayoutPanelDesigner .cs
> Replace `ArrayList` usage in `FlowLayoutPanelDesigner` with List

- Directory.Build.props
- eng/FacadeAssemblies.props
- eng/Versions.props
- eng/pipelines/build.yml
Enable coverage for all source folders in the repository.
> Update coverlet, codecov, and ReportGenerator

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripPanelDesigner.cs
- Improve the NRT annotations of `ToolStripPanelDesigner`
- Fix a bug introduced in #9408 when calling the `Dispose` method twice (see #10585)
> Improve the NRT annotations of ToolStripPanelDesigner

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewColumnCollectionDialog.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewDesigner.cs
- Improve the NRT annotations of `DataGridViewDesigner`
- Fix a bug introduced in #9408 when calling the Dispose method twice (see #10585)
> Improve the NRT annotations of DataGridViewDesigner

- codecov.yml
Fixes # https://github.com/dotnet/winforms/pull/10476#discussion_r1446868536
- Remove  System.Design and Drawing from reporting.
> Remove  System.Design and Drawing from codecov.yml file

- src/System.Windows.Forms/src/System/Windows/Forms/Panels/Panel.PanelAccessibleObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/Panel.PanelAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/TabPage.TabPageAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/TextBoxBaseAccessibleObjectTests.cs
add and fix unit tests as a follow up pr [10561](https://github.com/dotnet/winforms/pull/10561)
> add and fix unit tests as a follow up pr 10561

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
sorted using edit > advanced > sort lines in VS after selecting all lines
> Sort PublicAPI.Shipped.txt Files

- .github/fabricbot.json
- eng/Versions.props
- Update milestone for fabricbot
- Update branding to .NET 9 Preview 2 for main
> Update main Branding to .NET 9 Preview 2

- src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/CategoryGridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/GridEntry.EventEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/GridEntry.cs
- Enable nullability in some GridEntry members.
> Enable nullability in some GridEntry members

- src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider/ErrorProvider.ControlItem.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider/ErrorProvider.ErrorWindow.cs
> Refactor `ErrorProvider` to remove `PropertyStore`

- src/System.Drawing.Common/src/packaging.targets
> Remove source build flags

- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/LabelDesignerTests.cs
> Add LabelDesigner tests

- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ComboBoxDesignerTests.cs
> Add ComboBoxDesigner tests

- src/System.Drawing.Common/src/System/Drawing/Printing/PrinterSettings.StringCollection.cs
The collection already implemented almost everything.
#10795 tracks formal API review
> Add IReadOnlyList<string> to PrinterSettings.StringCollection

- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/RadioButtonDesignerTests.cs
- Add RadioButtonDesigner tests.
> Add RadioButtonDesigner tests

- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ComboBoxDesignerTests.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/LabelDesignerTests.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/MaskedTextBoxDesignerTests.cs
- Add MaskedTextBoxDesigner tests.
> Add MaskedTextBoxDesigner tests

- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/TreeViewDesignerTests.cs
> Add TreeViewDesigner tests

- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/RichTextBoxDesignerTests.cs
- Add RichTextBoxDesigner tests.
> Add RichTextBoxDesigner tests

- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/PictureBoxDesignerTests.cs
- Add PictureBoxDesigner tests.
> Add PictureBoxDesigner tests

- src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/AxHost.PropertyBagStream.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/Control.ActiveXImpl.PropertyBagStream.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/Control_ActiveXControlInterfaces.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2IManagedPerPropertyBrowsingHandler.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2TypeInfoProcessor.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.ComboBoxUiaTextProvider.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridView.Methods.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListBoxes/CheckedListBox.CheckedListBoxItemAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListView/ListView.ListViewItemCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListView/ListViewItem.ListViewItemBaseAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/MonthCalendar/MonthCalendar.MonthCalendarAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGrid.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyGridView.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripHighContrastRenderer.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripItem.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripOverflowButton.ToolStripOverflowButtonAccessibleObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripPanelRow.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/WebBrowser/HtmlElementCollection.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/WebBrowser/WebBrowser.WebBrowserSite.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/WebBrowser/WebBrowserSiteBase.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataBinding/BindingManagerBase.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Dialogs/TaskDialog/TaskDialog.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Dialogs/TaskDialog/TaskDialogPage.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.LayoutInfo.cs
- src/System.Windows.Forms/src/System/Windows/Forms/MDI/MdiWindowListStrip.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.BitmapBinder.cs
Clean up some of what hits `dotnet format` on System.Windows.Forms.
> Some simple format cleanup

- eng/Versions.props
> Update branding to 8.0.3

- eng/Versions.props
> Update branding to 7.0.17

- eng/Versions.props
> Update branding to 6.0.28

- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/BlackSaturationEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/BlurEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/BrightnessContrastEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/ColorBalanceEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/ColorLookupTableEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/ColorMatrixEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/ContrastEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/DensityEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/ExposureEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/GrayScaleEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/HighlightEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/InvertEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/LevelsEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/MidtoneEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/SepiaEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/ShadowEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/SharpenEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/TintEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/VividEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/WhiteSaturationEffect.cs
- src/System.Drawing.Common/tests/System/Drawing/Imaging/Effects/EffectsTests.cs
I realized part of the fun is writing your own sets of effect settings so I've unsealed all of the classes and broken out the statics for Grayscale, Sepia, Invert, and Vivid. Improves discoverability and allows users to build their own "suite" of effects. (Rather than second guess which ones might be interesting I've unsealed them all.)
> Split out effects and unseal classes

- azure-pipelines-richnav.yml
It doesn't provide any benefit to run the richnav pipeline on PRs. We don't do this on other richnav pipelines.
> Disable PR triggers for azure-pipelines-richnav.yml

- eng/DotNetBuild.props
> Rename to DotNetBuild.props for unified-build

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ButtonBaseDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ComboBoxDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/LabelDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/MaskedTextBoxDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/PictureBoxDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/RadioButtonDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/RichTextBoxDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ScrollableControlDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TextBoxBaseDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TreeViewDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/UpDownBaseDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/UserControlDocumentDesigner.cs
- src/System.Windows.Forms.Primitives/src/System/ComponentModel/MemberDescriptorExtensions.cs
- src/System.Windows.Forms.Primitives/src/System/ComponentModel/PropertyDescriptorCollectionExtensions.cs
- src/System.Windows.Forms.Primitives/src/System/ComponentModel/PropertyDescriptorExtensions.cs
- Enable nullability in some Designer classes.
> Enable nullability in some Designer classes

- src/System.Private.Windows.Core/src/Windows/Win32/System/Com/WinFormsComWrappers.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Application.MsoThreadContext.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs
In prep for refactoring it to a flag-backed option.
> Move Mso code into a separate file

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DragAssistanceManager.Line.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DragAssistanceManager.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/ToolboxItemSnapLineBehavior.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CommandSet.cs
- Enable nullability in DragAssistanceManager.
> Enable nullability in DragAssistanceManager

- src/System.Windows.Forms/src/System/Windows/Forms/DataBinding/Binding.BindingStates.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataBinding/Binding.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataBinding/BindingSource.BindingSourceStates.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataBinding/BindingSource.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataBinding/CurrencyManager.CurrencyManagerStates.cs
- src/System.Windows.Forms/src/System/Windows/Forms/DataBinding/CurrencyManager.cs
> Refactor `BindingSource` and `CurrencyManager` to use flags enum field instead of individual boolean fields

- src/System.Windows.Forms.Primitives/src/Microsoft/Office/msoloop.cs
- src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.EnumThreadWindows.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Application.ComponentThreadContext.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Application.LightThreadContext.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Application.MarshallingControl.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadWindows.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.AutoCompleteDropDownFinder.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
- src/System.Windows.Forms/src/System/Windows/Forms/WindowsFormsSynchronizationContext.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Application.ParkingWindowTests.cs
A little follow-up cleanup for ThreadContext. Visibility cleanup and other minor tweaks.
> More ThreadContext related cleanup

- eng/Versions.props
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System.Windows.Forms.Analyzers.CSharp.Tests.csproj
- src/System.Windows.Forms.Analyzers/tests/UnitTests/System.Windows.Forms.Analyzers.Tests.csproj
> [release/6.0] Bump Nuget.Packaging and System.Data.SqlClient Versions

- eng/Versions.props
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System.Windows.Forms.Analyzers.CSharp.Tests.csproj
- src/System.Windows.Forms.Analyzers/tests/UnitTests/System.Windows.Forms.Analyzers.Tests.csproj
> Bump Nugetpackaging version

- src/System.Drawing.Common/src/System/Drawing/Bitmap.cs
- src/System.Drawing.Common/src/System/Drawing/Graphics.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/BlackSaturationCurveEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/BlurEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/BrightnessContrastEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/ColorBalanceEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/ColorCurveEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/ColorLookupTableEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/ColorMatrixEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/ContrastCurveEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/CurveChannel.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/DensityCurveEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/Effect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/ExposureCurveEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/GrayScaleEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/HighlightCurveEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/InvertEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/LevelsEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/MidtoneCurveEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/SepiaEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/ShadowCurveEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/SharpenEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/TintEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/VividEffect.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/WhiteSaturationCurveEffect.cs
- src/System.Drawing.Common/src/System/Drawing/PointerExtensions.cs
- src/System.Drawing.Common/tests/System/Drawing/Imaging/Effects/EffectsTests.cs
This updates Effects to match the approved API and removes [RequiresPreviewFeatures].
Fixes #8835
https://github.com/dotnet/winforms/issues/8835#issuecomment-1954987873
> Update Effects per API review

- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
1. Selected all in PublicAPI.Shipped.txt > Edit > Advanced > Sort Lines (1st commit, for ease of review)
2. ran  .\eng\ApiCompatibility\mark-shipped.cmd (no change)
> Publish APIs for .NET 9 Preview 2

- .github/policies/resourceManagement.yml
- eng/Versions.props
> Update Pre-Release Iteration and Resource Management Milestone

- eng/Versions.props
> Update branding to 8.0.4

- eng/Versions.props
> Update branding to 6.0.29

- eng/Versions.props
> Update branding to 7.0.18

- eng/Versions.props
- src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System.Windows.Forms.Analyzers.CSharp.Tests.csproj
- src/System.Windows.Forms.Analyzers/tests/UnitTests/System.Windows.Forms.Analyzers.Tests.csproj
> [release/7.0] Bump Nuget.Packaging and System.Data.SqlClient Versions

- .gitignore
> Ignore changes to VS Code settings

- azure-pipelines-PR.yml
For pipeline migration purposes
> Duplicate azure-pipelines.yml

- azure-pipelines-PR.yml
Fix to match release/6.0 version of azure-pipelines.yml
> [release/6.0] Fix azure-pipelines-pr.yml

- azure-pipelines-PR.yml
Fix to match release/7.0 version of azure-pipelines.yml
> [release/7.0] Fix azure-pipelines-pr.yml

- azure-pipelines-PR.yml
- eng/pipelines/build-PR.yml
- eng/pipelines/post-build-PR.yml
Duplicating YAML files per servicing guidance for 1ES template migration
> [release/7.0] Duplicate All Build YAML Files

- azure-pipelines-PR.yml
- eng/pipelines/build-PR.yml
- eng/pipelines/post-build-PR.yml
Duplicating YAML files per servicing guidance for 1ES template migration
> [release/6.0] Duplicate All Build YAML Files

- azure-pipelines-PR.yml
- eng/pipelines/build-PR.yml
- eng/pipelines/post-build-PR.yml
Duplicating YAML files per servicing guidance for 1ES template migration
> [release/8.0] Duplicate All Build YAML Files

- .github/policies/resourceManagement.yml
- eng/Versions.props
> Update Pre-Release Iteration and Resource Management Milestone to preview4

- eng/pipelines/build-PR.yml
PR YAMLs will get used in internal projects, so add back related conditionals that were removed in https://github.com/dotnet/winforms/pull/11025
> Re-add Conditionals for PR YAMLs

- .editorconfig
- src/Microsoft.VisualBasic.Forms/src/GlobalSuppressions.vb
- src/System.Drawing.Common/src/Special/NotSupported.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignSurface.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerHost.Site.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerHost.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.AdornerWindow.MouseHook.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignSurfaceTests.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignerHostTests.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/NullRecord.cs
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/NonNullCollection.cs
- src/System.Windows.Forms.Primitives/tests/TestUtilities/NoAssertContext.cs
- src/System.Windows.Forms/src/GlobalSuppressions.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripManager.ModalMenuFilter.HostedWindowsFormsMessageHook.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/Control.ControlAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/ToolStripDropDownMenu.ToolStripDropDownMenuAccessibleObjectTests.cs
Enable another batch of analyzers.
Make a pass cleaning up DesignerHost based on feedback from earlier PRs. (Modern patterns, duplicated docs not needed, etc.)
> Enable more analyzers

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerExtenders.NameExtenderProvider.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerExtenders.NameInheritedExtenderProvider.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerExtenders.cs
- Enable nullability in DesignerExtenders.
> Enable nullability in DesignerExtenders

- README.md
We got some very good and important feedback on the summit, and this is a first step (and draft) to get that feedback addressed in a quick way.
Please read and comment.
Thanks!
> WinForms Repo Readme update

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ColumnHeaderCollectionEditor.cs
- Enable nullability in ColumnHeaderCollectionEditor.
> Enable nullability in ColumnHeaderCollectionEditor

- eng/Versions.props
> Update branding to 7.0.19

- eng/Versions.props
> Update branding to 8.0.5

- azure-pipelines-PR.yml
- azure-pipelines.yml
- eng/pipelines/build-PR.yml
- eng/pipelines/build.yml
- eng/pipelines/post-build-PR.yml
- eng/pipelines/post-build.yml
Related: https://github.com/dotnet/winforms/issues/10895
Test Run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2414266&view=results
Steps:
- Ran the migration tool with release/7.0 branch
- changed necessary pools, templates, enable auto baselining
- Simplified conditions
> [release/7.0] Migrate to 1ES Pipeline Template

- azure-pipelines-PR.yml
- azure-pipelines.yml
- eng/pipelines/build-PR.yml
- eng/pipelines/build.yml
- eng/pipelines/post-build-PR.yml
- eng/pipelines/post-build.yml
Related: https://github.com/dotnet/winforms/issues/10895
Test Run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2408673&view=results
Steps:
- Ran the migration tool with release/6.0 branch
- changed necessary pools, templates, enable auto baselining
- Removed public vs internal conditionals
Note: this will need to wait until May servicing opens to merge.
> [release/6.0] Migrate to 1ES Pipeline Template

- azure-pipelines-PR.yml
- azure-pipelines.yml
- eng/pipelines/build-PR.yml
- eng/pipelines/build.yml
- eng/pipelines/post-build-PR.yml
- eng/pipelines/post-build.yml
Related: https://github.com/dotnet/winforms/issues/10895
Test run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2408671&view=results
Essentially backported changes from https://github.com/dotnet/winforms/pull/11025 and cross checked any differences between 8.0 and main
Note: this will need to wait until May servicing opens to merge.
> [release/8.0] Migrate to 1ES Pipeline Template

- Winforms.sln
- src/System.Windows.Forms/tests/IntegrationTests/TrimTestBinaryDeserialization/Form1.Designer.cs
- src/System.Windows.Forms/tests/IntegrationTests/TrimTestBinaryDeserialization/Form1.cs
- src/System.Windows.Forms/tests/IntegrationTests/TrimTestBinaryDeserialization/Form1.resx
- src/System.Windows.Forms/tests/IntegrationTests/TrimTestBinaryDeserialization/Program.cs
- src/System.Windows.Forms/tests/IntegrationTests/TrimTestBinaryDeserialization/TrimTestBinaryDeserialization.csproj
- src/System.Windows.Forms/tests/IntegrationTests/TrimTestBinaryDeserialization/readme.txt
Add new trim project that has `ImageList` with image to hit BinaryFormatter deserialization
cc: @LakshanF
> Add New Trim Project

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DragAssistanceManager.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.ChildWindowTarget.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SplitContainerDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripContainerDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripPanelDesigner.cs
- src/System.Windows.Forms.Design/tests/UnitTests/ControlDesignerTests.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ComboBoxDesignerTests.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/LabelDesignerTests.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/MaskedTextBoxDesignerTests.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/PictureBoxDesignerTests.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/RadioButtonDesignerTests.cs
- Enable nullability in some ControlDesigner members.
> Enable nullability in some ControlDesigner members

- src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/CategoryGridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/GridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/MultiPropertyDescriptorGridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyDescriptorGridEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyGridView.cs
- Enable nullability in remaining GridEntry members.
> Enable nullability in remaining GridEntry members

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomComponentSerializationState.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.ComponentListCodeDomSerializer.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.cs
- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationServiceTests.cs
- test.cmd
Related to https://github.com/dotnet/winforms/issues/10425
> Updated XML-doc comments around CodeDomComponentSerializationService

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.ChildSubClass.cs
- Enable nullability in ChildSubClass.
> Enable nullability in ChildSubClass

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DocumentDesigner.DocumentInheritanceService.cs
- Enable nullability in DocumentInheritanceService.
> Enable nullability in DocumentInheritanceService

- .config/1espt/PipelineAutobaseliningConfig.yml
- azure-pipelines.yml
Remove -pt images since they will be removed and add baselining file
Test run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2431665&view=results
> Remove -pt Images and Add Baselining File

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/ToolStripMenuItem.ToolStripMenuItemAccessibleObjectTests.cs
Related #10244
- Add unit tests for Controls that support InvokePattern
> Add unit test for Invoke pattern

- eng/Localize/LocProject.json
Fixes [build failure](https://dev.azure.com/dnceng/internal/_build/results?buildId=2434009&view=logs&j=c2111129-d6a3-58de-e667-00e5a0966c99&t=dbb91d6b-a8a9-52a4-d165-489e1fa4c9b8&l=233) due to mismatching LocProject.json
> Fix LocProject.json

- eng/Localize/LocProject.json
wrt https://github.com/dotnet/winforms/pull/11244
> Fix LocProject.json Whitespace

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
Sort the content of System.Windows.Forms.Design\src\PublicAPI.Shipped.txt by running .\eng\ApiCompatibility\mark-shipped.cmd
> Sort the content of System.Windows.Forms.Design\src\PublicAPI.Shipped.txt

- azure-pipelines.yml
release branches expected use `NetCore1ESPool-Svc-Internal` pool
Test run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2437258&view=results
> [release/9.0-preview4] Update Pipeline Pool

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/CheckBox.CheckBoxAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CheckBoxTests.cs
Related #https://github.com/dotnet/winforms/issues/10453
- Add unit tests for CheckBox to test its events: AppearanceChanged, DoubleClick, MouseDoubleClick, CheckedChanged and CheckedStateChanged.
- Add AccessibleObject unit test for CheckBox to test its methods: DefaultAction.
- Update AccessibleObject unit test for CheckBox to test its methods: State.
No
- No
Minimal
Unit Tests
> Add test coverage for checkbox

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerToolStripControlHost.cs
- Enable nullability in DesignerToolStripControlHost.
> Enable nullability in DesignerToolStripControlHost

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/MonthCalendar.CalendarHeaderAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/MonthCalendar.CalendarNextButtonAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs
- Add unit tests for MonthCalendar to test its properties: Bounds, HitTest
- Add unit tests for MonthCalendar to test its methods: RemoveAllAnnuallyBoldedDates
,RemoveAnnuallyBoldedDate, RemoveAllBoldedDates, RemoveBoldedDate, RemoveAllMonthlyBoldedDates, RemoveMonthlyBoldedDate
- None
-  No
-Minimal
- Unit tests
> Add code coverage for MonthCalendar

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ItemTypeToolStripMenuItem.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/StandardCommandToolStripMenuItem.cs
- Enable nullability in ItemTypeToolStripMenuItem and StandardCommandToolStripMenuItem.
> Enable nullability in ItemTypeToolStripMenuItem and StandardCommandToolStripMenuItem

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
Related #10453 
- Add unit tests for ComboBox to test its MaxLength property
- None
- No
- Minimal
- Unit tests
> Add code coverage for ComboBox

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/PbrsForward.cs
- Enable nullability in PbrsForward.
> Enable nullability in PbrsForward

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ParentControlDesigner.EscapeHandler.cs
- Enable nullability in EscapeHandler.
> Enable nullability in EscapeHandler

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.DesignerWindowTarget.cs
- Enable nullability in DesignerWindowTarget.
> Enable nullability in DesignerWindowTarget

- eng/Versions.props
> Update branding to 8.0.6

- eng/Versions.props
> Update branding to 6.0.31

- .config/guardian/SDL/.gdnbaselines
- azure-pipelines.yml
Remove -pt images since they will be removed and add baselining file.
Note we cannot auto baseline for release branches so manual baselining is done here
Test run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2431886&view=results
> [release/6.0] Remove -pt Images and Add Baselining File

- .config/guardian/SDL/.gdnbaselines
- azure-pipelines.yml
Remove -pt images since they will be removed and add baselining file. 
Note we cannot auto baseline for release branches so manual baselining is done here
Test run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2431834&view=results
> [release/8.0] Remove -pt Images and Add Baselining File

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/InheritanceUI.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/InheritanceUITests.cs
- Enable nullability in InheritanceUI.
> Enable nullability in InheritanceUI

- src/System.Windows.Forms.Design/src/System/ComponentModel/Design/MultilineStringEditor.OleCallback.cs
- Enable nullability in OleCallback.
> Enable nullability in OleCallback

- docs/testing.md
Small PR. PR #5122 moved the location of the `TestAccessor.cs` file. This PR adjusts sources to changes.
No much impact 
No
No risk
- 
- 
- 
-
> Update TestAccessor reference

- src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ByteViewerTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ContainerControlTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/ComponentEditorFormTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/ComponentEditorPageTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DomainUpDownTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FlowLayoutPanelTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MenuStripTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PanelTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/StatusStripTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabPageTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TableLayoutPanelTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripContentPanelTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripDropDownTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/UpDownBaseTests.cs
access ScrollStateAutoScrolling from parent class
> access ScrollStateAutoScrolling from parent class

- src/System.Windows.Forms/tests/UnitTests/MaskedTextBoxTests.cs
Related #10453
- Add unit tests for MaskedTextBox to test its properties: FormatProvider, Lines, MaskedTextProvider, MaxLength, ReadOnly, ResetOnSpace, SkipLiterals, SelectedText, TextAlign.
- Add unit tests for MaskedTextBox to test its events: MaskInputRejectedEvent, TextAlignChangedEvent.
- None
- No
- Minimal
- Unit tests
> Add test coverage for MaskedTextBox

- src/System.Private.Windows.Core/src/System/Windows/Forms/BinaryFormat/Deserializer/Deserializer.cs
- src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Common/EventOrderTests.cs
- src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Common/SerializationTest.cs
- src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Common/TestTypes/BinaryTreeNodeWithEvents.cs
- src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Common/TestTypes/BinaryTreeNodeWithEventsBase.cs
- src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Common/TestTypes/BinaryTreeNodeWithEventsISerializable.cs
- src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Common/TestTypes/ValueType.cs
- src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Common/TestTypes/ValueTypeBase.cs
- src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Common/TestTypes/ValueTypeISerializable.cs
- src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/FormattedObject/EventOrderTests.cs
- src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Formatter/EventOrderTests.cs
Take 11336 > SafePayloadReader
> Add Deserialization Event Order Tests (#11336)

- src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Common/EventOrderTests.cs
- src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Common/TestTypes/BinaryTreeNodeWithEvents.cs
- src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Common/TestTypes/BinaryTreeNodeWithEventsISerializable.cs
- src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Common/TestTypes/ObjectReferenceISerializable.cs
Merge main -> SafePayloadReader
> Merge Main to SafePayloadReader

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CheckedListBox.CheckedIndexCollectionTests.cs
- Add unit tests for CheckedListBox.CheckedIndexCollection to test its properties: Count, SyncRoot, IsSynchronized, IsFixedSize, IsReadOnly
- Add unit tests for CheckedListBox.CheckedIndexCollection to test its method: Add, Clear, Insert, Remove, RemoveAt, Contains, IndexOf, CopyTo, GetEnumerator
- None
- No
- Minimal
- Unit tests
> Add unit test for CheckedListBox.CheckedIndexCollection

- src/System.Private.Windows.Core/src/System/Windows/Forms/BinaryFormat/Deserializer/Deserializer.PendingUpdates.cs
- src/System.Private.Windows.Core/src/System/Windows/Forms/BinaryFormat/Deserializer/Deserializer.cs
Fix an issue where multiple objects that had dependencies completed by the same dependency would not complete successfully.
> Simplify handling of pending info

- src/System.Private.Windows.Core/src/System/Windows/Forms/BinaryFormat/Deserializer/Deserializer.PendingUpdates.cs
- src/System.Private.Windows.Core/src/System/Windows/Forms/BinaryFormat/Deserializer/Deserializer.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/TreeView.TreeViewAccessibleObjectTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CheckedListBox.CheckedIndexCollectionTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePickerTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeCollectionTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeConverterTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeTests.cs
> FI from main

- eng/Versions.props
> Update branding to 7.0.20

- eng/Versions.props
> Update branding to 8.0.7

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ImageListImage.cs
- Enable nullability in ImageListImage.
> Enable nullability in ImageListImage

- azure-pipelines-PR.yml
> Include feature/* branches for PR builds

- azure-pipelines-PR.yml
> Include feature/* branches for PR builds (#11478)

- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/InheritedPropertyDescriptorTestExtensions.cs
- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/InheritedPropertyDescriptorTests.cs
related to #714
add InheritedPropertyDescriptor unit tests
> add InheritedPropertyDescriptor unit tests

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs
- Add unit tests for below 10 events
> 1. AllowUserToAddRowsChanged
> 2. AllowUserToDeleteRowsChanged
> 3. AllowUserToOrderColumnsChanged
> 4. AllowUserToResizeColumnsChanged
> 5. AllowUserToResizeRowsChanged
> 6. AlternatingRowsDefaultCellStyleChanged
> 7. AutoGenerateColumnsChanged
> 8. BackgroundColorChanged
> 9. BorderStyleChanged
> 10. CellBorderStyleChanged
> Add unit test case for DataGridView 10 events

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePickerTests.cs
- Updated some test cases
> 1. CalendarFont
> 2. Checked
> 3. CustomFormat
> 4. MaximumDateTime
> 5. MinDate
> 6. Value
> Updated 6 unit test cases to fully coverage code lines in DateTimePicker

- eng/Versions.props
> Update branding to 8.0.8

- eng/Versions.props
> Update branding to 6.0.33

- NuGet.config
- azure-pipelines-PR.yml
- azure-pipelines.yml
- eng/Version.Details.xml
- eng/Versions.props
- eng/common/templates-official/job/source-build.yml
- eng/common/templates-official/job/source-index-stage1.yml
- eng/common/templates-official/jobs/source-build.yml
- eng/common/templates-official/post-build/common-variables.yml
- eng/common/templates-official/steps/enable-internal-runtimes.yml
- eng/common/templates-official/steps/get-delegation-sas.yml
- eng/common/templates-official/steps/get-federated-access-token.yml
- eng/common/templates/job/source-build.yml
- eng/common/templates/job/source-index-stage1.yml
- eng/common/templates/jobs/source-build.yml
- eng/common/templates/post-build/common-variables.yml
- eng/common/templates/steps/enable-internal-runtimes.yml
- eng/common/templates/steps/get-delegation-sas.yml
- eng/common/templates/steps/get-federated-access-token.yml
- eng/pipelines/build-PR.yml
- eng/pipelines/build.yml
- global.json
> [release/6.0] Switch to dSAS for internal runtimes

- NuGet.config
- azure-pipelines-PR.yml
- azure-pipelines.yml
- eng/Version.Details.xml
- eng/Versions.props
- eng/common/post-build/publish-using-darc.ps1
- eng/common/templates-official/job/publish-build-assets.yml
- eng/common/templates-official/job/source-build.yml
- eng/common/templates-official/job/source-index-stage1.yml
- eng/common/templates-official/jobs/source-build.yml
- eng/common/templates-official/post-build/post-build.yml
- eng/common/templates-official/steps/enable-internal-runtimes.yml
- eng/common/templates-official/steps/get-delegation-sas.yml
- eng/common/templates-official/steps/get-federated-access-token.yml
- eng/common/templates/job/publish-build-assets.yml
- eng/common/templates/job/source-build.yml
- eng/common/templates/job/source-index-stage1.yml
- eng/common/templates/jobs/source-build.yml
- eng/common/templates/post-build/post-build.yml
- eng/common/templates/post-build/setup-maestro-vars.yml
- eng/common/templates/steps/enable-internal-runtimes.yml
- eng/common/templates/steps/get-delegation-sas.yml
- eng/common/templates/steps/get-federated-access-token.yml
- eng/pipelines/build-PR.yml
- eng/pipelines/build.yml
- global.json
> [release/8.0] Switch to dSAS for internal runtimes

- .gitattributes
https://github.com/VerifyTests/Verify?tab=readme-ov-file#text-file-settings
> mark verified files as lf and utf8

- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
- src/System.Windows.Forms/src/Resources/SR.resx
- src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
- src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStrip.cs
Fixes #9288
Fixes #9240
Fixes #9277
Fixed #2544
Unsure on the attributes for the new property and whether or not an auto implemented property is okay.
I went with 'AllowClickThrough' because I thought it was more self documenting.
My development environment isn't fully setup yet so this was a very quick pr without any testing.
> Add Click Through behavior to `ToolStrip`/`MenuStrip`

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs
- Add unit tests for ListBox to test its properties: PreferredHeight, Text
- Add unit tests for ListBox to test its method: Refresh, SetSelected
> Add test coverage for ListBox

- docs/trimming/feature-switches.md
Creating a doc in the repo for the private feature switches that will be used in trimming
> Document private WinForms feature switches

- src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/CategoryGridEntry.cs
Found while investigating #11672
Class used to use `Hashtable` and we converted it to `Dictionary`. We didn't realize at the time that it could be `ConcurrentDictionary`.
> Refactor `CategoryGridEntry` to replace Dictionary and lock object with `ConcurrentDictionary`

- src/System.Private.Windows.Core/src/System/Private/Windows/Core/BinaryFormat/BinaryFormattedObjectExtensions.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.cs
- src/System.Windows.Forms/tests/ComDisabledTests/runtimeconfig.template.json
> declare feature switch as not static to be able to change it in tests.

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/GroupBoxTests.cs
- Add unit test for groupBox to test its property: DisplayRectangle
> Add unit tests for GroupBox

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
- Add unit tests for ListView to test its events: ColumnClick, GroupTaskLinkClick
> Add test coverage for ListView

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyStoreTests.cs
> Refactor `PropertyStoreTests` to `TheoryData` and use `Fact`/`Theory`

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.ChildSubClass.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
- Enable nullability in remaining ControlDesigner members.
> Enable nullability in remaining ControlDesigner members

- .editorconfig
> add Verify settings to editorconfig

- .github/policies/resourceManagement.yml
- eng/Versions.props
> Update to RC1

- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ImageListActionListTests.cs
- Add unit test ImageListActionListTests.cs for public properties and method of the ImageListActionList.
- Enable nullability in ImageListActionList.
> Add unit test for image list action list

- eng/Version.Details.xml
- eng/Versions.props
https://github.com/dotnet/wpf/pull/9511 wpf PRs are broken on a coherency check. This will fix it
> Add System.Formats.Nrbf dependency (needed for wpf)

- eng/Version.Details.xml
- eng/Versions.props
@adamsitnik @JeremyKuhne @dipeshmsft @pchaurasia14 @mmitche
> Fix dependency flow for Nrbf package

- eng/Versions.props
> Update branding to 8.0.9

- eng/Versions.props
> Update branding to 6.0.34

- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/AxImporterTests.cs
- Add unit test AxImporterTests.cs for public properties and method of the AxImporter.
- Enable nullability in  AxImporter.
> Add unit tests for AxImporter

- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ListViewActionListTests.cs
- Add unit test ListViewTests.cs for public properties and method of the ListViewActionList.
- Enable nullability in ListViewActionList.
> Add unit tests for ListViewActionList

- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/BindingSourceDesignerTests.cs
-  Add unit test file: BindingSourceDesignerTests.cs for public property and method of the BindingSourceDesigner.cs file.
> Add unit test for BindingSourceDesigner.cs file

- .github/policies/resourceManagement.yml
- eng/Versions.props
> Update release/9.0 to RC2

- .github/policies/resourceManagement.yml
- eng/Versions.props
> Update main to 10.0 alpha

- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/CompositionDesignerTests.cs
- Add unit test CompositionDesignerTests.cs for public properties and method of the CompositionDesigner.
- Enable nullability in CompositionDesigner.
> Add unit tests for CompositionDesigner

- src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider/ErrorProvider.ErrorProviderStates.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider/ErrorProvider.ErrorWindow.cs
- src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider/ErrorProvider.cs
Related #10827
Similar to work done in: #10843
> Refactor `ErrorProvider` private bool fields to use flags enum

- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ContextMenuStripGroupCollectionTests.cs
- Add unit test ContextMenuStripGroupCollectionTests.cs for public properties and method of the ContextMenuStripGroupCollection.
- Enable nullability in ContextMenuStripGroupCollection.
> Add unit tests for ContextMenuStripGroupCollection

- eng/Versions.props
> Update branding to 8.0.10

- eng/Versions.props
> Update branding to 6.0.35

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripStatusLabelTests.cs
Add unit tests for toolStripStatusLabel to test its properties & methods & events
> Add code coverage for toolStripStatusLabel

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/SelectionManager.cs
Respond to previous PR Feedback
Fixes continues #11984 Follow up feedback from removal of period 2 spaces
- Comment changes only, fix spelling errors, shorten long lines
- None
- No
- None no code changes
> Cleanup SelectionManager long lines and spelling issues

- docs/analyzers/akams.txt
- src/System.Windows.Forms.Analyzers/src/AnalyzerReleases.Shipped.md
Fixes #
PR #11791 moved the location of the `AppManifestAnalyzer` reference. This PR updates the locations.
- 
- 
- Yes / No
-
- 
- 
- 
-
> Update AppManifestAnalyzer reference

- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/CollectionEditVerbManagerTests.cs
Related #10773
- Add test for CollectionEditVerbManager.cs
- No
-  No
- Minimal
- Unit tests
> Add test for CollectionEditVerbManager

- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/RichTextBoxDesignerTests.cs
Related #10773
- Adds code coverage for RichTextBoxDesginer
- None
- No
- Minimal
- Unit tests
> Add code coverage for RichTextBoxDesigner

- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/TextBoxDesignerTests.cs
- Add unit test TextBoxDesignerTests.cs for public properties and method of the TextBoxDesigner.cs
- Enable nullability in TextBoxDesignerTests.cs
> Add unit tests for TextBoxDesigner

- azure-pipelines.yml
> Enable Binskim

- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/PanelDesignerTests.cs
- Add unit test PanelDesignerTests.cs for public properties and method of the PanelDesigner.cs
- Enable nullability in PanelDesignerTests.cs
> Add unit tests for PanelDesigner

- src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/Devices/NetworkTests.cs
Comment out failing test on GitHub (server)
- Skip Ping Timeout test on server
- None
- No
- None
> Skip failing ping test on server

- eng/sdl-tsa-vars.config
Update the area path to match the path in https://github.com/dotnet/winforms/blob/main/eng/pipelines/tsaoptions.json#L5
> Update AreaPath in sdl-tsa-vars.config

- eng/Versions.props
> [release/9.0] Update to rtm

- README.md
fixes https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2253481
> rephrased a statement in the readme file

- src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/Devices/NetworkTests.cs
Fix failing Ping tests
- Fix issue #12140 
- 
- None
- No
- fixes a broken test no runtime code changes
> Fix failing ping test

- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/SRDisplayNameAttributeTests.cs
- Add unit test  SRDisplayNameAttributeTests.cs for public properties and method of the  SRDisplayNameAttribute.cs
- Enable nullability in  SRDisplayNameAttribute.cs
> Add unit tests for SRDisplayNameAttribute

- .editorconfig
- src/System.Private.Windows.Core/tests/BinaryFormatTests/BinaryFormatTests.csproj
- src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj
https://github.com/dotnet/winforms/pull/12167#discussion_r1765451388
> Moved suppression for informational message to editorconfig file.

- src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
This PR fixes issue https://github.com/dotnet/winforms/issues/12184 where users are unable to retrieve items that they have set on the clipboard via `SetClipboardData()` API after calling `Clipboard.Clear()`. We had always been incorrectly clearing the clipboard. Per [documentation](https://learn.microsoft.com/en-us/windows/win32/api/ole2/nf-ole2-olesetclipboard#parameters), we should be calling `SetOleClipboard()` passing in `null` to clear the clipboard, but instead we were setting an empty `DataObject`. This behavior regressed in 9.0 preview 1 after we changed to leverage ComWrappers and Cswin32 for our clipboard code, which exposed that we were incorrectly clearing the clipboard thus getting it into a bad state.
Prior to the change, the code happened to work because the proxy that is …
> [release/9.0] Clear Clipboard Correctly

- src/System.Private.Windows.Core/src/System/Value.TypeFlags.cs
- src/System.Private.Windows.Core/src/System/Value.Union.cs
- src/System.Private.Windows.Core/src/System/Value.cs
- src/System.Windows.Forms/src/System/Windows/Forms/PropertyStore.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyStoreTests.cs
Adds non-boxing support for Point in Value.
Also fix issue trying to put Rectangle/Padding over top of different stored value and add test.
> Add support for Point in Value

- eng/Versions.props
> Update branding to 6.0.36

- eng/Versions.props
> Update branding to 8.0.11

- src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/Logging/FileLogTraceListenerTests.cs
Improves VB Code Coverage for FileLogTraceListener
- Add additional code coverage for FileLogTraceListener
- Improve test coverage
- No
- None adds additional tests
> Improve code coverage for FileLogTraceListener from simplifying PR #11863 

- README.md
git cherry-pick f18a64b252f760a78812e29bc5d7edab8ecab7d3
This is a fix for compliance issue in NET9 [Bug 2270261 [policheck:Error]: 203386 (in s/README.md) (visualstudio.com)](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2270261) in our readme file
> rephrased a statement in the readme file (#12165)

- src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/GetUniqueUtilitiesTests.vb
Cleanup Tests from previous PR
- Use BoolData
- None trivial simplification of Theory Test
- No
- None
> Use BoolData in Tests

- src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/Devices/ComputerTests.cs
- src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/MyServices/ClipboardProxyTests.cs
- src/System.Windows.Forms/tests/ComDisabledTests/ClipboardComTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataFormatsTests.ClipboardTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellTests.ClipboardTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataObjectTests.ClipboardTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DragDropFormatTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.ClipboardTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTextBoxTests.ClipboardTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTextBoxTests.cs
Fixes https://github.com/dotnet/winforms/issues/12229
- Add` [UISettings(MaxAttempts = 3)]` for all Clipboard related tests
> Added retry mechanism for all remaining clipboard tests

- eng/Versions.props
Updates to consume latest docs from dotnet-api-docs
> Bump Microsoft.Private.Intellisense to 20241010.1

- docs/analyzers/akams.txt
- src/System.Windows.Forms.Analyzers.CSharp/src/AnalyzerReleases.Shipped.md
- src/System.Windows.Forms.Analyzers.CSharp/src/AnalyzerReleases.Unshipped.md
Commit e2ec84cb8bb93ff24cf227c974ae57852eaabb24 moved the location of `ApplicationConfigurationGenerator.Help.md`. This PR adjusts sources to changes.
> Update `ApplicationConfigurationGenerator.Help.md` reference

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemCollectionTests.cs
related #10453
Add unit tests for ToolStripItemCollection.cs to test its properties & methods & events
> Add code coverage for ToolStripItemCollection

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripComboBoxTests.cs
Add unit tests for ToolStripComboBox.cs to test its properties & methods & events
> Add code coverage for ToolStripComboBox

- docs/designer/readme.md
> minor edit in the readme file

- .github/ISSUE_TEMPLATE/config.yml
Updating config to enable the blank issue template per team discussion.
Fixes #12218
> Enable Blank issues

- docs/designer/readme.md
> add vs-feedback info to the designer readme

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapterTests.cs
**Proposed changes**
Add unit tests for ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapter.cs to test its properties & methods
> Add code coverage for ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapter

- src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/ApplicationServicesExceptionsTests.vb
- src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/UserTests.UserIdentity.vb
Improved VB Code coverage
- Add tests for VB Application Services Exceptions and fix UserTests.UserIdentity to use Auto Properties to stop compiler from giving suggestion.
- Improves code coverage
- No
- None - improves code coverage
> Code Coverage for VB ApplicationServices Exceptions and minor cleanup

- eng/Versions.props
> Update branding to 9.0.1

- eng/Versions.props
> Update branding to 8.0.12

- eng/Versions.props
> [release/9.0] Change PreReleaseVersionLabel to servicing

- Directory.Build.targets
- eng/versioning.targets
- src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/ComputerInfo.vb
- src/System.Drawing.Common/src/CompatibilitySuppressions.xml
- src/System.Drawing.Common/src/Special/NotSupported.cs
- src/System.Drawing.Common/src/System.Drawing.Common.csproj
- src/System.Drawing.Common/src/System/Drawing/Imaging/ColorMatrix.cs
- src/System.Drawing.Common/src/System/Drawing/Imaging/ImageCodecInfo.cs
- src/System.Windows.Forms.Design/src/System.Windows.Forms.Design.csproj
- src/System.Windows.Forms.Design/src/System/Drawing/Design/BitmapEditor.cs
- src/System.Windows.Forms.Design/src/System/Drawing/Design/ColorEditor.cs
- src/System.Windows.Forms.Design/src/System/Drawing/Design/CursorEditor.cs
- src/System.Windows.Forms.Design/src/System/Drawing/Design/FontEditor.cs
- src/System.Windows.Forms.Design/src/System/Drawing/Design/ImageEditor.cs
- src/System.Windows.Forms.Design/src/System/Drawing/Design/MetafileEditor.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/AnchorEditor.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/BorderSidesEditor.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ComponentTray.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CompositionDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DockEditor.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FileNameEditor.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FolderNameEditor.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ImageListImageEditor.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ParentControlDesigner.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ShortcutKeysEditor.cs
- src/System.Windows.Forms.Primitives/src/System.Windows.Forms.Primitives.csproj
- src/System.Windows.Forms/src/System.Windows.Forms.csproj
- src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/AxHost.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.DataStore.cs
This reverts commit f7a53322868ee629e8302198908b5412dcc554da.
Didn't realize the impact this would have upstream if dependencies were building as CLSCompliant.
> Revert "Remove CLSCompliant attribute (#12469)"

- Winforms.sln
- src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb
- src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/WindowsFormsApplicationBaseTests.vb
- src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/Devices/ComputerTests.cs
- src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/FormattedObject/BinaryFormatWriterTests.cs
- src/System.Private.Windows.Core/tests/BinaryFormatTests/SerializationRecordExtensionsTests.cs
- src/System.Windows.Forms/src/System/Resources/ResXDataNode.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.NativeToWinFormsAdapter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.WinFormsToNativeAdapter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.DataStore.DataStoreEntry.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.DataStore.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OLE/DragDropFormat.cs
- src/System.Windows.Forms/tests/ComDisabledTests/ClipboardComTests.cs
- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DragDropTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BinaryFormatUtilitiesTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataObjectTests.ClipboardTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DragDropHelperTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DragEventArgsTests.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemTests.cs
> Sealed the internal DataStore class, and some minor clean-up

- src/System.Windows.Forms/src/System/Windows/Forms/Accessibility/AccessibleObjectExtensions.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Internal/AssemblyAttributes.cs
> fixed a couple of typos

- src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.NativeToWinFormsAdapter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.RuntimeToNativeAdapter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.WinFormsToNativeAdapter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.ClipboardTests.cs
> removed casts to interfaces by changing methods visibility to public

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewColumnDesignTimeVisibleAttributeTests.cs
Add unit tests for DataGridViewColumnDesignTimeVisibleAttribute.cs to test its properties & methods
> Add code coverage for DataGridViewColumnDesignTimeVisibleAttribute

- src/System.Private.Windows.Core/src/Properties/AssemblyInfo.cs
- src/System.Windows.Forms/tests/IntegrationTests/ScratchProject/Program.cs
- src/System.Windows.Forms/tests/IntegrationTests/ScratchProject/ScratchProject.csproj
- src/System.Windows.Forms/tests/IntegrationTests/ScratchProjectWithInternals/Program.cs
- src/System.Windows.Forms/tests/IntegrationTests/ScratchProjectWithInternals/ScratchProjectWithInternals.csproj
Couple of minor tweaks to the scratch projects for ease of use.
Also add System.Printing for visibility of System.Private.Windows.Core.
> Tweak Scratch projects and add WPF visibility for SPWC

- src/Common/tests/TestUtilities/AppContextSwitchNames.cs
- src/System.Windows.Forms/src/Resources/SR.resx
- src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
- src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.BinaryFormatUtilities.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.Binder.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.NativeToWinFormsAdapter.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObjectExtensions.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OLE/ITypedDataObject.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/CloneTestListView.cs
- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ScrollableControls.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/NativeToWinFormsAdapterTests.cs
> Added resource to SR file for the clipboard APIs

- src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.Binder.cs
and removed unwrapping nullable structs the second time.
> preparation to validate known types

- src/System.Windows.Forms/src/Resources/SR.resx
- src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
- src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Nrbf/WinFormsSerializationRecordExtensions.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OLE/JsonData.cs
Start localization process for strings of exceptions that surface when using OLE Json APIs.
> Start Localization for OLE Json APIs

- src/System.Private.Windows.GdiPlus/System.Private.Windows.GdiPlus.csproj
> Add ChecksumAlgorithm to System.Private.Windows.GdiPlus

- eng/pipelines/build-PR.yml
- eng/pipelines/build.yml
Fixes the broken official builds
> Update MicroBuild to v4

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/NumericUpDownAccelerationTests.cs
- Add unit tests for NumericUpDownAcceleration.cs to test its properties & methods
- Enable nullability in NumericUpDownAccelerationTests.cs
> Add unit tests for NumericUpDownAcceleration

- eng/Versions.props
> Update branding to 9.0.2

- eng/Versions.props
> Update branding to 8.0.13

- src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/SingleInstanceHelpers.vb
- src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb
- src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Network.DownloadFile.vb
- src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/Network.UploadFile.vb
- src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/NetworkUtilities.vb
- src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Interaction.vb
- src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/MyServices/ClipboardProxy.vb
- src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/TestUtilitiesTests.vb
- src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/TestUtilities/TestData/PathSeparatorTestData.vb
- src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/TestUtilities/VbFileCleanupTestBase.vb
Fixes PR Review Comments from #12486
Cleanup
SingleInstanceHelpers.vb
WindowsFormsApplicationBase.vb
Network.DownloadFile.vb
Interaction.vb
ClipboardProxy.vb
SingleInstanceHelpersTests.vb
TestUtilitiesTests.vb
PathSeparatorTestData.vb
VbFileCleanupTestBase.vb
Simplify review if #12486
- No
- minimal only code cleanup
> PR Feedback Cleanup files in Separate PR

- NuGet.config
- eng/Version.Details.xml
- eng/Versions.props
- global.json
> Merging internal commits for release/9.0

- docs/analyzers/akams.txt
- pkg/Microsoft.Private.Winforms/sdk/dotnet-wpf/System.Windows.Forms.Analyzers.props
- src/System.Windows.Forms.Analyzers/src/AnalyzerReleases.Shipped.md
- src/System.Windows.Forms.Analyzers/src/AnalyzerReleases.Unshipped.md
> fixed analyzer docs links

- src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/Devices/NetworkUtilities.vb
Fixes #12763
- Use correct version of GetResourceString
- Labels in ProgressDialog will have correct values
- Yes
- Minimal
> Fix issue #12763

- .github/policies/resourceManagement.yml
Set milestone number PRs are labeled with to 9.0.2 - February servicing milestone
> [release/9.0] Update resourceManagement.yml

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewButtonColumnTests.cs
Add unit tests for DataGridViewButtonColumn.cs to test its methods & properties
> Add code coverage for DataGridViewButtonColumn

- src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
> Don't serialize obsolete properties

- eng/Versions.props
> Update pre-release label to preview

- eng/Versions.props
> Update branding to 9.0.3

- eng/Versions.props
> Update branding to 8.0.14

- src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/WinformsControlsTest.csproj
> removing unused dependency that causes compliance issues

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FlatButtonAppearanceConverterTests.cs
Add unit tests for FlatButtonAppearanceConverter.cs to test its methods & properties
> Add code coverage for FlatButtonAppearanceConverter

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBox.SelectedIndexCollectionTests.cs
Add unit tests for ListBox.SelectedIndexCollection.cs to test its methods
> Addd code coverage for ListBox.SelectedIndexCollection

- docs/analyzers/WinFormsCSharpAnalyzers.Help.md
- docs/analyzers/WinFormsVisualBasicAnalyzers.Help.md
> Adding VB analyzer documentation for WFO1001

- src/System.Windows.Forms/tests/IntegrationTests/ScratchProject/ScratchProject.csproj
- src/System.Windows.Forms/tests/IntegrationTests/ScratchProjectWithInternals/ScratchProjectWithInternals.csproj
> Add the design project to the scratch tests

- src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/OpenFileDialogTests.cs
> added a test for ShowDialog re-entry

- src/System.Windows.Forms/tests/IntegrationTests/ScratchProject/ScratchProject.csproj
- src/System.Windows.Forms/tests/IntegrationTests/ScratchProjectWithInternals/ScratchProjectWithInternals.csproj
To test type editors in the runtime scenarios for HDPI testing
> add facade assemblies to scratch projects

- src/System.Drawing.Common/tests/System/Drawing/ImageTests.cs
- src/System.Drawing.Common/tests/System/Drawing/Imaging/MetafileTests.cs
- src/System.Private.Windows.Core/src/NativeMethods.txt
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerUtils.cs
- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.cs
- src/System.Windows.Forms.Primitives/src/NativeMethods.txt
- src/System.Windows.Forms.Primitives/src/System/Windows/Forms/DeviceContextExtensions.cs
- src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/EmfScope.cs
- src/System.Windows.Forms/src/System/Windows/Forms/Rendering/ControlPaint.cs
Move a few interop definitions down and add some more EMF tests to ensure we have #12951 fully covered.
> Add a few more EMF tests

- eng/Localize/LocProject.json
> removed extra whitespaces from the project file

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
> Publish the unshipped APIs

- src/System.Windows.Forms.Analyzers.CSharp/src/AnalyzerReleases.Shipped.md
- src/System.Windows.Forms.Analyzers.CSharp/src/AnalyzerReleases.Unshipped.md
- src/System.Windows.Forms.Analyzers.VisualBasic/src/AnalyzerReleases.Shipped.md
- src/System.Windows.Forms.Analyzers.VisualBasic/src/AnalyzerReleases.Unshipped.md
These analyzers are shipped in preview2
> move WFO1001 to the shipped analyzers files

- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBox.SelectedObjectCollectionTests.cs
Add unit tests for ListBox.SelectedObjectCollection.cs to test its methods
> Add code coverage for ListBoxSelectedObjectCollection

- src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/THIRD-PARTY-NOTICE.txt
added header per https://github.com/dotnet/runtime/blob/main/docs/project/copyright.md
> renamed License.txt to THIRD-PARTY-NOTICE.txt

- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ToolStripDesignerUtilsTests.cs
- Add unit test file: ToolStripDesignerUtilsTests.cs for public methods of the ToolStripDesignerUtils.cs.
- Enable nullability in ToolStripDesignerUtilsTests.cs.
> Add unit tests for ToolStripDesignerUtils.cs file

- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ToolStripPanelDesignerTests.cs
- Add unit test ToolStripPanelDesignerTests.cs for public properties and method of the ToolStripPanelDesigner
- Enable nullability in ToolStripPanelDesignerTests.cs
> Add unit tests for ToolStripPanelDesigner

- src/System.Private.Windows.Core/src/System/SpanHelpers.cs
Fixes https://github.com/dotnet/winforms/issues/12997
Re-enable IDE0059 for a "reference-like" type, as our SDK now has the fix for this analyzer.
> Re-enable IDE0059 for a "reference-like" type

- src/System.Private.Windows.Core/src/System/Private/Windows/Ole/Composition.NativeToManagedAdapter.cs
- src/System.Private.Windows.Core/src/System/Private/Windows/Ole/DataFormatNames.cs
- src/System.Private.Windows.Core/src/System/Private/Windows/Ole/DataStore.cs
- src/System.Private.Windows.Core/src/System/Private/Windows/Ole/FormatEnumerator.cs
- src/System.Private.Windows.Core/src/System/Private/Windows/Ole/IOleServices.cs
- src/System.Private.Windows.Core/tests/System.Private.Windows.Core.Tests/System/Private/Windows/Ole/ClipboardCoreTests.cs
- src/System.Private.Windows.Core/tests/System.Private.Windows.Core.Tests/System/Private/Windows/Ole/MockOleServices.cs
- src/System.Windows.Forms/src/System/Windows/Forms/OLE/WinFormsOleServices.cs
- src/System.Windows.Forms/tests/TestUtilities/Data/DataObjectTestHelpers.cs
- src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataObjectTests.cs
Few minor tweaks to handle metafile scenarios in WPF.
> Tweak OLE code to allow metafile handling in WPF

- docs/designer/designer-high-dpi-mode.md
Fixes missing closing <Project> tag in example XML
- None
- No
- None
> Added missing closing <Project> tag to example XML

- src/System.Windows.Forms/System/Windows/Forms/Dialogs/CommonDialogs/ColorDialog.cs
This regressed when moving to CsWin32. We need to use a copy of custom colors when calling ChooseColor so that we can skip updating colors when the dialog is cancelled.
Fixes #13067
> Use custom color copy with ColorDialog

- eng/Versions.props
> Update branding to 9.0.4

- eng/Versions.props
> Update branding to 8.0.15

- src/System.Windows.Forms/System/Windows/Forms/Controls/TextBox/MaskedTextBox.cs
Missed this in the last XML cleanup.
> Fix a comment miss

- eng/Localize/LocProject.json
pick up file generated by eng\common\generate-locproject.ps1 - this is a reactive change to move of resx files
> fix for an internal build break in Loc task

- Directory.Packages.props
- eng/Versions.props
- src/Common/tests/TestUtilities/FluentAssertions/FluentAssertExtensions.cs
- src/Common/tests/TestUtilities/System.Private.Windows.Core.TestUtilities.csproj
- src/System.Drawing.Common/tests/System.Drawing.Common.Tests.csproj
- src/System.Private.Windows.Core/tests/BinaryFormatTests/BinaryFormatTests.csproj
- src/System.Private.Windows.Core/tests/System.Private.Windows.Core.Tests/System.Private.Windows.Core.Tests.csproj
- src/System.Windows.Forms.Design/tests/UnitTests/System.Windows.Forms.Design.Tests.csproj
- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DataGridViewColumnTypePickerTests.cs
- src/System.Windows.Forms.Primitives/tests/TestUtilities/System.Windows.Forms.Primitives.TestUtilities.csproj
- src/System.Windows.Forms.Primitives/tests/UnitTests/System.Windows.Forms.Primitives.Tests.csproj
- src/test/integration/UIIntegrationTests/ListBoxItemAccessibleObjestTests.cs
- src/test/unit/System.Windows.Forms/ComDisabled/ComDisabled.Tests.csproj
- src/test/unit/System.Windows.Forms/System.Windows.Forms.Tests.csproj
- src/test/unit/System.Windows.Forms/System/Windows/Forms/ToolStripTextBoxTests.cs
Context: https://github.com/fluentassertions/fluentassertions/pull/2943
Note that code didn't change - namespace is the same.
Didn't try building/running tests
cc @Tanya-Solyanik @artl93 @marcpopMSFT  @rainersigwald
> Try replacing FluentAssertions

- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DesignBindingValueUIHandlerTests.cs
Add unit test file: DesignBindingValueUIHandler.cs for public methods of the DesignBindingValueUIHandler.cs
> Add code coverage for DesignBindingValueUIHandler

- eng/pipelines/azure-pipelines-codeql.yml
> enable code-ql on the release 8 and 9 branches

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- Adjust the order of PublicAPI in Shipped file
> Adjust the order of PublicAPI in Shipped file

- .github/policies/resourceManagement.yml
- eng/Versions.props
- Update Pre-Release Iteration and Resource Management Milestone to 10.0 Preview4
> Update Pre-Release Iteration and Resource Management Milestone to 10.0 Preview4

- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DataSourceListEditorTests.cs
Add unit test DataSourceListEditorTests.cs for public method of the DataSourceListEditor.
> Add coverage for DataSourceListEditor

- eng/pipelines/build-PR.yml
- eng/pipelines/build.yml
test AzDO run - https://dnceng.visualstudio.com/internal/_build/results?buildId=2677006&view=results
Doc reference - https://learn.microsoft.com/en-us/azure/devops/pipelines/yaml-schema/steps-checkout?view=azure-pipelines#properties
> checkout:self and clean are the default steps, we don't have to specify them in the script

- eng/Versions.props
> Update branding to 8.0.16

- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/TableLayoutPanelCodeDomSerializerTests.cs
Related #10773
- Add unit test for `TableLayoutPanelCodeDomSerializer`
> Add test for TableLayoutPanelCodeDomSerializer

- eng/Versions.props
> Update branding to 9.0.5

- src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/MaskedTextBoxTextEditorDropDown.cs
- Enable nullability in MaskedTextBoxTextEditorDropDown.
> Enable nullability in MaskedTextBoxTextEditorDropDown

- src/System.Private.Windows.Core/src/System.Private.Windows.Core.csproj
> re-enable IDE0059 in the VMR build since it's on SDK p4 already

- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/EditorServiceContextTests.cs
- Add unit test file: EditorServiceContextTests.cs for public method of the EditorServiceContext.cs.
> Add unit tests for EditorServiceContext

- src/System.Private.Windows.Core/src/Windows/Win32/System/Com/AgileComPointer.cs
- src/System.Windows.Forms/System/Windows/Forms/Controls/WebBrowser/HtmlElement.cs
Enhance the `AgileComPointer<TInterface>` class by introducing a `_memoryPressure` field and updating the constructor to accept a `memoryPressure` parameter. This allows for better memory management by informing the garbage collector about native memory usage.
In the `HtmlElement` class, define a `MemoryPressure` constant and update its constructor to pass this value to `AgileComPointer`, improving garbage collection efficiency when creating multiple `HtmlElement` instances.
Tried creating a cached version of the `AgileComPointer`, but that didn't help in this case as items in the linked repro were always new instances.
Fixes: #13195
> Add memory pressure management to AgileComPointer

- src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/Behavior/SnapLineTests.cs
A follow-up to [PR13324](https://github.com/dotnet/winforms/pull/13324)
Add Unit Test For [Issue13305](https://github.com/dotnet/winforms/issues/13305)
> Add Unit Test For issue 13305

- src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
- src/System.Windows.Forms/PublicAPI.Shipped.txt
- src/System.Windows.Forms/PublicAPI.Unshipped.txt
The important addition is a new Clipboard helper method, the rest is virtual overrides
> publishing APIs that we ship in NET10 Preview4

- src/test/integration/UIIntegrationTests/ListViewTests.cs
> Removing all skip tag and add ListViewUITests in a new collection and add retry mechanism

- src/System.Private.Windows.Core/tests/System.Private.Windows.Core.Tests/System/Private/Windows/Ole/ClipboardCoreTests.cs
- src/test/unit/System.Windows.Forms/System/Windows/Forms/ClipboardTests.cs
Related #13331
- Moving some cases from ClipboardTests class to ClipboardCoreTests
> Moving some cases from ClipboardTests class to ClipboardCoreTests

- .github/policies/resourceManagement.yml
Update label "area:NRT" to "area-NRT" in file resourceManagement.yml
> Update label "area:NRT" to "area-NRT"

- eng/Versions.props
> Update branding to 9.0.6

- eng/Versions.props
> Update branding to 8.0.17

- .github/policies/resourceManagement.yml
- eng/Versions.props
Update Pre-Release Iteration and Resource Management Milestone to preview6
> Update resourceManagement.yml and Versions.props

- eng/Versions.props
> Update branding to 9.0.7

- src/test/unit/System.Windows.Forms/System/Windows/Forms/HtmlElementErrorEventArgsTests.cs
- Add unit test file: HtmlElementErrorEventArgsTests.cs for HtmlElementErrorEventArgs.cs file.
> Add unit test for HtmlElementErrorEventArgs.cs file

- dotnet.config
Fixes #
- Adds `dotnet.config` to use the `dotnet test` experience for MTP.
- Follow-up to https://github.com/dotnet/winforms/pull/13540
- None
- Yes / No
-
- 
- 
- 
-
> Add dotnet.config to opt-in MTP `dotnet test`

- eng/Versions.props
> Update xunit.v3 and xunit.stafact

- src/test/unit/System.Windows.Forms/System/Windows/Forms/DataGridViewLinkCellTests.cs
Add unit test file: DataGridVieLinkCellTests.cs for DataGridVieLinkCell.cs file.
> Add code coverage for DataGridVieLinkCell

- eng/Versions.props
> Update branding to 9.0.8

- eng/Versions.props
> Update branding to 8.0.19

- src/test/unit/System.Windows.Forms/System/Windows/Forms/ListView.CheckedIndexCollectionTests.cs
- Add unit test file: ListView.CheckedIndexCollectionTests.cs for ListView.CheckedIndexCollection.cs file
> Add unit test for ListView.CheckedIndexCollection file

- src/test/unit/System.Windows.Forms/System/Windows/Forms/ListView.CheckedListViewItemCollectionTests.cs
**Proposed changes:**
- Add unit test file: ListView.CheckedListViewItemCollectionTests.cs for ListView.CheckedListViewItemCollection.cs file
> Add unit test for ListView.CheckedListViewItemCollection file

- eng/Versions.props
> Update xunit.v3 to 3.0.0

- eng/Versions.props
Fixes #
- 
- 
- 
- 
- 
- Yes / No
-
- 
- 
- 
-
> Update stafact to latest stable

- src/test/unit/System.Windows.Forms/System/Windows/Forms/PropertyGrid.PropertyTabCollectionTests.cs
Add more test for uncovered public methods in PropertyGrid.PropertyTabCollectionTests.cs file
> Add unit test for PropertyGrid.PropertyTabCollection file

- eng/Localize/LocProject.json
Should fix CI [build failure](https://dev.azure.com/dnceng/internal/_build/results?buildId=2784392&view=logs&s=a104fbd5-e56d-5594-72d4-a9fcde2d089f) for main branch due to mismatch between existing and generated `LocProject.json`.
> Update LocProject.json with new language set

- eng/Versions.props
> Update branding to 8.0.22
