src/System.Windows.Forms.Primitives/src/Interop/WinFormsComWrappers.cs

We need to release the incoming pointer when returning a wrapped object. This was fixed in .NET 7 and removed completely in .NET 8 (where we access the COM object directly).
Without this any time we access IPicture we will permanently leak the incoming native class with no way for customers to fix it. This usually manifests as an exhaustion of GDI handles and will crash the application.
This is a regression from .NET 5.
Fixes #9774

Release COM object when wrapping in PictureWrapper

---

src/System.Windows.Forms.Primitives/src/Interop/Kernel32/Interop.GetExitCodeThread.cs

Fixes #9721
`PInvoke.GetExitCodeThread()` is incorrectly wrapped. It doesn't define `SetLastError = true`, which causes `Marshal.GetLastWin32Error()` to not return the invalid handle error code that would terminate [this loop ](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/src/System/Windows/Forms/Control.cs#L3840) we eventually get into, ultimately causing WinForms app to hang on exit.
This is not an issue in .NET 8 as we are leveraging Cswin32, which defines PInvokes correctly.

Fix application hang on exit

---

Directory.Build.targets
docs/testing-in-vs.md
eng/Version.Details.xml
eng/Versions.props
global.json

move to runtime toolset 'dotnet/x64 v9.0.0-alpha.1.23430.1' to ensure coherency in the windows desktop repo, see https://github.com/dotnet/windowsdesktop/pull/3841 for details

bump up VS redist to 9.0

---

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ComponentCache.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ComponentCodeDomSerializer.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ContainerCodeDomSerializer.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/EnumCodeDomSerializer.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/EventMemberCodeDomSerializer.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/PrimitiveCodeDomSerializer.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourceCodeDomSerializer.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripMenuItemCodeDomSerializer.cs

- Enable nullability in `ContainerCodeDomSerializer`
- Enable nullability in `EnumCodeDomSerializer`
- Enable nullability in `EventMemberCodeDomSerializer`
- Enable nullability in `PrimitiveCodeDomSerializer`
- Enable nullability in `ResourceCodeDomSerializer`
- Enable nullability in `ToolStripMenuItemCodeDomSerializer`
- Enable nullability in `ComponentCodeDomSerializer` (2nd commit)

Enable nullability in several internal CodeDomSerializers

---

src/System.Design/src/System.Design.Forwards.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewComboBoxColumnDesigner.cs
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/DesignerAttributeTests.cs

Related to #4908 
- Add DataGridViewComboBoxColumnDesigner.cs
- DataGridViewComboBoxColumnDesigner can be designed in runtime
- No
- Minimal
The ComboBoxColumn cannot be added to DataGridView
- Manually (added DataGridViewComboBoxColumnDesigner to DemoConsole test app)
- .net 8.0.0-rc.1.23421.3

Port DataGridViewComboBoxColumnDesigner to runtime

---

src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemTileAccessibleObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemWithImageAccessibleObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/ListViewLabelEditAccessibleObject.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemWithImageAccessibleObjectTests.cs

Fixes #9829 
The parent node of the edit label in the ListView may be one of SubItem or ListViewItem, so the tree structure needs to be drawn according to different view modes.
- Modify the access level of the selected  ListViewItem in ListView class so that ListViewLabelEditAccessibleObject can access it.
- Modify the ListViewItemTileAccessibleObject and ListViewItemWithImageAccessibleObject classes so that when the ListView is enabled for editing, the tree structure can correctly load the AccessibleObject of Edit label.
- Modify the ListViewLabelEditAccessibleObject class to make sure the edit label can find correctly parent node in different ViewModel.
- No Excepiton pop up when Accessibility tools accessed the edit label in ListView.
- Edit label can correctly find parent nodes in all …

Make sure no exception pop up when edit label is accessed in ListView with viewMode: LargeIcon,SmallIcon,Tile

---

THIRD-PARTY-NOTICES.TXT
src/System.Windows.Forms/tests/AxHosts/THIRD-PARTY-NOTICES.txt

Fixes #9905 
Removes the test-only notice in the main repo's TPN and add it alongside the test that utilizes it in a local TPN

Place Test-Only Notice Alongside Test

---

eng/Localize/LocProject.json

We ported DataGridviewDesigner via https://github.com/dotnet/winforms/pull/9677 in main branch but failed to update stored LocProj file to reflect the resource content that came with this porting.
Fixing issue in CI https://dev.azure.com/dnceng/internal/_build/results?buildId=2266578&view=logs&j=c2111129-d6a3-58de-e667-00e5a0966c99&t=04624205-1088-500d-206a-392ceb108efa with this update.

Update LocProj to help CI verification

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlCodeDomSerializer.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TableLayoutPanelCodeDomSerializer.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripCodeDomSerializer.cs

- Enable nullability in `ControlCodeDomSerializer`
- Enable nullability in `ToolStripCodeDomSerializer`
- Enable nullability in `TableLayoutPanelCodeDomSerializer`

Enable nullability in several internal CodeDomSerializers, part 2

---

src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomLocalizationProvider.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/MemberCodeDomSerializer.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/PropertyMemberCodeDomSerializer.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourcePropertyMemberCodeDomSerializer.cs

- Enable nullability in `MemberCodeDomSerializer`
- Enable nullability in `EventMemberCodeDomSerializer`
- Enable nullability in `PropertyMemberCodeDomSerializer`
- Enable nullability in `ResourcePropertyMemberCodeDomSerializer`, remove an unused field and rename another field

Enable nullability in MemberCodeDomSerializer and all derived classes

---

docs/design/anchor-layout-changes-in-net80.md
src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/LocalAppContextSwitchesTest.cs

AnchorLayoutV2 was introduced during the early preview of .NET 8.0 with the intention of making it the default option to gather user feedback on its functionality. Currently, there are two unresolved issues, namely [9740](https://github.com/dotnet/winforms/issues/9740) and [5136](https://github.com/microsoft/winforms-designer/issues/5136), which must be addressed before this feature can be widely adopted.
While we are actively working on resolving these issues, given the nature of fixes needed, we have decided to change the status of this feature to an explicit opt-in for .NET 8.0. This allows us to focus on addressing these issues and incorporating feedback that has been received thus far.

Change default opt-in to false for AnchorLayoutV2 in .Net 8.0

---

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripHighContrastRenderer.cs
src/System.Windows.Forms/src/System/Windows/Forms/ToolstripProfessionalRenderer.cs

Relate #https://github.com/dotnet/winforms/pull/9878#issuecomment-1720807530
- Update the checked style of ToolstripMenuItem.
- Update the TextColor under HighContrast environment.
- Update the border of ToolstripMenuItem under HighContrast environment.
- The color contrast of ToolStripMenuItem's checked style is consistent with the ToolStripButton.
- Yes
-Minimal
The color contrast ratio of the rectangle box is less than 3:1
**HighContrast Aquatic:**
(checked)
(selected and checked)
**Desert:**
(checked)
(selected and checked)
**Dusk:**
(checked)
(selected and checked)
**Night sky:**
(checked)
(selected and checked)
The color contrast of the rectangle box meets the normal proportions.
**HighContrast Aquatic:**
(checked)
(selected and checked)
**Desert:**
(checked)
(selected and checked) …

Fix the color contrast ratio of ToolStripMenuItem's checked style is less than 3 : 1

---

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Automation/UiaTextProvider.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Automation/UiaTextRange.cs
src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/Automation/UiaTextRangeTests.cs
src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/ListBox.AccessibleObject.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBox.ListBoxItemAccessibleObjectTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObjectTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewLabelEditAccessibleObjectTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObjectTests.cs

This problem manifests as a first chance NotSupportedException    at System.StubHelpers.ObjectMarshaler.ConvertToNative(Object objSrc, IntPtr pDstVariant)
```
System.NotSupportedException
HResult=0x80131515
Message=Type 'Windows.Win32.Foundation.COLORREF' cannot be marshalled to a Variant. Type library is not registered.
Source=<Cannot evaluate the exception source>
StackTrace:
<Cannot evaluate the exception stack trace>
```
This exception is thrown when the user is selecting text in a text box (or any text control that has a UIA text provider) under a Narrator. UIA is querying the foreground and background text colors and the bounding rectangle of the control. Colors and bounding rectangle are c# structs, and our UIA implementations cast these structs to an object. However, the interop …

Convert structs to primitive types when passing them to the interop methods that expect VARIANTs

---

eng/Versions.props
src/System.Drawing.Common/src/System.Drawing.Common.csproj

System.Drawing.Common has been ported from runtime during the .NET 8 previews. In it's current form, it will have an unstable version when we switch to rtm. This PR fixes that

Make System.Drawing.Common stable for rtm

---

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Automation/UiaTextProvider.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Automation/UiaTextRange.cs
src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/Automation/UiaTextRangeTests.cs
src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/ListBox.AccessibleObject.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBox.ListBoxItemAccessibleObjectTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObjectTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewLabelEditAccessibleObjectTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObjectTests.cs

Porting a regression fix from main - https://github.com/dotnet/winforms/pull/9960
Accessibility model data will be incorrect for Accessibility tools 
Yes, related to the interop/CS-Win32 work 
Manual testing under UIA accessibility tools – Narrator, Inspect and Accessibility Insights
Low – only accessibility scenarios are affected.
I noticed this as  NotSupportedException at System.StubHelpers.ObjectMarshaler.ConvertToNative(Object objSrc, IntPtr pDstVariant)
```
System.NotSupportedException
HResult=0x80131515
Message=Type 'Windows.Win32.Foundation.COLORREF' cannot be marshalled to a Variant. Type library is not registered.
Source=<Cannot evaluate the exception source>
StackTrace:
<Cannot evaluate the exception stack trace>
```
As a result of this exception UIA Accessibility tools will …

[RC2] Convert structs to primitive types when passing them to the interop methods that expect VARIANTs

---

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Automation/UiaTextProvider.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Automation/UiaTextRange.cs
src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/Automation/UiaTextRangeTests.cs
src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/ListBox.AccessibleObject.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBox.ListBoxItemAccessibleObjectTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObjectTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewLabelEditAccessibleObjectTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObjectTests.cs

Porting a regression fix from main - https://github.com/dotnet/winforms/pull/9960
Accessibility model data will be incorrect for Accessibility tools 
Yes, related to the interop/CS-Win32 work 
Manual testing under UIA accessibility tools – Narrator, Inspect and Accessibility Insights
Low – only accessibility scenarios are affected.
I noticed this as  NotSupportedException at System.StubHelpers.ObjectMarshaler.ConvertToNative(Object objSrc, IntPtr pDstVariant)
```
System.NotSupportedException
HResult=0x80131515
Message=Type 'Windows.Win32.Foundation.COLORREF' cannot be marshalled to a Variant. Type library is not registered.
Source=<Cannot evaluate the exception source>
StackTrace:
<Cannot evaluate the exception stack trace>
```
As a result of this exception UIA Accessibility tools will …

[RTM] Convert structs to primitive types when passing them to the interop methods that expect VARIANTs

---

src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs

fix #6559
`TreeView.cs`
After TreeNode is selected or TreeView is fouced, `AutomationFocusChangedEvent` will be raised.
``` c#
protected virtual void OnAfterSelect(TreeViewEventArgs e)
{
_onAfterSelect?.Invoke(this, e);
// Raise an event to highlight & announce the selected node.
if (IsAccessibilityObjectCreated)
{
AccessibleObject nodeAccessibleObject = e.Node!.AccessibilityObject;
nodeAccessibleObject.RaiseAutomationEvent(UiaCore.UIA.AutomationFocusChangedEventId);
nodeAccessibleObject.RaiseAutomationEvent(UiaCore.UIA.SelectionItem_ElementSelectedEventId);
// Raise to say "Selected" after announcing the node.
nodeAccessibleObject.RaiseAutomationPropertyChangedEvent(
UiaCore.UIA.SelectionItemIsSelectedPropertyId,
oldValue: !nodeAccessibleObject.IsItemSelected,
newValue: …
```

fix bug: TreeView control has no highlighting of selected node first time if the control has first TabIndex on the form

---

src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNode.TreeNodeAccessibleObjectTests.cs

Fix #9822
- 
- TreeViewItem add `SelectItem` method.
- 
- Yes 
- 
- unit test
- 
8.0.0-preview.7.23375.6
-

Fix Accessibility: Can't select TreeView items using UIAutomation SelectionItem.Select

---

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Automation/UiaTextRange.cs
src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/Automation/UiaTextRangeTests.cs
src/System.Windows.Forms/src/System/Windows/Forms/TextBox.cs
src/System.Windows.Forms/tests/UnitTests/TextBoxBaseTests.cs

Fixes #9828
- Base on [PR 9960](https://github.com/dotnet/winforms/pull/9960), we need update the ITextRangeProvider.GetBoundingRectangles() method to make sure the rectangeles for the selection text in TextBox can be correctly drawn.
- Update the method of ProcessCmdKey(ref Message m, Keys keyData) in TextBox class.
- When using keyboard: Ctrl+A or mouse to choose all texts in TextBox/ComboBox/DomainUpDown/NumericUpDown, Narrator cannot focus entire texts and announce "Document selected" to user
- Yes 
- Minimal
Keep the same behavior with .Net 7.0, narrator can focus entire texts and announce "Document selected" to user.
- Manual (Narrator)

Fix Narrator cannot announce correctly and getting incorrect rectanges

---

src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.TreeNodeAccessibleObject.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNode.TreeNodeAccessibleObjectTests.cs

[This PR is a correction on incorrectly merged PR - #9955 ]
Fix #9822
- 
- TreeViewItem add `SelectItem` method.
- 
- Yes 
- 
- unit test
- 
8.0.0-preview.7.23375.6
-

[RC2] Can't select TreeView items using UIAutomation SelectionItem.Select 

---

src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.cs
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DesignSurfaceExt/NameCreationServiceImp.cs

Fixes #9968 
When we click the control of 'Add Tab', an exception message will be thrown in the CreateName method:
DataGridViewComboBoxColumn cannot be converted to component, 
So we need to modify the creation method of the DataGridViewComboBoxColumn object.
- Modify the creation way of DataGridViewComboBoxColumn object.
- TabPage can add to TabControl in DemoConsole.
- No
-Minimal
- Manual(DemoConsole)

Fix TabPage cannot add to TablControl in DemoConsole

---

eng/Versions.props
src/System.Drawing.Common/src/System.Drawing.Common.csproj

System.Drawing.Common has been ported from runtime during the .NET 8 previews. In it's current form, it will have an unstable version when we switch to rtm. This PR fixes that

[release/8.0] Make System.Drawing.Common stable for rtm

---

src/System.Windows.Forms/src/System/Windows/Forms/ImageList.ImageCollection.cs

When multiple threads call `Images.IndexOfKey`, it is possible to get `System.ArgumentOutOfRangeException: 'Index was out of range. Must be non-negative and less than the size of the collection. (Parameter 'index')` exception when one of the calls returns -1.
Debugging this, the first `IsValidIndex` check passes, but the `_imageInfoCollection[]` accessor throws, which should not be possible, especially when the collection is not modified.
Another thing that could be optimized is removing the double list accessor by doing `_imageInfoCollection[i] is {} image`, so that next `SafeCompareStrings` call does not read from the list again.
- No
- None

Fix thread-safety issue of reading last accessed index in `ImageList.ImageCollection.IndexOfKey`

---

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewBand.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellStyle.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewHeaderCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/KeyEventArgs.cs
src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
src/System.Windows.Forms/src/System/Windows/Forms/PreviewKeyDownEventArgs.cs
src/System.Windows.Forms/src/System/Windows/Forms/WebBrowser.WebBrowserSite.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ApplicationTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PowerStatusTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/SystemInformationTests.cs

- Replace usage of `Enum.IsDefined` by `Enum.IsDefined<T>` across codebase

use generic overload of Enum.IsDefined to avoid boxing

---

src/System.Windows.Forms/src/PublicAPI.Shipped.txt
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxCell.cs

- Enable nullability in DataGridViewTextBoxCell.

Enable nullability in DataGridViewTextBoxCell

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewCellStyleBuilder.resx
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/xlf/DataGridViewCellStyleBuilder.cs.xlf
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/xlf/DataGridViewCellStyleBuilder.de.xlf
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/xlf/DataGridViewCellStyleBuilder.es.xlf
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/xlf/DataGridViewCellStyleBuilder.fr.xlf
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/xlf/DataGridViewCellStyleBuilder.it.xlf
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/xlf/DataGridViewCellStyleBuilder.ja.xlf
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/xlf/DataGridViewCellStyleBuilder.ko.xlf
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/xlf/DataGridViewCellStyleBuilder.pl.xlf
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/xlf/DataGridViewCellStyleBuilder.pt-BR.xlf
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/xlf/DataGridViewCellStyleBuilder.ru.xlf
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/xlf/DataGridViewCellStyleBuilder.tr.xlf
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/xlf/DataGridViewCellStyleBuilder.zh-Hans.xlf
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/xlf/DataGridViewCellStyleBuilder.zh-Hant.xlf
src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/EmbeddedResourceTests.cs

Fixes #3047
- Add missing file DataGridViewCellStyleBuilder.resx
-  The cell style properties can be updated normally
-  No
- Minimal
When edit the cell style properties for a DataGridView control in PropertyGrid, an error dialog pop-up.
The CellStyle Builder dialog can be opened.
- Manually (Add test to Dome project)
- .net 9.0.0-alpha.1.23470.17

Add missing DataGridViewCellStyleBuilder.resx

---

src/System.Windows.Forms/src/System/Windows/Forms/Cursor.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CursorTests.cs

DO NOT REBASE/SQUASH
Our static Cursors should never be disposed. This was a regression for the ones wrapped around system cursors. Our own resource cursors were never properly guarded, this fixes them.

Don't invalidate Cursors cursors (#9994)

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FlowLayoutPanelDesigner .cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripContainerDesigner.cs

Fixes #9989 
- Add judgement before invoking function "ContainerParent" in file ToolStripContainerDesigner.cs
- Add missing property "FlowDirection"  and "InheritanceAttribute" from VS repo to FlowLayoutPanelDesigner.cs
- All of the control can be selected normally in Demo project
- Yes  
- Minimal
https://github.com/dotnet/winforms/assets/104609169/22b8bb87-cfd8-4627-b9fe-786484f1e9e6
- Manually
- .net 9.0.0-alpha.1.23470.17

Update FlowLayoutPanelDesigner.cs and ToolStripContainerDesigner.cs

---

src/System.Windows.Forms/src/System/Windows/Forms/Cursor.cs
src/System.Windows.Forms/src/System/Windows/Forms/CursorConverter.cs
src/System.Windows.Forms/src/System/Windows/Forms/Cursors.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CursorConverterTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CursorTests.cs

Construction of Cursors statics had gotten a bit over complicated. ToString() was also very expensive when creating Cursors from handles.
The core of the change is to pass the property name when constructing a Cursor from Cursors for consistency and performance.
These changes will also allow making the CursorConverter reflection free in the future.

Simplify Cursor code

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.AdornerWindow.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerFrame.cs

- Replace `ArrayList`s with `List<T>`s in `DesignerFrame` (contributes to #8140)
- Enable nullability in `DesignerFrame`
- Clean up `DesignerFrame` and one call site

Enable nullability in DesignerFrame and clean it up

---

src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/WindowsFormsSynchronizationContextTests.cs

Fixes #9965
- add a specific test in Control.InvokeMarshaledCallbackDo to detect when the delegate is of type SendOrPostCallback
- better performances when using WindowsFormSynchronizationContext.Post or Send and TaskScheduler when derived from WindowsFormSynchronizationContext
- No
```csharp
at System.Environment.get_StackTrace()
at System.Windows.Forms.Tests.WindowsFormsSynchronizationContextTests.<>c__DisplayClass9_0.<WindowsFormsSynchronizationContext_Send_NoDynamicInvoke>g__Callback|0(Object _) in C:\code\external\dotnet\winforms\src\System.Windows.Forms\tests\UnitTests\System\Windows\Forms\WindowsFormsSynchronizationContextTests.cs:line 164
at InvokeStub_SendOrPostCallback.Invoke(Object, Span`1)
at System.Reflection.MethodBaseInvoker.InvokeWithOneArg(Object obj, BindingFlags …
```

add shortcut on Control.Invoke when the delegate is SendOrPostCallback

---

src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CollectionCodeDomSerializer.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.DesignerControlCollectionCodeDomSerializer.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewRowCollectionCodeDomSerializer.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TableLayoutControlCollectionCodeDomSerializer.cs

I think this is the last public serializer that wasn't annotated (counting open PRs)
- Enable nullability in `CollectionCodeDomSerializer`
- Enable nullability in `DataGridViewRowCollectionCodeDomSerializer`
- Enable nullability in `TableLayoutControlCollectionCodeDomSerializer`

Enable nullability in CollectionCodeDomSerializer and child classes

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewColumnCollectionDialog.cs

- Enhance nullable annotations in `DataGridViewColumnCollectionDialog`, removing almost all in the process `!`
- Replace `Hastable`s with `Dictionary`s and a `HashSet` (contributes to #8143)

Enhance nullable annotations in DataGridViewColumnCollectionDialog and replace Hashtables

---

src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DateTimeEditor.DateTimeUI.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DateTimeEditor.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/MaskedTextBoxTextEditor.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ShortcutKeysEditor.ShortcutKeysUI.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ShortcutKeysEditor.cs

Those should be straightforward.
- Enable nullability in `ShortcutKeysEditor`
- Enable nullability in `DateTimeEditor`
- Enable nullability in `MaskedTextBoxTextEditor`

Enable nullability in several UITypeEditors

---

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs

- Enable nullability in some PropertyGridView members.

Enable nullability in some PropertyGridView members

---

src/System.Windows.Forms/src/PublicAPI.Shipped.txt
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumn.cs

- Enable nullability in remaining DataGridViewColumn members.

Enable nullability in remaining DataGridViewColumn members

---

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MergePropertyDescriptor.cs
src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiPropertyDescriptorGridEntry.cs

- Enable nullability in MergePropertyDescriptor.

Enable nullability in MergePropertyDescriptor

---

src/System.Windows.Forms.Design/src/System/Drawing/Design/ColorEditor.ColorPalette.cs
src/System.Windows.Forms.Design/src/System/Drawing/Design/ColorEditor.ColorUI.cs
src/System.Windows.Forms.Design/src/System/Drawing/Design/ColorEditor.StandardColorComparer.cs

- Annotate `ColorEditor.ColorPalette` and `ColorEditor.StandardColorComparer`
- Make `ColorEditor.StandardColorComparer` an `IComparer<Color>`

Add missing NRT annotations for ColorEditor nested classes

---

src/System.Drawing.Common/tests/Drawing2D/GraphicsPathTests.cs
src/System.Drawing.Common/tests/GlobalUsings.cs
src/System.Drawing.Common/tests/Helpers.cs
src/System.Drawing.Common/tests/System.Drawing.Common.Tests.csproj
src/System.Windows.Forms.Design/tests/UnitTests/CodeDomHelpers.cs
src/System.Windows.Forms.Design/tests/UnitTests/GlobalUsings.cs
src/System.Windows.Forms.Design/tests/UnitTests/System.Windows.Forms.Design.Tests.csproj
src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/EmbeddedResourceTests.cs
src/System.Windows.Forms.Primitives/tests/TestUtilities/Extensions/AssertExtensions.cs
src/System.Windows.Forms.Primitives/tests/TestUtilities/FluentAssertions/FluentAssertExtensions.cs
src/System.Windows.Forms.Primitives/tests/TestUtilities/FluentAssertions/PointFAssertions.cs
src/System.Windows.Forms.Primitives/tests/TestUtilities/FluentAssertions/RectangleFAssertions.cs
src/System.Windows.Forms.Primitives/tests/TestUtilities/System.Windows.Forms.Primitives.TestUtilities.csproj
src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/Oleaut32/VARIANTTests.cs
src/System.Windows.Forms/tests/UnitTests/GlobalUsings.cs
src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/EmbeddedResourceTests.cs

Xunit removed some public constructors on exception objects and moved them to static factory methods. Changed a few of the usages.
Xunit validation of arrays that aren't 0 based also changed (Xunit validates them correctly). Changed VARIANT tests to compare the output of Marshal and VARIANT.ToObject directly to address this. Removed checking against non-equivalent expected arrays in the non-0 case.
Added FluentAssertions in more of the test projects and moved RectangleF and PointF validation to that model.

Handle Xunit changes

---

src/System.Windows.Forms/src/System/Windows/Forms/Keys.cs

Fixes designer issue #https://github.com/microsoft/winforms-designer/issues/5383
- 
- Switch the order of the Enum value
- 
- 
- manual 
-

fix issue Short keys are inconsistent in Shortcut Keys property dialog and form designer

---

src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
src/System.Windows.Forms.Design/src/System/Drawing/Design/ToolboxComponentsCreatingEventArgs.cs
src/System.Windows.Forms.Design/src/System/Drawing/Design/ToolboxItemCollection.cs

- Enable nullability in `ToolboxItemCollection`
- Enable nullability in `ToolboxComponentsCreatingEventArgs`

Enable nullability in missing Toolbox classes

---

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.CheckBoxPropertyLine.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.EditorPropertyLine.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.HeaderLine.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.Line.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.LineInfo.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.MethodLine.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.PanelHeaderLine.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.PropertyLine.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.SeparatorLine.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.TextBoxPropertyLine.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.TextLine.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.cs
src/System.Windows.Forms.Primitives/src/System/ComponentModel/MemberDescriptorExtensions.cs

As discussed in #9422 @dreddy-work 
- Refactor `DesignerActionPanel` `Line` and `LineInfo` objects to increase the number of immutable fields in `Line` objects. The goal is to have a design that works better with NRT annotations

Refactor DesignerActionPanel

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FlowLayoutPanelDesigner .cs

Fixes #10082 
- Set DesignerTransaction to null after submitting CleanDesignerTransaction
- When there is no substantial positional movement of the internal control, cancel the DesignerTransaction directly to avoid _insertionIndex=-1 causing an exception in code line [while (_insertionIndex < _childInfo.Length - 1 && _childInfo[_insertionIndex].InSelectionCollection) ](https://github.com/dotnet/winforms/blob/e6d1ad98adb7825970935942de483273912c82f1/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FlowLayoutPanelDesigner%20.cs#L593C8-L593C109)
- All of the control can be selected normally in Demo project
- Yes
- Minimal
https://github.com/dotnet/winforms/assets/108860782/e838fc43-2456-4b6f-8496-a2a5fcd843fe
- Manually
-  .net  9.0.0-alpha.1.23508.5

Clean DesignerTransaction after DesignerTransaction committed

---

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/GridErrorDialog.cs
src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs

- Enable nullability in remaining PropertyGridView members.

Enable nullability in remaining PropertyGridView members

---

src/System.Drawing.Common/src/System/Drawing/DrawingCom.ComWrappers.cs

Runtime reverted the change in following PR.
https://github.com/dotnet/runtime/pull/91983
@JeremyKuhne as FYI.

Updating QueryInterface API calls

---

Directory.Build.props
Directory.Build.targets
eng/CodeCoverage.proj
global.json
pkg/Microsoft.Private.Winforms/Microsoft.Private.Winforms.csproj
src/Accessibility/src/Accessibility.ilproj

Updating TFM for WinForms assemblies.

Update WinForms assembly TFM to net9.0

---

src/System.Windows.Forms/src/System/Windows/Forms/ColumnHeader.cs
src/System.Windows.Forms/src/System/Windows/Forms/ListView.cs
src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemDetailsAccessibleObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewSubItem.ListViewSubItemAccessibleObject.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewItem.ListViewItemDetailsAccessibleObjectTests.cs

Fixes #7492
- 
- Change the way to get childAO of a ListViewItem
- 
- Yes 
- 
- Manual and Automation 
- 
8.0.0-rc.1.23376.5

fix [Accessibility] SubItems displayed incorrectly in Inspect or AccessibilityInsights after a column is removed from the ListView. #7492

---

src/System.Windows.Forms/src/PublicAPI.Shipped.txt
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewImageCell.cs

- Enable nullability in DataGridViewImageCell.

Enable nullability in DataGridViewImageCell

---

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.CheckBoxPropertyLine.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.EditorPropertyLine.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.HeaderLine.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.MethodLine.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.PropertyLine.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.TextBoxPropertyLine.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.TextLine.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.cs

Fix a bug introduced in #10035
Fixes #10095
Fixes #10097
I refactored a bit the code to make the mistake more obvious.
- HeaderLine being a TextLine, HeaderInfo also needs to be a TextInfo
- I ran DemoConsole and verified manually that the bugs no longer reproduce

Fix a bug introduced in the DesignerActionPanel refactoring

---

azure-pipelines-richnav.yml
eng/pipelines/post-build.yml

The RichNav team reached out to me to update the "environment", this was done in arcade and flowed to winforms but the pipeline was overriding the value here.
Also deleted a duplicated RichCodeNavIndexer@0 task in the repo-local post-build.yml which is not actually used.

Update richCodeNavigationEnvironment in pipelines

---

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.CheckBoxPropertyLine.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.DesignerActionPanelHeaderItem.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.EditorPropertyLine.EditorButton.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.EditorPropertyLine.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.Line.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.MethodLine.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.PanelHeaderLine.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.PropertyLine.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.TextBoxPropertyLine.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.TextLine.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.TypeDescriptorContext.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.cs
src/System.Windows.Forms/src/PublicAPI.Shipped.txt
src/System.Windows.Forms/src/System/Windows/Forms/Design/IWindowsFormsEditorService.cs

Now that #10035 is merged, my plan is to annotate just `DesignerActionPanel`, and then rebase #9367 to remove the annotation changes I made on it there, but keep all the other changes with their review.
My changes here include the modification of the annotation of a public interface. The two internal implementers of method `IWindowsFormsEditorService.DropDownControl` cannot handle a null `Control` as argument, and nothing in the docs said the implementers should prepare for that scenario
- Enable nullability in `DesignerActionPanel`
- Update nullability annotations of interface `IWindowsFormsEditorService`

Enable nullability in DesignerActionPanel

---

src/System.Windows.Forms/src/PublicAPI.Shipped.txt
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowHeaderCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTopLeftHeaderCell.cs

- Enable nullability in DataGridViewRowHeaderCell.

Enable nullability in DataGridViewRowHeaderCell

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/InputLanguageTests.cs

This test has started failing after CI machine update. This is blocking dependency code flow among other PRs. I've created https://github.com/dotnet/winforms/issues/10150 to track investigating and re-enabling this test.

[release/8.0] Disable N'Ko in InputLanguageTests

---

src/System.Windows.Forms/src/PublicAPI.Shipped.txt
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnHeaderCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTopLeftHeaderCell.cs

- Enable nullability in DataGridViewColumnHeaderCell.

Enable nullability in DataGridViewColumnHeaderCell

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DesignerActionBehavior.cs

Extracted from #9367
- Modernise DesignerActionBehavior
- Enable nullability in `DesignerActionBehavior`

Enable nullability in DesignerActionBehavior

---

src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.CollectionEditorCollectionForm.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.CollectionForm.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.FilterListBox.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.PropertyGridSite.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.SplitButton.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.cs
src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/CollectionEditorTests.cs
src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/CollectionFormTests.cs

In the process, I had to revisit the annotations of `CollectionEditor.CollectionForm`. These are new in .NET 8. and some annotations look incorrect...
- Enable nullability in `CollectionEditor`
- Replace `ArrayList`s with `List<T>`s in `CollectionEditor` (contributes to #8140)

Enable nullability in CollectionEditor

---

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignSurface.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignSurfaceManager.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionService.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionUIService.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/BasicDesignerLoader.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ComponentCodeDomSerializer.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ServiceContainerExtensions.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ComponentTray.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DocumentDesigner.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripInSituService.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripKeyboardHandlingService.cs

`IServiceContainer` has methods that take a type as argument. We introduce here a generic extension method to encapsulate the type argument
- Introduce method `AddService<T>(this IServiceContainer serviceContainer, T serviceInstance)`
- Introduce method `AddService<T>(this IServiceContainer serviceContainer, ServiceCreatorCallback callback)`
- Introduce method `RemoveService<T>(this IServiceContainer serviceContainer)`
- Use the new methods across the codebase

Introduce generic ServiceContainerExtensions.AddService and RemoveService

---

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyGridView.cs

PR https://github.com/dotnet/winforms/pull/10088/ had changed nullability of the argument in - https://learn.microsoft.com/dotnet/api/system.windows.forms.design.iwindowsformseditorservice.dropdowncontrol?view=windowsdesktop-7.0
I'm updating implementation of this service in the PropertyGrid to match the new definition and to handle a null argument gracefully. This method displays a control in a property grid's value cell's dropdown holder, if there is no control, then there is nothing to show. This method is invoked from the property grid and property grid is not expecting or handling a null reference exception any more gracefully than "do nothing", so I opted for immediately returning from this method if a null is passed in.

Made argument non-nullable to match the new interface definition for IWindowsFormsEditorService.DropDownControl

---

src/System.Windows.Forms/src/PublicAPI.Shipped.txt
src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewAutoSizeColumnsModeEventArgs.cs

- Enable nullability in some DataGridView.Methods members.

Enable nullability in some DataGridView.Methods members

---

src/System.Windows.Forms/src/PublicAPI.Shipped.txt
src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewButtonCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.DataGridViewCheckBoxCellFlags.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewEditingCell.cs

- Enable nullability in some DataGridViewCheckBoxCell members.

Enable nullability in some DataGridViewCheckBoxCell members

---

src/System.Windows.Forms/src/System/Windows/Forms/HtmlElementCollection.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HtmlDocumentTests.cs

Fixes #10188 
When indexing into a `HtmlElementCollection` via `string`, there is a chance that the id given does not exist in which case we will get null back for the `IDispatch`. Add a null check to the string indexing method to ensure it is nonnull before querying it. If the `IDispatch` is null, we will simply return null as we did before. 
Note that indexing via `int` should not have this same issue since we already do bounds checking and throw if there is any illegal argument.

Ensure Indexing HtmlElementCollection By String Doesn't Throw

---

src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewComboBoxCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTextBoxCell.cs

Steps:
Run a debug build of WinformsControlsTest app,
open the DataGridView page and resize columns or rows
Result: an Assert.
We assumed that lifetime of editing control is not longer than that of its container panel, and tested only the editing control for null. However their lifetimes are not tied explicitly, it's safer to have an explicit null-check. It's unlikely that anyone was processing this NRE other than by ignoring it, as it happens on mouse move.
Another change is a removal of null check for EditingPanel get property as this property allocated the panel on the first access.

Removed a noisy Debug.Assert

---

src/System.Windows.Forms/src/System/Windows/Forms/HtmlDocument.cs
src/System.Windows.Forms/src/System/Windows/Forms/HtmlElement.cs
src/System.Windows.Forms/src/System/Windows/Forms/HtmlElementCollection.cs
src/System.Windows.Forms/src/System/Windows/Forms/HtmlWindow.cs
src/System.Windows.Forms/src/System/Windows/Forms/HtmlWindowCollection.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HtmlWindowTests.cs

Fixes https://github.com/dotnet/winforms/issues/10193
- Add null check to `HtmlWindow.Opener` and `HtmlWindow.WindowFrameElement` and add regression tests
- Also went ahead and looked through HTMLX files and added additional null checks where it is valid to receive an empty pointer and using it would result in null reference.

Harden Against Null in HTMLX files

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignBindingPicker.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerUtils.cs

This replaces #9381 now that #10091 and #10092 are merged.
I also considered reusing that PR, but it was too different. If you feel like this goes against the decision made [here](https://github.com/dotnet/winforms/issues/8342#issuecomment-1769354111), feel free to close this PR. My take on it is that it finishes already started work.
- Enable nullability in internal helper `DesignerUtils`

Enable nullability in DesignerUtils

---

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionUI.DesignerActionToolStripDropDown.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionUI.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DesignerActionGlyph.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DesignerActionKeyboardBehavior.cs

Extracted from #9367
- Enable nullability in `DesignerActionUI`
- Enable nullability in `DesignerActionKeyboardBehavior`

Enable nullability in DesignerActionUI

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewColumnCollectionDialog.cs
src/System.Windows.Forms/src/PublicAPI.Shipped.txt
src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.DataGridViewCellAccessibleObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnCollection.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.DataGridViewRowAccessibleObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRow.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewTopLeftHeaderCell.DataGridViewTopLeftHeaderCellAccessibleObject.cs

- Enable nullability in remaining DataGridViewColumnCollection members.

Enable nullability in remaining DataGridViewColumnCollection members

---

src/System.Windows.Forms/src/PublicAPI.Shipped.txt
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCheckBoxCell.cs

- Enable nullability in remaining DataGridViewCheckBoxCell members.

Enable nullability in remaining DataGridViewCheckBoxCell members

---

src/System.Windows.Forms.Primitives/src/System/ComponentModel/TypeConverterHelper.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/PaddingConverter.cs
src/System.Windows.Forms/src/System/Resources/ResXDataNode.cs
src/System.Windows.Forms/src/System/Resources/ResXResourceReader.cs
src/System.Windows.Forms/src/System/Resources/ResXSerializationBinder.cs
src/System.Windows.Forms/src/System/Windows/Forms/BindingSource.cs
src/System.Windows.Forms/src/System/Windows/Forms/Control.ActiveXImpl.cs
src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
src/System.Windows.Forms/src/System/Windows/Forms/LinkArea.LinkAreaConverter.cs
src/System.Windows.Forms/src/System/Windows/Forms/LinkConverter.cs
src/System.Windows.Forms/src/System/Windows/Forms/LinkUtilities.cs
src/System.Windows.Forms/src/System/Windows/Forms/SelectionRangeConverter.cs
src/System.Windows.Forms/src/System/Windows/Forms/TableLayoutPanelCellPositionTypeConverter.cs

There is no issue tied to this, but I encountered several times pieces of code that could use more recent overloads of `string.Split` to reduce allocations, and I thought I'd let the team decide if it's worth the effort or not.
I split the work in four distinct commits. Each one can be spun out in a separate PR or simply discarded
- Use `StringSplitOptions.TrimEntries` where relevant. This includes a bit of cleanup in BindingSource that helps readability quite a bit
- Remove useless usage of string.Split. Sometimes it's not even more readable anyway
- Introduce and use TypeConverterHelper. This factorise a pattern often found in `TypeConverter`s in a way that reduces allocations
- Remove allocs in LinkUtilities.GetIELinkBehavior

Review usage of string.Split across codebase

---

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/BinaryFormattedObjectExtensions.cs

This is inspired by https://github.com/dotnet/winforms/pull/10114

Constructor for `Decimal` expects a ReadOnlySpan, updating a call site.

---

src/System.Windows.Forms/src/PublicAPI.Shipped.txt
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewColumnHeaderCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewHeaderCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewRowHeaderCell.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewHeaderCellTests.cs

- Enable nullability in DataGridViewHeaderCell.

Enable nullability in DataGridViewHeaderCell

---

src/System.Windows.Forms/src/System/Windows/Forms/HtmlWindow.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HtmlWindowTests.cs

Fixes https://github.com/dotnet/winforms/issues/10218
We previously changed internal `NativeHtmlWindow` to type `AgileComPointer` after removing old `IHTMLWindow2` Interface definition and did not update `DomWindow` to return the interface like it always had been. This was missed due to `DomWindow` being of type `object`. I've updated code to return the interface as well as added regression test for this.

Return Interface for HtmlWindow.DomWindow

---

src/System.Windows.Forms/src/System/Windows/Forms/ReadOnlyControlCollection.cs
src/System.Windows.Forms/src/System/Windows/Forms/TypedControlCollection.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.ControlCollection.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridView.DataGridViewControlCollectionTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Form.ControlCollectionTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MdiClient.ControlCollectionTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ReadOnlyControlCollectionTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/SplitContainer.SplitContainerTypedControlCollectionTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TypedControlCollectionTests.cs

- Add some tests for classes that inherit from Control.ControlCollection.

Add some tests for classes that inherit from Control.ControlCollection

---

src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroupConverter.cs

- Replace ArrayList with generic list in ListViewGroupConverter.

Replace ArrayList with generic list in ListViewGroupConverter

---

eng/Versions.props

MicrosoftNETTestSdkVersion holds reference to NewtonsoftJsonVersion 9.0.1 which is out of compliance.

[release/6.0] Upgrade MicrosoftNETTestSdkVersion

---

src/System.Windows.Forms/src/System/Windows/Forms/DataGridView.Methods.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellCancelEventArgs.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellEventArgs.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellFormattingEventArgs.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellMouseEventArgs.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellPaintingEventArgs.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellParsingEventArgs.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellValidatingEventArgs.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCellValueEventArgs.cs
src/System.Windows.Forms/src/System/Windows/Forms/IDataGridViewCellEventArgs.cs

While working on #9726, I encountered this factorisation opportunity. This cleans up the code and optimises it by getting the throw expressions out of the way.
As a follow-up, if the team is willing to modify the error messages, we could use `ArgumentOutOfRangeException` throw helpers inside the new method, but this change is less valuable
- Factorise EventArgs index bound checks in `DataGridView` in a dedicated helper method

Introduce a throw helper in DataGridView.Methods

---

src/System.Windows.Forms.Primitives/src/Windows/Win32/System/Com/StandardDispatch.cs
src/System.Windows.Forms.Primitives/src/Windows/Win32/UI/Accessibility/AccessibleDispatch.cs
src/System.Windows.Forms.Primitives/tests/UnitTests/Windows/Win32/UI/Accessibility/AccessibleDispatchTests.cs
src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.AccessibleDispatchAdapter.cs
src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComponentModel/Com2Interop/ComNativeDescriptorTests.cs

Adds IAccessible dispatch support through AccessibleDispatch.
AccessibleObject has the requisite interfaces defined. IAccessible is currently just stubbed out (all return E_NOTIMPL). When IAccessible is implemented and `IManagedWrapper` is added to AccessibleObject, it will get IDispatch support.

Add IAccessible dispatch support

---

src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ItemAccessibleObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/ListViewGroup.ListViewGroupAccessibleObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/ListViewItem.ListViewItemBaseAccessibleObject.cs

Fixes https://github.com/dotnet/winforms/issues/10259
Fixes https://github.com/dotnet/winforms/issues/10258
These AccessibleObjects were added in early .NET Core and did not exist in Framework. Since these objects do not have windows handles, we should be returning `HWND.Null` (0) on `GetPropertyValue(UIA_PROPERTY_ID.UIA_NativeWindowHandlePropertyId)`. We had recently changed to stop doing legacy marshaling for `GetPropertyValue`, which brought this to light. Did manual testing to verify issue no longer repros.

Return 0 on UIA_PROPERTY_ID.UIA_NativeWindowHandlePropertyId for Objects with No Handle

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DropSourceBehavior.BehaviorDataObject.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DropSourceBehavior.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/ToolStripPanelSelectionBehavior.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FlowLayoutPanelDesigner .cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ParentControlDesigner.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TabControlDesigner.cs

Finish work started in #8673 
Related: #8140
Now that `DropSourceBehavior` is passed a `List<IComponent>` in its constructor, we can update `BehaviorDataObject` to do the same instead of using `ICollection`
- Refactor `BehaviorDataObject.DragComponents` to be a `List<IComponent>` and update code accordingly
- Another small `BehaviorDataObject` refacto while we're touching this code, but in a separate commit

Use List<T> instead of ICollection in BehaviorDataObject

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/ResizeBehavior.cs

- Refactor `ResizeBehavior` to use `List<T>` instead of `ArrayList`
- Refactor `ResizeComponent.resizeControl` from `object` to `Control` to remove casting
Related: #8140

Refactor `ResizeBehavior` to use `List<T>` instead of `ArrayList`

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/TableLayoutPanelBehavior.cs

I fixed the field name in the same PR (in a separate commit) to make it easier to review all the call sites of this field
- Replace `ArrayList` `styles` with `List<TableLayoutStyle>` `_styles` in TableLayoutPanelBehavior

Replace ArrayList with List<T> in TableLayoutPanelBehavior

---

src/System.Windows.Forms.Primitives/src/Interop/OleAut32/Interop.VARIANT.cs
src/System.Windows.Forms.Primitives/src/Windows/Win32/UI/Accessibility/UIAHelper.cs
src/System.Windows.Forms/src/System/Windows/Forms/Control.ControlAccessibleObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.ControlItem.ControlItemAccessibleObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/LabelEditAccessibleObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/ListBox.AccessibleObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/ListBox.ItemAccessibleObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/ListView.ListViewAccessibleObject.cs
src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListBoxes.Designer.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/ListBoxAccessibleObjectTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/ListVIew.ListViewAccessibleObjectTests.cs

We didn't handle multiple sections in accessibility tools correctly, for ListBox, we could add items to selection but not remove items from selection, I added that functionality.

Fixes in Selection pattern for ListBox and ListView items

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ParentControlDesigner.cs

- Replace `ArrayList` styles with `List<T>` in `ParentControlDesigner`
- Change return type of internal method `ParentControlDesigner.GetComponentsInRect` to `List<Control>` to save some allocations

Replace ArrayList with List<T> in ParentControlDesigner

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TableLayoutPanelDesigner.cs

I fixed the impacted field name in the same PR (in a separate commit) to make it easier to review all its call sites
- Replace all `ArrayList`s with `List<T>` in TableLayoutPanelDesigner

Replace ArrayList with List<T> in TableLayoutPanelDesigner

---

src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/BinaryEditor.BinaryUI.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ByteViewer.cs
src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ByteViewerTests.cs

- Enable nullability in `ByteViewer`
- Cleanup code and remove most allocations when drawing

Enable nullability in ByteViewer and remove allocations when drawing

---

src/System.Windows.Forms.Primitives/src/Windows/Win32/Foundation/AgileComPointer.cs
src/System.Windows.Forms.Primitives/tests/UnitTests/Windows/Win32/AgileComPointerTests.cs
src/System.Windows.Forms/src/System/Windows/Forms/AccessibleObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/AxHost.AxContainer.cs
src/System.Windows.Forms/src/System/Windows/Forms/HtmlDocument.cs
src/System.Windows.Forms/src/System/Windows/Forms/HtmlElement.cs
src/System.Windows.Forms/src/System/Windows/Forms/HtmlWindow.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HtmlWindowTests.cs

Fixes #10261
When obtaining a COM pointer to an object that was created on a different thread, we get a proxy so we cannot just directly compare for identity like we had been doing with maintaining `_originalObject` in `AgileComPointer`. If we want to know identity, we need to register the COM pointers in the GIT, query for the IUnknowns on the _same_ thread, and then compare the values.
As a consequence of this, updated `GetHashCode()` on HTMLX. We can no longer get the hashcode the same manner we were doing so before (getting the interface and using the value) because it would change depending on the thread if we had an AgileComPointer created from a proxy. So, we will now get the initial value of the `AgileComPointer` and use that for the hash code to make it constant. 
Added a …

Always Query for IUnknown when Comparing AgileComPointer for Identity

---

src/System.Windows.Forms.Design/src/System/Drawing/Design/IconEditor.cs

Fix #[5092](https://github.com/dotnet/winforms/issues/5092)
-  No
- Minimal
The icon property of the NotifyIcon control cannot be modified
The icon property of the NotifyIcon control can be modified
- Manually (Verified in Scratch project)
- .net 9.0.0-alpha.1.23510.12

fix bug Painting bug in IconEditor

---

eng/Versions.props

Partially reverted https://github.com/dotnet/winforms/pull/9654/files, to move forward https://github.com/dotnet/winforms/pull/10114 
After the change, according to the Build.binlog, command line build uses Roslyn binaries that are distributed with arcade - .dotnet\sdk\9.0.100-alpha.1.23511.2\Roslyn\bincore\csc.dll
Microsoft (R) Visual C# Compiler version 4.8.0-3.23477.1 (a0f63522)
Commit associated with this version was merged in September - https://github.com/dotnet/roslyn/commit/a0f63522, after the [commit](https://github.com/dotnet/roslyn/pull/69412) where the the inline arrays were introduced, which was in August.

unpin the csc version, use compiler that comes with the arcade instead

---

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerBase.cs
src/System.Windows.Forms.Design/src/System/Resources/Tools/StronglyTypedResourceBuilder.cs
src/System.Windows.Forms.Primitives/src/Microsoft/VisualStudio/Shell/ICategorizeProperties.cs
src/System.Windows.Forms.Primitives/src/Microsoft/VisualStudio/Shell/IProvidePropertyBuilder.cs
src/System.Windows.Forms.Primitives/src/Microsoft/VisualStudio/Shell/IVSMDPerPropertyBrowsing.cs
src/System.Windows.Forms.Primitives/src/Microsoft/VisualStudio/Shell/IVsPerPropertyBrowsing.cs
src/System.Windows.Forms.Primitives/src/System/CharacterConstants.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Automation/UiaTextProvider.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/BinaryFormattedObjectExtensions.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/DeviceContextExtensions.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/IExtender.cs
src/System.Windows.Forms.Primitives/src/Windows/Win32/Foundation/IID.cs
src/System.Windows.Forms.Primitives/src/Windows/Win32/System/Com/IComCallableWrapper.cs
src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/Oleaut32/SAFEARRAYTests.cs
src/System.Windows.Forms.Primitives/tests/UnitTests/Windows/Win32/System/Com/ComScopeTests.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataObject.BitmapBinder.cs
src/System.Windows.Forms/src/System/Windows/Forms/DateTimePicker/DateTimePicker.cs
src/System.Windows.Forms/src/System/Windows/Forms/GroupBox.cs
src/System.Windows.Forms/src/System/Windows/Forms/GroupBoxRenderer.cs
src/System.Windows.Forms/src/System/Windows/Forms/MonthCalendar/MonthCalendar.cs
src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Input/KeyboardSimulator.cs
src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Input/MouseSimulator.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs

This is the same thing that was done in dotnet/runtime#93125
- Use collection expressions to init spans where possible

Use collection expressions to init spans where possible

---

src/Microsoft.VisualBasic/tests/IntegrationTests/VisualBasicRuntimeTest/Program.cs
src/System.Drawing.Common/src/System/Drawing/Font.cs
src/System.Drawing.Common/src/System/Drawing/Imaging/MetafileHeader.cs
src/System.Drawing.Common/src/System/Drawing/Printing/PaperSize.cs
src/System.Windows.Forms/src/System/Resources/ResXResourceReader.cs
src/System.Windows.Forms/src/System/Windows/Forms/AxHost/AxHost.cs
src/System.Windows.Forms/src/System/Windows/Forms/Buttons/ButtonInternal/CheckBoxBaseAdapter.cs
src/System.Windows.Forms/src/System/Windows/Forms/ComboBox/ComboBox.ComboBoxChildNativeWindow.cs
src/System.Windows.Forms/src/System/Windows/Forms/ComboBox/ComboBox.cs
src/System.Windows.Forms/src/System/Windows/Forms/Containers/ContainerControl.cs
src/System.Windows.Forms/src/System/Windows/Forms/Containers/SplitContainer.cs
src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
src/System.Windows.Forms/src/System/Windows/Forms/ControlBindingsCollection.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataBinding/Binding.BindToObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataBinding/Binding.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridView/DataGridView.AccessibleObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridView/DataGridView.DataConnection.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridView/DataGridView.HitTestInfo.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridView/DataGridView.Methods.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataGridView/DataGridView.cs

This changes some of the code (primarily DataGrid) to match the desired code style with line breaking on long logical statements.
To align conceptually the logical operators should be at the beginning of the line when breaking long statements.
When considering how to break lines, logical conditions grouped by a specific set of parentheses should either all be broken out into separate lines or kept together on a single line. To show nesting, statements should be indented to match the parenthetical nesting, but parentheses should not get their own line.
Some examples:
``` C#
if (_trackColumn != previousColumnIndex
&& !(previousColumnIndex == -1 && hti._col == _trackColumn)
&& (dataGridViewColumnNext is null || _trackColumn != dataGridViewColumnNext.Index))
```
And:
``` C#
if (Focused
&& …
```

Move && and || to front of lines

---

src/System.Design/src/System.Design.Forwards.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/NavigationalTableLayoutPanel.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/StyleCollectionEditor.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/StyleCollectionEditor.resx
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/StyleEditorForm.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/xlf/StyleCollectionEditor.cs.xlf
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/xlf/StyleCollectionEditor.de.xlf
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/xlf/StyleCollectionEditor.es.xlf
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/xlf/StyleCollectionEditor.fr.xlf
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/xlf/StyleCollectionEditor.it.xlf
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/xlf/StyleCollectionEditor.ja.xlf
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/xlf/StyleCollectionEditor.ko.xlf
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/xlf/StyleCollectionEditor.pl.xlf
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/xlf/StyleCollectionEditor.pt-BR.xlf
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/xlf/StyleCollectionEditor.ru.xlf
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/xlf/StyleCollectionEditor.tr.xlf
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/xlf/StyleCollectionEditor.zh-Hans.xlf
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/xlf/StyleCollectionEditor.zh-Hant.xlf
src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/EmbeddedResourceTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Design/DesignerAttributeTests.cs

Fixes #10213 
- Adding class StyleCollectionEditor，NavigationalTableLayoutPanel.cs and StyleEditorForm.cs
- Due to the missing StyleCollectionEditor, rows and columns cannot be added to the TableLayoutPanel control normally.
- minimal
In [DemoConsole](https://github.com/dotnet/winforms/tree/main/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole) test app of Winforms repo, unable to add columns/rows via the Edit Rows and Columns window of the TableLayoutPanel control.
https://github.com/dotnet/winforms/assets/94418985/8734d29d-5db7-4674-8065-339b38f22e35
- Manually
- .net 9.0.0-alpha.1.23559.1

Fixing issue 10213 by adding missed class StyleCollectionEditor

---

eng/Localize/LocProject.json

This fixes CI failures in https://dev.azure.com/dnceng/internal/_build/results?buildId=2319748&view=logs&s=8942c932-824b-5cec-8f0c-ca2e44dadd6c . We had ported StyleCollectionEditor in https://github.com/dotnet/winforms/pull/10271, but did not updating LocProject.json to include StyleCollectionEditor.xlf

Update LocProj to include StyleCollectionEditor.xlf

---

eng/Localize/LocProject.json

Following up to https://github.com/dotnet/winforms/pull/10346
CI is still failing due to indentation..

Fix indentation in LocProject.json

---

src/System.Windows.Forms/src/System/Windows/Forms/Containers/ContainerControl.cs

This catch is unneeded, its setting a value that never escapes in the case of an exception. This ruins debugging crashes caused by this path and I hit this trying to look at crashes tracked by 1906584 internally.

Remove unneeded catch

---

src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/MainFormControlsTabOrder.cs
src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs
src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolStripSeparatorPreferredSize.cs

Changed to pattern matching and did minor refactor for conditional expression
Related: #2576

Add `ToolStripSeparatorPreferredSize` form in `WinformsControlsTest` for `ToolStripSeparator.GetPreferredSize`

---

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ComponentCache.ResourceEntry.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ComponentCache.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourceCodeDomSerializer.SerializationResourceManager.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourceCodeDomSerializer.cs

As dicussed [here](https://github.com/dotnet/winforms/pull/9419/files#r1253754529)
- Enable nullability in ResourceCodeDomSerializer.SerializationResourceManager
- Fix what looks to be a bug introduced in #8332

Enable nullability in ResourceCodeDomSerializer.SerializationResourceManager

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/TreeView/TreeNode.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs

Fixes #10376
- Fix Clear and Remove after Sort in TreeView. It looks like we broke this in https://github.com/dotnet/winforms/pull/9078 by following https://github.com/dotnet/winforms/pull/9078#discussion_r1187710943. Perhaps we should just bring back the old method instead of using the current approach?

Fix Clear and Remove after Sort in TreeView

---

src/System.Drawing.Common/src/misc/GDI/DeviceContext.cs

Fixes #8728 for System.Drawing.Common
- Use `Stack<T>` for `DeviceContext`

Use generic Stack for DeviceContext

---

src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs

Backport of https://github.com/dotnet/winforms/pull/10377
Servicing was approved over email

[release/8.0] Fix Clear and Remove after Sort in TreeView

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/RichTextBox/RichTextBox.cs
src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/RichTextBoxes.Designer.cs
src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/RichTextBoxes.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs

- Refactor `RichTextBox.Find` to use `EM_FINDTEXT` when checking for kashida instead of relying on internal text.
- Change the WinformsControlsTest/RichTextBoxes to add an example and a find function.
- Add unit tests for find function with table.
Fixes #10322

Refactor `RichTextBox.Find` to use `EM_FINDTEXT` when checking for kashida

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs

Fixes #10397
- Add unit tests "Remove_MultipleLevelsNodes_AfterSort", "Clear_MultipleLevelsNodes_AfterSort" and "Verify_NodeValue_AfterSortAndRemove" to test TreeView after sorting
- Minimal
- Unit tests
- .net 9.0.0-alpha.1.23578.3

Add tests tree view after sorting

---

src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/MainFormControlsTabOrder.cs
src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/CustomComCtl32Button.cs
src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MainForm.cs

Related #6514 
As requested in [PR 10388](https://github.com/dotnet/winforms/pull/10388#discussion_r1408566765):
- Creates a sample on `WinformsControlsTest` for rendering a custom border on a button whose style is defined by the OS. The custom border is darker than the default one when visual styles is enabled;
- Makes the main view be rendered with a minimum of 3 columns of buttons.
- None
- No
- Minimal
- Manual
- 9.0.100-alpha.1.23511.2

Issue 6514 sample renderer for winforms control test

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripDesignerUtils.cs

Small refactor of `ToolStripDesignerUtils` to remove `ArrayList` usage

---

src/System.Windows.Forms/src/System/Windows/Forms/OLE/DragDropHelper.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DropSource.cs
src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/DragDropTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DragDropHelperTests.cs

- Fix drag and drop related spelling mistakes.
- Fix `_lastGiveFeedbakEventArgs` and rename to `_lastGiveFeedbackEventArgs`.
- Fix test method names like *`ReturnsExptected` and rename to *`ReturnsExpected`.
- None
- No
- None

Fix drag and drop related spelling mistakes

---

src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
src/System.Windows.Forms/src/System/Windows/Forms/Layout/Containers/ContainerControl.cs
src/System.Windows.Forms/src/System/Windows/Forms/Layout/Containers/SplitContainer.cs

I noticed this while working on another PR. I updated all callsites accordingly.
- Use `NotNullWhenAttribute` on method `Contains` of class `Control`

Improve NRT annotations for Control.Contains

---

src/System.Windows.Forms/src/PublicAPI.Shipped.txt
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewComboBoxCell.cs

- Enable nullability in remaining DataGridViewComboBoxCell members.

Enable nullability in remaining DataGridViewComboBoxCell members

---

src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider/ErrorProvider.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ErrorProviderTests.cs

Fix `ErrorProvider.HasErrors` so maintains correct value

---

CONTRIBUTING.md

- Fix coding style link in CONTRIBUTING.md

Fix coding style link in CONTRIBUTING.md

---

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Automation/UiaTextProvider.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Automation/UiaTextRange.cs
src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/Automation/UiaTextProviderTests.cs

Visual Studio shows CA1822 warning that a method could be made static

Get rid of CA1822 in UiaTextProvider

---

src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewComboBoxEditingControl.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewTextBoxEditingControl.cs

Fix #10343
Related to [PR_7349](https://github.com/dotnet/winforms/pull/7349)
Take a look here this [PR_7349](https://github.com/dotnet/winforms/pull/7349) had made
Same as this:
https://github.com/dotnet/winforms/pull/7349/files#diff-2cdcad323e7cd83529f6ded1cfd60aa6906ccbb32755221d36cdb67f72b507c0L306-L315
We can see this [PR_7349](https://github.com/dotnet/winforms/pull/7349)  was to address memory leaks.
Indeed the code here was problematic because if there are no Accessibility Client listening to then there is no need to create AccessibilityObject
``` c#
protected override void OnHandleCreated(EventArgs e)
{
base.OnHandleCreated(e);
if (IsHandleCreated)
{
// The null-check was added as a fix for a https://github.com/dotnet/winforms/issues/2138 …
```

fix [Accessibility] Accessibility Insights tool keeps loading when mouse-over DataGridView #10343

---

src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs

When receiving dropped data the COM IDataObject was not adding a ref count as appropriately. (The RCW adds a ref, but we were also releasing it.)
This causes random memory corruption, and crashes .NET.
Fixes #10470

Fix RichTextBox drag and drop

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/MultiPropertyDescriptorGridEntry.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/MultiSelectRootGridEntry.PropertyMerger.cs

Hopefully this one doesn't step on your toes @gpetrou. Happy to close it if you prefer handling it yourself
- Enable nullability in `MultiSelectRootGridEntry.PropertyMerger`

Enable nullability in MultiSelectRootGridEntry.PropertyMerger

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.DesignerControlCollectionCodeDomSerializer.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FlowLayoutPanelDesigner .cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FlowPanelDesigner.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TabControlDesigner.cs

- Replace `ArrayList` with `List<IComponent>` in `ControlDesigner`
- Replace `ArrayList` with `List<Control>` in `FlowLayoutPanelDesigner`
- ~~Replace `ArrayList` with `List<SnapLine>` in `FlowPanelDesigner`~~ see https://github.com/dotnet/winforms/pull/10432#issuecomment-1841717995
- Replace `ArrayList` with `List<IComponent>` in `TabControlDesigner`

Replace ArrayList with List in several designers

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripMenuItem.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripMenuItemTests.cs

Fixes #10384
- Localizing Keyboard Shortcuts with the CurrentUICulture.
- The shortcuts will be display in windows display language.
- Yes
- Minimal
- Manual 
- 9.0.100-alpha.1.23504.14

Using CurrentUICulture to localize instead of using the CurrentCulture

---

docs/design/anchor-layout-changes-in-net80.md
src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/LocalAppContextSwitchesTest.cs

Fixes #10382 
-  Update the switch `System.Windows.Forms.AnchorLayoutV2` to be disabled by default
- Developers need to opt-in to get the new feature by setting the switch  `System.Windows.Forms.AnchorLayoutV2` value to `true` in the [runtimeconfig.json]
- Minimal

Change default opt-in to false for AnchorLayoutV2 (#9942)

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridView.Methods.cs

Fixes #10428
- Makes UIA consider DataGridView starting row as 1 by default when adding a new row, unless the `LocalAppContextSwitches.DataGridViewUIAStartRowCountAtZero` switch is set to true.
- None
- Yes
- Minimal
- Manual (Narrator)
- 9.0.100-alpha.1.23511.2

Makes UIA consider starting row as 1 (new default) for new lines in DataGridView

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/RichTextBox/RichTextBox.OleCallback.cs

Fixes #8903 
- The RichTextBox behaves differently in the cross-process scenario and the drag image manager doesn't automatically synthesize a call to DragLeave on drop when the Effect is set to None, like it does in the in-process scenario, leaving a drag image artefact.
- Hide the RichTextBox drag image and drop description if the application sets the Effect to None.
- Fixes a drag image artefact that occurs when dropping onto the RichTextBox cross-process with an Effect of None.
- No
-
Cross-process behavior on drop when the Effect is set to None.
https://github.com/dotnet/winforms/assets/5017479/784fa0a4-bf5e-44c4-807c-a2ecc1152b7b
In-process behavior on drop when the Effect is set to None. Note how the drag image manager automatically synthesizes a drag leave on drop. I'm very …

Hide the RichTextBox drag image and drop description if the Effect is set to None

---

src/System.Windows.Forms.Primitives/src/Windows/Win32/System/Com/ComSafeArrayScope.cs
src/System.Windows.Forms.Primitives/tests/UnitTests/Windows/Win32/System/Com/ComSafeArrayScopeTests.cs
src/System.Windows.Forms/src/System/Windows/Forms/Accessibility/LabelEditUiaTextProvider.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.ComboBoxUiaTextProvider.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxBase.TextBoxBaseUiaTextProvider.cs

Fixes https://github.com/dotnet/winforms/issues/10443
If the object being placed into a SafeArray is a IDispatch or IUnknown, SafeArray does an `AddRef` on the object (https://learn.microsoft.com/en-us/windows/win32/api/oleauto/nf-oleauto-safearrayputelement#remarks). This means to maintain the correct ref count, we should be releasing the object that we put into the SafeArray. This was missed in `ComSafeArrayScope.CreateFromInterfaceArray`
Before:
After: No AccessibleObject leaks
Note:
This should also fix other AccessibleObject memory leaks that have been noted as .NET 9 regressions.

Release Pointer when Index Setting ComSafeArrayScope

---

src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/DragDrop.Designer.cs

Fixes https://github.com/dotnet/winforms/issues/10449
Re-layout OpenCats and Clear buttons by setting Anchor property
N/A
No
When resizing form, the size of OpenCats and Clear buttons will be increased or decreased.
https://github.com/dotnet/winforms/assets/26474449/8540b1ae-538e-4c37-a2a4-44adeddcbbd6
When decreasing or increasing the size of the current window, as long as buttons are in the current tablelayout cell, they are visible and their size are fixed.
https://github.com/dotnet/winforms/assets/26474449/c2ca4192-0eae-4fbd-9071-14f981878a83

Fix GH issue 10499 by layout current form's controls

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripItem.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemTests.cs

After PR [10321 add ToolStripItem.SelectedChanged event](https://github.com/dotnet/winforms/pull/10321), tester raised a question: whether it is reasonable to fire SelectedChanged event **twice** when selection status turns from unselected to selected **and** from selected to unselected. After discussion we reached an agreement: the newly added API(ToolStripItem.SelectedChanged) should be consistent with framework's , i.e. when selection status turns from unselected to selected we will fire ToolStripItem.SelectedChanged event. but when selection status turns from selected to unselected we will **not**.
See the discussion [here](https://github.com/dotnet/winforms/issues/8548#issuecomment-1862431770)

fix ToolStripItem SelectedChanged event is invoked twice

---

src/System.Drawing.Common/src/System/Drawing/Icon.cs
src/System.Windows.Forms.Design/src/System/Drawing/Design/IconEditor.cs

Fixes #9999
-  Update function Icon.Draw to use targetRect to calculate offset
- The icon property of the NotifyIcon control can be modified
-  No
- Minimal
The icon property of the NotifyIcon control cannot be modified
https://github.com/dotnet/winforms/assets/56664234/dab536e8-e545-4370-a641-0008ba2bc5a8
The icon property of the NotifyIcon control can be modified
- Manually (Verified in Demo project)
- .net 9.0.0-alpha.1.23515.3

Fix issue 9999: Update IconEditor to offset the icon within the property grid entry

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/TreeView/TreeView.TreeViewAccessibleObject.cs

Fixes #10485
There is something wrong with the base method `BoundingRectangle`.
So override this method in the same manner that `TextBox` did
https://github.com/dotnet/winforms/blob/9e2fc95fca4e6d18444c819b35bb1338ac6ca63d/src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListBoxes/ListBox.AccessibleObject.cs#L31-L32C10
- Yes.  It repro on .NET 8.0 & 7.0
- minimal 
- 
- manual 
- 
- 9.0.0-alpha.1.23623.1

fix bug [Accessibility]Inspect or AccessibilityInsights tool's rectangle can't focus on the entire Treeview with scrollBar

---

eng/pipelines/post-build.yml

Avoids a warning in CI that occurs when attempting to upload test results and none exist.

Only upload test results when tests run

---

src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Dpi/FormDpiTests.cs
src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Dpi/SplitContainerTests.cs
src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Dpi/ToolStripItemTests.Dpi.cs

The `Initialize` method was renamed while integration tests were disabled, so this error was not caught by CI.

Fix dynamic invocation of InitializeStatics

---

Directory.Build.props
Directory.Build.targets
eng/Test.props
eng/Test.targets
src/Microsoft.VisualBasic.Forms/tests/UnitTests/Microsoft.VisualBasic.Forms.Tests.vbproj
src/Microsoft.VisualBasic/tests/UnitTests/Microsoft.VisualBasic.Tests.csproj
src/System.Windows.Forms.Design/tests/UnitTests/System.Windows.Forms.Design.Tests.csproj
src/System.Windows.Forms.Primitives/tests/TestUtilities.Tests/System.Windows.Forms.Primitives.TestUtilities.Tests.csproj
src/System.Windows.Forms.Primitives/tests/TestUtilities/System.Windows.Forms.Primitives.TestUtilities.csproj
src/System.Windows.Forms.Primitives/tests/UnitTests/System.Windows.Forms.Primitives.Tests.csproj
src/System.Windows.Forms.PrivateSourceGenerators/tests/UnitTests/System.Windows.Forms.PrivateSourceGenerators.Tests.csproj
src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/System.Windows.Forms.IntegrationTests.Common.csproj
src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/System.Windows.Forms.UI.IntegrationTests.csproj
src/System.Windows.Forms/tests/InteropTests/System.Windows.Forms.Interop.Tests.csproj
src/System.Windows.Forms/tests/TestUtilities/System.Windows.Forms.TestUtilities.csproj
src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj

- Move all test-related definitions into own Tests.props and Tests.targets.

Move all test-related definitions into own Tests.props and Tests.targets

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxBase.TextBoxBaseAccessibleObject.cs

The `_owner` fiels is a weak reference now, thus comment is outdated.

Removed an outdated comment

---

src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.TextBoxBaseAccessibleObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/TextBoxBase.cs
src/System.Windows.Forms/src/System/Windows/Forms/WinFormsUtils.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Control.ControlAccessibleObjectTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MaskedTextBox.MaskedTextBoxAccessibleObjectTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextBoxBaseAccessibleObjectTests.cs

Backport of https://github.com/dotnet/winforms/pull/10295 to release/8.0
- Add raise ValuePattern.Value property changed event to TextBoxBase.
- ValuePattern.Value property changed event will be sent from TextBox control. 
- When we don't set the accessible name of the textbox or the previous label, the accessible name of the textbox will return "" not the value of textbox.
- Yes
- Minimal
ValuePattern.Value property changed event is not sent from TextBox.
When we make changes to the text in the textbox, it will send the ValuePattern.Value property changed event.
- Manual (Insights)
- 8.0.0-beta.23564.4

[release/8.0] Add ValuePattern.Value changed event to TextBox

---

src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
src/System.Windows.Forms/src/System/Windows/Forms/Controls/Buttons/CheckBox.CheckBoxAccessibleObject.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/CheckBox.CheckBoxAccessibleObjectTests.cs

revert [PR 10533](https://github.com/dotnet/winforms/pull/10533), since it is not a bug.

Revert "fix isssue 10516 [Accessibility] CheckBox control should support ValuePattern property (#10533)"

---

src/System.Windows.Forms/src/System/Windows/Forms/DataObject.cs

Port of #10475 to release.
When receiving dropped data the COM IDataObject was not adding a ref count as appropriately. (The RCW adds a ref, but we were also releasing it.)
This causes random memory corruption, and crashes .NET.

Fix RichTextBox drag and drop (#10475)

---

src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/MultiPropertyDescriptorGridEntry.cs
src/System.Windows.Forms/src/System/Windows/Forms/PropertyGridInternal/PropertyDescriptorGridEntry.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridTests.cs

Fixes #https://github.com/dotnet/winforms/issues/10427
Port of a .NET9 fix - https://github.com/dotnet/winforms/pull/10433
Fixed a typo where we were not referencing the right local variable.
DevExpress can't use expandable property grid entries, i.e. entries where a child value is displayed on the parent line.
- Yes 
-low, this is a very specific scenario
Manual and unit test.

[release/8.0.x] Fix expandable property grid entries

---

eng/CodeAnalysis.test.globalconfig

xUnit1004 comes with a code fix that allows users to remove the `Skip` attribute from a test method using the light bulb. This code fix only works when the diagnostic is enabled. This pull request enables the diagnostic at `silent` severity, which means it applies to the IDE experience but still does not report any diagnostics during a build.

Enable the xUnit1004 refactoring

---

src/System.Windows.Forms/src/System/Windows/Forms/Input/Cursor.cs

call GC.SuppressFinalize(this) for constructors where we don't own the cursor handle so we can avoid being queued for finalization.
Fixes https://github.com/dotnet/winforms/issues/10539

Avoid finalization in Cursor.cs if freeing handle not needed

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/AdapterHelpers.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DragAssistanceManager.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ButtonBaseDesigner.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ComboBoxDesigner.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DateTimePickerDesigner.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FlowPanelDesigner.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FormDocumentDesigner.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/IWrapper.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/LabelDesigner.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ListAdapter.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ParentControlDesigner.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SplitContainerDesigner.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TextBoxBaseDesigner.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripContainerDesigner.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/UpDownBaseDesigner.cs

Kind of related: #8140
Mostly trying to remove `ArrayList` usage through the code base. This code is using a typesafe cast to `ArrayList`, where it can just use IList directly.
We cannot convert to `List<T>` because we have a public API that uses `ArrayList` ParentControlDesigner.AddPaddingSnapLines:
https://github.com/dotnet/winforms/blob/cc1a96870bfb794efc2005b843f3908e422865fe/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ParentControlDesigner.cs#L295-L319
Ultimately it would be great if the public API could be changed to `List<SnapLine>` to be more explicit.

Refactor `SnapLines` to use `IList` directly instead of casting to `ArrayList`

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs

Fix `StackOverflow` in `ControlDesigner`

---

src/System.Windows.Forms/src/System/Windows/Forms/TreeView.TreeViewAccessibleObject.cs

related to [PR_10532](https://github.com/dotnet/winforms/pull/10532)
Fix #10485
Do not use BoundingRectangle method defined on the AccessibleObject class, instead use Win32 API GetWindowRect
Accessibility tools do not have access to the control scroll bars if TreeView shows them.

[release/8.0] [Accessibility]Inspect or AccessibilityInsights tool's rectangle can't focus on the entire Treeview with scrollBar

---

src/System.Drawing.Common/tests/Imaging/ImageCodecInfoTests.cs

Refactoring `ImageCodecInfoTests` to replace `Hashtable` with Generic Dictionary

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ComboBoxDesigner.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ParentControlDesigner.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TabControlDesigner.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripDesigner.cs

In #9408, we forced the `ComponentDesigner.Component` property to be non-null. We noticed this had implications in the method `ControlDesigner.Dispose`. This PR addresses all other such cases that were broken by this PR but 2 instances that will be addressed in followup PRs.

Fix calls to Component in ComponentDesigner.Dispose overrides

---

src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
src/System.Windows.Forms/src/System/Windows/Forms/FormCollection.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ApplicationTests.cs

Fixes #3606
- Replace `foreach` in `OpenForms` iteration.
- Iterate in backward direction.
- Users now can close existing and open new forms in `FormClosing` after `Application.Exit` or`Application.Restart` call.
- MDI users now safely can use `Application.Exit` and `Application.Restart`.
- No
- Minimal
- New ~integration~ unit tests added.

Fix Application.Exit issues

---

src/System.Drawing.Common/src/System.Drawing.Common.csproj

Helps fix build errors in https://github.com/dotnet/wpf/pull/8635

Avoid System.Private.Windows.Core Package Reference in System.Drawing.Common

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewDesigner.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/NotifyIconDesignerActionList.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TableLayoutPanelDesigner.cs

Stumbled onto this when investigating #10579

Refactoring `DesignerActionMethodItem` usage to use nameof instead of inline string

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListView/ListView.ListViewAccessibleObject.cs

Fix `ListViewAccessibleObject` control type to be dependent on ListView View type

---

.github/fabricbot.json

We want to stop the bot from removing milestones off of closed issues to better track what work has been done in different previews.

Disable Removing Milestones from Closed Issues

---

src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/MessageBoxes.cs

Fixes #10513
- Don't pass owner when `MessageBoxOptions.ServiceNotification | MessageBoxOptions.DefaultDesktopOnly` is specified. 
- Changed help file name as the old one was missing.

Fix `WinformsControlsTest` MessageBox to avoid exception

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/InheritanceUI.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripTemplateNode.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/ScaleHelper.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/GridErrorDialog.cs
src/System.Windows.Forms/src/System/Windows/Forms/Dialogs/ThreadExceptionDialog.cs

Fixes #10512 
-   Adding methods `GetLargeIconResourceAsBitmap `and `GetSmallIconResourceAsBitmap `to ScaleHelper.cs to 100% scaling the icon resource.
-  In the original logic, the resource was scaled once when calling `GetSystemMetrics(SM_CXICON)` (this is not expected), and was scaled again when calling `ScaleToDpi`. The two scalings resulted in abnormal icon display.
- The down arrow icon align with Details in Thread exception dialog can be show normally
- Yes 
- Minimal
In 200% screen:
- Manually
- .net 9.0.0-alpha.1.23623.1

Scale icon to Dpi when initializing icon in ThreadExceptionDialog

---

src/BuildAssist/BuildAssist.msbuildproj

This reduces the amount of noise that appears in the build output window in Visual Studio.

Reduce the build verbosity for AxHosts.csproj

---

pkg/Microsoft.Private.Winforms/sdk/dotnet-windowsdesktop/System.Windows.Forms.FileClassification.props
pkg/Microsoft.Private.Winforms/sdk/dotnet-windowsdesktop/UpdateFileClassification.ps1

This helps with failures in https://github.com/dotnet/windowsdesktop/pull/4063. We want System.Private.Windows.Core to be in the runtime pack of the shared Framework, so this does not need to be omitted from FrameworkListFile

Ignore System.Private.Windows.Core in FileClassification

---

pkg/Microsoft.Private.Winforms/sdk/dotnet-windowsdesktop/System.Windows.Forms.FileClassification.props
pkg/Microsoft.Private.Winforms/sdk/dotnet-windowsdesktop/System.Windows.Forms.IgnoredReferences.props
pkg/Microsoft.Private.Winforms/sdk/dotnet-windowsdesktop/UpdateFileClassification.ps1

Place `IgnoredReferences` tag added in https://github.com/dotnet/winforms/pull/10639 in its own props file for windowsdesktop to consume to avoid tight coupling.
cc: @ericstj

Move IgnoredReferences to Own Props File

---

src/System.Windows.Forms/src/PublicAPI.Shipped.txt
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridView.Methods.cs

- Enable nullability in remaining DataGridView.Methods members.

Enable nullability in remaining DataGridView.Methods members

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGrid.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridTests.cs

Tab removal wasn't matching the tab type so it wouldn't remove tabs.
Fixes #10574

Fix PropertyGrid.RemoveTabType method

---

src/System.Windows.Forms/tests/InteropTests/Directory.Build.targets
src/System.Windows.Forms/tests/InteropTests/System.Windows.Forms.Interop.Tests.csproj

More context in https://github.com/dotnet/arcade/issues/14295
This allows to not exclude the CMake.Sdk targets when the project should be excluded (i.e. in source-build or a VMR vertical build).

Make it possible to not import CMake Sdk when excluding project

---

eng/packageContent.targets
pkg/Microsoft.Private.Winforms/sdk/dotnet-windowsdesktop/System.Windows.Forms.FileClassification.props
pkg/Microsoft.Private.Winforms/sdk/dotnet-windowsdesktop/System.Windows.Forms.IgnoredReferences.props
pkg/Microsoft.Private.Winforms/sdk/dotnet-windowsdesktop/UpdateFileClassification.ps1
src/System.Drawing.Common/src/System.Drawing.Common.csproj
src/System.Private.Windows.Core/src/System.Private.Windows.Core.csproj

As nothing is actually visible in this assembly we were trying to leave it out of the ref package. C# needs the types to be there when it compiles interface casts. This adds the assembly to the ref and excludes looking for IntelliSense files.

Add System.Private.Windows.Core to ref

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListBoxes/ListBox.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListBoxTests.cs

Fixes #4463
- 
-  when `DrawMode` is `DrawMode.Normal `, the ItemHeight can not be set to ListBox. So, ItemHeight should not be serialized.
- 
https://github.com/dotnet/winforms/blob/5234e14330d5379bab230817df65bb4d8c1af28c/src/System.Windows.Forms/src/System/Windows/Forms/DrawMode.cs#L6-L28
https://github.com/dotnet/winforms/blob/5234e14330d5379bab230817df65bb4d8c1af28c/src/System.Windows.Forms/src/System/Windows/Forms/ListBox.cs#L582-L622
The generated code for ListBox1 have extra code: this.listBox1.ItemHeight = 15;
https://github.com/dotnet/winforms/assets/135201996/73544c63-e0cf-4c06-a829-56bfc5d09ebb
- Yes / No
- minimal
- 
- Manually 
-

fix bug The code generated by the ListBox control is not consistent with Framework

---

src/System.Drawing.Common/src/System.Drawing.Common.csproj

Help fix build errors in https://github.com/dotnet/wpf/pull/8694
This is the same error as received in https://github.com/dotnet/wpf/pull/8635. This tag was removed recently, but it actually needs to be present to avoid this error.

Add PrivateAsset tag to System.Drawing.Common

---

src/System.Private.Windows.Core/src/Windows/Win32/System/Com/SafeArrayScope.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/WebBrowser/HtmlDocument.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/HtmlDocumentTests.cs

Fixes https://github.com/dotnet/winforms/issues/10615 , regression from https://github.com/dotnet/winforms/pull/9972
- Avoid throwing on failure in `IHtmlDocument2.Write` as original code did not throw on failure 
- While making changes in the regression PR, I had accidentally commented out some tests covering this scenario 🤦‍♀️ , I re-enabled those tests which covers scenario outlined by issue
- The SafeArray type passed to `IHtmlDocument2.Write` needs to be `VT_VARIANT` so I've added to `SafeArrayScope` to be able to handle this.

Fix SafeArray type in HtmlDocument.Write

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/Labels/LinkLabel.cs

Fixes #10630 , fixes #10555
- Update function `EnsureRun ` to return null when _textRegion is null
- UI can be show normally when scrolling
- Yes 
- Minimal
The content on Window is messed up.
- Manually
- .net 9.0.0-alpha.1.24060.2

Update EnsureRun to return null when _textRegion is null

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/TreeView/TreeNode.TreeNodeAccessibleObject.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/TreeNode.TreeNodeAccessibleObjectTests.cs

Fixes #10591
- 
- Add Level and ExpandCollapsePattern support
- 
- Yes
- minimal 
Narrator:
Inspect:
https://github.com/dotnet/winforms/assets/135201996/f327d45b-56f7-4b6a-90ba-d271d6285244
https://github.com/dotnet/winforms/assets/135201996/8a83f270-d4e5-4c60-8730-2192d953cb78
- 
- manually 
- 
- 9.0.0-alpha.1.24066.33

fix [Accessibility] Narrator cannot announce the leaf node information(level 1) for nodes in TreeView

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewLinkCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewRowHeaderCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListBoxes/ListBox.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/MaskedTextBox.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStrip.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/TreeView/TreeView.cs
src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.cs
src/System.Windows.Forms/src/System/Windows/Forms/Dialogs/ThreadExceptionDialog.cs
src/System.Windows.Forms/src/System/Windows/Forms/Layout/Containers/SplitContainer.cs
src/System.Windows.Forms/src/System/Windows/Forms/MDI/MDIControlStrip.cs
src/System.Windows.Forms/src/System/Windows/Forms/Rendering/ControlPaint.cs

avoid explicit calls to Dispose() in favor of 'using' statement.  this ensures Dispose() is called in the event of an exception and improves code readability.

avoid explicit calls to Dispose() in favor of 'using' statement

---

src/System.Windows.Forms/tests/AxHosts/AxHosts.csproj
src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxSystemMonitorTests.cs

Related #8302 
- Instead of consolidating multiple controls into a single pull request, opted for separate PRs for each control for better organization.
- Followed [Lonitra's instructions](https://github.com/dotnet/winforms/issues/8294#issuecomment-1331026574) on related issue #[8294](https://github.com/dotnet/winforms/issues/8294) by adding Ax control references to both the AxHosts project and the WinForms test project. Additionally, added corresponding tests.
- None
- No
- Minimal
- Unit tests
- 9.0.100-alpha.1.23618.3

Adds tests for AxSystemMonitor

---

src/System.Windows.Forms.Primitives/src/Windows/Win32/Foundation/COLORREF.cs
src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.ImageList.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ImageList/ImageList.cs

The fundamental issue is that we're modifying the `CLR_NONE` constant when passing it to Win32 APIs that accept it.
- Don't pass PInvoke.CLR_NONE through Color.FromArgb, just cast to COLORREF
- Add comments to COLORREF
- Added Inheritdoc for a few methods in PInvoke.ImageList
I've manually verified with the sample from #10680.
Fixes #10680
Fixes #10462

Fix ImageList rendering of transparent images

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/TabControl/TabControl.cs

dispose graphics in TabControl.WmReflectDrawItem()

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/UpDown/UpDownBase.UpDownButtons.UpDownButtonsAccessibleObject.cs

Implementation in the ControlAccessibleObject class - 
https://github.com/dotnet/winforms/blob/d5528f6ce1d65d9f3694d679ee745690cb2e1675/src/System.Windows.Forms/src/System/Windows/Forms/Accessibility/Control.ControlAccessibleObject.cs#L535-L547

removing an override that is identical to the base class implementation

---

.gitignore
Winforms.sln
src/System.Private.Windows.Core/src/Properties/AssemblyInfo.cs
src/System.Windows.Forms.Design/src/Properties/AssemblyInfo.cs
src/System.Windows.Forms.Primitives/src/Properties/AssemblyInfo.cs
src/System.Windows.Forms/src/Properties/AssemblyInfo.cs
src/System.Windows.Forms/tests/IntegrationTests/ScratchProjectWithInternals/Form1.Designer.cs
src/System.Windows.Forms/tests/IntegrationTests/ScratchProjectWithInternals/Form1.cs
src/System.Windows.Forms/tests/IntegrationTests/ScratchProjectWithInternals/Form1.resx
src/System.Windows.Forms/tests/IntegrationTests/ScratchProjectWithInternals/Program.cs
src/System.Windows.Forms/tests/IntegrationTests/ScratchProjectWithInternals/ScratchProjectWithInternals.csproj
src/System.Windows.Forms/tests/IntegrationTests/ScratchProjectWithInternals/readme.txt

Adds another test project similar to `ScratchProject` , which has access to our internals for experimenting.

Add ScratchProject with Access to Internals

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerUtils.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripDesigner.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripItemBehavior.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripItemDataObject.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripMenuItemDesigner.cs

- Replace `ArrayList` usage in `ToolStripItemDataObject` with `List`
- Update relevant call sites to move off `IList` and `ICollection` interfaces

Replace `ArrayList` usage in `ToolStripItemDataObject` with `List`

---

src/System.Private.Windows.Core/src/System/Collections/Generic/CollectionExtensions.cs
src/System.Windows.Forms.Primitives/src/System/Collections/Generic/ListConverter.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/ArrayInfo.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/ArrayRecord.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/ArraySingleObject.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/ArraySinglePrimitive.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/ArraySingleString.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/BinaryArray.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/BinaryFormatWriter.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/BinaryFormattedObjectExtensions.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/IPrimitiveTypeRecord.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/MemberPrimitiveTyped.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/Record.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/Support/ListConverter.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/Support/TypeInfo.cs
src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/BinaryFormat/ArrayTests.cs
src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/BinaryFormat/BinaryFormatWriterTests.cs
src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/BinaryFormat/BinaryFormattedObjectTests.cs
src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/BinaryFormat/ListTests.cs

`ArraySinglePrimitive` was taking `IReadOnlyList<object>` which necessitated boxing all items. This converts `ArrayRecord` to be typed so we can avoid this and adds special optimizations for `byte[]`. This is important for performance of the types we're supporting or intending to support (such as `ImageListStreamer`).
It may be possible to further improve this. If the array data is always aligned in the input then we can just read/write the data directly as byte arrays. `DateTime`, `TimeSpan`, and `decimal` need individually parsed.

Type primitive arrays in BinaryFormattedObject

---

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/BinaryFormatWriter.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/BinaryFormattedObjectExtensions.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/Record.cs
src/System.Windows.Forms/src/System/Resources/ResXDataNode.cs
src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/Control.ActiveXImpl.cs
src/System.Windows.Forms/src/System/Windows/Forms/BinaryFormat/WinFormsBinaryFormatWriter.cs
src/System.Windows.Forms/src/System/Windows/Forms/BinaryFormat/WinFormsBinaryFormattedObjectExtensions.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComDataObjectAdapter.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BinaryFormat/WinFormsBinaryFormattedObjectTests.cs

Adds support for binary formatting ImageListStreamer without the BinaryFormatter.
Add another record writing optimization for ArraySegment<byte>.

Add support for binary formatting ImageListStreamer

---

src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs

Fixes #4555 
**Background:**
WinForms original clipboard behavior is that:
- The original data coming in must implement `System.Runtime.InteropServices.ComTypes.IDataObject` to be taken as is. If it does not, we will wrap the data in a `DataObject`.
- The original data going out must implement `System.Windows.Forms.IDataObject` to be passed out as is. If it does not, we will wrap the data in a `DataObject` before passing it out
Native call to `OleGetClipboard` will always return a proxy that will forward all IDataObject method calls to the real data object, without giving out the real data object. The only time that the proxy ever gives back the real object is when we query for an interface it does not know about. WinForms `DataObject` class also implements `IComCallableWrapper` which is …

Always Wrap Incoming Clipboard Data

---

src/System.Drawing.Common/src/System/Drawing/Bitmap.cs
src/System.Drawing.Common/src/System/Drawing/Drawing2D/GraphicsPath.cs
src/System.Drawing.Common/src/System/Drawing/Graphics.cs
src/System.Drawing.Common/tests/Drawing2D/GraphicsPathTests.cs
src/System.Drawing.Common/tests/GraphicsTests.cs

This adds simple methods for drawing rounded rectangles.
Also changes behavior of LockBits to allow passing in an empty rectangle to mean "the whole bitmap".
I'll move the bitmap validation helper somewhere centralized.

Add RoundedRectangle methods to System.Drawing

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListView/ListView.cs

The state got inverted in https://github.com/dotnet/winforms/commit/7e0115d442c26dfce4ad49231e446b8bdd172cab. I don't think there is a good way to get an automated test for this, but I'll look into it.
We need to get this serviced as it always flips what you try to do.
Fixes #10746

Fix ListView CancelEdit

---

src/System.Drawing.Common/src/System/Drawing/Bitmap.cs
src/System.Drawing.Common/src/System/Drawing/Graphics.cs
src/System.Drawing.Common/src/System/Drawing/Image.cs
src/System.Drawing.Common/src/System/Drawing/ImageConverter.cs
src/System.Drawing.Common/src/System/Drawing/Imaging/ImageFormat.cs
src/System.Drawing.Common/src/System/Drawing/Imaging/Metafile.cs
src/System.Drawing.Common/src/System/Drawing/PointerExtensions.cs
src/System.Drawing.Common/src/System/Drawing/TextureBrush.cs
src/System.Private.Windows.Core/src/NativeMethods.txt
src/System.Private.Windows.Core/src/System/Drawing/IImage.cs
src/System.Private.Windows.Core/src/System/IO/IRawData.cs

Do a little cleanup on Image.Save.
- Improve terminology
- Factor code to allow moving some logic to Core

Clean up Image.Save

---

src/System.Drawing.Common/src/System/Drawing/Image.cs
src/System.Drawing.Common/src/System/Drawing/ImageConverter.cs
src/System.Drawing.Common/src/System/Drawing/Imaging/ImageCodecInfo.cs
src/System.Drawing.Common/src/System/Drawing/Imaging/ImageFormat.cs
src/System.Private.Windows.Core/src/NativeMethods.txt
src/System.Windows.Forms/tests/IntegrationTests/ScratchProject/Program.cs

Getting the array of encoder ImageCodeInfo is expensive and unnecessary to do repeatedly. Cache the guids for internal use without converting to managed classes and jagged arrays.

Improve Image save performance

---

eng/Version.Details.xml
eng/Versions.props
src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ControlTestBase.cs
src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ScreenRecordService.cs
src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ScreenshotService.cs
src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/System.Windows.Forms.UI.IntegrationTests.csproj

Record the screen during integration tests, and save an animated PNG (*.apng) if the test fails. Derived from a similar implementation in dotnet/roslyn.
Integration tests will be re-enabled for CI as a follow-up to this.
The APNG code is derived from code originally written for Roslyn in #70983, with significant modifications to make it operate on WinForms types instead of WPF types.

Implement screen recording for integration tests

---

src/Common/tests/TestUtilities/FileCleanupTestBase.cs
src/System.Drawing.Common/tests/Helpers.cs
src/System.Drawing.Common/tests/System/Drawing/GdiPlusHandlesTests.cs
src/System.Drawing.Common/tests/System/Drawing/GraphicsTests.cs
src/System.Drawing.Common/tests/System/Drawing/Printing/PageSettingsTests.cs
src/System.Drawing.Common/tests/System/Drawing/Printing/PrintDocumentTests.cs
src/System.Drawing.Common/tests/System/Drawing/Printing/PrinterSettingsTests.cs
src/System.Private.Windows.Core/src/NativeMethods.txt
src/System.Private.Windows.Core/src/Properties/AssemblyInfo.cs
src/System.Private.Windows.Core/src/Windows/Win32/PInvoke.GetClientRect.cs
src/System.Windows.Forms.Primitives/src/NativeMethods.txt
src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/GroupBox/GroupBox.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListBoxes/ListBox.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListView/ListView.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyGridView.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/StatusStrip.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripDropDown.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripManager.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripTextBox.ToolStripTextBoxControl.cs
src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
src/System.Windows.Forms/src/System/Windows/Forms/Layout/Containers/ContainerControl.cs
src/System.Windows.Forms/src/System/Windows/Forms/Screen.cs
src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/TestHelpers.cs
src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ImageListTests.cs

Remove some hand spun interop from System.Drawing tests.  Also:
- Unskip RS4 related issue tests (seem to all work fine now)
- Only create the directory for FileCleanupTestBase on demand
- Cache the installed printer names for tests

Remove test interop from System.Drawing

---

src/System.Windows.Forms.Primitives/src/Windows/Win32/UI/Controls/ToolInfoWrapper.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolTipTests.cs

Fixes #10614 
Cswin32 definition of `TTTOOLINFOW` has a different struct size than what we were using originally. Cswin32 has the additional member `lpReserved` while we did not in our old definition, which breaks compatibility.
https://learn.microsoft.com/en-us/windows/win32/controls/common-control-versions#structure-sizes-for-different-common-control-versions outlines some structs that have different sizes between versions, including `TTTOOLINFOW`. We had been previously using `TTTOOLINFO_V2_SIZE`. In order to maintain compatibility, we need to continue to use the struct size we had been using before, so explicitly set the `cbSize` to the "old" size when creating `TTTOOLINFOW`. This is unfortunately not exposed via Cswin32.

Fix TTTOOLINFOW Struct Size

---

src/System.Drawing.Common/src/System/Drawing/Bitmap.cs
src/System.Drawing.Common/tests/System/Drawing/BitmapTests.cs

Add a simple overload for ConvertFormat that picks (hopefully) reasonable defaults.
Add some tests for Convert and expand docs a bit.
Default 1 and 4 bpp indexed results:

Add simple overload for ConvertFormat

---

src/System.Windows.Forms/tests/UnitTests/WebBrowserBaseTests.cs

Related #10453
- Add Unit test for WebBrowserBase
- No
- Minimal

Add test case for WebBrowserBase

---

src/System.Windows.Forms/src/System/Windows/Forms/Input/CursorConverter.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CursorConverterTests.cs

Fixes https://github.com/dotnet/winforms/issues/10185
We had previously removed this code in https://github.com/dotnet/winforms/pull/10005 in an attempt to avoid using reflection when converting Cursor->string. We had tried to avoid reflection by adding property `CursorsProperty` to `Cursor` to track the "string version" of the Cursor. This will work as expected when we are setting the cursor, however there are times when other processes set the cursor, in which we only have the handle available to us i.e. we cannot utilize `CursorsProperty` to properly convert Cursor->string since we will not have that information. To handle this case, we should fall back to our old code to convert the cursor properly.
Manually testing results:

Add Fallback to CursorConverter.ConvertTo

---

Directory.Build.targets
eng/CodeCoverage.proj
eng/pipelines/build.yml
src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/TabControlTests.cs

Prior testing indicated that the inclusion of a screen capture in the render loop (part of #10552) was sufficient to stabilize the mouse interactions for integration tests. Even with the retry mechanism disabled I have not been able to reproduce a failure.
Merge commit recommended for clarity of the individual changes (note that CI was passed for each commit individually).
Closes #6654
Closes #9318

Enable UI tests

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/LabelTests.cs

Add unit tests for Label to test its BorderStyle, FlatStyle and TextAlign
- None
- No
- Minimal
- Unit tests

Add unit tests for Label

---

src/System.Windows.Forms/src/System/Windows/Forms/Input/KeysConverter.cs

Related #10732
- Change return type of the GetDisplayOrder method from IList<> to List<>, the return type in GetKeyNames from IDictionary<> to Dictionary<>
- Minimal
- Manually
- .net 9.0.0-preview.2.24102.8

Update the return Type of the function GetDisplayOrder and GetKeyNames

---

eng/CodeCoverage.proj
eng/pipelines/build.yml

Also enable integration tests for main branch builds so reference code coverage data is available.

Support partial code coverage when integration tests are not running

---

src/System.Windows.Forms.Design/src/System/Drawing/Design/IconEditor.cs

Fixes #10830 
- Remove offset calculation from method "PaintValue" of IconEditor
- When using "Choose Icon... " command line to add an icon, the icon can be displayed in correct position
- Yes  
- Minimal
The icon is displayed in the upper left corner of the properties window
The icon display in correct position
- Manual
- .net 9.0.0-preview.2.24105.1

Remove offset calculation from method "PaintValue" of IconEditor

---

src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/WinformsControlsTest.csproj

Added properties hidden in the application bootstrap explicitly to the project file for easy testing. I'm setting them to the default values.

Update WinformsControlsTest.csproj for easy testing with no VisualStyles

---

src/System.Windows.Forms.Primitives/src/Windows/Win32/Foundation/COLORREF.cs
src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.ImageList.cs
src/System.Windows.Forms/src/System/Windows/Forms/ImageList.cs

backport of https://github.com/dotnet/winforms/pull/10696
We were modifying the CLR_NONE constant when passing it to Win32 APIs that accept it.
- Don't pass PInvoke.CLR_NONE through Color.FromArgb, just cast to COLORREF
- Add comments to COLORREF
- Added Inheritdoc for a few methods in PInvoke.ImageList

[release/8.0] Fix ImageList rendering of transparent images

---

src/System.Windows.Forms/src/System/Windows/Forms/KeysConverter.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/KeysConverterTests.cs

Backport of https://github.com/dotnet/winforms/pull/10647 to release/8.0
- Update GetStandardValues to get the standard values by CultureInfo.InvariantCulture
- The KeysConverter.GetStandardValues() can be used normally
- Yes 
- Minimal
Simply calling
`var test = new KeysConverter().GetStandardValues();`
throws the exception:
`System.Collections.Generic.KeyNotFoundException: 'The given key 'en-US' was not present in the dictionary.'`
Call `var test = new KeysConverter().GetStandardValues();` to return standard key values
- Manually
- .net 9.0.0-alpha.1.24058.11

[release/8.0] Fix regression in KeysConverter.GetStandardValues 

---

src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ErrorProviderTest.Designer.cs
src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ErrorProviderTest.cs

Related #10735
- Adds new control to the ErrorProvider form on the WinformsControlTests project;
- Aims to test with scaling of multi-resolution icons on the ErrorProvider control.
- None
- No
- Minimal
- Interactive test
- 9.0.100-alpha.1.23618.3

Adds control for ErrorProvider on WinformsControlTest

---

src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider/ErrorProvider.IconRegion.cs
src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ErrorProviderTest.Designer.cs
src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ErrorProviderTest.cs

Fixes #10735
- Apply @elachlan 's [suggestion][elachlan-suggestion] on sizing the icon using `ScaleHelper.LogicalSmallSystemIconSize`.
- Multi-resolution icons should now display on correct size on the ErrorProvider component.
- Yes
- Minimal
- Interaction test on WinformsControlsTest, ErrorProvider component test.
- 9.0.100-alpha.1.23618.3
[elachlan-suggestion]: https://github.com/dotnet/winforms/issues/10735#issuecomment-1917911767

Issue 10735 error provider wrong icon multiple resolution

---

eng/SourceBuild.props

Don't error out on MSB3026 in the VMR build.

[VMR] Don't error out on non-fatal file locking warnings

---

src/System.Windows.Forms/src/System/Windows/Forms/Dialogs/CommonDialogs/FileDialog.cs
src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Dialogs.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FileDialogTests.cs

Fix empty `OpenFileDialog.FileNames` when `AutoUpgradeEnabled=false` and `Multiselect = true`

---

src/System.Windows.Forms/tests/IntegrationTests/ScratchProject/ScratchProject.csproj

To convert scratch project to a single file, change appropriate property values to true and run `dotnet publish` or build in VisualStudio

make it easier to experiment with single file deployments

---

src/Common/tests/TestUtilities/TestAccessor.cs
src/Common/tests/TestUtilities/TestAccessors.cs
src/System.Drawing.Common/src/System/Drawing/Imaging/ImageAttributes.cs
src/System.Drawing.Common/src/System/Drawing/Imaging/ValueColorMap.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionPanel.EditorPropertyLine.EditorButton.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewRowHeaderCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/PictureBox/PictureBox.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripHighContrastRenderer.cs
src/System.Windows.Forms/src/System/Windows/Forms/Layout/ImageLayout.cs
src/System.Windows.Forms/src/System/Windows/Forms/Rendering/ControlPaint.cs

Add span overloads to ImageLayout and a new struct ValueColorMap to avoid allocating a class for every map value.
- Remove all ColorMap usages
- Change ControlPaint.CalculateBackgroundImageRectangle to take the image size rather than the image
- Use ARGB span to access the bitmap scan in ControlPaint.CreateHBitmapTransparencyMask
- Use BufferScope in ControlPaint.DrawBorder
- Stack alloc the matrix array in DrawImageDisabled
Also add clarifying comments in TestAccessor and a few other random clean ups.

Add span overloads to ImageLayout

---

src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/RichTextBox/RichTextBox.OleCallback.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs

This PR fixes some issues found when running our test suite with `BuiltInComSupport = false` (mimic trimming).
When there is data on the clipboard that is from another process or when the clipboard has been flushed ([OleFlushClipboard](https://learn.microsoft.com/en-us/windows/win32/api/ole2/nf-ole2-oleflushclipboard) was called), we are no longer able to retrieve the real `IDataObject` pointer from the proxy that is returned by `OleGetClipboard` if we had placed something on the clipboard. In this case, when built in COM is turned on, marshal will simply return the proxy in a wrapper that implements `System.Runtime.InteropServices.ComTypes.IDataObject` via `Marshal.GetObjectForIUnknown`. When built in COM is turned off, we need to mimic this behavior ourselves.
Also added …

Mimic Marshal Behavior on Clipboard when Built-in Com is Off

---

src/System.Private.Windows.Core/src/Windows/Win32/System/Com/AgileComPointer.cs
src/System.Private.Windows.Core/src/Windows/Win32/System/Com/ComHelpers.cs
src/System.Private.Windows.Core/src/Windows/Win32/System/Com/WinFormsComWrappers.cs
src/System.Windows.Forms.Primitives/src/Microsoft/Office/IMsoComponent.cs
src/System.Windows.Forms.Primitives/src/Microsoft/Office/IMsoComponentManager.NativeAdapter.cs
src/System.Windows.Forms.Primitives/src/Microsoft/Office/IMsoComponentManager.cs
src/System.Windows.Forms.Primitives/src/Microsoft/Office/msocstate.cs
src/System.Windows.Forms.Primitives/src/Microsoft/Office/msoloop.cs
src/System.Windows.Forms.Primitives/src/System/ComponentModel/CompModSwitches.cs
src/System.Windows.Forms/src/System/Windows/Forms/Application.ComponentManager.cs
src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs
src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadWindows.cs
src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Properties/launchSettings.json
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Application.ComponentManagerTests.cs

This change converts the interfaces to match the same patterns we're using with other Com interfaces. Also yanks the trace statements for these.
I'm probably going to try and factor this stuff out into an opt-in feature.

Make MsoComponent code trim friendly

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/TreeView/TreeNode.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/TreeView/TreeView.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/TreeView/TreeViewLabelEditAccessibleObject.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs

Fixes #10876
TreeNodeAccessibleObject can't be created when the parent TreeView is not found. This could happen when a node is being added or deleted from the Nodes collection. If AccessibleObject is not created on this attempt, it will be created on the next access. If TreeView is not available, we skip object creation.
- Yes  from NET7
Low - adding a null-check
Fix is based on the exception callstack, I couldn't reproduce this crash

replace a null-forgiving operator with a null-check in TreeNodeAccessibleObject 

---

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.CollectionEditorCollectionForm.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.cs
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.Designer.cs
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.cs
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DesignSurfaceExt/PropertyGridExt.cs

Fixes #10545
- 
-  `PropertyGrid` requires `DesignerHost` to perform some functions . in our case it is to CreateNewObject
- 
https://github.com/dotnet/winforms/blob/a05dd925fe03e64ee026ad2fda65638b75d08998/src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.cs#L91-L114
please see line 95. if the `host` here is not null, then our existing code can create target object **and set `Text` property(line 102)**
if the `host` is null, some properties would not be initialized inclining `Text`, which is the cause of this issue.
- low
https://github.com/dotnet/winforms/assets/135201996/c6e1f5bf-d614-41e2-ba07-ca82902a53e1
- 
- manual
- 
9.0.0-alpha.1.24066.33

fix bug: No text for new tabpage item that added by TabPages property in the properties window in the DemoConsole application

---

src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/DataStreamFromComStream.cs

- Add optimised overloads to methods `DataStreamFromComStream.ReadByte` and `WriteByte`
- remove some small arrays allocations
- low
- CI

Add missing Stream overloads in DataStreamFromComStream

---

src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.PrintDlg.cs
src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintDialog.cs
src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/PrintDialogTests.cs

Fix `PrintDialog` to return `DialogResult.Cancel` when cancelled or closed

---

src/System.Design/src/System.Design.Forwards.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewColumnCollectionDialog.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewColumnTypeEditor.Picker.ListBoxItem.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewColumnTypeEditor.Picker.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewColumnTypeEditor.cs

Fixes #10364 
- 
- Add DataGridViewColumnTypeEditor
- 
- low
- 
- manually
- 
9.0.0-preview.2.24116.2

fix Issue "ColumnType is disabled for Columns in EditColumns dialog"

---

src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolStripTests.Designer.cs

Related #10834 
- Add ToolStripMenuItem test in WinformsControlTests
- ToolStripMenuItem can be tested in project WinformsControlTests
- No
- Minimal
- Manually
- .net 9.0.0-preview.2.24116.2

Add ToolStripMenuItem test UI in WinformsControlTests

---

src/System.Drawing.Common/tests/mono/System.Drawing/BitmapTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageListTests.cs

Related #10871
Suppress codeQL warnings in BitmapTests and ImageListTests 
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1666874/?view=edit
https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1775936/?view=edit

Suppress codeQL warnings in tests "BitmapTests" and "ImageListTests"

---

src/System.Windows.Forms/src/System/Windows/Forms/AutoCompleteStringCollection.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBox.cs
src/System.Windows.Forms/src/System/Windows/Forms/StringSource.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AutoCompleteStringCollectionTests.cs
src/System.Windows.Forms/tests/UnitTests/TextBoxTests.cs

- Refactoring to add `ArgumentNullException`/`InvalidOperationException` to `AutoCompleteCustomSource`
- add tests to verify
- Cleanup/Refactor of `StringSource`
I think this is an API change, so it might need to be documented. Since the APIs now throw exceptions.
#Fixes #10904

Fix `null` values in `AutoCompleteCustomSource` 

---

eng/Versions.props

False is already the default and winforms probably doesn't need to use a newer compiler than what's available in the SDK anytime soon. That was different in the past when the SDK wasn't updated every month.

Delete UsingToolMicrosoftNetCompilers property

---

docs/developer-guide.md

`Windows Media Player` and `Media Features` are required for building the full repo.
Without those Windows Features, the build fails with the following error:
`
C:\git\winforms\src\System.Windows.Forms\tests\AxHosts\AxHosts.Designer.cs(64,13): error CS0246: The type or namespace name 'AxWMPLib' could not be found (are you missing a using directive or an assembly reference?) [C:\git\winforms\src\System.Windows.Forms\tests\AxHosts\AxHosts.csproj] [C:\git\winforms\src\BuildAssist\BuildAssist.msbuildproj]
`
- Update machine setup requirements with the list of Windows Features that are required for successful build.

Update machine requirements

---

src/System.Windows.Forms/src/System/Windows/Forms/FileDialog.cs
src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Dialogs.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FileDialogTests.cs

Backport of https://github.com/dotnet/winforms/pull/10849
Fix the parsing logic for `GetMultiselectFiles`. When using `OpenFileDialog`​ that has properties `AutoUpgradeEnabled = false`​  and  `Multiselect = true​` , selecting a single file or mutiple files will result in no file names being returned, causing this to be unusable.​ The logic has been updated to include the null delimiter from the directory path when selecting multiple files and to check if we have single file case before proceeding with rest of parse.

[release/8.0] Fix empty `OpenFileDialog.FileNames` when `AutoUpgradeEnabled=false` and `Multiselect = true`

---

src/System.Windows.Forms/src/System/Windows/Forms/TreeNode.cs
src/System.Windows.Forms/src/System/Windows/Forms/TreeView.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs

Fixes #10876
Port of https://github.com/dotnet/winforms/pull/10880
(PR was created by cherry-picking commits one-by-one)
TreeNodeAccessibleObject can't be created when the parent TreeView is not found. This could happen when a node is being added or deleted from the Nodes collection. If AccessibleObject is not created on this attempt, it will be created on the next access. If TreeView is not available, we skip object creation. This fix was implemented based on the exception call stack from the customer.
Customer observes random crashes in their application when dragging TreeView items and clicking on TreeView subtrees with the mouse.
No workaround is available, 
- Yes from NET7, introduced while enabling accessibility events to TreeNode operations.
- Low, we are exiting if accessible …

[release/8.0] WinForms TreeView null reference exception 'owningTreeView'

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/LabelTests.cs

- Add unit tests for Label to test its properties: AutoEllipsis, BackgroundImage, BackgroundImageLayout, ImageIndex, ImageKey, ImageList, LiveSetting, UseCompatibleTextRendering
- Add unit tests for Label to test its events: AutoSizeChanged, BackgroundImageChanged, BackgroundImageLayoutChanged, KeyUp, KeyDown, KeyPress, TabStopChanged, TextAlignChanged
- None
- No
- Minimal
- Unit tests

Add test coverage for Label 

---

azure-pipelines-PR.yml
eng/pipelines/build-PR.yml
eng/pipelines/post-build-PR.yml

Follow up to https://github.com/dotnet/winforms/pull/11007. We need to duplicate our other build yamls that'll be affected by the pipeline migration so our PR validation continues to use original definition.

Duplicate All Build YAML Files

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripDesigner.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripMenuItemDesigner.cs
src/System.Windows.Forms.Design/tests/UnitTests/ToolStripDesignerTests.cs

Fixes #9413 
The error is thrown in line 1585. MenuItem.Owner is null here.
https://github.com/dotnet/winforms/blob/bd97476fa596ac2063153181daa6a46251dc755d/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripMenuItemDesigner.cs#L1579-L1586
Actually , MenuItem.Owner is set in the method.
https://github.com/dotnet/winforms/blob/bd97476fa596ac2063153181daa6a46251dc755d/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripMenuItemDesigner.cs#L1640
We didn't bind this method to `ComponentChangeService`. It looks like a careless omission.
- 
- bind methods to `ComponentChangeService`
- 
https://github.com/dotnet/winforms/assets/94418985/4ae6cb77-9592-41ae-96df-65fe24d9241b
https://github.com/dotnet/winforms/assets/135201996/eb8502a2-5bc0-4526-833c-ff8b2e …

fix An exception popped up when click "Type Here" on ContextMenuStrip control in DemoConsole application

---

azure-pipelines-PR.yml
azure-pipelines.yml
eng/pipelines/build-PR.yml
eng/pipelines/build.yml
eng/pipelines/post-build-PR.yml
eng/pipelines/post-build.yml

Best to review without whitespace since the conversion tool removed any unnecessary indents
test run: https://dev.azure.com/dnceng/internal/_build/results?buildId=2400049&view=results
The error in the test run is being tracked by https://github.com/dotnet/arcade/issues/14560 but it does not block successful build
note- the PR validation does not use this new yml file, it uses `azure-pipelines-pr.yml` which is a dupe of the original azure-pipelines.yml definition

Convert to 1ES Pipeline Template

---

src/System.Windows.Forms/tests/UnitTests/MaskedTextBoxTests.cs

- Add unit tests for MaskedTextBox to test its properties: BeepOnError, AsciiOnly and Culture
- None
- No
- Minimal
- Unit tests

Add test coverage for MaskedTextBox

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RichTextBoxTests.cs

- Add unit tests for RichTextBox to test its DrawToBitmap()/LoadFile()/SaveFile()/Paste() methods
- None
- No
- Minimal
- Unit tests

Add code coverage for RichTextBox

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ParentControlDesigner.cs
src/System.Windows.Forms.Primitives/src/System/ComponentModel/CompModSwitches.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Message.cs
src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/Buttons/RadioButton.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridView.Methods.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/TabControl/TabControl.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/TabControl/TabPage.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxBase.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStrip.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripDropDown.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripDropTargetManager.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripManager.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripPanelCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripPanelRow.HorizontalRowManager.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripPanelRow.VerticalRowManager.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripPanelRow.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/WebBrowser/WebBrowserBase.cs
src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
src/System.Windows.Forms/src/System/Windows/Forms/Layout/Containers/ContainerControl.cs
src/System.Windows.Forms/src/System/Windows/Forms/Layout/Containers/SplitContainer.cs
src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DropTarget.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Internals.cs

Removes another set of trace statements.
Reduce nesting on a few impacted methods.
Make OnEnter/Leave protected internal to avoid a separate method just to make internal access possible.

Remove another batch of tracing

---

src/System.Windows.Forms/tests/UnitTests/ProgressBarRendererTest.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ProgressBarRendererTest.cs

- Add unit tests for ProgressBarRenderer to test its properties: IsSupported， ChunkThickness， ChunkSpaceThickness
- Add unit tests for ProgressBarRenderer to test its methods: DrawHorizontalBar，DrawVerticalBar，DrawHorizontalChunks， DrawVerticalChunks
- None
- No
- Minimal
- Unit tests

Add code coverage for ProgressBarRenderer

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePickerTests.cs

Add unit tests for DateTimePicker's property and event
- Properties:
1. > CalendarTitleBackColor
2. > CalendarForeColor
3. > CalendarTitleForeColor
4. > CalendarTrailingForeColor
5. > CalendarMonthBackground
- Events:
1. > BackColorChanged
2. > BackgroundImageChanged
- None
- No
- Minimal
- Unit tests

Add test coverage for DateTimePicker

---

src/System.Drawing.Common/src/System/Drawing/Bitmap.cs
src/System.Drawing.Common/src/System/Drawing/Imaging/ColorPalette.cs
src/System.Drawing.Common/src/System/Drawing/Imaging/PaletteType.cs
src/System.Drawing.Common/tests/System/Drawing/BitmapTests.cs

This updates bitmap conversion and fixed color palette creation to match the final API approval and removes the preview flags.
Fixes #8827

Update bitmap conversion for API review

---

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.CollectionEditorCollectionForm.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/EventBindingService.EventPropertyDescriptor.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourceCodeDomSerializer.SerializationResourceManager.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewColumnCollectionDialog.cs
src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/ComNativeDescriptor.cs

Reducing [TrimTest](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/tests/IntegrationTests/TrimTest/TrimTest.csproj) project warnings by mostly addressing [IL2046](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-warnings/il2046) warnings that the test project encounters (should be reduced by 12 warnings to 72 now, with some fixes coming from other repos)

Match annotations for interface and overridden methods to reduce TrimTest warnings

---

azure-pipelines-PR.yml

Re-adds another variable that was dependent on public vs internal that was removed in https://github.com/dotnet/winforms/pull/11025 since this YAML file could be run in either public or internal

Re-add Internal vs Public Variable in YAML

---

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/MultilineStringEditor.OleCallback.cs

Fixes https://github.com/dotnet/winforms/issues/11084
When calling `QueryGetData` on the `IDataObject` given to us in `MultilineStringEditor.OleCallback.QueryAcceptData`, we were getting a failure due to invalid `FORMATETC` we were creating. Fixed to fill out `FORMATETC` completely using the same values we typically use when doing this same `QueryGetData` call in `DataObject` e.g. https://github.com/dotnet/winforms/blob/0e896ceec52ab5afea2731766bda744310df7995/src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs#L472-L478
Since `MultilineStringEditor.OleCallback` is private and `MultilineStringEditor` is sealed, there doesn't seem to be a good way to add regression test so opted to do a debug assert to catch future …

Fill out FORMATETC on MultilineStringEditor Paste

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStrip.cs

Fixes #10970
- Stops updating the current Tooltip item while refreshing on the Toolstrip.
- Tabbing through the controls in the PrintPreviewDialog ToolStripButton's will show proper tooltip even after zoom is altered in the dropdown.
- Yes
- Minimal
- Manual
- 9.0.100-preview.1.24101.2

Fixes wrong tooltip when tabbing through PrintPreviewDialog's ToolStripButtons

---

.github/policies/resourceManagement.yml

Likely `isPullRequest` and `isIssue` is causing this action to always fail since both cannot be true. `isOpen = true` when item is an issues **or** PR

Fix Close Stale Issue/PR Action

---

src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionUIService.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerActionUIStateChangeEventArgs.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DesignerActionKeyboardBehavior.cs

- Enable nullability in DesignerActionUIService and DesignerActionUIStateChangeEventArgs.

Enable nullability in DesignerActionUIService and DesignerActionUIStateChangeEventArgs

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/ToolTip/ToolTip.cs

Fixes https://github.com/dotnet/winforms/issues/11083
Fixes https://github.com/dotnet/winforms/issues/7262
•	Added null-checks when accessing the owner DataGridView property from the DataGridView cell because this is a public property and could be set to null either by user code of when the owner control is re-created. Use default values when the owner DGV control is null.
•	Do not show the ToolTip when the owner window is null. This could happen when owner is available at the moment when the tool tip timer is started, but is destroyed by the end of the timer interval when the tooltip is ready to be shown. 
Fixes a rare application crash.
•	Probably not a regression, the same code is present in the .NET Framework, where the keyboard tooltips were originally introduced. However, we don’t …

Fix NPE Error

---

src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/DemoConsole.csproj
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DesignSurfaceExt/DesignSurfaceExt.csproj

Related to https://github.com/dotnet/winforms/issues/10779
Related to https://github.com/dotnet/dotnet/pull/86
Related to https://github.com/dotnet/installer/pull/19218
All files in `src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/**`, except for the project files, are under a non-OSS license and [cannot be in the dotnet product](https://github.com/dotnet/arcade/blob/main/Documentation/UnifiedBuild/VMR-Permissible-Sources.md#policy-1). This means that the files must be removed from the .NET product via cloaking (originally completed in https://github.com/dotnet/installer/pull/19218).
Since these tests will not be buildable in the .NET product due to the cloaking, we must add `<ExcludeFromDotNetBuild>true</ExcludeFromDotNetBuild>` to the project files.

Don't build DesignSurface tests in .NET product build

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePickerTests.cs

- Updated the BackColorChanged and BackgroundImageChanged event test cases in DateTimePickerTest.cs
> 1 DateTimePicker_BackColorChangedEvent_Raised_Success()
> 2 DateTimePicker_BackgroundImageChangedEvent_Raised_Success()
- None
- No
- Minimal
- Unit tests

Updated the BackColorChanged and BackgroundImageChanged event test cases in DateTimePickerTest.cs

---

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerHost.cs
src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignerHostTests.cs

Fixes #11095
- Add `string.Empty` judgement in function `CreateSite `of the file `DesignerHost`
- The DemoConsole app can be run normally
- Yes 
- Minimal
- Run DemoConsole App
- .net 9.0.0-preview.4.24169.16

Restore handling of a null name in CreateComponent and CreateSite

---

src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/ToolTip.cs

Fixes https://github.com/dotnet/winforms/issues/11083
Fixes https://github.com/dotnet/winforms/issues/7262
•	Added null-checks when accessing the owner DataGridView property from the DataGridView cell because this is a public property and could be set to null either by user code of when the owner control is re-created. Use default values when the owner DGV control is null.
•	Do not show the ToolTip when the owner window is null. This could happen when owner is available at the moment when the tool tip timer is started, but is destroyed by the end of the timer interval when the tooltip is ready to be shown. 
Fixes a rare application crash.
•	Probably not a regression, the same code is present in the .NET Framework, where the keyboard tooltips were originally introduced. However, we don’t …

[release/8.0] Fix NRE in the keyboard-driven ToolTips when DataGridView control is re-created.

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ListControlStringCollectionEditor.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/StringArrayEditor.cs

- Enable nullability in ListControlStringCollectionEditor and StringArrayEditor.

Enable nullability in ListControlStringCollectionEditor and StringArrayEditor

---

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerHost.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxAutoCompleteSourceConverter.cs
src/System.Windows.Forms/src/System/Windows/Forms/Layout/Containers/ContainerControl.cs

Addresses the following warnings
- [ContainerControl.BindingContext](https://github.com/dotnet/winforms/blob/0e3964e75d345cdb4d849e676d97042cf3e5f723/src/System.Windows.Forms/src/System/Windows/Forms/Layout/Containers/ContainerControl.cs#L254): Adds a feature switch to indicate that binding is not supported in default trimming
- Missed earlier annotation in [IReflect.InvokeMember](https://github.com/dotnet/winforms/blob/0e3964e75d345cdb4d849e676d97042cf3e5f723/src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerHost.cs#L1245)
- `EnumConverter` no longer require a DAM annotation due to https://github.com/dotnet/runtime/pull/100347

Miscellaneous trim fixes

---

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/ArrayRecord.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/BinaryArray.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/ClassRecord.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/ClassWithMembers.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/ClassWithMembersAndTypes.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/ObjectRecord.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/BinaryFormat/Record.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Id.cs
src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/IdTests.cs

- BinaryArray was not putting itself in the record map
- Id negative and positive values are not equivalent
- Add "null" Id
- Add base ObjectRecord to surface ObjectId
- Handle BinaryLibrary records occuring before other record data
- Raise LibraryId to ClassRecord

Fix some record issues

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs

Fixes #10307
When drag begins, this is the call stack of InProc designer
here `ControlDesigner.CanBeAssociatedWith` is an override method.
**But in this case (DemoConsole), there is no override method, so it comes to base method.** which always return true.
https://github.com/dotnet/winforms/blob/3bf6970715b552384bfb28a2752c385ad8353a27/src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.cs#L53
So the following logic will not be executed.
I guess this might be a careless omission.
- 
- Add override method `CanBeAssociatedWith`
- 
- low
https://github.com/dotnet/winforms/assets/104609169/61c945b7-b584-478b-a981-7638e738db0e
- 
- manually 
- 
-

fix issue 10307: TabPage should not be moved in the DemoConsole application

---

src/System.Drawing.Common/src/System/Drawing/Font.cs
src/System.Drawing.Common/src/System/Drawing/Icon.cs
src/System.Drawing.Common/src/System/Drawing/Image.cs
src/System.Windows.Forms/src/System/Resources/ResXSerializationBinder.cs
src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/AxHost.State.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.BitmapBinder.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataObject_BitmapBinderTests.cs

This PR fixes a few CodeQL warnings
- Add `NonSerializedAttribute` to explicitly indicate that pointers/handles are not being serialized ([ex](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1943327/?view=edit))
- Suppress [warning](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1845222/?view=edit) in `ResXSerializationBinder` as this is meant to redirect to .NET Framework type names, if we cannot do so we want to fall back to default binder
- Add more logic in BitmapBinderTest testing `BindToType` to ensure deserialized bitmap is equivalent to original
- Update `BitmapBinder` to avoid return null ([ex](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/1931519/?view=edit))
- Change to use fluent assertions for `BitmapBinderTests`

Fix Few CodeQL Warnings

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ImageList.ImageCollectionTests.cs

Related #11226
- Comment out some theory data of the test `ImageCollection_VisualStyles_on_Item_Get32bppColorDepth_TestData` that cause flaky failure
- Low

Comment out some theory data of the test "ImageCollection_VisualStyles_on_Item_Get32bppColorDepth_TestData" that cause flaky failure

---

src/System.Windows.Forms/src/Resources/SR.resx
src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.WinFormsDataObjectToNativeAdapter.cs
src/System.Windows.Forms/tests/ComDisabledTests/ClipboardComTests.cs
src/System.Windows.Forms/tests/ComDisabledTests/ComDisabled.Tests.csproj
src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs

Added a feature switch check with the default set to true (enable using `BinaryFormatter` for compatibility). The feature switch flag is used so as to not generate a trim warning when the flag is false, which is the expectation in trimming. The trimmer will generate a warning if the feature is enabled to use the `BinaryFormatter`.

Disable binary formatter for trimming

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendar.HitTestInfoTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MonthCalendarTests.cs

- Add unit tests for MonthCalendar to test its properties: HitTestInfo, HitArea, Help, Name, Bounds, Description, Role , State
- Add unit tests for MonthCalendar to test its methods: GetFocused(), Select(). 
-  None
-  No
- Minimal
- Unit tests

Add code coverage for MonthCalendar

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs

Related #10453 
- Add unit tests for ListView to test its RightToLeftLayoutChanged event
- None
- No
- Minimal
- Unit tests

Add code coverage for ListView

---

src/System.Windows.Forms/tests/UnitTests/CheckedListBoxTests.cs

- Add unit tests for CheckedListBox to test its properties: DataSource, DrawMode, ItemHeight, ThreeDCheckBoxes, UseCompatibleTextRendering
- Add unit tests for CheckedListBox to test its events: DataSourceChanged, DisplayMemberChanged, ItemCheck, Click, MouseClick,  MeasureItem, ValueMemberChanged
- None
- No
- Minimal
- Unit tests

Add unit test for checkedListBox

---

src/System.Windows.Forms/src/System/Resources/ResXSerializationBinder.cs
src/System.Windows.Forms/tests/UnitTests/System/Resources/ResXSerializationBinderTests.cs

- Utilize new [TypeName parser API](https://github.com/dotnet/runtime/pull/100094) in `ResXSerializationBinder` where we had been manually picking apart the type name to redirect to/from .NET Framework type names
- Add tests for ResXSerializationBinder to ensure behavior before/after is the same

Utilize TypeName Parser API in ResXSerializationBinder

---

src/Common/tests/TestUtilities/XUnit/EnumerableTupleTheoryData.cs
src/System.Private.Windows.Core/src/System/Windows/Forms/BinaryFormat/Deserializer/ArrayRecordDeserializer.cs
src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Common/BasicObjectTests.cs
src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Legacy/EqualityExtensions.cs

The most expensive thing we're doing in the binary format tests is getting the validation test method for types. I've added a cache for this, which cuts a third of the testing time for the project.
Also adding some theory data helper classes for tuples for clarity and minor perf.
Finally, no need to call the slow method for array index sets for multidimensional arrays.

BinaryFormat test updates

---

src/System.Private.Windows.Core/src/System/Windows/Forms/BinaryFormat/Deserializer/Deserializer.cs
src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Common/EventOrderTests.cs
src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Common/SerializationTest.cs
src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Common/TestTypes/BinaryTreeNodeWithEvents.cs
src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Common/TestTypes/BinaryTreeNodeWithEventsBase.cs
src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Common/TestTypes/BinaryTreeNodeWithEventsISerializable.cs
src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Common/TestTypes/ValueType.cs
src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Common/TestTypes/ValueTypeBase.cs
src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Common/TestTypes/ValueTypeISerializable.cs
src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/FormattedObject/EventOrderTests.cs
src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Formatter/EventOrderTests.cs

- Adds tests for BinaryFormatter and Deserializer to capture what can be observed about the deserialization state in different scenarios based on the various hooks available (`IDeserializationCallback`, `OnDeserialized`, `ISerializable`).
- Flip the ordering of `OnDeserialized` and `IDeserializationCallback` in the deserializer since BinaryFormatter always fires `IDeserializationCallback` last
- Fix bug where multiple callbacks to `OnDeserialized` and `IDeserializationCallback` was occuring in scenario with ISerializable value types

Add Deserialization Event Order Tests

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/TreeView/ArraySubsetEnumerator.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/TreeView/TreeNode.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/TreeView/TreeNodeCollection.cs
src/System.Windows.Forms/tests/UnitTests/SerializableTypesTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/TreeNode.TreeNodeAccessibleObjectTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs

Fixes #11243 
- 
-  manually 
- 
9.0.0-preview.4.24219.3

fix issue 11243 TreeNodeCollection.AddRange has been broken in .NET 8 and no longer results in TreeNodes being drawn at the correct location

---

src/System.Private.Windows.Core/src/System/Windows/Forms/BinaryFormat/Deserializer/ClassRecordDeserializer.cs
src/System.Private.Windows.Core/src/System/Windows/Forms/BinaryFormat/Deserializer/ClassRecordFieldInfoDeserializer.cs
src/System.Private.Windows.Core/src/System/Windows/Forms/BinaryFormat/Deserializer/ClassRecordSerializationInfoDeserializer.cs
src/System.Private.Windows.Core/src/System/Windows/Forms/BinaryFormat/Deserializer/Deserializer.cs
src/System.Private.Windows.Core/src/System/Windows/Forms/BinaryFormat/Deserializer/IDeserializer.cs
src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Common/EventOrderTests.cs

Always hook completed callbacks in the same order that we parse the graph. This gives more predictable results and simplifies the logic a bit.

Simplify completed callbacks

---

src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Common/EventOrderTests.cs
src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Common/TestTypes/BinaryTreeNodeWithEvents.cs
src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Common/TestTypes/BinaryTreeNodeWithEventsISerializable.cs
src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/Common/TestTypes/ObjectReferenceISerializable.cs

Add tests for `IObjectReference` in EventOrderTests to ensure deserialization events relating to `IObjectReference` only fired once

Add Tests for ObjectReference in EventOrderTests

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePickerTests.cs

- Add unit tests for below 6 events
> 1. BackgroundImageLayoutChanged
> 2. Click
> 3. DoubleClick
> 4. ForeColorChanged
> 5. PaddingChanged
> 6. TextChanged
- None
- No
- Minimal
- Unit tests

Add unit test for DateTimePicker 6 events

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/TreeView.TreeViewAccessibleObjectTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeCollectionTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeConverterTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeTests.cs

- Add unit tests for TreeView to test its properties: Name, IsReadOnly, ContextMenuStrip, RowBounds, IsVisible, IsExpanded, EnsureVisible
- Add unit tests for TreeView to test its methods: GetChildCount, Add, Insert, CanConvertTo, ConvertTo, HitTest, FromHandle, ExpandAll, Clone, Collapse, GetNodeCount, Toggle
- None
- No
- Minimal
- Unit tests

Add test coverage for TreeView

---

src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ButtonTests.cs
src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ListViewTests.cs
src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/NumericUpDownTests.cs

Related #11324, #11325, #11326, #11327, #11328, #11329
- Add `SkipOnArchitecture `for following unstable test cases to disable them in X64 run
1. Button_DialogResult_SpaceToClickFocusedButtonAsync
2. Button_Hotkey_Fires_OnClickAsync
3. Button_CancelButton_EscapeClicksCancelButtonAsync
4. Button_PerformClick_Fires_OnClickAsync
5. ListView_Group_NavigateKeyboard_SucceedsAsync
6.  NumericUpDownAccessibleObject_Focused_ReturnsCorrectValueAsync

Skip unstable tests in "ButtonTests", "ListViewTests" and "NumericUpDownTests"

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs

Related https://github.com/dotnet/winforms/issues/11322
- Add judgment logic to the x86 test to skip the following test scenarios `System.Windows.Forms.Tests.DataGridViewTests.DataGridView_OnColumnHeadersHeightChanged_InvokeWithHandle_CallsColumnHeadersHeightChanged(columnHeadersWidthSizeMode: DisableResizing, columnHeadersVisible: True, eventArgs: EventArgs { })`  and `System.Windows.Forms.Tests.DataGridViewTests.DataGridView_OnColumnHeadersHeightChanged_InvokeWithHandle_CallsColumnHeadersHeightChanged(columnHeadersWidthSizeMode: DisableResizing, columnHeadersVisible: True, eventArgs: null)`

Skip unstable test DataGridView_OnColumnHeadersHeightChanged_InvokeWithHandle_CallsColumnHeadersHeightChanged

---

.github/policies/resourceManagement.yml

Attempts to fix 'Remove no recent activity label from pull requests' action from dotnet-policy-service as any activity on it currently removes the label. This copies the same conditions that are on remove waiting for author feedback label

Fix no recent activity label in pull requests

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs

Related #11382
- Add label `SkipOnArchitecture `for test `ToolStrip_WndProc_InvokeMouseActivateWithHandle_Success`

Disable unstable test case "ToolStrip_WndProc_InvokeMouseActivateWithHandle_Success"

---

src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ButtonTests.cs

Related #11327
- Add tag `SkipOnArchitecture `to test case `Button_Press_Enter_Fires_OnClickAsync ` and remove wrongly added tag on test `Button_PerformClick_Fires_OnClickAsync`

Disable test Button_Press_Enter_Fires_OnClickAsync and enable Button_PerformClick_Fires_OnClickAsync

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignerUtils.cs

Fixes #11353
- Changing the `selectionBorderBrush `to use `SystemColors.ControlDarkDark` instead of  `Color.Transparent` as backcolor
-   No
- Minimal
The selected control has a dashed border in the DemoConsole application.
The selected control should have a solid border in the DemoConsole application.
- Manually
- .net 9.0.0-preview.5.24258.12

Using solid border for selected control in the DemoConsole application.

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListView/ListViewItem.ListViewSubItem.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListView/ListViewItem.cs

Fixes #10963
Change `ListViewSubItem.Text` to pass index to `ListViewItem.UpdateSubItems` to avoid loop.

Improve `ListViewSubItem.Text` performance

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/TrackBar.TrackBarAccessibleObjectTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/TrackBar.TrackBarChildAccessibleObjectTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/TrackBar.TrackBarFirstButtonAccessibleObjectTests.cs

- Add unit test for TrackBar Accessible Object in three files: TrackBarAccessibleObjectTests, TrackBarChildAccessibleObjectTests, TrackBarFirstButtonAccessibleObjectTests
- Test TrackBarAccessibleObjectTests method and property: HitTest, DefaultAction
- Test TrackBarChildAccessibleObjectTests properties: Role, State
- Test TrackBarFirstButtonAccessibleObjectTests property: Name

Add test coverage for TrackBar Accessible Object

---

src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ButtonBaseDesigner.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ComboBoxDesigner.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/RadioButtonDesigner.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/RichTextBoxDesigner.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TextBoxBaseDesigner.cs

- Enable nullability in some ControlDesigner members.

Enable nullability in some ControlDesigner members

---

src/System.Windows.Forms/src/System/Windows/Forms/ToolTip/ToolTip.cs

Introduced in  https://github.com/dotnet/winforms/commit/ca1199eb6cfaf8ecd26ee429761764ea264dd2f5 -
Tooltip owner window is used for tooltip placement when tool is not a control, this is the case of ToolStripItems.

Fix refactoring in tooltips

---

src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.RuntimeDataObjectToNativeAdapter.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/IDataObject.cs

Reordered IDataObject's and DataObject's methods alphabetically.
Removed explicit xml doc comments on DataObject's implementation of the managed IDataObject interface 
Removed a duplicate test (format != DataFormats.BitmapConstant) in TryGetBitmapData
Changed return type to MemoryStream from Stream in ReadByteStreamFromHGLOBAL

Minor changes in the Clipboard code

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs

- Add unit tests for ListView to test its events: TextChanged, AfterLabelEdit, BeforeLabelEdit, CacheVirtualItems

Add test coverage for ListView

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs

- Add unit tests for ComboBox to test its properties: AutoCompleteCustomSource, SelectedText
- Add unit test for stability and reliability of ComboBox in EndUpdate and BeginUpdate settings

Add test coverage for ComboBox

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs

Related #11418
- Add `SkipOnArchitecture` for test `ToolStrip_WndProc_InvokeMouseActivate_Success`

Disable unstable test case "ToolStrip_WndProc_InvokeMouseActivate_Success"

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/UpDown/UpDownBase.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/UpDownBaseTests.cs

Makes sure that the `_upDownEdit` and `_upDownButtons` have their tooltip removed.
Fixes #11417
I am unsure how to add tests for this. I manually tested the fix.

Implement missing `RemoveToolTip` on `UpDownBase` to cleanup `ToolTip`

---

src/System.Windows.Forms.Design/src/Resources/SR.resx
src/System.Windows.Forms.Design/src/Resources/xlf/SR.cs.xlf
src/System.Windows.Forms.Design/src/Resources/xlf/SR.de.xlf
src/System.Windows.Forms.Design/src/Resources/xlf/SR.es.xlf
src/System.Windows.Forms.Design/src/Resources/xlf/SR.fr.xlf
src/System.Windows.Forms.Design/src/Resources/xlf/SR.it.xlf
src/System.Windows.Forms.Design/src/Resources/xlf/SR.ja.xlf
src/System.Windows.Forms.Design/src/Resources/xlf/SR.ko.xlf
src/System.Windows.Forms.Design/src/Resources/xlf/SR.pl.xlf
src/System.Windows.Forms.Design/src/Resources/xlf/SR.pt-BR.xlf
src/System.Windows.Forms.Design/src/Resources/xlf/SR.ru.xlf
src/System.Windows.Forms.Design/src/Resources/xlf/SR.tr.xlf
src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hans.xlf
src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hant.xlf
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TabPageCollectionEditor.cs

- Enable nullability in TabPageCollectionEditor.

Enable nullability in TabPageCollectionEditor

---

eng/pipelines/build-PR.yml
eng/pipelines/build.yml

The new version of the powershell script will not place the creds in the nuget.config file, instead it will use standard environment variables. Update the YAML file to use NuGetAuthenticate to avoid a build break that may happen if the credential provider is not available.

Call NuGetAuthenticate after SetupNuGetSources

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DateTimePickerTests.cs

- Add unit tests for below 12 properties
1. CalendarFont
2. Checked
3. CustomFormat
4. DropDownAlign
5. MaxDate
6. MaximumDateTime
7. MinDate
8. MinimumDateTime
9. RightToLeftLayout
10. ShowUpDown
11. Text
12. Value

Add unit test for DateTimePicker 12 properties

---

.editorconfig
src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationGeneratorTests.cs
src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ApplicationConfigurationInitializeBuilderTests.cs
src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System/Windows/Forms/Generators/ProjectFileReaderTests.FontConverter.cs

Makes progress to fix #11041 
Deal with the feedback of the PR #11171 
- Changed untyped test data to use typed TheoryData objects.
- Allowing us to enable xUnit1024 errors in .editorconfig.
- Currently fixes test cases in Windows form analyzer (CSharp) with one exception 
for the file reader font converter.
- No customer impact, just refactoring old test cases.
- No
-There should be no risk in moving to strongly typed parameterized test methods.
- Because the tests are functionally identical, I used the tests that were already present. 
-

Tests should use theory data

---

azure-pipelines-PR.yml
azure-pipelines.yml
eng/pipelines/build-PR.yml
eng/pipelines/build.yml

Enables internal builds (access to internal runtimes and feeds) via azure account tokens and dSAS templates instead of PATs and account SAS.

Enable internal builds using new arcade templates

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/ToolStripDropDownButton.ToolStripDropDownButtonAccessibleObjectTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripCustomIComparerTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripDropDownTests.cs
src/System.Windows.Forms/tests/UnitTests/ToolStripContainerTests.cs

- Add unit tests for ToolStrip to test its properties: Visible, Size, BackgroundImage, CausesValidation, ContextMenuStrip, CausesValidation, Cursor, ForeColor
- Add unit tests for ToolStrip to test its methods: Compare(), Show()
- Add unit tests for ToolStrip to test its events: DockChanged, BackColorChanged, BackgroundImageChanged, BackgroundImageLayoutChanged, BottomToolStripPanelVisible,CausesValidationChanged, ContextMenuStripChanged, CursorChanged

Add Code Coverage For ToolStrip

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DomainUpDownTests.cs

- Add unit tests for DomainUpDown to test DownButton and UpButton methods: Verify the behavior of the DownButton and UpButton methods in the DomainUpDown class and how they change the SelectedIndex under different conditions
-  Add unit test for DomainUpDown to test ToString method: Test ToString method's output, ensuring it correctly reflects the state of the Items collection and the SelectedIndex.
- None
- No
- Minimal
- Unit tests

Add unit tests for DomainUpDown

---

src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/MyServices/ClipboardProxyTests.cs
src/System.Windows.Forms/tests/ComDisabledTests/ClipboardComTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs

Run Clipboard test sequentially, this is not eliminating potential interferences, but is an improvement in my observations, the next step would be to add a Clear in the try/finally block in every test.
enabled nullability in ClipboardTests
Used fluent assertions, particularly BeEquivalentTo was helpful to make some tests more specific. Several test names didn't match the content due to a copy/paste mistake

Cleanup in the ClipboardTests

---

src/System.Windows.Forms/tests/UnitTests/TextBoxBaseTests.cs

Related #11497, #11498
- Add SkipOnArchitecture for tests `TextBoxBase_Copy_PasteNotEmptyWithHandle_Success` and `TextBoxBase_ClearUndo_CanUndo_Success`

Skip test "TextBoxBase_Copy_PasteNotEmptyWithHandle_Success" and "TextBoxBase_ClearUndo_CanUndo_Success"

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/CheckBoxRendererTests.cs

Related #11496
- Add judgement in unit test `CheckBoxRenderer_DrawCheckBox_OverloadWithSizeAndText ` to skip validation of CheckBoxState.CheckedNormal on X86

Issue 11496 skip unstable test CheckBoxRenderer_DrawCheckBox_OverloadWithSizeAndText

---

src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/TreeView/TreeNodeCollection.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeCollectionTests.cs

Fixes #8768 
if tree is already sorted then we don't want to set fixed Index value. due to these reason It is misbehave. 
- No
- Yes
- No
When the user adds a value to the treenode list and sorts it using treeview.sort(), it works fine. Subsequently, when the user adds individual trees through the add event, it functions as expected and sorts the entire tree automatically. However, if the user adds multiple values through AddRange, it does not work as expected.
I've fixed the sorting issue we discussed earlier, and now everything is working smoothly. When users add values individually or use treeview.sort(), the sorting works fine. Even when they add multiple values at once using AddRange, the sorting behaves as expected.
- Testcase added
- tested with .net core 8.0

 8768 :: Resolve Addrange issue after sorting.

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridTests.cs

- Add unit tests for PropertyGrid to test its events: PropertyValueChanged, PropertySortChanged, SelectedObjectsChanged.
- Add unit tests for PropertyGrid to test its methods: CollapseAndExpandAllGridItems, ResetSelectedProperty.

Add test coverage for PropertyGrid

---

global.json

`latest` is not supported by Arcade, and there's no `latest` archive in the Azure blob store, so force a supported value here.
```
CommonLibrary\DownloadAndExtract : Download failed from
https://netcorenativeassets.blob.core.windows.net/resource-packages/external/windows/cmake/cmake-latest-win64-x64.zip
At C:\d\source-indexer\bin\repo\winforms\eng\common\native\install-tool.ps1:90 char:22
```

Specify a version of cmake in global.json

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/LabelAccessibleObjectTests.cs

- Add unit tests for Label.LabelAccessibleObject to test Name property

Add code coverage for LabelAccessibleObject

---

src/System.Windows.Forms/tests/UnitTests/NumericUpDownTests.cs

- Add unit tests for NumericUpDown to test its properties: Hexadecimal, Increment, Maximum, Minimum, ThousandsSeparator, Value
- Add unit tests for NumericUpDown to test its events: PaddingChanged, TextChanged, ValueChanged, 
- Add unit tests for NumericUpDown to test its methods: BeginInit, DownButton, EndInit, ToString, UpButton

Add test coverage for NumericUpDown

---

eng/Version.Details.xml
eng/Versions.props
src/System.Private.Windows.Core/tests/BinaryFormatTests/BinaryFormatTests.csproj
src/System.Windows.Forms.Design/tests/UnitTests/System.Windows.Forms.Design.Tests.csproj
src/System.Windows.Forms/tests/ComDisabledTests/ComDisabled.Tests.csproj
src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj

- Move SystemRuntimeSerializationFormattersPackageVersion in `Versions.prop` and add entry in Version.Details.xml on it to have maestro bump verison in updates
- Update naming to match existing naming pattern

Fix SystemRuntimeSerializationFormatters package version dependency

---

src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintControllerWithStatusDialog.BackgroundThread.cs
src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintControllerWithStatusDialog.StatusDialog.cs

Fixes #11456 
- Create AccessibleObject for PrintStatusDialog
- Change the type of `_cancellingLabel` to a read-only Textbox so that the page counts changing can be announced, since the Label control itself cannot directly receive focus. 
- Yes 
- Minimal
The screen reader does not announce any information about “Generating Previews”.
- Manually
- .net 9.0.0-preview.6.24307.2

Create AccessibleObject for PrintStatusDialog

---

src/System.Drawing.Common/src/System/Drawing/ToolboxBitmapAttribute.cs

Changes to `ToolboxBitmapAttribute` were to avoid errors when a bitmap was expected but the icon file was a png based icon. The try catch method was used elsewhere in the class to avoid similar errors.
Used the method outlined in the linked issue and wrote the following python script to automate:
```python
import os
import subprocess
import glob
ico_files = [f for f in os.listdir('.') if f.endswith('.ico')]
for ico_file in ico_files:
try:
base_name = ico_file.replace('.ico', '')
subprocess.run(['magick', ico_file, f'{base_name}-%d.png'], check=True)
png_files = glob.glob(f'{base_name}-*.png')
if not png_files:
print(f"No .png files were created for {ico_file}. Skipping.")
continue
icotool_command = ['icotool', '-c', '-o', ico_file] + [f'-r{png}' for png in png_files] …
```

Fix `ToolboxBitmapAttribute` to improve error tolerance and better support `PNG` based `ICO` embedded resources

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/MenuStripTests.cs

Related #11560, #11561
- Add SkipOnArchitecture for test "MenuStrip_WndProc_InvokeMouseActivate_Success" and "MenuStrip_WndProc_InvokeMouseActivateWithHandle_Success"

Skip test "MenuStrip_WndProc_InvokeMouseActivate_Success" and "MenuStrip_WndProc_InvokeMouseActivateWithHandle_Success"

---

src/System.Drawing.Common/src/System/Drawing/ImageConverter.cs
src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/Effect.cs
src/System.Windows.Forms/src/System/Windows/Forms/Application.ComponentThreadContext.cs
src/System.Windows.Forms/src/System/Windows/Forms/Application.LightThreadContext.cs

Fixes https://github.com/dotnet/winforms/issues/11493

Fix IDE0036 warnings with newer SDK

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/PictureBox/PictureBox.cs

this will unblock https://github.com/dotnet/sdk/pull/41616
see https://github.com/dotnet/runtime/pull/103456
fix https://github.com/dotnet/winforms/issues/11544

use HttpClient to replace WebClient

---

pkg/Microsoft.Private.Winforms/sdk/dotnet-wpf/Microsoft.NET.Sdk.WindowsDesktop.WindowsForms.targets

Setting default WinForms `msbuild` trim values so that simple WinForms applications like [TrimTest](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/tests/IntegrationTests/TrimTest/TrimTest.csproj) will not generate any trim warnings. These will be used in trimming to set the [RuntimeHostConfigurationOptions](https://github.com/dotnet/sdk/pull/41702) for WinForms trimming.

Set default trim values for WinForms

---

src/System.Windows.Forms/tests/UnitTests/TextBoxBaseTests.cs

Related #11559, #11558
- Add SkipOnArchitecture for test "TextBoxBase_Undo_CanUndo_Success" and "TextBoxBase_Copy_PasteNotEmpty_Success"

Skip test "TextBoxBase_Undo_CanUndo_Success" and "TextBoxBase_Copy_PasteNotEmpty_Success"

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs

- Add unit tests for ComboBox to test its methods: GetItemHeight, ResetText, SelectAll

Add code coverage for combobox

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs

- Add unit tests for below 16 events
> 1. ColumnHeadersBorderStyleChanged
> 2. ColumnHeadersDefaultCellStyleChanged
> 3. DataMemberChanged
> 4. DataSourceChanged
> 5. DefaultCellStyleChanged
> 6. EditModeChanged
> 7. GridColorChanged
> 8. MultiSelectChanged
> 9. ReadOnlyChanged
> 10. RowHeadersBorderStyleChanged
> 11. RowHeadersDefaultCellStyleChanged
> 12. RowsDefaultCellStyleChanged
> 13. CurrentCellChanged
> 14. CurrentCellDirtyStateChanged
> 15. SelectionChanged
> 16. Sorted

Add unit test case for DataGridView 16 events

---

src/System.Drawing.Common/src/CompatibilitySuppressions.xml
src/System.Drawing.Common/src/System/Drawing/Drawing2D/GraphicsPathIterator.cs
src/System.Drawing.Common/tests/System/Drawing/Drawing2D/GraphicsPathIteratorTests.cs

Related to #8954.
This also adds more aggressive input validation to avoid buffer overruns.

Add span overloads to GraphicsPathIterator

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripHighContrastRenderer.cs
src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ToolStripTests.Designer.cs

Fixes #11550
- Unhighlighting the ToolStripMenuItem when it is in the drop-down menu 
- Add third level menu item in ToolStripTests.cs of the test project `WinformsControlsTest`
- The color contrast of the toolStripMenuItem's indeterminate state icon is sufficient, regardless of whether the selected state is enabled or disabled.
- Yes 
- Minimal
toolStripMenuItem is highlighted in unfocused state when its check property is enabled, this causes the color contrast of indeterminate state icon for toolStripMenuItem is less than 3:1.
Unhighlighting the ToolStripMenuItem when it is in the drop-down menu
- Manually
- .net 9.0.0-preview.6.24318.5

Unhighlighting the ToolStripMenuItem when it is in the drop-down menu

---

src/System.Windows.Forms/tests/UnitTests/TextBoxBaseTests.ClipboardTests.cs
src/System.Windows.Forms/tests/UnitTests/TextBoxBaseTests.cs

Related #11227
- Move all Clipboard related tests to a new class and remove SkipOnArchitecture label

Move all Clipboard related tests to a new class and remove SkipOnArchitecture label

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs

- Add unit tests for below 7 events
> 1. BackColorChanged
> 2. BackgroundImageChanged
> 3. BackgroundImageLayoutChanged
> 4. ForeColorChanged
> 5. FontChanged
> 6. PaddingChanged
> 7. TextChanged

Add unit test case for DataGridView 7 events

---

src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
src/System.Windows.Forms/src/System/Windows/Forms/Layout/Containers/ContainerControl.cs

Simplifies some logic in Control.cs.
- Pull in some methods with only a single private caller,
- Invert ifs to reduce nesting
- Use ternary expressions
- Use better variable names
- Use pattern matching

Simplify some logic in Control.cs

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListView/ListView.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/WebBrowser/WebBrowserContainer.cs
src/System.Windows.Forms/src/System/Windows/Forms/Design/ComponentEditorForm.cs

Refactor remaining `GetService` calls to use `GetService<T>` and reduce nesting in `System.Windows.Forms`.

Refactor to use `GetService<T>` and reduce nesting

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripDropDown.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripMenuItem.ToolStripMenuItemAccessibleObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripMenuItem.cs

Fixes #11449
- Modify the ProcessCmdKey() method to support space key.
- Make a focus on the MenuStrip after the user hits enter to check it.
- MenuItems does not respond to the spacebar key to check/uncheck the menu and enter key executes it and closes the menu without focus the menustrip.
- No
-Minimal
- Manual
- 9.0.100-preview.6.24312.9

Make the toolbar menu items support the support space key.

---

azure-pipelines.yml

This is a prerequisite for inclusion on source.dot.net.
It seems a first attempt was made to add winforms.git to source.dot.net [in late 2018](https://github.com/dotnet/source-indexer/commit/34f0c3d814b0e50c030ed46aee2a98f464243acf), but it started failing at some point leading to being missed during index generation.
Generally speaking, "V2" repositories (data sent in by individual repo CI) are more robust for inclusion than the old V1 repos (repo data generated during source-indexer CI runs) - as such we aren't really interested in adding or fixing any V1 repos, and would like to move to V2.
This move also allows the repo owners who know their code best to fine-tune their build flags and environment far more easily than for V1 repos.
Please note that there is …

Add source.dot.net stage 1 asset publication 

---

src/System.Windows.Forms/tests/UnitTests/CheckedListBoxTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/CheckedListBoxItemAccessibleObjectTests.cs

- Add unit test for CheckedListBox to test its event: DrawItem
- Add unit tests for CheckedListBox.CheckedListBoxItemAccessibleObject to test its property: AccessibleStates

Add unit tests for CheckedListBox and CheckedListBox.CheckedListBoxItemAccessibleObject

---

src/System.Windows.Forms/src/PublicAPI.Shipped.txt
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripItem.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemTests.cs

Fixes #10592 
- Enhance ToolStripItem to make Renderer accessable
- ToolStripItem's Renderer accessable
- No
- No
- This modification is very tiny, and doesn't change default behavior.

Modify the accessibility of ToolStripItem's "Renderer" to enable subclasses to set custom renderers and reuse OnPaint logic

---

.github/policies/resourceManagement.yml

If issue was waiting for author feedback and author responds, have the bot add untriaged label to ensure we see it again during triage if not earlier

Add Untriaged to Issue when Author Responds

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/Labels/LinkLabel.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGrid.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellTests.cs

Didn't have the using scope correct. Did a regex to try and find other places where this mistake might have been made and fixed another found in PropertyGrid.
Fixes #11680

Fix image rendering in LinkLabel

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/TrackBar/TrackBar.cs

Fixes https://github.com/dotnet/winforms/issues/11639
[Docs](https://learn.microsoft.com/en-us/windows/win32/controls/tbm-setticfreq) for `TBM_SETTICFREQ` explicitly calls out that the trackbar must have style `TBS_AUTOTICKS` to use this message. We had not checked to ensure that was the case before sending `TBM_SETTICFREQ`. As it turns out, sending this message without the trackbar having style `TBS_AUTOTICKS` actually messes up the native side's internal state, causing this issue under certain values. The fix here is to make sure that we always check if the trackbar has `TBS_AUTOTICKS` before sending `TBM_SETTICFREQ`. We had been doing this incorrectly in 2 places which I have gone ahead in fix. I also did minor clean up.
**Before:**
scenario 1: issue repro - Trackbar does not have …

Only Send TBM_SETTICFREQ if AutoTick Enabled

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/TreeNode.TreeNodeAccessibleObjectTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeCollectionTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewTests.cs

**Proposed changes**
- Add unit tests for TreeView to test its properties:CanGetDefaultActionInternal, CanGetNameInternal, IsItemSelected, CanGetValueInternal, VisibleCount
- Add unit tests for TreeView to test its methods: Contains(), Reset()

Add code coverage for treeview

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/MonthCalendarDesignerTests.cs

Related to #10773 
- Add test case for MonthCalendarDesigner.

Add test case for MonthCalendarDesigner

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataObjectTests.cs

The first commit separates FORMATs into a set that does not result in managed serialization and a set that is serialized by our code. These sets are then used to generate test data.
The second commit is a mechanical replacement of Asserts with fluent assertions.

Cleanup in DataObjectTests

---

src/System.Windows.Forms/src/Resources/SR.resx
src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf

Fixes #11682
Preventing a trim warning with `BinaryFormatter` serialization requires an earlier [check ](https://github.com/dotnet/winforms/blob/main/src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs#L25)on its use using the same `AppContext` string. The exception message related to this included a reference to trimming which non-trim users can also see. Changing the exception message to remove the trimming reference.

Change the exception message for the BinaryFormatter use

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs

- Add unit tests for below 21 events
> 1. AutoSizeColumnsModeChanged
> 2. AutoSizeRowsModeChanged
> 3. CellDoubleClick
> 4. CellEndEdit
> 5. CellEnter
> 6. CellFormatting
> 7. CellLeave
> 8. CellMouseClick
> 9. CellMouseDoubleClick
> 10. ColumnDividerDoubleClick
> 11. ColumnHeaderMouseClick
> 12. ColumnHeaderMouseDoubleClick
> 13. ColumnHeaderCellChanged
> 14. ColumnMinimumWidthChanged
> 15. ColumnNameChanged
> 16. ColumnRemoved
> 17. ColumnSortModeChanged
> 18. ColumnToolTipTextChanged
> 19. ColumnWidthChanged
> 20. DataBindingComplete
> 21. DefaultValuesNeeded

Add unit test case for DataGridView 21 events

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/RadioButton.RadioButtonAccessibleObjectTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RadioButtonTests.cs

- Add unit test for RadioButton to test its property: CheckAlign
- Add unit test for RadioButton.RadioButtonAccessibleObject to test its properties: Name, KeyboardShortcut

Add unit tests for RadioButton and RadioButton.RadioButtonAccessibleObject

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/MaskDescriptorTests.cs

Add unit test file: MaskDescriptorTests.cs for public properties of the MaskDescriptor

Add test code coverage for MaskDescriptor

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DateTimePickerDesignerTests.cs

- Add unit test file: DateTimePickerDesignerTests.cs for public properties of the DateTimePickerDesigner

Add unit tests for DateTimePickerDesigner

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.FlatComboAdapter.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.cs
src/System.Windows.Forms/tests/UnitTests/TextBoxBaseTests.cs

Fixes #[2053861]( https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2053861)
- Separate `DrawPopUpCombo `from `DrawFlatCombo `method，draw the outer black border only when the ComboBox mouse is over
- Combobox no longer flickers when hovering over it
- No
- Minimal
Combo box flashes when you move the mouse over it
Combo boxes no longer flicker when you move the mouse over them
- Manually
- .net 9.0.0-preview.6.24305.2

Issue 2053861 fix combo box flickering issue

---

src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.Designer.cs
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.MyScrollableControl.cs
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.MyUserControl.cs
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.cs

Related #11669 #11678
- Adds remaining missing controls from #4908 to the `DemoConsole` app, in the new tab (ToolStripContainer) added by PR #11678.
- Inserts instances of missing designers in the newly created tab:
- `System.Windows.Forms.Design.UpDownBaseDesigner` (base class of `NumericUpDown`)
- `System.Windows.Forms.Design.SplitterDesigner`
- Won't need to add because instances already exist in other tabs of the `DemoConsole` app:
- `System.Windows.Forms.Design.TextBoxBaseDesigner` (base class of `TextBox`)
- `System.Windows.Forms.Design.ButtonBaseDesigner` (base class of `Button`)
- The remainder of the controls [could not be instantiated](https://github.com/dotnet/winforms/pull/11707#issuecomment-2237840141) and [will be investigated …

Add remaining missing designer instances to DemoConsole, in complement to #11678

---

src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/ControlBodyGlyph.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.TransparentBehavior.cs

- Enable nullability in TransparentBehavior.

Enable nullability in TransparentBehavior

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ImageListDesignerTests.cs

- Add unit test ImageListDesignerTests.cs for public properties and method of the ImageListDesigner
> 1. ActionLists

Add unit test for ImageListDesigner

---

src/System.Windows.Forms.Design/tests/UnitTests/ButtonBaseDesignerTests.cs

- Add unit test `ButtonBaseDesignerTests.cs` for public properties and method of the ButtonBaseDesigner

Add unit tests for ButtonBaseDesigner

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ImageListImageTests.cs

- Add unit test ImageListImageTests.cs for public properties and method of the ImageListImage.
- Enable nullability in ImageListImage.

Add unit test for ImageListImage

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/MaskedTextBoxTextEditorTests.cs

- Add unit test `MaskedTextBoxTextEditorTests.cs` for public properties and method of the MaskedTextBoxTextEditor

Add tests for MaskedTextBoxTextEditor

---

src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/DemoConsole.csproj

Fixes #11710
- Add binary Formatter package to DemoConsole.csproj
- The components control in the Democonsole application can be moved
- Yes
- Mininal
BinaryFormatter error when moving the components control in the Democonsole application
https://github.com/user-attachments/assets/490d421b-363a-454a-a154-de622080bbfa
The components control in the DemoConsole application can be moved normally
- Manually
- .net 9.0.0-preview.7.24371.6

Add binary Formatter package to DemoConsole

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGrid.PropertyTabCollectionTests.cs

- Add unit test for PropertyGrid.PropertyTabCollection to test its properties: Count, this.
- Add unit test for PropertyGrid.PropertyTabCollection to test its method: AddTabType.

Add test coverage for PropertyGrid.PropertyTabCollection

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNode.IKeyboardToolTipTests.cs

Related #11752
- Add condition to skip validation of the scenario `System.Windows.Forms.Tests.TreeNode_TreeNodeIKeyboardToolTipTests.TreeNodeIKeyboardToolTip_InvokeIsHoveredWithMouse_ReturnsExpected(insideTreeView: True, isHovered: True, expected: True`) on x64

Skip test TreeNodeIKeyboardToolTip_InvokeIsHoveredWithMouse_ReturnsExpected

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ListBoxDesigner.cs
src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ListBoxDesignerTests.cs

- Add unit test `ListBoxDesignerTests.cs` for public properties and method of the ListBoxDesigner
- Enable nullability in ListBoxDesigner.

Add tests for ListBoxDesigner

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/MaskDescriptorTemplateTests.cs

Add unit test file: MaskDescriptorTemplateTests.cs for public properties/Methods of the MaskDescriptorTemplate

Add code coverage for MaskDescriptorTemplate

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGrid.cs

It is possible to not have a PropertyDescriptor, we should handle that case.
Fixes #11768

Handle null PropertyDescriptor in PropertyGrid value set event

---

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomSerializerBase.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourceCodeDomSerializer.cs

Overlooked in the code review when removing the tracing.
I've done a full review twice. Two other small tweaks to WriteResource to remove the TraceScope name.
Fixes #11657

Put back AddStatement call in CodeDomSerializer

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BindingContextTests.cs

Related #11795
- Add SkipOnArchitecture for test "BindingContext_Item_GetIListSourceDataSourceWithDataMemberReturningIListNull_ThrowsArgumentNullException"

Disable test case "BindingContext_Item_GetIListSourceDataSourceWithDataMemberReturningIListNull_ThrowsArgumentNullException“

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.FlatComboAdapter.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapter.cs

Fixes #11760
- When the control is ToolStripComboBox, redraw the control when the mouse hovers. (It's mean that revert the changes of PR #11529 when the ComboBox's dropdown button is using small button)
- The ToolStripComboBox can be used normally without weird display
- Yes
- Minimal
When hovering over drop-down arrow of ToolStripComboBox, an additional blue hover effect appears outside the icon.
https://github.com/user-attachments/assets/65127428-e7df-4c92-878d-def027ca0be6
No additional blue hover effect appears outside the icon.
- Manually
- 9.0.0-preview.7.24370.5

Issue 11760 fix tool strip combo box display

---

global.json
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DesignSurfaceExt/NameCreationServiceImp.cs

Fixes #11700
When adding a control, the counter should not count by the control type, but by Text+Type.Name.
Assuming that there is already a ToolStripMenuItem named Test in the contextScript, when we add the default ToolStripMenuItem, when the first ToolStripMenuItem is found, the counter takes on the value of +1, but in the subsequent codes does not satisfy the name. StartsWith() condition in the subsequent code, causing the counter to take the value of 1.
This causes the program to enter the else branch:
https://github.com/dotnet/winforms/blob/a52e943ec837fdec352cd8bd542266d01a278568/src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DesignSurfaceExt/NameCreationServiceImp.cs#L63-L66
- Adjusting the Counter Position to make sure the control name can be correctly assigned.
- …

Adjusting the counter to fix the naming errors in DemoConsole App

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/FlowPanelDesignerTests.cs

- Add unit test file: FlowPanelDesignerTests.cs for public properties of the FlowPanelDesigner.cs file.

Add unit tests for FlowPanelDesigner

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/NotifyIconDesignerTests.cs

Related to #10773 
- Add test case for NotifyIconDesigner.

Add test case for NotifyIconDesigner

---

src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs
src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewCellStyle.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewLinkCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripItem.cs
src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
src/System.Windows.Forms/src/System/Windows/Forms/Layout/CommonProperties.cs
src/System.Windows.Forms/src/System/Windows/Forms/Layout/FlowLayout.cs
src/System.Windows.Forms/src/System/Windows/Forms/PropertyStore.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyStoreTests.cs

Property Store Refactor

---

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/GdiPlus/GdiPlusCache.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/RefCountedCache.CacheEntry.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/RefCountedCache.cs
src/System.Windows.Forms.Primitives/src/System/Windows/Forms/SinglyLinkedList.cs
src/System.Windows.Forms.Primitives/tests/UnitTests/System/Windows/Forms/RefCacheTests.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewTopLeftHeaderCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/Rendering/FontCache.cs
src/System.Windows.Forms/src/System/Windows/Forms/Rendering/GdiCache.cs

We'll need to expose the cache entry to retain handles for fonts that we expose the HFONT on. Notably this would be with calls to WM_SETFONT.

Expose CacheEntry from RefCountedCache

---

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/ScaleHelper.cs
src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ApplicationTests.cs

Fixes #11037
- Сhange the default font only if it has really changed. Most of these problems already was solved in f36b0db2400247c3ed68b9538f92ab6914896b1d.
- Not use scaled default font for system fonts.
- Not dispose user (external) fonts.
- Fewer font changing related actions and a bit less memory use.
- Bug fixes.
- Yes
- Minimal.
- Existing unit tests.
- New unit tests.
- Manually with test app: [DefFontTest.zip](https://github.com/dotnet/winforms/files/14957130/DefFontTest.zip)

Default font scaling corrections and optimizations. Fix #11037.

---

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CommandSet.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.ComponentDataObject.cs
src/System.Windows.Forms/src/System/Resources/ResXDataNode.cs
src/System.Windows.Forms/src/System/Resources/ResXSerializationBinder.cs
src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/AxHost.PropertyBagStream.cs
src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/Control.ActiveXImpl.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.NativeToWinFormsAdapter.cs

Fixes #11804
- Suppresses CodeQL for BinaryFormatter deserialization for several files
- Wasn't able to suppress CodeQl for 2 files, due to the following reasons:
- `src/System.Windows.Forms/src/System/Resources/ResXSerializationBinder.cs`, line 69: No reference to `BinaryFormatter` in the whole file (except in a comment)
- `src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.ComposedDataObject.NativeDataObjectToWinFormsAdapter.cs`, line 208: The file could not be found
- None
- No
- Minimal
- 9.0.100-preview.5.24307.3

Suppress CodeQL for BinaryFormatter deserialization in several files

---

src/System.Drawing.Common/src/System/Drawing/Font.cs
src/System.Drawing.Common/src/System/Drawing/FontConverter.cs
src/System.Drawing.Common/src/System/Drawing/FontFamily.cs
src/System.Drawing.Common/src/System/Drawing/Text/FontCollection.cs
src/System.Drawing.Common/tests/System/Drawing/FontFamilyTests.cs
src/System.Drawing.Common/tests/System/Drawing/FontTests.cs

There is no need to track or dispose of FontFamily objects from the installed font collection. This collection is a static in GDI+. Ref counting needs to be done only when coming from a private collection.
- Should fix ref count issues with private font collections
- Static FontFamily objects are now safe to use after "disposal"
- Removes an unnecessary creation of an empty private font collection in FontConverter
- Reuses FontFamily instances if from installed fonts

Don't dispose FontFamily objects from installed fonts

---

src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.cs

Fixes #11792
- 
- `surface.CreateControl` will add the Control to the designer form, so we don't have to add these controls to `tabPage6`
-

fix The RichTextBox control is not support the SmartTag under ToolStripContainer tab

---

src/System.Windows.Forms.Design/src/System/Drawing/Design/ColorEditor.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/Control.ControlAccessibleObjectTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.ControlCollection.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Properties.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ScreenTests.cs

Fixes #3361
- Add `using` or `control?.Dispose()` to unit tests
- lower risk of hanging CI test runs
- No
- Minimal
- Tests were leaving controls for GC to collect
- Controls are disposed before UI thread terminates
- Set a breakpoint in the Control.Dispose function to confirm that it is executed successfully

Dispose controls that using in unit tests

---

src/System.Drawing.Common/src/GlobalUsings.cs
src/System.Drawing.Common/src/System/Drawing/Graphics.cs
src/System.Drawing.Common/src/System/Drawing/Internal/SystemColorTracker.cs
src/System.Drawing.Common/src/System/Drawing/Lock.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/MenuCommandService.cs
src/System.Windows.Forms.Primitives/tests/TestUtilities/NoAssertContext.cs
src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs
src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
src/System.Windows.Forms/src/System/Windows/Forms/Control.ThreadMethodEntry.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ImageList/ImageList.NativeImageList.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ImageList/ImageListStreamer.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/PictureBox/PictureBox.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripManager.cs
src/System.Windows.Forms/src/System/Windows/Forms/DataBinding/Command.cs
src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs
src/System.Windows.Forms/src/System/Windows/Forms/NotifyIcon.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataFormats.cs
src/System.Windows.Forms/src/System/Windows/Forms/OwnerDrawPropertyBag.cs
src/System.Windows.Forms/src/System/Windows/Forms/Rendering/FontCache.cs
src/System.Windows.Forms/src/System/Windows/Forms/Screen.cs
src/System.Windows.Forms/src/System/Windows/Forms/SendKeys/SendKeys.cs
src/System.Windows.Forms/src/System/Windows/Forms/Timer.cs
src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/ScreenshotService.cs

Change internal lock objects to System.Threading.Lock
Fixes #11672

Change locks to System.Threading.Lock

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.AdornerWindow.MouseHook.cs
src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/AxHost.AxContainer.cs
src/System.Windows.Forms/src/System/Windows/Forms/Application.ThreadContext.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/GridEntry.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyGridView.MouseHook.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripManager.ModalMenuFilter.HostedWindowsFormsMessageHook.cs
src/System.Windows.Forms/src/System/Windows/Forms/NativeWindow.cs
src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintControllerWithStatusDialog.BackgroundThread.cs
src/System.Windows.Forms/src/System/Windows/Forms/Timer.cs

Better to have explicit lock objects from a maintenance perspective.
Ideally we can whittle down some of the other locks on non Lock objects, but we need to be very careful about where we might be inadvertently exposing the ability to lock externally. Even if you can technically do so, we might want to take the breaking change for some of these in 10.

Stop locking internal objects with `this`

---

src/System.Windows.Forms/src/System/Windows/Forms/OLE/DropSource.cs

Related to https://github.com/dotnet/winforms/issues/11847
Regression was introduced in https://github.com/dotnet/winforms/pull/10319 because we had removed a condition to check whether drag image is present. Re-adding that conditional the PR originally took out in DropSource. I checked this issue is fixed and the issue linked PR resolved remains fixed.

Fix Cursor Display Incorrectly On Drag

---

src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/CloneTestListView.cs
src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.Designer.cs
src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ListViewTest.cs

https://github.com/dotnet/winforms/issues/11658#issuecomment-2246680860
Add a manual test case for clones ListViewItem to WinformsControlsApp.
When we try to call the ListView's derived class to use a clone of ListViewItem, we need to be aware that the clone's ListView is actually null, so we need to add an extra judgment when calling methods like OnItemChecked
```
if (e.Item.ListView == this)
{
...
} 
```
to ensure that the code doesn't throw an exception at runtime because the ListView property of the cloned object is null.

Add a manual test case for clones ListViewItem to WinformsControlsApp

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxAutoCompleteSourceConverter.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TextBoxAutoCompleteSourceConverterTests.cs

Fixes #11806 
This issue caused the PR #8276
- Correct the logic of the function GetStandardValues of the file TextBoxAutoCompleteSourceConverter
- The "AutoCompleteSource" property of the TextBox control can be used normally
- Yes 
- Minimal
The value set for the property "AutoCompleteSource" of the TextBox control is missing
The value of the "AutoCompleteSource" property of the TextBox control is fully displayed
- Manually(Tested in DemoConsole)
-  .net 9.0.0-rc.1.24406.14

Correct the logic of the function GetStandardValues of the file TextBoxAutoCompleteSourceConverter

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTextBoxTests.cs

Add unit tests for toolstrip to test its properties & methods & events

Add code coverage for ToolStripTextBox

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SplitContainerDesigner.cs
src/System.Windows.Forms.Design/tests/UnitTests/SplitContainerDesignerTests.cs

Fixes #11793
When `SplitContainer` is deleted, two things will happen
1.`SplitContainerDesigner.Dispose(bool)` will be invoked,and eventually `ComponentDesigner.Dispose(bool)` will be invoked.
So in the end, `SplitContainerDesigner.Component` will be null
https://github.com/dotnet/winforms/blob/ab9eb71f903d7771849887a15ab5ff3f37ba4c00/src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ComponentDesigner.cs#L452-L464
2. `SplitContainerDesigner.ActionList` will be accessed.
https://github.com/dotnet/winforms/blob/ab9eb71f903d7771849887a15ab5ff3f37ba4c00/src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SplitContainerDesigner.cs#L39-L42
https://github.com/dotnet/winforms/blob/ab9eb71f903d7771849887a15ab5ff3f37ba4c00/src/System.Windows.Forms.Design/src/System/Windows …

Fix:The SplitContainer control cannot be deleted successfully under ToolStripContainer tab #11793

---

global.json
src/BuildAssist/BuildAssist.msbuildproj

Related: https://github.com/dotnet/sdk/pull/42699
Implemented [suggestion](https://github.com/dotnet/sdk/pull/42699#issuecomment-2288280126) to resolve build error when moving to use Preview 7 SDK

Fix AxHosts.csproj build errors with Preview 7 SDK

---

src/Microsoft.VisualBasic.Forms/src/Microsoft.VisualBasic.Forms.vbproj
src/Microsoft.VisualBasic.Forms/tests/UnitTests/Microsoft.VisualBasic.Forms.Tests.vbproj
src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/AssemblyPublicKeyIsAsExpectedTest.vb
src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.vb
src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/TimeTests.vb
src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/UserTests.UserIdentity.vb
src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/UserTests.UserPrincipal.vb
src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/UserTests.vb
src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/Devices/AudioTests.cs
src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/MyServices/ClipboardProxyTests.cs

Partially Fixes #11655 Replace PR #11819 targeting Features/10.0
Add tests to VB Runtime that require no changes to existing code and change existing VB Test to use FluentAssertions 
Improves code coverage
- No
- None, only adds test
Only adds and improves tests and improves test coverage

Recreate VB tests only based on Features 10 (Review 1st)

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridView.Methods.cs
src/System.Windows.Forms/src/System/Windows/Forms/ToolTip/ToolTip.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTests.cs

Fixes https://github.com/dotnet/winforms/issues/11837
`DataGridView` completely owns its `KeyboardToolTip` so it should be disposed of when the DataGridView is disposed of to avoid a situation where calls to the KeyboardToolTip leads to the disposed DataGridView.
Also added a debug failto catch any other places we might be getting into the `Hide` method with a disposed control.

Dispose KeyboardToolTip when DataGridView is disposed

---

src/System.Windows.Forms.Primitives/tests/TestUtilities.Tests/PathLengthTests.cs

This test compares length of file paths in this repo against the MAX_PATH const, we assume that path length of the repo root is 40 chars or less, this leaves MAX_PATH - 1 - 40 chars for the path that we see in the GH (portion from src to .cs). This test enforces this limit be enumerating all repo files, getting the full path length and comparing this length against the maximim. Maximum full path length should be compensated for repo roots that are shorter than 40.
```
MaxRootLength + <relative path to the file>.Length < 259
MaxRootLength + <full path to the file>.Length  - currentRootLength  < 259
<full path to the file>.Length  < 259 - MaxRootLength + currentRootLength  
```

belated feedback on https://github.com/dotnet/winforms/pull/11835/

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/SplitterPanelDesigner.cs

Fixes #11790
- Since [applyClipping is always true when deleting the ComboBox](https://github.com/dotnet/winforms/issues/11790#issuecomment-2288199065), `TextRenderer.DrawText()` should be called with `TextFormatFlags.PreserveGraphicsClipping` flag to avoid the issue.
- None
- No
- Minimal
- Manual
- 9.0.100-preview.5.24307.3

Add clipping and transforms from Graphics to DC when repainting watermark in SplitterPanelDesigner

---

src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb
src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
src/System.Windows.Forms/src/System/Windows/Forms/Form.cs

* Fixes issue where in Visual Basic the "classic" Visual Styles are no longer get set. (This is a breaking change, since in VB the classic Visual Styles are no longer set, even if they are enabled in the VS App Framework Property Pages.) 
NOTE: This has nothing to do with the originally considered `VisualStylesMode` Experimental feature in the dark mode context.
* Fixes issue where instead of the `FormCaptionTextColorChanged` event the `FormCaptionBackColorChanged` event is raised (This is not a breaking change, since these are completely new events.)
Fixes #11898.
Fixes #11897.
Fixes #11895.
Fixes #11910.

Dark mode/Visual Styles (VB Only) fix

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripDropDown.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripMenuItem.ToolStripMenuItemAccessibleObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripMenuItem.cs

Revert #11520 to fix a MenuItem issue.

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListView/ListView.cs
src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/CloneTestListView.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs

Fixes #11658
Add `e.item.ListView == this` to the OnItemChecked method to avoid throwing an accessiblity object not created exception when the ListViewItem is a clone.
- Verify that this item belongs to this ListView in OnItemChecked method.
- When the ListViewItem is a clone, the OnItemChecked method does not throw an accessiblity object not created exception.
- Yes
- Minimal
- Manually

Fix OnItemChecked method throw exception when the ListViewItem is clone object.

---

src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/Analyzers/MissingPropertySerializationConfiguration/ControlPropertySerializationDiagnosticAnalyzerTest.cs
src/System.Windows.Forms.Analyzers.CodeFixes.CSharp/System/Windows/Forms/CSharp/CodeFixes/AddDesignerSerializationVisibility/AddDesignerSerializationVisibilityCodeFixProvider.cs
src/System.Windows.Forms.Analyzers.CodeFixes.VisualBasic/AddDesignerSerializationVisibility/AddDesignerSerializationVisibilityCodeFixProvider.vb
src/System.Windows.Forms.Analyzers.VisualBasic/tests/UnitTests/System.Windows.Forms.Analyzers.VisualBasic.Tests/MissingPropertySerializationConfigurationAnalyzerTest.vb

Backport the MissingSerializationConfiguration Analyzer Fix into .NET 9RC1.
(See #11904)
We phased out the binary serializer in .NET 9 Preview 5 and start collecting and addressing feedback since than. One of the efforts to improve Customer's security and make the phasing out easier, was the introduction of Analyzers to guide through the process. One of the serializers/code fixes helps customers to identify Properties of Controls which could serialize their content accidentally. There were some cases, were the code fix did not work as expected, and this PR fixes those.
Workaround: You would need to make the code change manually.
Regression?
Risk
Verification

[RC1/9.0] Backport SecAnalyzer (11904)

---

src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb
src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ApplicationTests.cs

Backport the Dark Mode Fix into .NET 9RC1.
The original bug fix (#11907) addressed a series of issues (#11910, #11898, #11897, #11895).
Since the original bug fix used Properties-APIs, which are not available in .NET 9RC/Rel, a few adjustments had to be made here. To further ensure stability, I added basic unit tests for dark mode. 
We introduced a new experimental Feature “Dark Mode”. This accidentally regressed VB Apps, which are no longer able to enable Visual Styles. This PR would also address a couple of minor issues in Dark Mode itself, which have been found in recent testing.
Workaround: For the VB Part, there is no easy workaround, since `Application.EnableVisualStyles` is usually run in Program.cs, and in a VB App Framework App, there is no equivalent. 
The issues of the new …

[RC1/9.0] Backport Dark Mode fix

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripDropDown.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripMenuItem.ToolStripMenuItemAccessibleObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripMenuItem.cs

Backport the Menu Item Fix (#11920) into .NET 9RC1 to fix #11909.
Since the original bug fix used Properties-APIs, which are not available in .NET 9RC/Rel, a few adjustments had to be made here. 
The original A11Y PR introduced a breaking change, and it is specifically blocking [Rick Brewster (the maintainer of Paint .NET)](https://blog.getpaint.net/) to migrate Paint.NET to .NET 9, which is another reason why I would like this to get in into RC1 already, to unblock all folks, who have been started to migrate to .NET 9 and are blocked by this.
Workaround: There is none.

[RC1/9.0] Backport MenuItemFix

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs

Fixes [designer/issues/2707](https://github.com/microsoft/winforms-designer/issues/2707)
We use `_requestedHeight` to set the height of a ComboBox when `DropDownStyle` is `ComboBoxStyle.Simple`
https://github.com/dotnet/winforms/blob/70a6a7b4a9af452160e636838f946b3f4327383c/src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.cs#L61-L63
Let's go through the repro steps that was described here https://github.com/microsoft/winforms-designer/issues/2707#issuecomment-799222994
The following steps also can repro this issue:
1. Create a Winforms .Net Core project with a ComboBox
2. Close and reopen form designer
3. Set the DropDownStyle of comboBox as Simple
Step I : Create a Winforms .Net Core project with a ComboBox
I think this is the generated code
``` c#
private …
```

fix winforms-designer/issues/2707  The comboBox incorrect display on form designer when setting its DropDownStyle as Simple after building the project

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripDropDown.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripMenuItem.ToolStripMenuItemAccessibleObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripMenuItem.cs

Backport the Menu Item Fix (#11920) into .NET 9RC1 to fix #11909.
•	[MenuStrip highlight "sticks" after menu item is activated, also affects keyboard focus · Issue #11909 · dotnet/winforms (github.com)](https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fdotnet%2Fwinforms%2Fissues%2F11909&data=05%7C02%7CTatiana.Solyanik%40microsoft.com%7C36f94292375f495ee51e08dcc134fd67%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C638597680547308270%7CUnknown%7CTWFpbGZsb3d8eyJWIjoiMC4wLjAwMDAiLCJQIjoiV2luMzIiLCJBTiI6Ik1haWwiLCJXVCI6Mn0%3D%7C0%7C%7C%7C&sdata=39FGpIQnB4NPJMw0XM67CQZP42CPl8dvsjfZmpj3Vak%3D&reserved=0)
This is a breaking change, and it is specifically blocking [Rick Brewster (the maintainer of Paint .NET)](https://nam06.safelinks.protection.outlook.com/?url=https%3A% …

[release/9.0] [RC2] Revert #11520 to fix a MenuItem issue

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewImageCell.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellTests.cs

Fixes #11927
This regressed due to some property store work in .NET 10. `PropertyStore.AddOrRemoveValue` will remove the value from the property store if the value is the default value. 
When setting `DataGridViewImageCell.ImageLayout` we cannot remove the value in the property store even if the value being set is the default because our getter for ImageLayout had always returned `DataGridViewImageCellLayout.Normal` if the property had not been set, not the default value, which is `DataGridViewImageCellLayout.NotSet`. This means with the current code if the user sets the ImageLayout to `DataGridViewImageCellLayout.NotSet`, when retrieving ImageLayout we will receive `DataGridViewImageCellLayout.Normal` instead, which is not expected. 
Updated the code to never remove the property store …

Fix Setting DataGridViewImageCell.ImageLayout to NotSet

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripMenuItemTests.cs

Add unit tests for ToolStripMenuItem to test its properties & methods & events

Add code coverage for ToolStripMenuItem

---

src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb
src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ApplicationTests.cs

Backport the Dark Mode Fix into .NET 9Rel.
The original bug fix (#11907) addressed a series of issues (#11910, #11898, #11897, #11895).
Since the original bug fix used Properties-APIs, which are not available in .NET 9RC/Rel, a few adjustments had to be made here. To further ensure stability, I added basic unit tests for dark mode. 
We introduced a new experimental Feature “Dark Mode”. This accidentally regressed VB Apps, which are no longer able to enable Visual Styles. This PR would also address a couple of minor issues in Dark Mode itself, which have been found in recent testing.
Workaround: For the VB Part, there is no easy workaround, since `Application.EnableVisualStyles` is usually run in Program.cs, and in a VB App Framework App, there is no equivalent. 
The issues of the new …

[RC2/9.0] Backport Dark Mode fix

---

src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/Analyzers/MissingPropertySerializationConfiguration/ControlPropertySerializationDiagnosticAnalyzerTest.cs
src/System.Windows.Forms.Analyzers.CodeFixes.CSharp/System/Windows/Forms/CSharp/CodeFixes/AddDesignerSerializationVisibility/AddDesignerSerializationVisibilityCodeFixProvider.cs
src/System.Windows.Forms.Analyzers.CodeFixes.VisualBasic/AddDesignerSerializationVisibility/AddDesignerSerializationVisibilityCodeFixProvider.vb
src/System.Windows.Forms.Analyzers.VisualBasic/tests/UnitTests/System.Windows.Forms.Analyzers.VisualBasic.Tests/MissingPropertySerializationConfigurationAnalyzerTest.vb

Backport the MissingSerializationConfiguration Analyzer Fix into .NET 9Rel.
(See #11904)
We phased out the binary serializer in .NET 9 Preview 5 and start collecting and addressing feedback since than. One of the efforts to improve Customer's security and make the phasing out easier, was the introduction of Analyzers to guide through the process. One of the serializers/code fixes helps customers to identify Properties of Controls which could serialize their content accidentally. There were some cases, were the code fix did not work as expected, and this PR fixes those.
Workaround: You would need to make the code change manually.
Regression?
Risk
Verification

[RC2/9.0] Backport SecAnalyzer (11904)

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/MaskPropertyEditorTests.cs

- Add unit test MaskPropertyEditorTests.cs for public properties and method of the MaskPropertyEditor.
- Enable nullability in MaskPropertyEditor.

Add unit tests for MaskPropertyEditor

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DesignBindingPicker.cs

Fixes #11925
- Add  `TextFormatFlags.PreserveGraphicsClipping | TextFormatFlags.PreserveGraphicsTranslateTransform` to TextFormatFlags of the class `HelpTextLabel`
-  None
-  No
- Minimal
The DemoConsole app under the Winforms repo will stop running when opening the smattag of the DataGridView and click the dropdown button of the "Choose Data Source"
The DemoConsole app can be debug normally
- Manually
- .net 9.0.0-rc.1.24413.14

Update the TextFormatFlags of the HelpTextLabel

---

docs/testing.md

Update testing.md to add section about Clipboard tests
- Update node `Throw unhandled exceptions` which does not exist in the directory to `Strategy` and the link of node `Theory tests`
- Add section about Clipboard tests (What is a Sequential Collection? and Why Use a Sequential Collection for Clipboard-Related Tests? and Which types of tests should use Sequential Collection? )

Update testing.md: Add section about Clipboard tests

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ContextMenuStripGroupTests.cs

- Add unit test ContextMenuStripGroupTests.cs for public properties and method of the ContextMenuStripGroup.
- Enable nullability in ContextMenuStripGroup.

Add unit tests for ContextMenuStripGroup

---

src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/FolderNameEditorTests.cs

Related #10773
- Adds code coverage to `FolderNameEditor`
- None
- No
- Minimal
- Unit tests

Adds code coverage to FolderNameEditor

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripComboBoxTests.cs

Add unit tests for ToolStripComboBox to test its properties & methods & events

Add code coverage for toolstripComboBox

---

azure-pipelines.yml

With move to 1ES templates, Policheck and TSA Upload stopped working as they are not enabled by default. We need to opt in for them to work.

Enabling Policheck and TSA Upload in CI builds

---

src/System.Windows.Forms.Analyzers.CSharp/src/System/Windows/Forms/CSharp/Analyzers/AvoidPassingTaskWithoutCancellationToken/AvoidPassingTaskWithoutCancellationTokenAnalyzer.cs
src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/Analyzers/AvoidPassingTaskWithoutCancellationToken/AvoidPassingTaskWithoutCancellationTokenTest.cs
src/System.Windows.Forms.Analyzers.VisualBasic/src/Analyzers/AvoidPassingTaskWithoutCancellationToken/AvoidPassingTaskWithoutCancellationTokenAnalyzer.vb
src/System.Windows.Forms.Analyzers.VisualBasic/src/Analyzers/MissingPropertySerializationConfiguration/MissingPropertySerializationConfigurationDiagnosticAnalyzer.vb
src/System.Windows.Forms.Analyzers.VisualBasic/tests/UnitTests/System.Windows.Forms.Analyzers.VisualBasic.Tests/AvoidPassingTaskWithoutCancellationTokenTest.vb

There is a file name length check in place for .NET 9, which we either don't have or need for main.
#11976 was hit by that and this needed to be addressed.
So, curiously enough, to be in sync with namespace and filename naming, this is the backport of that backport modification.

Backport the fix of a Backport of the Async Analyzer

---

Directory.Build.props
src/Microsoft.VisualBasic/tests/UnitTests/GlobalUsings.cs
src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/Devices/AudioTests.cs
src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/Devices/NetworkTests.cs
src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/MyServices/ClipboardProxyTests.cs

* Enable simple creation of VB test projects in this repo solution by not forcing preview language version which is not supported by VB
* Use fluent assertions in ClipboardProxyTests  - copied from Loni's PR https://github.com/dotnet/winforms/pull/11527 for future merging.

Minor cleanup

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/CustomMenuItemCollectionTests.cs

- Add unit test CustomMenuItemCollectionTests.cs for public properties and method of the CustomMenuItemCollection.
- Enable nullability in CustomMenuItemCollection.

Add unit tests for CustomMenuItemCollection

---

eng/Versions.props

Bump Microsoft.Private.Intellisense version to consume latest API documentation
This will be backported to release/9.0

Bump Microsoft.Private.Intellisense version

---

src/System.Windows.Forms/tests/UnitTests/TextBoxBaseTests.ClipboardTests.cs

Related #12002
- Add `Clipboard.Clear();` at the begin of all tests

Add Clipboard.Clear(); at the end of the tests

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DesignerToolStripControlHostTests.cs

- Add unit test DesignerToolStripControlHostTests.cs for public properties and method of the DesignerToolStripControlHost.
- Enable nullability in DesignerToolStripControlHost.

Add unit tests for DesignerToolStripControlHost

---

src/System.Drawing.Common/src/System/Drawing/Drawing2D/Matrix.cs
src/System.Drawing.Common/src/System/Drawing/Drawing2D/PathGradientBrush.cs
src/System.Drawing.Common/src/System/Drawing/Graphics.cs
src/System.Drawing.Common/src/System/Drawing/Imaging/ColorMatrix.cs
src/System.Drawing.Common/src/System/Drawing/Imaging/ColorPalette.cs
src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/Effect.cs
src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/GrayScaleEffect.cs
src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/InvertEffect.cs
src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/SepiaEffect.cs
src/System.Drawing.Common/src/System/Drawing/Imaging/Effects/VividEffect.cs
src/System.Drawing.Common/src/System/Drawing/Imaging/ImageAttributes.cs

Adds/edits some missing documentation for public methods
Also change Effect.Dispose from public -> virtual according to API review https://github.com/dotnet/winforms/issues/8835#issuecomment-1954987873

Add missing documentation for public methods in System.Drawing

---

src/System.Windows.Forms/src/PublicAPI.Shipped.txt
src/System.Windows.Forms/src/System/Windows/Forms/Controls/WebBrowser/HtmlElement.cs

Fixes #[2240374](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2240374?src=WorkItemMention&src-action=artifact_link)
- Could not fork AzDo dotnet-winforms due to lack of permissions.
- Changes orient to orientation for compliance reasons.
- None
- Minimal

Fixes term due to compliance

---

Winforms.sln
src/System.Private.Windows.Core/src/System/Private/Windows/Core/BinaryFormat/BinaryFormatWriter.cs
src/System.Private.Windows.Core/src/System/Private/Windows/Core/Nrbf/SerializationRecordExtensions.cs
src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/FormattedObject/BinaryFormatWriterTests.cs
src/System.Private.Windows.Core/tests/BinaryFormatTests/SerializationRecordExtensionsTests.cs
src/System.Windows.Forms/src/System/Resources/ResXDataNode.cs
src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/Control.ActiveXImpl.cs
src/System.Windows.Forms/src/System/Windows/Forms/BinaryFormat/WinFormsBinaryFormatWriter.cs
src/System.Windows.Forms/src/System/Windows/Forms/Nrbf/WinFormsSerializationRecordExtensions.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.BinaryFormatUtilities.cs
src/System.Windows.Forms/tests/ComDisabledTests/ClipboardComTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BinaryFormatUtilitiesTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs

Added Nrbf record extension/BinaryFormatWriter read/write functions for System.Drawing.Primitives types that are designer-serialized using TypeConverters, but require BinaryFormatter in Clipboard read/write operations. These types are
Color
Point
Rectangle
Size
SizeF
After this change, Clipboard operations with these types do not require the OOB BinaryFormatter implementation, see changes in ClipboardTests.cs for an example.

System.Drawing.Primitives types should not require BinaryFormatter in Clipboard operations

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripSplitStackDragDropHandlerTests.cs

Add unit tests for ToolStripSplitStackDragDropHandler to test its properties & methods & events

Add code coverage for ToolStripSplitStackDragDropHandler

---

src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
src/System.Windows.Forms/src/System/Windows/Forms/Control.cs

Don't set DWMWA_USE_IMMERSIVE_DARK_MODE if users haven't explicitly made a choice.
This creates havoc for existing dark mode implementors.
Fixes #12014

Don't set DWMWA_USE_IMMERSIVE_DARK_MODE unnecessarily

---

src/System.Drawing.Common/src/System/Drawing/Bitmap.cs
src/System.Drawing.Common/src/System/Drawing/FontFamily.cs
src/System.Drawing.Common/src/System/Drawing/Graphics.cs
src/System.Drawing.Common/src/System/Drawing/Image.cs
src/System.Drawing.Common/src/System/Drawing/Imaging/ColorPalette.cs
src/System.Drawing.Common/src/System/Drawing/Imaging/Metafile.cs
src/System.Drawing.Common/src/System/Drawing/PointerExtensions.cs
src/System.Drawing.Common/src/System/Drawing/Region.cs
src/System.Drawing.Common/src/System/Drawing/Text/FontCollection.cs
src/System.Drawing.Common/tests/System/Drawing/FontFamilyTests.cs
src/System.Private.Windows.Core/src/System/Drawing/CoreImageExtensions.cs
src/System.Private.Windows.Core/src/Windows/Win32/Foundation/IPointer.cs
src/System.Private.Windows.Core/src/Windows/Win32/Foundation/IPointerExtensions.cs
src/System.Private.Windows.Core/src/Windows/Win32/Foundation/PointerExtensions.cs
src/System.Private.Windows.Core/src/Windows/Win32/Graphics/Gdi/RegionScope.cs
src/System.Private.Windows.Core/src/Windows/Win32/Graphics/GdiPlus/GpBitmapExtensions.cs
src/System.Private.Windows.Core/src/Windows/Win32/Graphics/GdiPlus/GpImageExtensions.cs
src/System.Private.Windows.Core/src/Windows/Win32/Graphics/GdiPlus/GpMetafileExtensions.cs

Fixes https://github.com/dotnet/winforms/issues/11983
This issue occurs because System.Private.Windows.Core is included in the ref as C# needs the types to be there when it compiles interface casts (https://github.com/dotnet/winforms/pull/10673), but this also causes issues for us in CLI/CLR C++ mixed mode as shown in issue. 
This is a workaround that updates our `IPointer<T>` interface to avoid returning a generic as it present compile issues in CLI/CLR C++ mixed mode. This looks to be a limitation that is in mix mode as this error occurs with non WindowsForms related classes that have similar implementation. This workaround mitigates this issue while coordination is happening to determine a fix.
Tested by building dlls from change and replacing System.Drawing.Common.dll and …

Change IPointer interface method to return nint

---

src/System.Drawing.Common/src/System/Drawing/Bitmap.cs
src/System.Drawing.Common/src/System/Drawing/Graphics.cs
src/System.Drawing.Common/src/System/Drawing/Image.cs
src/System.Drawing.Common/src/System/Drawing/Imaging/ColorPalette.cs
src/System.Drawing.Common/src/System/Drawing/Imaging/Metafile.cs
src/System.Drawing.Common/src/System/Drawing/PointerExtensions.cs
src/System.Drawing.Common/src/System/Drawing/Region.cs
src/System.Private.Windows.Core/src/System/Drawing/CoreImageExtensions.cs
src/System.Private.Windows.Core/src/Windows/Win32/Foundation/IPointer.cs
src/System.Private.Windows.Core/src/Windows/Win32/Foundation/PointerExtensions.cs
src/System.Private.Windows.Core/src/Windows/Win32/Graphics/Gdi/RegionScope.cs
src/System.Private.Windows.Core/src/Windows/Win32/Graphics/GdiPlus/GpBitmapExtensions.cs
src/System.Private.Windows.Core/src/Windows/Win32/Graphics/GdiPlus/GpImageExtensions.cs
src/System.Private.Windows.Core/src/Windows/Win32/Graphics/GdiPlus/GpMetafileExtensions.cs

backport of #12103
**Customer Impact:**
Currently, users are unable to compile some of our controls in CLI/CLR C++ mixed code project because C++/CLI cannot compile when it encounters generic pointers even if it is internal code. The PR is a workaround that makes changes to avoid returning generic pointers in our internal interface. 
**Risk:**
Minimal. This is a change in our internal code to ensure C++/CLI is able to compile successfully by changing the return type of affected interface method. Anywhere we were using the interface method we have updated to use an extension method to achieve the same behavior as before. This has been tested and confirmed C++/CLI is able to compile successfully with change.

[release/9.0] Change IPointer interface method to return nint (#12103)

---

docs/debugging.md

Fixes #12114 
- Document additional references required to debug Windows Forms binaries using technique <span>#</span>2.

Document additional references required to debug

---

docs/debugging.md

Related to #12114 and addresses the comment in https://github.com/dotnet/winforms/commit/4c2a4bb420175d97226e9da75581d4bebceb5311#r146586472.
- Document additional references required to debug Windows Forms binaries.
- Update the reference output paths TFM to net9.0.

Update the Debugging document reference output paths TFM to net9.0

---

Directory.Build.props
NuGet.config
eng/Versions.props
src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System.Windows.Forms.Analyzers.CSharp.Tests.csproj
src/System.Windows.Forms.Analyzers.VisualBasic/tests/UnitTests/System.Windows.Forms.Analyzers.VisualBasic.Tests/System.Windows.Forms.Analyzers.VisualBasic.Tests.vbproj
src/System.Windows.Forms.Analyzers/tests/UnitTests/System.Windows.Forms.Analyzers.Tests.csproj
src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/CollectionEditorTests.cs
src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/MaskedTextBoxTextEditorTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/DataGridViewCellAccessibleObjectTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ApplicationContextTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxSystemMonitorTests.cs

Related: https://github.com/dotnet/arcade/issues/15019

Enable NuGet Audit and Fix Errors

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/RichTextBox/RichTextBox.OleCallback.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripDropTargetManager.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DropTarget.cs

Fixes #10504 
- Notify the drag-image manager prior to invoking the DragDrop and DragLeave event handlers.
- Fixes an issue where a drag-image remnant remains on the screen after a drag and drop completes if an unhandled exception occurs during DragDrop or DragLeave.
- No
-
- Manual

Notify the drag-image manager prior to invoking the DragDrop and DragLeave events

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripPanel.ToolStripPanelRowCollectionTests.cs

Add unit tests for ToolStripPanel_ToolStripPanelRowCollection to test its properties & methods & events

Add code coverage for ToolStripPanel_ToolStripPanelRowCollection

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/TabPageDesignerTests.cs

- Add unit test file: TabPageDesignerTests.cs for public properties of the TabPageDesigner.cs.
- Enable nullability in TabPageDesignerTests.cs.

Add unit test for TabPageDesigner.cs file

---

src/System.Windows.Forms/tests/UnitTests/TextBoxBaseTests.ClipboardTests.cs

Fixes #12002
- Add Thread.Sleep before executing control.Paste
- Add  control.Focus() before control.Copy()
-  No
- Minimal
Running all tests in TextBoxBaseTests.ClipboardTests, there will always be 3-6 cases failing in 10 iterations
Run all tests in TextBoxBaseTests.ClipboardTests for 100 iterations without failure
- Manually

Add Thread.Sleep before executing control.Paste

---

src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/CantStartSingleInstanceException.vb

Improves XML Comments #11984 
- Add missing XML comment to CantStartSingleInstanceException
-  Improve development experence
- 
- No
- None only comment additions

Add XML Comments to CantStartSingleInstanceException

---

src/System.Private.Windows.Core/src/System.Private.Windows.Core.csproj
src/System.Private.Windows.Core/tests/BinaryFormatTests/BinaryFormatTests.csproj
src/System.Windows.Forms.Primitives/tests/TestUtilities/System.Windows.Forms.Primitives.TestUtilities.csproj
src/System.Windows.Forms/src/System.Windows.Forms.csproj
src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj

With dotnet/runtime#107905, we are marking `System.Formats.Nrbf` as `[Experimental]`, using diagnostic ID `SYSLIB5005`. This suppresses the diagnostics produced by that annotation.
We plan to backport this change to `release/9.0` and `release/9.0-rc2`.

Suppress SYSLIB5005 for System.Formats.Nrbf as experimental

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/RichTextBoxActionListTests.cs

Related #10773
- Adds code coverage for `RichTextBoxActionList`
- Coverage for the `EditLines()` method could not be added. The dependent method `EditorServiceContext.EditValue(_designer, Component!, "Lines")` is static and could not be mocked, and the dialog that opens during its execution requires manual intervention to close.
- None or succinct description
- No
- Minimal
- Unit tests

Add code coverage for RichTextBoxActionList

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/FormatControlTests.cs

Related #10773
- Adds code coverage to `FormatControl`.
- None
- No
- Minimal
- Unit tests
- 9.0.100-rc.1.24452.12

Adds code coverage to FormatControl

---

src/Common/tests/TestUtilities/BinaryFormatterScope.cs
src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/MyServices/ClipboardProxy.vb
src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/MyServices/ClipboardProxyTests.cs
src/System.Private.Windows.Core/src/System/Private/Windows/Core/Nrbf/SerializationRecordExtensions.cs
src/System.Private.Windows.Core/tests/BinaryFormatTests/BinaryFormatTests.csproj
src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/FormattedObject/ListTests.cs
src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/FormattedObject/PrimitiveTypeTests.cs
src/System.Windows.Forms/tests/UnitTests/System.Windows.Forms.Tests.csproj
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BinaryFormatUtilitiesTests.cs

* Added round trip tests for binary formatted payload under restricted clipboard formats
* Removed verification is BinaryFormatter is on or off from the switch as this behavior is now shipped.
* Removed CollectionDefinition attribute from a test class

Added more  clipboard  roundtrip tests

---

src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs
src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewButtonCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewCellStyle.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewCheckBoxCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewComboBoxCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewHeaderCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewImageCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewLinkCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewTextBoxCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/Labels/Label.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripItem.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripMenuItem.cs
src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
src/System.Windows.Forms/src/System/Windows/Forms/PropertyStore.cs

It is pretty common to have default values that aren't the same as the type `default`. As such, being explicit about the default value allows pairing with `GetValueOrDefault`.
We don't want to maintain entries in the dictionary for things that aren't actually needed.

Add default value to PropertyStore.AddOrRemoveValue

---

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/AccessibilityExtensions.cs

SMALL fix for part of ##11984
- Correct spelling AccessibiltyExtensions for fixe and class
- N/A
- No
-Changing name of internal class might have risks but all tests pass

Fix spelling of AccessibilityExtensions, rename file as well as class

---

src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.NativeToWinFormsAdapter.cs

This PR fixes issue https://github.com/dotnet/winforms/issues/12190 where users receive an incomplete list of formats for the data they are dragging/dropping and receive `true` when calling `GetDataPresent` with formats that the DataObject did not have, rendering APIs unusable. This regressed in 9.0 preview 1 while converting our interop code to leverage cswin32. We had accidentally removed a while loop in our `GetFormats()` method so we only retrieved the first format in the list. 
For `GetDataPresent`, we had updated to check the results of `QueryGetData` for success, but `QueryGetData` can return `HRESULT.S_FALSE` which is considered "success", causing the return of `true` for formats that the DataObject did not actually have.
Tested with issue repro scenario to verify this fixes the …

[release/9.0] Fix GetFormats and GetDataPresent

---

src/System.Drawing.Common/tests/System/Drawing/BitmapTests.cs
src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ArrayEditorTests.cs
src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/CollectionEditorTests.cs
src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/DesignerCommandSetTests.cs
src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/ComboBoxTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/AccessibleObjectTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/Control.ControlAccessibleObjectTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/ErrorProviderAccessibleObjectTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ColorDialogTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBox.ComboBoxUiaTextProviderTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ComboBoxTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.ControlCollection.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FileDialogTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FontDialogTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListControlTests.cs
src/System.Windows.Forms/tests/UnitTests/TextBoxTests.cs

Fixes # #12153
- Fix spelling errors is test Names related to Overridden, IAccessible and doesn't
-  For developers fewer spelling errors cluttering up the error window 
- No
- no code changes only rename if test names

Fix spelling of Overridden and IAccessible and doesnt in test names

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/TextBoxActionListTests.cs

- Add unit test TextBoxActionListTests.cs for public properties and method of the TextBoxActionList.
- Enable nullability in  TextBoxActionList.

Add unit tests for  TextBoxActionList

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripLabelTests.cs

Add unit tests for ToolStripLabe.cs to test its properties & methods & events

Add code coverage for ToolStripLabel.cs file

---

src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/Control.ActiveXImpl.cs
src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/Labels/Label.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStrip.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripDropDown.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripItem.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripPanel.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripPanelRow.cs
src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
src/System.Windows.Forms/src/System/Windows/Forms/Layout/Containers/ContainerControl.cs
src/System.Windows.Forms/src/System/Windows/Forms/Layout/DefaultLayout.cs
src/System.Windows.Forms/src/System/Windows/Forms/Layout/TableLayout.cs
src/System.Windows.Forms/src/System/Windows/Forms/PropertyStore.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemTests.cs

This actually removes one of the legacy methods, so yay progress.
In Form the owned forms set is now a `List<Form>` rather than a manually managed array.

Update another set of PropertyStore usages

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/FormatStringDialogTests.cs

Related #10773
- Adds code coverage for `FormatStringDialog`.
- None
- No
- Minimal
- Unit tests
- 9.0.100-rc.1.24452.12

Adds code coverage to FormatStringDialog

---

src/System.Private.Windows.Core/src/System/Value.cs
src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridView.Methods.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridView.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewBand.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewCellStyle.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewLinkCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewRow.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListView/ListView.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStrip.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripItem.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripMenuItem.cs
src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
src/System.Windows.Forms/src/System/Windows/Forms/Layout/Containers/ContainerControl.cs
src/System.Windows.Forms/src/System/Windows/Forms/PropertyStore.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ListViewTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyGridInternal/AccessibleObjects/PropertyDescriptorGridEntry.PropertyDescriptorGridEntryAccessibleObjectTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/PropertyStoreTests.cs

- Tweak AddOrRemove methods for better change comparison
- Make it consistently throw if trying to force cast null to T
Follow up:
- Try and lock down harder on insertion of null values. Considering using a sentinel perhaps.
- Try to move away from CreateKey. Considering using enum(s), making PropertyStore generic, etc.

Remove remaining old PropertyStore APIs

---

src/System.Windows.Forms/tests/UnitTests/ClipboardTestBase.cs
src/System.Windows.Forms/tests/UnitTests/TextBoxBaseTests.ClipboardTests.cs

Fixes #12229
- Add `[UISettings(MaxAttempts = 3)]` instead of `Thread.Sleep(100)` for **TextBoxBaseTests.ClipboardTests.cs**
Results of 1000 iterations：

Add retry mechanism for clipboard tests

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/FormatStringEditorTests.cs

Related #10773
- Adds code coverage to `FormatStringEditor`
- None
- No
- Minimal
- Unit tests
- 9.0.100-rc.1.24452.12

Adds code coverage to FormatStringEditorTests

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridView.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewRow.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowTests.cs

Fixes https://github.com/dotnet/winforms/issues/12187 in .NET 9.0 release
Revert "Makes DataGridView row header left border have proper luminosity in RightToLeft mode, both with VisualStyles enabled or disabled" commit 9bda02dfd677f1e7d87c223cc5f8717e2add2d8a. This change regresses the color contrast issue that we will re-do in NET10. Besides this regression, the original fix was incomplete, as it applied only to RightToLeft layout.
Customer will observe visual difference between NET8 and NET9.
While fixing a color contrast issue https://github.com/dotnet/winforms/issues/5961 in .NET9, we regressed a customization scenario where dev sets a custom DataGridView grid color. The grid color now partially shows in the column header bar. It should be applied only to the regular DGV cells. …

[release/9.0] Extra Border Color in DataGridView with RightToLeft layout

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridView.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewRow.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowTests.cs

This is a cherry pick from release/9.0
git cherry-pick 5ef6d46e559a95f7b1a23895b111d8ca536f3fcf
Fixes #12187 in .NET 10 release
Revert "Makes DataGridView row header left border have proper luminosity in RightToLeft mode, both with VisualStyles enabled or disabled" commit 9bda02d. This change regresses the color contrast issue that we will re-do in NET10. Besides this regression, the original fix was incomplete, as it applied only to RightToLeft layout.
Customer will observe visual difference between NET8 and NET9. While fixing a color contrast issue #5961 in .NET9, we regressed a customization scenario where dev sets a custom DataGridView grid color. The grid color now partially shows in the column header bar. It should be applied only to the regular DGV cells.
Yes
Manual testing
Low. …

Extra Border Color in DataGridView with RightToLeft layout

---

src/System.Windows.Forms/tests/UnitTests/NumericUpDownTests.cs

Warning:
In language version preview, the 'field' keyword binds to a synthesized backing field for the property. To avoid generating a synthesized backing field, and to refer to the existing member, use 'this.field' or '@field' instead.

Get rid of a warning in the latest IntPreview VS build

---

src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs

Backport of https://github.com/dotnet/winforms/pull/10536, fixes https://github.com/dotnet/winforms/issues/12157
We are leaking a Graphics object causing the finalizer to run to dispose it, which is sub optimal. Users can also see a `OutOfMemoryException` surface from this.
Manual verification that leak is not present
Low. The change involves avoid creating a new Graphics object here, which is unnecessary

[release/8.0] Avoid Creating Graphics in TabControl.WmReflectDrawItem()

---

src/Microsoft.VisualBasic/tests/UnitTests/Microsoft/VisualBasic/Logging/LogTests.cs

Fixes IDE0002 in LogTests.cs
- Fix IDE0002 in LogTests.cs
- Development Only
- No, it was missed when global usings was added 4/21/2023
- None

Fix IDE0002 in LogTests.cs

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ToolStripContainerDesignerTests.cs

- Add unit test ToolStripContainerDesignerTests.cs for public properties and method of the ToolStripContainerDesigner.
- Enable nullability in ToolStripContainerDesignerTests.cs.

Add unit tests for ToolStripContainerDesigner

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/MaskedTextBoxTextEditorDropDownTests.cs

Related #10773
- Add test file `MaskedTextBoxTextEditorDropDownTests.cs`  for MaskedTextBoxTextEditorDropDown

Add tests for MaskedTextBoxTextEditorDropDown.cs

---

src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/AxHost.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs

Fixes https://github.com/dotnet/winforms/issues/12056
We had missed a release in `CreateWithoutLicense`, causing the underlying ocx to linger after `AxHost` control disposal. Made the same adjustment for `CreateWithLicense`. While investigating also noticed a missing release for `ShowPropertyPages` so fixed this as well. Regression test has been added for this issue scenario.

Ensure proper ref count of underlying ocx

---

src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs

Backport of #12281 to release/8.0
Upon doing improvements to our interop code, we had missed releasing a pointer to the underlying ocx of the AxHost control, which was causing the underlying ocx to linger even after customer AxHost control is disposed. This causes the destructor of the underlying ocx to not get called because it still has a ref count of 1, causing issues with resource management in their application.
Tested manually with customer repro scenario and added regression test for the scenario.
Low. Change involves releasing the pointer we missed, correcting the ref count.

[release/8.0] Ensure proper ref count of underlying ocx

---

.editorconfig
eng/Versions.props
src/System.Private.Windows.Core/src/Windows/Win32/Graphics/GdiPlus/EncoderParameters.cs
src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.ImmGetContext.cs
src/System.Windows.Forms.Primitives/src/Windows/Win32/PInvoke.ImmReleaseContext.cs
src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/EmfRecord.cs
src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/Oleaut32/SAFEARRAYTests.cs
src/System.Windows.Forms/src/System/Windows/Forms/Control.Ime.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.FlatComboAdapter.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewComboBoxCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/MaskedTextBox.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStrip.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapter.cs
src/System.Windows.Forms/src/System/Windows/Forms/Input/InputLanguage.cs

Updates to the latest release of CSWin32 and updates code where necessary.
Also add back explicit span casts where VS IntelliSense is unable to differentiate. Without this contributors would need to have access to internal preview feeds.

Update CSWin32 to v0.3.106

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ItemTypeToolStripMenuItem.cs
src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ItemTypeToolStripMenuItemTests.cs

- Add unit test ItemTypeToolStripMenuItemTests.cs for public properties and method of the ItemTypeToolStripMenuItem.
- Enable nullability in ItemTypeToolStripMenuItem.

Add unit tests for ItemTypeToolStripMenuItem

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripSplitButtonTests.cs

Add unit tests for ToolStripSplitButton.cs to test its properties & methods & events

Add code coverage for ToolStripSplitButton

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ImageListDesigner.OriginalImageCollection.cs
src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ImageListDesignerOriginalImageCollectionTests.cs

Fixes #12291
Related #10773
- Fixes the `Remove()` and `IndexOf()` methods in the `ImageListDesigner.OriginalImageCollection` class, which had the wrong argument types in their signatures;
- Adds code coverage for that class.
- None
- No
- Minimal
- Unit tests
- 9.0.100-rc.1.24452.12

Fixes the `Remove()` and `IndexOf()` methods in the `ImageListDesigner.OriginalImageCollection` class and adds coverage to it

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DataGridViewCellStyleBuilderTests.cs

- Add unit test DataGridViewCellStyleBuilderTests.cs for public methods of the DataGridViewCellStyleBuilder.
- Enable nullability in DataGridViewCellStyleBuilderTests.cs.

Add unit tests for DataGridViewCellStyleBuilder

---

src/System.Windows.Forms/src/System/Windows/Forms/AxHost.OleInterfaces.cs
src/System.Windows.Forms/src/System/Windows/Forms/WebBrowserSiteBase.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AxHostTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/WebBrowserTests.cs

Backport of #12333 to release/8.0
When creating a WebBrowser an InvalidCastException always occurs. Due to this, users will experience usability issues as WebBrowser will be broken and not receive any events. This regressed upon doing improvements to our interop code and was missed because this fails silently due to a try/catch. When constructing a WebBrowser, one of the objects that is created is a ConnectionPointCookie, which checks that an argument of the constructor is an instance of type IPropertyNotifySink. With the move to leveraging cswin32, this should've been updated to IPropertyNotifySink.Interface, but was missed. 
Added regression tests to ensure WebBrowser is created successfully and events are received.
Low. The change involves updating to check against the correct …

[release/8.0] Fix ConnectionPointCookie usages

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/SplitterPanelDesignerTests.cs

1. Add unit test SplitterPanelDesignerTests.cs for public properties and method of the SplitterPanelDesigner.
2. Enable nullability in SplitterPanelDesignerTests.cs.

Add test for SplitterPanelDesigner.cs

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DesignerExtendersTests.cs

- Add unit test DesignerExtendersTests.cs for public properties and method of the DesignerExtenders.
- Enable nullability in DesignerExtenders.

Add unit tests for DesignerExtenders

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DataGridViewComponentPropertyGridSiteTests.cs

- Add unit test DataGridViewComponentPropertyGridSiteTests.cs for public methods of the DataGridViewComponentPropertyGridSite.
- Enable nullability in DataGridViewComponentPropertyGridSiteTests.cs.

Add unit tests for DataGridViewComponentPropertyGridSite

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ToolStripContentPanelDesignerTests.cs

- Add unit test ToolStripContentPanelDesignerTests.cs for public properties and method of the ToolStripContentPanelDesigner.
- Enable nullability in ToolStripContentPanelDesignerTests.cs.

Add unit tests for ToolStripContentPanelDesigner

---

src/System.Private.Windows.Core/src/Resources/SR.resx
src/System.Private.Windows.Core/src/System/Private/Windows/Core/BinaryFormat/Deserializer/ClassRecordFieldInfoDeserializer.cs
src/System.Private.Windows.Core/src/System/Private/Windows/Core/BinaryFormat/Deserializer/DefaultTypeResolver.cs
src/System.Private.Windows.Core/src/System/Private/Windows/Core/BinaryFormat/Deserializer/DeserializationOptions.cs
src/System.Private.Windows.Core/src/System/Private/Windows/Core/BinaryFormat/Deserializer/Deserializer.cs

Copy the DefaultTypeResolver back from the Runtime.
This also replaces SerializationBinder in the options with ITypeResolver.
Additionally, use a bool instead of FormatterAssemblyStyle.

Add the DefaultTypeResolver

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripStatusLabelTests.cs

Modified the unit tests for ToolStripStatusLabelTests.cs to ensure corresponding constructor is called

Modified the test case to ensure corresponding constructor is called

---

src/System.Private.Windows.Core/src/NativeMethods.txt
src/System.Private.Windows.Core/src/Windows/Win32/Foundation/HandleRef.cs
src/System.Private.Windows.Core/src/Windows/Win32/PInvoke.GetWindowText.cs
src/System.Private.Windows.Core/src/Windows/Win32/PInvoke.GetWindowTextLength.cs
src/System.Private.Windows.Core/src/Windows/Win32/PInvoke.MapWindowPoints.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/MultilineStringEditor.MultilineStringEditorUI.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ListViewDesigner.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripAdornerWindowService.cs
src/System.Windows.Forms.Primitives/src/NativeMethods.txt
src/System.Windows.Forms.Primitives/tests/UnitTests/Interop/User32/GetWindowTextTests.cs
src/System.Windows.Forms/src/System/Windows/Forms/Accessibility/LabelEditAccessibleObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/Accessibility/LabelEditUiaTextProvider.cs
src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/Control.ActiveXImpl.cs
src/System.Windows.Forms/src/System/Windows/Forms/Control.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.ComboBoxItemAccessibleObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.ComboBoxUiaTextProvider.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/RichTextBox/RichTextBox.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxBase.TextBoxBaseUiaTextProvider.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/TextBoxBase.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/StatusStrip.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripManager.ModalMenuFilter.cs
src/System.Windows.Forms/src/System/Windows/Forms/Dialogs/CommonDialogs/FileDialog.cs
src/System.Windows.Forms/src/System/Windows/Forms/Internal/WinFormsUtils.cs
src/System.Windows.Forms/src/System/Windows/Forms/ToolTip/ToolTip.cs
src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/TestHelpers.cs
src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/Infra/SendInput.cs

Move GetWindowText and MapWindowPoints to Core.
Also add cast operators for HandleRef to faciliate converting between the generic and non-generic version to help WPF which publically exposes the generic version.

Move GetWindowText to Core

---

src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs

Fixes #12365 
- 
- Change the text color to black
- 
- No
- low
- 
- manual 
-

fix #12365 [Accessibility] The text "Document does not contain any pages" in printPreviewControl has low color contrast

---

pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-CSharp/net6.0/Form1.Designer.cs
pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsApplication-VisualBasic/Form1.Designer.vb
pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-CSharp/net6.0/UserControl1.Designer.cs
pkg/Microsoft.Dotnet.WinForms.ProjectTemplates/content/WinFormsControlLibrary-VisualBasic/UserControl1.Designer.vb

Fixes #8350
-  Removing `this.` and full namespace names from  InitializeComponent() template of the `Form1.Designer.cs` and `Form1.Designer.vb` 
- Modern CodeDom serialization templates can be applied when creating new projects
-  No
- Minimal
`this./Me.` still showed in InitializeComponent() when creating a new Winforms C#/VB project
The `this./Me.` are removed
- Manually
- .net 9.0.100

Update InitializeComponent() template 

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyGridView.cs
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.cs

Fixes #12031
- Removing `CommonEditorHide` to cancel closing dropdown when performing a refresh on the property page
- In the SelectRow method, when the drop-down box gets the focus, _selectedGridEntry will be null and `CommonEditorHide` should not be executed.
- When property is in set, cancels the action of setting the focus on property page
- Add Checkbox to Demo Console
-  The property "Auto size" drop-down menu option now works properly by toggling it using the up/down arrow keys
-  No
- Minimal
When we navigate to "Auto Size" dropdown using the up/down arrow keys, it is getting auto selected without hitting ENTER key
When we navigate to the "Auto-Size" drop-down menu using the up/down arrow keys, the selected menu item toggles normally
-  Manually
- .net 10.0.0-alpha.1.24519.3

Update the logic about the attribute [RefreshProperties(RefreshProperties.All)] on PropertyGridView.cs

---

src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/ApplicationServicesExceptionsTests.vb
src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/CompilerServicesTests.vb
src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/SingleInstanceHelpersTests.vb
src/Microsoft.VisualBasic.Forms/tests/UnitTests/System/Windows/Forms/UserTests.UserPrincipal.vb
src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/Generators/ProjectFileReaderTests.FontConverter.cs
src/System.Windows.Forms.Analyzers.VisualBasic/tests/UnitTests/System.Windows.Forms.Analyzers.VisualBasic.Tests/AvoidPassingTaskWithoutCancellationTokenTest.vb
src/System.Windows.Forms.Analyzers.VisualBasic/tests/UnitTests/System.Windows.Forms.Analyzers.VisualBasic.Tests/MissingPropertySerializationConfigurationAnalyzerTest.vb

Fixes VB issues caused by dotnet#12426) in tests
- Fix all the VB issues exposed by PR #12426
- reduces developer noise in Visual Studio
- Yes, in source but not with respect to customer using code
- None, 100% changes are in tests

Fix VB issues caused by dotnet#12426) in tests

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DataSourceDescriptorCollectionTests.cs

- Add unit test DataSourceDescriptorCollectionTests.cs for public properties and method of the DataSourceDescriptorCollection
- Enable nullability in DataSourceDescriptorCollectionTests.cs

Add unit tests for DataSourceDescriptorCollection

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DataSourceGroupCollectionTests.cs

- Add unit test DataSourceGroupCollectionTests.cs for public methods of the DataSourceGroupCollection.
- Enable nullability in DataSourceGroupCollectionTests.cs.

Add unit tests for DataSourceGroupCollection

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ImageIndexEditorTests.cs

Fixes #12237 
Related #10773
- Fixes namespace for the `ImageIndexEditorTests` class.
- None
- Minimal
- 9.0.100-rc.2.24474.12

Fix namespace for ImageIndexEditorTests

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TrackBarRendererTests.cs

Add unit tests for TrackBarRenderer.cs to test its properties & methods

Add code coverage for TrackBarRenderer

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ContextMenuStripActionListTests.cs

- Add unit test ContextMenuStripActionListTests.cs for public properties and method of the ContextMenuStripActionList.
- Enable nullability in ContextMenuStripActionList.

Add unit tests for ContextMenuStripActionListTests

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ToolStripContentPanelDesignerTests.cs

Fix warning (as error):
> src\winforms\src\System.Windows.Forms.Design\tests\UnitTests\System\Windows\Forms\Design\ToolStripContentPanelDesignerTests.cs(43,67): error CS8620: (NETCORE_ENGINEERING_TELEMETRY=Build) Argument of type 'string[]' cannot be used for parameter 'span' of type 'Span<string?>' in 'bool MemoryExtensions.Contains<string?>(Span<string?> span, string? value)' due to differences in the nullability of reference types.
This is to unblock https://github.com/dotnet/sdk/pull/44843. I have tested with `10.0.100-alpha.1.24562.4` in global.json, this is the only instance of the error.

Fix nullability error CS8620 in tests

---

src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Printing/PrintPreviewControlTests.cs

Fixes #12441
- 
- change back color and fore color
- 
- 
- manually accessibility insights
-

fix 12441 [Accessibility] HC themes: The color contrast is less than 4.5:1 for the text "Document does not contain any pages" in printPreviewControl

---

src/System.Drawing.Common/src/System/Drawing/Imaging/ImageCodecInfo.cs
src/System.Private.Windows.Core/src/Windows/Win32/Graphics/GdiPlus/GdiPlusInitialization.cs

One place slipped through the cracks. If you call GetImageEncoders before any other System.Drawing code you will get a fatal error.
(Port from #12501)

Ensure GDI+ is initialized for all codepaths

---

src/System.Windows.Forms.Design/src/AssemblyInfo.cs
src/System.Windows.Forms.Design/src/AssemblyRef.cs
src/System.Windows.Forms.Design/tests/UnitTests/ControlDesignerTests.cs
src/System.Windows.Forms.Design/tests/UnitTests/TestControlDesigner.Mocks.cs
src/System.Windows.Forms.Design/tests/UnitTests/TestControlDesigner.cs

Related #10773
- Adds coverage for `ControlDesigner`.
- Introduces the `CreateMockSiteWithDesignerHost()` helper function, as the original (`MockSite.CreateMockSiteWithDesignerHost()`) was configured with `MockBehavior.Strict`, which conflicted with the requirements of `ControlDesigner.GetGlyphs()`.
- None
- No
- Minimal
- Unit tests
- 9.0.100-rc.2.24474.12

Adds coverage to ControlDesigner

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyGridView.GridViewTextBox.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyGridView.cs

Fixes #12440
- When setting a property with the [RefreshProperties(RefreshProperties.All)] attribute, suppress recalculation and reset constants for the entire property page
- The rectangle in the edit text box always stays in the edit textbox when changing the property value using the up/down buttons 
- No
- Mininal
The rectangle always back to focus on entire row after using the up/down changed the property values directly in the edit textbox
The rectangle in the edit text box always stays in the edit textbox when changing the property value using the up/down buttons 
- Manually
- .net 10.0.0-alpha.1.24554.9

Fixed the issue where edit textBox loses focus when using up/down to switch property values ​​on edit textBox

---

pkg/Microsoft.Private.Winforms/sdk/dotnet-windowsdesktop/System.Windows.Forms.FileClassification.props

WPF now depends on it as well, need to mark it so it is included in WPF references.

Mark System.Private.Windows.Core as WPF as well

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellStyleConverterTests.cs

Add unit tests for DataGridViewCellStyleConverter.cs to test its  methods

Add code coverage for  DataGridViewCellStyleConverter

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/TextBoxBaseDesignerTests.cs

1. Add unit test TextBoxBaseDesignerTests.cs for public properties and method of the TextBoxBaseDesigner.
2. Enable nullability in TextBoxBaseDesignerTests.cs.

Add unit test for TextBoxBaseDesigner

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ToolStripActionListTests.cs

- Add unit test ToolStripActionListTests.cs for public properties and method of the ToolStripActionList.
- Enable nullability in ToolStripActionList.

Add unit tests for ToolStripActionList

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ListControlStringCollectionEditorTests.cs

- Add unit test ListControlStringCollectionEditorTests.cs for public properties and method of the ListControlStringCollectionEditor
- Enable nullability in ListControlStringCollectionEditorTests.cs

Add unit tests for ListControlStringCollectionEditor

---

src/Common/tests/TestUtilities/TheoryDataExtensions.cs
src/System.Private.Windows.Core/tests/BinaryFormatTests/FormatTests/FormattedObject/BinaryFormatWriterTests.cs

Declared string[] as an Array in order to avoid confusion as to what  the `object` is  - a single string or an array of strings in IEnumerable<object[]>
VS tests fail intermittently with "The test method expected 1 parameter, but received 2"

Replaced string[] with Array as the T in TheoryData 

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewLinkColumnTests.cs

Add unit tests for DataGridViewLinkColumn.cs to test its properties & methods & events

Add code coverage for DataGridViewLinkColumn

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripItemCollection.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemCollectionTests.cs

Fixes https://github.com/dotnet/winforms/issues/12495 and https://github.com/dotnet/winforms/issues/4454
- Early return for empty collection
- Converts the ToolStripItemCollection into a temporary array (using ToArray()) to avoid modifying the original collection during iteration. This ensures that items can be safely added to the new collection without causing exceptions or unintended behavior, especially when items are removed from the original collection if they have a different owner control.
- Add unit test for issue https://github.com/dotnet/winforms/issues/12495 case
- Yes 
- Test fixing for GH issues: 12495 and 4454 manually 
- Unit test

Fix issue 12495: Infinite loop in ToolStripItemCollection.AddRange

---

src/System.Drawing.Common/src/System/Drawing/Graphics.cs
src/System.Drawing.Common/tests/System/Drawing/GraphicsTests.cs

Fixes https://github.com/dotnet/winforms/issues/12538
- Remove the recursive call between` IsVisible(int, int)` and `IsVisible(Point)`. Directly convert `int `to `float` in `IsVisible(int x, int y)` and call `IsVisible(float x, float y)` API.
- Add unit test to verify that all overloads of the `IsVisible` method return the same result for both points and rectangles.
- Yes
**Before:** cannot run app with exception
**After:** run app successfully
- Test fixing for GH issue: https://github.com/dotnet/winforms/issues/12538 manually
- Unit test

Fix issue 12538: Infinite loop in System.Drawing.Graphics between IsVisible(Point) and IsVisible(int, int)

---

src/System.Windows.Forms/src/System/Windows/Forms/Printing/PrintPreviewControl.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Printing/PrintPreviewControlTests.cs

Backport of #12368 and #12448 to release/9.0
BUG: https://github.com/dotnet/winforms/issues/12365, https://github.com/dotnet/winforms/issues/12441
When `PrintPreviewControl` has no document to show, it shows a text message to that effect.  This message has low color contrast ratio, making it hard to read. Text to background ratio is 2.3:1 or 3.9:1 in high contrast mode instead of the required 4.5:1 (https://www.w3.org/WAI/WCAG21/Understanding/contrast-minimum.html)
Accessibility requirement violation.
no
* manual, using Accessibility insights. Testing covered Dark mode and all HC modes on both Windows11 and windows10
* test team ran migrated automation cases 
low, these colors are not under user control, they wouldn't interfere with user changes.

[release/9.0] Informational text in PrintPreviewControl has low contrast in basic and HightContrast themes.

---

src/System.Windows.Forms/src/System/Windows/Forms/ToolStripItemCollection.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemCollectionTests.cs

BackPort of https://github.com/dotnet/winforms/pull/12513 to release/8.0
Bugs: https://github.com/dotnet/winforms/issues/12495, https://github.com/dotnet/winforms/issues/4454.
/cc @Tanya-Solyanik @Olina-Zhang
- Yes, from .NET 6.0
- There is an infinite loop to call ToolStripItemCollection.AddRange(ToolStripItemCollection toolStripItems) with items when they have same owner.
- Changes now: converts the ToolStripItemCollection into a temporary array (using ToArray()) to avoid modifying the original collection during iteration. This ensures that items can be safely added to the new collection without causing exceptions or unintended behavior, especially when items are removed from the original collection if they have a different owner control.
- Low
- Manual scenario testing and unit test
- …

[release/8.0] Fix issue 12495: Infinite loop in ToolStripItemCollection.AddRange

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripItemCollection.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripItemCollectionTests.cs

BackPort of https://github.com/dotnet/winforms/pull/12513 to release/9.0
Bugs: https://github.com/dotnet/winforms/issues/12495, https://github.com/dotnet/winforms/issues/4454.
/cc @Tanya-Solyanik @Olina-Zhang
From NET6.0
There is an infinite loop to call ToolStripItemCollection.AddRange(ToolStripItemCollection toolStripItems) with items when they have same owner.
Changes now: converts the ToolStripItemCollection into a temporary array (using ToArray()) to avoid modifying the original collection during iteration. This ensures that items can be safely added to the new collection without causing exceptions or unintended behavior, especially when items are removed from the original collection if they have a different owner control.
Low
Manual scenario testing and unit test
Regression tests

[release/9.0] Fix issue 12495: Infinite loop in ToolStripItemCollection.AddRange

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DesignerVerbToolStripMenuItemTests.cs

- Add unit test DesignerVerbToolStripMenuItemTests.cs for public properties and method of the DesignerVerbToolStripMenuItem.
- Enable nullability in DesignerVerbToolStripMenuItem.

Add unit tests for DesignerVerbToolStripMenuItem

---

src/System.Windows.Forms/src/System/Windows/Forms/ToolTip/ToolTip.cs

Fixes #12556
- Updates the `Reposition()` method in the `ToolTip` class to correctly handle cases where the tooltip extends beyond the left boundary of the screen, ensuring it is fully visible and not truncated.
The tooltip will be fully visible regardless of how close it is to the left border of the screen.
- No
- Minimal
- Manual
SDK: 9.0.100

ToolTip Appears Partially Off-Screen on Left Border

---

src/Common/tests/TestUtilities/System.Private.Windows.Core.TestUtilities.csproj
src/Microsoft.VisualBasic/tests/IntegrationTests/VisualBasicRuntimeTest/VisualBasicRuntimeTest.csproj
src/System.Windows.Forms.Primitives/tests/TestUtilities/System.Windows.Forms.Primitives.TestUtilities.csproj
src/System.Windows.Forms/tests/AccessibilityTests/Accessibility_Core_App.csproj
src/System.Windows.Forms/tests/AxHosts/AxHosts.csproj
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/DemoConsole.csproj
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DesignSurfaceExt/DesignSurfaceExt.csproj
src/System.Windows.Forms/tests/IntegrationTests/NativeHost.ManagedControl/NativeHost.ManagedControl.csproj
src/System.Windows.Forms/tests/IntegrationTests/ScratchProject/ScratchProject.csproj
src/System.Windows.Forms/tests/IntegrationTests/ScratchProjectWithInternals/ScratchProjectWithInternals.csproj
src/System.Windows.Forms/tests/IntegrationTests/System.Windows.Forms.IntegrationTests.Common/System.Windows.Forms.IntegrationTests.Common.csproj
src/System.Windows.Forms/tests/IntegrationTests/TrimTest/TrimTest.csproj
src/System.Windows.Forms/tests/IntegrationTests/TrimTestBinaryDeserialization/TrimTestBinaryDeserialization.csproj
src/System.Windows.Forms/tests/IntegrationTests/VisualBasicTemplate/VbWinForms.vbproj
src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/WinformsControlsTest.csproj
src/System.Windows.Forms/tests/TestUtilities/System.Windows.Forms.TestUtilities.csproj

I noticed that these get built in the normal product build that shouldn't build tests.

Annotate test utility projects so that they don't get built inside the VMR

---

src/System.Windows.Forms/tests/UnitTests/LinkLabelTests.cs

- Add unit tests for LinkLabel to test its FlatStyle, LinkArea, LinkBehavior, TabStop, Padding, VisitedLinkColor, UseCompatibleTextRendering properties and TabStopChanged, LinkClicked events

Add unit tests for LinkLabel

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/MaskedTextBoxDesignerActionListTests.cs

1. Add unit test MaskedTextBoxDesignerActionListTests.cs for public properties and method of the MaskedTextBoxDesignerActionList.
2. Enable nullability in MaskedTextBoxDesignerActionListTests.cs.

Add unit test for MaskedTextBoxDesignerActionList

---

pkg/Microsoft.Private.Winforms/README.md
pkg/Microsoft.Private.Winforms/sdk/dotnet-windowsdesktop/System.Windows.Forms.FileClassification.props
pkg/Microsoft.Private.Winforms/sdk/dotnet-windowsdesktop/UpdateFileClassification.ps1

Related: https://github.com/dotnet/windowsdesktop/issues/4796
This change includes file classification that is needed for the runtime pack in windowsdesktop in our FileClassification.props to avoid maintaining this list in the windowsdesktop repo. These dlls come from winforms so they should be maintained here and simply pulled into windowsdesktop [like how we are already doing for the ref pack](https://github.com/dotnet/windowsdesktop/blob/main/src/windowsdesktop/src/sfx/Microsoft.WindowsDesktop.App.Ref.sfxproj#L25). The list is currently being maintained https://github.com/dotnet/windowsdesktop/blob/main/src/windowsdesktop/src/sfx/Microsoft.WindowsDesktop.App.Runtime.sfxproj#L22-L39

Add File Classification for runtime pack

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/MaskDesignerDialogTests.cs

1. Add unit test MaskDesignerDialogTests.cs for public properties and method of the MaskDesignerDialog.
2. Enable nullability in MaskDesignerDialogTests..cs.

Add unit test for MaskDesignerDialog

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyGridView.cs

Fixes #12434
After changing the value by pressing up/down keyboard directly in EditTextbox, the `EditTextBox.HookMouseDown` will be set to True
The stack trace:
```
at System.Windows.Forms.PropertyGridInternal.PropertyGridView.GridViewTextBox.set_HookMouseDown(Boolean value)
at System.Windows.Forms.PropertyGridInternal.PropertyGridView.SetCommitError(ErrorState error, Boolean capture)
at System.Windows.Forms.PropertyGridInternal.PropertyGridView.OnEditChange(Object sender, EventArgs e)
at System.Windows.Forms.Control.OnTextChanged(EventArgs e)
at System.Windows.Forms.TextBoxBase.OnTextChanged(EventArgs e)
at System.Windows.Forms.Control.set_Text(String value)
at System.Windows.Forms.TextBoxBase.set_Text(String value)
at System.Windows.Forms.TextBox.set_Text(String value)
at …
```

Unhook the mouse down hook at the end of PropertyGridView.ProcessEnumUpAndDown

---

src/System.Private.Windows.Core/src/Windows/Win32/Foundation/HRESULT.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.NativeToWinFormsAdapter.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.WinFormsToNativeAdapter.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataObjectTests.cs

1. Ensure that HGLOBAL is freed when a serialization exception is thrown when flushing data to the clipboard. Before the change we were always allocating it but freeing only when an HR failure was returned.
2. Ensure that we don't attempt deserialization if we couldn't serialize data from the inproc scenario

Ensure memory is freed on a serialization failure in the cipboard

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewComboBoxCell.ObjectCollectionTests.cs

related #10453
Add unit tests for  DataGridViewComboBoxCell.ObjectCollection.cs to test its properties & methods

Add code coverage for DataGridViewComboBoxCell.ObjectCollection

---

src/Common/tests/TestUtilities/GlobalUsings.cs
src/Common/tests/TestUtilities/ModuleInitializer.cs
src/Common/tests/TestUtilities/NoAssertContext.cs
src/Common/tests/TestUtilities/ThrowingTraceListener.cs
src/System.Windows.Forms.Primitives/tests/TestUtilities/GlobalUsings.cs

This will allow it to be used in WPF as well.

Move NoAssertContext to Core test utilities

---

src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.NativeToWinFormsAdapter.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataObjectTests.cs

Fixed the autoConvert default values in DataObject.TryGetData  to match default values from DataObject.GetData

Fixed the autoConvert default values in DataObject.TryGetData

---

src/System.Windows.Forms/src/System/Windows/Forms/Internal/TypeExtensions.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.BinaryFormatUtilities.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.NativeToWinFormsAdapter.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/BinaryFormatUtilitiesTests.cs

Factored out code that reads formats that allow only restricted deserialization to run, such as OLE formats.

Minor refactoring in DataObject-related code

---

src/System.Drawing.Common/src/System/Drawing/Printing/PrintController.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerHost.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/InheritanceService.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomDesignerLoader.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CollectionCodeDomSerializer.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourceCodeDomSerializer.SerializationResourceManager.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlCodeDomSerializer.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ImageCollectionCodeDomSerializer.cs
src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
src/System.Windows.Forms.Primitives/tests/TestUtilities/Metafiles/RecordTypes/ENHMETAHEADER.cs
src/System.Windows.Forms/src/System/Windows/Forms/Application.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListBoxes/CheckedListBox.CheckedItemCollection.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGrid.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/TextBox/MaskedTextBox.cs
src/System.Windows.Forms/src/System/Windows/Forms/Form.cs
src/System.Windows.Forms/src/System/Windows/Forms/MDI/MDIControlStrip.cs
src/System.Windows.Forms/src/System/Windows/Forms/NotifyIcon.NotifyIconNativeWindow.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.Binder.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.NativeToWinFormsAdapter.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/IDataObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/ITypedDataObject.cs
src/System.Windows.Forms/src/System/Windows/Forms/WinCategoryAttribute.cs

I ran this regex on all projects, and hanges only xml doc comments. Remaining double spaces are in .resx files and in build warning that will be eventually visible to the users.

replaced end of sentence dot followed by 2 spaces with a dot with a single space

---

src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/AxHost.cs

Fixes #12551
- -  The `DetachWindow` method always sets `Handle` and `HWND` value to NULL. This make code inside if block go in recursive infinite loop. To fix this, we now store the value of `Handle` in a variable before calling the `DetachWindow` method. This was the previous behavior but got disrupted due to [this change](https://github.com/dotnet/winforms/commit/834d0a0d364c82bf70803706886ff9a40bd3e090#diff-dc17cf8f6ef4b80a13b2386597a72cd7ae36cab7375583a0a1e76a62f7f9238fL3556).
I had already [completed a PR](https://github.com/dotnet/winforms/pull/12564) which stored `IsHandleCreated` before calling `DetachWindow` method but missed to store and use `Handle` value.
Go through [this comment](https://github.com/dotnet/winforms/issues/12551#issuecomment-2545971442) to reproduce this …

Fix WM_DESTROY message handling

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellConverterTests.cs

Add unit tests for DataGridViewCellConverter.cs to test its methods

Add code coverage for DataGridViewCellConverter

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyGridView.GridViewTextBox.cs

Fixes #12565
- Add MSAA event to method OnGotFocus of the Control.cs
- NVDA tool can show focus blue rectangle in property edit textbox
- Yes
- Minimal
NVDA does not show focus blue rectangle.
https://github.com/user-attachments/assets/a147db27-d749-4819-840f-d11e26e5aa45
NVDA should show focus blue rectangle.
- Manually
- .net 10.0.0-beta.24613.2

Add MSAA event to method OnGotFocus of the Control.cs

---

src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.BinaryFormatUtilities.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.Composition.NativeToWinFormsAdapter.cs
src/System.Windows.Forms/tests/ComDisabledTests/ClipboardComTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs

restore behavior of
1. app with BinaryFormatter enabled SetData("custom format", new List<Point>(){})
2. app with BInaryFormatter disabled GetData("custom format")
NET8 and NET9 were returning an empty memory stream, I regressed it to throw the NotSupportedException from the spot where we detect that BinaryFormatter is disabled. After this change I retain the NotSupportedException only in the Typed Get APIs

Fix for a regression in how GetData APIs swallow all exceptions.

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.ClipboardTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ControlTests.Methods.cs

- Move the Control.DragDrop tests under ControlTests.Methods.cs to Collection "Sequential"

Move the Control.DragDrop tests under ControlTests.Methods.cs to Collection "Sequential"

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewComboBoxCell.ObjectCollectionTests.cs

Fixes #12612
Related #12613
- A `[WinFormsFact]` annotation was missing from a unit test in PR #12613, causing the test not to execute as part of the suite.
- Add the missing `[WinFormsFact]` annotation to the relevant unit test.
- Ensures the test runs as intended, increasing coverage and preventing regressions in the modified `DataGridViewComboBoxCell.ObjectCollection` class.
- No
- Minimal
- Unit tests
- 10.0.100-alpha.1.24573.1

Add the missing "WinFormsFact" annotation to the relevant unit test.

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ControlDesigner.TransparentBehaviorTests.cs

- Add unit test ControlDesigner.TransparentBehaviorTests.cs for public properties and method of the ControlDesigner.TransparentBehavior.
- Enable nullability in ControlDesigner.TransparentBehaviorTests.cs.

Add unit tests for ControlDesigner.TransparentBehavior

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/AccessibleObjects/DataGridViewTopLeftHeaderCellAccessibleObjectTests.cs

- Add unit tests for DataGridViewTopLeftHeaderCellAccessibleObject to test its DefaultAction, Name properties, State and DoDefaultAction, Navigate events
- Enable nullability in DataGridViewTopLeftHeaderCellAccessibleObjectTests.cs. 
- Update to use the `TheoryData<>` pattern for theory tests

Add unit tests for DataGridViewTopLeftHeaderCellAccessibleObject

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DataGridViewAddColumnDialogTests.cs

1. Add unit test DataGridViewAddColumnDialogTests.cs for public properties and method of the DataGridViewAddColumnDialog.
2. Enable nullability in DataGridViewAddColumnDialogTests.cs.

Write unit test for DataGridViewAddColumnDialog

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/LinkUtilitiesTests.cs

- Add unit tests for LinkUtilities to test its  GetIELinkBehavior and EnsureLinkFonts methods.

Add unit tests for LinkUtilities

---

src/System.Windows.Forms/src/PublicAPI.Unshipped.txt
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/StatusStrip.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/StatusStripTests.cs

Fixes #12616
This is due to #11502. We changed the default RenderMode of StatusStrip from System to ManagerRenderMode.
- Revert the changes on PR [11502](https://github.com/dotnet/winforms/pull/11502), the corresponding issue [11450 ](https://github.com/dotnet/winforms/issues/11450) was fixed when issue [12083 ](https://github.com/dotnet/winforms/issues/12083) was fixed, so the changes in PR [11502](https://github.com/dotnet/winforms/pull/11502) are no longer needed.
- When upgrading a project with StatusStrip from .net8.0 to .net9.0, there will no longer be extra white lines in the Form
- Yes 
- Minimal
A white line in the dialog when using StatusStrip
No extra white line the dialog
The color contrast between the focus indicator and toolStripSplitButton1 is still sufficient
- Manually
- …

Get rid of an unexpected white line above the status strip due to a changed 

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/TreeView/TreeView.cs

Fixes #12680 
The default indent is 19, but we didn't scale it properly in HDPI mode.
- 
- scale indent properly in HDPI mode.
- 
- 
- manually 
-

fix issue 12680 [HDPI]The dot line disappeared between checkbox and Expand/collapse in HDPI mode

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripHighContrastRenderer.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolstripProfessionalRenderer.cs

Fixes #12663 
dot color is not contrasting enough compared to the background color.
- 
- Change the color to a more contrasting color compared to the background color.
- 
- No
- low
**HC Aquatic**
**HC Desert** 
**HC Dusk**
**HC Night Sky**
- 
- manual, 
-

fix #12663 [Accessibility][High Contrast] ToolStrip grip icon colour contrast is less than 4.5:1 in Normal Mode and HC Desert mode

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ControlDesigner.ControlDesignerAccessibleObjectTests.cs
src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ControlDesignerAccessibleObjectTests.cs

- Add unit test ControlDesigner.ControlDesignerAccessibleObjectTests.cs for public properties and method of the ControlDesigner.ControlDesignerAccessibleObject.
- Enable nullability in ControlDesigner.ControlDesignerAccessibleObjectTests.cs.

Add unit tests for ControlDesigner.ControlDesignerAccessibleObject

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripPanel.ToolStripPanelControlCollection.XYComparerTests.cs

Add unit tests for ToolStripPanelControlCollectionXYComparer.cs to test its methods

Add code coverage for ToolStripPanelControlCollection_XYComparer

---

eng/pipelines/build-PR.yml
eng/pipelines/build.yml

Infrastructure change only. This change updates MicroBuild version to get CI build passing for release/8.0 as it currently fails due to out of date MicroBuild version
Same change was done to main in https://github.com/dotnet/winforms/pull/12666

[release/8.0] Update MicroBuild to v4

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/StatusStrip.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripHighContrastRenderer.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripSystemRenderer.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolstripProfessionalRenderer.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/StatusStripTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripButtonTests.Rendering.cs

Back port pr #12646 and #12092 to release9.0
Fixes #12616
In NET9 to fix accessibility color contrast issue #11450  (the contrast between the focus color and the background color of the `ToolStripSplitButton` in the `StatusStrip` control is less than 3:1), the rendering mode of the `StatusStrip` control was changed in PR #12045. But this fix caused the issue #12616: unexpected white lines appearing in the StatusStrip component when the dialog background is dark.
We had redone the fix for color contrast issue #11450 in NET10 (PR #12092)，by changing Pen to a more contrasting one in `ToolStripSystemRenderer`, `ToolStripHighContrastRenderer` and `ToolstripProfessionalRenderer`, so that the `ToolStripSplitButton` can achieve sufficient contrast regardless of the High Contrast theme or when it …

[release/9.0] Get rid of an unexpected white line above the status strip due to a changed renderer

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/TabControl/TabControl.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs

Fixes https://github.com/dotnet/winforms/issues/12661
- Update the WmSelChange method in TabControl.cs to check if the AccessibilityObject is null before calling the method
- Add a unit test to verify the fix
- Throw exception in Application.Run()
- No
- Minimal
Throw exception in Application.Run()
No exception in runtime
- Manually
- Unit test
- 10.0.0-alpha.1.24622.1

Fix #12661 Null Reference Exception: System.Windows.Forms.TabControl.<WmSelChange>

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewTextBoxColumnTests.cs

- Add unit tests for DataGridViewTextBoxColumn to test its Constructor, CellTemplate, MaxInputLength, SortMode properties and ToString() method
- Enable nullability in DataGridViewTextBoxColumnTests.cs

Add unit tests for DataGridViewTextBoxColumn

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/LinkAreaEditorTests.cs

1. Add unit test LinkAreaEditorTests.cs for public properties and method of the LinkAreaEditor.
2. Enable nullability in LinkAreaEditorTests.cs.

Add unit test for LinkAreaEditor

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStrip.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripItemCollection.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ToolStripTests.cs

Fix #12591.
This revert #4808 fix commit from #11358 PR.
The clean up of `DisplayedItems` after removal **has already been implemented** in `DoLayoutIfHandleCreated` but only if handle is created:
https://github.com/dotnet/winforms/blob/034543a7f08086c5ce29d85beaafcae70c3a33a5/src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStrip.cs#L3218-L3224
https://github.com/dotnet/winforms/blob/034543a7f08086c5ce29d85beaafcae70c3a33a5/src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStrip.cs#L3244-L3247
So we have leak only if handle is destroyed (#4808 case) and we didn't take this into account :(
All are much more complicated than [originally intended](https://github.com/dotnet/winforms/issues/4808#issuecomment-1849319594). And lead to some side …

Revert #4808 fix. Due to #12591 and investigations.

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewRowHeightInfoPushedEventArgsTests.cs

Add unit tests for DataGridViewRowHeightInfoPushedEventArgs.cs to test its properties

Add code coverage for DataGridViewRowHeightInfoPushedEventArgs

---

src/System.Windows.Forms/src/System/Windows/Forms/AxHost.cs

BackPort PR #12564 And #12648 To 8.0
Fixes https://github.com/dotnet/winforms/issues/12551
Parent container control is not sending WM_DESTROY message to the child control while disposing the ActiveX child controls. ActixeX child expects a WM_DESTORY message, but the message handler is never called. 
Yes. Due to  [Move from IntPtr to nint to avoid runtime casting errors. (#5791) · dotnet/winforms@834d0a0](https://github.com/dotnet/winforms/commit/834d0a0d364c82bf70803706886ff9a40bd3e090#diff-dc17cf8f6ef4b80a13b2386597a72cd7ae36cab7375583a0a1e76a62f7f9238fL3556), We accidentally removed caching of a window handle before destroying it, once the handle was destroyed, we were not able to forward message to its winproc. 
Manual testing with the user-provided project
Low - The change reverts …

[release/8.0] Fix WM_DESTROY message handling in ActiveX control

---

src/Microsoft.VisualBasic.Forms/src/Resources/Microsoft/VisualBasic/MyServices/Internal/ProgressDialog.resx
src/System.Windows.Forms/tests/AccessibilityTests/Menu_Toolbars_controls.resx

Fixes #12686
- Missing information in resource files prevents them from loading.
- Fill missing information in resource files so they can be loaded correctly.
- None
- No
- Minimal
- Manual
- `10.0.100-alpha.1.24573.1`

Fill missing information in resource files so they can be loaded correctly

---

src/System.Windows.Forms/src/System/Windows/Forms/TabControl.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TabControlTests.cs

Backport of #12683 to release/8.0
Fixes https://github.com/dotnet/winforms/issues/12661
A customer reported a crash in their application that uses WinForms TabControl and requested a fix in NET8 release. Application is running under accessibility tools and is removing TabPages from a control dynamically. When the selected page is removed, the selection moves to the next page and the corresponding accessibility event is queued using BeginInvoke to be raised. If by the time the event is raised, the page is removed, a NullReferenceException is thrown. No workaround is available.
Test if the selected page is still available before raising the accessibility event inside the BeginInvoke delegate.
Manual with the customer repro case and unit tests.
Low - this is an additional validation only.

[release/8.0] Fix #12661 Null Reference Exception: System.Windows.Forms.TabControl<WmSelChange>

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.FlatComboAdapter.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapter.cs

Fixes #12590
In order to fix the flickering issue#[2053861](https://devdiv.visualstudio.com/DevDiv/_workitems/edit/2053861), I modified the drawing logic of ComboBox in https://github.com/dotnet/winforms/pull/11529, this leads to the current issue and issue #11760.
- Revert the changes on PR #11529 and PR #11761
- ComboBox dropdown button can be shown normally when switching RightToLeft property, or recreating the combobox for any other reason.
- Yes 
- Minimal
When change the **RightToLeft** property **after expanding** the **Popup FlatStyle** comboBox, the dropdown button on the comboBox disappeared
The dropdown button on the comboBox can be show normally
- Manually
- .net 10.0.0-alpha.1.24605.1

Revert changes in PR11529 and PR11761

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewCell.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellTests.cs

Fixes #12692
- This issue is caused by PR #10406，which removes the check whether the control is null before executing `OnMouseUp` in file [DataGridViewCell.cs](https://github.com/dotnet/winforms/pull/10406/files#diff-2f4ea4bfa98a3298b78d36d7385f3100955c9fd85ee1254dfb802929029c5ce0R3098:~:text=%7D-,if%20(DataGridView%20is%20not%20null%20%26%26%20e.ColumnIndex%20%3C,%26%26%20e.RowIndex%20%3C%20DataGridView.Rows.Count),-Comment)
That fix moved the null check for the parent property grid to the top of the method. However, the parent can be set to null when this cell (or a row containing it) is deleted. In the user's case the row is deleted when the DGV cell is clicked.
- Add a check if `DataGridView is not null` before executing `OnMouseUp` in function `OnMouseUpInternal`, because the Parent …

Add a null-check for "DataGridView" property before executing OnMouseUp  in function OnMouseUpInternal

---

src/System.Drawing.Common/src/System/Drawing/Printing/PrinterSettings.StringCollection.cs
src/System.Private.Windows.Core/src/System/Collections/Generic/CollectionExtensions.cs
src/System.Private.Windows.GdiPlus/System/Drawing/IIcon.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.CollectionEditorCollectionForm.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/DesignerHost.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/CodeDomComponentSerializationService.CodeDomSerializationStore.ComponentListCodeDomSerializer.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/SelectionManager.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/TableLayoutPanelBehavior.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/ToolStripPanelSelectionBehavior.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/CommandSet.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/FlowLayoutPanelDesigner .cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/OleDragDropHandler.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/TableLayoutPanelDesigner.cs
src/System.Windows.Forms/src/System/Windows/Forms/ActiveX/AxHost.AxPropertyDescriptor.cs
src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/COM2PropertyDescriptor.cs
src/System.Windows.Forms/src/System/Windows/Forms/ComponentModel/COM2Interop/ICom2ExtendedBrowsingHandler.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStrip.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripDropDown.cs
src/System.Windows.Forms/src/System/Windows/Forms/Dialogs/TaskDialog/TaskDialogPage.cs

Using the latest daily build of the .NET 10 SDK to build this repo causes various code analysis build errors for IDE0040, IDE0057, IDE0305, and IDE0306. Fixing those here. These were found as part of the work in https://github.com/dotnet/sdk/pull/45749.

Fix code analysis issues

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/LinkAreaEditor.LinkAreaUITests.cs

- Add unit test LinkAreaEditor.LinkAreaUITests.cs for public properties and method of the LinkAreaEditor.LinkAreaUI.
- Enable nullability in LinkAreaEditor.LinkAreaUITests.cs.

Add unit tests for LinkAreaEditor.LinkAreaUI

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewCellTests.cs

Remove unused variable from test DataGridViewCell_OnContentClick_ClearAndReAddCell_InvokeOnMouseUpInternal

Removing unused variable from test DataGridViewCell_OnContentClick_ClearAndReAddCell_InvokeOnMouseUpInternal

---

src/System.Private.Windows.Core/src/Windows/Win32/System/Com/ComHelpers.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
src/System.Windows.Forms/tests/ComDisabledTests/ClipboardComTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataObjectTests.cs

Fixes https://github.com/dotnet/winforms/issues/12665
In .NET 9, we had switched to leveraging cswin32 and ComWrappers for our OLE interop. During this we discovered that switching from built-in COM to ComWrappers took away the ability to automatically cast native pointers back to their original managed object when round tripping through native code. In order to remedy this, we updated to wrap the data on clipboard set and unwrap the object retrieved from the clipboard manually before returning it to get the original data. 
While doing this, we had missed the fact that the native IDataObject interface doesn't have the concept of explicit autoConvert. Meaning that when calling our Clipboard APIs with autoConvert = false, it will effectively be ignored and produce same results as …

Only Unwrap If Given IDataObject

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/UserControlDocumentDesignerTests.cs

- Add unit test UserControlDocumentDesignerTests.cs for public properties and method of the UserControlDocumentDesigner.UserControlDocumentDesigner.
- Enable nullability in UserControlDocumentDesignerTests.cs.

add unit test for UserControlDocumentDesigner

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs

Related: https://github.com/dotnet/winforms/pull/12738#discussion_r1909558485
Clipboard.Clear was added to some Clipboard tests to help with flakyness in https://github.com/dotnet/winforms/pull/11527. At the time it was unclear why we were experiencing increased flaky Clipboard tests locally, but in https://github.com/dotnet/winforms/pull/12738 moved test that was added in JSON PR that was accessing Clipboard without being under same collection as other clipboard tests. Since this is now under same collection Clipboard.Clear should not be necessary so removing.

Remove Clipboard.Clear From Some Tests

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ImageCollectionCodeDomSerializerTests.cs

- Add unit test ImageCollectionCodeDomSerializerTests.cs for public Deserialize() method of the ImageCollectionCodeDomSerializer.
- Enable nullability in ImageCollectionCodeDomSerializerTests.cs.

Add unit test for ImageListCodeDomSerializer

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripItem.cs

Fixes #12589 
https://github.com/dotnet/winforms/blob/012e82d6d2627bb10b47d7048d5ef117c74ee02f/src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStrip.cs#L4489-L4518
ToolStrip.UpdateToolTip can be used to show or hide the `ToolTip` of `ToolStrip`.
But we didn't update tooltip when Enter key is hit on ToolStripItem.
Update ToolTip when Enter key is hit on ToolStripItem
Keyboard tooltip of toolStripDropDown item keeps displaying when tab to other control:
https://github.com/user-attachments/assets/a8b70e73-11c5-42c9-8063-59e5d1be4051
https://github.com/user-attachments/assets/f56efa61-5f6f-4503-bea8-08503291dc89
Manually

fix issue #12589 Keyboard tooltip of toolStripDropDown item keeps displaying when tab to other control

---

src/System.Private.Windows.Core/src/Windows/Win32/System/Com/ComHelpers.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
src/System.Windows.Forms/tests/ComDisabledTests/ClipboardComTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs

Backport of https://github.com/dotnet/winforms/pull/12738
When users set an object that is not an IDataObject onto our Clipboard using the SetDataObject API, calls to our clipboard APIs with `autoConvert = false` (either directly or indirectly) will no longer recognize equivalent clipboard formats as it had done in .NET 8, producing unintended behavior change.
This regressed because in .NET 9, we had switched to leveraging cswin32 and ComWrappers for our OLE interop. During this we discovered that switching from built-in COM to ComWrappers took away the ability to automatically cast native pointers back to their original managed object when round tripping through native code. In order to remedy this, we updated to wrap the data when setting it onto the clipboard and unwrap manually on …

[release/9.0] Only Unwrap If Given IDataObject

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewColumnConverterTests.cs

Add unit tests for DataGridViewColumnConverter.cs to test its methods

Add code coverage for DataGridViewColumnConverter

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ListControlUnboundActionListTests.cs

- Add unit test ListControlUnboundActionListTests.cs for public properties and methods of the ListControlUnboundActionList.
- Enable nullability in ListControlUnboundActionListTests.cs.

Add unit test for ListControlUnboundActionList

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataGridViewSortCompareEventArgsTests.cs

- Add unit tests for DataGridViewSortCompareEventArgs to test its Constructor initialization, SortResult property
- Enable nullability in DataGridViewSortCompareEventArgsTests.cs

Add unit tests for DataGridViewSortCompareEventArgs

---

src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataObjectTests.cs

When creating a DataObject from another DataObject we need to keep the original DataObject as the "inner" data so that virtuals get called as they historically have.
Also pass through to correct overload on TryGetDataCore.
Fixes #12789
(Note that #12789 is "fixed" by wrapping/unwrapping the original DataObject in #12738, but that doesn't fix the underlying problem.)

Don't unwrap wrapped DataObject inner data store

---

src/System.Windows.Forms.Primitives/src/System/LocalAppContextSwitches/LocalAppContextSwitches.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/TreeView/TreeView.cs

Fixes #12601
- Update the drawing position of the Treeview control text
- The check box of the TreeView control can be fully displayed
- No
- Minimal
Create a form, add a TreevView with CheckBoxes=true and DrawMode=OwnerDrawText
In OnDrawNode event only set DrawDefault=true
Show the form: checkboxes are shown corrupted on the right border
The checkbox of the Treeview control can be fully displayed
- Manually
- .net 10.0.0-alpha.1.24611.1

Add switch "MoveTreeViewTextLocOnePixel" for update the drawing position of the Treeview control text

---

src/System.Private.Windows.Core/src/System/Private/Windows/Core/Ole/IDataFormat.cs
src/System.Private.Windows.Core/src/System/Private/Windows/Core/Ole/TextDataFormat.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataFormats.Format.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataFormats.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/TextDataFormat.cs

Prepare DataFormats to move core implementation to share with WPF.
This splits the format list into two collections. The first is the known predefined format ids that come from Windows headers. The second collection contains ones that must be looked up. This optimizes allocations for typical user scenarios in WinForms and WPF.
An internal interface is used to abstract the Format class.
Next PR will move the shared logic into the shared assembly.

Refactor DataFormats

---

src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/DataObjectTests.cs

Ports #12800, do NOT squash
When creating a DataObject from another DataObject we need to keep the original DataObject as the "inner" data so that virtuals get called as they historically have.
Fixes #12789

Don't unwrap wrapped DataObject inner data store (#12800)

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/CommandSetTests.cs

- Add unit test CommandSetTests.cs for public method of the CommandSet.
- Enable nullability in CommandSetTests.

Add unit tests for CommandSet

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStrip.cs

fix #12777
- 
- add hiding ToolTip logic, When toolstrip loses focus, 
- 
- 
- now tooltip can disappear.
- 
https://github.com/user-attachments/assets/296542aa-5bc1-4ed4-b018-f19b28a33bcc
https://github.com/user-attachments/assets/bfc07993-6bab-49b4-aec0-c44033ec6fe7
- 
- manual
- 
10.0.0-alpha.1.25064.15

fix #12777 Keyboard tooltip of toolStripDropDownButton item still displaying when tab to other control

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/NotifyIconDesignerActionListTests.cs

- Add unit test NotifyIconDesignerActionListTests.cs for public properties and methods of the NotifyIconDesignerActionList.
- Enable nullability in NotifyIconDesignerActionListTests.cs.

Add unit test for NotifyIconActionList

---

Directory.Build.props

There is no need to do this when iterating inside VS.
Put in a conditional property group so we can easily add other settings that we may want to do for faster iteration when doing dev work.
Fixes #12817

Disable package validation while building inside Visual Studio

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DesignerFrameTests.cs

- Add unit test DesignerFrameTests.cs for public properties and method of the DesignerFrame
- Enable nullability in DesignerFrameTests.cs

Add unit tests for DesignerFrame

---

src/System.Windows.Forms/src/Resources/SR.resx
src/System.Windows.Forms/src/Resources/xlf/SR.cs.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.de.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.es.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.fr.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.it.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.ja.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.ko.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.pl.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.pt-BR.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.ru.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.tr.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hans.xlf
src/System.Windows.Forms/src/Resources/xlf/SR.zh-Hant.xlf
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewComboBoxCell.cs

Fixes #12810
- The original resource file used the term "field" instead of "property," which caused confusion in the context where we were searching for a property with a given name.
- Updated the resource string to replace "field" with "property" as suggested, ensuring it reflects the correct value.
- None
- No
- Minimal
- Manual
- `10.0.100-alpha.1.25064.3`

Fixes misleading error message

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.FlatComboAdapter.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ComboBox/ComboBox.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripComboBox.ToolStripComboBoxControl.ToolStripComboBoxFlatComboAdapter.cs

Backport #12737 to 9.0
Fixes #12744
Fixes #12590
- `ComboBox` drop down button disappears when switching RightToLeft property, or recreating the `ComboBox` for any other reason.
- `ComboBox` focus border is not shown when TAB-ing into ToolStripComboBoxItem
- Regression introduced by PRs #11529 and #11761, which modified how `ComboBox` controls was be drawn. It was an attempt to fix flickering of the control border when the mouse hovers over the control by reducing the number of times control is re-drawn, but we missed some cases where re-drawing was required. We don't have a better fix for the original flickering issue at the moment.
- Revert code from PRs #11529 and #11761, as that issue is less impactful than the new one we inadvertently introduced.
- Yes
- Minimal
- Manual
- 9.0.100

[release/9.0] WinForms ComboBox border and drop down button are not visible sometimes

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/FocusableLabelTests.cs

- Add unit tests for FocusableLabel.cs to test its methods

Add unit tests for FocusableLabel

---

src/System.Private.Windows.Core/tests/System.Private.Windows.Core.Tests/System/Private/Windows/Nrbf/CoreNrbfSerializerTests.cs
src/System.Private.Windows.Core/tests/System.Private.Windows.Core.Tests/System/Reflection/Metadata/TypeNameComparerTests.cs
src/System.Private.Windows.Core/tests/System.Private.Windows.Core.Tests/System/TypeExtensionsTests.cs

Move `TypeExtensionsTests` to Core test assembly. Add additional tests for other classes.
Will add more tests to `TypeExtensionsTests`- don't want to break history.

Move TypeExtensionsTests

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ToolStripMenuItemCodeDomSerializerTests.cs

- Add unit test ToolStripMenuItemCodeDomSerializerTests.cs for public method of the ToolStripMenuItemCodeDomSerializer.
- Enable nullability in ToolStripMenuItemCodeDomSerializerTests.

Add unit tests for ToolStripMenuItemCodeDomSerializer

---

src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/ArrayEditor.cs
src/System.Windows.Forms.Design/src/System/ComponentModel/Design/CollectionEditor.cs
src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/ArrayEditorTests.cs
src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/CollectionEditorTests.cs
src/System.Windows.Forms.Design/tests/UnitTests/System/ComponentModel/Design/CollectionFormTests.cs

- Enable nullability in ArrayEditor.

Enable nullability in ArrayEditor

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStrip.cs

Fixes #12818,#12819
- 
- when `ToolStrip` loses focus, remove all tooltips.
- 
- No
- low
https://github.com/user-attachments/assets/81d5b97d-b10e-4579-9690-c841e4768f83
https://github.com/user-attachments/assets/3314d249-9d70-43e9-a561-f792a3e293d1
https://github.com/user-attachments/assets/f9fe6f0e-86a4-4d90-a48c-4cf28b4da4b9
- 
- Manually 
- 
.Net 10.0.0-alpha.1.25072.13

Fix ToolStrip's ToolTip issues 

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewCheckBoxCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewRow.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewRowHeaderCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewTextBoxCell.cs

Fixes #12752
- The issue occurs because the `NotifyMSAAClient` method is called without checking if the `DataGridView` instance is `null`. This leads to a potential `NullReferenceException`.
- Add a `null` check for the `DataGridView` instance before calling the `NotifyMSAAClient` method.
- Prevents runtime crashes when the `DataGridView` is `null`.
- No
- Minimal
- `10.0.100-alpha.1.25064.3`

Fixes Exception being thrown when the space key is pressed on a CheckBoxCell

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/RadioButtonRendererTests.cs

Related #12935
- Add judgment to skip test `RadioButtonRenderer_DrawRadioButton_OverloadWithHandle` in x86

Disable test "RadioButtonRenderer_DrawRadioButton_OverloadWithHandle" in X86

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStripItem.cs
src/System.Windows.Forms/src/System/Windows/Forms/Dialogs/CommonDialogs/CommonDialog.cs
src/System.Windows.Forms/tests/IntegrationTests/UIIntegrationTests/OpenFileDialogTests.cs

Fixes https://github.com/dotnet/winforms/issues/12847
`ShowDialog` for `OpenFileDialog` waits while it populates the folders view, if at this moment we receive another `ShowDialog` call for the same dialog, we would attempt to subclass the same OpenFileDialog window again and start calling our own WinProc recursevely.
Fix: handle the repeated call to ShowDialog gracefully by returning "Cancel"

Fix for Double clicking on a ToolStripButton to open a dialog causes stack overflow

---

src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeNodeConverterTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/TreeViewImageIndexConverterTests.cs

- Add unit tests for TreeNodeConverter to test its ConvertTo method
- Add unit tests for TreeViewImageIndexConverter to test its GetStandardValues method

Add code coverage for TreeNodeConverter and TreeViewImageIndexConverter

---

src/System.Private.Windows.Core/src/System.Private.Windows.Core.csproj
src/System.Private.Windows.GdiPlus/System.Private.Windows.GdiPlus.csproj
src/System.Windows.Forms.Primitives/src/System.Windows.Forms.Primitives.csproj
src/System.Windows.Forms/src/System.Windows.Forms.csproj

Contributes to https://github.com/dotnet/sdk/pull/46829
NuGet added a new feature that automatically prunes package and project references that are provided by the shared framework that is targeted.
Resolve the warnings that got emitted when building the repository in non-source-only mode.

React to NuGet package pruning warnings

---

src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/WinformsControlsTest.csproj

Chart control in the winforms interactive test requires the SQL Client dependency at runtime. We are getting 4.9.0 version, which is the latest by default.
Fixes https://github.com/dotnet/winforms/issues/12940

Chart control requires the SQLClient at runtime

---

src/System.Private.Windows.Core/src/System/Private/Windows/JsonData.cs
src/System.Private.Windows.Core/src/System/Private/Windows/Nrbf/INrbfSerializer.cs
src/System.Private.Windows.Core/src/System/Private/Windows/Nrbf/SerializationRecordExtensions.cs
src/System.Private.Windows.Core/src/System/Private/Windows/Ole/BinaryFormatUtilities.cs
src/System.Private.Windows.Core/src/System/Private/Windows/Ole/DataObjectCore.cs
src/System.Private.Windows.Core/src/System/Private/Windows/Ole/TypeBinder.cs
src/System.Private.Windows.Core/tests/System.Private.Windows.Core.Tests/System/Private/Windows/Ole/BinaryFormatUtilitesTestsBase.cs
src/System.Private.Windows.Core/tests/System.Private.Windows.Core.Tests/System/Private/Windows/Ole/BinaryFormatUtilitiesTests.cs
src/System.Private.Windows.Core/tests/System.Private.Windows.Core.Tests/System/Private/Windows/Ole/TypeBinderTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/NativeToWinFormsAdapterTests.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/Ole/BinaryFormatUtilitiesTests.cs

This change refines deserialization binding behavior for the BinaryFormatUtilites class.
- Untyped requests must be requesting the object type (as the outer APIs all do)
- Removes delegate in TypeBinder
- TypeBinder returns typeof(object) for untyped requests
- TypeBinder does not fall back to implicit INrbfSerializer binding when missing a resolver
- Move JsonSerializer serialization to static interface
- Reorder TryGetObjectFromJson to fail out appropriately when binding the root type
- Reset the stream position in TryReadObjectFromStream
- Create the binder up front in TryReadObjectFromStream to normalize usage
- Don't allow implicit nullable conversion without an explicit binder
- Write a number of new tests
Plan is to continue to write tests with further test cleanup

Refine type binding for deserialization

---

src/System.Windows.Forms/src/System/Windows/Forms/PropertyStore.cs

The manual unboxing we were doing was not an ECMA approved use of the instruction. As such it could potentially fail in the future should the runtime decide to break the way we were using it.
One way to fix this would be to set each of the fields individually on the unboxed ref as the current two types we're optimizing are mutable. I've instead used `StrongBox<T>`. While significantly more complicated, it will not run afoul of the ECMA spec should we get an immutable type we want to handle.
If performance here ever ends up being a problem we could go the other way.
Fixes #12933

Avoid ECMA spec violation in PropertyStore

---

Directory.Packages.props
src/Common/tests/TestUtilities/System.Private.Windows.Core.TestUtilities.csproj
src/Microsoft.VisualBasic/src/Microsoft.VisualBasic.Facade.csproj
src/System.Windows.Forms.Primitives/tests/TestUtilities/System.Windows.Forms.Primitives.TestUtilities.csproj
src/System.Windows.Forms/tests/TestUtilities/System.Windows.Forms.TestUtilities.csproj

Replaces https://github.com/dotnet/winforms/pull/12960
Unsure why those weren't flagged in 9249b89d72852616b25660141f9d1a155c1aebd9 but this is the right thing to do.
Set PackageId for the facade project to avoid project prune warnings.

React to NuGet package pruning warnings (2)

---

src/System.Private.Windows.Core/src/Windows/Win32/System/Com/ComManagedStream.cs
src/System.Private.Windows.Core/tests/System.Private.Windows.Core.Tests/Windows/Win32/System/Com/ComManagedStreamTests.cs

Fixes #12951
- `ComManagedStream` will ensure that the stream wrapping a non-seekable source stream has a position of 0 at the end of its constructor.
- `Image.FromStream` with a non-seekable stream should no longer throw an exception when loading `.emf` and `.wmf` images.
- Yes
- Risk seems relatively low, in particular because this constructor created a stream with a position of 0 in .NET Framework and .NET Core 3.1. It seems unlikely that consumers are relying on a non-zero position.
- Added unit tests ensuring that the stream returned by `ComManagedStream.GetDataStream()` has the expected state.

Ensure `ComManagedStream` seekable wrapper stream has position of 0

---

eng/Localize/LocProject.json
src/System.Windows.Forms/tests/IntegrationTests/TrimTest/TrimTest.csproj
src/System.Windows.Forms/tests/UnsupportedTypes/UnsupportedTypes.csproj

Will check in as 2 separate commits
1 [Fixes](https://dnceng.visualstudio.com/internal/_build/results?buildId=2642760&view=logs&j=c2111129-d6a3-58de-e667-00e5a0966c99&t=dbb91d6b-a8a9-52a4-d165-489e1fa4c9b8) the localization step in the CI build
2. exclude a test project from the shipping code ([reference](https://github.com/dotnet/arcade/blob/d4adfaba4969147b67d364f47500c73a5de16def/Documentation/ArcadeSdk.md?plain=1#L959))

fix for the CI build

---

src/System.Private.Windows.Core/src/Windows/Win32/Graphics/Gdi/HBITMAP.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/WinFormsOleServices.cs

The same logic is used in WPF, factoring so it can be reused.

Move bitmap copy code to HBITMAP

---

src/System.Private.Windows.Core/src/System/Private/Windows/Ole/Composition.ManagedToNativeAdapter.cs
src/System.Private.Windows.Core/src/System/Private/Windows/Ole/Composition.NativeToManagedAdapter.cs
src/System.Private.Windows.Core/src/Windows/Win32/Foundation/GlobalBuffer.cs

Handle XAML data format.
For clarity, break helpers into three different text formats and add an HGLOBAL scope.

Handle XAML data format

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ToolStripCollectionEditorTests.cs

- Add unit test file: ToolStripCollectionEditorTests.cs for public methods of the ToolStripCollectionEditor.cs.
- Enable nullability in ToolStripCollectionEditorTests.cs.

Add code coverage for ToolStripCollectionEditor.cs file

---

src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/Program.cs

Start the interactive test in the classic mode, but this is a reminder to test this app in the dark mode as well.

make it easier to run the test app in the dark mode if needed

---

src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/CustomControls/CustomButton.cs
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/CustomControls/CustomButtonDesigner.cs
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/CustomControls/CustomButtonDesignerActionList.cs
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/CustomControls/DesignerActionVerbItem.cs
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/DemoConsole.csproj
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/GlobalUsings.cs
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.Designer.cs
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.MyScrollableControl.cs
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.MyUserControl.cs
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.cs
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/Program.cs
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DesignSurfaceExt/DesignSurfaceExt.cs
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DesignSurfaceExt/DesignSurfaceExt.csproj
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DesignSurfaceExt/DesignerOptionServiceExt.cs
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DesignSurfaceExt/DesignerSerializationServiceImpl.cs
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DesignSurfaceExt/GlobalUsings.cs
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DesignSurfaceExt/IDesignSurfaceExt.cs
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DesignSurfaceExt/NameCreationServiceImp.cs
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DesignSurfaceExt/PropertyGridExt.cs
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DesignSurfaceExt/TabOrderHooker.cs
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DesignSurfaceExt/TypeDiscoveryService.cs
src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DesignSurfaceExt/UndoEngineExt.cs

Related #12830
- Changes DemoConsole and DesignSurfaceExt projects to adopt implicit usings.
- None
- No
- Minimal
- 10.0.100-alpha.1.25077.2

Changes DemoConsole and DesignSurfaceExt projects to adopt implicit usings

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ToolStripCustomTypeDescriptorTests.cs

Add unit test file: ToolStripCustomTypeDescriptorTests.cs for public methods of the ToolStripCustomTypeDescriptor.cs.
Enable nullability in ToolStripCustomTypeDescriptorTests.cs.

Add code coverage for ToolStripCustomTypeDescriptor

---

src/System.Private.Windows.Core/src/Resources/SR.resx
src/System.Private.Windows.Core/src/System/Private/Windows/Ole/ClipboardCore.cs
src/System.Private.Windows.Core/src/System/Private/Windows/Ole/DataObjectExtensions.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs

Implementation is the same with WPF.
Add a null check for formatting the ArgumentException. Removal of resources from SWF will happen in a later audit.

Move SetFileDropList to ClipboardCore

---

src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs
src/System.Windows.Forms/tests/UnitTests/System/Windows/Forms/ClipboardTests.cs

Where we construct DataObject's directly or indirectly we should always throw for null data. This is to be more consistent with our APIs and also with WPF.
Simplify test names in ClipboardTests for easier navigation.

Consistently throw data on null data

---

azure-pipelines.yml
eng/pipelines/azure-pipelines-codeql.yml

update 1es-windows-2022 to windows.vs2022preview.amd64 in order to get a newer version of the VS on the CI machines
Tests
CI - https://dev.azure.com/dnceng/internal/_build/results?buildId=2650725&view=results
CodeQL - https://dev.azure.com/dnceng/internal/_build/results?buildId=2650655&view=results

Run CI build on a more up-to-date image

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/SelectionUIHandlerTests.cs
src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ToolStripCollectionEditorTests.cs

- Add unit test file: SelectionUIHandlerTests.cs for public methods of the SelectionUIHandler.cs.
- Enable nullability in SelectionUIHandlerTests.cs file.
- Simplified the ToolStripCollectionEditorTest.cs file by creating mock services directly

Add code coverage for SelectionUIHandler.cs file

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/TableLayoutPanelResizeGlyph.cs

- Enable nullability in TableLayoutPanelResizeGlyph.

Enable nullability in TableLayoutPanelResizeGlyph

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ControlCodeDomSerializer.cs
src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ControlCodeDomSerializerTests.cs

Add unit test file: ControlCodeDomSerializerTests.cs for public methods of the ControlCodeDomSerializer.cs.

Add code coverage for ControlCodeDomSerializer

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ToolStrips/ToolStrip.cs

Fixes #12916 
When we use Tab key to focus on second ToolStrip and then press down key, ProcessCmdKey method get triggered, but the event owner isn't right, it should have been toolStrip2 not toolStrip1.
- 
- Set Active ToolStrip when ToolStrip get  focused.
- 
- 
- manually 
-

fix #12916 Cannot use down to expand ToolStripDropDownButton in toolStrip2 after using right/Left to collapse ToolStripDropDownButton in toolStrip1

---

src/System.Private.Windows.Core/src/System/Private/Windows/Ole/ClipboardCore.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/WinFormsOleServices.cs

Adds a flush helper (this is a public API in WPF). Tweaks some code in WinFormsOleServices for better clarity and error state handling.
Also adds a helper to check if a given object is on the clipboard.

Add flush helper to ClipboardCore

---

src/System.Private.Windows.Core/src/System/Private/Windows/Ole/Composition.cs
src/System.Private.Windows.Core/src/System/Private/Windows/Ole/IDataObjectInternal.cs
src/System.Windows.Forms/src/PublicAPI.Shipped.txt
src/System.Windows.Forms/src/System/Windows/Forms/OLE/Clipboard.cs
src/System.Windows.Forms/src/System/Windows/Forms/OLE/DataObject.cs

The autoconvert argument doesn't make sense when setting data as JSON as the only place this has any impact is with a fixed set of predefined formats (text for example). You shouldn't be setting known formats with this method.
Also add a more extensive comment to `TryUnwrapUserDataObject`.

Remove autoconvert from SetDataAsJson

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/ListView/ListView.cs

We accidentally dropped the call to ColorTranslator, which properly handles alpha when converting COLORREF. COLORREF's implicit conversion does this correctly.
Fixes #13048

Retrieve color data correctly in ListView

---

src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.Designer.cs

- Resizes `DemoConsole` project's `MainForm` for convenience and to make everything visible in the surface designer.
- None
- No
- Minimal
- Manual
- 10.0.100-preview.3.25125.5

Resizes `DemoConsole` project's `MainForm` for convenience and to make everything visible in the surface designer

---

src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DesignSurfaceExt/PropertyGridExt.cs

- Sets `DesignerSerializationVisibility` to `Hidden` in `PropertyGridExt.DesignerHost`
- None
- No
- Minimal
- Manual
- 10.0.100-preview.3.25125.5

Related #12830.  Sets `DesignerSerializationVisibility` to `Hidden` in `PropertyGridExt.DesignerHost`

---

src/System.Windows.Forms/tests/IntegrationTests/DesignSurface/DemoConsole/MainForm.cs

Fixes #12987
- Added strings to `DropDownItems` instead of adding controls.
- Add proper working `ToolStripMenuItem` controls to `DropDownItems`.
- Interaction with `DemoConsole` fixed `DropDownItems` will be possible.
- No
- Minimal
- Manual
- 10.0.100-preview.3.25125.5

Add proper working `ToolStripMenuItem` controls to `DropDownItems`

---

docs/analyzers/Experimental.Help.md

I searched all files from the repo root and didn't find any references. It's also not documented.

We didn't use WFO5000 warning ID, removing it from internal docs

---

src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ErrorProviderTest.cs

Correct spelling of textbox in ErrorProviderTest.cs

---

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/ScaleHelper.cs
src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider/ErrorProvider.ErrorWindow.cs
src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider/ErrorProvider.IconRegion.cs
src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider/ErrorProvider.cs

Fixes #12939
- Scale errorProvider Icon to DeviceDPI
- The icon of errorProvider can be scaled well on HDPI screen
- Yes 
- Minimal
The icon of errorProvider is not scaled well on HDPI screen with SystemAware and PerMoniterV2 modes
The icon of errorProvider can be scaled well on HDPI screen
- Manually
- .net 10.0.0-preview.2.25111.15

Scale errorProvider Icon to DeviceDPI

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/OleDragDropHandlerTests.cs

- Add unit test file: OleDragDropHandlerTests.cs for public methods of the OleDragDropHandler.cs.

Add code coverage for OleDragDropHandler.cs file

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/TableLayoutPanelDesignerTests.cs

- Add unit test TableLayoutPanelDesignerTests.cs for some public properties and method of the TableLayoutPanelDesigner.

Add unit tests for TableLayoutPanelDesigner

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DataGridViewColumnTypePickerTests.cs

Add unit test file: DataGridViewColumnTypePicker.cs for public methods of the DataGridViewColumnTypePicker.cs

Add code coverage for DataGridViewColumnTypePicker

---

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/DpiHelper.cs
src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.ErrorWindow.cs
src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.IconRegion.cs
src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider.cs
src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ErrorProviderTest.Designer.cs
src/System.Windows.Forms/tests/IntegrationTests/WinformsControlsTest/ErrorProviderTest.cs

Back port pr #10850 and pr #12947 to release8.0
Fixes #12850 and #12939
The PR #8486 removed `new Icon(icon, 16 ,16)` from `IconRegion` constructor, that causes the released icon object to be directly referenced, so there is an exception `Cannot access a disposed object. Object name: 'Icon' `.
Backport #10850 fixes the above problem, but the PR always scaled `IconRegion` to 100% DPI, so it causes issue #12939: _The icon of errorProvider is not scaled well on HDPI screen_, so backport #12947 to scale the ErrorProvider's `IconRegion` according to the current device DPI.
- ErrorProvider exception when shown a second time after being dragged on another monitor with different DPI. This regression was reported by the customer.
- Yes, it's fine in dotnet 7. This is due to #8486
- Low - the fix …

[release/8.0] Fix 12850 error provider exception in different dpi

---

src/System.Windows.Forms.Primitives/src/System/Windows/Forms/Internals/ScaleHelper.cs
src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider/ErrorProvider.ErrorWindow.cs
src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider/ErrorProvider.IconRegion.cs
src/System.Windows.Forms/src/System/Windows/Forms/ErrorProvider/ErrorProvider.cs

BackPort PR https://github.com/dotnet/winforms/pull/12947 to 9.0
Fixes #12939
- Calculate the display size of the ErrorProvide Icon according to the DPI of the current device
- The icon of errorProvider is not scaled well on HDPI screen
- Yes.  it's fine in dotnet 8. This is due to https://github.com/dotnet/winforms/pull/10850, the initial loaded size of the ErrorProvider IconRegion is scaled to 100% DPI even on HDPI screens.
- Low – because the change only change ErrorProvider icon's display size when it run in HDPI screen.
- Manual testing with the user-provided project

[release/9.0] Scale errorProvider Icon to DeviceDPI 

---

src/System.Windows.Forms.Design/src/Resources/SR.resx
src/System.Windows.Forms.Design/src/Resources/xlf/SR.cs.xlf
src/System.Windows.Forms.Design/src/Resources/xlf/SR.de.xlf
src/System.Windows.Forms.Design/src/Resources/xlf/SR.es.xlf
src/System.Windows.Forms.Design/src/Resources/xlf/SR.fr.xlf
src/System.Windows.Forms.Design/src/Resources/xlf/SR.it.xlf
src/System.Windows.Forms.Design/src/Resources/xlf/SR.ja.xlf
src/System.Windows.Forms.Design/src/Resources/xlf/SR.ko.xlf
src/System.Windows.Forms.Design/src/Resources/xlf/SR.pl.xlf
src/System.Windows.Forms.Design/src/Resources/xlf/SR.pt-BR.xlf
src/System.Windows.Forms.Design/src/Resources/xlf/SR.ru.xlf
src/System.Windows.Forms.Design/src/Resources/xlf/SR.tr.xlf
src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hans.xlf
src/System.Windows.Forms.Design/src/Resources/xlf/SR.zh-Hant.xlf

Fixes #12983
- Extra dot at the end of resource string `Horizontal Splitter Orientation`
- Remove extra dot at the end of resource string `Horizontal Splitter Orientation`
- None
- No
- Minimal
- Manual
- 10.0.100-preview.3.25125.5

Remove extra dot at the end of resource string

---

src/System.Drawing.Common/src/System/Drawing/Internal/GPStream.cs

This is a manual port of #12953. The code was refactored in .NET 9 so the fix needs manually applied.

Set stream copy position to beginning

---

src/test/integration/WinformsControlsTest/ListBoxes.cs

Fixes #13047
- Add a logical judgment before invoking `listBox.Items[e.Index]` in `ListBox_DrawItem` method in `ListBoxes.cs` of the `WinformsControlsTest` application to prevent the exception
-  The click event can be done normally on ListBox
- No
- Minimal
Clicking on ListBox Drawmode.OwnerDrawFixed and ListBox Drawmode.OwnerDrawVariable brings up the exception error window in the WinformsControlsTest application
Everything work well on ListBox 
- Manually tested the application
- .net10.0.0-preview.3.25155.12

Test if listbox has any items before invoking listBox.Items[e.Index] in ListBoxes.cs of the WinformsControlsTests

---

src/test/unit/System.Windows.Forms/System/Windows/Forms/KeysConverterTests.cs
src/test/unit/System.Windows.Forms/System/Windows/Forms/ToolStripMenuItemTests.cs

Related #13117
- Skip following 3 localization test cases
1.  System.Windows.Forms.Tests.KeysConverterTests.ConvertFrom_ShouldConvertKeys_Localization
2.  System.Windows.Forms.Tests.ToolStripMenuItemTests.ToolStripMenuItem_SetShortcutKeys_ReturnExpectedShortcutText
3.  System.Windows.Forms.Tests.KeysConverterTests.ConvertToString_ShouldConvertKeys_Localization

Skip 3 localization tests

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DataGridViewColumnTypeEditorTests.cs

Add unit test file: DataGridViewColumnTypeEditor.cs for public methods of the DataGridViewColumnTypeEditor.cs

Add code coverage for DataGridViewColumnTypeEditor

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripCollectionEditor.ToolStripItemEditorForm.cs

Fixes #13040
- Update method `OnSelectedItemName_Paint`: When `selectedItem.Site` is null, only show selectedItem type in Items Collection Editor
-  The right type name can be show in the  Items Collection Editor
- No
- Minimal
The wrong type name show in the Items Collection Editor
The type name `ToolStripDropDownMenu` can be show correctly, and the item name is empty
- Manually
- .net 10.0.0-preview.3.25152.4

Update OnSelectedItemName_Paint: When selectedItem.Site is null, only show selectedItem type in Items Collection Editor

---

docs/analyzers/AppManifestAnalyzer.Help.md
docs/analyzers/ApplicationConfigurationGenerator.Help.md
docs/analyzers/WinFormsCSharpAnalyzers.Help.md
docs/analyzers/WinFormsVisualBasicAnalyzers.Help.md
docs/list-of-diagnostics.md
src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/ApplyApplicationDefaultsEventArgs.vb
src/Microsoft.VisualBasic.Forms/src/Microsoft/VisualBasic/ApplicationServices/WindowsFormsApplicationBase.vb
src/System.Windows.Forms.Analyzers.CSharp/src/AnalyzerReleases.Shipped.md
src/System.Windows.Forms.Analyzers.CSharp/src/System/Windows/Forms/CSharp/Analyzers/Diagnostics/CSharpDiagnosticDescriptors.cs
src/System.Windows.Forms.Analyzers.CSharp/tests/UnitTests/System.Windows.Forms.Analyzers.CSharp.Tests.csproj
src/System.Windows.Forms.Analyzers.VisualBasic/src/AnalyzerReleases.Shipped.md
src/System.Windows.Forms.Analyzers.VisualBasic/src/Diagnostic/VisualBasicDiagnosticDescriptors.vb
src/System.Windows.Forms.Analyzers/src/AnalyzerReleases.Shipped.md
src/System.Windows.Forms.Analyzers/src/System.Windows.Forms.Analyzers.csproj
src/System.Windows.Forms.Analyzers/src/System/Windows/Forms/Analyzers/Diagnostics/DiagnosticDescriptorHelper.cs
src/System.Windows.Forms.Analyzers/src/System/Windows/Forms/Analyzers/Diagnostics/DiagnosticIDs.cs
src/System.Windows.Forms.Analyzers/src/System/Windows/Forms/Analyzers/Diagnostics/SharedDiagnosticDescriptors.cs
src/System.Windows.Forms.Analyzers/tests/UnitTests/Analyzers/AppManifestAnalyzer/AppManifestAnalyzerTests.cs

Main change is the addition of DiagnosticDescriptorHelper.Create method that sets up the help link following the common pattern. I'm using the new aka.ms links in the documentation files.
Steps to create links and set them up with the diagnostic descriptors are in the list-of-diagnostics.md
We had a special "experimental" URL pattern used in VB with 2 APIs, I replaced it with the common one for the NET10, the old link still works for NET9
Potential follow up - combine ObsoletionIDs with DiagnosticIDs and move the resulting file to the Primitives assembly(to make it visible to VB) and Common folder(for Drawing)
Changes are logically grouped in commits, I plan to rebase-merge this PR.

ensured that help urls are set up for our analyzers

---

src/System.Windows.Forms/Resources/SR.resx
src/System.Windows.Forms/Resources/xlf/SR.cs.xlf
src/System.Windows.Forms/Resources/xlf/SR.de.xlf
src/System.Windows.Forms/Resources/xlf/SR.es.xlf
src/System.Windows.Forms/Resources/xlf/SR.fr.xlf
src/System.Windows.Forms/Resources/xlf/SR.it.xlf
src/System.Windows.Forms/Resources/xlf/SR.ja.xlf
src/System.Windows.Forms/Resources/xlf/SR.ko.xlf
src/System.Windows.Forms/Resources/xlf/SR.pl.xlf
src/System.Windows.Forms/Resources/xlf/SR.pt-BR.xlf
src/System.Windows.Forms/Resources/xlf/SR.ru.xlf
src/System.Windows.Forms/Resources/xlf/SR.tr.xlf
src/System.Windows.Forms/Resources/xlf/SR.zh-Hans.xlf
src/System.Windows.Forms/Resources/xlf/SR.zh-Hant.xlf
src/System.Windows.Forms/System/Windows/Forms/Controls/DataGridView/DataGridViewButtonCell.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/DataGridView/DataGridViewComboBoxCell.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/DataGridView/DataGridViewLinkCell.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/DataGridView/DataGridViewTextBoxCell.cs

- Correct the spelling of `DefaultDataGridViewButtonCellTollTipText`, `DefaultDataGridViewComboBoxCellTollTipText`, `DefaultDataGridViewLinkCellTollTipText`,  `DefaultDataGridViewTextBoxCellTollTipText` in the SR.resx file

Correct the spelling of DataGridViewCellToolTip in the resource file

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/StatusCommandUITests.cs

- Add unit test StatusCommandUITests.cs for public method of the StatusCommandUI.

Add unit tests for StatusCommandUI

---

src/Microsoft.VisualBasic.Forms/tests/UnitTests/Microsoft.VisualBasic.Forms.Tests.vbproj
src/System.Windows.Forms.Design/tests/UnitTests/System.Windows.Forms.Design.Tests.csproj
src/System.Windows.Forms/System/Windows/Forms/DataBinding/ControlBindingsCollection.cs
src/test/unit/System.Windows.Forms/System.Windows.Forms.Tests.csproj
src/test/unit/System.Windows.Forms/System/Windows/Forms/Design/DesignerAttributeTests.cs

This is an attempt to fix intermittent MSB3106 failures like this one that appeared after we removed project reference to the System.Drawing facade assembly from the System.Windows.Forms.Tests and Microsoft.VisualBasic.Forms.Tests projects.
https://dnceng.visualstudio.com/internal/_build/results?buildId=2660881&view=results
```
D:\a\_work\1\s\.dotnet\sdk\10.0.100-preview.3.25125.5\Microsoft.Common.CurrentVersion.targets(2424,5): error MSB3106: Assembly strong name "D:\a\_work\1\s\artifacts\bin\Microsoft.VisualBasic.Forms.Tests\..\System.Drawing.Facade\Release\net10.0\System.Drawing.dll" is either a path which could not be found or it is a full assembly name which is badly formed. If it is a full assembly name it may contain characters that need to be escaped with backslash(\). Those …
```

Ensure that System.Drawing facade assembly is built before the tests that consume it are.

---

src/System.Drawing.Common/src/System/Drawing/Imaging/EncoderParameter.cs

Part of the "remove unsafe" campaign. This call site was flagged by an experimental rule as being a good candidate for removing the `fixed` keyword and using standard array iteration. There's still obviously unsafe code in this method, but we're working in baby steps. :)
The experimental rule was looking only for low-hanging fruit and did not identify any other good candidates in this repo at this time.

Remove unnecessary 'fixed' statement

---

src/System.Private.Windows.Core/src/System.Private.Windows.Core.csproj

re-introduce https://github.com/dotnet/winforms/issues/12881 to support the VMR build which uses an older version of Roslyn is https://github.com/dotnet/sdk/pull/47167 is not fixed before Preview3.

Disable IDE0082 in the VMR build

---

src/System.Windows.Forms/Resources/xlf/SR.fr.xlf
src/test/unit/System.Windows.Forms/System/Windows/Forms/KeysConverterTests.cs
src/test/unit/System.Windows.Forms/System/Windows/Forms/ToolStripMenuItemTests.cs

Fixes #13117 
- Enable following localization tests since all resources are translated
-   System.Windows.Forms.Tests.KeysConverterTests.ConvertFrom_ShouldConvertKeys_Localization
-   System.Windows.Forms.Tests.ToolStripMenuItemTests.ToolStripMenuItem_SetShortcutKeys_ReturnExpectedShortcutText
-   System.Windows.Forms.Tests.KeysConverterTests.ConvertToString_ShouldConvertKeys_Localization
- Correct the translation for `(none)` in French from `(aucune)` to `(aucun)`

Enable localization testing since all resources are translated

---

src/test/unit/System.Windows.Forms/System/Windows/Forms/InputLanguageTests.cs

Fixed #10150
- Moved the OS condition to SupplementalInputLanguages_TestData of the test InputLanguage_FromCulture_SupplementalInputLanguages_Expected. 
In this way, the current OS version can be known by checking the number of running scenarios in the CI pipeline running results
Currently, this scenario is always in the pass state
- Keep this condition to avoid failures if someone runs the test on W11 21H2

Moving OS Condition to SupplementalInputLanguages_TestData for test InputLanguage_FromCulture_SupplementalInputLanguages_Expected

---

src/test/unit/interop/System.Windows.Forms.Interop.Tests.csproj

Fixes: https://github.com/dotnet/winforms/issues/13188
`System.Windows.Forms` interop tests depend on NativeTests project, which doesn't build in VMR.
This PR just conditions the test project to not build in VMR. Additional work would be needed to enable these tests in VMR. The remaining work is likely best suited for someone with domain knowledge.

Condition out the native tests in VMR

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ControlCommandSetTests.cs
src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DataGridViewColumnTypeEditorTests.cs

- Add unit test file: ControlCommandSetTests.cs for public methods and 2 protected methods of the ControlCommandSet.cs.

Add code coverage for ControlCommandSet.cs file

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/ContainerSelectorBehavior.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ControlDesigner.cs

- Enable nullability in ContainerSelectorBehavior.

Enable nullability in ContainerSelectorBehavior

---

src/test/unit/System.Windows.Forms/System/Windows/Forms/KeysConverterTests.LocalizationTests.cs
src/test/unit/System.Windows.Forms/System/Windows/Forms/KeysConverterTests.cs

Update test "ConvertFrom_ShouldConvertKeys_Localization" to use the SR resource name to retrieve the localized string

Update test "ConvertFrom_ShouldConvertKeys_Localization" to use the SR resource name to retrieve the localized string

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/TabOrderTests.cs

Add unit test file: TabOrderTests.cs for public methods & Properties of the TabOrder.cs

Add code coverage for TabOrder

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ToolStripMenuItemCodeDomSerializerTests.cs

Related #10773
Related #12883
- After the merging of #12883, there was a [request for some specific serialization test cases of the `ToolStripMenuItemCodeDomSerializer` class](https://github.com/dotnet/winforms/pull/12883#issuecomment-2644222449).
- Adds some specific serialization test cases for the `ToolStripMenuItemCodeDomSerializer` class.
- None
- Minimal
- Unit tests
- 10.0.100-preview.3.25167.3

Adds some specific serialization test cases for the `ToolStripMenuItemCodeDomSerializer` class

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/ToolboxItemSnapLineBehavior.cs

- Enable nullability in ToolboxItemSnapLineBehavior.

Enable nullability in ToolboxItemSnapLineBehavior

---

src/System.Private.Windows.Core/src/System.Private.Windows.Core.csproj
src/System.Windows.Forms/System.Windows.Forms.csproj

IDE0031 warnings were turned into errors in VMR build, with the latest SDK and compiler - https://github.com/dotnet/sdk/pull/48226
```
D:\a\_work\1\vmr\src\winforms\src\System.Private.Windows.Core\src\System\Private\Windows\Ole\FormatEnumerator.cs(59,13): error IDE0031: Null check can be simplified (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0031) [D:\a\_work\1\vmr\src\winforms\src\System.Private.Windows.Core\src\System.Private.Windows.Core.csproj::TargetFramework=net8.0]
D:\a\_work\1\vmr\src\winforms\src\System.Private.Windows.Core\src\System\Private\Windows\Ole\FormatEnumerator.cs(77,9): error IDE0031: Null check can be simplified (https://learn.microsoft.com/dotnet/fundamentals/code-analysis/style-rules/ide0031) …
```

Suppress IDE0031

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/StandardCommandToolStripMenuItemTests.cs

Add unit test file: StandardCommandToolStripMenuItemTests.cs for public methods of the StandardCommandToolStripMenuItem.cs

Add code coverage for StandardCommandToolStripMenuItem

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ParentControlDesignerTests.cs

- Add unit test ParentControlDesignerTests.cs for public properties and method of the ParentControlDesigner.

Add unit tests for ParentControlDesigner

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ToolStripEditorManagerTests.cs

Add unit test file: ToolStripEditorManagerTests.cs for public methods & Properties of the ToolStripEditorManager.cs
Original PR: https://github.com/dotnet/winforms/pull/13094

Add code coverage for ToolStripEditorManager

---

src/test/unit/System.Windows.Forms/System/Windows/Forms/InputLanguageTests.cs

Fixes #13226
- Disable validation of InputLanguage.LayoutName in non-English OS in test InputLanguage_FromCulture_SupplementalInputLanguages_Expected

Disable validation of InputLanguage.LayoutName in non-English modes in test InputLanguage_FromCulture_SupplementalInputLanguages_Expected 

---

src/System.Windows.Forms/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyGridView.cs
src/System.Windows.Forms/System/Windows/Forms/Input/KeysConverter.cs
src/test/unit/System.Windows.Forms/System/Windows/Forms/KeysConverterTests.cs
src/test/unit/System.Windows.Forms/System/Windows/Forms/PropertyGridInternal/PropertyGridView.DropDownHolderTests.cs
src/test/unit/System.Windows.Forms/System/Windows/Forms/PropertyGridTests.cs

ToolStripMenuItem.ShortcutKeys property type (Keys enum) has a TypeConverter that reports that it has a set of standard values. This is not entirely accurate. Keys type has a set of standard values, but the ShortcutKeys property does not, Shortcuts are combinations or keys and modifiers that follow certain rules, it's not practical to present all combinations for user to step through with up/down keys or with mouse wheel. We need to disable scrolling through potential values in the properyt grid.
This behavior regressed when we added Keys.None value to the list of standard values - #8401. This was done to localize "None" (as "(none)") in the property grid. We should keep this value in the type converted tables for localization purposes. But we should remove it from the list of standard …

Property grid entry for ShortCut keys should not be up/down scrollable

---

src/test/integration/DesignSurface/DesignSurfaceExt/DesignSurfaceExt.cs
src/test/integration/DesignSurface/DesignSurfaceExt/DesignerOptionServiceExt.cs

Fixes #13234
- In .NET Framework, the `ComponentDesigner.InitializeNewComponent` method calls `ShowUI` during component initialization if `ShouldAutoShow` returns true.
- In .NET (Core+), this issue doesn't occur because the `ShowUI` logic was removed when porting `ComponentDesigner` (see [PR #552](https://github.com/dotnet/winforms/pull/552)).
- Introduces a `DesignerOptionsBuilder` helper that explicitly sets `ObjectBoundSmartTagAutoShow = false`
- Adapts classes inheriting `DesignerOptionsService` to use this builder.
- None
- No
- Minimal
- Manual
- 10.0.100-preview.3.25167.3

Introduces a `DesignerOptionsBuilder` helper that explicitly sets `UseSmartTags = false`

---

src/System.Private.Windows.Core/src/System/Private/Windows/Ole/DataFormatNames.cs
src/System.Private.Windows.Core/src/System/Private/Windows/Ole/DataStore.cs
src/System.Private.Windows.Core/tests/System.Private.Windows.Core.Tests/System/Private/Windows/Ole/ClipboardCoreTests.cs
src/System.Windows.Forms/PublicAPI.Unshipped.txt
src/System.Windows.Forms/System/Windows/Forms/OLE/Clipboard.cs
src/System.Windows.Forms/System/Windows/Forms/OLE/WrappingDataObject.cs
src/test/unit/System.Windows.Forms/System/Windows/Forms/ClipboardTests.cs

When copy is not set to true, the original object is still available and we can get data directly without serializing through NRBF.
- Updated `DataFormatNames` for case-insensitive format lookups.
- Changed format equality checks in `DataStore` to be case-insensitive.
- Renamed a test method in `ClipboardCoreTests` for clarity and added a new test for `SerializableObject` to ensure it does not use `BinaryFormatter`.
- Introduced a generic `TryGetData<T>(out T data)` method in `Clipboard`.
- Modified `SetDataObject` to use `WrappingDataObject` for improved data wrapping.
- Enhanced `WrappingDataObject` to always consider `autoConvert` as true, aligning with native `IDataObject` behavior.
- Updated assertions in `ClipboardTests` for more flexible type checking.
- Added tests to verify the …

Avoid serialization with in-process Clipboard use

---

src/System.Windows.Forms.Design/src/PublicAPI.Shipped.txt
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/WindowsFormsDesignerOptionService.cs

- Enable nullability in WindowsFormsDesignerOptionService.

Enable nullability in WindowsFormsDesignerOptionService

---

src/test/unit/System.Windows.Forms/ResourceStrings.cs
src/test/unit/System.Windows.Forms/System/Windows/Forms/ClipboardTests.cs
src/test/unit/System.Windows.Forms/System/Windows/Forms/NativeToWinFormsAdapterTests.cs
src/test/util/System.Windows.Forms/Data/ManagedAndRuntimeDataObject.cs
src/test/util/System.Windows.Forms/Data/TypedDataObject.cs
src/test/util/System.Windows.Forms/Data/UntypedDataObject.cs

renamed a test input class,
added exception message verification
and did a minor code cleanup

 test code cleanup

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ListViewGroupCollectionEditorTests.cs

Related #10773
Add unit test file: ListViewGroupCollectionEditorTests.cs for public methods of the ListViewGroupCollectionEditor.cs

Add code coverage for ListViewGroupCollectionEditor

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/FlowLayoutPanelDesignerTests.cs

- Add unit test file: FlowLayoutPanelDesignerTests.cs for public method and 6 protected methods of the FlowLayoutPanelDesigner.cs.

Add code coverage for FlowLayoutPanelDesigner.cs file

---

src/System.Windows.Forms/System/Windows/Forms/DataBinding/BindingSource.cs
src/test/unit/System.Windows.Forms/System/Windows/Forms/BindingSourceTests.cs

Fixes #13061
- Using `StringComparison.InvariantCultureIgnoreCase` instead  `StringComparison.InvariantCulture`  in method `ParseSortString.
`
- Yes. Introduced in https://github.com/dotnet/winforms/pull/10172/files#diff-be7f960595c89e574536157bf61838085bce49d7e8c48a7f96a58e6764b6a533L994-R997
- Minimal
Debugging project, exception "Sort string contains a property that is not in the IBindingList"  throws out when setting `BindingSource.Sort = "Property desc`"(lower case `desc`)
The debugging result is normal
- Manually

Ignore case for DESC and ASC in BindingSource.Sort

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ToolStripInSituServiceTests.cs

Related #10773 #13021
- Adds coverage for the `ToolStripInSituService` class.
- Uses code from closed #13021
- None
- No
- Minimal
- Unit tests
- 10.0.100-preview.3.25167.3

Issue 10773 add coverage for ToolStripInSituService

---

src/System.Windows.Forms/System/Windows/Forms/Controls/ToolStrips/ToolStrip.cs

Fixes #12958
- This positions the `ToolTip` so that it is offset by 1px from the cursor's HotSpot X value.
- This prevents `ToolStrip` tooltips from appearing directly under cursor HotSpot. Thus, the user is able to click the `ToolStripItem`.
- No
-
- Manually tested.
-

Prevent Toolbar tooltips from appearing directly under cursor hotspot

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ToolStripContainerActionListTests.cs

- Add unit test ToolStripContainerActionListTests.cs for public properties and method of the ToolStripContainerActionList.

Add code coverage for ToolStripContainerActionList

---

src/test/unit/interop/NativeTests/CMakeLists.txt
src/test/unit/interop/System.Windows.Forms.Interop.Tests.csproj

Fixes https://github.com/dotnet/winforms/issues/13186
I chose min version that works with both the latest cmake (v4.0.1 requires min version 3.10)  and the version shipped in the public preview(v 3.30 requires min version 3.5).
This fixes error like this one
```
CMake Error at CMakeLists.txt:1 (cmake_minimum_required):
Compatibility with CMake < 3.5 has been removed from CMake.
Update the VERSION argument <min> value.  Or, use the <min>...<max> syntax
to tell CMake that the project requires at least <min> but has been updated
to work with policies introduced by <max> or earlier.
Or, add -DCMAKE_POLICY_VERSION_MINIMUM=3.5 to try configuring anyway.
```

Update the min cmake version to enable native code compilation with cmake shipped in VS public preview .

---

src/System.Windows.Forms/System/Windows/Forms/Controls/DataGridView/DataGridView.Methods.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/DataGridView/DataGridView.cs

Fixes #13304
Regression introduced in PR #4637
When closing the dialog in edit mode, `DataSource` is set to null, and then `CurrentCell = null` is set. Then unnecessary method `EndEdit` of the `SetCurrentCellAddressCore` is called.
- Add `_isReleasingDataSource` in DataGridView and set it to null in property `DataSource` before setting `CurrentCell = null` to prevent the `EndEdit` method of the SetCurrentCellAddressCore from being called
- When the DataGridView is in editing mode, its dialog box can be closed normally
- Yes 
- Minimal
When a dialog with a DataGridView that has focus is closed, an `System.InvalidOperationException: Operation is not valid because it results in a reentrant call to the SetCurrentCellAddressCore function.` is thrown …

Add _isReleasingDataSource to prevent unnecessary operations on CurrentCell when changing or releasing DataSource

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/BehaviorService.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/Behavior/DragAssistanceManager.cs

fix #13305
This issue is caused by [PR10279](https://github.com/dotnet/winforms/pull/10279)
These are two of all changes make in [PR10279](https://github.com/dotnet/winforms/pull/10279)
`BehaviorService`, `DragAssistanceManager` use `SnapLines` to add some effects during design time.
`ControlDesigner` has a **_virtual_** property `SnapLines`, but most designers override the property, in other words,  _**most designers have customized `SnapLines`**_
when `BehaviorService` or `DragAssistanceManager` accesses  `SnapLines` , customized `SnapLines` were returned.
ControlDesigner.cs
when `BehaviorService` or `DragAssistanceManager` **_accesses  `SnapLinesInternal`_** , **_customized `SnapLines` were skipped._**
- 
- Use `SnapLines`
- 
- 
- manually 
-

fix #13305  Baseline SnapLines do not appear in DesignSurface

---

src/test/integration/UIIntegrationTests/ListViewTests.cs

Related #13288, #13291
-  **Skip the following unstable ListView tests on Windows x86** 
1. System.Windows.Forms.UITests.ListViewTests.ListView_Tile_FragmentNavigate_ReturnsNullAsync(columnCount: 1, subItemsCount: 0, width: 150, height: 150, direction: 3)
2. System.Windows.Forms.UITests.ListViewTests.ListView_Tile_FragmentNavigate_WorksExpectedAsync(columnCount: 2, subItemsCount: 2, width: 150, height: 150, itemIndex: 0, subItemIndex: 1, direction: 3)
3. System.Windows.Forms.UITests.ListViewTests.ListView_Tile_GetChild_ReturnsExpected_For_BigSizeAsync
4. System.Windows.Forms.UITests.ListViewTests.ListView_Tile_GetChild_ReturnsExpectedAsync
5. System.Windows.Forms.UITests.ListViewTests.ListView_Tile_GetChild_ReturnsNullAsync(columnCount: 4, subItemsCount: 0, width: 150, height: 150)
6. …

Skip unstable ListView Tile tests and case ListView_Click_On_Second_Column_Does_Not_Alter_CheckBoxesAsync

---

.github/workflows/backport.yml

Fixes #13332
From the logs, the backport PR was not generated because the Ubuntu 20.04 LTS set in the [current workflow](https://github.com/dotnet/winforms/blob/698cfb403515150b08ca8cd1f201b5d0aacde813/.github/workflows/backport.yml#L14) was removed on 2025-04-15, and we need to set up a new runner
- Update the run-on setting to ubuntu-22.04 in .github/workflows/backport.yml

Update the run-on setting to ubuntu-22.04 in .github/workflows/backport.yml

---

src/System.Windows.Forms/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/GridEntry.GridEntryAccessibleObject.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyGridView.Flags.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyGridView.cs
src/test/unit/System.Windows.Forms/System/Windows/Forms/PropertyGridTests.cs

Fixes #13071 
- 
- revert [PR#12431](https://github.com/dotnet/winforms/pull/12431) , use another approach to fix [Issue#12440](https://github.com/dotnet/winforms/issues/12440)
- Introduce  `EditMouseDown` flag in PropertyGridView.flag. This flag is on when the TextBox in the PropertyGrid.GridEntry is focused and is off when editing is done.
- The cause of   [Issue#12440](https://github.com/dotnet/winforms/issues/12440) is that after editing is done, GridEntryAccessibleObject will raise AutomationFocusChangedEvent
GridEntry.GridEntryAccessibleObject.cs
``` c#
...
internal override void SetFocus()
{
if (PropertyGridView is null || !PropertyGridView.IsHandleCreated)
{
return;
}
base.SetFocus();
RaiseAutomationEvent(UIA_EVENT_ID.UIA_AutomationFocusChangedEventId);
}
```
So in order to not …

fix #13071 Changing properties with RefreshProperties.All does not requery the property list in the PropertyGrid in .net 9 (worked in .net 8) 

---

.gitignore
Winforms.sln
eng/Versions.props
src/test/integration/DesignSurface/DemoConsole/DemoConsole.csproj
src/test/integration/DesignSurface/DemoConsole/MainForm.Designer.cs
src/test/integration/DesignSurface/DemoConsole/MainForm.MyUserControl.cs
src/test/integration/DesignSurface/DemoConsole/MainForm.cs
src/test/integration/DesignSurface/DemoConsole/Properties/launchSettings.json
src/test/integration/DesignSurface/DemoConsole/README.md
src/test/integration/DesignSurface/DesignSurfaceExt/DesignSurfaceExt.cs
src/test/integration/DesignSurface/DesignSurfaceExt/DesignSurfaceExt.csproj
src/test/integration/DesignSurface/DesignSurfaceExt/NameCreationServiceImp.cs
src/test/integration/DesignSurface/Directory.Build.props
src/test/integration/DesignSurface/README.md

Fixes #12830
- Updated `DemoConsole.csproj` and `DesignSurfaceExt.csproj` to support multiple target frameworks (`$(NetCurrent)-windows;net481`).
- Adjusted `TargetFramework` property to avoid over-building.
- Enabled `SignAssembly` and `GenerateAssemblyInfo` properties in the project files.
- Updated resource and reference handling in `DemoConsole.csproj` and `DesignSurfaceExt.csproj` to improve compatibility.
- Fixed `Controls.AddRange` usage to use the correct syntax in `MainForm.MyUserControl.cs`.
- Corrected `Controls.AddRange` call in `MainForm.cs` to `Controls.Add`.
- Suppressed `IDE0057` warning and reverted to `Substring` method for compatibility in `NameCreationServiceImp.cs`.
- Changed `StartsWith('_')` check by directly accessing the first character in …

Issue 12830 multi target demo console

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DesignerUtilsTests.cs

Add unit test file: DesignerUtilsTests.cs for public methods & properties of the DesignerUtils.cs
**Note: working on another PR for the remaining test case**

Add code coverage for DesignerUtils

---

src/System.Windows.Forms/System/Windows/Forms/Controls/DataGridView/DataGridView.Methods.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/DataGridView/DataGridView.cs

Fixes #13304
- This is a supplemental fix to PR #13320
- Add judgment `IsHandleCreated` before invoking `EndEdit` to avoid the exception
- #### Microsoft Reviewers: [Open in CodeFlow](https://microsoft.github.io/open-pr/?codeflow=https://github.com/dotnet/winforms/pull/13362)

Moving tag OperationInReleasingDataSource to function "OnDataSourceDisposed"

---

src/System.Windows.Forms/System/Windows/Forms/Controls/ToolStrips/ToolStripItem.cs
src/test/unit/System.Windows.Forms/System/Windows/Forms/ToolStripButtonTests.cs

Fixes #13344 
[PR_7611](https://github.com/dotnet/winforms/pull/7611) fixed [Issue_7601](https://github.com/dotnet/winforms/issues/7601) that Narrator is reading ToolStripMenuitems even when they are disabled
- 
- Set `CanSelect` True,  when selected and disabled don't send acc event.
- 
ToolStrip, MenuStrip, StatusStrip
They all hehave the same
- 
- manually 
-
1.We can add a switch like `CanSelectWhenDisabled` to let users decide 
2.We can make disabled items selectable just like Winfows Desktop Context menu, but this could be breaking change.

fix #13344 Disabled ToolstripMenuItems are no longer highlighted

---

eng/Version.Details.xml
eng/Versions.props

Follow-up on https://github.com/dotnet/winforms/pull/13370
All of the removed dependencies and properties in this PR aren't necessary. They were needed previously for coherency but that isn't necessary anymore now that winforms flows directly into the VMR.

Clean-up dependencies after first VMR sync

---

src/System.Drawing.Common/src/System/Drawing/Printing/PageSettings.cs
src/System.Drawing.Common/tests/Helpers.cs
src/System.Drawing.Common/tests/System/Drawing/Printing/PageSettingsTests.cs
src/System.Drawing.Common/tests/System/Drawing/Printing/PrintDocumentTests.cs

This was inadvertently flipped when changing to CsWin32. Moves helper code for using the PDF printer to write a regression test.
There is no practical workaround for this. If you're looking for whether a printer supports color, however, you can check `PrinterSettings.SupportsColor` instead. 
Fixes #13367

Fix Color value in PageSettings

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/ToolStripTemplateNode.cs

Fixes #13286
- Add a null check before getting `SelectionService` and `BehaviorService` in ToolStripTemplateNode.cs
- ToolStripMenuItem can be added normally in DemoConsole project
- No
- Minimal
https://github.com/user-attachments/assets/4bff443e-cdc2-4bc9-9ca8-aee3f7660d39
- Manually
- .net 10.0.0-preview.4.25223.119

Fix 13286: Add a null check before getting SelectionService and BehaviorService

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewDesigner.DataGridViewChooseDataSourceActionList.cs
src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataGridViewDesigner.cs

Related #13231
- Missing structure for choosing data source designer action item.
- Move `DataGridViewChooseDataSourceActionList` into a separate file
- Add comment about missing structure for choosing data source designer action item.
- None
- No
- Minimal
- 10.0.100-preview.3.25201.16

Move `DataGridViewChooseDataSourceActionList` into a separate file

---

src/System.Windows.Forms/System/Windows/Forms/Controls/ListView/ListView.ListViewAccessibleObject.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/ListView/ListViewGroup.ListViewGroupAccessibleObject.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/ListView/ListViewGroup.cs
src/test/unit/System.Windows.Forms/System/Windows/Forms/AccessibleObjects/ListViewGroup.ListViewGroupAccessibleObjectTests.cs

This fix is based on this call stack, I'm eliminating the top frame by creating this Accessibility object only when the parent control is available.
```
System.InvalidOperationException: ListView
at System.Windows.Forms.ListViewGroup.ListViewGroupAccessibleObject..ctor(ListViewGroup owningGroup, Boolean owningGroupIsDefault)
at System.Windows.Forms.ListViewGroup.get_AccessibilityObject()
at System.Windows.Forms.ListView.OnGotFocus(EventArgs e)
```
This is a follow up on https://github.com/dotnet/winforms/pull/10910#issuecomment-1958261561
Related to https://github.com/dotnet/winforms/issues/4019
I couldn't reproduce the issue, but the call stack is clear enough to understand the problem. There are situations when AccessibilityObject is not available, for example when the corresponding …

Intermittent exception when creating a ListViewGroupAccessibleObject

---

src/System.Windows.Forms.Analyzers.CSharp/src/System/Windows/Forms/CSharp/Analyzers/MissingPropertySerializationConfiguration/MissingPropertySerializationConfigurationAnalyzer.cs
src/System.Windows.Forms.Analyzers.VisualBasic/src/Analyzers/MissingPropertySerializationConfiguration/MissingPropertySerializationConfigurationDiagnosticAnalyzer.vb

Fixes #13160.
We're servicing only the false-positive WinForms Analyzers edge cases for low-risk servicing.

[Release/9.0] Fix false-positive WinForms Analyzer diagnostics.

---

src/test/integration/DesignSurface/DemoConsole/GlobalUsings.cs
src/test/integration/DesignSurface/DemoConsole/MainForm.Designer.cs
src/test/integration/DesignSurface/DemoConsole/MainForm.cs
src/test/integration/DesignSurface/DesignSurfaceExt/DesignSurfaceExt.cs
src/test/integration/DesignSurface/DesignSurfaceExt/DesignerOptionServiceExt.cs
src/test/integration/DesignSurface/DesignSurfaceExt/DesignerSerializationServiceImpl.cs
src/test/integration/DesignSurface/DesignSurfaceExt/IDesignSurfaceExt.cs
src/test/integration/DesignSurface/DesignSurfaceExt/NameCreationServiceImp.cs
src/test/integration/DesignSurface/DesignSurfaceExt/PropertyGridExt.cs
src/test/integration/DesignSurface/DesignSurfaceExt/TabOrderHooker.cs
src/test/integration/DesignSurface/DesignSurfaceExt/UndoEngineExt.cs

Related #13388
- Unifies `DesignSurfaceExt` and `DemoConsole` namespaces under the latter.
- Renames class names where appropriate to reflect the shared project identity, in preparation for relocating all files into the `DemoConsole` folder in a follow-up PR.
- None
- No
- Minimal
- 10.0.100-preview.3.25201.16

Unify namespaces and class names under DemoConsole

---

Directory.Build.targets
eng/Version.Details.xml
eng/Versions.props
global.json

This avoids need for a workaround in VMR builds and reduces friction for stable builds. When building non-win-x64 verticals, we end up having to set the x64 runtime pack and x64 VS redist pack properties (stable and non-stable properties) based on other values in the VMR orchestrator. Instead, use MicrosoftNEtCoreAppRef as the stable version property, and MicrosoftNETCorePlatforms as the non-stable one.

Replace arch-specific package properties with arch neutral ones

---

NuGet.config
eng/Version.Details.xml
eng/Versions.props
global.json

Merging internal commits for release/8.0

---

docs/list-of-diagnostics.md
src/Common/tests/TestUtilities/AppContextSwitchNames.cs
src/System.Private.Windows.Core/src/NativeMethods.txt
src/System.Private.Windows.Core/src/System/Private/Windows/CoreAppContextSwitches.cs
src/System.Windows.Forms.Analyzers/src/System/Windows/Forms/Analyzers/Diagnostics/DiagnosticIDs.cs
src/System.Windows.Forms/PublicAPI.Unshipped.txt
src/System.Windows.Forms/System/Windows/Forms/OLE/DropTarget.cs
src/System.Windows.Forms/System/Windows/Forms/OLE/IAsyncDropTarget.cs

Chromium based apps don't support file drop without using `IDataObjectAsyncCapability`. This includes the new Outlook.
To support this, we'll look for this interface in our current code paths and utilize it. This makes the async operation sync, which works, but isn't ideal. Chromium will pop a dialog that will leave WinForms modal as well until it is responded to.
If this behavior creates an issue, it can be disabled with the AppContext switch: "Windows.DragDrop.DisableSyncOverAsync"
In order to truly support async we're also introducing a new interface to allow calling back off of the UI thread. This will be shipped as experimental for .NET 10 as there is a small risk we'll want to change the API based on real-world feedback. See #13422.

Allow IDataObjectAsyncCapability

---

src/System.Windows.Forms/PublicAPI.Shipped.txt
src/System.Windows.Forms/PublicAPI.Unshipped.txt

Publish unpublished APIs

---

src/System.Windows.Forms/System/Windows/Forms/OLE/DropTarget.cs

Fixes #13508 
code snippet before [PR13431](https://github.com/dotnet/winforms/pull/13431)
```
{
ClearDropDescription();
DragDropHelper.Drop(dragEvent);
}
_owner.OnDragDrop(dragEvent);
*pdwEffect = (DROPEFFECT)dragEvent.Effect;
}
else
{
*pdwEffect = DROPEFFECT.DROPEFFECT_NONE;
}
_lastEffect = DragDropEffects.None;
_lastDataObject = null;
return HRESULT.S_OK;
}
```
code snippet after [PR13431](https://github.com/dotnet/winforms/pull/13431)
```
private HRESULT HandleOnDragDrop(DragEventArgs e, IDataObjectAsyncCapability* asyncCapability, DROPEFFECT* pdwEffect)
{
#pragma warning disable WFO5003 // Type is for evaluation purposes only
if (asyncCapability is not null && _owner is IAsyncDropTarget asyncDropTarget)
#pragma warning restore WFO5003
{
// We have an implemented IAsyncDropTarget and …
```

fix #13508 Original text box is not empty after drag and drop the value to a new text box

---

src/System.Windows.Forms/System/Windows/Forms/Application.ThreadContext.cs

Switch to a concurrent backing collection. Note that we only ever create them if you ask for them on the current thread.

Handle ThreadContext cache more cleanly

---

src/System.Windows.Forms/System/Windows/Forms/OLE/DropTarget.cs

Fixes #13538
- Update method `Drop` to delete `*pdwEffect = DROPEFFECT.DROPEFFECT_NONE` before `CreateDragEventArgs` 
- The component controls can be moved in design time
- Yes
- Minimal
Unable move component controls in DemoConsole application.
https://github.com/user-attachments/assets/fb3397cc-15c7-4565-b42a-09866a6bd404
Component controls can be moved normally
- Manually
- .net 10.0.0-preview.6.25278.103

Fix 13538: Update method Drop of DropTarget.cs

---

src/System.Windows.Forms.Primitives/src/NativeMethods.txt
src/System.Windows.Forms/PublicAPI.Unshipped.txt
src/System.Windows.Forms/Resources/SR.resx
src/System.Windows.Forms/Resources/xlf/SR.cs.xlf
src/System.Windows.Forms/Resources/xlf/SR.de.xlf
src/System.Windows.Forms/Resources/xlf/SR.es.xlf
src/System.Windows.Forms/Resources/xlf/SR.fr.xlf
src/System.Windows.Forms/Resources/xlf/SR.it.xlf
src/System.Windows.Forms/Resources/xlf/SR.ja.xlf
src/System.Windows.Forms/Resources/xlf/SR.ko.xlf
src/System.Windows.Forms/Resources/xlf/SR.pl.xlf
src/System.Windows.Forms/Resources/xlf/SR.pt-BR.xlf
src/System.Windows.Forms/Resources/xlf/SR.ru.xlf
src/System.Windows.Forms/Resources/xlf/SR.tr.xlf
src/System.Windows.Forms/Resources/xlf/SR.zh-Hans.xlf
src/System.Windows.Forms/Resources/xlf/SR.zh-Hant.xlf
src/System.Windows.Forms/System/Windows/Forms/Form.cs
src/System.Windows.Forms/System/Windows/Forms/ScreenCaptureMode.cs
src/test/unit/System.Windows.Forms/System/Windows/Forms/FormTests.cs

Fixes #13258.
Fixes #13450.
Looks like this, when _recorded_:

Introduce FormScreenCaptureMode property on Form

---

src/test/integration/DesignSurface/DemoConsole/MainForm.cs
src/test/integration/DesignSurface/DesignSurfaceExt/DesignSurfaceExt.cs

related to #10466
- Add ↑, ↓, ←, →  shortcut
- Some minor code refactoring 
manually

related to issue 10466: add short cut ↑, ↓, ←, → to demo console

---

src/test/integration/DesignSurface/DemoConsole/MainForm.cs

Fixes #13539
There is a UserControl in the designer, which is big enough to cover the MenuStrip.
- 
- Make enough room for MenuStrip
- 
- 
- low
-
https://github.com/user-attachments/assets/af05626f-e340-48d1-ab4b-3ffeb2c4f475
- 
- manual 
-

fix #13539 Unable to select ToolStripMenuItem and TooStripTextBox of MenuStrip2 in DemoConsole application

---

src/test/unit/System.Windows.Forms/System/Windows/Forms/AccessibleObjects/UpDownBase.UpDownBaseAccessibleObjectTests.cs
src/test/unit/System.Windows.Forms/System/Windows/Forms/UpDownBase.UpDownBaseAccessibleObjectTests.cs

Related #13442
- Add unit test file: UpDownBase.UpDownBaseAccessibleObjectTests.cs for public methods of the UpDownBase.UpDownBaseAccessibleObject.cs.cs

Add code coverage for UpDownBase.UpDownBaseAccessibleObject

---

src/test/unit/System.Windows.Forms/System/Windows/Forms/GridEntryRecreateChildrenEventArgsTests.cs

- Add unit test file: GridEntryRecreateChildrenEventArgsTests.cs for GridEntryRecreateChildrenEventArgs.cs file.

Add unit test for GridEntryRecreateChildrenEventArgs.cs file

---

.github/copilot-instructions.md
.github/copilot/GDIPlus-copilot-instructions.md
Winforms.sln

This PR is adding a way more detailed instruction set according to our .editorConfig enforced coding-standards, and it helps with refactorings or code generation from Copilot to minimize manual work.
It also adds a set of rules for GDI/GDI+ based renderer instructions.
The latter does not get automatically involved. If you have a code file which you for example would like to review according to our standards, which are reflected by those instructions, prompt as an example something like this:
"Could you review the code file #MyNewGridViewRenderer.cs according to the GDI+ instructions in #GDIPlus-copilot-instructions.md"
**Important:** These instructions do NOT have any influence on how Copilot is reviewing PRs!
**Note:** If you wish the edit or expand on those instructions, please do not …

Update copilot instructions

---

src/test/integration/UIIntegrationTests/ListViewTests.cs

Related #11328, #13291
Adding this test to the new synchronized collection does not resolve the instability
-  **Skip the following unstable ListView tests** 
1. System.Windows.Forms.UITests.ListViewTests.ListView_Tile_FragmentNavigate_ReturnsNullAsync(columnCount: 1, subItemsCount: 0, width: 150, height: 150, direction: 3)
2. System.Windows.Forms.UITests.ListViewTests.ListView_Tile_FragmentNavigate_WorksExpectedAsync(columnCount: 2, subItemsCount: 2, width: 150, height: 150, itemIndex: 0, subItemIndex: 1, direction: 3)
3. System.Windows.Forms.UITests.ListViewTests.ListView_Tile_GetChild_ReturnsExpected_For_BigSizeAsync
4. System.Windows.Forms.UITests.ListViewTests.ListView_Tile_GetChild_ReturnsExpectedAsync
5. System.Windows.Forms.UITests.ListViewTests.ListView_Tile_GetChild_ReturnsNullAs …

Skip unstable ListView UI tests

---

src/test/unit/System.Windows.Forms/System/Windows/Forms/WebBrowserUriTypeConverterTests.cs

- Add unit test file: WebBrowserUriTypeConverterTests.cs for WebBrowserUriTypeConverter.cs file.

Add unit test for WebBrowserUriTypeConverter.cs file

---

src/test/integration/DesignSurface/DemoConsole/MainForm.cs
src/test/integration/DesignSurface/DesignSurfaceExt/DesignSurfaceExt.cs

Related to #10466   Support Tab key in the demo console
- 
- Add tab
- 
Not supported.

Related to #10466   Support Tab key in the demo console

---

src/test/integration/UIIntegrationTests/ListViewTests.cs

Fixes #13288
- Add Task.Delay for test ListView_Click_On_Second_Column_Does_Not_Alter_CheckBoxesAsync

Fix 13288 by add Task.Delay for test ListView_Click_On_Second_Column_Does_Not_Alter_CheckBoxesAsync

---

src/System.Windows.Forms.Design/src/System/ComponentModel/Design/Serialization/ResourceCodeDomSerializer.SerializationResourceManager.cs

Fixes #12595
This issue is caused by replacing `for (;;)` with `if (appendCount || _nameTable.TryGetValue(nameBase, out count))` in PR #8332, which leads to resource name conflicts.
- Add do...while loop in the SetValue method until resourceName is unique
- When serializing collection values, the resource numeric suffix can be incremented without duplication
- Yes 
- Minimal
Paste after the second time, the resource will end up using the same number 1 over and over
Resource suffixes are increasing
- Manually
- .net 10.0.0-preview.6.25304.106

Add do...while loop in the SetValue method of SerializationResourceManager.cs until resourceName is unique

---

src/System.Windows.Forms/System/Windows/Forms/Controls/TreeView/TreeView.cs

Fixes #13583
-  Update TreeView's `TvnEndLabelEdit` method to set label to null when no text has changed
- The edit state of TreeNode can be exited using the Enter key
- Yes 
- Minimal
Pressing the Enter key when a TreeNode enters the edit state will cause an exception
When a TreeNode enters the edit state, press the Enter key, the node will exit the edit state
- Manually
- .net 10.0.0-preview.6.25310.107

Update TreeView's TvnEndLabelEdit method to set label to null when no text has changed

---

src/test/unit/System.Windows.Forms/System/Windows/Forms/DomainItemAccessibleObjectTests.cs

Add unit test file: DomainItemAccessibleObject.cs for public methods of the DomainItemAccessibleObject.cs

Add code coverage for DomainItemAccessibleObjectTests

---

src/System.Private.Windows.Core/tests/System.Private.Windows.Core.Tests/System/Private/Windows/Ole/ClipboardCoreTests.cs

Related https://github.com/dotnet/winforms/issues/13331
Adding `GetData` tests and `SetAudio` tests to `ClipboardCoreTests`

Adding GetData test and SetAudio tests to ClipboardCoreTests

---

src/System.Windows.Forms.Design/tests/UnitTests/Mocks/MockSite.cs
src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/ChangeToolStripParentVerbTests.cs

Related #10773
- Adds code coverage for public members of `ChangeToolStripParentVerb`.
- None
- No
- Minimal
- Unit tests
- 10.0.100-preview.3.25201.16

Issue 10773 Adds code coverage for public members of `ChangeToolStripParentVerb`.

---

src/test/unit/System.Windows.Forms/System/Windows/Forms/PropertyGridInternal/GridToolTipTests.cs

- Add unit test file: GridToolTipTests.cs for GridToolTip.cs file.

Add unit test for GridToolTip.cs file

---

eng/Versions.props

Fixes #
- 
- 
- 
- 
- 
- Yes / No
-
- 
- 
- 
-

Cleanup for XUnitV3Version

---

src/test/integration/UIIntegrationTests/ListViewTests.cs

Related https://github.com/dotnet/winforms/issues/13288
- Add `InvokeAsync` before executing `listView.RectangleToScreen(listView.Items[0].SubItems[1].Bounds) `

Update ListView_Click_On_Second_Column_Does_Not_Alter_CheckBoxesAsync to add judgment and InvokeAsync

---

src/test/unit/System.Windows.Forms/System/Windows/Forms/DataGridViewImageColumnTests.cs

Add unit test file:DataGridViewImageColumnTests.cs for public methods of the DataGridViewImageColumn.cs

Add code coverage for DataGridViewImageColumn

---

src/System.Windows.Forms/System/Windows/Forms/Control.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/Buttons/Button.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/ListView/ListView.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/TextBox/TextBoxBase.cs

When a control wants to automatically participate in DarkMode handling, it does so by setting the `ControlStyles.ApplyThemingImplicitly` flag first thing in the overridden property `CreateParams`.
For custom control controls, which derive von other controls than controls, and which in addition have already opted in (like `ButtonBase`) in to auto-DarkMode handling, this PR makes it possible for a control to opt out in the same way.
To this end, the derived custom control _also_ needs to overwrite the `CreateParams` property, and then needs to clear the `ApplyThemingImplicitly` flag the first thing before calling the base implementation:
```csharp
// In CreateParams, do this first to opt an inherited control out of dark mode handling:
SetFlags(ControlStyles.ApplyThemingImplicitly, false); …
```

Extend DarkMode opt-out option for multiple descendant scenarios.

---

src/test/unit/System.Windows.Forms/System/Windows/Forms/DataGridViewButtonCellTests.cs

Add unit test file:DataGridViewButtonCellTest.cs for public/protected methods of the DataGridViewButtonCellcs

Add code coverage for DataGridViewButtonCell

---

src/test/unit/System.Windows.Forms/System/Windows/Forms/DataGridViewComboBoxCellTests.cs

Add unit test file:DataGridViewComboBoxCellTest.cs for public/protected methods of the DataGridViewComboBoxCell.cs

Add code coverage for DataGridViewComboBoxCell

---

src/System.Windows.Forms/src/System/Windows/Forms/DataGridViewLinkCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/LinkUtilities.cs

Backport of https://github.com/dotnet/winforms/pull/13681 to release/8.0
Fixes https://github.com/dotnet/winforms/issues/13677
- Modified the signature of the `EnsureLinkFonts ` method, removed the bool `isActive ` parameter, and adjusted the related conditional logic and updated the text rendering method of **LinkLabel** in the Active state, by moving the text 1 pixel to the right to achieve a bold effect.
- Allows users to correctly set the **LinkLabel** control to a bold font through `FontStyle.Bold` at runtime
- Yes， introduced in https://github.com/dotnet/winforms/pull/6250
- Low

[release/8.0] FontStyle.Bold Not Visually Applied to LinkLabel at Runtime via Code

---

src/System.Windows.Forms/src/System/Windows/Forms/Controls/DataGridView/DataGridViewLinkCell.cs
src/System.Windows.Forms/src/System/Windows/Forms/Controls/Labels/LinkUtilities.cs

Backport of https://github.com/dotnet/winforms/pull/13681 to release/9.0
Fixes https://github.com/dotnet/winforms/issues/13677
- Modified the signature of the `EnsureLinkFonts ` method, removed the bool `isActive ` parameter, and adjusted the related conditional logic and updated the text rendering method of **LinkLabel** in the Active state, by moving the text 1 pixel to the right to achieve a bold effect.
- Allows users to correctly set the **LinkLabel** control to a bold font through `FontStyle.Bold` at runtime
- Yes， introduced in https://github.com/dotnet/winforms/pull/6250
- Low

[release/9.0] FontStyle.Bold Not Visually Applied to LinkLabel at Runtime via Code

---

src/System.Windows.Forms/System/Windows/Forms/Form.cs

Fixes #13680
- Update `SetScreenCaptureModeInternal` by reset `WINDOW_DISPLAY_AFFINITY` to `NONE` before setting new affinity
- `FormScreenCaptureMode` still works properly after multiple calls
- Yes
- Minimal
When the FormScreenCaptureMode property is set twice in succession, ScreenCaptureMode always retains the first setting.
https://github.com/user-attachments/assets/1e37db66-9b7a-48cc-a7bf-f7f896cf440c
https://github.com/user-attachments/assets/16b61d36-0eb1-4022-a0cd-ec28b7b2d895
- Manually
- .net 10.0.0-preview.7.25320.118

Update SetScreenCaptureModeInternal by reset WINDOW_DISPLAY_AFFINITY to NONE before setting new affinity

---

src/test/unit/System.Windows.Forms/System/Windows/Forms/ToolStripProfessionalLowResolutionRendererTests.cs

Add unit test file: ToolStripProfessionalLowResolutionRendererTests.cs for ToolStripProfessionalLowResolutionRenderer.cs file

Add code coverage for ToolStripProfessionalLowResolutionRenderer

---

src/System.Windows.Forms/System/Windows/Forms/Form.cs
src/test/integration/UIIntegrationTests/FormTests.cs

Fixes #13698
In the original code, changing the MinimumSize of a form calls `SetWindowPos` with the flag `SWP_NOZORDER`. While this ensures that the Z-order of the forms is unchanged, it is not enough to prevent the affected forms from becoming active.
- In `UpdateMinimumSize` of Form.cs add `SET_WINDOW_POS_FLAGS.SWP_NOACTIVATE` so that the form is not automatically activated when the `MinimumSize` property changes
- Setting MinimumSize will not activate form
- No
- Minimal
https://github.com/user-attachments/assets/f2129ffc-bcfb-4bff-8026-77712122377e
https://github.com/user-attachments/assets/95d35f03-198a-4606-a66a-01089a08144f
- Manually 
- Unit test
- .net 10.0.0-preview.7.25365.101

Do not activate the form if MinimumSize changes

---

src/test/integration/UIIntegrationTests/ListViewTests.cs

Releated #13288 
- Add judgement for test ListView_Click_On_Second_Column_Does_Not_Alter_CheckBoxesAsync

Add judgement for test ListView_Click_On_Second_Column_Does_Not_Alter_CheckBoxesAsync

---

src/test/unit/System.Windows.Forms/System/Windows/Forms/MultiPropertyDescriptorGridEntryTests.cs

Add unit test file:MultiPropertyDescriptorGridEntryTests.cs for public/protected methods/properties of the MultiPropertyDescriptorGridEntry.cs

Add code coverage for MultiPropertyDescriptorGridEntry

---

src/System.Windows.Forms/PublicAPI.Unshipped.txt
src/System.Windows.Forms/System/Windows/Forms/Control.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/Buttons/Button.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/ComboBox/ComboBox.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/ListView/ListView.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/RichTextBox/RichTextBox.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/TextBox/TextBoxBase.cs

Fixes the `ComboBox` and `RichTextBox` BackColor issue in dark mode, where the background color was the same as in Classic mode (LightMode).
Note, that ComboBox internally uses depending on the ComboBox DropDownStyle different nested controls for different modes. So, practically there are inner ListBox and TextBox controls which had to be addressed:
Again: Tested by CTI and made sure, that the Classic mode CodePaths remain as they were.

DarkMode (b): Fix rendering of disabled TextBox types

---

src/System.Windows.Forms/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/DropDownButton.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/PropertyGridView.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/UpDown/UpDownBase.UpDownButtons.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/UpDown/UpDownBase.cs
src/System.Windows.Forms/System/Windows/Forms/Rendering/ControlPaint.ModernControlButton.cs
src/System.Windows.Forms/System/Windows/Forms/Rendering/ControlPaint.ModernControlButtonState.cs
src/System.Windows.Forms/System/Windows/Forms/Rendering/ControlPaint.cs
src/System.Windows.Forms/System/Windows/Forms/Rendering/ControlPaint_ModernControlButtonRenderer.cs

Fixes System Control Button rendering issues in dark mode, where a control button is either rendering not in dark mode, or has rendering artefacts when rendering in the context of the property grid.
These issues have been pointed out by customers, and are, among others, one of the blockers for GitHub Extensions, which are emotionally discussed on their GitHub issues
https://github.com/gitextensions/gitextensions/issues/9191#issuecomment-2293935942
(and also might even save lives https://github.com/gitextensions/gitextensions/issues/11904)
Note while the latter is certainly an ironic-funny remark, those discussions around dark mode for WinForms app shows the high participation of the community and the desire to make this work, and note also that other issues which have been pointed out in …

[Preview7/Release] Backport 13747 DarkMode: SystemControlButton rendering

---

src/test/unit/System.Windows.Forms/System/Windows/Forms/ButtonPopupAdapterTests.cs

Add unit test file:ButtonPopupAdapterTests.cs for public/protected methods/properties of the ButtonPopupAdapter.cs

Add code coverage for ButtonPopupAdapter

---

src/test/unit/System.Windows.Forms/System/Windows/Forms/CheckBoxBaseAdapterTests.cs

Add unit test file:CheckBoxBaseAdapterTests.cs for public/protected methods/properties of the CheckBoxBaseAdapter.cs

Add code coverage for CheckBoxBaseAdapter

---

src/test/unit/System.Windows.Forms/System/Windows/Forms/CheckBoxFlatAdapterTests.cs

Add unit test file:CheckBoxFlatAdapterTests.cs for public/protected methods/properties of the CheckBoxFlatAdapter.cs

Add code coverage for CheckBoxFlatAdapter

---

src/test/unit/System.Windows.Forms/System/Windows/Forms/ButtonRendererTests.cs

Add unit test file:ButtonRendererTests.cs for public/protected methods/properties of the ButtonRenderer.cs

Add code coverage for ButtonRenderer

---

src/test/unit/System.Windows.Forms/System/Windows/Forms/RadioButtonBaseAdapterTests.cs

Add unit test file:RadioButtonBaseAdapterTests.cs for public/protected methods/properties of the RadioButtonBaseAdapter.cs

Add code coverage for RadioButtonBaseAdapter

---

src/test/integration/UIIntegrationTests/ListViewTests.cs

Fixes #13291 
- Disable unstable case `ListView_Click_On_Second_Column_Does_Not_Alter_CheckBoxesAsync`

Skip unstable test ListView_Click_On_Second_Column_Does_Not_Alter_CheckBoxesAsync

---

src/System.Windows.Forms/PublicAPI.Unshipped.txt
src/System.Windows.Forms/System/Windows/Forms/Controls/PropertyGrid/PropertyGridInternal/DropDownButton.cs
src/System.Windows.Forms/System/Windows/Forms/Rendering/ControlPaint.ModernControlButtonState.cs
src/System.Windows.Forms/System/Windows/Forms/Rendering/ControlPaint_ModernControlButtonRenderer.cs
src/System.Windows.Forms/System/Windows/Forms/VisualStyles/ComboBoxState.cs

Fixes #13766, #13765
- Added a Focused state to the property page's drop-down button.
- Reduces the icon width of the model button.
- The drop-down button of the Property page can be focused under DarkMode
- Yes 
- Minimal
Dropdown arrow and ellipse symbol in PropertyGrid appears larger in DarkMode and the focus indicator (e.g., dotted line or outline) is not visible when navigating to the DropDownButton or Ellipse Button controls by keyboard 
Dark mode on 100% DPI:
Dark mode on 250% DPI:
The dropdown arrow appears normal and it can be focued
100% DPI:
250% DPI:
- manually
- .net 10.0.0-preview.7.25377.103

Add focused state for DropDownButton and reduces the icon width of the dropdown model button

---

src/System.Windows.Forms/System/Windows/Forms/Controls/UpDown/UpDownBase.UpDownButtons.cs

Fixes #13777 
- 
- add hover parameter
- 
- 
- manual
-

fix #13777 : Dark Mode: Divider line between Up and Down buttons is not visible in DomainUpDown/NumericUpDown when mouse-over or click them

---

src/System.Windows.Forms/System/Windows/Forms/Controls/Buttons/ButtonBase.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/ToolStrips/ToolStripItem.cs
src/test/unit/System.Windows.Forms/System/Windows/Forms/BinaryFormat/WinFormsBinaryFormattedObjectTests.cs

Fixes #13801.
Affected Controls are
- `ButtonBase`
- `ToolStripItem`
Fixes:
- `CommandParameter` is now shown in the property browser, and string values can be directly entered.
- If `CommandParameter` is effectively of type `string`, the values are getting CodeDOM-serialized and -deseriaslized.

CommandParameter property: Provide designer support and control CodeDOM serialization

---

src/System.Windows.Forms/System/Windows/Forms/Controls/ListBoxes/CheckedListBox.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/PropertyGrid/PropertyGrid.cs

Fixes #13767
- Add judgement `IsDarkModeEnabled` for ` FocusForeColor` of the **CheckedListBox** and **PropertyGrid**
-  The selected item of the control **CheckedListBox** and **PropertyGrid** can be show clearly under DarkMode
- No
- Minimal
When the application is in Dark Mode, the contrast of focusing items in CheckedListBox/PropertyGrid is insufficient.
The contrast of focusing items in CheckedListBox/PropertyGrid is sufficient
- Manually
- .net 10.0.0-preview.7.25373.104

Add check "IsDarkModeEnabled" for FocusForeColor of the CheckedListBox and PropertyGrid

---

src/System.Windows.Forms/PublicAPI.Unshipped.txt
src/System.Windows.Forms/System/Windows/Forms/Controls/Buttons/Button.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/Buttons/ButtonBase.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/Buttons/ButtonInternal/DarkMode/ButtonDarkModeAdapter.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/Buttons/ButtonInternal/DarkMode/ButtonDarkModeRendererBase.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/Buttons/ButtonInternal/DarkMode/FlatButtonDarkModeRenderer.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/Buttons/ButtonInternal/DarkMode/IButtonRenderer.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/Buttons/ButtonInternal/DarkMode/PopupButtonDarkModeRenderer.cs
src/System.Windows.Forms/System/Windows/Forms/Controls/Buttons/ButtonInternal/DarkMode/SystemButtonDarkModeRenderer.cs

Fixes #13813
Add code to see if BackColor or ForeColor is specified in dark mode, if so then use the specified color, if not then let the renderer decide the color.

fix #13813 : Dark Mode: The ForeColor & BackColor properties are not working for the controls

---

src/test/unit/System.Windows.Forms/System/Windows/Forms/ToolStrip.ToolStripAccessibleObjectWrapperForItemsOnOverflowTests.cs

Add more test for uncovered public method of ToolStrip.ToolStripAccessibleObjectWrapperForItemsOnOverflow.cs file to get a full coverage.

Add unit test for ToolStrip.ToolStripAccessibleObjectWrapperForItemsOnOverflow.cs file

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/DataMemberFieldEditor.cs

Fixes #12571
- When DataSource is null, do not return value immediately but return after the `designBindingPicker` is created.
- The dropdown list of the `DisplayMember` property of the `PropertyGrid` can be expanded when DataSource is null
- Yes 
- Minimal
There no "Open" button for the "DiaplayMember" property and cannot not expand the dropdown list in the PropertyGrid control
The dropdown list of the `DisplayMember` property can be expanded when DataSource is null
https://github.com/user-attachments/assets/5016f6e7-3f1f-4616-8bd0-b34cd2edfdb9
- Manually
- .net 10.0.0-beta.25418.105

Fix 12571 "DisplayMember" property cannot expand

---

src/System.Windows.Forms.Design/src/System/Drawing/Design/CursorEditor.CursorUI.cs

Fixes #9007
- Scale the Cursor Editor's Height as needed.
- Update the `OnDrawItem` method to draw the cursor using the scaled width instead of hard-coding it.
- On High DPI environment, cursor editor in propertyGrid can be scaled well
- Yes
- Minimal
On High DPI environment, cursor editor in propertyGrid is not scaled well
On High DPI environment, cursor editor in propertyGrid can be scaled normally
- Manually
- .net 10.0.0-rc.1.25418.105

Scale the Cursor editor according to DPI

---

src/System.Windows.Forms/System/Windows/Forms/Control.cs

Fixes #13835
When a control (e.g., MainObject) references another control (ExternalObject) from a separate assembly (ExternalAsm), and that assembly is missing at runtime, the constructor of MainObject fails. However, the .NET runtime still attempts to call `Dispose()` on the partially constructed control. Inside `Control.Dispose`, accessing `ContextMenuStrip` triggers a `NullReferenceException` because `Properties` is not initialized.
- Added a defensive null check around `ContextMenuStrip` access in `Control.Dispose()`
- Replaced direct property access with `Properties?.TryGetValue(...)` to ensure safe event unsubscription
- This change ensures that `Control.Dispose()` can safely execute even when the control was never fully constructed.
- Yes
- Minimal
Run the attached project …

Fix Control.Dispose crash when dependent UserControl fails to load due to missing assembly

---

src/System.Windows.Forms/System/Windows/Forms/Printing/PrintPreviewControl.cs

Fixes #13861 
-
- [pr #12368](https://github.com/dotnet/winforms/pull/12368) is to fix the High Contrast issue but omitted the case that a custom color is set.
- if ForeColor is set then use that color
- 
- low
- 
- manual
-

fix #13861 The custom ForeColor set on PrintPreviewControl is not rendered correctly

---

src/System.Windows.Forms.Design/src/System/Windows/Forms/Design/AnchorEditor.AnchorUI.cs

Related #13830
-  Update the `InitializeComponent` method to draw the Anchor Editor using the scaled size instead of hard-coding it.
-  On High DPI environment, Anchor editor in propertyGrid can be scaled well
-  No
- Minimal
In 300% DPI:
In 300% DPI:
-  Manually
- .net 10.0.0-rc.1.25454.102

Scale the Anchor editor according to DPI

---

src/System.Windows.Forms.Design/tests/UnitTests/System/Windows/Forms/Design/DocumentDesignerTests.cs

- Add unit test DocumentDesignerTests.cs for some methods of the DocumentDesigner.cs file. Still has some methods not covered successfully.

Add unit tests for DocumentDesigner.cs file

---

eng/pipelines/build.yml

Added ConnectedPMEServiceName for MicroBuild signing in CI builds
Reference: https://dev.azure.com/devdiv/DevDiv/_wiki/wikis/DevDiv.wiki/46279/Real-signing-with-PME-Enforcement

Add ConnectedPMEServiceName for MicroBuild signing in CI builds

---

eng/pipelines/build.yml

Conditional causes build to fail if invoked manually. It works for automatically invoked CI builds.
This condition is not required.

Remove conditional for ConnectedPMEServiceName
